### ISSUE TITLE
Revisit ResizeObserver usage in horizontal overflow once all browsers support

### ISSUE THREAD

**Issue by nalogiudice** [microsoft/fast#1142]
ResizeObserver does not have full support as of yet, but is the best option for getting the desired functionality in the horizontal overflow overflow change callback.
Revisit and fix once available.

See current bugs:
- [https://bugzilla.mozilla.org/show_bug.cgi?id=1272409](https://bugzilla.mozilla.org/show_bug.cgi?id=1272409)
- [https://bugs.webkit.org/show_bug.cgi?id=157743](https://bugs.webkit.org/show_bug.cgi?id=157743)

**Comment by chrisdholt** [comment]
closed with #3517
