### ISSUE TITLE
Justify content is missing from align in Fast Form

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#1275]
**Describe the bug; what happened?**
We only have right, center and left align in horizontal align in Fast Form. Justify content is missing

**Current horizontal align in build:**
![image](https://user-images.githubusercontent.com/37851214/50865409-7c01fc00-135a-11e9-91b0-871c13bb9da7.png)

**Example from design:**
![image](https://user-images.githubusercontent.com/37851214/50864467-fd578f80-1356-11e9-8dff-e9e87e4132d4.png)

**Comment by chrisdholt** [comment]
Can you provide more insight into the details of this bug? I'm unclear on what is being asked here and what the issues are. Can you elaborate so others can better understand how to solve this? At this point, I don't have enough information to keep this open.
