### ISSUE TITLE
Document handled vs unhandled prop guidance 

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#1399]
We need clear documentation on when a prop is handled vs unhandled. Documentation should clearly communicate the criteria that makes a prop handled:
- Any HTML attribute name that is required (in general we should avoid HTML attribute names)
  - id, title, etc 
- Any prop name that is not a valid HTML attribute
- Any HTML attribute not applied to the HTML element populated with `unhandledProps()` - for instance, `value` of checkbox where the root of the `Checkbox` component is actually a `div`

We should also clearly document the unhandledProps()` mechanism and it's intended use.

**Comment by chrisdholt** [comment]
closed with #3517
