### ISSUE TITLE
Add optional direction prop to Pivot and Horizontal overflow

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#1438]
**What feature are you requesting?**
We should add am optional direction prop to components that logic requires knowing the current language direction. If the optional prop is not passed we will continue to use the `getLTR()` function but if it is we no longer need to use the expensive `getComputedStyle()` function this makes it a none braking change.

**What would be the benefit of adding this feature?**
Adding this prop would allow us to no longer rely on `getComputedStyle()` which is a very expensive call.

**Comment by chrisdholt** [comment]
@nalogiudice if you are fairly far along on this, can you give a quick update on the status? If not, can you un-assign yourself so it shows as a fully open issue?

**Comment by chrisdholt** [comment]
@scomea Is this related to things you are investigating with horizontal overflow?

**Comment by scomea** [comment]
@chrisdholt Yes, related.  Not sure if the prescription is the way to go but will look into it along with other rtl behavior changes.

**Comment by scomea** [comment]
Question - if we add this prop should we also write the dir value to the dom attribute of the root component?

**Comment by chrisdholt** [comment]
Adding @microsoft/fast-dna-collaborators for inpu

**Comment by janechu** [comment]
@scomea I believe so, because that will result in the other DOM changes we expect such as text alignment

**Comment by chrisdholt** [comment]
closed with #3517
