### ISSUE TITLE
Unable to pass jssStyleSheet or className overrides to children components in AutoSuggest component

### ISSUE THREAD

**Issue by danavil87** [microsoft/fast#1574]
**Describe the bug; what happened?**
Currently in order to pass overrides to the TextAction layer you need to provide an override for inputRegion and then you could provide the jssStyleSheet override in your override function.

This lets you provide overrides for the parent level (AutoSuggest) and the TextAction level but if you need to do any additional overrides to say TextField (child of TextAction) there is no way to do so.

Also, this probably is the case for other components as well but calling this one out since it happens to be the one I'm using and having the issue with.

**Comment by chrisdholt** [comment]
closed with #3517
