### ISSUE TITLE
Add support for lazy loaded slides in Carousel component

### ISSUE THREAD

**Issue by prabashn** [microsoft/fast#1649]
**What feature are you requesting?**
Two features:
1) Need the ability to lazy load components in the Carousel component
2) Need a notification event from Carousel when the slide changes

**What would be the benefit of adding this feature?**
The above features would be required for the infopane experience for MMX/DHP/NTP to avoid the perf penalty you get with large infopanes. The infopane currently loads in ContentPreview and soon complex slides (composed of multiple content preview), which all end up requesting the network to load their experience data. As the infopane author, I want control over how my slides are instantiated so that we don't take up resources to load invisible slides in the infopane that can severely effect the performance of the rest of the page (depending on how big and complex the infopane content is)

**What solution would be ideal for you?**
The Carousel already takes in render props as form of a list of callbacks that returns a React.ReactNode element for each slide. A simple prop to enable lazy loading would go a long way to prevent rendering of the UI until after the carousel changes the view to a specific slide. This should give us control over the rendering side of things. 

In addition to the rendering however, I also want to be able to preload the next slide's experience data when the active slide changes (or else user will have to wait until the network call resolves to render the next slide when they go to the next slide). In order to implement this type of control we also need a notification event of when the active slide changes.

**What alternatives have you considered?**
As it is, we don't have much flexibility on how to achieve this in a good way.

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by prabashn** [comment]
@nicholasrice, do you know the ETA for this task?

**Comment by chrisdholt** [comment]
closed with #3517
