### ISSUE TITLE
Add ref-forwarding to all Base and MSFT components

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#1668]
It looks like React is deprecating `ReactDOM.findDOMNode`: https://reactjs.org/docs/react-dom.html#finddomnode

Our current reccomended to retrieve a DOM node is through that method, so I think we need to integrate ref forwarding into all of our components. While this should be pretty transparent for many components, there are several components that provide public properties on class instances, which we will need to provide alternate solutions for.

**Comment by shauntc** [comment]
+1

**Comment by chrisdholt** [comment]
I believe this is slated for our next major version, not stale

**Comment by chrisdholt** [comment]
closed by #3517
