### ISSUE TITLE
Fix "method_complexity" issue in packages/fast-colors/src/palette-extractor.ts

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#1677]
Function `extractPalette` has a Cognitive Complexity of 31 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-colors/src/palette-extractor.ts#issue_5cb78212833d5e000100047a

**Comment by eigenvector32** [comment]
Note that this is a very perf-sensitive chunk of code. Any refactoring that tries to simplify it should take care not to excessively impact performance.

**Comment by nikolaykrashnikov** [comment]
can i take this?

**Comment by QuantumlyTangled** [comment]
The [link](https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-colors/src/palette-extractor.ts#issue_5cb78212833d5e000100047a) does not work anymore. Is there a working version?

**Comment by chrisdholt** [comment]
Closing this as both stale and obsolete. Per the comment from 2019, this is by-design for perf reasons. While complex, it serves a purpose.
