### ISSUE TITLE
Fix "similar-code" issue in packages/fast-components-styles-msft/src/utilities/color/neutral-fill-card.ts

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#1707]
Similar blocks of code found in 4 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-styles-msft/src/utilities/color/neutral-fill-card.ts#issue_5cbdfc35fadd0300010004d1

**Comment by chrisdholt** [comment]
closed with #3517
