### ISSUE TITLE
Add touch gesture in carousel

### ISSUE THREAD

**Issue by alnw** [microsoft/fast#1710]
**What feature are you requesting?**
Please support swiping (touch on mobile) for Carousel component

**What would be the benefit of adding this feature?**
I believe most component should consider mobile platform. When carousel used in mobile, user naturally just use touch to swipe forth and back to view the content in carousel.

**Comment by chrisdholt** [comment]
@SethDonohue Have you considered this for the Carousel proposal you have written up? If so, can you link to this?

**Comment by chrisdholt** [comment]
closed with #3517
