### ISSUE TITLE
ListboxItem and derived types should use a local ID and not entangle with the html ID attribute

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#1713]
Feedback from devs suggests that requiring listboxItemId's to be unique across the application is unnecessarily burdensome.  At first glance, it looks like we really only need these id's to be unique in the context of a particular Listbox or derived type like Select.

Assuming we encounter no complicating issues I propose that we:
- rename the listbox item id prop to something else that does not imply that it is the same as the html id attribute, I'm thinking "ItemId"?

- we do not apply this value to the html id attribute of listbox items and derived types, this identifies data and not a particular html element.

**Comment by chrisdholt** [comment]
closed with #3517
