### ISSUE TITLE
Add autocomplete to property keys in the CSS property editor

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast#1790]
**Interaction when typing out a property key**

- While typing the key, a drop down menu appears with available keys to choose from. 
(The available keys displayed, in the menu, will base on the letter you type. The list is in alphabetical order.)

- Using the up and down arrows will move focus up and down the menu.

- Once the desired key is focused, you can press `enter` or `tab` to select it.

**Comment by janechu** [comment]
Closing this as the CSS property editor is being removed in #4092 in favor of the solution in #3773
