### ISSUE TITLE
Add autocomplete to property values in the CSS property editor

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast#1791]
**Interaction when typing out a property value**

- While typing the value, a drop down menu appears with available values to choose from. 
(The available values displayed, in the menu, will be listed in alphabetical order.)

- Using the up and down arrows will move focus up and down the menu.

- Once the desired value is focused, you can press `enter` or `tab` to select it.

**Another option on choosing a value without typing it**

- After a user selects a key, the drop down menu for the value will automatically be opened, displaying all the available values pertaining to the key selected.

**Comment by janechu** [comment]
This will use the same solution as the `Form` via #2346
