### ISSUE TITLE
Change the hover icons on Navigation

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#1932]
The `Navigation` component should show icons on hover that correspond with user expectations. Use the [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) pointer styles.

Namely:
- A not-allowed cursor when dragging over an item that is not children or a childItem
- ~~A pointer when not dragging over an item that is not children or a childItem~~(already completed)

**Comment by chrisdholt** [comment]
@khamudom are you working on this?

**Comment by janechu** [comment]
A different solution has emerged where items will be dropped on the last droppable location.
