### ISSUE TITLE
No way to render unhandled props to Radio button input

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast#1968]
**What feature are you requesting?**
Trying to render some supplementary `data-` attributes to a `<Radio />` component. The unhandled props are rendered to the wrapper div (as expected, since unhandled props are rendered to the outermost element of the component). There is no way to render props onto the radio input itself.

It would be useful to be able to render attributes to the input element.

**What would be the benefit of adding this feature?**
Render supplementary data attributes to the input element. Our requirements have input changes globally tracked, the inputs are identified uniquely by data attributes.

**What solution would be ideal for you?**
Maybe an extra prop to pass attributes to radio input? I.e. something like `<Radio inputUnhandledProps={{ "data-my-input-data": "some value" }} />`

**Comment by nicholasrice** [comment]
Related to #1968

We've been discussing a way to inject unhandled props to sub elements as you're suggesting, likely aligning to elements exposed in class-name-contracts

**Comment by hchokshi** [comment]
@nicholasrice good to hear! :)

> Related to #1968

Just a note that the related issue you mentioned is this one.

**Comment by nicholasrice** [comment]
hah good catch - related to #1834 ;)

**Comment by hchokshi** [comment]
Refresh stale status - this is still present.

**Comment by chrisdholt** [comment]
Still tracking for vNext.

**Comment by hchokshi** [comment]
We have also run into this on the `<Toggle />` control. Do you want to use this issue to track this entire class of request, or should I open another one to track for `Toggle`?

**Comment by chrisdholt** [comment]
@hchokshi the issue is global so it's like more that we need an issue that represents the feature request. Feel free to file that as a "catch-all", or I can follow-up and file it here in a bit.

**Comment by chrisdholt** [comment]
closed with #3517
