### ISSUE TITLE
Pipeline update to prevent erroneous commit messages

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#2016]
There should be an update to the pipeline when PRs are created that should check to see if:

1. There is one commit then that commit message should include the fix/feat/chore and other conventional commit wording
2. There are multiple commits then the PR title should include the fix/feat/chore and other conventional commit wording

This would prevent the merging of commits that do not follow the pattern and ensure correct changelogs.

As a secondary ask, this should also:
1. Automatically merge PRs once they meet the policies
2. Automatically rebase PRs if they fall out of date
3. Use the PR title as the commit title and the PR body as the commit body

Additional notes:
It might be prudent to accomplish this using a Github App such as https://github.com/palantir/bulldozer

**Comment by chrisdholt** [comment]
@SethDonohue looking into this

**Comment by janechu** [comment]
Resolved by https://github.com/microsoft/fast/pull/3500, the secondary asks to automatically rebase and merge are still being considered but not worth investing time into currently.
