### ISSUE TITLE
Add range form field

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2053]
Add an editor for a numeric range that can be used in FAST tooling form.

![Range data](https://user-images.githubusercontent.com/47367562/62159310-3725be80-b2c6-11e9-8ecc-9db872db1552.png)

**Comment by janechu** [comment]
This is now no longer necessary for us to create as a custom form control within tooling as the `<fast-slider>` from `@microsoft/fast-components` can be used.

**Comment by bheston** [comment]
The intent of this was to pair the slider with the numeric input. I believe slider does not have this option, so it would still be relevant, but without a specific use case in mind currently I'm fine with closing this.
