### ISSUE TITLE
Need to interpret strings in box shadow component

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2055]
**Describe the bug; what happened?**
We need regEx to read values from a string on box shadow so editing HTML directory does not get the component out of sync.

Should allow for outside manipulation of internal box shadow CSS implemented in #2047

**Comment by chrisdholt** [comment]
@khamudom @janechu @eljefe223 will this still be an issue with the work happening right now on the standard control plugin conversion?

**Comment by khamudom** [comment]
@chrisdholt This issue should still be addressed, but it can be done after the conversion work.

**Comment by chrisdholt** [comment]
closed with #3517
