### ISSUE TITLE
Remove lodash get from class names in the tooling components

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#2171]
Convert the managed classes in the tooling components to use the `classNames` utilities that the `@microsoft/fast-components-base-react` uses so that there is not so much over-use of the lodash `get` utility.

`classNames` can be imported as a secondary import from the `@microsoft/fast-web-utilities` package.

This should improve perf of the tooling.

**Comment by nicholasrice** [comment]
`managedClasses` should be added to the `defaultProps` object:

```
public static defaultProps = { managedClasses: {}}
```

**Comment by janechu** [comment]
This has been done on the `Form` component with #2280, still needed for the `Navigation` and `NavigationMenu`.

**Comment by Grommers00** [comment]
I'll take a look for Navigation and NavigationMenu!

**Comment by chrisdholt** [comment]
closed by #3517
