### ISSUE TITLE
Add custom spin buttons to number field

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#2202]
Currently the browser adds inner spin buttons to the number field input type. These spin buttons cannot be styled easily as they are part of the shadow DOM. This creates problems as the spin buttons take the browser styling and cannot be styled to align with the design system. Considering this, the spin buttons should be hidden for the time being.

I think it's worth a discussion as to whether or not we should add custom spin buttons to the number field component.

Outstanding questions:
- What are the perf tradeoffs for including this behavior?
- Should this be done at the base or MSFT level? 
- Is work currently being done on the browser side to expose similar functionality?
- Should this be a render prop approach? This would allow users to opt into the behavior by passing their own spin buttons. We could build out the spin button as components which would make for an easier implementation.

**Comment by mdtauk** [comment]
WinUI is in the process of adding a NumberBox control to its Xaml library.  There is a focus on it being touch friendly, but the same design could work for the Fast DNA Number Input Field.

![image](https://user-images.githubusercontent.com/7389110/63986740-35ba0280-cacd-11e9-9b21-400e996fcb15.png)

**Comment by chrisdholt** [comment]
Thanks for the insight @mdtauk! I think we'd want this to support touch for sure. I'm leaning towards implementing a spin button specific to the increment and decrement functionality which the number field could optionally be composed with: https://w3c.github.io/aria-practices/#spinbutton

**Comment by mdtauk** [comment]
Yes, it should conform to the W3C expected behaviour, but I don't think that prohibits aligning the Up and Down buttons horizontally, instead of stacking them vertically, where there is not a lot of height available in the TextField.

**Comment by bheston** [comment]
Here is the design we proposed for the native platform controls update. We had to hold on it for now as the overlay proved to be difficult.
My goal was to maintain the up down visual relationship while supporting touch or generally larger hit points.
On the platform control we needed to maintain the narrow width due to an incredibly narrow 45px default field width.
![image](https://user-images.githubusercontent.com/47367562/64041733-18108b80-cb15-11e9-84e5-10ec39749a1c.png)

**Comment by bheston** [comment]
@mdtauk for the WinUI control did you consider arrows instead of chevrons? Obviously there are lines and another "up" icon in the design you shared, but it might not be as discernible from a select box. Perhaps + and - would be good universal options too.

**Comment by mdtauk** [comment]
I only added to the discussion and design ideation for the WinUI NumberBox control that is now being built. I like that flyout approach, but there would need to be some thought as to focus and keyboard navigation, as well as accessibility concerns.

In the designs I worked on, it was mainly looking at other Windows Spinner Buttons, and making them more touch friendly.  So side by side made sense, and they all used chevrons.

I mocked up a few other arrangements too

![spin buttons alt forms](https://user-images.githubusercontent.com/7389110/64043768-27b3c280-cb5d-11e9-9883-b0733ece0321.png)

And to try to make the controls clear as to their behaviour, I also suggested a design language for Pickers, Combo Boxes, and Input Boxes

![Comparing Similar Controls](https://user-images.githubusercontent.com/7389110/64043930-8a0cc300-cb5d-11e9-98eb-b721dfaa4044.png)

**Comment by KevinTXY** [comment]
> for the WinUI control did you consider arrows instead of chevrons? Obviously there are lines and another "up" icon in the design you shared, but it might not be as discernible from a select box. Perhaps + and - would be good universal options too.

When I was developing NumberBox we decided that we'd include DecrementIcon and IncrementIcon IconSource properties to give devs easy control over this - this is [reflected in the spec](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/savoyschuler/numberbox/active/NumberBox/NumberBox.md) though not yet implemented.

**Comment by mdtauk** [comment]
@KevinTXY  Has the WinUI Design team taken a pass at the NumberBox control design yet, or is it still in the building functionality stage?

The Fabric Web team, are using Chevrons, stacked vertically, with no allowance for Touch sadly.
![image](https://user-images.githubusercontent.com/7389110/64080686-eb17d080-ccee-11e9-8d15-b2b64c74ee18.png)

If a consensus with the Fluent Design team can be reached, I hope all frameworks will adopt it, and maybe even backport it to WPF and the CommonControls in Win32

**Comment by KevinTXY** [comment]
I wouldn't know for certain but if I remember correctly a design review was a next step. Stepping button stylings especially in regards to localization and accessibility were major components of our discussions early in the summer. We picked a compromise of being friendly towards retemplating/restyling that was good for development and while i'm sure the issue is malleable that'd be something for Savoy to comment on. 

Designing this functionality in a way that adapts towards several input types (including touch and gamepad) as well as vastly different screen sizes while still being multi-purpose is definitely non-trivial.

**Comment by mdtauk** [comment]
> I wouldn't know for certain but if I remember correctly a design review was a next step. Stepping button stylings especially in regards to localization and accessibility were major components of our discussions early in the summer. We picked a compromise of being friendly towards retemplating/restyling that was good for development and while i'm sure the issue is malleable that'd be something for Savoy to comment on.
> 
> Designing this functionality in a way that adapts towards several input types (including touch and gamepad) as well as vastly different screen sizes while still being multi-purpose is definitely non-trivial.

I will include @SavoySchuler  here just so he will be aware of the conversation.  If consistency is part of the aim for WinUI, then talking to FastDNA and Fluent Web's designers could be useful.

**Comment by chrisdholt** [comment]
A new Proposal for spin buttons has started up at #2230

**Comment by chrisdholt** [comment]
@EisenbergEffect would prefer to close this related to #3517 as we don't have number field yet. I'm happy to create a new task tracking the creation of that control; as it stands, this issue seems like it would be confusing as the control does not exist.
