### ISSUE TITLE
*DRAFT* Create a Carousel component (AKA Slide Show, Image Rotator)

### ISSUE THREAD

**Issue by SethDonohue** [microsoft/fast#2226]
### *WIP* Feedback encouraged
# Carousel

## General
 
Carousels are used for rendering a collection of items showing one item at a time. Examples of use can be for scrolling news, image galleries, and featured articles.

**Where will it be added?**
`@microsoft/fast-components-react-base`

**User Stories:**
* Chad is looking for a sweet new background for his desktop. He navigates to his favorite ultra-high-uber-def desktop art website, where he searches for "sports" and is displayed a rotating selection of images matching his search.

* Zee needs to get the new beez-kneez gadget for their phone. They navigate to their favorite e-commerce site and are greeted with a rotating banner of ads showcasing the newest items.

**Accessibility**
Refer to *w3c* standards for accessibility:
https://www.w3.org/WAI/tutorials/carousels/#what-makes-a-carousel-accessible
https://www.w3.org/WAI/tutorials/carousels/#why-is-this-important

**Functional Requirements:**
* Rotation autoplay should start on page load (default to true)
* Rotation should stop when the keyboard focus enters the carousel, and does not restart unless the user explicitly requests it to do so.
* Rotation should stop when the mouse is hovering over the carousel.
* A user should be able to cycle forward and backwards through the slides.
* A user should be able to stop and start the rotation.
* A user should be able to interact with content in each slide.
* Each slide should be pickable by a control or group of controls.

**Technical Requirements:**
* The component should have an autoplay prop to control whether it starts rotation on page load or not.

**API**
`items` array of slides, each slide has content and ID
`label` string
`autoplayInterval` *optional*, number, to control the speed of slide rotation
`autoplay` *optional*, boolean, set whether autoplay happens on page load, defaults to false.
`loop` *optional*, boolean, set whether looping happens on page load, defaults to true.
`activeId` *optional*, string, the current active slide ID
`nextFlipper` *optional*, (onClick, className?: string) => React.ReactNode, render prop with click handler callback
`previousFlipper` *optional*, (onClick, className?: string) => React.ReactNode, render prop with click handler callback

**Implementation Example:**
```jsx
<Carousel
    label={"carousel of items"}
    items={[
        {
                id: uniqueId(),
                content: (className?: string): React.ReactNode => <Slide className={className} {...props} />,
        },
        {
                id: uniqueId(),
                content: (className?: string): React.ReactNode => <Slide className={className} {...props} />,
        },
    ]}
    autoplay={true}
    autoplayInterval={10}
/>
```

**Comment by chrisdholt** [comment]
@microsoft/fast-dna-collaborators for awareness.

**Comment by SethDonohue** [comment]
@chrisdholt Ok to close this since it is for the react version? Assuming we are no longer building *new* things for the react side.

**Comment by chrisdholt** [comment]
> @chrisdholt Ok to close this since it is for the react version? Assuming we are no longer building _new_ things for the react side.

@SethDonohue I think we can close _this_, I'll do so now :).
