### ISSUE TITLE
*DRAFT* Radio group as a base component

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast#2229]
### Radio group
*WIP - Feedbacks are welcome on this proposal*

**Where will it be added?**
@microsoft/fast-components-react-base

The goal of having radio group is to have a component for the radio-button. Currently, we are able to see how a single radio button behaves, from rest to hover and checked to unchecked. Most real world applications will have two or more radio buttons together and radio group will provide the ability for authors to add a group of radio buttons to their application.

**Design pattern**
Radio group is a collection of radio inputs, where only one input can be checked or selected at a time. In some implementations, the radio buttons may be unchecked, on initial load, to force users to check one of the buttons before moving past a certain point in the workflow. 

**Accessibility**
Radio group should also be accessible, out of the box, for keyboard users and screen readers.

*Keyboard focus* - the behavior when radio group is not in a toolbar.
- TAB and SHIFT + TAB	
Move focus into and out of the radio group.	
When focus moves into a radio group:
· If a radio button is checked, focus is set on the checked button.
· If none of the buttons are checked, focus is set on the first radio button in the group.
- SPACE
Checks the focused radio button, if it is not already checked.	
- RIGHT and DOWN arrows
Moves focus to the next radio button in the group	
While arrowing through:
· Uncheck the previously focused button, and check the newly focused button. 
· If the focus is on the last button, focus moves to first button of the group.
- LEFT and UP arrows
Moves focus to the previous radio button in the group, 	While arrowing through

*Screen reader*
How the elements, being read, will vary between screen reader technology. 
VoiceOver, Narrator, or NVDA.

**Propose API**
- selectedId:string	
Id used to select a radio button
- items:(classname?: string) => React.ReactNode	
Content items in the radio group
- onChange:(event?: React.ChangeEvent<HTMLInputElement>) => void	
To check the onChange of the selected item
- labelledBy:string	
aria-label attribute to link radio group to another element that will be the label of the group.

**Comment by chrisdholt** [comment]
@microsoft/fast-dna-collaborators any feedback on this proposed new base component?

**Comment by chrisdholt** [comment]
I think there's a good call out here for the `RadioGroup` keyboard interaction when it's not in a toolbar.
> Keyboard focus - the behavior when radio group is not in a toolbar.

Should we support the alternative keyboard behavior as defined by the W3C specification for when this is in a toolbar?
https://w3c.github.io/aria-practices/#for-radio-group-contained-in-a-toolbar

@khamudom I would expect children instead of items in your proposed prop contract. I don't see a benefit to passing a render prop in that scenario. I'd see this more similar to how we've implemented context menu and tree view (currently in review).

**Comment by chrisdholt** [comment]
closed with #3517
