### ISSUE TITLE
*DRAFT* Create spin button as base component

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2230]
### Spin Button
WIP - Feedbacks are welcome on this proposal

**Where will it be added?**
`@microsoft/fast-components-react-base`

Spin buttons are used to allow the user to increment or decrement a value from a range of numeric values. Spin buttons are used in coordination with a numeric input field to display that selected value.

![image](https://user-images.githubusercontent.com/37851214/64547887-6c202a80-d2e2-11e9-819d-b42eb90173b8.png)

**Problem**
Currently there is no way to easily style the stock spin buttons. Traditionally spin buttons are stacked and placed on the right of a numeric input field. There is some interest in exploring new designs that break this pattern.

![image](https://user-images.githubusercontent.com/37851214/64548888-63305880-d2e4-11e9-9fd5-0ed916ae3ecf.png)

**API** - As grouped buttons
`IncrementGlyph` render prop
`DecrementGlyph` render prop
`OnIncrement` increment call back
`OnDecrement` decrement call back

**API** - As Single button
`glyph` increment / decrement render prop
`OnClick` increment / decrement call back

**Accessibility**
Numeric inputs increment and decrement on keyboard up and down arrows. Spin buttons should not be focusable.

**Comment by mdtauk** [comment]
If the Spin buttons are split between the left and right of the control, the number value should probably be centred.

![image](https://user-images.githubusercontent.com/7389110/64617407-5724c380-d3d6-11e9-9f92-de1d354d4c7c.png)

**Comment by chrisdholt** [comment]
@bheston do you have any design feedback for this? @microsoft/fast-dna-collaborators as an FYI on this proposal

**Comment by chrisdholt** [comment]
related design feedback for @mdtauk is also in #2202

**Comment by bheston** [comment]
> do you have any design feedback for this?

From a base component perspective this sounds good to me. Regarding styling, I still favor the flyout design for touch and keyboard use, acknowledging that some details of the interaction need to be tested and defined more. I agree with not allowing focus on the arrow buttons.

**Comment by chrisdholt** [comment]
closed by #3517
