### ISSUE TITLE
Divider line thickness not consistent at 150% scale

### ISSUE THREAD

**Issue by adkaufm** [microsoft/fast#2231]
The thickness of the Divider component is not consistent when the page is scaled to 150%. 

1. Go to https://explore.fast.design/components/context-menu
2. Add two dividers to the context menu using the "children" menu
3. Zoom in the page to 150% or set your windows scale factor to 150% in Windows settings
4. Observe that one divider line appears to be 2 pixels wide, while the other is only 1 pixel.

I would expect that the thickness would always be exactly one pixel.

![image](https://user-images.githubusercontent.com/44783604/64553317-033eaf80-d2ee-11e9-8174-04e996265b1d.png)

This issue is observed on Windows in both Chromium-Edge and retail Chrome. It seems to be a renderer bug, but I found a fix that works. Setting the border width to 1/window.devicePixelRatio makes the line always 1 pixel. However this has to be done at render time because devicePixelRatio might change.

Overall, I'm not sure it makes sense to fix this in the fast component. Please let me know what you guys think. Maybe providing a utility function, or adding a prop like adjustForScaleFactor or something.

**Comment by chrisdholt** [comment]
Thanks @adkaufm - Ideally I'd love this to get fixed on the rendering side of things, but that can obviously be complex. Do you know if this repro's at all in non-chromium browsers? My immediate thought is in scenarios where this is important a user can always pass the style in as an unhandled prop which would cause it to inline to the DOM and take precedence. 

Pinging other @microsoft/fast-dna-collaborators for their thoughts on the above as well.

**Comment by adkaufm** [comment]
Right - I added the fix with an unhandled prop every time we use Divider. And I agree that a fix on the renderer would be ideal here. I just thought to raise the issue here given that Chrome is such a big share of the market. And keep in mind many devices are automatically at 150% scale (surface products for example), so it will repro a lot.

**Comment by chrisdholt** [comment]
> Right - I added the fix with an unhandled prop every time we use Divider. And I agree that a fix on the renderer would be ideal here. I just thought to raise the issue here given that Chrome is such a big share of the market. And keep in mind many devices are automatically at 150% scale (surface products for example), so it will repro a lot.

For sure, I think this is a valid scenario and worth the conversation.

**Comment by eljefe223** [comment]
Edge:
![image](https://user-images.githubusercontent.com/37851214/64555194-ad6c0680-d2f1-11e9-8b49-f4162ae27d8c.png)

Chrome:
![image](https://user-images.githubusercontent.com/37851214/64555232-ba88f580-d2f1-11e9-8860-320058ee50c5.png)

Safari: (no Repro)
![image](https://user-images.githubusercontent.com/37851214/64555413-1ce1f600-d2f2-11e9-81d7-06a24bf187ea.png)

Firefox: (no Repro)
![image](https://user-images.githubusercontent.com/37851214/64555589-82ce7d80-d2f2-11e9-8e84-77aa0b9887d6.png)

**Comment by chrisdholt** [comment]
@adkaufm there could be an interesting experiment here. What would happen to all FAST components if we set the design system system value for certain things to a value derived from `window.devicePixelRatio`? I think we'd need to look at similar things, but outline width, and focusOutlineWidth are two that come to mind. It could be an interesting experiment to see if that would help or hurt the issue we're having with subpixel rendering here.

@bheston for awareness

**Comment by chrisdholt** [comment]
closed with #3517
