### ISSUE TITLE
Various issues in Select component

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2237]
**Describe the bug; what happened?**
Currently seeing crashed in `<Select/>`

1. Cannot read property 'map' of undefined `listbox/listbox.js (377:14)`
2. items.map is not a function `listbox/listbox.js (377:14)`

**What are the steps to reproduce the issue?**

Below is a link to a prototype.

https://stackblitz.com/edit/react-8fiuom?file=index.js

1. To repro Cannot read property 'map' of undefined simply click the "Add Robot" button
2. To repro items.map is not a function simply remove `selectedItems` on `line 49`

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/37851214/64713975-afa99e80-d472-11e9-835c-e38de55c4527.png)

![image](https://user-images.githubusercontent.com/37851214/64714028-c3550500-d472-11e9-84d7-6edcb0ca0318.png)

**Comment by chrisdholt** [comment]
@scomea is this still a known issue?

**Comment by chrisdholt** [comment]
Marking as needs more info - @eljefe223 or @scomea are either of you aware if this is still an issue and what expected behavior would be?

**Comment by chrisdholt** [comment]
closed by #3517
