### ISSUE TITLE
Add "Show More" Feature

### ISSUE THREAD

**Issue by tvalipour** [microsoft/fast#2240]
**"Show More" feature:**
Show more feature allows you to display list of items in batches. This component will initially display a few items and hide the rest of them, as user click "Show More" button, more items will appear on the screen.
It provides better user experience on mobile devices by loading content on demand as opposed to having infinite scrolling. It can also be used in place of pagination combined with lazy loading.

**Design Pattern:**
"Show More" component is a wrapper around the list of items. On first load it would display the initial number of items and as user click the button, more items will be displayed until it reaches the limit (passed in as properties) or end of the list. When all the items are displayed the show more button would be hidden from user.

**Accessibility:**
Show More button feature should be accessible for keyboard and screen reader users.

**Component detail:**
The following properties can be configured:
	• Number of items on each load
	• Number of initial items
	• Maximum number of items (it's used when we want to have limit on number of items displayed)
	• Text to be displayed on the button
For keyboard user click will be provided on enter key

**Comment by connorjsmith** [comment]
Does this better align with the Disclosure pattern?
https://w3c.github.io/aria-practices/#disclosure

> A disclosure is a button that controls visibility of a section of content. When the controlled content is hidden, it is often styled as a typical push button with a right-pointing arrow or triangle to hint that activating the button will display additional content.

**Comment by chrisdholt** [comment]
@tvalipour can you provide a bit more insight into what exactly the proposed accessible interaction model is for this? If it's not a feed, is it [disclosure](https://w3c.github.io/aria-practices/#disclosure)? Would be great to see a proposed API as well as how one might instantiate the component.

**Comment by chrisdholt** [comment]
Closing as this is stale and in favor of #3731 as a long-term solution for the same pattern - "disclosure".
