### ISSUE TITLE
Add build info to all FAST apps

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2257]
**What feature are you requesting?**
Let's have some way to see basic build information in the tools; at least the build date, but possibly a build number if that's useful, or version numbers of component libraries.

**What would be the benefit of adding this feature?**
As the number of apps and deployment location grows, it's increasingly harder to know what's current and how current it is. We need to know that if we direct a partner somewhere, that it's up to date.

**What solution would be ideal for you?**
Any of these options would be a good start:
- A url that's not even linked or indexed, like /ver.txt
- A tooltip over the product header
![image](https://user-images.githubusercontent.com/47367562/65341050-59c8ab00-db84-11e9-9332-a4610c291a55.png)
- A question mark icon in that same space, with tooltip or more detailed flyout

**Comment by chrisdholt** [comment]
As we've essentially deprecated the explore site in practice (fast-components is deprecated) and we've got things setup for automated deployments I'm going to close this stale issue out. If we find we'd like to add the feature in the future, we can open the issue (or just contribute the work) .
