### ISSUE TITLE
Add density control to Storybook component explorer

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2258]
**What feature are you requesting?**
Ability to control design system density in Storybook:
![image](https://user-images.githubusercontent.com/47367562/65345704-ba111a00-db8f-11e9-9792-3edd02a08de1.png)

**What would be the benefit of adding this feature?**
It's a core aspect of the components and should be tested when working on updates.

**What solution would be ideal for you?**
Add a slider, drop list, or any other reasonable control for testing the 7 supported density steps.

**Comment by chrisdholt** [comment]
Closing this in relation to the components as that pacakge has been deprecated and our storybook primarily exists now to test foundation components.
