### ISSUE TITLE
Update glyphs to use currentcolor

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2260]
**What feature are you requesting?**
In many places we keep `color` and `fill` synchronized because svg icons generally need a fill that's the same as related text's foreground color. Set the fill of all svg paths to [currentcolor](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentColor) and remove the fill attributes in the stylesheets.

**What would be the benefit of adding this feature?**
We can simplify our stylesheets, including high contrast overrides.

**Comment by brookdozer** [comment]
Can I take this one?

**Comment by bheston** [comment]
To add a little clarity, since this was created with the React components and internal icon library in mind...

This affects scenarios using common mono-stroke or single-color icons. It's likely the intent is for the color of the icon to match the color of neighboring text. Since svg `paths` use `fill` not `color`, we need to either pair `fill` and `color` style attributes everywhere, or allow for a common style like `svg { fill: currentcolor; }`.

I'm in favor of avoiding the attribute pair, but I'm not sure all icon libraries or designers would know to bake in `currentcolor`. My assumption here is that it's what people would expect by default, and it doesn't break if you use an icon that has its own color.

Our recommendation for single-color icons is to remove all `fill` attributes from the svg markup. This would apply to any icons provided by the components as well, like the dropdown chevron.
