### ISSUE TITLE
Buttons animate focus rectangles

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2261]
**Describe the bug; what happened?**
Our focus rectangles are animating their appearance, when they should appear instantly

Fix is likely to update our transition logic to specify the properties we want to animate, rather than saying "all"

**Comment by connorjsmith** [comment]
Line in question: https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-styles-msft/src/button/index.ts#L128

We should probably do a pass for all transition: all uses, since it's rarely what we want

**Comment by nicholasrice** [comment]
We're about to do a bunch of motion work so this will likely get addressed with those changes
