### ISSUE TITLE
Expose clean method inside sheet-manager

### ISSUE THREAD

**Issue by minnieliu** [microsoft/fast#2265]
I would like the clean() method inside sheet-manager to be accessible publicly. 

Users should be able to clean the registry inside sheet-manager on demand. Useful for server side rendering use case to ensure that class names match between server and client. 

Call this function: 
![clean](https://user-images.githubusercontent.com/19615595/65465002-1d10e400-de10-11e9-89ca-edc68340e2c3.JPG)

**Comment by nicholasrice** [comment]
I think we can make the registry public

**Comment by chrisdholt** [comment]
closed with #3517
