### ISSUE TITLE
Add option for slider to show current value on drag

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2267]
Ex.
![image](https://user-images.githubusercontent.com/5892363/65537688-8a794f00-deba-11e9-92c6-b94b0667c905.png)

![image](https://user-images.githubusercontent.com/5892363/65537749-abda3b00-deba-11e9-9f3c-922ecff5d3e4.png)

As you are dragging the slider, we should be able to display some sort of text or value in addition to the labels under the control

**Comment by chrisdholt** [comment]
closed with #3517
