### ISSUE TITLE
Export data-props from @microsoft/fast-components-explorer package

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast#2269]
Move props in fast-dna\packages\fast-component-explorer\app\utilities\configs\data.props.ts
into @microsoft/fast-components-react-msft package

**Comment by Manan311** [comment]
Hello,
I can move the data.props.ts. But before I do I just want to confirm I am moving from packages/fast-component-explorer/app/utilities/configs/data.props.ts     to     fast-dna/packages/fast-components-react-msft/. Is that right?

**Comment by chrisdholt** [comment]
Adding @janechu - @khamudom can you elaborate on the goal here? Removing as good first issue for now until we get more information.

**Comment by khamudom** [comment]
**Description**
The task is to export `data.props.ts` in fast-component-explorer\app\utilities\configs

**Motivation**
In the case, an author would want to create a page similar to the component explorer and use the same data interfaces, we should export the data.props.ts file from a common src file. 

**Proposal**
A suggested place, to export, could be in the fast-toolings-react utilities directory.

**Comment by janechu** [comment]
Closing as this file no longer exists due to the v2 refactor in #3238
