### ISSUE TITLE
chore: allow convert schema build script to interpret ES6 imports

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#2302]
The `convert-schemas.js` script which converts typescript exported JSON schemas to `.json` does not properly convert any imports.

Instead of doing a series of regex on the read file, we should convert this with typescript to a JavaScript file, then use node to write the JSON file which would be less error prone.

An example of where this should be done is in [select](https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-react-base/src/select/select.schema.ts).

Ideally select should import viewport positioner schema for the `menuFlyoutConfig` so that neither schema will fall out of sync.

**Comment by chrisdholt** [comment]
closed with #3517
