### ISSUE TITLE
Make the Component Explorer themeable

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#2345]
The Component Explorer should be themeable, this is reliant on #2344.

It should allow:
- Class name overrides
- Changes to the MSFT design system to update the density etc of the app

Related to #2337

**Comment by chrisdholt** [comment]
@janechu is this still a feature we need to track in this repo?

**Comment by janechu** [comment]
So, the Component Explorer will remain in this repository for the forseeable future and this was a feature requested, there are a number of pre-requisites for it however. They include conversion of the FAST tooling UI to use the `@microsoft/fast-components`. The real question is, if we expect this feature to be done at some point, do we expect other parts of our documentation to be themeable?

**Comment by chrisdholt** [comment]
@janechu I think this should be closed given #5853 as well - let me know if you agree.

**Comment by chrisdholt** [comment]
> @janechu I think this should be closed given #5853 as well - let me know if you agree.

Closing this out
