### ISSUE TITLE
properly set `backgroundColor` in component explorer

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2388]
**What feature are you requesting?**
Currently we are setting `backgroundColor` with hard coded values in component explorer. These values should be derived from setting `luminance` instead.

**Comment by bheston** [comment]
Working backwards, the goal is to remove `dark` and `light` and then determine `updatedThemeColor` based on `neutralLayerL1` with the current `updatedLuminance`.

**Comment by janechu** [comment]
This has been resolved in #3238
