### ISSUE TITLE
Add SSR support to Grid component and canUseCssGrid()

### ISSUE THREAD

**Issue by k1mby** [microsoft/fast#2408]
Grid component always uses -ms-grid styles on server side because canUseCssGrid() always evaluates to false. 

We can pass the client's browser version to the server to determine what styles are supported but we need a prop to pass this information to the Grid component. Grid should then use that prop to determine which styles to use.

Thanks!

**Comment by chrisdholt** [comment]
closed with #3517 but I believe this was also closed with a PR prior :)
