### ISSUE TITLE
Add translation to Creator

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#2428]
The rendered area on the canvas of both Creator and Component Explorer should be translatable, to start with using:
- German (for long words)
- Arabic (for ascenders/descenders)
- Korean (for density)

It is preferable to use Bing translation tools.

These should also prompt a flip (if necessary) for RTL.

**Comment by chrisdholt** [comment]
@janechu Do we want to transfer this to the necessary repo or can this be closed? I think perhaps it was left for the explore site.

**Comment by janechu** [comment]
@chrisdholt No, I think we close this, the other project is not under active maintenance.
