### ISSUE TITLE
Create a utility and component for TypeDocs to add to the Component Explorer

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#2430]
## Motivation & context
As part of the documentation, the Component Explorer should be able to show the TypeScript APIs more effectively in generated UI. These are currently buried on the documentation site and are not very consumable. Material UI documentation site is an example of good API documentation.

## Description
- Create a parser for generated typedocs converting them into JSON
- Create a component that generates a table utilizing typedocs

**Comment by chrisdholt** [comment]
I believe @nicholasrice is currently working and close to a solution on this (@janechu for FYI).

**Comment by chrisdholt** [comment]
@janechue can this be closed with the removal of the component explorer in #5853?

**Comment by janechu** [comment]
Closed due to the Component Explorer being moved and no longer under active development.
