### ISSUE TITLE
Adaptive motion

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2431]
# Summary
Add *adaptive motion* concept to DesignSystem, providing a mechanism to adjust the amount of motion components express.

# Details
## Relative motion property
`relativeMotion: number`

Work will include adding an additional property to the `DesignSystem` object of the `@microsoft/fast-components-styles-msft` package. The property will be a number type of between the values of 0 and 1 - where 0 expresses a preference to disable motion and 1 expresses a preference to experience maximum expressiveness in motion.

This will be a starting point - if we find additional configuration options to inform motion algorithms we can add them in the future.

## Common UI transition implementations
Implementations for five common UI transitions:
- Reveal
- Dismiss
- Slide
- Elevate
- Expand

Implementations will include generation of bezier curves, durations, and CSS properties in context to the relative motion. These utilities will be designed to work with JSS.

## Animation utilities
Several utilities intended to help track transition states and apply CSS animations will be exposed. Due to the myriad of ways transitions can be applied and the constraints of individual implementations, these utilities will be general purpose and designed to work in the widest variety of use-cases. As common patterns get exposed, we can created more targeted utilizes to address those common use-cases.

**Comment by chrisdholt** [comment]
Closing as obsolete - perhaps an opportunity for the Adaptive Web folks (@bheston, @kingoftac)
