### ISSUE TITLE
How can we address known issues with JSSManager

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2433]
This is tracking an investigation into how we can address known issues with the JSSmanager and CSS-in-JS.

Issue's we want to solve:
- CSS specificity inconsistencies. https://github.com/microsoft/fast-dna/issues/1279 highlights an unpredictable bug caused by the ordering algorithm of the JSSManager. We need a deterministic way to order CSS stylesheets so that specificity is independent of React render order.
- General performance, while good, is still prohibitive on slower devices and leaves room for improvement. The bottleneck seems to be primarily in the CSS-in-JS approach itself - creating these sheets runtime. Can we find a way to make CSS extraction server-side easy, given that no run-time  re-calculation is required.
- Generated class-names have proven to be an issue in highly dynamic content scenarios where the initial render may be different than cached resources. Is there a way to make class-name generation more consistent?

**Comment by chrisdholt** [comment]
closed by #2398 3517
