### ISSUE TITLE
Create single website consolidating FAST app resources

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2434]
Create a single application hosting the fast-color-explorer, fast-component-explorer, and any future exploration sites.

**Comment by chrisdholt** [comment]
@nicholasrice are you working on this - can we convert to a task in that case?

**Comment by chrisdholt** [comment]
@nicholasrice @EisenbergEffect is this still something we want to track for the time being?

**Comment by EisenbergEffect** [comment]
Well, it is planned. There's design work being done to this end. I'm not sure what the timeline for implementation is just yet though. I think we should keep this open.

**Comment by janechu** [comment]
Closed, we are simplifying what sites we publish to only be documentation sites for now per #6955.
