### ISSUE TITLE
Hook up focus colors to existing controls

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2438]
**What feature are you requesting?**
We recently added `focus` to the color recipes. These values are not yet hooked up in controls.

**What would be the benefit of adding this feature?**
Adding to the design system to allow more flexibility in component interaction states.

**Comment by chrisdholt** [comment]
@bheston can you provide an example of how the recipe could be applied to something fairly simple - just as an example. Without context here it would likely require a collaborator to do this, but if it's simple enough and we have the details it may be something a first time contributor could take on.

**Comment by bheston** [comment]
A simple example is something like this search field
![image](https://user-images.githubusercontent.com/47367562/68972871-a9e97580-07a1-11ea-9d5d-6c2ce9957925.png)

The rest, hover, active, and focus states may all be different.

The delta has already been added to the design system and color recipes, so the task here is to go into each style sheet and apply the focus color to the focus state. It's fairly mechanical and shouldn't require design. That being said, the current theory assumes that the focus color is in the same palette as the other state colors, which is true for the current way recipes are applied.

I'll tag it as a good first issue.

**Comment by bheston** [comment]
In the default design system configuration, the focus color should not be different than the resting state. For instance, tab-focusing a button should not change the color. This update will also validate the new color recipes in a real-world scenario. For instance, use a delta that's 10-20 larger than the hover or active state, which should result in a noticeable state change.
Note that foreground colors will need to be adjusted based on the focus background as well.

**Comment by chrisdholt** [comment]
closed with #3517
