### ISSUE TITLE
Add margin offsets for vertical typography alignment

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2439]
**What feature are you requesting?**
Different fonts have different inherent top padding, but all seem to have enough that vertical alignment doesn't always feel uniform. For instance, headers on dialogs have much more space on the top than the left when a consistent padding is used. This causes alignment offsets when related to something like an icon that fits the desired boundaries.

**What would be the benefit of adding this feature?**
Better control in aligning text and spacing between lines of different text styles.

**What solution would be ideal for you?**
Applying a specific offset for each step of the ramp. Understanding that it may be difficult to determine what value to use for any given font, even an approximation would help bring lines closer to visual alignment than no adjustment at all. Presumably a negative margin, like t7 gets -4px top margin applied.

**What alternatives have you considered?**
Aside from longer term potential updates to the way browsers calculate and render type, the only alternative I can identify would be manual application of offsets or different margins at each specific instance.

**Comment by chrisdholt** [comment]
Converting to a task assuming @bheston is working on this :)

**Comment by chrisdholt** [comment]
@bheston is this related to #2432? Should it be?

**Comment by bheston** [comment]
It is loosely related, but either could be done independently. In some regards it may be better to complete this one first, then adapt the entire typography solution to modular scale.

**Comment by chrisdholt** [comment]
Closing given #5853

**Comment by bheston** [comment]
For future reference, the latest thoughts around solving this are described in #5510
