### ISSUE TITLE
Update components to use toggle recipe in selected states

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2440]
**What feature are you requesting?**
We added the toggle recipe to use for components that show a selection state. Update checkbox, radio button, and toggle based on the new design guidance using this new recipe.

**What would be the benefit of adding this feature?**
More distinction between selected and unselected states.

![image](https://user-images.githubusercontent.com/47367562/68967249-9d125500-0794-11ea-8267-a30e267dfc1d.png)

**Comment by chrisdholt** [comment]
closed with #3517
