### ISSUE TITLE
Design form validation handling and display

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2442]
**What feature are you requesting?**
Basic form elements, and custom property editors need to validate input and communicate error information.

Some points to consider:
- Work with built-in html 5 validation where appropriate
- Option for inline messages and summary
- Summary may appear outside of the scroll bounds if appearing at the top of the form
- Should inline validation reserve space or grow and push
- Consider success and warning cases as well as error

**What would be the benefit of adding this feature?**
Clear error handling for form input.

**Comment by janechu** [comment]
I'm removing this from the tooling project as the tooling form elements already have a couple ways they can show validation, including HTML5 validation and inline.

It should be noted however that integration of the components to the tooling cannot happen until this work on the components has been completed.

**Comment by usrrname** [comment]
Commenting for the sake of watching this

**Comment by janechu** [comment]
Removing per #6955 we are no longer working on components directly in this project and focusing on the underlying architecture as provided by the `@microsoft/fast-element` package.
