### ISSUE TITLE
Migrate elevation into the design system

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2443]
**What feature are you requesting?**
Elevation configurations are currently hard-coded into the utility functions. Turn these into a system so they can be adjusted and applied algorithmically similar to the color system.

**What would be the benefit of adding this feature?**
Enabling control of elevation through the design system to be able to customize and coordinate with other platforms and environments.

**What solution would be ideal for you?**
Ability to control up to three elevation configurations per element: ambient, penumbra, and umbra.

**Comment by chrisdholt** [comment]
@bheston can you elaborate on the thinking behind having three configurations. Also, would be helpful to define the configurations as named above and their behavior? It sounds like an implementation has been decided on, but the request here doesn't outline it. If that's the case, can this change to more of a proposal format?

**Comment by bheston** [comment]
The three configurations come from natural shadows. Some shadow systems use all three (Material) and some only use two (current Fluent). Of course, one is a reasonable possibility as well. Any individual shadows need to be combined onto the same element, which is supported at the implementation level of the box-shadow attribute.

It may not be important to actually give these configurations names, and could be done in a way where the relationship is one to many.

Open to suggestions and other ideas.

**Comment by bheston** [comment]
Resolved by #2463

**Comment by nicholasrice** [comment]
This looks like the same issue as #3443. Closing this issue in favor of the former because it has more activity.
