### ISSUE TITLE
Add improved border handling to components

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2444]
**What feature are you requesting?**
Currently applying borders to component elements is very manual and error prone. Here are some of the issues:
- Placeholders for focus states
- Different handling for filled and outlined components
- Adjusting padding for different border thicknesses
- Supporting thick borders, for instance, focus states that push into content
- Using css border and box-shadow inconsistently or together

**What would be the benefit of adding this feature?**
Cleaning up style sheets and making applying and customizing borders easier.

**What solution would be ideal for you?**
Considering options to layer, contain, or decorate elements for consistent handling of fill, outline, focus, and selection states.

**Comment by bheston** [comment]
Another issue occurs on Windows where the scrollbar has buttons and a backplate. The scrollbar rectangle is drawn immediately inside the border, and above an inset box-shadow. Text inputs are currently using 1px border and 1px inset box shadow on focus, which results in:

![Windows input focus border](https://user-images.githubusercontent.com/47367562/71496066-14acb880-2806-11ea-82dc-938e140af39d.png)

**Comment by bheston** [comment]
> @bheston This appears to have been created prior to our web components work. Is it still relevant or can we close this?

@EisenbergEffect This is actually exactly related to what came up in #5566. It relates to my current thinking around injection of styles, which is still the requirement I see for enabling a true token architecture that can be descriptively applied to any component part.

I'd like to see it stay open, and I'll try to remember it's here and link it with the work I need to take some time to write up soon.

**Comment by janechu** [comment]
Removing this per #6955.
