### ISSUE TITLE
[feature request] Support for Hooks

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2450]
Potential areas for Hooks:
* Move functionality out of `Foundation` into functions consumable by function components
* Hooks support for `fast-jss-manager-react`, possibly updating JSS to v10
* plug-and-play support for areas that require context (ie. Background and design system providers, etc.)

**Comment by connorjsmith** [comment]
Let's keep this open

**Comment by chrisdholt** [comment]
closed by #3517
