### ISSUE TITLE
proposal: viewport aware virtualizer

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#2453]
I've worked up a rough working version of a virtualizing container.  Basically we use intersection observer to detect when the component is within a particular viewport or not and the component uses that information combined with props to help authors manage instanciation and rendering.

The intent is to have an easy way for developers to delay loading of out of view elements and/or remove out of view elements from the dom to improve performance.  It could be thought of as a jazzed up lazy loader.

The component manages rendering at the React render level by simply not rendering the component internals in its render function. 

### Props (aspirational, not necessarily what is currently in sample):

**Viewport:** dom element or ref to be used as viewport (must be a hierarchy parent)

**Mode:** 
    - always instanciated: internals render at all times
    - lazy load only: internals only render once they have been brought into view, but are never de-instanciated
    - in view only: internals only render when the component is in view

**onVisibilityChange:**  Callback for when visibility changes

**Managed classes**
Additionally, the component would apply an author provided class to the component when it is in view.  Authors can use this css classs for additional rendering management  if desired.  For example the class could be used for component internals to apply a "display: none" css attribute to the component internals when they are not in view (ie. keep the object instanciated as a React node, but don't render in the dom).

https://github.com/microsoft/fast-dna/tree/users/scomea/viewport-aware-wrapper

**Comment by chrisdholt** [comment]
Thanks @scomea! Is it possible to edit the issue above to include the proposed interface as well as how this might be used? I was able to dig into the code, but it might be easier for folks looking to provide feedback to see some of that inline above.

**Comment by scomea** [comment]
Renamed to LazyLoader.  Updated functionality.

**Comment by chrisdholt** [comment]
closing due to #3517
