### ISSUE TITLE
update select component to use Aria 1.2 when it is implemented

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#2454]
Aria 1.1 has some issues around implementing aria support for combo boxes that are directly relevant to the Fast select component.  We have attempted to get close but we will need to revisit how we implement aria support in the component once Aria 1.2 is available.

A discussion of the issue and changes being considered can be found here:
https://github.com/w3c/aria/wiki/Resolving-ARIA-1.1-Combobox-Issues

**Comment by chrisdholt** [comment]
closed with #3517
