### ISSUE TITLE
Error when passing as "string" as child to Listbox in base

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2464]
**Describe the bug; what happened?**
When you pass a child that is a string too `<Listbox/>`. You get the following error:

![image](https://user-images.githubusercontent.com/37851214/69452897-af057200-0d17-11ea-8fc9-a0a78750dc73.png)

**What are the steps to reproduce the issue?**

Example:
```
<ListBox>
  Child1
</ListBox>
```

**Comment by chrisdholt** [comment]
@eljefe223 can you elaborate on what you would expect to happen if strings (multiple) were passed as children to listbox? Is this a scenario you would expect to be supported, and if so, what would your expectation be for how the listbox would handle it?

**Comment by eljefe223** [comment]
I would expect it to either fail gracefully or render the text string. Currently we get the above compiler error.

**Comment by chrisdholt** [comment]
closed with #3517
