### ISSUE TITLE
Investigate yarn "error code 137"

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2470]
**Describe the bug; what happened?**
Every so often for no explicable reason build gates fail with `error code 137`

![image](https://user-images.githubusercontent.com/37851214/69761048-0db55c00-111b-11ea-9251-4518fb72f0a8.png)

Investigate further into why this happens.

**Comment by janechu** [comment]
@awentzel do you know if we are investigating some mitigation of this? I see it happening more and more often.

@chrisdholt @nicholasrice for awareness.

**Comment by chrisdholt** [comment]
I haven't seen this happen in awhile - do we think this can be closed?

**Comment by awentzel** [comment]
Unable to replicate as well so we're closing.  Happy to re-open if this pops up again and can be reproduced.
