### ISSUE TITLE
unhandledProps() returns an empty object if no handledProps member is defined

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2480]
Issue is with this logic here
https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-foundation-react/src/foundation/foundation.ts#L112

if `this.handledProps` is falsy, then no props will make it into `unhandledPropsKeys`, ultimately making `this.unhandledProps()` return an empty object. I would expect if no handledProps are specified, then all props should be returned (sans children, since it is the default handled prop)

**Comment by nicholasrice** [comment]
Good catch, that seems like a bug.

**Comment by chrisdholt** [comment]
closed with #3517
