### ISSUE TITLE
*Draft*  Add virtualizing stackpanel as a new base component

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#2501]
A virtualizing stack panel is a container component that displays a horizonal or vertical stack of children.  Child elements that are not currently in the container's viewport are not instanciated to improve performance and memory usage.  

Props:
 /**
     * Whether items outside the viewport should be rendered or not
     * default is true
     */
    enableVirtualization?: boolean;

    /**
     *  the indexes of children that should always be rendered
     */
    neverVirtualizeIndexes?: number[];

    /**
     *  The default span of each item (width in horizontal orientation, height in vertical)
     */
    defaultItemSpan?: number;

    /**
     * An object whose entries specifies the height of items that differ from the default height.
     * Format is {itemIndex: heightValue}
     */
    itemSpanOverrides?: ItemSpanOverride;

    /**
     * How many items to preload before and after the range defined by viewportMaxHeight
     */
    preloadBufferLength?: number;

    /**
     * The orientation of the stackpanel
     */
    orientation?: stackPanelOrientation;

    /**
     * The children of the panel
     */
    children?: React.ReactNode;

    /**
     * Callback for when scroll values change
     */
    onScrollChange?: (newScrollValue: number, scrollMaxValue: number) => void;

    /**
     * When the component scrolls focused content into view how many pixels should the next item "peek" into view
     */
    nextItemPeek?: number;

    /**
     * Whether to enable smooth scrolling
     */
    enableSmoothScrolling?: boolean;

    /**
     * The duration the scroll movement should last
     */
    scrollDuration?: number;

    /**
     * The index of the item initially in view
     */
    initiallyVisibleItemIndex?: number;

**Comment by scomea** [comment]
Working branch for this here - https://github.com/microsoft/fast-dna/tree/users/scomea/virt-stackpanel

**Comment by scomea** [comment]
This is now fairly advanced and will be in a PR soon.

**Comment by chrisdholt** [comment]
closed with #3059
