### ISSUE TITLE
Focus behavior of modals

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2536]
## Issue
#2319 made it so that all focus events on the document while the modal is mounted returns focus to the modal. The issue we see with this behavior is that if the modal is about to unmount, we generally want a specific element to have keyboard focus. Our implementation has us using redux to manage visible modals, but I believe this repros with any use of the modal.

```typescript
function closeModal() {
  dispatch(hideModal()); 
  elementToFocusAfterClosingModal.focus();
}
```

Here, we dispatch an action that ultimately unmounts the modal, but the focus event bubbles to the document before this lifecycle event happens. Therefore focus is given to the correct element, but then has it taken by the modal. The modal then unmounts and reasonable focus is lost on the page.

We could stop propagation on focus events, but why we are stopping focus propagation could be unclear to someone new to a codebase and may break other components that listen to document focus.

## Proposed fix
If we don't want to go the stop propagation route, we could provide an "element to return focus" prop which is used in `componentWillUnmount`, after we deregister the document listeners. Since this promotes reasonable focus behavior (the modal will almost certainly have focus when it is dismissed), this seems like a good option.

Happy to discuss :)

**Comment by chrisdholt** [comment]
@connorjsmith any desire to submit a PR for this?

**Comment by connorjsmith** [comment]
Sure, assuming the proposed fix of a new focusable element prop makes sense in the context of fast-dna

**Comment by nicholasrice** [comment]
@connorjsmith I'm having trouble understanding what exactly is causing the bug here - I put together this sandbox - is this the issue you're having? https://codesandbox.io/s/confident-sutherland-xl1k7?fontsize=14&hidenavigation=1&theme=dark

**Comment by connorjsmith** [comment]
Yeah, basically because the setState call does not unmount the modal, it's document listeners are not unregistered and the modal takes focus back from the button

**Comment by nicholasrice** [comment]
I think exposing a *focusOnClose* prop is in line with the accessibility requirements of the component but I think the bug here is really that our focus managment and unmount code-paths do not solve for this case. I'm going to investigate if this specific issue can be solved without an additive prop and extra work for app authors.
