### ISSUE TITLE
Add component which provides messages for screenreaders to read aloud

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2546]
**What feature are you requesting?**
We often need to announce messages to screen reader users (generally for confirmation of action scenarios). Our current project uses a react component that uses `role="status"` or `role="alert"` internally, but we've come across a few gotchas that make this component non-trivial and a good candidate for a standardized message reader component in fast-dna.

**What would be the benefit of adding this feature?**
* Batteries-included way to announce messages to screen reader users, making it easier for any component to announce a message regardless of position in the DOM/component tree.
* Avoid some of the gotchas of a naive react solution (ie. reading the same message twice wont be a DOM update -> second message isn't read)

**What solution would be ideal for you?**
Ideal psuedocode would be something along the lines of 
```typescript
announceStatus('random message');
announceAlert('random important message');
```

Whether these functions are static or passed in via HoC injection is up for discussion. I believe a static function would be easiest, but may not be feasible without yucky global variables/DOM manipulation.

**Comment by chrisdholt** [comment]
Would this request be akin to something like an aria-live region? This sounds more SR specific rather than something like an accessible [alert](https://w3c.github.io/aria-practices/#alert) or message dialog.

**Comment by connorjsmith** [comment]
Yeah this is SR specific. Since there is no visual component to these messages, aria-live="polite"/"assertive" is probably a better attribute
