### ISSUE TITLE
Add loading spinner to auto-suggest component 

### ISSUE THREAD

**Issue by fmamic** [microsoft/fast#2552]
**What feature are you requesting?**

Loading spinner is missing from the auto-suggest component so custom spinner needs to be added when loading data async.

**What would be the benefit of adding this feature?**
No need for custom implementation of the loading spinner in the auto-suggest component.

**What solution would be ideal for you?**
Auto-suggest component with the small spinner on the right side and controlled with the component props (can be turned on/off)

**What alternatives have you considered?**
Custom component: adding auto-suggest component plus the spinner above it.

**Is there any additional context for your request?**
Component in question: https://explore.fast.design/components/auto-suggest

**Attach screenshots or images add detail to your request:**
![1](https://user-images.githubusercontent.com/9407124/71833857-c5884280-30a5-11ea-8f9f-acf0c2575126.JPG)

**Comment by scomea** [comment]
Currently this can be achieved with a custom input region render function.
 
As the component itself has no notion of loading states I’d suggest this would be an enhancement to the MSFT styled version and not base if we decided to add it.
 
I think it makes sense to add it for the sake of design consistency if we see this as a common thing for devs to add.  We'd probably want to think about how we handle loading states across the framework along with this - visuals, accessibility, etc...

**Comment by chrisdholt** [comment]
@fmamic does this help solve the issue? I think this is likely somewhat related to #2255 although slightly different.

**Comment by chrisdholt** [comment]
closed with #3517
