### ISSUE TITLE
How should stateful recipes be assigned in Figma plugin

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2588]
The Figma plugin currently hard-codes usage of the "rest" recipe when it exists. We'll want a way to surface stateful recipes, so we should investigate how we want to surface this in the UI.

**Comment by Jeremy-Knudsen** [comment]
Adding a preliminary UI design for surfacing stateful  recipes:
![image](https://user-images.githubusercontent.com/11559173/73286312-35bd4c00-41ac-11ea-9f56-4a111674f480.png)
