### ISSUE TITLE
Add unit testing to Figma plugin

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2590]
Add jest test library and test all appropriate units of the figma plugin.

We should also investigate if it makes sense to test *in* a figma document, and if so, how we can do that.

**Comment by Jeremy-Knudsen** [comment]
Regarding testing _in a figma document, we gather some notes about this after meeting with Eugene. Eugene built their own thing to test: a VM running Figma and use Selenium in the browser to open the plugin and do very basic operations to test the a limited set of main scenarios in an automatic manner: install the plugin, launch the plugin, sign in/sign out, apply content, monitor the status of the plugin. This is done in the browser version of Figma. Most of our plugin testing is manual. **The investment in automatic testing likely won’t payoff.**
