### ISSUE TITLE
Add prop 'expanded/collapsed' to tree-view-item

### ISSUE THREAD

**Issue by adkaufm** [microsoft/fast#2597]
Add a prop to tree-view-item that allows a parent to control if the item is expanded or collapsed. 

We'd like to use tree-view-item with dragConnect to make a draggable/droppable tree-view-item. One of our d&d scenarios is that an item should expand after a few seconds if another item is drag-hovered over it. This is impossible with just dragConnect, because the parent won't have access to the tree-view-item's internal expanded/collapsed state.

The ideal solution would be for the parent to be able to control if the item is expanded or collapsed via a prop.

**Comment by chrisdholt** [comment]
closed with #3517
