### ISSUE TITLE
Column breakpoints in fast-layouts uses the default breakpoints to determine start/span values

### ISSUE THREAD

**Issue by shauntc** [microsoft/fast#2602]
The fast layouts column uses the [default breakpoints](https://github.com/microsoft/fast-dna/blob/master/packages/fast-layouts-react/src/utilities/breakpoints.ts#L7) instead of ones set in the fast breakpoint tracker to determine what span/start value to use (though the check is triggered by the fast breakpoint tracker breakpoints).

This happens because [this line](https://github.com/microsoft/fast-dna/blob/master/packages/fast-layouts-react/src/column/column.tsx#L97) uses [this utility function](https://github.com/microsoft/fast-dna/blob/master/packages/fast-layouts-react/src/utilities/breakpoints.ts#L12) without a second parameter, causing it to use the default value (which is the default breakpoints). The easiest solution would be to just add passing in the breakpoints here but I would suggest also removing the default value here or moving things around so that `defaultBreakpoints` are never exposed (and are only used by the fast breakpoint tracker)

**What are the steps to reproduce the issue?**
1. Create a layout with a span/start column value defined as an array of values
2. Set new breakpoint numbers
3. alter the window size, notice that it will only transition when the new breakpoint number are hit but will use the `defaultBreakpoints` values to select which span/start value to use

**Comment by chrisdholt** [comment]
@shauntc would you like to send a PR for this?

**Comment by shauntc** [comment]
@chrisdholt I can do a PR for this but it'll be a few days before I get to it

**Comment by chrisdholt** [comment]
> @chrisdholt I can do a PR for this but it'll be a few days before I get to it

That works for us - if we get additional feedback that this is higher impact from other folks we can jump on it; though, considering you filed the issue I'll trust your priority on it :).

Thanks!

**Comment by chrisdholt** [comment]
closed with #3517
