### ISSUE TITLE
Allow changing the base background color on colors.fast.design

### ISSUE THREAD

**Issue by shauntc** [microsoft/fast#2618]
**What feature are you requesting?**
Ability to change the base background color, and more clarity/explanation on the page about the color system

**What would be the benefit of adding this feature?**
Show what the relative colors will be with different backgrounds, better understanding of the fast color system

**What solution would be ideal for you?**
Add it just like the other color configurations on that page

![image](https://user-images.githubusercontent.com/4647935/73035408-d30b2f80-3dfc-11ea-99e0-ecad5d2ae41f.png)

**Comment by chrisdholt** [comment]
Tagging in @bheston and/or @nicholasrice for triage

**Comment by bheston** [comment]
Realizing the details of the algorithmic system are complicated to fully grasp, we're currently evaluating a way to publish more of the design guidance with details on the implementation. We're also working on tooling for the design side. The color explorer currently fits as a reference of the default recipes (with default configuration), but doesn't provide controls to alter recipes, for instance, the offsets used to determine recipe colors.

You've specifically highlighted the background. Are you looking for a way to see the values for L1, L2, and other named layers for something like a slightly darker light mode, where you start on a medium grey or some other color?

If you want to see the in-between backgrounds you can uncheck the checkbox on the right. That will give you all 94 backgrounds in the current neutral palette.

If you want something other than grey you can change that in the top color picker.

I want to make sure I understand the exact request here.

**Comment by bheston** [comment]
Closing this because it's not actionable without answers to the above questions. We have #4313 to track general improvements to this tool and related documentation.
