### ISSUE TITLE
Add the ability to change the accent color palette source color in the plugin

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [microsoft/fast#2622]
**What feature are you requesting?**
Ability to change the accent source color to any custom accent color. Right now, we just use the default accent (#0078d4) base color to generate the backround color ramp.

**What would be the benefit of adding this feature?**
The ability for customers to use a custom accent color to generate the accent color ramp, which would align to our design system.

**What solution would be ideal for you?**
I am thinking a treeview that is part of a set of global variables like this one. The treeview item would consist of a color swatch to visualize the color, coupled with an editable input field to show/edit the precise base color.

**What alternatives have you considered?**
This UI could also live under a global/recipe pivot like we have in https://www.fast.design
![image](https://user-images.githubusercontent.com/11559173/73094277-1e711c80-3e95-11ea-8f26-4d7b74bce5d1.png)

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by nicholasrice** [comment]
This capability was added but it looks like this issue wasn't' closed. Closing now.
