### ISSUE TITLE
autosuggest does not get dismissed when tabbing out

### ISSUE THREAD

**Issue by paucortescosta** [microsoft/fast#2655]
When using the autosuggest component, I see there's a handleInputRegionKeydown function that takes care of the keydown events, but it's missing the tab key.

Basically what happens is the autosuggest menu remains open even though it loses the focus.

https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx

Example:

1. Go to https://microsoftnews.msn.com/
2. Click on Personalize
3. Try searching for some topic
4. Once the autosuggest menu pops up, push the tab key

**What behavior did you expect?**
Autosuggest menu would close, but it remains open

**Comment by chrisdholt** [comment]
Thanks @paucortescosta - Can you help provide a bit of insight where the ask regarding tab is coming from? I see it as intuitive, but I haven't identified it as part of the expected interaction model for autosuggest. I think this is something to fix, but I want to be sure that we can point to something tangible as our guidance.

**Comment by paucortescosta** [comment]
in the current scenario, if you start typing something in the textbox, you might get some suggestions, if you press the tab key once, you will focus on the suggestions list, if you press it again, you'll focus on the side pane. In that scenario, the autosuggest menu should disappear to let the user see where the focus is, right now the autosuggest menu is hiding the focus in that scenario.

**Comment by chrisdholt** [comment]
closed w/ #2699
