### ISSUE TITLE
Select menu shows behind other controls

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2659]
**Describe the bug; what happened?**
The select menu shows up behind other controls. 
<img width="338" alt="Screen Shot 2020-02-05 at 9 13 16 AM" src="https://user-images.githubusercontent.com/37851214/73867283-43518200-47fb-11ea-8651-86781140279f.png">

**What are the steps to reproduce the issue?**
Compose a page by vertically placing <Select/>. The select's menu shows up behind the components below it.

We should add a `z-index` of `1` to the `select_menu` class to ensure the open menu is above the controls below it. This will cover the majority of cases where `z-index` is not being set.

**Comment by chrisdholt** [comment]
closed with #3517
