### ISSUE TITLE
Form components in FAST Components

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2694]
# Form components
## Objective
Make a decision on which model(s) we want to adopt for form elements in `@microsoft/fast-components`. Following that, individual specifications will be written for the above components where appropriate.

## Overview
This spec outlines two general approaches to form input elements that are natively available in the browser but that we have design opinion for. Our current offering for these components includes:
- Checkbox -> input[type="checkbox"]
- Number field -> input[type="number"]
- Radio -> input[type="radio"]
- Select -> select
- Select option -> option
- Slider -> input[type="range"]
- Text area -> textarea
- Text field -> input[type="text"]

As a library we will determine how app authors will use our components to accept user input. This spec outlines several approaches we can take to address this requirement.

### Background
While the platform exposes a number of elements and configurations for accepting user input, in general these components are not stylistically flexible. They do not generally expose a standardized set of style-able pseudo-elements and in many cases the desired visual design is impossible to achieve. For many libraries, the general approach is to offer a replacement component to be used instead of the standard `input` element. This allows libraries to achieve the desired visual design extensibility at the cost of having to maintain replacements for native functionality.

### Use Cases
The primary use-case is accepting user input and surfacing that information to form submit events for consumption by app authors. We additionally want to offer style extensibility so that visual design for these elements can be customized in the same way that other components can.

### Risks and Challenges
There are two primary challenges for form elements with Web Components:

#### Form Data & Validation
Native form elements offer several convenience features for working them, including input validation and surfacing input values automatically during submit events. There is an API to replicate this behavior for custom elements, however support is not wide and the following do not offer support for form association:
- Safari & Safari Tech Preview
- Firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1552327

For browsers that do not support this API, custom form elements are invisible to their containing form and their values must be extracted manually through direct element references.

#### Shadow DOM obfuscation
A general approach some component libraries (ourselves included) have used to address the above issue is to render a hidden input element that reflects the state of the visible input replacement. This hidden input then reflects *it's* state to the parent form. There is an additional complication with the Shadow DOM though, where inputs rendered in the shadow tree are not expressed to the parent form.

These two issues are a bit of a catch-22 for us; if we want reasonable browser support we can't use the **Form Associated Custom Elements** API, but we need to use that API if we want to create custom form elements that have feature parity with native elements.

#### Replacement
One option is to offer replacement components for the various input types. This would require re-implementing the behavior and semantics of each input type, as well as conditionally implementing the [Form Associated Custom Elements](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example) APIs for browsers with support. For browsers that support the Form Associated Custom Elements API, we could make these components work just like native browser elements.

For browsers *without* Form Associated Custom Elements API support, there are several complications for app authors.
1. The elements would not be "form associated", meaning their values are not surfaced to the parent form.
2. Validation pseudo-selectors such as `:valid`, `:invalid`, `:in-range`, `:out-of-range` etc would not work
3. Implementation of https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation would be painful and *maybe* impossible. I think we *could* do work to expose the same API for the elements but there could (and likely is) side effects to not providing the *native* implementation of these APIs. We would need to do more research here to see if this is really an option, but worst case the validation APIs do not work.

```html
<fast-checkbox checked></fast-checkbox>
```

#### Component wrappers
Another option is to offer a *wrapper* component for native input elements. This would provide us sufficient opportunity to provide style overrides to the native input element while still exposing the input itself to the light DOM tree, preserving native form element capabilities.

```html
<fast-checkbox>
    <input type="checkbox" checked>
</fast-checkbox>
```

In general this is a good approach because it keeps the input itself in the light-dom and does not require us to re-implement all of the platform features into a custom element. Ergonomically, it requires a bit more code for an app-author to write and for some of the more advanced scenarios could be cumbersome. It also limits the extensibility of a component and reduces opportunity to add convenience features. Take select:

```html
<fast-select>
  <select>
    <option value="A">
    <option value="B">
    <option value="C">
  </select>
</fast-select>
```

Because all of the data is represented using native elements, we need to go scrape HTML elements to surface the relevant data in our replacement UI. It also limits extensibility: how do I associate a glyph with an `option` element?

#### Hybrid
We could take either approach where appropriate. Simple inputs like `checkbox` and `text` could be implemented easily using a wrapping model, where more complicated components like `select` could be implemented using a replacement model. This does lead us to an inconsistent developer experience which may not be desirable.

```html
<fast-checkbox>
    <input type="checkbox" checked> <!-- would be form connected -->
</fast-checkbox>

 <!-- would *not* be form connected (in some browsers) -->
<fast-select>
  <fast-option value="A">
  <fast-option value="B">
  <fast-option value="C">
</fast-select>

```

### Prior Art/Examples
- Material UI: https://github.com/material-components/material-components-web-components/tree/master/packages/textfield 
  - Implements the "replacement" model. They do not seem to currently implement form connections, so authors are required to maintain references to the custom form elements directly to read values.
- Fabric (react) implements a replacement component that renders an input in the light DOM: https://developer.microsoft.com/en-us/fabric#/controls/web/checkbox
- FAST-DNA (react) implements a replacement model as well.
  - I imagine this is the case for all non-custom-element implementations.
- vaadin implements a replacement model: https://github.com/vaadin/vaadin-checkbox

### Final thoughts
It appears that most libraries simply replace the input elements and don't do work (yet) to surface the value to the parent form. The [Form Associated Custom Element](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example) API is rather new, so that is likely why. Over time, I think a replacement model and the above API will provide us the most extensibility, but it does suffer in the short term.

**Comment by awentzel** [comment]
Well written, Nick.  Are there any performance, accessibility, or SEO impacts on these approaches?

**Comment by EisenbergEffect** [comment]
Yep, great write up! @nicholasrice It seems like we should go with the replacement model, but then also have our elements add a hidden form control to the Light DOM. It could be added directly to the content and then we could provide slotted styles that make it display none, as one idea. This could be wrapped up in a utility class...maybe we could even make it look a bit like ElementInternals. I'm not sure how hard that would be.

**Comment by nicholasrice** [comment]
@awentzel There shouldn't be any notable performance or accessibility concerns. Element replacement has a non-zero impact on perf so I expect it will be marginally less performant than using native elements. It will also likely wind up being more code, though I think we can minimize the total with good abstractions.

I'm honestly not sure about SEO. I don't see why form elements would have a significant impact on search results, and I would expect search algorithms to be able to determine an `input=[type="checkbox"]` is the same as `div[role="checkbox"]`, but I'm not an expert in this area.

I like that @EisenbergEffect. I had a similar thought of expecting a hidden input as a child if the author wanted form connection, though the downside to that is hidden inputs don't participate in validation. It would also require the author to create that element. If we can just render an `input` into the light DOM as a child of the custom element in cases where `attachInternals` isn't supported, I think that could be a good model.

**Comment by chrisdholt** [comment]
Given that our WC work is still in its infancy, by the team we reach adoption and then implementation of other teams, it seems reasonable to assume that a relatively small portion of folks would need a 100% web component based solution here. I think a fair amount of folks would likely still be leveraging other frameworks or solutions to manage the overall state of their app and submissions.

I'm all for going the direction articulated by @nicholasrice and @EisenbergEffect - "replacement+" as an ideal model.

**Comment by nicholasrice** [comment]
I did some further investigations into the "wrapper" model described above that can be viewed here: https://github.com/microsoft/fast/tree/users/nirice/input-control

And while I didn't prototype every control, I did run into several issues:

**Changing CSS based on input state:**
Controls such as radio and checkbox change visually when `checked` and `indeterminate` and the control should be able to apply CSS changes accordingly. This cannot be done solely with CSS because no CSS combinator can select a shadowed element sibling based on a slotted `:checked` element. Therefore, a `.checked` and `.indeterminate` class must be hoisted by the wrapper control. This isn't too much of a problem for `:checked` because the wrapper can listen for `change` events and update a local state, but `indeterminate` is a bit more troublesome. There is no native capability to detect changes to that property, meaning we must either: 1.) replace `HTMLInput.indeterminate` with a property descriptor that allows us to notify on property changes. 2.) Require setting `indeterminate` on the wrapper and the `<input />`

**::slotted has limited pseudo-element support**:
The `::slotted` css selector can do much of what we need to, but it makes certain patterns challenging because it only supports [tree-abiding pseudo elements](https://drafts.csswg.org/css-pseudo-4/#tree-abiding) (meaning only `::before`, `::after`, `::marker`, and `::placeholder`). Styling pseudo elements of range sliders, date pickers, and others(?) is not supported.

**Some native UI can't be styled**:
Chromium supports some native autofill-type modals for `<input type="text" />` that cannot be styled (AFAIK). Because the modal displays as a result of user interaction with the web-page and not the browser application, it *feels* like site UI, which leads to a disjointed experience if the visual designs differ significantly.

**Comment by nicholasrice** [comment]
After thinking on this some more:

I don't recommend going with a wrapper model. I really like the ergonomics of the wrapper, but there are technical limitations that are blockers on the implementation (primarily limited pseduo-class selectors from slotted elements.) I don't think we'll be able to achieve visual designs targets.

That really leaves us with our existing model (ElementInternals where supported and proxy where not) or a full proxy model (custom element is not FormAssociated). I like the full proxy model because it reduces inconsistency for authors developing for multiple browsers, but I also see benefit to using modern platform features where available, and would prefer to prioritize browsers that support those features. All this to say, if we're going to do anything, it would be to un-associate the custom elements from the parent form in chromium browsers and implement a proxy-element model in all browsers. 

At this point I don't recommend changing our approach, because the bugs we've had won't be addressed by the alternative option.
