### ISSUE TITLE
Animation timing of sequence indicators in carousel

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2697]
**Describe the bug; what happened?**
There is some questions around the timing of the animation for the transitions on the sequence indicators in `<Carousel/>`, specifically that they may be too fast. Creating issue to follow up with Parker.

**What are the steps to reproduce the issue?**

Example:

1. Go to https://explore.fast.design/components/carousel
2. Focus onto sequence indicators
3. Left and right arrow key through indicators
4. Note animation speed.

**Comment by chrisdholt** [comment]
closed with #3517
