### ISSUE TITLE
Toggle component spacing is uneven

### ISSUE THREAD

**Issue by alyssacleonard** [microsoft/fast#2700]
Pixel spacing on the left of the "off" toggle does not match pixel spacing on the right of the "on" toggle. This causes the "on" toggle center circle to appear to be lower than the "off" toggle center circle on some screens.

<img width="44" alt="toggles2" src="https://user-images.githubusercontent.com/32080524/75378409-78944180-5888-11ea-9d37-469bcf115862.png">

<img width="298" alt="toggles" src="https://user-images.githubusercontent.com/32080524/75378157-0facc980-5888-11ea-9b63-dc45522bf3c6.png">

**Comment by eljefe223** [comment]
Thanks @alyssacleonard, I looked into this further and at 100% zoom I'm not reproing. Could you give me a bit more detail on the zoom level you are using / app zoom levels (PC) / screen resolution etc.?

**Comment by alyssacleonard** [comment]
Yep:
Screen resolution: 2256x1504 (recommended for 13" surface book)
Size of text, apps and other items: 150% (recommended for 13" surface book)
Zoom in edge: 100%

**Comment by chrisdholt** [comment]
closed with #3517
