### ISSUE TITLE
Correct elevation algorithm in web-components

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2778]
The elevation is algorithm is dependent on the relative luminance of the regions background. Right now the value is hard-coded to the relative luminance of white, but we'll want to update this implementation when we get recipe support from `@microsoft/fast-element`.

We'll want to land implementation details, but a few options are:
- When the background color is set by any recipe, the relative luminance of that background color should also be written. Then this recipe could always be used.
- Bind an "elevation" recipe to the control that would write the `--background-luminance` value.

**Comment by nicholasrice** [comment]
related to #3443

**Comment by chrisdholt** [comment]
Closing given #5853
