### ISSUE TITLE
[chore] Migrate to using eslint over tslint

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2788]
Figure it's time we bite the bullet and upgrade ourselves to eslint now that it is strictly preferred over tslint

**Comment by nicholasrice** [comment]
Thanks @connorjsmith! This is something we we certainly want to do because the tslint project has publicly stated they're halting development of tslint in favor of eslint: https://medium.com/palantir/tslint-in-2019-1a144c2317a9
