### ISSUE TITLE
Create release requirements for publishing packages and websites from the repository

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#2804]
I'm starting this feature request, however, collaborator input is required to define the requirements.  Once those requirements are defined, I will begin implementation.  Below includes high level summary based on conversations between @EisenbergEffect and myself.

**What feature are you requesting?**
Specifications to add new pipelines for deploying websites and packages.

**What would be the benefit of adding this feature?**
Automating package and website releases including deployment

**What solution would be ideal for you?**
Search for a pattern in tag names on master, like x.x.x and if the tag matches that pattern publish a release of the package at the version specified by the tag name, for example. So, then publishing is only a matter of pushing a correctly named tag to master. I'm thinking that would kick of a process that merges master into the release branch, tags the release branch, and then publishes the package from the release branch, or something like that. If we publish an official release like that, I think it would be ideal to also deploy the website with the latest docs on conjunction with that.

**What alternatives have you considered?**

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by chrisdholt** [comment]
Is this a request for specs around pipelines or would this end up being a spec for the release pipeline?

**Comment by awentzel** [comment]
@chrisdholt this proposal is intended to provide requirements so I can automate how we publish packages and deploy fast.design website when there is something to deploy.

**Comment by nicholasrice** [comment]
The biggest question in my mind regarding package publishing is the cadence in which we publish. Is it something we want to happen for every merged PR or something we want a bit more control over.

**Comment by chrisdholt** [comment]
I'm hesitant to think we should be publishing / automating publish on every PR run. I can likely come up with some requirements but it would be helpful to know the overall goals or problem being solved with automation here so I can tailor my feedback accordingly.

**Comment by awentzel** [comment]
The goals are to automate the process and eliminate the dependency requiring certain people on the team to perform manual process.  We had discussed publishing on a weekly cadence along with docs at one point.  Also, we want to start leveraging Git Packages.

**Comment by chrisdholt** [comment]
> The goals are to automate the process and eliminate the dependency requiring certain people on the team to perform manual process. We had discussed publishing on a weekly cadence along with docs at one point. Also, we want to start leveraging Git Packages.
> 
> Regarding cadence, it can be dependent on a git naming, which fires off the automation job. Also, deploying sites should be similar and the naming should be consistent between all tags.

Currently, publishing as needed hasn't had a ton of issues in FAST-DNA. Automating that process and having a release cadence can provide benefit, so I'm definitely open to pursuing it. It sounds like there's already been some research and some possible proposals (use git packages, weekly cadence, automation synced with explorers). I'm happy to provide feedback on a proposal which can provide some additional requirements but I don't want to write a wholesale document from scratch given there seems to be some existing ideas that would provide greater context to me. I think it would be helpful to have something written up that we can then provide feedback on.

**Comment by janechu** [comment]
Maybe we can break this up into things we know we want.

Stepping back from automated package publishing, I believe that one thing we want for sure is the ability to automate deployment of our documentation when a publish has happened. This will at least keep our docs in sync and when we publish we already have the aforementioned git tags.

**Comment by nicholasrice** [comment]
Yep - a process that:

1. Publishes all packages requiring publishing
2. Deploys documentation

Thinking about this a bit more - any kind of scheduled publish *could* cause an issue if we add a new package to the repo and the publish process runs before the OS team makes the first publish.

**Comment by awentzel** [comment]
closing as duplicate
