### ISSUE TITLE
Update slider visual styling to better represent lower and upper bound option

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#2826]
**What feature are you requesting?**
Slider has a mode option `adjustBoth` that provides two thumbs. Currently the thumbs much each remain upper and lower and not cross over each other. As currently styled it's difficult to tell that there are two thumbs when they both represent the same value because they are half circles connected forming a whole circle. They are also very small and difficult to grab for dragging.

Update the design to full-sized handles that more clearly indicate directional ends of bounds:
![image](https://user-images.githubusercontent.com/47367562/77375385-8e334480-6d2a-11ea-8685-4ddc907f330c.png)

**What would be the benefit of adding this feature?**
Improved accessibility through larger controls and visible separation.

SVG for thumbs:
[lower-thumb.svg.txt](https://github.com/microsoft/fast-dna/files/4372496/lower-thumb.svg.txt)
[upper-thumb.svg.txt](https://github.com/microsoft/fast-dna/files/4372497/upper-thumb.svg.txt)

**Comment by chrisdholt** [comment]
closed with #3517 - we should investigate this as a new task related to WC's if still desired
