### ISSUE TITLE
Min and Max values have no effect on Progress

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#2848]
**Describe the bug; what happened?**
Changing the `min` and `max` values on `fast-progress` web component has no effect.

**What are the steps to reproduce the issue?**

1. Change the `max` value on `fast-progress`

**What behavior did you expect?**
Currently the default `max` is `100` but if the `max` is changed to something else the value should be visualized as a percentage of that `max` value.

**Comment by EisenbergEffect** [comment]
Is this still blocked? Anything I need to do in the fast-element library to help this along?

**Comment by eljefe223** [comment]
This requires us to perform a calculation on multiple attributes. for example something like:
```
<svg class="progress" part="progress" viewBox="0 0 16 16" slot="determinate">
         <circle class="background" part="background" cx="8px" cy="8px" r="7px"></circle>
         <circle class="determinate" part="determinate" style="stroke-dasharray: ${x =>
             (44 * x.value) / x.max}px 44px" cx="8px" cy="8px" r="7px"></circle>
</svg>
```

**Comment by EisenbergEffect** [comment]
Ah, this is the one where we're not observing everything. Right! Ok, I'll get this work at least started this week.
