### ISSUE TITLE
Root design-system-provider should write the default design system

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#2886]
Current implementation of the `fast-design-system-provider` web component requires the use of a `use-defaults` attribute to apply default values of the design system.

Ideally, the design-system-provider would recognize that it is the root level provider and apply defaults in that case. 

- The `use-defaults` attribute should still be available and behave as it does today
- A new `no-defaults` attribute would *prevent* the root level behavior expressed above.

**Comment by EisenbergEffect** [comment]
Closing as obsolete due to new provider design.
