### ISSUE TITLE
Accessibility Bug on the slider component

### ISSUE THREAD

**Issue by shachak** [microsoft/fast#2959]
Narrator focus doesn't move with the moving slider.

Steps to repro:
1. Open the slider component 
2. Open Narrator
3. Keep using caps + enter to take focus to the slider.
4. use left and right arrow key to move the slider.
Observe that although the slider is moving the narrator focus is not moving.

Expected narrator focus should move along with the slider movement.

**Comment by scomea** [comment]
Looking into it a bit, but given that narrator focus deosn't move with basic page scrolling I'm expecting this is a narrator issue.

**Comment by EisenbergEffect** [comment]
@scomea Was this an issue with the web component or the React Component?

**Comment by chrisdholt** [comment]
@eisenberg effect, this can be closed with #3517
