### ISSUE TITLE
[Mac][Edge] Accessibility issue with slider when voice over is on

### ISSUE THREAD

**Issue by shachak** [microsoft/fast#2960]
Not able to move the speed slider using VoiceOver instructions or left right arrow when focus is on slider.

Steps to repro:
1. Use a Mac PC
2. Open the new Edge browser
3. Open the slider component
4. Try navigating to the slider using voice over instructions or using tabs.
5. When focus is on slider voice over says in order to interact use control + option + shift + down arrow. But on using the instruction we should be able to interact with slider.
6. Even left and right arrow don't seem to work.

**Comment by chrisdholt** [comment]
Thanks @shachak - I'll need a repro outside of our [component explorer](https://explore.fast.design/components/slider) as I can successfully move the slider values using voiceover with that example. I personally find [Stackblitz](https://stackblitz.com/) helpful as I can import components from our packages as dependencies.

**Comment by roryfa** [comment]
@chrisdholt apparently this repros in Read Aloud for Edge

![image](https://user-images.githubusercontent.com/54419365/110035066-4610f600-7cdf-11eb-8887-0a71d5313e7d.png)

**Comment by chrisdholt** [comment]
@roryfa is that the deprecated react version though?

**Comment by shachak** [comment]
we are currently using <Slider> from fast/fast-components-react-msft @chrisdholt not sure if this is deprecated.
