### ISSUE TITLE
Horizontal overflow does not correctly detect overflow state when items have subpixel width

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast#3044]
**Describe the bug; what happened?**
The horizontal overflow component fails to correctly detect overflow state when items have subpixel width.

The issue is that available width is calculated using `clientWidth` (rounded to nearest pixel), whereas total item width is calculated using `getClientBoundingRect` which gives decimal widths. If the total item width is `100.11px`, the rounded client width of their container comes back as `100px` and triggers overflow behavior even though the items may fit.

https://github.com/microsoft/fast-dna/blob/e3bab735adb6659359522fd9cf0ac075ecebe6a0/packages/react/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx#L677

https://github.com/microsoft/fast-dna/blob/e3bab735adb6659359522fd9cf0ac075ecebe6a0/packages/react/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx#L693

**What are the steps to reproduce the issue?**
Render horizontal overflow with items that have subpixel width (e.g. text).

**What behavior did you expect?**
Overflow state is detected correctly.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/10136407/80743982-cde00f80-8ad2-11ea-8bee-9c058ad34c95.png)

![image](https://user-images.githubusercontent.com/10136407/80744131-0bdd3380-8ad3-11ea-8526-8c0de21234ec.png)

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Windows 10

* Browser [e.g. Edge, Chrome, Safari, FireFox]
Edge Chromium, Firefox, Chrome, Edge Legacy

**Comment by chrisdholt** [comment]
closed with #3517
