### ISSUE TITLE
Prettier fails across platforms and is breaking CI Weekly Windows build

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3054]
**Describe the bug; what happened?**
Prettier is failing due to `.tmp`, `dist`, and `app/.tmp` folders across platforms. If these ignored files or folders exist prettier is failing.

Running `yarn run prettier:diff` on the following packages fail.
Running `npm run prettier:diff` fails, but, with a little more detail.
Running 'lerna run prettier:diff` on CI for Windows fails.

**What are the steps to reproduce the issue?**
1. Get latest from master on a new branch.
2. `cd /packages/react/fast-components-react-base` OR `cd /packages/react/fast-components-react-msft` or `cd /sites/fast-component-explorer`
3. run commands from above

**What behavior did you expect?**
successful completion

```bash
src/typography/.tmp/documentation.tsx
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @microsoft/fast-components-react-msft@4.30.10 prettier:diff: `prettier --config ../../../.prettierrc "**/*.{ts,tsx}" --list-different`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @microsoft/fast-components-react-msft@4.30.10 prettier:diff script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/awentzel/.npm/_logs/2020-05-04T19_03_06_915Z-debug.log
awentzel@Microsoft-MBP fast-components-react-msft % cd ../fast-components-react-styles && npm run prettier:diff
```

**Comment by awentzel** [comment]
This latest run on windows ci, failed https://github.com/microsoft/fast-dna/runs/648624713?check_suite_focus=true.  

More investigation is needed on Windows.

**Comment by EisenbergEffect** [comment]
@awentzel Is this fixed? Can this be closed?

**Comment by awentzel** [comment]
duplicate of #3894
