### ISSUE TITLE
[Accessibility] [Narrator] [Select] Combo box is read as button by Narrator

### ISSUE THREAD

**Issue by dhveerap** [microsoft/fast#3064]
**Describe the bug; what happened?**

Narrator reads select combo box as button instead of combo box.

**What are the steps to reproduce the issue?**
1) Render Select component and use Narrator to navigate to the select menu.
2) It reads out as button collapsed.
3) Repro's in component explorer also - https://explore.edgewebui.net/FastMSFT/components/select

**What behavior did you expect?**
It should read as combo box instead of button.

**If applicable, provide screenshots:**
1) In the below image it reads - Translate Choose a language(aria-labelledby) **button collapsed**
![image](https://user-images.githubusercontent.com/64888708/81148666-501c7800-8f9a-11ea-806d-889b5e0aa683.png)

2) It reads - Country slash region India(aria-labelledby) **button collapsed**
![image](https://user-images.githubusercontent.com/64888708/81148812-9b368b00-8f9a-11ea-9673-6b32bb42a519.png)

**In what environment did you see the issue?**

* OS & Device: [Windows
* Browser [Edge]

**Comment by chrisdholt** [comment]
closed with #3517
