### ISSUE TITLE
Address perf concerns in fast-slider

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#3126]
**Describe the bug; what happened?**
As discussed [here](https://github.com/microsoft/fast-dna/pull/3125#discussion_r424785264), performance issues should be cleaned up in the `<fast-slider>` element:

- Calling `getBoundingClientRect()` during `mousemove` is likely causing a lot of layout thrashing
- Transitioning on `right` property may be gpu-intensive
- Using `transition: all` can lead to unintended style behaviors

**Comment by EisenbergEffect** [comment]
@radium-v Do you recall if this work was ever done or is it still needed?

**Comment by chrisdholt** [comment]
@EisenbergEffect, I believe this was done with #3414
