### ISSUE TITLE
Accessibility: Pane separator should report aria valuemax valuemin and valuenow

### ISSUE THREAD

**Issue by bekell** [microsoft/fast#3231]
As per https://www.digitala11y.com/separator-role/

aria-valuemax (if focusable)
aria-valuemin (if focusable)
aria-valuenow (if focusable)

These values should be set initially, and valuenow should be kept up to date as the slide is moved left/right via keyboard or mouse.

The Pane component: https://github.com/microsoft/fast-dna/blob/master/packages/react/fast-layouts-react/src/pane/pane.tsx

**Comment by roryfa** [comment]
@chrisdholt can we get this triaged and assigned?

I'm sitting on this Edge bug Bug 26436757: Accessibility: Separator should report aria valuemax valuemin and valuenow
