### ISSUE TITLE
Type-ramp values constant when base-type-ramp value is changed in design-system-provider

### ISSUE THREAD

**Issue by SamanthaAO** [microsoft/fast#3233]
**Discussion Topic**
I noticed upon inspecting the marketing site's variables that setting the type-ramp in the design-system-provider seems to be updating the base, but not any of the other increments of type-ramp-font-size. So for the marketing site when we set type-ramp-base-font-size to 16px we actually end up losing the increment of 14px(which was base before) and get a duplicate 16px value in plus-1 and base. I was wondering if there are plans in the future for having the other type-ramp values be based upon the base value, or if the plan was for them to be hard coded? This it to open a discussion on what the plans for type-ramp are so that the marketing site can be best tailored for it. 

**Current Issue:**
![Screen Shot 2020-06-04 at 11 57 25 AM](https://user-images.githubusercontent.com/48499261/83808874-5e79b480-a66a-11ea-9625-948ead05552a.png)

**Comment by nicholasrice** [comment]
Thanks @SamanthaAO

A few questions that are top of mind concerning this, followed by some brainstorming:
1. How do we facilitate type ramp replacement?
2. How do we facilitate type-ramp customization?
3. Do we think these values should be *independent* of one another. *should* setting the base affect every other property?

There are two primary use-cases I see:
**1. Type Ramp Replacement**  
This is the scenario you're trying to achieve for the marketing site. There is a good chance when trying to set the base size, a consumer is *also* trying to scale the ramp according to that base size.

**2. Type Ramp Customization**  
This is the ability to adjust a single type ramp value without affecting the other properties. 

Balancing these two scenarios is tricky. While you might expect changing the base size to affect all other ramp sizes, there also might exist cases where that behavior is undesirable. For example, if I want to raise the base size from the default (14px) to 15px. 

An approach that enables both scenarios would be to abstract type ramp creation:

```js
// Pseudocode
createFASTTypeRamp(16px).entries(pair => {
    designSystemProviderInstance[pair[0]] = pair[1]
});
```
or  we could make this function a method of the provider:
```js
designSystemProviderInstance.setTypeRamp(16px); // Sets all type ramp properties
```

The downside to making this a method is that it would add runtime code to the provider that only *some* instances would need. It also hard-codes *our* opinion of how a type ramp should be generated, but that may not be what everyone wants. The upside is that it makes updating the typeramp easy. A middle ground could be something like the following:

```js
designSystemProviderInstance.setTypeRamp(fastTypeRamp(16px));
```

**Comment by SamanthaAO** [comment]
@nicholasrice 
With the last example that you provided, am I correct in thinking that this would update all type-ramps around the base of 16px, but there would still be the ability to define specific type-ramp values after the function is run and override specific values that the function produces? For example: if you like the spread of type-ramps provided with a base of 16px but you want --type-ramp-plus-6-font-size to be larger, you could used the fastTypeRamp(16px), but also set type-ramp-plus-6-font-size = 80px. Also, would users also be able to provide their own version of fastTypeRamp() to create different increments around a base?

**Comment by chrisdholt** [comment]
Closing given #5853, also given the DSP is considered "legacy at this point"
