### ISSUE TITLE
[Proposal] Add hover treatment to Tree View Item expand / collapse button

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#3262]
**What feature are you requesting?**
A Tree View Item that is a parent node has a button for expanding or collapsing itself. Currently it doesn't indicate its boundary or that it will act differently than clicking anywhere else on the item.

**What would be the benefit of adding this feature?**
Visual feedback that clicking on the caret will function differently than clicking on the row. Note that it would be up to the consumer to decide if the expand / collapse action also performed a selection.

**What solution would be ideal for you?**
The caret button has a backplate that shows on interaction (hover and active).
It's sized to fit within the selection indicator.
All other surface area of the item row acts as a click on the item.

![image](https://user-images.githubusercontent.com/47367562/84203782-e262e080-aa5e-11ea-8787-039d3210633a.png)

Considered making the hit target of the caret button larger, but this would be a divergence from every other component and complicates some of the rules of the system. This seems like a reasonable size considering other interaction patterns available.

**Comment by chrisdholt** [comment]
Thanks @bheston, I'm going to tag this with needs investigation so I can ensure we'd be accessible with these changes. The intent seems clear though :).

**Comment by bheston** [comment]
@chrisdholt we support keyboard navigation, so it should pass accessibility. A top goal is to keep hit targets as large as possible, and though the caret is smaller with this change, it's still as large as checkbox and radio.

**Comment by bheston** [comment]
Also noticed the button is aria hidden anyway.
