### ISSUE TITLE
Components not property re-sizing with width / height CSS

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#3269]
This issue concerns the following components:
- fast-anchor
- fast-button
- badge
- ~text-area~
- ~text-field~

Sizing the above components is difficult because the primary visual element is *not* the host element - the inner "control" part is the element with visual elements. This means that while the host element can be resized, it does not *appear* to be resized.

This work tracks work to make the above components appear resized when they are resized.

**Comment by chrisdholt** [comment]
I noticed today that we have this same problem for button and anchor with color on the components (background, foreground, border...). Something to consider this as we explore fixing this.

**Comment by nicholasrice** [comment]
Noticing a few things upon digging into this.

1. For button / anchor - these components implement an inner `<button>` and `<anchor>` respectively. Because of those inner elements are *actionable* there must be no box-model size difference between the host and the element, otherwise there will exist a clickable portion of the element that does not behave consistently with other clickable portions. The implication of this is that the host cannot contain properties that impact the inner element, such as border and padding.
2. For text-field and text-area, those components implement a *label* slot, where an included label changes the overall height of the host. Sizing the host to size the *input control* is not actually an ideal approach because of that, since sizing the whole element affects both the label and the input control. For this reason I don't think text-field and text-area should be changed.
