### ISSUE TITLE
Docusaurus displays a blank page when clicking the logo link without workaround

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#3299]
**Describe the bug; what happened?**
Discovered in #3295 for the upcoming v2 release: clicking the documentation site's logo will display a blank page unless a workaround is in place. Currently, that workaround is in two parts:

- For production builds: a hard-coded `href` is used and the link opens in the same window
- For development builds, `target: "_blank"` is applied to prevent the blank page from being rendered.

**Comment by EisenbergEffect** [comment]
@radium-v Do we want to continue to track this or do we think our workaround is fine to stay as is? Is there anything we can really do about it?

**Comment by radium-v** [comment]
@EisenbergEffect I think the current workaround is fine (it's definitely not a major breaking bug).

**Comment by scomea** [comment]
Also, the logo on the top left corner of component explorer doesn't do anything.  It should go to the Fast home page (https://explore.fast.design/)

**Comment by chrisdholt** [comment]
Closing this based on the workaround being reasonable as of 2019 and no further action taken here since.
