### ISSUE TITLE
radio-group tabindex not working in cases where the radio items are not fast-radio components

### ISSUE THREAD

**Issue by marjonlynch** [microsoft/fast#3300]
**Describe the bug; what happened?**
When the child items of radio group are not fast-radio elements the tab-index of the selected or first item is not getting set correctly, no tab-index is set.

**What are the steps to reproduce the issue?**

Example:

1. Go to feature branch for feature/fast-frame
2. go to sites/fast-website
3. yarn run start
4. scroll down and change the to the color settings and try to tab to the first radio group of color swatches, no tab-index is set so you can't

The selected radio should have it's tabindex set to 0 by the radio-group

**If applicable, provide screenshots:**
<img width="795" alt="Screen Shot 2020-06-12 at 4 45 38 PM" src="https://user-images.githubusercontent.com/25805778/84554335-39212200-accc-11ea-9f75-9689bec5eb1c.png">

**Comment by chrisdholt** [comment]
@marjonlynch can this be closed?

**Comment by EisenbergEffect** [comment]
@marjonlynch When you're back, let me know if we can close this one out. Thanks!

**Comment by chrisdholt** [comment]
@EisenbergEffect this was closed with #3169
