### ISSUE TITLE
Deprecate React Packages

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#3305]
In the interests of platform alignment and prioritization of Web Components, FAST collaborators are proposing the deprecation of the following packages:

- `@microsoft/fast-components-class-name-contracts-base`
- `@microsoft/fast-components-class-name-contracts-msft`
- `@microsoft/fast-foundation-react`
- `@microsoft/fast-components-react-base`
- `@microsoft/fast-components-react-msft`
- `@microsoft/fast-components-styles-msft`
- `@microsoft/fast-jss-manager`
- `@microsoft/fast-jss-manager-react`
- `@microsoft/fast-jss-utilities`
- `@microsoft/fast-layouts-react`
- `@microsoft/fast-react-utilities`
- `@microsoft/fast-storybook-design-system-addon`
- `@microsoft/fast-storybook-presets`
- `@microsoft/fast-tslint-rules` *this isn't specific to React, just needs to be deprecated*

**Steps for deprecation:**

1. In the interests of preserving the repository history, a fork of the FAST repository will be made under the name **microsoft/fast-dna-react.** The forked repository will be immediately archived using the [github archive feature]([https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories)). The archived repository will exist under the Microsoft domain.
2. The existing FAST repository will add language to the repository README.md that the above packages have been deprecated and can be viewed / accessed from the archived repository. A link to the archived repository will be provided.
3. All of the deprecated packages will have a deprecation notice added to their individual README.md files. The deprecated packages will then be published a final time so the deprecation notice is visible from the NPM registry.

**What about React support?**

FAST intends to support React through an interop layer written as a React component. A good summary of the challenges [can be found here](https://custom-elements-everywhere.com/libraries/react/results/results.html), and our own [investigation summarized here](https://github.com/microsoft/fast/issues/3389).

**Comment by Shivam60** [comment]
i think a link is missing in `A good summary of the challenges can be found here.`

**Comment by nicholasrice** [comment]
It sure was! Thanks @Shivam60 - updated.

**Comment by chrisdholt** [comment]
@nicholasrice, before we deprecate we'll likely need to remove the dependency on `fast-components-styles-msft` from `fast-components-msft`. Do we have an issue tracking that?

**Comment by nicholasrice** [comment]
@chrisdholt I don't think we need to break that necessarily, the deps will install from npm instead. We will probably want to clean that up but I don't think it needs to block deprecation.
