### ISSUE TITLE
Clarify usage of `parseColorString`

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#3375]
There were two pieces of feedback for the `parseColorString` export:
1. It was unintuitive that it would not parse a rgba color string
2. Why did it exist when an author could just use `@microsoft/fast-colors#parseColor`

The answer to 1. is that the code that leverages `parseColorString` will not work correctly with transparent values. However, a rgba color string with an alpha channel of `1` is not transparent - this fn should not throw an error when parsing a `"rgba(r, g, b, 1)"` string. We can also throw a more informative error if the parsed color has an alpha value other than 1.

Regarding 2. - I think this can be clarified in API docs and by changing the fn name to `parseOpaqueColorString`. We can point authors to `@microsoft/fast-colors` for more general parsing needs from that fn.

**Comment by EisenbergEffect** [comment]
@nicholasrice Can this be closed now?

**Comment by nicholasrice** [comment]
It can, I think that function was removed in the 2.0 refactor.
