### ISSUE TITLE
Add a way to default start and end templates in web components

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#3376]
**What feature are you requesting?**
I would like the ability to default the content of the start and end templates when using `endTemplate` and `startTemplate`.

**What would be the benefit of adding this feature?**
This would allow us to continue to use the shared library in cases where we want to default content.

**Comment by chrisdholt** [comment]
@nicholasrice any thoughts on how we can accommodate this given the existing implementation? It seems an initial workaround may be to duplicate the template portion, but I'm unsure if that would have side effects (outside of duplication).

**Comment by chrisdholt** [comment]
This is supported as of the latest version of `fast-foundation` and `fast-components`! 🎉 

Check out a simple example of default slotted content in `checkbox` and more complex examples using ViewTemplates, binding properties, and leveraging methods in `horizontal-scroll`.
