### ISSUE TITLE
Cannot find module in Angular

### ISSUE THREAD

**Issue by ginomessmer** [microsoft/fast#3432]
**Describe the bug; what happened?**
I created a new project with Angular's CLI and added FAST DNA as a dependency. For this, I followed the integration guide step by step, however, once I attempt to build the project with `ng build` and `ng serve`, the compiler says that it cannot find certain modules that are required for FAST DNA. 

**What are the steps to reproduce the issue?**
https://www.fast.design/docs/integrations/angular

```
ng new test-project
npm install --save @microsoft/fast-components @microsoft/fast-element lodash-es
```

```ts
// main.ts
import { 
  FASTDesignSystemProvider, 
  FASTCard, 
  FASTButton 
} from '@microsoft/fast-components';

/*
 * Ensure that tree-shaking doesn't remove these components from the bundle.
 * There are multiple ways to prevent tree shaking, of which this is one.
 */
FASTDesignSystemProvider;
FASTCard;
FASTButton;
```

**What behavior did you expect?**
I expected that the build runs successfully.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/8465892/86370553-2cb33800-bc80-11ea-9dcf-50c2fb68ccb6.png)

**In what environment did you see the issue?**

* OS & Device: Windows 10, WSL 1 (Ubuntu)
* Browser: Edge
* Version 83.0.478.58 (Official build) (64-bit)

**Is there any additional context?**
Spoke to @EisenbergEffect about it on Discord: https://discordapp.com/channels/449251231706251264/482296787021856768/728223388014739457

**Comment by nicholasrice** [comment]
I'm able to repro this and also noticing the same errors in the built d.ts file on master
