### ISSUE TITLE
Clicking outside of an AutoSuggest does not transfer focus if menu was open

### ISSUE THREAD

**Issue by dafang-ms** [microsoft/fast#3434]
**Problem**

If the AutoSuggest input has focus while the suggestions menu is open, clicking outside of the component on the first click closes the menu but does not blur the input.

**Repro**

1. Click on the AutoSuggest component.
2. The suggestions menu should open, and text cursor should be blinking in the input
3. Click outside of the AutoSuggest component.
4. The menu should be closed now, but the text cursor is still blinking in the input.
5. Additional keystrokes will end up displaying in the input

**What behavior did you expect?**

In staying consistent with most browser address bars and search engine search bars (e.g. Google or Bing), clicking away from the component should both close the suggestions menu and blur the input on a single click. Focus should be transferred accordingly as well. Menu closure can continue to be accessible via keyboard actions (e.g. escape key).

**Comment by chrisdholt** [comment]
@scomea can you take a look at this?

**Comment by abhishekjakhar** [comment]
@chrisdholt can I pick this up?

**Comment by chrisdholt** [comment]
I believe @scomea closed this with #3459 - @scomea is this closed?

**Comment by scomea** [comment]
Yes, closing.
