### ISSUE TITLE
Support for Svelte

### ISSUE THREAD

**Issue by BenHayat** [microsoft/fast#3446]
**What feature are you requesting?**
Support For Svelte

**What would be the benefit of adding this feature?**
Svelte suffers from lack of third party UI components. FF Can help use this new set of UI with Svelte

**What solution would be ideal for you?**
Just like you have support for Vue, we should similar installation and support

**What alternatives have you considered?**
Just to stay with Vue and Vue's third part UI components.

**Is there any additional context for your request?**
Please increase the # of components, especially Data Grid,

**Attach screenshots or images add detail to your request:**

**Comment by oVerde** [comment]
@huynhicode pleeeease consider this with tender and care :pray:

**Comment by huynhicode** [comment]
Hi @oVerde, absolutely - support for Svelte is in the pipeline.  🙂

**Comment by frederikhors** [comment]
Why is closed? Where can we find info about it?

**Comment by EisenbergEffect** [comment]
It's closed because the work is complete. We'll be publishing the update to the website shortly, as soon as the build completes and is validated.

In the meantime, you can find Svelte starters here: https://github.com/microsoft/fast/tree/master/examples/svelte-starters and documentation on how to create your own setup here: https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/docs/integrations/svelte.md

**Comment by EisenbergEffect** [comment]
Actually, it looks like there will be a delay in getting this published to the site. But you can use the links above. That markdown file is exactly what would be displayed on the site.

**Comment by WolfspiritM** [comment]
@EisenbergEffect It would be great if you could also provide some information how to use it with sveltekit. I know that sveltekit is still beta but more and more people are going to use it. Cause of SSR this doesn't really work. What I did is using the _layout.svelte file and add:

```svelte
<script lang="ts">
	import { onMount } from 'svelte';
	onMount(async () => {
		const {provideFASTDesignSystem, fastCard, fastButton} = await import('@microsoft/fast-components');
		provideFASTDesignSystem()
			.register(
				fastCard(),
				fastButton()
			);
	});
</script>
```

But not sure if that is the correct approach.

Also: Is there a way to add attribute autocomplete / suggestion to vscode?
It would be great to have a way to e.g. "fast-button" suggest an attribute "appearance".

I got something working by doing the following in the app.d.ts:
```ts
declare namespace svelte.JSX {
	interface IntrinsicElements {
		"fast-button": HTMLProps<HTMLElement> & {
			"appearance": string;
                        ...
		};
	}
}
```

But it would be great if these can be autogenerated somehow.

**Comment by EisenbergEffect** [comment]
We're not Svelte experts and unfortunately haven't worked with SvelteKit. But we'd be happy to take a contribution to the docs for any additional notes related to that. I couldn't say what the best approach would be with that library. We have to rely on the Svelte community to tell us.

There is a work in progress autocomplete. We need VS Code to support the new custom-element.json W3C Community Protocol. Once they do, elements and attributes for web components should "just work".
