### ISSUE TITLE
Azure Portal - Ibiza - Support

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/fast#3447]
FAST is looking awesome, please consider allowing FAST Azure UI custom blades

**Comment by EisenbergEffect** [comment]
@grahamehorner Can you provide some more thoughts on what you have in mind for this?

**Comment by chrisdholt** [comment]
We're over a year without action or response on this so I'm going to close this due to being stale. If there is still an appetite for this, we should consider creating a new feature request in Fluent UI as I believe that would be a better request for that project.
