### ISSUE TITLE
Blade Component

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/fast#3449]
Please consider adding support for Blades (similar to Azure Portal)

**Comment by chrisdholt** [comment]
Thanks @grahamehorner - is this a dupe of #3447 ?

**Comment by grahamehorner** [comment]
@chrisdholt no this is for the development of a blade style component; while the other is to have support for creating Azure Portal (aka project Ibiza) components and may possibly require display system specifically for Azure Portal

**Comment by janechu** [comment]
Due to project re-alignment goals (see #6955) we are not doing component work as part of FAST, if there is interest in the community I suggest creation a project for this component.
