### ISSUE TITLE
Button active color

### ISSUE THREAD

**Issue by arkadiuszwojcik** [microsoft/fast#3451]
Looks like there is some issue with `<fast-button>` color in `active` state. When clicked (active) color stays the same as for `hover ` state or difference in colors between `active `and `hover ` is hard to notice. `<fast-flipper>` for example looks ok, when clicked color becomes darker for a moment.

**Comment by chrisdholt** [comment]
Thanks @arkadiuszwojcik - is this in the `fast-components` or the `fast-components-msft` package?

**Comment by ChristopherHaws** [comment]
I seem to be having this issue too following the getting started guide (pics show blazor version). It seems to be happening reguardless of `fast-components` or `fast-components-msft`

![fast-button](https://user-images.githubusercontent.com/5934505/86879340-b6f40580-c09f-11ea-9836-adc0551339df.gif)
![fast-button-msft](https://user-images.githubusercontent.com/5934505/86879344-b8253280-c09f-11ea-94d8-b3d7a0928c1b.gif)

**Comment by arkadiuszwojcik** [comment]
@ChristopherHaws thanks for screenshots. @chrisdholt I confirm, this issue occurs in both: `fast-components` and `fast-components-msft`

**Comment by chrisdholt** [comment]
thanks @ChristopherHaws and @arkadiuszwojcik - we'll get a fix going for this
