### ISSUE TITLE
Slotted content for a component wrapped inside of design system dark theme does not theme properly

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#3455]
**Describe the bug; what happened?**
I have one template for `<info-pane-slide/>` where all the slotted content is wrapped inside of a Design System provider.

```HTML
<template class="${x => x.layout}">
        <fast-design-system-provider
            class="wrapper"
            background-color="#333333"
            use-defaults
        >
            <slot ${slotted("items")}></slot>
            ${when(
                x => x.layout === InfoPaneSlideLayout.list,
                html` <span class="topic">Topic Titles</span> `
            )}
        </fast-design-system-provider>
    </template>
```

I pass another component as children to the above component. The component seems to theme properly **except** the slotted content of that component.

```HTML
<info-pane-slide>
        <fast-content-card href="#">
            Non varius ultricies risus, faucibus quis rhoncus eget eu ut egestas nullam molestie
            <img slot="background-image" src="https://placehold.it/68x68" alt="placeholder" />
            <fast-attribution slot="attribution">
                <fast-ad-label slot="image">Ad</fast-ad-label>
                Sponsored
            </fast-attribution>
            <fast-button appearance="stealth" slot="actions">
                <svg>
                    <path
                        d="..."
                    />
                </svg>
            </fast-button>
        </fast-content-card>
    </info-pane-slide>
```

Result:
![image](https://user-images.githubusercontent.com/37851214/86941650-074b8180-c0f9-11ea-91fa-232c146e75d0.png)

Interestingly, the path inside the button which is a "..." themes white as if it is on a black background but the back plates do not.

**Comment by EisenbergEffect** [comment]
In my understanding, this is how things work. If the design system provider is in the shadow dom, it will only affect elements that are in that shadow dom (that's there the css properties are flowing through). The elements you are referring to are actually in the light dom; they are only projected into the shadow dom. So, the css properties in the shadow dom don't affect them.
