### ISSUE TITLE
Runtime error in <fast-button> and <fast-anchor>

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#3456]
**Describe the bug; what happened?**

There is a runtime error:
```console
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
```

**What are the steps to reproduce the issue?**

Example:

1. Add <fast-button> to the page using `createElement` or `createElementNS`

**Is there any additional context?**

This appears to be because there is a modification to an attribute in the constructor as indicated by the top answer in this post: https://stackoverflow.com/questions/43836886/failed-to-construct-customelement-error-when-javascript-file-is-placed-in-head

We should not therefore be setting any DOM in the constructor and should wait for the `connectedCallback`.

**Comment by nicholasrice** [comment]
I don't repro this: https://codesandbox.io/s/upbeat-hertz-kkgdb?file=/src/index.ts

Can you add further repro details?

**Comment by chrisdholt** [comment]
@janechu are you sure this repros in `fast-anchor`? I can see where this would be applying in Button as it's form connected and we're setting attributes, but not on `fast-anchor`.

**Comment by janechu** [comment]
This is not yet an issue with published packages, but I am able to repro it locally, I have created a simple test on the following branch by creating a test folder inside `sites`, see: `users/janechu/custom-element-test`

If you install and run that package locally you will see the error.

**Comment by chrisdholt** [comment]
Thanks @janechu, adding @EisenbergEffect as FYI. I'll take a look at the repro you've provided.

**Comment by chrisdholt** [comment]
OK, I think I have this coming in soon.

**Comment by SethDonohue** [comment]
So if we're not using a constructor at all and doing things in the connectedCallback only then we won't run in to this issue, correct?

**Comment by chrisdholt** [comment]
@SethDonohue, it's not a matter of not using a constructor at all, it's a matter of what is being done in the constructor. Specifically, we should avoid using `____.setAttribute()` in the constructor and instead use the `connectedCallback`:
 
An example for a form connected component:
```ts
connectedCallback() {
   super.connectedCallback();

   this.proxy.setAttribute(foo, "bar");
}
```

**Comment by SethDonohue** [comment]
Ok I saw that example in your PR, guess I was just trying to clarify, but I understand it now, thanks!
