### ISSUE TITLE
[fast-divider] separator is spelled "seperator" causing accessibility issues

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#3462]
Note: https://www.w3.org/WAI/PF/aria-1.1/roles#separator

Currently the role is not supported as this is spelled wrong.

**Comment by abhishekjakhar** [comment]
Can I pick this up?

**Comment by chrisdholt** [comment]
@abhishekjakhar I don't think @SethDonohue has started on this - PR is welcome!
