### ISSUE TITLE
ElementStyles.addStylesTo(document) fails in Firefox

### ISSUE THREAD

**Issue by CuddleBunny** [microsoft/fast#3476]
**Describe the bug; what happened?**

```
Uncaught DOMException: Document.prepend: Cannot have more than one Element child of a Document
    addStylesTo styles.js:108
```

**What are the steps to reproduce the issue?**

```js
const someCss = css`
  h1 {
    font-size: 40px;
  }
`;

someCss.addStylesTo(document); // Error
```

**What behavior did you expect?**

ElementStyles are applied to the document.

**In what environment did you see the issue?**

* OS & Device: Windows 10
* Browser FireFox
* Version 78.0.1

**Is there any additional context?**

@EisenbergEffect noted in discussion: The reason is that FF doesn't support `adoptedStyleSheets` (yet). So, it falls back to creating a style element and prepending it to the target node. The problem is that document can only have one body node. So, in this special case, it needs to get the body element and add the styles to that instead.

**Comment by EisenbergEffect** [comment]
Thanks for finding this @CuddleBunny ! I've got this on my todo list now. I'm hoping to get to it tomorrow, but don't hold me to that as I've got a few other things on the list as well 🤣

**Comment by EisenbergEffect** [comment]
Fixed!
