### ISSUE TITLE
Dialog breaks keyboard navigation?

### ISSUE THREAD

**Issue by patrickhlauke** [microsoft/fast#3480]
Going to https://fast.design/docs/components/dialog, it seems that whatever scripting the dialog attaches to the page, it immediately breaks keyboard navigation.

Example:

1. Go to https://fast.design/docs/components/dialog
2. Try to use `TAB`/`SHIFT`+`TAB` to move focus
3. ...nothing happens

**What behavior did you expect?**

Keyboard navigation to work (it works in other pages checked here).

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* Windows
* Chrome, Firefox
* Version: latest stable

**Comment by chrisdholt** [comment]
Thanks @patrickhlauke! I have a couple of ideas as to what this could be. I'll investigate and see if we can get a fix out.

**Comment by chrisdholt** [comment]
A quick update on this - I think that dual instances of `fast-components` and likely the `tabbable` dependency are being loaded. We were calling one in from the CDN to get live code examples, and another was being packaged with the homepage. Dropping the CDN version returned tabbing as expected but doesn't register the elements. I'll work to find a way to reference the package being included and bundled by webpack.
