### ISSUE TITLE
Menu has erratic keyboard behavior, announced by AT as collapsed, can't check radio items

### ISSUE THREAD

**Issue by patrickhlauke** [microsoft/fast#3481]
Trying the menu in https://fast.design/docs/components/menu/, the first time around it seems possible, using `TAB`, to set focus initially to "Menu item 1", then "Menu item 4". Next time around though, only "Menu item 1" takes focus. If tabbing to "Menu item 4", it also then seems to break cursor up/down to move through the menu.

Additionally, at least just checking briefly with Chrome/Firefox and NVDA, menu items are announced as "collapsed", and trying to use `SPACE` to check/select radio menu item doesn't work/just scrolls the page

**What are the steps to reproduce the issue?**

Example:

1. Go to https://fast.design/docs/components/menu/
2. Navigate to the menu using `TAB` (avoiding the keyboard trap that is the live editor)
3. On first `TAB`, focus goes to "Menu item 1"
4. Verify that cursor up/down moves the focus
5. cursor back to "Menu item 1"
6. `TAB` again
7. focus lands on "Menu item 4"
8. try using cursor up/down - note that focus disappears
9. `TAB` out of the menu.
10. reverse `SHIFT`+`TAB` back to the menu
11. note that "Menu item 2" takes focus?

fire up NVDA

12. Set focus to one of the menu items
13. note it's announced as "collapsed"
14. set focus to one of the radio menu items
15. try using `SPACE`
16. note that instead of checking the item, the page scrolls

**What behavior did you expect?**

Consistent tabbing/cursor behavior, menu items not announced as collapsed unless they have a submenu, radio items to be checkable with `SPACE` (and on this last point, the radio menu items are confusing, as they don't seem to visually do anything even for mouse users?)

**In what environment did you see the issue?**

* OS & Device: Windows
* Browser: Chrome, Firefox
* AT: NVDA
* Version: latest stable

**Comment by chrisdholt** [comment]
Thanks @patrickhlauke, I thought we had a task tracking the menuitemradio and menuitemcheckbox designs for the both of these, but it looks like that's missing. I'll add that and link here.

The keyboard behavior detailed in the bug report certainly seems odd and is definitely a bug somewhere. For the NVDA issue, the announcement seems like a bug on the side of NVDA as we appear to be following the roles model and the appropriate structure. We definitely need to get the menuitemcheckbox and menuitemradio behaviors locked and a design implemented and should likely do so as part of the fix for the keyboarding behavior.

**Comment by chrisdholt** [comment]
@bheston Do you have some thoughts on how we could accommodate the design for a menuitemradio and menuitemcheckbox instances? I think the same visual could apply to both (checkmark) but the behavior would be either multiselect or single select. The nuance here is that the menu items support slots for start/end content for glyphs. In our MSFT implementation, considering we have those slots, where would the checkmark go? My initial thought would be to have it be the default slotted content in the "end" slot. Thoughts?

**Comment by bheston** [comment]
@chrisdholt the closest pattern we have for this is tree view. Our selection indicator is a pill more than a check. The benefit of this is it fits in existing margins and doesn't change alignment for every item whether any item in the list is selected or not.
![image](https://user-images.githubusercontent.com/47367562/87206082-d49eb600-c2bd-11ea-8091-7f034c3c2b9f.png)

I agree that the treatment could be the same for single vs. multi-select. The context should be the indicator as to the behavior.

An alternative is at the end as you mention, but that is more disconnected from the text and may be harder to understand. It also would sit in the same column as any chevrons for child menus. I'm not sure it would be the most usable experience, but I'm sure there is a scenario for a checked item with child menus. Maybe turning on a feature and then selecting the mode. This would conflict with a single icon slot on the right.
