### ISSUE TITLE
Not all form associated elements can be required

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#3483]
`FormAssociated` supports the `required` property and attribute. There are cases (notably switch) that *do not* support being `required` per the ARIA spec (#3458). PR #3478 removes the `aria-required` attribute from the template, but the `FASTSwitch` still supports the `required` property and attribute because it extends `FormAssociated`.

We should refactor `FormAssociated` so that properties can be opt-it or opt-out and so that components like `Switch` can form-associated without exposing properties it should not have.

**Comment by janechu** [comment]
Closing per #6955
