### ISSUE TITLE
Upgrade to Webpack 5

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#3490]
# Background

There is currently an issue with `fsevents` which causes us to have to downgrade build servers to Node v10.
See the #3491 for details.

## Requirements

When Webpack 5 is released which removes the use of `fsevents`, upgrade to that version in the repository and remove the downgrade to Node 10 in the `.github/workflows/ci-weekly.yml`.

List of  packages to be updated with webpack 5

![image](https://user-images.githubusercontent.com/14119043/115934829-cbdf3100-a446-11eb-9ede-7b3a8a7fe64a.png)

**Comment by Ibrahimmaga** [comment]
article on web-pack 5 https://frontend-digest.com/whats-new-in-webpack-5-ef619bb74fae

**Comment by awentzel** [comment]
Closing this PR as #3491 as a workaround has been closed.  Additionally, I'll be creating a new milestone/plan for upgrading Web Pack.
