### ISSUE TITLE
Add aria-valueunit attribute to the slider component

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast#3504]
**What feature are you requesting?**
Allow the developer to add a readout, for screen readers, of the unit, set on the slider label. 

**What would be the benefit of adding this feature?**
Having the screen reader tell users the unit of the value, for example,
instead of just hearing the number, "90", the screen reader can say, 90 degrees celsius"
![image](https://user-images.githubusercontent.com/37851220/87342894-dc9a6800-c500-11ea-9717-b1385e4a0358.png)
other units could be "pixels" or "inches" etc.

**What solution would be ideal for you?**
In the slider component, create an attribute called, `aria-valueunit`
```
@attr({ attribute: "aria-valueunit" })
    public ariaValueUnit: string;
```

In the template, we would use `aria-valuetext` so the screen reader will read out a string.
https://www.w3.org/TR/wai-aria-1.1/#aria-valuetext

Adding `ariaValueUnit`
```
aria-valuetext="${x => x.value} ${x => x.ariaValueUnit ? x.ariaValueUnit : ""}"
```

When implementing,
```
<fast-slider 
        id="switcher" 
        orientation="vertical" 
        min="0" 
        max="100" 
        step="10" 
        value="70" 
        aria-valueunit="&#8451;"
>
    <fast-slider-label position="0">
        0&#8451;
    </fast-slider-label>
    <fast-slider-label position="10">
        10&#8451;
    </fast-slider-label>
    <fast-slider-label position="90">
         90&#8451;
     </fast-slider-label>
     <fast-slider-label position="100">
         100&#8451;
    </fast-slider-label>
</fast-slider>
```

**What alternatives have you considered?**
An alternative to doing the ternary option in the template is maybe creating a `nullableStringConverter` for empty strings.
This to help when `aria-valueunit` is not defined.

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by marjonlynch** [comment]
This issue was resolved with the introduction of the attribute valueTextFormatter
