### ISSUE TITLE
CDN Bundle's include duplicate licensing notices

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3521]
**Describe the bug; what happened?**
Microsoft MIT license, is being duplicated in all NPM package bundles

**What are the steps to reproduce the issue?**
View source on the bundles and search MIT to find duplicate notices.

**What behavior did you expect?**
A single notice is ample.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
All

**Is there any additional context?**

**Comment by Ibrahimmaga** [comment]
When I run the application locally, I didn't see any duplicate certificate. Can you reproduce the steps to get the duplicate? witch tool are you using?

**Comment by awentzel** [comment]
Confirmed, not able to replicate.  No longer an issue.
