### ISSUE TITLE
Accordion behaves differently in component explorer than in documentation

### ISSUE THREAD

**Issue by SayusiAndo** [microsoft/fast#3526]
**Describe the bug; what happened?**

In component explorer accordion works like a charm. It is just beautiful.
However in the documentation side it doesn't expand and collapse. It remains collapsed. If I use the code displayed in the documentation side the result is the same on my page.

**What are the steps to reproduce the issue?**

Please check the video here: https://1drv.ms/u/s!AkndgIjnAZNKqhXU9TBejbJdcuzL?e=NjAfPa

**What behavior did you expect?**
I would expect the displayed example in documentation work well.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: MacOS - 10.15.6
* Browser Edge and Chrome
* Version Chrome: 83.0.4103.116; Edge: 84.0.522.40

*Is there any additional context?**
I searched through the issues but no result

**Comment by chrisdholt** [comment]
Thanks for this @SayusiAndo! I believe this is what we happened across yesterday while doing a release review. It's quite possible that #3524 will fix this as much of the breakage we saw on the documentation site was due to some bundling issues. I'll leave this open until we can confirm :).

**Comment by SayusiAndo** [comment]
> Thanks for this @SayusiAndo! I believe this is what we happened across yesterday while doing a release review. It's quite possible that #3524 will fix this as much of the breakage we saw on the documentation site was due to some bundling issues. I'll leave this open until we can confirm :).

Thanks for the quick response!

**Comment by abhishekjakhar** [comment]
Can I pick this up?

**Comment by chrisdholt** [comment]
> Can I pick this up?

@abhishekjakhar i think the work here is already done - we primarily need to just confirm with a test prod bundle. Happy to help find a good issue for you to grab though if you’d like :)

**Comment by abhishekjakhar** [comment]
> > Can I pick this up?
> 
> @abhishekjakhar i think the work here is already done - we primarily need to just confirm with a test prod bundle. Happy to help find a good issue for you to grab though if you’d like :)

I would really love to work on anything, it would be great if you could help me in finding issue on which I can work, really appreciate it.

**Comment by chrisdholt** [comment]
This appears to be resolved for the v1.6.0 CDN bundle via #3524: `https://unpkg.com/@microsoft/fast-components@1.6.0/dist/fast-components.min.js`
