### ISSUE TITLE
Using button @onclick in Blazor throws exception

### ISSUE THREAD

**Issue by limefrogyank** [microsoft/fast#3530]
When you try to attach the click event handler to `fast-button` in a Blazor app, an exception is thrown:
```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
```

To reproduce:
- Create a basic blazor app
- Add `<script type="module" src="https://unpkg.com/@microsoft/fast-components-msft"></script>` to the head of index.html
- Wrap the body contents with `<fast-design-system-provider use-defaults>...</fast-design-system-provider>`
- Add `<fast-button appearance="accent" @onclick=@(()=> { })>Click Me</fast-button>` to Index.razor
- Run the app

You'll see the error in the console and the element fails to render properly.
![image](https://user-images.githubusercontent.com/7821384/87860946-7a71a680-c8f6-11ea-8e6e-01ef994a4edf.png)

**What behavior did you expect?**

If you run v1.4, it renders fine and doesn't throw an exception.  The click handler works as expected:
![image](https://user-images.githubusercontent.com/7821384/87860981-b0168f80-c8f6-11ea-807f-9f2b86e733a3.png)

**In what environment did you see the issue?**

* OS & Device: Windows 10
* Browser Edge
* Version 83.0.478.64

**Comment by limefrogyank** [comment]
I should mention that even though the UI button failed to render, you can still click it and the handler runs!  This example doesn't do anything, but if you have the handler change a string, it will work.

**Comment by chrisdholt** [comment]
Assuming this is the `fast-components-msft` package, I think this is fixed as of #3523. If you import v1.5 of the `fast-components` package, does this repro still? If not, I think this will be fixed in our next release in the coming week.

**Comment by limefrogyank** [comment]
Sorry, you're right. There is no console exception with the plain fast-component package.  It was confusing because of the broken styles.

**Comment by chrisdholt** [comment]
No worries! This was an issue that was missed in the MSFT package - should be updated (hopefully) Monday! Thanks for filing this and confirming for us :)
