### ISSUE TITLE
[Proposal] Add accessibility section to fast component pages

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast#3531]
**What feature are you requesting?**
Add an accessibility section to all of the fast components.
 
**What would be the benefit of adding this feature?**
Having an accessibility section will let developers, PMs, or users, know that we build our components with accessibility in mind and are following the guidelines from the W3C Working Group. We can't assume all authors know about accessibility, so the section will act as a guideline on how to resolve certain concerns and inform what steps we have taken to make the components accessible out of the box.
 
**What solution would be ideal for you?**
- If there are any accessibility concerns for the component, we can state what they are and share ways and best practices to resolve them with code examples. There will also be links to the W3C to give further details on the accessibility specs.
- List out screen readers the components have been tested on, and make note of issues the component may have with a particular screen reader.
- Sharing or making a note that we have built the components with high contrast in mind, by giving options on how they can test high contrast, from the OS level, or to using well known high contrast extensions.
 
**Section Example**
 
#### `<fast-button>`

https://www.w3.org/TR/wai-aria-practices/#button
 
##### Icon button
- When only using an icon on a button, users may not know what the icon means, to resolve this, providing a tooltip whether on mouse hover or keyboard focus, will help inform users what action the button provides.
- Be aware of those using screen readers. The screen reader will read out as "button". But you should also add an `aria-label` attribute your button, so the screen reader will notify the person that they are not only on a button but will readout the string you added in the `aria-label`. A good note to keep in mind is when adding an `aria-label` do not just describe what the button is, but give action to what the button does. For example, "Play your music" or "Submit the form".
 
```html
    <fast-button aria-label="play your music">
        <svg
            width="10"
            height="14"
            viewBox="0 0 10 14"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M10 7L0 14V0L10 7ZM1 12.0781L8.25781 7L1 1.92188V12.0781Z"
            />
        </svg>   
    </fast-button>
```

### Screen readers tested

| Screen reader      | System | Description     |
| :---:        |    :----:   |          :---: |
| VoiceOver      | Mac OS       |   |
| Narrator   | Windows OS        |   |
| NVDA   | Windows        | Does not readout aria label. [https://github.com/nvaccess/nvda/issues/7807](https://github.com/nvaccess/nvda/issues/7807)
| JAWS   | Windows        |   |

**What alternatives have you considered?**
- I would also like to open this request up to all contributors to give feedback or suggestions on what we should also add to the section.
- In addition to adding an accessibility section to our components website. It would be great to add a toggle in our explorer to show the components in high contrast.

**Comment by EisenbergEffect** [comment]
@khamudom Before we put this in place, I thought it might be good to check into what the Fluent UI team is doing in their docs. If we can align on content and/or format, that would a bonus.

**Comment by khamudom** [comment]
> @khamudom Before we put this in place, I thought it might be good to check into what the Fluent UI team is doing in their docs. If we can align on content and/or format, that would a bonus.

Good idea. I'll investigate that. Thanks @EisenbergEffect

**Comment by janechu** [comment]
`@microsoft/fast-components` is deprecated.
