### ISSUE TITLE
Add form-associated components documentation.

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#3536]
We should add documentation to address questions about our form-associated custom elements. We should address:
1. What is form association? What does it enable?
2. Which components are form-associated?
3. Approach to down-level browser support.

**Comment by usrrname** [comment]
Can't wait for this!

**Comment by usrrname** [comment]
Here yuh go: https://stackblitz.com/edit/vitejs-vite-154zcd?file=index.html

**Comment by janechu** [comment]
Closing per #6955
