### ISSUE TITLE
Add [what] to/in [https://www.dropbox.com/s/x61m0vgzp073tgz/SMS%20Backup%2B%20-%20Apps%20on%20Google%20Play.webarchive?dl=0

### ISSUE THREAD

**Issue by msordini** [microsoft/fast#3541]
**What feature are you requesting?**

**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**

**What alternatives have you considered?**

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by EisenbergEffect** [comment]
Closing as spam.
