### ISSUE TITLE
[chore] Create GitHub releases in addition to tags

### ISSUE THREAD

**Issue by amis92** [microsoft/fast#3543]
**What feature are you requesting?**
In addition to creating tags, please create full GitHub releases as well.

**What would be the benefit of adding this feature?**
People who *watch releases* on this repository would be notified.

**What solution would be ideal for you?**
Creating a GitHub release for new package tags, e.g. for 1.6.0 version of all packages create a single 1.6.0 release to notify watchers about it.

**What alternatives have you considered?**
None really, just ignore this request.

**Is there any additional context for your request?**
Currently 55 people are watching, hard to say how many watch just releases - I know I am.

PS Love this, but honestly I think not enough coverage in MSFT media was given on this project. I've randomly stumbled on it a couple of days ago in one of .NET Community Standup streams.

While Beachball doesn't natively integrate with Github releases, the Fluent UI team has created some scripts to facilitate this integration. That implementation could be leveraged in part or in whole to replicate the functionality.

Note GitHub Releases may be going through some future changes so putting this near the end of the backlog.

**Comment by chrisdholt** [comment]
Thanks for the issue @amis92! We've definitely discussed this as we look into how we manage and deploy our packages. While we have some larger long-term goals for updating our release process, there may be some incremental steps we can take to get this out the door sooner.

In terms of your note on coverage, we've only recently started speaking externally and we're glad you found us! I think the work to move the MSFT implementation to Fluent UI with https://github.com/microsoft/fast/issues/3542 will likely lead to a bit more of the coverage you mention :).

**Comment by awentzel** [comment]
This works depends on #3889 and it's dependencies.

**Comment by awentzel** [comment]
This work is now completed and GitHub Releases should be updated nightly or as needed depending on what changes are being made each day.  Thanks.
