### ISSUE TITLE
text-field values are not sent to server Edge and Chrome

### ISSUE THREAD

**Issue by NPadrutt** [microsoft/fast#3544]
**Describe the bug; what happened?**
I have a login page in a asp.net core razor page with a fast-text-field for the username and one for the password. Both have the name and ID set so that they should be mapped to the according Bind Property of the model. When I fill in both values and hit send in FireFox I do get both values in my page model on the server. In Chrome and Edge (Chromium based) both values stay null. When I replace the fast-text-field with a normal input or an bootstrap input it works as expected.

Also maybe related (if it's not let me know and i file a bug for that separatly: Autofilled credentials aren't shown in the text-field aswell. But when I navigate to a page where there are saved credentials in firefox and just click login to submit, I do get the correct autofilled values although in the UI both fields are empty. In Edge and Chrome I get null (as in this case expected since no value is to see as well).

**What are the steps to reproduce the issue?**

Example:

[ReproductionSample.zip](https://github.com/microsoft/fast/files/4968372/ReproductionSample.zip)

1. Open the attached solution and hit debug
2. Start debugging and set a breakpoint in the LoginFast and the LoginBootstrap page
3. Navigate to the LoginFast page fill in some information into the field and hit login
4. See in the debug view that the username and password field in the Input Object are null.
5. Navigate to LoginBootstrap and repeat to see that they are filled there.

**What behavior did you expect?**
Entered value are correctly sent to server.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] Windows
* Browser [e.g. Edge, Chrome, Safari, FireFox]Edge (chromium, Version 84.0.522.40) / Chrome (84.0.4147.89)
* Version [e.g. 1.8.0]

**Is there any additional context?**

**Comment by nicholasrice** [comment]
Thanks for the detailed description @NPadrutt! This looks related to https://github.com/microsoft/fast/issues/3550 - working on a fix now.

**Comment by EisenbergEffect** [comment]
@nicholasrice Can we close this as done now?

**Comment by NPadrutt** [comment]
I had a look at the new version and the main issue, that data isn't sent to the server is fixed. Thanks for that!
The second one I mentioned with credentials not being autofilled (or offered to safe in the browser for that sake) however still exists. Should I create a new seperate issue for that?

**Comment by EisenbergEffect** [comment]
@NPadrutt Yes, if you don't mind, please create a separate issue for the credentials bug. We'll need to do some investigation on that to see if it's something we can fix.

I'm going to close this issue out in favor of the new issue related to creds.

**Comment by NPadrutt** [comment]
Done #3614

**Comment by NPadrutt** [comment]
@EisenbergEffect maybe a stupid question but this was fixed with the 1.7 version of fast-components. I noticed that the error still persists in the latest fast-component-msft package (1.6). Is that because of the transition to fluent and should be fixed with 0.1 once that is live or do I have to create a separate ticket for the fluent package?

**Comment by chrisdholt** [comment]
@NPadrutt I believe the fix was made in foundation so we should see it propagate to the FluentUI package. If you're using NPM you could try to test with that version today. If you're using the CDN link from unpkg, there's a PR up to fix that now.

**Comment by NPadrutt** [comment]
@chrisdholt Ah, I see. I tried the unpkg version, but the. i will try again tomorrow (or when it os fixed).
Thanks for the very quick answer! :)

**Comment by chrisdholt** [comment]
> @chrisdholt Ah, I see. I tried the unpkg version, but the. i will try again tomorrow (or when it os fixed).
> Thanks for the very quick answer! :)

No worries! If we can get the fix in quickly I'll see if I can kick off a publish to get this out today. If not, the Fluent build should publish automatically overnight!

**Comment by chrisdholt** [comment]
@NPadrutt, the CDN link *should* be working now, so you should be able to test. Let me know if you run into problems with the link.

**Comment by NPadrutt** [comment]
@chrisdholt works as expected after adjusting all the components from fast- to fluent-, including the fix for this issue here. thanks! :)
