### ISSUE TITLE
The logo on the documentation pages is pixelated

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3545]
**Describe the bug; what happened?**
The logo in the top left corner is pixelated on all documentation pages and also on component explorer site, both sites.

**If applicable, provide screenshots:**
<img width="579" alt="Screen Shot 2020-07-23 at 4 44 25 PM" src="https://user-images.githubusercontent.com/16669785/88349080-f0fe1200-cd03-11ea-8b80-c43ccb730b2e.png">

**In what environment did you see the issue?**

* OS & Device: [e.g. **MacOS**, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. **Edge**, Chrome, Safari, FireFox]
* Version [e.g. 85]

**Is there any additional context?**

**Comment by JazibJafri** [comment]
May I take this?

**Comment by EisenbergEffect** [comment]
@JazibJafri Absolutely. @awentzel Can you point @JazibJafri to the proper logo resource to use?

**Comment by Falkicon** [comment]
@JazibJafri , I have attached a zip with two SVG logos (one light, one dark). Not sure exactly how Docusaurus has this set up but it appears to swap logos when the light/dark toggle is flipped.

[logo_fast.zip](https://github.com/microsoft/fast/files/5052832/logo_fast.zip)

**Comment by EisenbergEffect** [comment]
There is a config setting in the `docusaurus.config.js` file for this. However, we'll need to get these assets up on CDN as well. @awentzel can you assist with this. This also relates to the asset compression issue we'd like to solve if we can.

**Comment by JazibJafri** [comment]
@Falkicon @EisenbergEffect thanks alot. I will send a PR for this soon.
