### ISSUE TITLE
Add templates to build components for different integrations

### ISSUE THREAD

**Issue by Valks** [microsoft/fast#3557]
**What feature are you requesting?**

I'm looking for a pre-set template with all the typescript compiler, dependency configuration, etc. ready to go along with the necessary integration components for the different integration targets.

**What would be the benefit of adding this feature?**

It would make it significantly easier to consume the FAST platform in custom solutions, especially for those who aren't as comfortable with the typescript environment.

**What solution would be ideal for you?**

In my case, I'm using FAST with Blazor. My ideal solution would be to have a Razor class library which builds and outputs a combined JS file into the wwwroot directory. That way I could add a project reference and add the JS file in my main app and I'd be ready to go.

As an added bonus having a pre-set service to take theme configuration would be nice also (that probably deserves to be a separate NuGet package in itself).

I image a similar scenario could be achieved for other targets, i.e. Aurelia, etc.

**What alternatives have you considered?**

I've tried taking the repo and duplicating the package web-components /fast-components[-msft] and creating a new version with my own suffix to work as a starting point but so far haven't been able to compile successfully.

Also, I've created my own Razor library and added typescript files with my new controls but I ran into trouble when I needed to configure a module system to combine multiple, also referring to the CDN for the library source caused all sorts of headaches.

Lastly, I'm working now to try and build a minimal project which has the necessary build infrastructure setup correctly so that I can then move it into a Class Library (WIP).

**Comment by EisenbergEffect** [comment]
@Valks Can you share a bit more about what you want to accomplish with this integration in the end? Are you trying to build your own design system? Are you trying to build your own components? Do you want a deeper integration with Blazor? Some combination of these things?

**Comment by Valks** [comment]
Sure, I guess the short answer to your question is whatever gives the best experience to consume and extend the fast framework (custom controls). I'm not looking to create the new Bootstrap or Material Design, but I do want to be able to consume a different design system as the fast framework is designed to enable.

In my case, that means creating Blazor Components which implement strongly typed versions of the fast controls (wrapper), a service for setting the design system default properties (accent color, etc.) and a way to build new components that are fully integrated into the fast platform (taking advantage of all the features), i.e. typescript definition following the [fast-element guide](https://www.fast.design/docs/fast-element/defining-elements).

### Project Structure
#### Component Project (template)
```
- Blazor.FastUI.csproj
- wwwroot
  - blazor.fastui.js (compiled js file using the CDN for consumption)
- index.ts (file to export all the controls)
- Controls
  - Anchor.razor
  - Anchor
    - index.ts (element definition)
    - anchor.styles.ts (element unique styles definition)
    - anchor...ts (other files that might help for clarity)
```

#### Configuration Project (NuGet package)
```
- Blazor.FastUI.Configuration.csproj
- FastUI.cs (Service that configures the fastui design system)
- WebHostExtensions.cs (Inject the configuration service)
- wwwroot
  - fastui.configuration.js (javascript interop for configuration service)
```

Currently, I have two projects, one which implements all the available fast components as Blazor Components along with a few extras I expect will make it into the fast project, i.e. toolbar; the other project implements controls from the FluentUI I want to use, i.e. Flex, Popup, Avatar (avatar will have to move after recent spec announcements).

**Comment by EisenbergEffect** [comment]
@Valks Thanks for the additional explanation. It seems like this is maybe a few separate requests that we should break apart and tackle independently. We may also need to partner with some other teams to make some of it happen, as our team doesn't directly do a lot of .NET work. Let me think through this a bit more and get back to you with some thoughts.

**Comment by Valks** [comment]
I agree, as I explored the feature request more it grew into a few distinct parts.

That said, for my immediate needs a simple example of how to get typescript to build a bundled output which ideally references the CDN release would really help.

**Comment by EisenbergEffect** [comment]
@Valks I wanted to double check and see if you had tried copy/pasting the setup for `fast-components` directly. It has the basic setup for producing a fully bundled stand-alone script that includes the components and framework. I think you could set up something like that and then add your custom components. Then have a little something that drops the built script into your Blazor app.

Just trying to think of ways to get you moving forward that aren't delayed by our longer term tooling plans.

**Comment by Valks** [comment]
@EisenbergEffect First off thanks for your help. I gave it another try but ran into difficulties. That said I noticed there is a branch with a Todo sample which I based off with more success: https://github.com/microsoft/fast/tree/users/eisenbergeffect/todo-demo/examples/todo-app-tutorial

I've taken that sample and got it building bundle.js into the wwwroot folder. Unfortunately, it's not doing much after that (has no affect on the output). I saw that it was removing my code so I added calls to stop the tree shaking but that still doesn't seem to be enough. I'll give it another go tomorrow, hopefully it's just a case of more declarations needed to stop it tree shaking away more necessary code.

**Comment by EisenbergEffect** [comment]
Ah, yes. I started putting together a todo example based on a few different requests. I haven't actually run that yet...so there may be some issues with it 🤣  I'm hoping to get it into PR form today. It's quite possible there's a tree shaking issue. Bundlers are pretty aggressive. If you feel comfortable putting together a simple repo on GitHub that shows the most basic version of your setup, I can try to take a look next week and see what's going wrong. Something I can quickly git clone, install, and run would help me greatly.

**Comment by Valks** [comment]
Sure, I've put up a repo with two components: ```FastFlex```, ```FastFlexItem```. The project should trigger npm to build (Task Runner) and deploy the output to the ```wwwroot``` folder. From there the main demo app consumes the output.

To test I've added the ```FastFlex``` element to the main index, it should write hello world! on the screen with world pushed to the far right.

https://github.com/Valks/FastDemo

The main index file is modified in: https://github.com/Valks/FastDemo/blob/master/DemoApp/Pages/_Host.cshtml

I'll be taking another look at it to see if I can figure it out myself but if you have a chance I'd appreciate it.

Also, if you have feedback on how I should have build the elements that would be helpful.

**Comment by Valks** [comment]
Finally got it working :). Seems the last bit I missed is when I declare ```@customElement``` it must be directly before the ```export class ...```

I've updated the sample I put up though I need to work on it a touch more. Once I finish the flex control I'll update that demo with it to complete it.

Thanks for all your feedback and I'm looking forward to seeing more from this project.

**Comment by EisenbergEffect** [comment]
Sounds good. I'll keep this open so we can consider it as part of the docs and CLI planned work.

**Comment by EisenbergEffect** [comment]
Closing this out since there hasn't been activity in a while. Also, since this issue was opened, we've tracked CLI work and features in a dedicated issue and WIP PR, and we've shipped Blazor wrappers for the FluentUI Web Components. Additional integration docs have been added with more being worked on now as well.
