### ISSUE TITLE
Add Realtime editor component (Property panel)

### ISSUE THREAD

**Issue by uabarahona** [microsoft/fast#3558]
**What feature are you requesting?**
Allow the developer to add a component that allows real time modification of the UI, this panel could potentially have all the variables created by the framework or some parent variables that affect the others

![image](https://user-images.githubusercontent.com/15148088/88571468-af26e180-d00b-11ea-8444-a33b7db716d9.png)

**What would be the benefit of adding this feature?**
- It will allow to see bigpicture impact of the modifications we are planning to do
- If there could be a way to save the modifications it can potentially become a theme editor 

And idea of what I am asking is somehow done in the landing page and also have been show on the ASP.NET Stand up:

https://youtu.be/sYTH_xYH3iA?t=2781

![image](https://user-images.githubusercontent.com/15148088/88571677-075de380-d00c-11ea-8afa-432f01a6e1f6.png)

Thanks!

**Comment by EisenbergEffect** [comment]
@barahonajm I'm not sure how soon we'll be able to create an official component for this, but I do have a PR with a demo of how to create your own in the meantime: https://github.com/microsoft/fast/pull/3609

**Comment by barahonajm** [comment]
Awesome! thank you very much for that, I am going to play with FAST during the next days and try to integrate it with blazor and my project  :)

**Comment by EisenbergEffect** [comment]
The PR is now merged 😄  You can find the simple design property panel component code here: https://github.com/microsoft/fast/blob/master/examples/todo-app-tutorial/src/design-property-panel.ts

**Comment by janechu** [comment]
`@microsoft/fast-components` has been deprecated for some time now, closing this issue.
