### ISSUE TITLE
compliance: add footer to all websites

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3579]
1. Https://www.fast.design footer needs an additional URL added to link to trademark and brands.  The link should be named "Trademark" and point to "https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general" 
2. This same entire footer needs to be represented across all websites (https://explore.fast.design, https://create.fast.design, https://www.fast.design https://app.fast.design, https://color.fast.design, https://motion.fast.design)

Refer to the internal compliance work item: https://microsoft.visualstudio.com/edge/_workitems/edit/26058297 

This work should be done by August 1st.

**Comment by chrisdholt** [comment]
@awentzel where is the August 1st date coming from? That is 3 days from now and we have zero time to prioritize this against existing deliverables with a July 31st date. As it stands right now, I can't ensure that this will be done by August 1st.

**Comment by awentzel** [comment]
@chrisdholt this is from legal.  I realize it's late in the game.  The first thing I'm doing is just to identify all of the work.  Then we can determine how/when it gets done and I can communicate that too legal.  I think there is some flexibility.

**Comment by chrisdholt** [comment]
@awentzel, I think we are good for the homepage from what I can tell from a cursory glance. If we can get an extension for the secondary pages (docs footer + explore, etc) and call it August 15th that would help.

**Comment by JazibJafri** [comment]
@chrisdholt Maybe I can take this, with a little help?
