### ISSUE TITLE
Add improvements to the documentation

### ISSUE THREAD

**Issue by litteredwitherrors** [microsoft/fast#3591]
# Documentation Imrovements

I wanted to start the conversation on how we can improve the documentation site. Currently it is difficult for a user to quickly discern what each part of FAST does and whether or not it can help them achieve their goals.

 Here are my are some of my thoughts from the last couple weeks of using the site as a new user.

## Clarity of purpose
It would be beneficial to the user if there was a clear delineation of the purpose of each part of the FAST project.

**Ideas:**
- clear documentation on how to use `fast-foundation`/ what its purpose is
- Create distinction between each part of FAST by creating visually unique identities (iconography, colors, etc.).

## Improved getting started experience
While the current getting started experience does give the user some value, improvements could be made.

**Ideas:**
- Create a guide to building a design system/component library with `fast-element`
- Todo app tutorial
- FAST for React developers (Understanding nuances, limitations and anti-patterns) guide

## Improved references material

**Ideas:**
- Ensure each `fast-component` has all relevant information about its usage

**What would be the benefit of adding this feature?**

A user should be able to come to the site and quickly discern what each part of FAST does and whether or not it can help them achieve their goals.

## Site structure
The site could probably use some improvement to the information architecture of the site. It would be ideal to base the changes off of a proper user study.

**Ideas**
- Create separate pages for `fast-element`, `fast-foundation`, `fast-components` and `fast-components-msft`

**Comment by EisenbergEffect** [comment]
Thanks for the feedback @dlesaca Some of these items are currently being worked on. Here's what we're already up to:

* We've got a new tutorial coming that focuses on using the components a bit more.
* We're working on getting more details into the docs on each component. There's some work with another team we're doing to improve component documentation across the board for all libraries. So, our work is pending our PR being merged there.
* We've got several todos to improve the docs around fast-foundation and design systems.
* I'll be merging a Todo app example shortly. I can look into creating a tutorial around that in the future.
* Additional design work is also being done on the site.
* We've got a new guide to React integration here: https://www.fast.design/docs/integrations/react If you haven't seen that yet, please give it a look and let us know if you have any detailed ideas on how we can improve that.

**Comment by dlesaca** [comment]
Thanks @EisenbergEffect. I assumed many of these things were in motion. Are there any existing issues/todos you can point me to?

**Comment by EisenbergEffect** [comment]
@litteredwitherrors Would you mind creating some specific issues for items we haven't addressed or that we don't have issues to track related to documentation? After that, we should be able to close this issue and just track the individual items. Thanks!

**Comment by EisenbergEffect** [comment]
Ping @litteredwitherrors to create specific issues for any remaining work. Closing this out.
