### ISSUE TITLE
Exposing styles in fast components

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#3593]
**What feature are you requesting?**

I suggest to expose the styles in each components. For example CardStyles in the card component. 

**What would be the benefit of adding this feature?**

Consumers could import them when building new or extending components. 

**Is there any additional context for your request?**

It's already the case for the templates and it's very useful.

**Comment by nicholasrice** [comment]
We had planned to do this but it looks like we haven't done that work yet. Thanks for filing!
