### ISSUE TITLE
Add improved FAST component development guide to the documentation

### ISSUE THREAD

**Issue by litteredwitherrors** [microsoft/fast#3610]
**What feature are you requesting?**

The documentation should have clear instructions on how to contribute changes to the FAST repository.

**What would be the benefit of adding this feature?**

It will make it faster for those who want to contribute to the repo to do so.

**What solution would be ideal for you?**

- Instructions on how to run FAST locally
  - Dependency installation
  - Building
  - Running Storybook

Feel free to comment with other ideas.

**Comment by EisenbergEffect** [comment]
We've got this document in the GitHub repo: https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md which also gets published here: https://www.fast.design/docs/community/contributor-guide

@dlesaca Feel free to contribute PRs to improve this 😄
