### ISSUE TITLE
Please provide road map. Thanks.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3622]
Hi Fast

I am a contributor to [**Pane**l](https://panel.holoviz.org/) which is a framework for creating awesome analytics apps in Python using the tools you know and love.

I run the https://awesome-streamlit.org and https://awesome-panel.org sites.

Panel is a **really powerful framework** if you take a closer look. It runs on the very fast, asynchronous web server Tornado, It communicates via web sockets but can also run on Flask, Django and Voila servers. It provides two way binding between server and client via web sockets and provides easy access to combine the most used python visualization tools. It can also run be used to develop and run in Jupyter users, making it very easy to provide powerful components and apps to the data science community.

But all that **power is hidden**. One of the problems is that it needs a nice set of components and a design system. I have started working on adding support for the Material MWC Web Components. But I can see a lot of really good things about Fast. Just the definition+schema you provide would speed up things. I can also see that you don't build on "older" js frameworks like MWC in reality does. Also the announced support for different design frameworks is really cool.

I can also see that the framework for building web components that you provide could actually be **mirrored in Python** to create web components from python that generate web components via the FAST framework, **bringing Fast components to the world of python, data science and AI**.

So my questions are. **Do you have a road map? What components are coming? What tools are coming? And when?**

If Microsoft was interested in collaborating or providing resources to bring FAST to Python, Panel, data science and AI that might also be interesting. You find my contact details at datamodelsanalytics.com.

**Comment by chrisdholt** [comment]
Hey @MarcSkovMadsen, thanks for dropping a line 😄 !

A true roadmap is something that we've been looking AT. We currently provide insight to our [specs](https://github.com/microsoft/fast/tree/master/specs) and have some of the `fast-element` roadmap in the readme. I do think this would be valuable, it's likely just a matter of getting something designed and prioritizing the work. When you look for roadmaps, aside from components - are there other things you tend to look for from an informational standpoint?

**Comment by MarcSkovMadsen** [comment]
I’m mainly looking for information on

- table
- app bar, sidebar, menu system

And something where i can judge how likely it is that this is also a thing in 2 years: What (ms) products is already using this and which are expected to use within 3 months, 6 months and a year.

For example is this essential for vs code or Blazor?

**Comment by simkimsia** [comment]
I have similar questions as @MarcSkovMadsen 

My priorities are 

A) readonly table how to do sorting filtering and pagination
B) how to use fast to build layouts templates in example driven manner
C) how to introduce fast with existing code bases (I'm running react)

**Comment by SayusiAndo** [comment]
@MarcSkovMadsen Have you seen [this](https://youtu.be/sYTH_xYH3iA)? No roadmap info in it, but the motivation, what problem is solved by having this framework?, is explained well with a good example.

**Comment by MarcSkovMadsen** [comment]
Yes. The video is really, really awesome. And I totally get it.

I believe so much in web components. Maybe because I'm not a traditional front end developer but someone who comes from a data science background. Also because my experience is that in an enterprise is so difficult to get nice looking, branded components if you are not on the main framework. But there are so many other frameworks and use case where the main framework does not make sense. The same in data science where we work in Python and would like to be able to easily create analytics apps powered by Python primarily.

Currently I'm wrapping MWC Components for Panel. But I think that project has not yet released the power of web components. Just a simple thing as providing a bundled set of components from a CDN they don't do. It makes it so easy to web components for alternative use cases and situations. For example static sites like blog posts and also for wrapping with Python, Blazor, Vaadin etc.
