### ISSUE TITLE
Flatten the folder structure of components

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#3641]
# Abstract

There has been some inconsistency when structuring the `src` folders of components where sometimes a flat structure is used for items related to each other (menu and menu-item) and sometimes a nested folder structure is used (accordion and accordion-item). 

These should use a consistently flat structure since nesting can sometimes be subjective.

## Requirements

Change the folder structure in the `packages/web-components/fast-components/src/` and `packages/web-components/fast-foundation/src/` folders from:

```
/accordion
    /accordion-item
/progress
    /progress
    /progress-ring
/tabs
    /tab
    /tab-panel
```

to:

```
/accordion
/accordion-item
/progress
/progress-ring
/tabs
/tab
/tab-panel
```

**Comment by rimildeyjsr** [comment]
@janechu @chrisdholt - can I work on this?

**Comment by janechu** [comment]
@rimildeyjsr go for it!
