### ISSUE TITLE
Add ability to change theme and direction in web components storybook

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#3643]
**What feature are you requesting?**
This would bring the ability to change direction and theme for the component `iFrame` in the web components storybook page. Similar to what we had in React.

**What would be the benefit of adding this feature?**
This would help in testing the components theme and direction support as well as other teams building web component libraries leveraging FAST-Element.

**Comment by janechu** [comment]
@chrisdholt @EisenbergEffect I think there are two ways of resolving this:

1. Inject tooling to allow for dynamic updates to the fixtures while in storybook
2. Simply edit the fixtures files to include visual tests (would make for quite a long fixture file)

A couple things to consider, first how this will affect the use of fixtures down the line, vis a vis screenshots for visual diffing. Secondly, this will potentially result in a circular dependency issue if we use the `@microsoft/fast-tooling-react` package to generate UI as it relies on the `@microsoft/fast-components` now. We could side-step this by creating a web component that specifically tests certain design system attributes/properties and only uses the message system and other utilities in the `@microsoft/fast-tooling` package.

What are your thoughts?

**Comment by janechu** [comment]
Since this does not seem like a tooling specific issue, I have re-worked the area to be for the development environment and re-assigned it to the components project.

**Comment by chrisdholt** [comment]
closing given #5821
