### ISSUE TITLE
Incorrect open and close symbols in accordion documentation

### ISSUE THREAD

**Issue by peteryates** [microsoft/fast#3653]
On the [accordion component page](https://explore.fast.design/components/fast-accordion) the example accordion uses '+' symbols to close segments and '-' symbols to open them. This goes against the convention set by several other design systems and libraries:

* [GOV.UK Design System Accordion](https://design-system.service.gov.uk/components/accordion/)
* [US Web Design System Accordion](https://designsystem.digital.gov/components/accordion/)
* [Foundation Accordion](https://get.foundation/sites/docs/accordion.html)

I think that there may have been an error in creating the example. If not, I'd be interested on seeing research that supports this behaviour.

Not that it really matters, but for completeness, I encountered this with Firefox on Linux.

**Comment by chrisdholt** [comment]
Thanks @peteryates! I can confirm this repros across *all* browsers and OS' 😄
