### ISSUE TITLE
add https support for json-schema validation

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3659]
**What feature are you requesting?**
The AJV Validation code should be upgraded to support https instead of http moving forward.  Http was converted everywhere to use https in the source code for consistency and make sure not external linked to http (less secure) is being done.  Somewhere on ajv-validation.spec.ts support is failing when changing from http to https and this should pass testing.

**What would be the benefit of adding this feature?**
Better security support for HTTPS to bring into compliance https://webscout/#/scans/757563/issues?issueId=3692645 

**What solution would be ideal for you?**
convert all usage of http to https

**Comment by jackrmomo** [comment]
package.json

**Comment by awentzel** [comment]
I tried converting all schemas to use `https` and there was tooling issue that was not compatible.  I believe, if this is needed for schema's, @janechu has built the tool and perhaps can provide further context around if this is needed for schemas and what areas of the project are impacted.

**Comment by robarbms** [comment]
AJV currently does not support schemas using https.

https://github.com/ajv-validator/ajv/issues/1104

**Comment by janechu** [comment]
@robarbms yes, thanks for verifying, @awentzel this is why we cannot change that string.

**Comment by janechu** [comment]
Closing this in favor of #3795
