### ISSUE TITLE
feat: add links to documentation header

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#3666]
The documentation should have the same three links as the home page, except replacing the "Documentation" link with a "Home" link.

**Comment by bw-space** [comment]
Hello, I want to work on this issue, but I am unable to follow, which is the home page, in question? How do I access it?

**Comment by EisenbergEffect** [comment]
* The home page refers to this page: https://www.fast.design/
* On the home page we have header links for "Components", "Documentation", and "Community"
* We'd like to have "Home", "Components", and "Community" on the docs which are here: https://www.fast.design/docs/introduction/
* To fix this issue, we believe a configuration change is needed in our docusaurus config. That file can be found here: https://github.com/microsoft/fast/blob/master/sites/website/docusaurus.config.js

**Comment by bw-space** [comment]
Thanks a lot.

**Comment by bw-space** [comment]
![fast_result](https://user-images.githubusercontent.com/43056530/89858939-7109f000-dbbd-11ea-9ff4-9c0a5bd22435.png)
Is this the expected result?

**Comment by bw-space** [comment]
> ![fast_result](https://user-images.githubusercontent.com/43056530/89858939-7109f000-dbbd-11ea-9ff4-9c0a5bd22435.png)
> Is this the expected result?
![fast_result2](https://user-images.githubusercontent.com/43056530/89859287-48362a80-dbbe-11ea-93cc-55443ab73aa7.png)

Sorry, I am missed the change in positions.

**Comment by chrisdholt** [comment]
@bw-space, I think for the most part that looks good. @EisenbergEffect if the FAST logo takes you to the homepage, do we need a link for "Home"? If we do need "Home" I think the secondary position looks good (updated while I was typing 😄 ).

**Comment by chrisdholt** [comment]
@bw-space let's go ahead and create a PR with it how it is - @EisenbergEffect is ahead of me by about 3hrs so I anticipate in the AM we'll get resolution for whether we need the home link or not (given that the logo goes to the homepage).

**Comment by bw-space** [comment]
ok cool, I am working on it.

**Comment by EisenbergEffect** [comment]
@chrisdholt Per a convo I had with @Falkicon he wanted to have the Home link as well. There was some concern that the logo might not be obvious enough on its own.
