### ISSUE TITLE
feat: docs dark/light toggle should also toggle components

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#3668]
The documentation currently supports a dark/light mode toggle, provided by the underlying docusaurus system. We should try to integrate this such that it switches the FAST components used in the docs into their corresponding dark/light themes as well.

**Comment by bw-space** [comment]
Can I work on this issue?

**Comment by EisenbergEffect** [comment]
I'd be happy to have your contribution on this @bw-space 

This is a tricky one because the documentation is built with Docusaurs at prensent, and it is Docusaurus that provides the theme switcher. So, we would need to find a way to tie into that and have the change in documentation theme affect the design system provider that is present on the page.

**Comment by bw-space** [comment]
Thanks, I am looking into it, and will update you as soon as I find a way.

**Comment by janechu** [comment]
Per #6955 we are no longer showcasing design systems or components, the `@microsoft/fast-components` package has been deprecated for some time now.
