### ISSUE TITLE
bug: account for Chromium adopted styles sheets bug

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#3670]
Here's a reference to the platform issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=1111864#c2

To manage this, we can keep a manual list of all styles added to a component in the controller. If we're running in adoptedStyleSheet mode, then during connect we can simply assign the array again. More to it than that, but it's a basic idea for the solution.

**Comment by ben-girardet** [comment]
Oh wouaw just ran into this bug with an Aurelia application and `if.bind` usage. Exemple:

```html
<fast-button click.trigger="showTemplate = !showTemplate">Togge</fast-button>
<fast-button if.bind="showTemplate">I am a fast button</fast-button>
```

![fast-toggle-button](https://user-images.githubusercontent.com/4275071/90306928-40ce9400-ded2-11ea-9195-64d8e16acdb3.gif)

Is there any current workaround ?

**Comment by EisenbergEffect** [comment]
No workarounds yet, but was hoping to work on a fix in the coming week. Can you confirm that it does function correctly on FireFox, just so we know it is the Chromium issue and not something else?

**Comment by ben-girardet** [comment]
I didn't try with Firefox but I did try with Safari and had no issue. I'm highly confident that it's the Chromium issue.

**Comment by EisenbergEffect** [comment]
That sounds like the issue then. Thanks for confirming.

@ben-girardet Any chance you can attach the repro you used to validate this? That would be handy in testing the solution I have in mind.

**Comment by ben-girardet** [comment]
Sure @EisenbergEffect here is a small repro: https://github.com/ben-girardet/fast-chromium-bug-repro

You'll see that I added routes pointing to modules with different `<fast-design-system-provider>`. This was an attempt to repro another (quite similar) bug I had with design systems where they would display correctly the first time but not if I routed away and back. Unfortunately I couldn't repro this bug so you can ignore the routes. If I get the design system bug again I'll try to repro it immediately.

Anyway thanks a lot to look into this.

**Comment by EisenbergEffect** [comment]
Thanks!

**Comment by EisenbergEffect** [comment]
@ben-girardet I'll be sending a PR for fast's template compiler shortly. However, this is a bug in Aurelia as well. I've alerted @fkleuver to the issue. So, this is something that you'll need to wait on the Aurelia fix for. Note to Fred: This isn't fast-specific. Anything that is using adoptedStyleSheets (web component or not) will break with Aurelia until this is fixed. It's a one line fix in the template compiler.

**Comment by ben-girardet** [comment]
Thanks for this !
