### ISSUE TITLE
Review, identify, and resolve compliance issues

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3675]
Continue managing the review and auditing for security, privacy, and accessibility to identify and create new issues that are required for compliance by Microsoft.

WebScout, GTMetrics, Website Compliance, and among other tools.  All tools and internal CELA requests in need of action will be represented by a GitHub Issue.

### Webscout Bugs & Exceptions
Exceptions as a result of inaccurate reporting from Webscout.  These can be ignored, referenced hear for documentation only.
1) https://msazure.visualstudio.com/One/_workitems/edit/7947911
2) https://msazure.visualstudio.com/One/_workitems/edit/7947901
3) Anonymous Access is by design
4) https://msazure.visualstudio.com/One/_workitems/edit/7948907 
5) https://msazure.visualstudio.com/One/_workitems/edit/7949092
6) https://msazure.visualstudio.com/One/_workitems/edit/8026423
7) https://msazure.visualstudio.com/One/_workitems/edit/8026386
8) https://msazure.visualstudio.com/One/_workitems/edit/8026226

### Closed
Closes #3658 #3671 #3680 #3579

**Comment by Abu441** [comment]
G

**Comment by Abu441** [comment]
> G

**Comment by Abu441** [comment]
[[]()]()

**Comment by awentzel** [comment]
Perform a new scan post-release on [Webscout](https://webscout/#/scan-configs/143021)

**Comment by chrisdholt** [comment]
@awentzel if this is dependent on the release, should it be listed as part of the release right now?
