### ISSUE TITLE
Fast brand image is not displaying from LinkedIn

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3679]
**Describe the bug; what happened?**
When adding a link to FAST on LinkedIn, the image is not loading.  We should make sure we have correct implementation so that linking to our site will preload the brand graphics in sites like LinkedIn and any other social media site to help with marketing.

![Screen Shot 2020-08-10 at 3 28 19 PM](https://user-images.githubusercontent.com/16669785/89837627-37ce7300-db1e-11ea-8e2d-286abb2d5169.png)

**What are the steps to reproduce the issue?**
1. Click to edit experience on your LinkedIn profile
2. Scroll to click "Link"
3. Add "https://fast.design"
4. Notice the image doesn't prepopulate and it should.
5. Click save and notice image is still blank.
6. When saving again to see within your experience of your profile still blank.

<img width="754" alt="Screen Shot 2020-08-19 at 10 58 23 AM" src="https://user-images.githubusercontent.com/16669785/90672459-02efa980-e20b-11ea-9c6d-f0a98d7b9fda.png">

**What behavior did you expect?**

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Is there any additional context?**

**Comment by chrisdholt** [comment]
Any insight here @awentzel? I don't see this issue when linking on other social media sites - is this an issue within the repo?

**Comment by awentzel** [comment]
I'm not sure if metadata is missing to support LinkedIn in our page html or something else.

**Comment by brookdozer** [comment]
LinkedIn's [post inspector](https://www.linkedin.com/post-inspector/) gives a warning for https://www.fast.design - og:image tag is needed.

**Comment by awentzel** [comment]
Thanks @brookdozer, Also, this for additional details https://stackoverflow.com/questions/10042786/how-to-successfully-implement-ogimage-for-the-linkedin/25093272#25093272

**Comment by awentzel** [comment]
Hi @brookdozer, I noticed this was assigned to you and curious how this is coming along?  Would be great to fix this so our profiles could reflect FAST to obtain further reach on the web. Thanks

**Comment by brookdozer** [comment]
@awentzel - Got distracted by other work. I'm on it today

**Comment by brookdozer** [comment]
This was fixed by #3821 . 

Image still doesn't appear during editing but it does once you save

Editing:

![linkedinEdit](https://user-images.githubusercontent.com/20569231/92965984-904da480-f42b-11ea-9ba7-6df410fc3067.png)

Saved:

![LinkedinSaved](https://user-images.githubusercontent.com/20569231/92966124-cc810500-f42b-11ea-8bf7-aa583dfae8ae.png)
