### ISSUE TITLE
issue with autofocus in text-field

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#3685]
**Describe the bug; what happened?**

When I use a `<fast-text-field>` with `autofocus` (`<fast-text-field autofocus>`) I get issues with the rest of the application. My use case is an Aurelia 2 project where using the `autofocus` interferes with the routing. I had a similar issue when using `autofocus` inside a `<fast-dialog>` where the autofocus would not work.

In both scenario, if I do the focus manually myself after a 50ms timeout (with `myElement.focus()`) then it works as it should.

[I suspect that the `focus()` is called a little too early here. ](https://github.com/microsoft/fast/blob/2879571796f210da49be8df90a74faee429bd34b/packages/web-components/fast-foundation/src/text-field/text-field.ts#L208)

**What are the steps to reproduce the issue?**

* Maybe set up a page with a `<fast-text-field autofocus>` inside a `<fast-dialog hidden>`
* And then show the fast dialog and check if everything works fine, including the focus of the text field

**What behavior did you expect?**

* autofocus should work
* autofocus should not cause any issues with the rest of the app

**In what environment did you see the issue?**

* MacOS
* Chrome
* Aurelia 2 project

**Comment by marjonlynch** [comment]
Hey @ben-girardet, I'm not sure if the dialog example is the best way to repro this issue, if I put a standard <input type="text" autofocus /> element in it doesn't get focus after showing the dialog from a hidden state. Maybe this is an issue with dialog but fast-text-field seems to not be the culprit. However, I did try putting the focus (which is in connectedCallback) inside a Dom.queueUpdate block, wondering if you can check if this fixes the issue in your case?

**Comment by ben-girardet** [comment]
Thanks @marjonlynch for having a look at this. What's the best way to try a specific PR in a project ? I'm planning to copy paste the component in my app `src` project for an import from there. If there is another simpler way I would be interested ?

Will give you a feedback in a moment...

**Comment by ben-girardet** [comment]
@marjonlynch as far as I could test with the copy/paste => yes it fixes the issue ! Thanks :-)

**Comment by marjonlynch** [comment]
Sweet! Glad to help
