### ISSUE TITLE
Tab animation glitch in Tabs component when I use key home and key end

### ISSUE THREAD

**Issue by tbetous** [microsoft/fast#3692]
**Describe the bug; what happened?**

In tabs component there is a glitch when I use home key or end key. The line under the title goes too far. Plus when you key down one more time and the line is well placed, the line move in the wrong place.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4435536/89946044-9846d880-dc22-11ea-8fe8-d5b7c989d4f5.gif)

**What are the steps to reproduce the issue?**

Example:

1. Go to https://explore.fast.design/components/fast-tabs
2. Click on focus on the first tab
3. Key down end touch (you can observe the glitch)
4. Key down end touch (you can observe the line is wrongly placed)

**What behavior did you expect?**

It should not have a glitch, plus the line should not move when it is rightly placed.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: MacOS on PC
* Browser Mozilla FireFox
* Version 80.0b3

**Is there any additional context?**

**Comment by tbetous** [comment]
If it's a bug, I volunteer to resolve it ! ✋

**Comment by chrisdholt** [comment]
Thanks @tbetous - this definitely looks like a bug and we would love you to take this on!

**Comment by chrisdholt** [comment]
@tbetous assigned to you 👍 - Thanks!

**Comment by EisenbergEffect** [comment]
Thanks @tbetous !
