### ISSUE TITLE
Favicon.svg is not loading

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3695]
**Describe the bug; what happened?**
All tabs are now having trouble loading favicon.svg which network trace says is blocked.

**Comment by Falkicon** [comment]
@awentzel, seems to be loading fine for me in Edge/Windows.

![image](https://user-images.githubusercontent.com/943328/89984335-165cac80-dc2e-11ea-8772-dac011476629.png)

**Comment by awentzel** [comment]
This is caused from Express Helmet middleware by default securing Consent Security Policy in such a way that blocks certain types of images/assets/xml/etc.  It's fixed in most sites, but, there is a bug currently on https://fast.design where I'm unable to clear cache on our load balancer so can't get the file to flush.  However, the release tomorrow should generate new static files to be cached and the old will fall off.  So this will rectify itself after deploy or Friday if no release when cache expires.

**Comment by awentzel** [comment]
Upon confirmation post-deploy, this will be closed.

**Comment by awentzel** [comment]
The cache appears to have flushed on AFD and Favicons are now loading as expected again.
