### ISSUE TITLE
Improve performance by avoiding CSS applied via @import

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3706]
## Problem
The following external stylesheets were included in https://use.typekit.net/spx2dgm.css using @import.  This is both a UX issue depending on what's in the style sheets as well as a performance issue caused by additional latency which could be avoided.

- https://p.typekit.net/p.css?s=1&k=spx2dgm&ht=tk&f=14032.14034.14036.14038&a=47677730&app=typekit&e=css

## Reason
CSS @import allows stylesheets to import other stylesheets. When CSS `@import` is used from an external stylesheet, the browser is unable to download the stylesheets in parallel, which adds additional round-trip times to the overall page load. 

The browser must download, parse, and execute first.css before it is able to discover that it needs to download second.css.

Reference: https://gtmetrix.com/avoid-css-import.html 

## Solution
Purchase the font for each font-weight in use, remove imports, host on FAST CDN.  Fixing this will boost our GTmetrix score by 8 points on this metric and increase page load speeds by 100ms or 25% faster.

**Comment by chrisdholt** [comment]
This is primarily an issue of needing a licensed font which has to (currently) be delivered via a specific CDN. @Falkicon for awareness on this. I think the perf optimization is the primary concern here; I'm less concerned with loading an external stylesheet as it pertains to fonts and more concerned with not having the import stantement blocking render.

@awentzel as an FYI, using the `@` decorator tagged an unknowing GH user ;)

**Comment by awentzel** [comment]
My recommendation is to get our own license from another vendor and host it on our CDN where we control all end-to-end.  This protects us against outages which could result in cloud license issues or payment problems, removes their tracking logic, decrease network latency, reduce the file size since these are not compressed, and compress with Brotli (the best).  I'd wouldn't implement without running some perf tests as well.  but, these two files today are the biggest we have except our main js.

**Comment by awentzel** [comment]
@chrisdholt to investigate font usage, if there is a compressed version of the fonts that could be referenced and if there is a way to implement without `@import`, and what the cost would be to purchase outright for our ownership on the web.

**Comment by awentzel** [comment]
Pushing out one release on behalf of Chris given he's OOF at the moment.

**Comment by awentzel** [comment]
The Security team has approved suppression so closing this issue.
