### ISSUE TITLE
bug: switch fast frame menu demo to use fast-divider

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#3722]
The home page FAST Frame demo menu is using an `hr` instead of a `fast-divider` which causes some visual inconsistency with respect to spacing. We should switch this to use a `fast-divider`.

**Comment by rimildeyjsr** [comment]
@EisenbergEffect - can I work on this?

**Comment by chrisdholt** [comment]
Hey @rimildeyjsr - I believe we merged a fox for this Friday, this should show as closed.

**Comment by chrisdholt** [comment]
Closed by #3726

**Comment by rimildeyjsr** [comment]
Cool, no issue! :)
