### ISSUE TITLE
Add 404 error page to Express service for websites

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#3727]
**What feature are you requesting?**
The `fast.design` website and all subdomains currently have no route for a 404 error page.

**What would be the benefit of adding this feature?**
A 404 route in the Express configuration would prevent any missing route (ex. `https://fast.design/this-does-not-exist`) from resolving with a 200 OK status.

**What solution would be ideal for you?**
A new design should be made for a simple 404 page that gets displayed whenever a route can't be resolved. An even simpler 500-level page should also be made.

**What alternatives have you considered?**
404 not found

**Is there any additional context for your request?**
The `express-history-api-fallback` import may need to be configured to handle things correctly depending on the environment it's loaded into.

Additionally, 500-level routes will need to be addressed as well due to [the way Express handles "missing" routes](http://expressjs.com/en/starter/faq.html#how-do-i-handle-404-responses).

**Attach screenshots or images add detail to your request:**
![image](https://user-images.githubusercontent.com/863023/90297038-1e8d3580-de42-11ea-9d0c-ee6d8cc3d381.png)

**Comment by chrisdholt** [comment]
Let's call this "Planned", though I think we need to start with a design 👍 . Thanks @radium-v!

**Comment by janechu** [comment]
This is now being handled by Docusaurus when the update to v3 occurs.
