### ISSUE TITLE
Add collapsible component

### ISSUE THREAD

**Issue by hardikpthv** [microsoft/fast#3731]
**What feature are you requesting?**
collapsible component

**What would be the benefit of adding this feature?**
This could be used to show or hide extra information on button click. It's similar to accordion but independent of the header where the header is button itself an invoker.

**What solution would be ideal for you?**
I can create this component and submit the MR,

**What alternatives have you considered?**
None yet.

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**
To give an idea:
![image](https://user-images.githubusercontent.com/9882972/90389678-4a9af780-e08a-11ea-9322-5e53c7007049.png)

**Comment by chrisdholt** [comment]
Hey @hardikpthv thanks for this request. Do you see this control mapping to the [WAI-ARIA specifications "Disclosure" model](https://w3c.github.io/aria-practices/#disclosure)?

**Comment by chrisdholt** [comment]
@hardikpthv Thanks for following up - I think the first action here would be to create a [new spec](https://github.com/microsoft/fast/tree/master/specs#specs) prior to starting on the work. That will help walk through some of what you've already articulated here. We do have a standard template you can use as well, which can be found [here](https://github.com/microsoft/fast/blob/master/specs/template.md).

As for the name, our preference is typically to map to the W3C specification if there is one. What we'd be defining at the "foundation" level is essentially a template and js class for the disclosure pattern.

**Comment by hardikpthv** [comment]
Thanks, @chrisdholt. I will go through the template and create the spec for the same.

W3C: https://www.w3.org/TR/wai-aria-practices-1.2/#disclosure
It looks like it can be named the `disclosure` component then.
