### ISSUE TITLE
Add support for text in slots to Explorer

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#3732]
**What feature are you requesting?**

Currently in Explorer it's possible to add "Text" elements as the content of a slot, say for a fast-button, however it isn't marked to appear in the correct slot.

**What would be the benefit of adding this feature?**

It makes the tool look like it's broken. We should wrap it in whatever is necessary to make it appear in the correct slot.

**What solution would be ideal for you?**

Possibly wrapping text in a span, but anything that works is fine.

Slots with "Text":
![fast-button slots-text](https://user-images.githubusercontent.com/47367562/90444620-08c27f00-e093-11ea-8989-4e09345c54a4.png)

Slots with fast-badge:
![fast-button-slots-badge](https://user-images.githubusercontent.com/47367562/90444645-1546d780-e093-11ea-82b0-3143fc2c621a.png)

**Comment by janechu** [comment]
In order to do this we should:
- Ensure we cannot add text to any other slot than the default
- Create a configuration for the span (and other elements) so that when added there is some content

**Comment by chrisdholt** [comment]
@janechu are we still tracking this as an issue? Just wanted to check if it's still open or if we can close it out

**Comment by chrisdholt** [comment]
closing given #5853
