### ISSUE TITLE
Add "accent stealth" appearance and color recipe

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#3734]
**What feature are you requesting?**

The current "stealth" appearance is neutral color only. Add the necessary color recipe for accent-fill-stealth and a shared appearance / style set for accent-stealth that mimics the neutral stealth behavior.

**What would be the benefit of adding this feature?**

This is a common treatment for buttons that are not primary actions but that are intended to be differentiated from other neutral content.

**What solution would be ideal for you?**

A new color recipe and a new fast-button appearance.

The recipe will need its own set of offsets, but start with the values used for neutral stealth. The rest color will need to be transparent if the offset is 0 otherwise some scenarios will cause a light accent color to show over a light neutral color, thus not being completely "stealth". If someone configures the design system such that this offset is _not_ 0 they are accepting that fact, so use the color from the ramp. I believe we can return a transparent color from the recipe to encapsulate that functionality so it doesn't affect the remainder of the button style.

**What alternatives have you considered?**

I'd prefer to avoid handling it in custom code as a one-off because this ties in well with the evolution of the color system in regards to handling lighter colors and upcoming opacity support.

**Attach screenshots or images add detail to your request:**

Here's an example from Outlook web access:

![image](https://user-images.githubusercontent.com/47367562/90449594-9e164100-e09c-11ea-96d3-f667fb9b8db4.png)
[ rest | hover | rest ]

**Comment by chrisdholt** [comment]
@bheston will this be for the FAST Frame design system or is this intended to support Fluent? If Fluent, we'll want to add this to the Fluent UI repo and close this instance.

**Comment by bheston** [comment]
Yep, closing and moving.
