### ISSUE TITLE
Fast-text-field does not correctly report elements validity (chrome)

### ISSUE THREAD

**Issue by dcharbonnier** [microsoft/fast#3761]
Fast-text-field does not correctly report elements validity on Chrome 84

Chrome : Version 84.0.4147.105 (Official Build) (64-bit)

Test :
```
<form>
    <fast-text-field placeholder="username" name="username" required></fast-text-field>
</form>
```
```
> const fastTextField = document.querySelector("body > fast-design-system-provider > form > fast-text-field")
> const fastTextFieldInput = document.querySelector("body > fast-design-system-provider > form > fast-text-field").shadowRoot.querySelector("#control")
> fastTextField.validity.valid
> true
> fastTextFieldInput.validity.valid
> false
````
I expect  `fastTextField.validity.valid === fastTextFieldInput.validity.valid` to be `true`

**Comment by dcharbonnier** [comment]
@EisenbergEffect I don't think, #3483 is quite different. 
I made more investigations, and this could be a Google Chrome bug, with FF this code is working (to be confirmed) and I couldn't find anything wrong on the way Fast is implementing this.

For now I'm fixing it doing `this.elementInternals?.setValidity(this.control.validity, this.control.validationMessage)`  on valueChanged. Not a long term solution, just a temporary hack.

**Comment by nicholasrice** [comment]
I think this is a bug in FAST, not Chromium. FF works because FF doesn't support form-associated custom elements; the form is checking validity of the proxy element which is a native `input[type=text]`, not the custom element itself.

@dcharbonnier I actually think your "temporary hack" is fundamentally the only fix. It is the responsibility of each custom form component to determine when it is valid and when it is invalid, and to inform the platform of that state when/if it changes.

**Comment by nicholasrice** [comment]
One solution here is to create a set of constraint-validation mixin classes that can be used to for fast-text-field (and other  custom elements that serve as drop-in replacements for native elements). These would match and meet the requirements for the [native validity attributes](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Validation-related_attributes). This would look something like:

```ts
export abstract class RequiredValidator {
    public abstract value: string;
    public abstract required: boolean;
    public abstract setValidity: ElementInternals["setValidity"];

    protected validateRequired() {
        return this.value.length > 0;
    }

    protected setRequiredValidity() {
        this.setValidity({valueMissing: this.validateRequired()})
    }
}
```

Each supported validator would then get wired into a dependent component (pseudo code):

```ts
class TextField extends FormAssociated {
  // ...
  requiredChanged() {
    this.setRequiredValidity();
  }

  //...
  valueChanged() {
    this.setRequiredValidity();
  }
}

applyMixin(TextField, RequiredValidator);
```

I briefly considered using the internal `<input>` as the source-of-truth and reflecting validity state *from* it to the custom element but there are a few challenges with that:
1. It isn't a solution for custom elements that don't have internal input elements to reflect from
2. It creates a potential for race-cases, where validity is being tested after properties on the custom element are set but before the template has updated (before the "source of truth" gets new attributes / properties / validity)
