### ISSUE TITLE
Add new component specification: Pagination

### ISSUE THREAD

**Issue by hardikpthv** [microsoft/fast#3765]
**What feature are you requesting?**
Pagination component

**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**
I can create this component and submit the MR,

**What alternatives have you considered?**
None yet.

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**
To give an idea something like this:

### < 1 ... 17 18 19 20 >

**Comment by rinaok** [comment]
Is there any update on the pagination component?

**Comment by janechu** [comment]
`@microsoft/fast-components` has been deprecated for some time now and per #6955 we are focusing on underlying architecture and not component libraries themselves.
