### ISSUE TITLE
Comments in html templates cause directives to not process

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#3777]
**Describe the bug; what happened?**

If there is a comment within an html template, any directives after the comment do not render.

**What are the steps to reproduce the issue?**

Render this component:

```ts
import { FASTElement, customElement, css, html, repeat, observable } from "@microsoft/fast-element";

const template = html<CommentTest>`
  <div>
    <p>Items:</p>
    <ul>
      ${repeat((x) => x.items, html<string>`<li>${(x) => x}</li>`)}
    </ul>
    <!-- Here is a test comment. With it the repeat will not render. Remove it and it will. -->
    <p>After the comment:</p>
    <ul>
      ${repeat((x) => x.items, html<string>`<li>${(x) => x}</li>`)}
    </ul>
  </div>
`;

const styles = css`
  :host {
    display: block;
  }
`;

@customElement({
  name: "comment-test",
  template,
  styles,
})
export class CommentTest extends FASTElement {
  @observable items = ["red", "green", "blue"];
}
```

![image](https://user-images.githubusercontent.com/47367562/91215575-8e64b100-e6c9-11ea-8c03-f254377e9cff.png)

**What behavior did you expect?**

The list to render a second time.

**Comment by EisenbergEffect** [comment]
Ok, tracked down the issue. Fix is easy (delete 2 unnecessary lines), testing is a bit more difficult. I should have a PR for Thursday's release.
