### ISSUE TITLE
Button has odd focus behavior when adding padding

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#3790]
**Describe the bug; what happened?**

![](https://cdn.discordapp.com/attachments/482296787021856768/748249351125467217/unknown.png)

The above SS has padding applied to the `fast-button` host. This causes the focus rect to draw inside the box of the host because focus is *actually* on an internal button element. We should move the focus rect to the host element and use `:focus-within` to account for this.

**Comment by chrisdholt** [comment]
Let’s remember to include “fast-anchor” as part of this as the styles are shared.

**Comment by CuddleBunny** [comment]
@chrisdholt - The affected styles are shared so the fix will apply to both.

**Comment by nicholasrice** [comment]
As discussed in #3792, the problem with my proposed approach is that `:focus-within` does not follow the same selection rules as :focus-visible.

Instead, the developer should set padding on the internal button element using CSS parts:

```css
fast-button::part(control) {
  padding: 12px
}
```

We can re-visit this if we ever get a `:focus-visible-within` selector
