### ISSUE TITLE
Glyph to see password in text-field is not respecting dark mode in explorer

### ISSUE THREAD

**Issue by marjonlynch** [microsoft/fast#3798]
When looking at text-field component in password mode in fast-component-explorer 

**What are the steps to reproduce the issue?**

Example:

1. Go to text-field in fast-component-explorer 
2. change the text-field into password mode/type
3. change to dark mode
4. start typing in the text field

observe the little eye glyph to the left side of the text-field.
<img width="330" alt="Screen Shot 2020-08-27 at 11 55 57 AM" src="https://user-images.githubusercontent.com/25805778/91484045-758d0480-e85d-11ea-9907-760d78ee986c.png">

Expect that to change the fill to a color appropriate for dark mode

Mac, Edge browser (released)

**Comment by khamudom** [comment]
This is a platform issue. Until we are able to change the color, this bug is currently blocked.
I created an issue for the platform team.
29031796

**Comment by bheston** [comment]
I just checked into this and followed up with the platform team again. There is currently a way to set the background color of the button, but I haven't found a way to update the foreground color yet.

**Comment by chrisdholt** [comment]
Closing as the components package has been deprecated
