### ISSUE TITLE
Component stories should use semantically correct headers

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3812]
Many of the demo "stories" for fast-components use headers in a non-semantic way in that they progress directly from an "h1" tag to an "h4" tag.  Progression should follow the appropriate steps ie. h1 -> h2 -> h3.

Example:
https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/accordion/fixtures/base.html

**What behavior did you expect?**
Linear progression of tags

**Comment by SethDonohue** [comment]
I'll get this done
