### ISSUE TITLE
PeerDependency of Lodash is missing in the foundations

### ISSUE THREAD

**Issue by gqio** [microsoft/fast#3825]
Lodash is declared as peer dependency inside components package.
But it's used inside foundations and the declaration of the dependency is missing.

it's imported from here https://github.com/microsoft/fast/blob/0530a4230946d2aee39861001f3deea3b8816038/packages/web-components/fast-foundation/src/menu/menu.ts#L2

but not present in the package.json 
https://github.com/microsoft/fast/blob/0530a4230946d2aee39861001f3deea3b8816038/packages/web-components/fast-foundation/package.json#L92

**Comment by rushilp2311** [comment]
I can work on this.

**Comment by m4thieulavoie** [comment]
I opened [this PR](https://github.com/microsoft/fast/pull/4298) to take care of this!

**Comment by m4thieulavoie** [comment]
@chrisdholt we can close this issue 👍

**Comment by chrisdholt** [comment]
closed by #4298
