### ISSUE TITLE
Fix vulnerability with Untrusted Resource Source when using unpkg

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3844]
The URL 'https://unpkg.com/@@microsoft/fast-components' is referenced from a link/script tags to a site that is not in a whitelist, and subresource integrity is not used.  This is a security vulnerability that exists in two different files.

All sites must be hosted on Microsoft servers.

It's my recommendation, that we do not use @microsoft/fast-components from a third-party CDN for any FAST sites, rather webpack locally into our site bundles.  This will still be cached by AFD, but, gets around subresource integrity issues since these are Microsoft servers.

This recommendation will comply with security guidance.

Ref: https://webscout/#/scans/771985/issues?issueId=3812985 [Internal Link to Web Scout]
Ref: https://webscout/#/scans/771985/issues?issueId=3812984 [Internal Link to Web Scout]

**Comment by awentzel** [comment]
@chrisdholt would you prefer to proceed with this?

**Comment by chrisdholt** [comment]
@awentzel I think we need to push back on this. This specific unpkg link is not being used, it's being referenced in a markdown files for the Blazor and ASP.Net integration. It only ends up in a `.js` file when the Docusaurus pages are generated.

![image](https://user-images.githubusercontent.com/13071055/92530924-2d1d0180-f1e2-11ea-8c10-714455dee8c9.png)

This URL is not being referenced, it is being provided as a resource for others in documentation.

**Comment by awentzel** [comment]
@chrisdholt what about the two JS files in the middle of your screenshot?  Isn't that bundling?  Or are the markdown files bundled into those two JS files?  I'm not exactly clear here.  But, I do agree, if only used for documentation sake we have approval to suppress.  If we're all good here feel free to close this issue.  Thanks,

**Comment by chrisdholt** [comment]
>  Or are the markdown files bundled into those two JS files?

Yep, that's what it is. The resources referenced on the site you sent offline when opened is the documentation page. This is it being bundled and deployed for the website.
