### ISSUE TITLE
Please bring the Fast Components to the world of Data and Python.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3850]
I'm a data science developer and data Ninja :). 

Me, my friends and my colleagues are fellow data scientists, data engineers, devops, scientists, analysts, traders, engineers etc.

We use Python for our work and would like to be able to quickly community and or distribute our models as analytics apps.

We would like those apps to be awesome. Fast is awesome.

So we would like to be able to use Fast in Jupyter Notebooks and in our data science apps powered by for example [Panel](https://panel.holoviz.org/).

It is not currently possible. But as the Fast components are web components they are pretty easy to "wrap" and get bidirectional communication up and running with. For example as described [here](https://awesome-panel.readthedocs.io/en/latest/guides/awesome-panel-extensions-guide/bokeh-extensions.html). You can also see how the Material mwc components are currently being added to Panel [here](https://awesome-panel.readthedocs.io/en/latest/packages/awesome-panel-extensions/index.html#material-button).

# Solution

Please provide a python package of the fast components to use with Panel.

# Additional Context

I run the [awesome-panel.org](https://awesome-panel.org) site and would like to use the components there and bring a light/ dark theme togger to that site. I also run the sister site [awesome-streamlit.org](https://awesome-streamlit.org).

**Comment by MarcSkovMadsen** [comment]
I just added this post this Feature Request to communicate that I have started the implementation and that if anybody is interested in contributing or using the components with Panel it's possible. Just reach out.

![fast-button](https://user-images.githubusercontent.com/42288570/92298347-25423080-ef48-11ea-86e4-8f3eb4edce61.gif)

And feel to share https://twitter.com/MarcSkovMadsen/status/1302111060980359168?s=20 if you like it.

If it's ok I would like to keep this one open while I develop to share a little bit of news on the implementation as it progresses.

**Comment by MarcSkovMadsen** [comment]
If you wan't to see what it takes to do you can found the 

Panel implementations here https://github.com/MarcSkovMadsen/awesome-panel-extensions/tree/master/awesome_panel_extensions/frameworks/fast

The Panel implementation uses a Bokeh Implementation which can be found here https://github.com/MarcSkovMadsen/awesome-panel-extensions/tree/master/awesome_panel_extensions/bokeh_extensions/fast

**Comment by MarcSkovMadsen** [comment]
If you wan't to check it out in a Jupyter Notebook you can via Binder.

<p><a class="reference external" href="https://mybinder.org/v2/gh/MarcSkovMadsen/awesome-panel-extensions/master?filepath=examples%2Freference%2Fframeworks%2Ffast%2FFastButton.ipynb"><img src="https://mybinder.org/badge_logo.svg" style="height:25px;display:inline;margin:5px"></a> <a class="reference external" href="https://nbviewer.jupyter.org/github/MarcSkovMadsen/awesome-panel-extensions/blob/master/examples/reference/frameworks/fast/FastButton.ipynb"><img src="https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg" style="height:25px;display:inline;margin:5px"></a></p>

**Comment by MarcSkovMadsen** [comment]
I've implemented a FastCheckbox

![fast-checkbox](https://user-images.githubusercontent.com/42288570/92334042-84a85980-f08a-11ea-8810-d4dbe17cf785.gif)

**Comment by MarcSkovMadsen** [comment]
I've implemented the `fast-text-field`. It's called FastTextinput.

![fast-text-input](https://user-images.githubusercontent.com/42288570/92334051-97bb2980-f08a-11ea-81d1-d90089890b5d.gif)

**Comment by MarcSkovMadsen** [comment]
#### FastAnchor Added

Use it via `from awesome_panel_extensions.frameworks.fast import FastAnchor`

Or checkout the reference guide

[<img src="https://mybinder.org/badge_logo.svg" style="height:25px;display:inline;margin:5px">](https://mybinder.org/v2/gh/MarcSkovMadsen/awesome-panel-extensions/master?filepath=examples%2Freference%2Fframeworks%2Ffast%2FFastAnchor.ipynb)

![fast-anchor](https://user-images.githubusercontent.com/42288570/92356965-5016bb00-f0e7-11ea-835d-e2a5dc53ae21.gif)

**Comment by EisenbergEffect** [comment]
@MarcSkovMadsen I just wanted to check in and see how things are going. Do you feel that you've been able to make good progress? Should we close this issue as done?

**Comment by EisenbergEffect** [comment]
Closing this since it is being driven by community efforts outside of our core project.

**Comment by MarcSkovMadsen** [comment]
Hi @EisenbergEffect 

I overlooked your comment. Yes I think you have made lots of progress. But there are still lots of components missing compared to other projects. I look to MaterialUI and Shoelace for comparison.

But pretty happy so far.

**Comment by EisenbergEffect** [comment]
Thanks @MarcSkovMadsen ! If you can, as you encounter specific missing components, would you create an issue for each one you find? That will help us better track the gap and work to address it more specifically.
