### ISSUE TITLE
Does text-field work as it should/ as documented?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3852]
I am trying to wrap the Fast components in Python/ Panel.

Currently I am working on the `text-field`.

I have the following feedback.

#### Some attributes do not work in Fast Component Explorer

When trying to explorer the components in the Fast Component Explorer I cannot get anything to happen for the following attributes/ properties.

maxlength
minlength
pattern
size
spellcheck
required

![image](https://user-images.githubusercontent.com/42288570/92331092-3ee09680-f074-11ea-85c9-650f3d3c0e20.png)

![image](https://user-images.githubusercontent.com/42288570/92331107-5e77bf00-f074-11ea-8e84-d00178137796.png)

Since the documentation is quite sparse I don't know what should happen. But I would expect that the when setting for example `maxlength=5` i cannot input text longer than 5 characters. But I can.

#### Readonly property does not work

I've tried to set the `el.readonly` property. But this does not seem to work even though is defined in the schema. But using `el.setAttribute("readonly", true)` works.

**Comment by janechu** [comment]
I've investigated and this does not pertain to tools, these attributes are being reflected on the web component properly. Could someone from component implementation take a peek?

**Comment by chrisdholt** [comment]
I've got a fix incoming for this - the attributes are not being set on the internal control within the template.
