### ISSUE TITLE
Using multiple `when` directives breaks observation/attribute updating in FAST Element templates

### ISSUE THREAD

**Issue by jpfifer** [microsoft/fast#3855]
**Describe the bug; what happened?**
When using multiple `when` directives in a template switching between them will break the observation/updating of child components. 

As a workaround it appears using template composition does produce the desired affect. An example of composition is present in the repro below as `composition-story`

**What are the steps to reproduce the issue?**

See https://webcomponents.dev/edit/6lheYMTi4TjrOb0AyBIa

The `multiple-when-story` shows this happening
1. Click on `C1A` and then `C1B`. This should show the next column with the corresponding button
2. Click on `C2A`
3. Click on `C1A` and then `C1B`. The next column will display `C1A`, but will display `C1B` or any other changed values. Switching between statements (e.g. switching to `C1A` to `C2A` will update the column, but staying in the same set of buttons will not update the column) 

Additionally in the DOM the children's attributes are no longer changed.

**What behavior did you expect?**
Switching to something rendered by a different `when` directive should correctly wire up the attributes of the child element.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
* MacOS
* Verified in both Firefox, and Chrome
* `@microsoft/fast-element`: 0.17.0

**Comment by nicholasrice** [comment]
@jpfifer I can't see which versions of fast-element your example is using, but I think this issue was fixed by https://github.com/microsoft/fast/pull/4477. Can you check your example again to see if you still get the repro?

**Comment by jpfifer** [comment]
I thought I had commented on this a while ago that it looked to be fixed. Must have lost the comment. It's fixed because I think I've used multiple `when` statements since then and they have worked. I'm pretty sure the repro was on a pretty old version.

**Comment by EisenbergEffect** [comment]
Awesome. Thanks @jpfifer !
