### ISSUE TITLE
Please add a fast-range-slider for data applications

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3856]
I'm working on bringing Fast to the world of Data, Python and [Panel](https://panel.holoviz.org). See [Issue 3850](https://github.com/microsoft/fast/issues/3850).

Very often in Data you would like to filter on a range of integers, floats or dates. In Panel that is supported via the

[IntrangeSlider](https://panel.holoviz.org/reference/widgets/IntRangeSlider.html#widgets-gallery-intrangeslider)
[RangeSlider](https://panel.holoviz.org/reference/widgets/RangeSlider.html#widgets-gallery-rangeslider)
[DateRangeSlider](https://panel.holoviz.org/reference/widgets/DateRangeSlider.html#widgets-gallery-daterangeslider)

They are all built on top of [NoUiSlider](https://refreshless.com/nouislider/).

![image](https://user-images.githubusercontent.com/42288570/92432466-8103f800-f19a-11ea-8014-b55aa4c49a57.png)

But in Fast I don't see this component anywhere. And I would very much need it. The NoUISlider is great but it would be awesome to have a `fast-range-slider` that integrates well with the rest of the fast components and the design system.

#### Solution

Provide a `fast-range-slider` similar to the `NoUiSlider`.

**Comment by bsdis** [comment]
+1

**Comment by janechu** [comment]
`@microsoft/fast-components` has been deprecated for some time now, if this is still needed please file an issue with https://github.com/microsoft/fluentui/
