### ISSUE TITLE
Please add a fast-number-field component for data applications

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3857]
I'm working on bringing Fast to the world of Data, Python and [Panel](https://panel.holoviz.org). See [Issue 3850](https://github.com/microsoft/fast/issues/3850).

Very often in Data you would like the user to type some numbers (integers or floats). For that Panel provides the [Spinner](https://panel.holoviz.org/reference/widgets/Spinner.html#widgets-gallery-spinner) (a bad name. Should have been `NumberInput` :-)).

I also see you would be needing it for the Component Explorer. For example for the [fast-progress](https://explore.fast.design/components/fast-progress).

![image](https://user-images.githubusercontent.com/42288570/92433368-20c28580-f19d-11ea-81b4-30a74d00a539.png)

But in Fast this is not supported. I see a Fast [number-field spec](https://github.com/microsoft/fast/blob/master/specs/number-field.md) though.

#### Solution

Design, Implement and Release a `fast-number-field` similar to the `fast-text-field`.

**Comment by chrisdholt** [comment]
Hey @MarcSkovMadsen, would you mind taking a look at the current spec and providing some feedback? You can find it here: https://github.com/microsoft/fast/blob/master/specs/number-field.md#number-field

**Comment by MarcSkovMadsen** [comment]
I have looked at the spec @chrisdholt . My feedback is

What I like about your components is that they are extensions of the basic ones. Like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number. That is very important to me as then they can be used as drop in replacements. For example something web components do no support discrete steps.

![image](https://user-images.githubusercontent.com/42288570/92684146-0fac7c80-f335-11ea-8374-5a2e689b5ecb.png)

and I need discrete steps in my applications.

Furthermore I don't see (marked in red) the below in your specification

![image](https://user-images.githubusercontent.com/42288570/92684245-4edacd80-f335-11ea-8d63-4cca56ca06ed.png)

The link below does not lead to anything usefull
![image](https://user-images.githubusercontent.com/42288570/92684095-edb2fa00-f334-11ea-889e-df272dfeb7cb.png)

**Comment by chrisdholt** [comment]
Thanks @MarcSkovMadsen for the feedback; would you want to contribute some of the below as improvements to the spec? Once we feel good about the spec, we - or anyone - can start work on the control!

**Comment by MarcSkovMadsen** [comment]
Nope :-). I would like to help improve things. But this time i did not have the time.

**Comment by chrisdholt** [comment]
All good; thanks for the feedback, we’ll look to address it in the spec!
