### ISSUE TITLE
Please add a fast-date-input date picker for data applications

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3858]
I'm working on bringing Fast to the world of Data, Python and [Panel](https://panel.holoviz.org). See [Issue 3850](https://github.com/microsoft/fast/issues/3850).

Very often in Data you would like the user to input some dates. For that Panel provides the [DatePicker](https://panel.holoviz.org/reference/widgets/DatePicker.html#widgets-gallery-datepicker).

![image](https://user-images.githubusercontent.com/42288570/92433711-25d40480-f19e-11ea-8509-ec581b8c174b.png)

But I don't see a `fast-date-picker` component and not even a specification.

It would be really nice to have a date picker that works nicely together with the rest of the fast components and the fast design system.

#### Solution

Add a `fast-date-input` similar to `fast-text-input` and `fast-number-input`.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time now.
