### ISSUE TITLE
Please add a fast-file-field widget for uploading files in data applications

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3859]
I'm working on bringing Fast to the world of Data, Python and [Panel](https://panel.holoviz.org). See [Issue 3850](https://github.com/microsoft/fast/issues/3850).

Very often in Data Applications the user would like to be able to upload a file with tabular data, json data or some images. For that Panel provides a basic [FileInput](https://panel.holoviz.org/reference/widgets/FileInput.html#widgets-gallery-fileinput) widget.

![image](https://user-images.githubusercontent.com/42288570/92434137-5c5e4f00-f19f-11ea-9718-a710b8608742.png)

But I don't see a `fast-file-field` or `fast-file-input` in Fast.

I can just add support for something like https://www.dropzonejs.com/ to Bokeh/ Panel. 

![image](https://user-images.githubusercontent.com/42288570/92434182-7730c380-f19f-11ea-84ee-dcc8b236dab9.png)

But this will not integrate nice and easy with the Fast design system.

#### Solution

Add a `fast-file-field` similar to `fast-text-field`, `fast-number-field` and `fast-date-field`.

#### Requirements

- Button enabled (must have)
- Drag and drop of files enabled. (must have)
- Folders can be uploaded (nice to have).
- Multiple files can be uploaded (nice to have)

**Comment by paule96** [comment]
Is this maybe the same as #5269?

But still this is really wanted!

**Comment by chrisdholt** [comment]
> Is this maybe the same as #5269?
> 
> But still this is really wanted!

I thought this was in PR, let me take a look.

**Comment by paule96** [comment]
@chrisdholt you are right. Here #5336

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time now.
