### ISSUE TITLE
Cannot keyboard tab out of tree-view when on a nested item

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast#3878]
**Describe the bug; what happened?**
Cannot focus out of `tree-view` when focused on a nested child item.

**What are the steps to reproduce the issue?**

1. tab into tree-view arrow key down(or up) to an item that has a child. 
2. then try to tab out of tree-view.

**What behavior did you expect?**
Should be able to tab out of tree-view when focused on any item in the tree.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Is there any additional context?**

**Comment by chrisdholt** [comment]
@khamudom didn't we already have an issue similar to this? If we can't get this in for today's release we should revert the code that went in causing this.

cc: @EisenbergEffect

**Comment by khamudom** [comment]
> @khamudom didn't we already have an issue similar to this? If we can't get this in for today's release we should revert the code that went in causing this.
> 
> cc: @EisenbergEffect

I have a fix. Putting up a PR now. Wanted to create a separate issue, since the last issue was being not being able to tab back into tree-view. While working on that I noticed you couldn't tab out when on a child item. just to make sure my changes didn't regress anything i tested to see if the issue was already there. Another test is the component explorer site.
