### ISSUE TITLE
bug: accordion example on fast components site has overlapping focus indicator

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3881]
**Describe the bug; what happened?**
On the "with start and end" accordion example at https://explore.fast.design/components/fast-accordion the item's focus rect overlaps the checkbox buttons.

**What are the steps to reproduce the issue?**
Navigate here - https://explore.fast.design/components/fast-accordion
Select "with start and end" in top page dropdown
Select an accordion element and notice the focus rect overlaps the checkbox button as in image below:

![image](https://user-images.githubusercontent.com/7649425/92788276-a80b2700-f35e-11ea-8b39-e136c1e04a58.png)

**What behavior did you expect?**
margins or padding

**Is there any additional context?**

**Comment by litteredwitherrors** [comment]
Would a suitable solution be to add a left margin to the checkbox? It makes sense to me to match the left margin of the checkbox part with the right margin of the `icon` part. The question would be: Would that break the design requirements?
