### ISSUE TITLE
Add custom telemetry onto shadow DOM template elements

### ISSUE THREAD

**Issue by chris-phelps** [microsoft/fast#3891]
It would be beneficial to have a hook or directive for my team's custom telemetry engine to have some way to mark custom values onto template defined elements that reside inside the shadow DOM.

For example if we had a piece of template code where we wanted to know the exact button that a user clicked on we could add a helper that would query the telemetry system.

```
<template>
  <div>
    <button>
  </div>
</template>
```

augmenting

```
<template>
  <div>
    <button ${telemetry(x => x.telemetryValue)}>
  </div>
</template>
```
I spoke offline to Rob Eisenberg about supporting this scenario and he suggested the following possibility where FAST might be able to add a noop directive that could be overridden:

```
const noopBehavior: Behavior = Object.freeze( { bind() {}, unbind() {} } );

class TelemetryDirective extends Directive {
    public static createBehavior: (target: Node, metadataOrBinding: any) => Behavior = () => noopBehavior;

    constructor(private metadataOrBinding: any) {
        super();
    }

    public createBehavior(target: Node): Behavior {
        return TelemetryDirective.createBehavior(target, this.metadataOrBinding);
    }

    public createPlaceholder(index: number): string {
        return DOM.createCustomAttributePlaceholder("fast-telemetry", index);
    }
}
```

Then the app dev could add their telemetry logic
```
elemetryDirective.createBehavior = (node: Node, metadata: any) => { /** Custom code */ }
```

Thoughts or suggestions on this approach?

**Comment by EisenbergEffect** [comment]
Now that we've worked out a plan for closed mode shadow dom, the original issues should be resolved. If an abstraction is needed for other scenarios, it need not be included in our library.
