### ISSUE TITLE
fast-badge not working at all and component explorer not working well

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3900]
I'm working on wrapping the fast components for use in Python, Bokeh and Panel to develop data science apps and for exploratory use in Jupyter Notebooks.

Next up is the `fast-badge` but I simply cannot get it working as I would expect.

I started with the component explorer. But that is simply confusing as all the attributes are input via TextArea and for example the `circular` attribute is a boolean.

![image](https://user-images.githubusercontent.com/42288570/93165219-bde06980-f71b-11ea-9d2a-8afa8f6bd90e.png)

The I created a code example

```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
    </head>
    <style>
        fast-badge {
            --badge-fill-primary: rgba(255, 0, 0, 1);
            --badge-fill-secondary: #00FF00;
            --badge-fill-transparent: transparent;
         }
    </style>
<body style="margin:0px">
    <fast-design-system-provider use-defaults style="height:100%;">
        <fast-badge
            fill="primary"
        >
            New
        </fast-badge>
        <fast-badge
            fill="secondary"
            circular=true
        >
            99
        </fast-badge>
        <fast-badge
            fill="secondary"
            circular=true
        >
            <fast-button>Button1</fast-button>
        </fast-badge>
        <fast-badge
            fill="secondary"
            circular=true
        >
            <fast-button slot="default">Button2</fast-button>
        </fast-badge>
        <fast-button>Button3
            <fast-badge
                fill="secondary"
                circular=true
            >
            </fast-badge>
        </fast-button>
        <fast-button>Button4
            <fast-badge
                fill="secondary"
                circular=true
                slot="default"
            >
            </fast-badge>
        </fast-button>
    </fast-design-system-provider>
</body></html>
```

But it looks like 

![image](https://user-images.githubusercontent.com/42288570/93165266-e2d4dc80-f71b-11ea-9596-43e1ff4a1cd1.png)

So I don't know what I really can do with the `badge` now and in the future.

#### Solution

Please fix component explorer and add better examples or documentation.

**Comment by eljefe223** [comment]
Thanks @MarcSkovMadsen , I've created a PR to address the above issues:

https://github.com/microsoft/fast/pull/3901

Was curious what you expectations were in adding a badge as a child of button? My presumption is you want some sort of indicator like the below example:

![image](https://user-images.githubusercontent.com/37851214/93243498-20962d00-f73d-11ea-891a-02cef2b055d3.png)

This is certainly achievable by making the button's position `relative` and the badge position `absolute`. Let me know if you have specific questions or get stuck on anything else.

**Comment by MarcSkovMadsen** [comment]
Your example is what I would expect to be able to create.

But I’m a data scientist and not front end developer. So I need some good examples to start from 👍
