### ISSUE TITLE
add menuitemcheckbox and menuitemradio support to fast-menu-items

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3906]
I was trying to learn how the `fast-menu works.

Both from code and the component explorer I'm not able to select anything but the top menu-item.

![fast-menu-item-select](https://user-images.githubusercontent.com/42288570/93288792-03b13680-f7dd-11ea-997d-0480021b0405.gif)

I would have expected a the second and third fast-menu-item to be selected/ highlight when clicked just as the first one.

**Comment by chrisdholt** [comment]
Thanks for the note @MarcSkovMadsen - we're in process of adding the checkbox and radio behavior here. The current events would simply invoke the menu item. Let's use this issue to track the addition of the checkbox and radio events *AND* visual states.

@bheston for both the radio and checkbox menu instances, I think we'd want a "check" svg. One question I have is where we think that may go from a design standpoint. I'm not sure the start or end slot would be preferred. Do we have designs for menuitemcheckbox/menuitemradio instances? If so, we can finish this up quickly.

**Comment by MarcSkovMadsen** [comment]
The important thing here to note @chrisdholt  and fix is that if I click the top menu-item it gets selected (fixed red color, border etc.). But that does not happen for other menu-items.

**Comment by bheston** [comment]
It wouldn't be considered standard, but putting the check at the end does solve some design issues that can happen. It would be nice if the check was its own element such that the position could be moved around the grid. Ultimately the menu may need more than a begin and end slot anyway considering there could be chevrons for submenus or keyboard shortcut labels.
The default design I suggest putting it at the end so it doesn't conflict with an item icon. I'd like to see that as a visual accessibility improvement on a select menu as well, so nice consistency there.

**Comment by chrisdholt** [comment]
Assigning to @radium-v as he's tracking other menu item changes for checkbox and radio behavior

**Comment by MarcSkovMadsen** [comment]
again. For me this is not about Checkboxes but selections.

The important thing here to note @chrisdholt and fix is that if I click the top menu-item it gets selected (fixed red color, border etc.). But that does not happen for other menu-items.

**Comment by chrisdholt** [comment]
> again. For me this is not about Checkboxes but selections.
> 
> The important thing here to note @chrisdholt and fix is that if I click the top menu-item it gets selected (fixed red color, border etc.). But that does not happen for other menu-items.

I'll look to confirm, but I think that is actually a focus rect in the example that you're showing above based on the border, etc. None of the examples from what I can see are either menuitemcheckbox or menuitemradio, just menuitem - so I'm not sure I'd expect a selected state.

It is odd that only one receives the focus state on click as you illustrate.

**Comment by EisenbergEffect** [comment]
@chrisdholt Can we close this as done?

**Comment by chrisdholt** [comment]
@EisenbergEffect yes, this can be closed
