### ISSUE TITLE
extend TextField with more types

### ISSUE THREAD

**Issue by dcharbonnier** [microsoft/fast#3911]
TextFieldType is defined as :
```
export declare enum TextFieldType {
    email = "email",
    password = "password",
    tel = "tel",
    text = "text",
    url = "url"
}
```

The fundation `TextField` use this enum for the property `type`.
The html standard define type as an enumerated DOMString with [27 different values](https://html.spec.whatwg.org/multipage/input.html#the-input-element:enumerated-attribute), most of them share a huge part of the TextField logic.
To implement an existing type or a new type it would be convenient to extend TextField but it's not possible.
There is 3 possibilities I can think of by order of personnal preference:
- `export declare class TextField<T extends string = TextFieldType> extends FormAssociated<HTMLInputElement> {` and then `type: T;`
- `type: TextFieldType & string;`
- add the 27 values to the TextFieldType (but what about new or custom ones?)

Let me know what you think, I can make a PR.

**Comment by nicholasrice** [comment]
Can you narrow this down a bit? Which of those 27 are you proposing to extend the enum with; what would be useful to you?

**Comment by dcharbonnier** [comment]
Number is a usefull one in my case.
But in general the fact we can't extend it isn't convenient, if I want to create a new type like "pin-code" I can't and the ony thing that prevent is is this enum.
I'm not speaking about providign the support for those types in the framework, I'm speaking of extending the class to support other types.

**Comment by chrisdholt** [comment]
I've been looking to move that to a type with explicit types for what we have now, but we could add "string" as well...that kind of would defeat some of the type safety, but it would be extensible. 

We could offset the breaking change of converting to a type by keeping and deprecating the enum rather than deleting it. @dcharbonnier Would that help here? @nicholasrice do you have any concerns over that approach?

**Comment by dcharbonnier** [comment]
Somehow linked to #3857

**Comment by dcharbonnier** [comment]
An approach could be to have an abstract input element and having text-field that implement it, we could keep a strick typing and that's something important IMO, implement a number-field with some specificity and other types. What do you think ? I can probably help on anything, I just don't want to take a direction and waste my time.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time now.
