### ISSUE TITLE
Unable to bind text field with Blazor Component

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#3928]
**Describe the bug; what happened?**

I am trying to integrate the FAST components with Blazor reusable components. But I cannot use @bind attribute for two way binding.

**What are the steps to reproduce the issue?**

Sample code

TestBlazorComponent.razor

`<fast-text-field type="text" @bind="@BindTestProperty" placeholder="key" required maxlength="@MaxKeyLength"></fast-text-field>`
           
**What behavior did you expect?**
Blazor @bind attributes should work out of the box.

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/13166236/93569980-2d866c80-f947-11ea-8fa9-0c8caf29af22.png)

**In what environment did you see the issue?**

Visual Studio 2019
ASP.NET CORE
BLAZOR SERVER

**Comment by EisenbergEffect** [comment]
This should now be addressed by the new FAST Blazor library https://github.com/microsoft/fast-blazor
