### ISSUE TITLE
Stealth is not stealth when used on card

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3940]
I would expect to be able to use the `fast-anchor` and `fast-button` in a `fast-card` easily.

But if I set the appearance to `stealth` it is not `stealth` see below example

![image](https://user-images.githubusercontent.com/42288570/93847911-93a52380-fca8-11ea-942a-895d2f61da44.png)

```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
    </head>
<body style="margin:0px">
    <fast-design-system-provider use-defaults style="height:100%;">
        <fast-card style="width: 300px;">
            <fast-anchor appearance="stealth">Title</fast-anchor> / <fast-anchor appearance="stealth">Sub Title</fast-anchor><br/>
            <fast-button appearance="stealth">Button</fast-button>
        </fast-card>
    </fast-design-system-provider>
</body></html>
```

**Comment by EisenbergEffect** [comment]
@nicholasrice Did we get the fix for this merged in or is this pending the larger provider work?

**Comment by chrisdholt** [comment]
@MarcSkovMadsen This should be fixed in the latest published version of `fast-components`.
