### ISSUE TITLE
Align Anchor with text

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3941]
I'm trying to combine the `fast-anchor` with text. But it does not align nicely as you can see below. The text is on "top" of the "anchor" text.

![image](https://user-images.githubusercontent.com/42288570/93848076-044c4000-fca9-11ea-8b3e-6c74ceade15f.png)

```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
    </head>
<body style="margin:0px">
    <fast-design-system-provider use-defaults style="height:100%;">
        <fast-card style="width: 300px;">
            <fast-anchor appearance="stealth">Title</fast-anchor> / <fast-anchor appearance="stealth">Sub Title</fast-anchor><br/>
        </fast-card>
    </fast-design-system-provider>
</body></html>
```

I've been trying to use the `fast-anchor` several times in different use cases. And every time I combine with text it's a pain to use.

**Comment by chrisdholt** [comment]
Most of the anchors are intended to include the appearance of buttons when they function as anchors. If you’re looking to include it inline with text, the “hypertext” appearance should help as its intended to be used inline with text as an anchor. If you’re looking to use the button format, you’ll likely need to provide additional contextual CSS for your use case. Flexbox or grid are two simple ways to address this.
