### ISSUE TITLE
Not removing DOM elements in repeat directive

### ISSUE THREAD

**Issue by adunndevster** [microsoft/fast#3944]
**Describe the bug; what happened?**
- I have an observable array string[].
- I use the repeat directive to `<li>` the contents of the array to the page
- when I clear the contents by setting the array to [], The page keeps a residual 'li' on the page
- each time I add elements to the array, then clear the array, a new empty 'li' is added to the DOM
- If I use splice instead, to clear the array, I get:
Uncaught TypeError: Cannot read property 'index' of undefined
    at mergeSplice (array-change-records.js:253)
    at createInitialSplices (array-change-records.js:307)
    at projectArraySplices (array-change-records.js:314)
    at ArrayObserver.flush (array-observer.js:60)
    at processQueue (dom.js:17)

**What are the steps to reproduce the issue?**
1. Create an observable array of type string[]
2. create a simple template html<string>`<li>${x => x}</li>`
3. use repeat to repeat that template as the array is changed
4. set array to [], and notice that a residual `<li>` remains on the DOM
5. change to clearing the array using splice, and notice the js error above

**What behavior did you expect?**
That when the array is empty, no dom elements are repeated

**In what environment did you see the issue?**
Microsoft Edge 85.x, Windows 10, inside a chrome extension

**Comment by EisenbergEffect** [comment]
I'm having trouble reproducing this. Here's a demo I put together:

https://webcomponents.dev/edit/ptFo1rBme8Y5SGyJAVzm

Everything seems to work fine. Is there some other detail I'm missing?

/cc @scomea

**Comment by EisenbergEffect** [comment]
Update, thanks to @scomea I was able to repro the mergeSplice bug. I've identified the issue and we'll get a PR up for that one soon. Haven't been able to reproduce the left over element issue yet though.

**Comment by EisenbergEffect** [comment]
Update: @scomea helped me reproduce what I like to call the "zombie" node bug. I've got a PR up to fix this.

**Comment by EisenbergEffect** [comment]
Should be all fixed in the next release 😄
