### ISSUE TITLE
bug: tree view nodes can't be expanded with keyboard in narrator scan mode

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3952]
In narrator's scan mode space bar is mapped to the primary action of the focused element which selects a tree view item.  Normally space bar expands/collapses the tree item and the enter key selects. Given that and that the expand/collapse button is not keyboard accessible it seems like we may have an accessibility gap because expanding a node would require a user to either leave scan mode or use a mouse. 

Not sure if other accessibility tools would have similar issues.

Not sure what the right answer is but seems like we should consider if our interaction scheme here could be improved.

Related to:
https://github.com/microsoft/fast/issues/3914
https://github.com/microsoft/fast/pull/3951

**Comment by chrisdholt** [comment]
> Normally space bar expands/collapses the tree item and the enter key selects.
@scomea where are you getting this behavior expectation - is this specific to narrator? Our interaction model is not linked to narrator or other AT - we should build our keyboard interaction model to the spec, which does not outline this behavior: https://w3c.github.io/aria-practices/#TreeView

Narrator issues would be related to the UIA markup of the tree being passed to them. Does this repro in other browsers?

**Comment by scomea** [comment]
The "space bar expands/collapses the tree item and the enter key selects" behavior I describe is what is currently implemented in our component.  I'm just pointing out that there may be an gap an our interaction model that warrants further consideration.

**Comment by chrisdholt** [comment]
@scomea I've had recent conversations around scan mode that has pushed back on it being used this way. I'll work on getting some better feedback on that - TLDR; this needs more investigation as I'm not sure we need to actually support this scenario specifically for scan mode.

**Comment by scomea** [comment]
@chrisdholt Cool, this issue was as much about sussing out the expected behavior as anything else.

**Comment by chrisdholt** [comment]
Confirmed with an internal a11y contact after sharing this scenario that while interaction is possible in scan mode, it's not really the intent nor is it expected if everything else works as expected. Closing this given that guidance.
