### ISSUE TITLE
bug: components should call preventDefault on keyboard actions which have caused a ui change

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3953]
We should do a pass to ensure that when we use a keyboard event to trigger a ui change we should mark that event with preventDefault() so that upstream consumers of bubbled events can avoid triggering a second ui change on the same event.

For example key handling in tree view item does not mark the event arrowLeft event when it triggers ui changes:

```js

    public handleKeyDown = (e: KeyboardEvent): void | boolean => {
        if (e.target !== e.currentTarget) {
            return true;
        }

        switch (e.keyCode) {
            case keyCodeArrowLeft:
                this.handleArrowLeft();
                break;
```
If a parent element in the dom also captures the event it has no way to know not to act on it.  This is most obvious with how the browser reacts to some key strokes, like scrolling on space/home, but it can also affect js code where user keystrokes could inadvertantly trigger multiple changes in the ui at once.

**Comment by tech4GT** [comment]
Hi @scomea is this issue still active? I would like to work on this 😄

**Comment by scomea** [comment]
@tech4GT Sure.  The important thing to remember is that template bound events invoke prevent default on the event by default (https://www.fast.design/docs/fast-element/declaring-templates#events) unless the call returns true which can be confusing.  Looking at the current state of the handleKeyDown() handler in tree item it always returns true and preventDefault has been added to the up/down key event cases. The fix here would be to return false for any handled key event and true for unhandled keystrokes.  ie. Enter and arrow left/right should also be marked with preventDefault (return false)

**Comment by tech4GT** [comment]
@scomea I see! That makes sense! So the solution here would be to have a default case within the switch which returns true rather than breaking out and returning true every single time, correct?

Something like this
```js
public handleKeyDown = (e: KeyboardEvent): void | boolean => {
        if (e.target !== e.currentTarget) {
            return true;
        }

        switch (e.keyCode) {
            case keyCodeArrowLeft:
                this.collapseOrFocusParent();
                break;
            case keyCodeArrowRight:
                this.expandOrFocusFirstChild();
                break;
            case keyCodeArrowDown:
                // preventDefault to ensure we don't scroll the page
                e.preventDefault();
                this.focusNextNode(1);
                break;
            case keyCodeArrowUp:
                // preventDefault to ensure we don't scroll the page
                e.preventDefault();
                this.focusNextNode(-1);
                break;
            case keyCodeEnter:
                // In single-select trees where selection does not follow focus (see note below),
                // the default action is typically to select the focused node.
                this.handleSelected(e);
                break;
            default:
                return true;
        }
    };
```

**Comment by tech4GT** [comment]
Also, I suppose we can also get rid of the explicit `e.preventDefault()` statements now that we would not be returning true in case one of those keys is pressed?

**Comment by scomea** [comment]
@tech4GT Yes, a handler for template events should use the return values instead of calling preventDefault directly.

**Comment by tech4GT** [comment]
@scomea Thanks for your help! I've opened a pull request #4489

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time now, and `@microsoft/fast-foundation` is being deprecated see #6955.
