### ISSUE TITLE
bug: bottom section moves vertically on selection in fast component explorer

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3958]
The bottom section of the component explorer screen moves up and down innapropriately when the user selects the "Code", "Guidance", "Definition" and "Schema" tabs.  This looks to be a regression.

**What are the steps to reproduce the issue?**

Example:

- Go to the currently staged version of component explorer:
https://stage.explore.fast.design/components/fast-tree-view
- selects the "Code", "Guidance", "Definition" and "Schema" tabs.
- note the tabs and associated content move vertically.

(Edge release, windows 10)

**Comment by EisenbergEffect** [comment]
I noticed that in order to repro this issue, the browser's vertical height needed to be shrunk down a bit.

**Comment by scomea** [comment]
I believe this style in component explorer's "style.css" is part of the issue :
.canvas-content {
    display: grid;
    grid-template-rows: 50% 50%;
}
