### ISSUE TITLE
bug: component explorer dropdowns need more differentiation from page background

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3979]
In the example below (edge, windows) it is difficult to tell where the menu items stop and where the other page content begins.

![image](https://user-images.githubusercontent.com/7649425/94463610-0cf1ba00-0172-11eb-8782-d80792d70f44.png)

We should add a border or some contrast to differentiate the two.

**What are the steps to reproduce the issue?**

- Go to https://explore.fast.design/components/fast-accordion
- expand the dropdown at the top of the right hand panel

**What behavior did you expect?**
Better differentiation between the menu and the page

**Comment by janechu** [comment]
As a little more information, the dropdown itself is browser and/or operating system specific, so there needs to be a solution that fits all of them, from **MacOS** here are some screenshots from various browsers:

Edge:
<img width="357" alt="Screen Shot 2020-09-29 at 1 48 48 PM" src="https://user-images.githubusercontent.com/7559015/94614186-a1cfe280-025a-11eb-9e81-2ae0836c458a.png">
Firefox:
![Screen Shot 2020-09-29 at 1 50 09 PM](https://user-images.githubusercontent.com/7559015/94614240-b8763980-025a-11eb-9756-a78a9fba2f99.png)
Safari:
<img width="236" alt="Screen Shot 2020-09-29 at 1 50 53 PM" src="https://user-images.githubusercontent.com/7559015/94614293-d04dbd80-025a-11eb-9024-809ab2af316e.png">
Chrome:
<img width="314" alt="Screen Shot 2020-09-29 at 1 51 56 PM" src="https://user-images.githubusercontent.com/7559015/94614395-f5dac700-025a-11eb-9935-b44942292c79.png">

**Comment by scomea** [comment]
Top of the page is Windows Edge,   Here are some other windows browsers.

Chrome:
![image](https://user-images.githubusercontent.com/7649425/94618739-7a7c1400-0260-11eb-9811-e6fac4b4688c.png)

Firefox:
![image](https://user-images.githubusercontent.com/7649425/94618842-ad260c80-0260-11eb-8dc6-42b7c2a9f3c1.png)
