### ISSUE TITLE
bug:  template attribute bindings get incorrectly formatted in some circumstances

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#3989]
In order to resolve an issue with the tooltip component not working properly in our documentation sample we added quotes around the bound attribute values in  the tooltip template: 

```ts
vertical-positioning-mode="${x => x.verticalPositioningMode}"
```

instead of 

```ts
vertical-positioning-mode=${x => x.verticalPositioningMode}
```

See resolved PR here - https://github.com/microsoft/fast/pull/3988/files

While this appears to have fixed the issue we don't have a good understanding of why the quotes are required and where the break was happening.  We should investigate further, particularly if folks encounter this in the wild.

**Comment by janechu** [comment]
The updated documentation should consistently use quotes, I believe this should solve the issue for consumers of `@microsoft/fast-element`. I believe `@microsoft/fast-element` relies on the quotes to correctly render the shadow DOM.
