### ISSUE TITLE
fast-slider does not raise "change" event

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#4019]
I'm trying to use the `fast-slider` and it's value `property`. According to the [specs](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/slider/slider.spec.md) the `fast-slider` will raise the `change` event when the value is changed.

That does not work for me.

I'm on fast v. 1.11.

## Example

When I run the below in a browser and change the slider knob I would expect the value in the div to be updated. It is not.

![fast-slider-not-working](https://user-images.githubusercontent.com/42288570/95686329-62f84000-0bfd-11eb-82f5-bb7ad0b0707e.gif)

```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
    </head>
<body style="margin:0px">
    <fast-design-system-provider use-defaults style="height:100%;">
        <fast-slider id="slider" style="width:200px" min="0" max="100" step="1" value="50"></fast-slider>
        <div id="value"></div>
        <script>
            el=document.getElementById("slider");
            dv=document.getElementById("value");
            dv.innerHTML="50"
            element.addEventListener("change", function() {
                console.log("change");
                dv.innerHTML = el.value.toString();
              });
        </script>
    </fast-design-system-provider>
</body></html>
```

**Comment by robarbms** [comment]
I ran some tests against the sliders in the story book using this snippet in the console:

Array.from(document.getElementsByTagName("fast-slider")).map(s => s.addEventListener("change", function () {console.log(this.value);}));

It was console logging the updated values as I moved the slider with both addEventListener and the elements .onchange property.

I found a mistake in the code example above. You are adding the event listener to element which is not defined. I think you meant to add it to el.

I created a fixed version here: https://codepen.io/kungfukarl/pen/rNLjzQr?editors=1010
