### ISSUE TITLE
bug:  utton component not detected as part of tab 

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#4034]
**Describe the bug; what happened?**

**What are the steps to reproduce the issue?**

Example:

**What behavior did you expect?**

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Is there any additional context?**

**Comment by EisenbergEffect** [comment]
@scomea What is this?

**Comment by EisenbergEffect** [comment]
Actually, this looks like an incomplete duplicate of the other tab button issue. Closing.
