### ISSUE TITLE
Icons disappear when navigating to accordion fixture in fast-components Storybook

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#4041]
**Describe the bug; what happened?**
The `fast-accordion` component story loses its icons when navigating to the story from another.

**What are the steps to reproduce the issue?**
1. Start storybook in fast-components: `$ yarn start`
2. Observe that the default story loaded is the Accordion, and the expand/collapse icons are present.
3. Navigate to another story by clicking an item in the Storybook sidebar.
4. Navigate back to the Accordion story by clicking "Accordion -> Base" in the Storybook sidebar.
5. Observe that the expand/collapse icons are no longer visible, though they are present in the DOM.

**What behavior did you expect?**
There's an event listener in `accordion.stories.ts` that handles `readystatechange` but it only works when the page first loads. The code in the handler should be handled when the story is displayed, not when the full page is loaded. My guess is that this bug hasn't been caught since "Accordion" is the first component in our list.

**In what environment did you see the issue?**
* OS & Device: Windows 10
* Browser Microsoft Edge
* Version 86.0.622.38

**Is there any additional context?**
I have a solution ready, which will allow us to offset all `<fast-design-system-provider>` wrappers in storybook stories which uses Storybook's Decorators feature.

**Comment by chrisdholt** [comment]
I'm not able to repro this, closing as such. @radium-v if you repro still, feel free to reopen and push a PR :)
