### ISSUE TITLE
bug: fast-anchor example has no margin between icon in default slot and primary text 

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#4044]
Needs space between icon and anchor text:

![image](https://user-images.githubusercontent.com/7649425/96477944-f3c9af80-11eb-11eb-8e92-d0dcb82ad114.png)

1 - go to https://stage.explore.fast.design/components/fast-anchor
2 - choose the "Icon in default slot" example

**Comment by scomea** [comment]
Button has the same issue 
![image](https://user-images.githubusercontent.com/7649425/96478460-8d915c80-11ec-11eb-8b1e-c4b159d0766b.png)

**Comment by chrisdholt** [comment]
I think this an issue with the configuration - this is coming from Storybook:

![image](https://user-images.githubusercontent.com/13071055/97203746-7b766780-1772-11eb-948d-fbab15cd1f99.png)

Taking a look

**Comment by chrisdholt** [comment]
Looks like this has been fixed:

Icon in the default slot:
![image](https://user-images.githubusercontent.com/13071055/97204309-2e46c580-1773-11eb-80a3-f1f25b5ffbea.png)
