### ISSUE TITLE
configure www.fast.design to avoid showing web server configuration directives

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4057]
Description:

Default configurations of web servers often provide too much information about their platform and version in HTTP headers and on error pages. This data is not itself dangerous, but it can help an attacker focus on vulnerabilities associated with your specific web server platform/version.

Details noted:  https://webscout/#/scans/804976/issues?issueId=4065508 
Curiously, all sites use the same application security and web server so it's unclear why not all sites do not require this.

Recommendation:

Configure your web server to avoid having it announce its own details.

In Apache Web Server, the following configuration directives should be added to the config file:

ServerSignature Off
ServerTokens Prod
In Microsoft IIS/10.0 Web Server, the "removeServerHeader" attribute should be added to the "security" configuration in web.config file:

<requestFiltering removeServerHeader="true" />

**Comment by Ibrahimmaga** [comment]
The latest scan does not reproduce any issue In Microsoft IIS/10.0 Web Server, the "removeServerHeader"
