### ISSUE TITLE
Update all FAST components to use attributes for styling rather than classes

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#4076]
This issue is meant to track an improvement to leverage attributes for styling rather than classes. Hoisting classes out of web components can have unintended side effects with author applied classes and can be clobbered when integrated with certain frameworks.

This task should be considered "complete" when all components have been updated to leverage attributes instead of classes.

**Comment by vertonghenb** [comment]
###  :host() style selecters
From:
`:host(.filled)` 
To:
`:host([appearance='filled'])`

@chrisdholt do we intend to still add the class names to the classList or is it just the styling that's changing?

**Comment by chrisdholt** [comment]
Example is here: https://github.com/microsoft/fast/pull/4077

Open to feedback from others (@nicholasrice) but IMO, I think classes are redundant given the update.

**Comment by vertonghenb** [comment]
Maybe we should consider aligning the Fluent package with these changes.
https://github.com/microsoft/fluentui/tree/master/packages/web-components/src

**Comment by chrisdholt** [comment]
> Maybe we should consider aligning the Fluent package with these changes.
> https://github.com/microsoft/fluentui/tree/master/packages/web-components/src

Yes, That's always part of the plan - if you'd like, I'm happy to take a change in that repo as well :)

**Comment by vertonghenb** [comment]
@chrisdholt sure, if the other PR #4078 is reviewed and ready to merge I'll make the changes in the Fluent repo. Can you make an issue for it?

**Comment by chrisdholt** [comment]
@vertonghenb See issue: https://github.com/microsoft/fluentui/issues/15747

Thanks!
