### ISSUE TITLE
Text field has undefined value on Firefox Nightly

### ISSUE THREAD

**Issue by muhammad-saleh** [microsoft/fast#4086]
**Describe the bug; what happened?**
The textbox on the website has undefined as a value

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1510608/97762245-951c0400-1b10-11eb-870b-b884a629c842.png">

**What are the steps to reproduce the issue?**
- Go to:  https://www.fast.design/
- Check the textbox on the homepage
- It has `undefined` as a value

**What behavior did you expect?**
Same behavior on Chrome
<img width="343" alt="image" src="https://user-images.githubusercontent.com/1510608/97762369-f80d9b00-1b10-11eb-8383-156ca267fab0.png">

**In what environment did you see the issue?**
- Browser: Firefox Nightly 84.0a1 (2020-10-30) (64-bit)
- OS: macOS Catalina 10.15.7 (19H2)

**Comment by EisenbergEffect** [comment]
I'm on macOS Catalina 10.15.7 with FireFox 82.0.2 (64-bit) and cannot reproduce the issue. Perhaps this is an issue in the nightly? @muhammad-saleh Can you provide any additional information?

**Comment by muhammad-saleh** [comment]
@EisenbergEffect I checked the console and I found this error:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/1510608/97879530-c5d68600-1d28-11eb-9330-93fa9b525c4c.png">

If you can't reproduce it then it must be a nightly issue only, Feel free to close this issue if it's not a priority then

**Comment by muhammad-saleh** [comment]
The issue is also found at:
https://explore.fast.design/components/fast-text-field

I get this error:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1510608/97881009-8741cb00-1d2a-11eb-85c9-9cc01f150a30.png">


and this issue happen with multiple components

**Comment by EisenbergEffect** [comment]
@nicholasrice Can you look into this? Is it possible that FF nightly is implementing element internals but not the full API set? If so, then we need to find out if they intend to ship it like that...if so, we'll need to feature detect differently I think.

**Comment by nicholasrice** [comment]
It appears that the `"ElementInternals"` key now exists in `window` so our feature detection is passing, however the at this point none of the features of ElementInternals actually exist in that object.

I don't see any *recent* changes to [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1552313) so it's possible this has always thrown in FF nightly. I'll update the feature-detection to ensure the `setFormData` function exists in that object.
