### ISSUE TITLE
Add Microsoft Clarity to FAST Sites for better UX understanding

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4090]
All you need to know is https://blogs.bing.com/webmaster/october-2020/Microsoft-Clarity-is-now-Generally-Available at the end is how to sign-up and begin using.  

https://clarity.microsoft.com/

clarity tracking code
<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "6kup5bdo0a");
</script>

**Session playbacks**
With individual session recordings, you can examine user behavior as it happened. You'll see where things are working smoothly and where people get stuck.

**Heatmaps**
Detailed heat maps show you where users clicked and scrolled, and how they moved around the site. Discover which parts of a page drive the most engagement.

**Insights**
Find interesting user sessions and root out problems like clicks that go nowhere, rage clicks, and excessive scrolling. Make data-driven decisions to streamline your design.

**Built to grow with your business**
Clarity can scale to support even the largest websites. We process more than 1 petabyte of data from over 100 million users per month. And Clarity won't get in the way of your site's performance.

**Masking**
This prevents text from being sent to our servers. By default, Clarity masks all sensitive text, such as email addresses and info entered by users.

**IP blocking**
Prevents specific IP addresses from being included in Clarity. For example, you may want to block site visits from your team members.

**Comment by Ibrahimmaga** [comment]
![image](https://user-images.githubusercontent.com/14119043/117379092-921d1a00-ae8b-11eb-8dbd-a6c228286f97.png)

**Comment by chrisdholt** [comment]
Would this have GDPR requirements? I'd like to capture all of our compliance requirements and the implications of this before this becomes a work item if we can. Looks interesting!

**Comment by Ibrahimmaga** [comment]
I'm still gathering useful information about it. but it sounds like a nice tool. It provides analytics and a dashboard for visibility as well.

**Comment by chrisdholt** [comment]
Thanks @Ibrahimmaga - it would be great to see these RFC’s contain a proposal that describes the value, benefits, requirements, risks, etc. I’ll look to review once these are ready!

**Comment by Ibrahimmaga** [comment]
a little update on heatmaps, session playbacks, and insights

**Comment by awentzel** [comment]
@chrisdholt @Ibrahimmaga I have reached out to our privacy contact to understand the compliance implications or requirements for adding this.  For sake of simplicity, this is similar to adding Google Analytics on steroids and may shine a light on how we would want to improve information architecture, design, or functionality in the future across our production sites.

**Comment by awentzel** [comment]
I have marked this Issue as blocked until I get more information from Privacy Lead.
