### ISSUE TITLE
JS error when using fast-dialog in a Blazor app

### ISSUE THREAD

**Issue by LucSuy** [microsoft/fast#4105]
**Describe the bug; what happened?**
The use of a fast-dialog component on a page causes an Uncaught TypeError 't.querySelectorAll is not a function error' to occur.

**What are the steps to reproduce the issue?**
1. Create a new Blazor Webassembly project following the integration guidelines [https://www.fast.design/docs/integrations/blazor]
2. Add a fast-dialog to the bottom of the Index.razor page:
```
<fast-dialog hidden=@(!IsActive)>
    <h3>A FAST Dialog Component</h3>
    <div>
        <fast-button appearance="accent" @onclick="@((e) => IsActive = false)">
            Hide Dialog
        </fast-button>
    </div>
</fast-dialog>
<fast-button appearance="accent" @onclick="@((e)=> IsActive = true)">
    Show Dialog
</fast-button>

@code
{
    public bool IsActive { get; set; }
}
```
3. Start the application
4. When application is running in the browser, press F12 to open the Console window
5. Press F5 several times to refresh the browser window
6. This error appears in the console window: 
```
Uncaught TypeError: t.querySelectorAll is not a function
    at xo (fast-components.min.js:15)
    at MutationObserver.onChildListChange (fast-components.min.js:15)
```

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/4997164/98347018-23afea00-2017-11eb-933a-4a9a03d246e1.png)

**In what environment did you see the issue?**

* OS & Device: Windows10
* Browser Microsoft Edge 86.0.622.61, Google Chrome 86.0.4240.183

**Comment by EisenbergEffect** [comment]
@LucSuy Does this error only happen intermittently? You mention pressing refresh several times so I wanted to get some clarification on that. Thank you!

**Comment by LucSuy** [comment]
> @LucSuy Does this error only happen intermittently? You mention pressing refresh several times so I wanted to get some clarification on that. Thank you!

@EisenbergEffect Just tested it again. Pressing F5 causes the error to appear "most of the times", when pressing CTRL+F5 the error appears "sometimes". If you wish I can make some screen recordings of it.

**Comment by EisenbergEffect** [comment]
@LucSuy No need for the screen recordings. I'll dig in and make sure I can reproduce this and see if I can tell what's going on. Thanks!

**Comment by EisenbergEffect** [comment]
I finally got around to looking into this. Apologies for the delay @LucSuy I've got a PR up that should fix the problem. I need a few other team members to review it though as this may have uncovered some additional issues with the dialog and I need folks more familiar with some of those details to take a look. Thanks for your patience!

**Comment by LucSuy** [comment]
@EisenbergEffect thanks a lot for the fix. 
And yes, as you state "_Given the nature of this bug, I'm not sure that tabbable was working correctly with the dialog ever._", I indeed encountered tabbing problems in the dialogs too.

**Comment by EisenbergEffect** [comment]
@LucSuy Thank you for the confirmation 😄  Hopefully this will address the other issues as well. Side note: we're in process on making some decisions and getting moving on some new e2e tests for our components, so those should help mitigate issues like this in the near future.
