### ISSUE TITLE
No default expanded state for Tree Items with children

### ISSUE THREAD

**Issue by jchen790** [microsoft/fast#4113]
**Describe the bug; what happened?**
When you run Narrator on Tree View, for Tree Items with children, there is not default expanded state. As a result, Narrator doesn't state whether the Tree Item is expanded or not.

**What are the steps to reproduce the issue?**
1. Go to https://explore.fast.design/components/fast-tree-view
2. Turn on Narrator
3. Click on "Tree Item 1"
4. Notice that Narrator doesn't state whether the item is expanded or collapsed

**What behavior did you expect?**
In the example above, would expect Narrator to state that the Tree Item is collapsed initially.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
Able to see this in Edge Chromium Stable and Canary.

**Comment by chrisdholt** [comment]
Thanks @jchen790!
