### ISSUE TITLE
Add testing suite to fast-foundation

### ISSUE THREAD

**Issue by tgoze** [microsoft/fast#4119]
Currently, testing functionality is written into fast-foundation. Specifically, the `fixture` function is used to test custom elements, templates, and bindings in the DOM. It would be convenient to use this when developing custom elements.

The functionality should be exported as a testing suite from fast-foundation. Accompanying documentation would be nice as well.

**Comment by chrisdholt** [comment]
Thanks @tgoze for the issue! I think the primary question I have is whether fast-foundation is the right place for the testing utility to be extracted to. It definitely could be, but determining packages and exports is always a bit tricky when we consider extensibility and long term goals. 

@EisenbergEffect as FYI - might be good to determine if there are other testing utilities or perhaps other generic WC utilities that we might want to make available.

**Comment by EisenbergEffect** [comment]
I would like to pull this out into its own test library and continue to grow the test capabilities as its own thing. I think there's probably a good bit we can do there over time to facillitate various testing scenarios. I'd propose `@microsoft/fast-testing`.

**Comment by chrisdholt** [comment]
I'm going to close this as stale and out of scope given our current project state. Feel free to reopen or propose again if you're particularly passionate about it!

**Comment by EisenbergEffect** [comment]
For 2.0 I moved all the testing helpers to `@microsoft/fast-element/testing`. There are basic source code docs in place. Planned docs articles on testing are also including in our vNext documentation proposal here: https://github.com/microsoft/fast/issues/6527
