### ISSUE TITLE
fast-text-field does not use the --font-family

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#4132]
I am trying to use Fast and set a custom font. I can see that not all the Fast Components are not using the specified Font.

I would have expected that.

![image](https://user-images.githubusercontent.com/42288570/99622764-16d5c200-2a2b-11eb-88f7-798219461cb9.png)

```html
<html>
    <head>
        <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
    </head>
<body style="margin:0px">
    <fast-design-system-provider use-defaults body-font="Times New Roman" style="min-height:100vh;padding:25px;">
        <p>Hello</p>
        <fast-button>World</fast-button>
        <fast-text-field ></fast-text-field>
    </fast-design-system-provider>
</body></html>
```

I'm using Chrome on Windows.

#### Additional Context

I also saw the bug for the `fast-text-area`. If you recognize that this is a bug and not a misunderstanding from my side then you probably should check all your components.

**Comment by chrisdholt** [comment]
Thanks @MarcSkovMadsen - I don't see this on Text Area, but I do see it on text field as well as several other components. A good test in the repo was to swap the body font to Wingdings and watch what happens :). I'll have a PR up soon for this. 

As an FYI, I'm not sure that `body-font` as an attribute would work as you have above. I do know that you can either apply it in CSS such as;

```css
fast-design-system-provider {
    --body-font: "Times New Roman";
}
```
Alternatively you can also apply that as an inline style:
```html
<fast-design-system-provider style="--body-font: 'Times New Roman'"></fast-design-system-provider>
```
