### ISSUE TITLE
Disabled listbox is missing styles and allows click events

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#4137]
**Describe the bug; what happened?**
The `listbox` component doesn't fully support its `disabled` attribute, which should prevent mouse interaction and change its appearance to show that it's disabled.

**Comment by EisenbergEffect** [comment]
Did we fix this or should we bump it to our next milestone?

**Comment by chrisdholt** [comment]
@radium-v thoughts on how you would like to see this handled?

**Comment by radium-v** [comment]
The `disabled` property can't be present on the base class `Listbox` when constructing, due to `FormAssociated` inheritance with `Combobox` and `Select`. These controls gain the `disabled` property from the `FormAssociated` base class which would collide with the property if it's present on `Listbox`.

In #4974 I'm splitting the `Listbox` class into an abstract class `Listbox` and a component class `ListboxElement`, which will allow all three components to scaffold the property either through extension or direct definition.
