### ISSUE TITLE
CAPS+ Enter doesnt select from the list of dropdown in Select component 

### ISSUE THREAD

**Issue by aayushd** [microsoft/fast#4149]
**Describe the bug; what happened?**

**What are the steps to reproduce the issue?**
1. Go to edge://settings/appearance . Notice the theme dropdown which uses the Select component from fast-components-react-msft
2. start narrator on windows
3. open the dropdown of the select component
4. focus on some dropdown item
5. use CAPS+Enter

expectation-
the option should get selected

Observation-
nothing happens

**What behavior did you expect?**

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
Windows

* OS & Device: windows
* Browser- Edge
* Version Any version should repro it. I tested on 89.0.707.0 

**Is there any additional context?**

**Comment by chrisdholt** [comment]
This is a component which no longer exists in this repository and is no longer being maintained here. Closing this as in actionable for FAST.
