### ISSUE TITLE
FAST fails to work properly with latest version and Safari

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#4151]
**Describe the bug; what happened?**

When running the latest version of FAST on safari there is a new issue that makes FAST not working. This happened for me in an Aurelia 2 application. Should be noted that it didn't happen with previous version of FAST.

**What are the steps to reproduce the issue?**

Example:

1. Follow the [steps described in the doc](https://www.fast.design/docs/integrations/aurelia) to create an Aurelia2 application with FAST
2. Start the app with Safari; my version: Version 14.0.1 (15610.2.11.51.10, 15610)

The console prints the following error:

```
TypeError: undefined is not an object (evaluating 'this.sheet.rules[this.sheet.insertRule(hostSelector)].style')
```

**What behavior did you expect?**

The app should start normally

**If applicable, provide screenshots:**

<img width="723" alt="Capture d’écran 2020-11-27 à 17 37 23" src="https://user-images.githubusercontent.com/4275071/100469785-3af26c80-30d7-11eb-87ef-3e47a4ab6231.png">

**In what environment did you see the issue?**

* OS & Device: MacOS Catalina
* Safari Version 14.0.1 (15610.2.11.51.10, 15610)
* FAST Elements: 0.20.0
* FAST Components: 1.12.0

**Is there any additional context?**

As mentionné this started to happen after upgrading to FAST Components 1.12.0

**Comment by MarcSkovMadsen** [comment]
I see the same problem. But for all browsers on my iphone: Safari, Edge , Chrome
