### ISSUE TITLE
Create a web component for the `<color>` syntax

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4175]
# Abstract

As a line item in #4174 this is the task to create a web component for the `@microsoft/fast-tooling-react` packages custom CSS control export (see #4174 for details on the files making up the CSS control).

## Requirements

The `<color>` syntax which can be identified in the file `css-data.js` as part of the syntaxes export consists of the following: `<rgb()> | <rgba()> | <hsl()> | <hsla()> | <hex-color> | <named-color> | currentcolor | <deprecated-system-color>`. What should be possible initially is the ability to set the color as a HEX.

- Use the `FormAssociated` method for mirroring an input found in the implementations of `<fast-checkbox>` and `<fast-text-field>`
- Allow the user to pick from a color wheel
- Allow the user to input into a text field a HEX color
- Place the created web component files in a folder `packages/tooling/fast-tooling-react/src/form/custom-controls/css/`
- These files should use the `@microsoft/fast-element` package
- The control should be added to the `custom-elements.d.ts` file
- The React rendering should be a simple function as well as a function to handle change events in the `control.css.utilities.tsx` file
- The above React rendering function should be called in the `control.css.utilities.syntax.tsx` file where the switch case is `"<color>"`

**Comment by EisenbergEffect** [comment]
@janechu Is this completed?

**Comment by williamw2** [comment]
Closing as it has been merged into feature branch and is pending merge into master.
