### ISSUE TITLE
FAST and BLAZOR - How to change the color pallet of fluent-design-system-provider with Blazor

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4209]
**Describe the bug; what happened?**
I am evaluating the new Microsoft fast.design https://www.fast.design/ with **fluent-design-system-provider** and trying to customize the accent color for Blazor project but no luck...

This is what I did so far as per the official documentation (https://www.fast.design/docs/design-systems/fast-frame):

In my asp.net core **Blazor Server Project's _Host.cshtml**

```
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Title </title>
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="Test.Main.styles.css" rel="stylesheet" />
</head>

<body>
    <fluent-design-system-provider use-defaults>
        <component type="typeof(App)" render-mode="ServerPrerendered" />

        <div id="blazor-error-ui">
            <environment include="Staging,Production">
                An error has occurred. This application may no longer respond until reloaded.
            </environment>
            <environment include="Development">
                An unhandled exception has occurred. See browser dev tools for details.
            </environment>
            <a href="" class="reload">Reload</a>
            <a class="dismiss">🗙</a>
        </div>
    </fluent-design-system-provider>

    <script src="_framework/blazor.server.js"></script>
    <script type="module" src="https://unpkg.com/@@microsoft/fast-components"></script>
    <script type="module" src="https://unpkg.com/@@fluentui/web-components"></script>
    <script type="module" src="~/script/site.js"></script>
</body>
</html>
```

After this in my **site.js** added in my **wwwroot/script** folder I am trying to generate and replace the color pallete as mentioned in the documentation https://www.fast.design/docs/design-systems/fast-frame#generating-and-replacing-palettes

```
import { parseColorHexRGB } from "@microsoft/fast-colors";
import { createColorPalette } from "@microsoft/fast-components";

// Initialization
(function () {
    const palette = createColorPalette(parseColorHexRGB("#28EBD7"));
    const provider = document.querySelector("fluent-design-system-provider");

    // change the neutral color pallete
    provider.neutralPalette = palette;    
})();
```

I get the following error, Uncaught TypeError: Failed to resolve module specifier "@microsoft/fast-colors". Relative references must start with either "/", "./", or "../".

How do i resolve this, what am I missing here in my site.js ?

**Comment by EisenbergEffect** [comment]
@ameyasubhedar Most of the team is out on vacation now. Folks should start trickling back in next week. Thank you for your patience.

@nicholasrice can you provide some guidance on this when you are back in office? Let's also think about whether there's some documentation improvements we can make.

**Comment by nicholasrice** [comment]
@ameyasubhedar It looks like your `site.js` just isn't importing the modules from the right location; there is no `"@microsoft/fast-colors"` and `"@microsoft/fast-components"` in the filesystem to import from. Changing to the following worked locally for me (minus the Blazor stuff).

```js
// site.js
import { parseColorHexRGB } from "https://unpkg.com/@microsoft/fast-colors";
import { createColorPalette } from "https://unpkg.com/@microsoft/fast-components";
```
