### ISSUE TITLE
Conditional template binding causes template not to update in certain scenarios

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4213]
**Describe the bug; what happened?**
When the `repeat` directive and the `when` directive are used in conjunction, the template fails to update in a case where the `when` directive switches between true and false cases. See https://webcomponents.dev/edit/GvZ1ei7qxCZ4n9n27vzo for a min repro of the issue.

**Comment by nicholasrice** [comment]
It appears that this repros without the `repeat` directive; I've updated the above repro link to illustrate.

**Comment by jayjl** [comment]
I am experiencing the same issue with this. Thanks Nick for chatting about it offline. Please let me know when this can be fixed. Really appreciate!

**Comment by Holyphoenix** [comment]
This issue is also impacting me.

**Comment by nicholasrice** [comment]
It seems that this doesn't have anything to do with the `when` directive inherently, and more to do with re-binding of template instances. In this [min repro](https://webcomponents.dev/edit/7wWVRpdUUBb3mQ2agAse) a template that is defined inline *in* a binding expression will unbind and rebind w/ the expected behavior, but a template stored in an external variable and *used* in the binding expression does not get re-bound correctly and will not update after being rendered, removed, and rendered again.
