### ISSUE TITLE
text-field's label div is not properly hidden when start or end slots have content 

### ISSUE THREAD

**Issue by SethDonohue** [microsoft/fast#4219]
**Describe the bug; what happened?**
In Text Field when there is content in the start or end slots the label div is _not_ hidden causing Text Field to have a larger height than it should.

With Start:
<img width="203" alt="Screen Shot 2021-01-04 at 2 16 30 PM" src="https://user-images.githubusercontent.com/31681651/103585221-8a2a7a80-4e97-11eb-990b-e486495ebe7e.png">

With End:
<img width="203" alt="Screen Shot 2021-01-04 at 2 16 48 PM" src="https://user-images.githubusercontent.com/31681651/103585217-8991e400-4e97-11eb-9790-e349e880a5c4.png">

**What are the steps to reproduce the issue?**
View with any Text Field that has content slotted in the `start` or `end` slots.

**What behavior did you expect?**

Should be similar to _default_ Text Field without a label where the height does not extend above the border.
<img width="170" alt="Screen Shot 2021-01-04 at 2 15 55 PM" src="https://user-images.githubusercontent.com/31681651/103585222-8ac31100-4e97-11eb-8894-862c83574468.png">

**In what environment did you see the issue?**

* OS & Device: MacOS on PC
* Browser Microsoft Edge, Google Chrome

**Comment by SethDonohue** [comment]
Looks like the template is interpreting the "white space" before and after the provided svg for start as `text` nodes, causing `defaultSlottedNodes` to have elements, leading to the label _not_ being hidden.
Not sure if this is a component change, slotted directive, or a templating issue.

I have highlighted in the code what it is seeing as `text` nodes, if this white space is removed the label is properly hidden. 
<img width="291" alt="Screen Shot 2021-01-13 at 12 25 07 PM" src="https://user-images.githubusercontent.com/31681651/104506541-6d2e2f80-559a-11eb-9d43-01117f716f41.png">

The same happens when I put `white space` in for text-area, the label is _not_ hidden.
<img width="399" alt="Screen Shot 2021-01-13 at 1 01 15 PM" src="https://user-images.githubusercontent.com/31681651/104510164-9a311100-559f-11eb-9771-cd545c6dfa7a.png">



@EisenbergEffect Is this already a known issues? Do we want to consider filtering out "empty" white space like this (where it is only white space and nothing else) for slotted content? Seems like that would be a bad idea and too heavy handed, causing problems elsewhere with formatting in other components and doing things an author wouldn't expect.

Will keep investigating unless I hear otherwise.

**Comment by EisenbergEffect** [comment]
White space is legitimately intended by the web standards to be projected into the slot. So, if we want to show/hide something internally, filtering out whitespace intentionally, I think we'd want to do that specific for a given component and not intentionally part of our slot directive, for example. What that means is that we probably need a custom filter for `defaultSlottedNodes` so that the conditional rendering isn't based on whitespace. The directive will let you write a filter and supply it. Detecting whitespace is a bit more tricky. I think there's some code inside fast-element for doing that but I'm not sure it's exported. I'll take a follow-up action to look into that and will comment later with some more info.

**Comment by chrisdholt** [comment]
> White space is legitimately intended by the web standards to be projected into the slot. So, if we want to show/hide something internally, filtering out whitespace intentionally, I think we'd want to do that specific for a given component and not intentionally part of our slot directive, for example. What that means is that we probably need a custom filter for `defaultSlottedNodes` so that the conditional rendering isn't based on whitespace. The directive will let you write a filter and supply it. Detecting whitespace is a bit more tricky. I think there's some code inside fast-element for doing that but I'm not sure it's exported. I'll take a follow-up action to look into that and will comment later with some more info.

@SethDonohue I don't think we want to filter out whitespace as you've shown for the slotted example above as that needs to be projected if it's part of something (such as a string). That space is a label as it's technically content.

I think the true culprit here is the whitespace in the template. Fixing that should address the issue IMO. It's possible that this could (or is?) able to be detected with the proposed linter @radium-v has out which would help when writing templates.

**Comment by SethDonohue** [comment]
@EisenbergEffect I agree which is why I was saying it sounded heavy handed. Thanks for the extra info on it! I think I'll explore a custom filter for `defaultSlottedNodes` on just text-field, and also keep an eye out for your follow up here.

@chrisdholt The whitespace in the template has no effect on this and does not cause this issue with the other text-field examples where no default slotted nodes are provided. I even removed the whitespace in the template to see and there is no difference. I can provide an example of that if needed. Just for clarification this only happens when start or end content is provided as the whitespace around the start or end content is interpreted as a text node by `defaultSlottedNodes`. This does not happen if nothing is slotted, as expected, so I don't think it is the whitespace in the template causing an issue.

Maybe we can filter whitespace out of the slotted nodes if and only if it is a text node and is _only_ whitespace? Just thinking out loud here.

**Comment by SethDonohue** [comment]
This regex filter seems to work.
Not sure I need the `nodeValue === "string"` check though. It is probably redundant since I am checking if it is nodeType of 3 and that is `text` so nodeValue _should_ always be a string, but I am having trouble confirming that.
``` js
export function whitespaceFilter(value, index, array) {
    return value.nodeType === 3 && typeof value.nodeValue === "string" && !value.nodeValue.replace(/\s/g, '').length ? false : true;
}
```

**Comment by SethDonohue** [comment]
The above _is_ also removing whitespace around any slotted html markup, but for this component the default slotted nodes become the label and any whitespace seems to be removed anyways.... which I just realized means I should be able to just use the `elements()` filter used elsewhere. That works the same.

**Comment by SethDonohue** [comment]
I've created a _draft_ PR with the changes:
PR #4245

**Comment by EisenbergEffect** [comment]
Looks like I removed the whitespace checking code some time back because it wasn't needed for the core. Glad you found a solution!
