### ISSUE TITLE
fast component explorer throws exception when changing tab orientation attribute twice

### ISSUE THREAD

**Issue by marjonlynch** [microsoft/fast#4221]
When changing the tabs component orientation via the drop down in the config panel, the first time it works but changing it back to `horizontal` causes an exception to be thrown

**What are the steps to reproduce the issue?**

1. Go to https://explore.fast.design/components/fast-tabs
2. change the orientation in the far right config panel to `vertical`
3. observe the tabs are now in vertical orientation
4. change the orientation attribute in the far right config panel again back to `horizontal`
5. observe no visual change to the tab and the exception message in the console

![Screen Shot 2021-01-04 at 3 47 23 PM](https://user-images.githubusercontent.com/25805778/103591174-383c2180-4ea4-11eb-9552-e68adcc7ad50.png)

**In what environment did you see the issue?**
Mac OS catalina, Edge Canary 89.0.756.0 and in Chrome 87.0.4280.88

**Comment by janechu** [comment]
This doesn't appear to be an issue in the local version and the site nor is it an issue on the staging site.

@awentzel @chrisdholt @EisenbergEffect I recommend we publish staging to production for the explore site on next publish. It should in fact be deploying every publish but I understand we've been off schedule for the last month or so.

**Comment by EisenbergEffect** [comment]
Agree. We need to get the sites updates. We're missing docs for all the new components...

**Comment by janechu** [comment]
This appears to be fixed in the latest release.
