### ISSUE TITLE
Blazor JsInterop function not binding data in fast-data-grid

### ISSUE THREAD

**Issue by ScottKane** [microsoft/fast#4227]
Using the example Blazor integration you should be able to achieve the same issue with the following:

In `wwwroot/` create a js file to hold interop functions (wwwroot/fastInterop.js):
```js
window.fastInterop = {
    setGridData: (id, data) => document.getElementById(id).rowsData = data
};
```

Then create a C# class to bind the equivalent function (FastInterop.cs):
```c#
public class FastInterop
{
    public static void SetGridData(IJSRuntime js, string id, object data)
    {
        js.InvokeAsync<string>(
            "fastInterop.setGridData",
            id,
            data); // Also tried serializing the object: JsonSerializer.Serialize(data)
    }
}
```

Create a razor file to be the Blazor component nesting the fast-data-grid (FastTable.razor):
```razor
@typeparam TItem
@inject IJSRuntime _js;

<h1>Data Grid</h1>

<fast-data-grid id="@_id"></fast-data-grid>

@code {
    [Parameter] public IList<TItem> Items { get; set; }

    private string _id;

    protected override void OnInitialized()
    {
        _id = $"{Items.FirstOrDefault().GetType().Name.ToLower()}s";
        FastInterop.SetGridData(_js, _id, Items);
    }
}
```

Create a POCO class to represent the data to be used in the fast-data-grid (Order.cs):
```c#
public class Order
{
    public Guid Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Gender { get; set; }
    public string Address { get; set; }
    public string Postcode { get; set; }
}
```

Create a Page to use the `FastTable` component (TestFastTable.razor)
```razor
@page "/test"

<FastTable Items="@_orders"></FastTable>

@code {
    private IList<Order> _orders = new List<Order>
    {
        new Order
        {
            Id = Guid.NewGuid(),
            FirstName = "John",
            LastName = "Doe",
            Gender = "Male",
            Address = "1  Alfred Drive",
            Postcode = "1111"
        },
        new Order
        {
            Id = Guid.NewGuid(),
            FirstName = "Jane",
            LastName = "Doe",
            Gender = "Female",
            Address = "4193  Woodhill Avenue",
            Postcode = "2222"
        }
    };
}
```

Now when you visit this page you would expect the fast-data-grid to be populated with the "Orders" which it isn't, it has a row for the header which is empty and no data rows.

```html
<fast-data-grid id="orders" role="grid" tabindex="0" generate-header="default">
  <fast-data-grid-row class="header" row-type="header"></fast-data-grid-row>
</fast-data-grid>
```

If while the app is running you navigate to the browser console and run `fastInterop.setGridData("orders", [{ item1: "value 1-1", item2: "value 2-1" }, { item1: "value 1-2", item2: "value 2-2" }, { item1: "value 1-3", item2: "value 2-3" }])`. The grid now shows a load of dividers bunched together but with no visible data. Inspecting the source shows that additional `fast-data-grid-row`'s  are added but are all empty.

```html
<fast-data-grid id="orders" role="grid" tabindex="0" generate-header="default">
  <fast-data-grid-row class="header" row-type="header"></fast-data-grid-row>
  <fast-data-grid-row row-type="default"></fast-data-grid-row>
  <fast-data-grid-row row-type="default"></fast-data-grid-row>
  <fast-data-grid-row row-type="default"></fast-data-grid-row>
</fast-data-grid>
```

* OS & Device: Windows 10 Pro 20H2
* Browser: Google Chrome
* Version: Latest

**Comment by ScottKane** [comment]
Modified interop binding classes so that I can consume the scoped IJSRuntime via a singleton and provide bindings statically.

```c#
public class FastInterop
{
    private static JsRuntime _js;
    public FastInterop(JsRuntime js) => _js = js;

    public static async ValueTask SetGridDataAsync(string id, object data)
    {
        await _js.InvokeVoidAsync(
            "fastInterop.setGridData",
            id,
            JsonSerializer.Serialize(data));
    }
}

public class JsRuntime
{
    private readonly IJSRuntime _js;
    public JsRuntime(IServiceScopeFactory factory)
    {
        using (var scope = factory.CreateScope())
            _js = scope.ServiceProvider.GetRequiredService<IJSRuntime>();
    }

    public async ValueTask InvokeVoidAsync(string identifier, params object[] args) => await _js.InvokeVoidAsync(identifier,  args);
}
```

This now results in the following:
```
Uncaught TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Object.getNotifier (fast-components.min.js:15)
    at Wt.observeItems (fast-components.min.js:15)
    at Wt.handleChange (fast-components.min.js:15)
    at O.notify (fast-components.min.js:15)
    at O.call (fast-components.min.js:15)
    at n (fast-components.min.js:15)
```
I had read that this could be caused by using toSet() and toSetSeq(), if thats the case maybe use toList(), toMap() or toArray() instead?

**Comment by ScottKane** [comment]
Although not serializing during the C# binding method and just passing the raw object adds the expected number of rows to the grid, they are however still empty.

**Comment by ScottKane** [comment]
You will also need to register the following:
```c#
services.AddTransient<JsRuntime>();
services.AddSingleton<FastInterop>();
services.BuildServiceProvider().GetRequiredService<FastInterop>();
```

**Comment by ScottKane** [comment]
This error was happening while loading fast from CDN, I have since pulled in fast through NPM and am serving it myself which solves the issue. Strange that binding the rowsData doesn't work from CDN

**Comment by janechu** [comment]
Closing this as it seems the issue has been resolved by pulling the package into npm, additionally this component and the `@microsoft/fast-components` package is no longer supported. Please check out Fluent UI web components for components built on FAST.
