### ISSUE TITLE
ASP.NET Core Data Annotation Validations and Model Binding Tag helpers  do not work with fast-components

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4228]
**Describe the bug; what happened?**

As per [official docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0), Blazor server uses ASP.NET core concepts for authentication e.g. Login that requires SignInManager... so for implementing Login.cshtml with fast components  (using fluent-design-system-provider) I tried to model bind using asp-for but that did not work ! Am I missing something or model biding tag helper with data annotation validators not supported by fast ?

**What are the steps to reproduce the issue?**

```
<fluent-text-field placeholder="user@email.com" asp-for="@Model.Input.Email">
 </fluent-text-field>
```

**Is there any additional context?**
Since Blazor server forces customers to use ASP.NET core to support user authentication, but fast-components not supporting the model binding and data annotation validations makes it difficult to migrate.

**Comment by EisenbergEffect** [comment]
My understanding is that the `asp-for` helper is not designed to work with arbitrary html elements, but only works with built-ins. We'll need to work with the community to resolve this. There may be some way to plug in on the .NET side and "teach" the `asp-for` helper how to properly bind to web components.

**Comment by matt-goldman** [comment]
I'm also interested in this. I'm overriding the scaffolded Identity pages so need this to work for that. I might try to get it working with something hacky in the meantime like hidden fields.

**Comment by EisenbergEffect** [comment]
Closing this now that we've got an official Blazor library at https://github.com/microsoft/fast-blazor that better supports .NET developers. If there are issues with the new library, please follow up there. Thank you!
