### ISSUE TITLE
Create a behavior for attaching component styles based on an appearance

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#4237]
Many of our components have an "appearance" attribute to define a given visual treatment (anchor, button, etc). Currently for a given component all styles are attached regardless of the component appearance. So if I have an input with a "filled" appearance, the "outline" appearance is also being created and attached as styles. Ideally, we should only include those styles which are being leveraged at a given time.

Ideally we can use something fairly generic like this:

```js
import { css } from "@microsoft/fast-element";
import { AppearanceBehavior } from "@microsoft/fast-foundation";

const buttonAccentBehavior = AppearanceBehavior.with("accent");

const styles = css`
  :host {
    background: grey;
    color: black;
  }
`
.withBehaviors(buttonAccentBehavior(css`
  :host {
    background: blue;
    color: white;
  }
`))
```

**Comment by EisenbergEffect** [comment]
To make sure I follow...is the idea that the behavior would observe the `appearance` attribute of the host element, and when its value equals "accent" it will add the specified stylesheet, otherwise it will not add or remove the styles?

**Comment by chrisdholt** [comment]
> To make sure I follow...is the idea that the behavior would observe the `appearance` attribute of the host element, and when its value equals "accent" it will add the specified stylesheet, otherwise it will not add or remove the styles?

Essentially, yes - consider the behavior we have for something like forced colors or match media but scoped to a given attribute value rather than the state of the OS or window.

**Comment by EisenbergEffect** [comment]
Cool. We can definitely do this. We can probably create a general mechanism for this so that we could even separate out the various attribute values, allowing for them to be tree-shaken.

**Comment by nicholasrice** [comment]
Small clarification since the question came up when syncing w/ this with Jeff, I think we would want to map this to observable *properties* and not content attributes, is that correct?

**Comment by EisenbergEffect** [comment]
I think so. If it's based on observable properties, we can use it with any property that uses our system and not just html elements. If I'm following you...

**Comment by eljefe223** [comment]
Thinking something like this:

```
export function appearanceBehavior(value: string, styleSheet: ElementStyles) {
    return new PropertyStyleSheetBehavior("appearance", value, styleSheet)  
}
```

```
.withBehaviors(
  appearanceBehavior("stealth", css`...`),
  appearanceBehavior("outline", css`...`),
  etc.
)
```

Any thoughts or objections?

**Comment by EisenbergEffect** [comment]
This is a good solution with what we have today. There are other options once the DI system is in place, if you want to be able to resolve appearance values from the design system itself and tree-shake out ones that customers aren't using. For example, you could have something like this:

```ts
.withBehaviors(
  appearanceBasedStyles("neutral")
);
```

where `appearanceBasedStyles` does something like this

```ts
function appearanceBasedStyles(defaultAppearance: string) {
  return {
    bind(element) {
      // subscribe to appearance property of element and call appearance changed
      this.onAppearanceChanged(element);
    }

    onAppearanceChanged(element) {
      const container = DI.findContainer(element);
      const styleSheet = container.get(`${element.tagName.toLowerCase()}:appearance:${element.appearance || defaultAppearance}`);
      // check if its the same as previous style sheet and remove old
      // add new style sheet to element via $fastController
    }
  }
}
```

It depends on what direction you want to go. With the DI-based solution, the actual appearance style sheets are decoupled and can be added/removed/extended by the end user through configuration. For example, we could have something like this:

```ts
new DesignSystem()
  .register(
    button(),
    buttonNeutralAppearance
    buttonStealthAppearance,
    buttonOutlineAppearance,
    buttonCustomAppearance
  )
```

All the above functions do is register the style sheet with the container using the same key pattern that the behavior uses to resolve them.

This is possible once this PR is merged: https://github.com/microsoft/fast/pull/4166
