### ISSUE TITLE
Blazor/Razor fast-checkbox does not model bind (2-way)

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4248]
**Describe the bug; what happened?**

Model binding for fast-checkbox does not work. This basically means that we cannot use the fast-checkbox in HTML forms with model binding.

For e.g. if I use fluent-text-field, I can bind the value to the onchange event and this works perfectly. I am able to update my model with 2-way binding.

```
   <fluent-text-field @ref="@element" appearance="@Styling.Appearance.Accent" placeholder="@Placeholder" @bind-value="@CurrentValue" @bind-value:event="onchange" type="@Type">
        @Title
    </fluent-text-field>
``` 

However if I try to use the model binding with fast-checkbox does not work, the events are not fired and values on Model are not updated based on User Interaction

```
<fluent-checkbox @bind-checked="@CurrentValue" @bind-checked:event="onchange">
        @Title
 </fluent-checkbox>
```

This is the issue.

Visual Studio 2019
Razor Components
Blazor WebAssembly
Blazor Server

**Comment by nicholasrice** [comment]
@ameyasubhedar are you saying that a change event is never fired from the checkbox?

**Comment by ameyasubhedar** [comment]
@nicholasrice, I think the change event works but fast checkbox value is not updating based on the change event.  We have to do it manually.

// This works
<input type="checkbox" @bind="CurrentValueBool" />

**// This does not work**
<fast-checkbox @bind-checked="CurrentValueBool" @bind-checked:event="onchange"></fast-checkbox>

// This works (but manual binding is required)
```
@inherits InputCheckbox

@* Fast cannot bind to boolean directly
      https://github.com/microsoft/fast/issues/4248
*@
<fluent-checkbox checked="@CurrentValue" @onchange="UpdateCurrentValue">
    @Title
</fluent-checkbox>

@code {

    private void UpdateCurrentValue(ChangeEventArgs e)
    {
        if (e.Value != null && e.Value.Equals("on"))
        {
            CurrentValue = true;
        }
        else
        {
            CurrentValue = false;

        }

    }
}
```

**Comment by ameyasubhedar** [comment]
@nicholasrice, Actually even the manual binding does not work correctly.... **@onchange event sends ChangeEventArgs e.Value="on" for both checked and non-checked state.**

```
 private void BindCurrentValue(ChangeEventArgs e)
    {

        if (e.Value != null && e.Value.Equals("on"))
        {
            CurrentValue = true;
        }
        else
        {
            CurrentValue = false;

        }

    }
```

**Comment by nicholasrice** [comment]
Ahhh okay. The `value` isn't *supposed* to change. Only `checked` is supposed to change. The Checkbox WC is modeled off of the native platform `input[type='checkbox']`, which  exhibits the same behavior: https://codesandbox.io/s/fragrant-tdd-udihc?file=/index.html

**Comment by ameyasubhedar** [comment]
@nicholasrice, thanks that make sense now as to why Value is on always. But the core problem stays in case of manual binding as a workaround of the solution ChangeEventArgs only has the Value field, so the onchange callback BindCurrentValue does not have access to checked state ?

**Comment by nicholasrice** [comment]
I may not be familiar enough with Blazor to have insight into what is going on here. You're saying `ChangeEventArgs` doesn't have a `checked` property?

**Comment by ameyasubhedar** [comment]
Nope, it does not and I think that leaves us no way to bind the checked state back to the model. Ideally Value should have reflected the new checked state but since that the native HTML behavior there should at-least be a way for applications to access the checked state

**Microsoft Source**

> using System;
> 
> namespace Microsoft.AspNetCore.Components
> {
>     //
>     // Summary:
>     //     Supplies information about an change event that is being raised.
>     public class ChangeEventArgs : EventArgs
>     {
>         public ChangeEventArgs();
> 
>         //
>         // Summary:
>         //     Gets or sets the new value.
>         public object? Value { get; set; }
>     }
> }

**Comment by ameyasubhedar** [comment]
@nicholasrice, any update on the fix or the timeline. Check box is a basic component and needs to support model binding for asp.net applications.

**Comment by ameyasubhedar** [comment]
@EisenbergEffect: Can you please comment on when can we expect a fix for this, no binding means no way for application to know what users selected, and this major issues for asp.net core apps

**Comment by EisenbergEffect** [comment]
@ameyasubhedar We haven't made an announcement yet, but we we are working with the Blazor team to make FAST's FluentUI official for Blazor. We're working through the details including both issues on our side and the Blazor side. Things are quite busy right now with the Build conference coming up very soon. So, it's hard to make predictions about specific issues and timelines.

If you are interested in this, would you mind checking out the official Blazor Nuget package? You can find our new repo here: https://github.com/microsoft/fast-blazor

The Nuget packages have special configuration to improve bindings with the web components, as well as other more .NET-like APIs to improve the developer experience. Please give it a try and see how it works for you.

I'm going to close this issue for now since we are tracking it for the official package here: https://github.com/microsoft/fast-blazor/issues/39
