### ISSUE TITLE
Add character counter to/in text fields

### ISSUE THREAD

**Issue by robsonsobral** [microsoft/fast#4257]
Hi!

I just arrived at this project and still don't know what kind of feature do you prefer to implement.

**What feature are you requesting?**

Is it possible to add characters counters to the corner of text fields?

**What would be the benefit of adding this feature?**

It would help users to plan their text ahead of reaching the field limit.

**What solution would be ideal for you?**

A parameter? Something like `show-field-limit`? Maybe the current count, the slash and the total colors could be customizable...

**What alternatives have you considered?**

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

![image](https://user-images.githubusercontent.com/931642/105399678-b9184e80-5c02-11eb-9447-24abcd1f9e3f.png)

Thank you!

**Comment by chrisdholt** [comment]
Closing as stale - FWIW this can likely be accomplished via extending the class and passing the character count in the end slot (as an example).
