### ISSUE TITLE
Replace instances of the deprecated React component ActionToggle with fast-switch

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4267]
# Description

Replace the `<ActionToggle />` component from the deprecated package @microsoft/fast-components-react-msft in:
- `./sites/fast-creator/app/creator.tsx`
- `./sites/fast-component-explorer/app/explorer.tsx`
With `<fast-switch>`.

**Comment by williamw2** [comment]
Closing as it has been merged into feature branch and is pending merge into master.
