### ISSUE TITLE
Remove deprecated FAST packages from the Creator, Site utilities and Component Explorer sites

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4270]
# Description

This is the parent issue detailing the removal of the dependency on `@microsoft/fast-components-react-msft` and `@microsoft/fast-components-styles-msft` and `@microsoft/fast-jss-manager-react` that are still used in the sites Creator and Component Explorer.

## Requirements to remove `@microsoft/fast-components-react-msft`

The removal of `@microsoft/fast-components-react-msft` requires the replacement of any React components with the equivalent web component from `@microsoft/fast-components` or the use of styling provided by the `<fast-design-system-provider>` web component in the form of CSS variables.

### Site utilities

- [#4262] Replace `<Label />` component used in the `./sites/site-utilities/src/components/accent-color-picker-index.tsx`
- [#4263, #4264] Replace `<ActionTrigger />` and `<NumberField />` components used in `./sites/site-utilities/src/components/dimension/index.tsx`
- [#4265, #4266, #4268] Replace the `<Background />`, `<Badge />`, `<Heading />` components in the `<Logo />` component
- [**TBD - reliant on the above issues being solved**] Remove the dependency on `@microsoft/fast-components-react-msft`

### Creator
- [#4267, #4268] Replace `<ActionToggle />`, `<Background />` from `creator.tsx`
- [**TBD - reliant on the above issues being solved**] Remove the dependency on `@microsoft/fast-components-react-msft`

### Component Explorer
- [#4267, #4268, #4269] Replace `<ActionToggle />`, `<Background />`, `<Select />`, `<SelectOption />` components from `explorer.tsx`
- [**TBD - reliant on the above issues being solved**] Remove the dependency on `@microsoft/fast-components-react-msft`

### Site utilities

- [#4271] Replace the `StandardLuminance` in the `<Editor />` component `index.tsx` and `editor.props.ts` to use the `StandardLuminance` in `./packages/web-components/fast-components/src/color/neutral-layer.ts`
- [#4272] Replace the `ColorRecipe` in the `<Logo />` component props
- [#4271] Replace the `StandardLuminance` in the `<ThemeSelector />` component `index.tsx` and `theme-selector.props.ts` files to use the `StandardLuminance` in `./packages/web-components/fast-components/src/color/neutral-layer.ts`
- [**TBD - reliant on the above issues being solved**] Remove the dependency on `@microsoft/fast-components-styles-msft` in the `package.json`

### Creator
- [#4268] Replace `neutralLayerL1` and `neutralLayerL2` from `creator.tsx`
- [#4271] Replace `StandardLuminance` in the `creator.props.ts` file to use the `StandardLuminance` in `./packages/web-components/fast-components/src/color/neutral-layer.ts`
- [#4274] Replace the `DesignSystem` from the `preview.style.ts`
- [#4274] Remove `DesignSystem`, `neutralLayerFloating` and `neutralLayerL2` from the `creator.style.ts`
- [**TBD - reliant on the above issues being solved**] Remove the dependency on `@microsoft/fast-components-styles-msft`

### Component Explorer
- [#4274] Replace the `DesignSystem` from the `preview.style.ts`
- [**TBD - reliant on the above issues being solved**] Remove the dependency on `@microsoft/fast-components-styles-msft`

### Creator & Component Explorer

- [#4275] Remove the JSS wrappers from the creator component and component explorer region component
- [#4275] Wrap the application in `<fast-design-system-provider>` web component
- [**TBD - reliant on the above issues being solved**] Remove the dependency on `@microsoft/fast-jss-manager-react`

**Comment by EisenbergEffect** [comment]
@janechu Can we close this now?

**Comment by janechu** [comment]
@EisenbergEffect yes, now that we have a new direction on the Component Explorer I'll close this now.
