### ISSUE TITLE
Remove DesignSystem reference from sites

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4274]
# Description

The `DesignSystem` and other imports from the `@microsoft/fast-components-styles-msft` package which is deprecated. 

## Requirements
- Remove the imports from `sites/fast-creator/app/preview.styles.ts`, `sites/fast-component-explorer/app/preview.styles.ts` & `sites/fast-creator/app/creator.style.ts`
- Create a CSS stylesheet for import using the same global styles expressed in the above files
- Note: any actual use of the preview should rely on a class name int he above stylesheet

**Comment by williamw2** [comment]
Closed in features/remove-deprecated-site-component-dependencies bending merge into master.
