### ISSUE TITLE
Remove the JSS wrapper

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4275]
# Description

Remove the JSS wrapper from the following locations:
- `sites/fast-component-explorer/app/preview.tsx`
- `sites/fast-creator/app/preview.tsx`

Remove the `DesignSystemProvider` from the following locations:
- `sites/fast-component-explorer/app/explorer-region.tsx`
- `sites/fast-creator/app/app.tsx`

Add the `<fast-design-system-provider>` web component as a wrapper.

Ensure that all styles are rendering correctly with the correct conversion for the new FAST design system provider.

**Comment by williamw2** [comment]
Closed in features/remove-deprecated-site-component-dependencies bending merge into master.
