### ISSUE TITLE
 Security: weekly security, accessibility, and privacy scans 

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4280]
This is to resolve issues from code scanning from WebScout.

You can view the results of this scan at https://webscout/#/scans/862909.

Total URLs: 72
Total issues found: 10
URLS with issues: 17
Suppressed issues: 9
Time in queue: 0h 5m 43s
Scan duration: 9h 5m 13s

For this Work Item, I only want to tackle improvement for Non Suppressed items (new items) with medium severity or higher.

Investigate and creating new GH issues about each problem and proposed solution.

**Comment by awentzel** [comment]
Closing, as there are more recent scans making this moot.
