### ISSUE TITLE
Add fast-icon wrapper component

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#4287]
## Problem

Controls often share consistent padding for visual balance and for stacks or rows to align properly. Control padding is often expressed simply like "12px padding left and right and 8px between elements, for instance, like in this button:

![image](https://user-images.githubusercontent.com/47367562/105788283-09f6b280-5f35-11eb-9d98-955adc135f4c.png)

Many modern icon libraries build in padding to the icons. This is done to allow for visual weighting or to make a feature more pronounced. For instance, the Fluent icons include a modifier system that extends into the trim (padding) area.

![image](https://user-images.githubusercontent.com/47367562/106215538-0c9c1680-6186-11eb-9b62-796ce3041f91.png)

If something looks off about the example above it's because the icon on the left, while filling the entire live area, includes 2px padding on all sides. The result is 14px on the left, 10px between, and 12px on the right:

![image](https://user-images.githubusercontent.com/47367562/105789209-dfa5f480-5f36-11eb-87bc-9e685b39cc32.png)
(note the icon is shown with the live area selected, not the full area including padding)

## Proposed solution

Add an `icon` component to `fast-components`.

The component references an optional design system variable `icon-padding` that defaults to `2px.` The thought behind the default is that if you're not using icons with padding you don't need the wrapper, so `0` isn't the right default. Based on the research above, `2px` is highly common.

The component applies the value as a negative margin on the `svg` element:
```css
svg {
    margin: var(--icon-padding, 2px);
}
```

This allows the same configuration described above to layout as expected while allowing icons of various size and padding.

![image](https://user-images.githubusercontent.com/47367562/106219208-c64ab580-618d-11eb-9c40-26d1a7d559bb.png)

**Comment by chrisdholt** [comment]
Closing as we've removed/deprecated the fast components package.
