### ISSUE TITLE
loss of tabindex attribute and unable to tab 2+ fast-menu-item in fast-menu

### ISSUE THREAD

**Issue by lee-leonardo** [microsoft/fast#4290]
**Describe the bug; what happened?**

The issue deals with tabbing through the child elements of the fast-menu component. If you press tab, the first child is correctly focused, but upon a subsequent tabs it skips the rest of the children and jumps to the next element. So this behavior seems to suggest that menu-items by default are taken out of the tabindex. When manually setting the tabindex, if you tab over the element and tab to the next item, the tabindex attribute is removed from the component as well. 

This is to address a problem we've experienced prior with our accessibility team.
In narrator mode the keys are accessible as intended the issue that is left is the tab order.

https://github.com/pwa-builder/PWABuilder/issues/810

**What are the steps to reproduce the issue?**

You can reproduce this issue on the demo page:

https://explore.fast.design/components/fast-menu

also on our website here:
https://nice-field-047c1420f.azurestaticapps.net/

you can download our repo and run the app (npm run dev) locally. Please checkout `v3_menu`, which has the latest menu related code.

Example:

1. Click on the menu button, or ensure focus is in the container element
2. Press tab
3. Press tab
4. Manually set tabindex on the menu-item components
5. repeat steps 1-3
6. tab again or shift+tab

On our app, if you notice rather than moving to the next visible element (e.g. the next menu item), it moves to the button below. The same behavior is replicable within the demo page.

**What behavior did you expect?**

The next tabbed item should be the next fast-menu-item as it is the next visible interactable element.

* OS & Device: MacOS
* Browser:
  *  Microsoft Edge, Google Chrome, Safari: only able to tab the first menu item
  * Mozilla FireFox: unable to tab any of the fast-menu-items

**Is there any additional context?**

@jgw96 @JudahGabriel @davrous

**Comment by chrisdholt** [comment]
Thanks for the issue and the repro @lee-leonardo. For clarity, are you expecting that you should *tab* through the menu items? If so, I think this is likely a misunderstanding of how one navigates through the menu. While tab does bring you into the menu, subsequent menu items are navigable via the arrow keys. While this describes both a menubar and menu's, the navigation is accurate for tab as described here: https://w3c.github.io/aria-practices/#keyboard-interaction-12

**Comment by lee-leonardo** [comment]
Ah okay good to know, if the accessibility team does push back on it, then we're better equipped to push back. Thanks!
