### ISSUE TITLE
Slotted Directive Behavior is Inconsistent with Documentation

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#4293]
**Describe the bug; what happened?**
According to the documentation for the [Slotted Directive](https://www.fast.design/docs/fast-element/using-directives#the-slotted-directive), the property that the reference is assigned to should be available in connectedCallback. When the reference property is logged to the console in the connectedCallback, it returns an empty array instead of the slotted nodes for the reference.

If this is the expected behavior then the example in the documentation probably shouldn't be accessing the property in connectedCallback, because this can lead to confusion as to what the expected behavior should be.

**What are the steps to reproduce the issue?**
1. Copy the example from [Slotted Directive](https://www.fast.design/docs/fast-element/using-directives#the-slotted-directive)
2. In the browser console the console.log() output from the example will be an empty array.

**What behavior did you expect?**
The slotted property should be accessible in connectedCallback.

**If applicable, provide screenshots:**
This [pen](https://codepen.io/kingoftac/pen/KKNwRKJ) shows the issue.

**In what environment did you see the issue?**
Windows 10
Microsoft Edge | 90.0.782.0 (Official build) canary (64-bit)

**Comment by EisenbergEffect** [comment]
@KingOfTac Thanks for reporting this! I'll get this corrected. 

The property is set to an empty array by the connected callback, but may not be updated with the slotted nodes because the browser may not have projected them yet. The best way to respond is to make the property `@observable` and add a change handler so you can be notified whenever the slotted nodes change.

**Comment by KingOfTac** [comment]
@EisenbergEffect That makes sense, thanks. I have been using the attribute changed callback as a work around, however, this breaks down in cases where you have multiple slotted directives and need to pass the slotted elements along to a third party library. 

My specific use case for this is I have a custom element that is a wrapper/provider for Popper.js. The element has two slots that I am using to pass elements to the Popper constructor. Ideally this would need to be done during connectedCallback, but like you mentioned they are not available yet. I have found that I can work around this by getting the elements directly from the view behaviors on $fastController, but it feels a bit hacky to do this.

One idea I had for this was possibly adding another event which component authors could hook into that runs after connectedCallback, but that may just be adding clutter to the api.

**Comment by EisenbergEffect** [comment]
Hmm. I'm trying to be careful not to add additional lifecycle hooks other than the ones provided by the platform. It seems simple but can introduce a surprising amount of complexity in implementation.

Can you share a code sample for how you are interacting with `$fastController`. I can provide some feedback on the approach.

When needing to pass two different slots along to a 3rd party library, that is a bit tricky. The platform doesn't really provide a hook you can tap into when all of the elements are slotted. I think would just need to track state across the two callbacks, or you could wire into `slotchanged` for each slot directly and try to coordinate across them.

**Comment by KingOfTac** [comment]
I don't think this is the best solution because of how deep I have to dig into $fastController, so I am open to suggestions for a better solution.

```
connectedCallback() {
    super.connectedCallback();
    this.slotted1 = this.$fastController.view.behaviors[0].target.assignedNodes[0];
    this.slotted2 = this.$fastController.view.behaviors[1].target.assignedNodes[0];

    someThirdPartyConstructor(this.slotted1, this.slotted2);
}
```

**Comment by EisenbergEffect** [comment]
Interesting. Yes, this is pretty brittle code. As an alternative, place a `ref` on each of the slots and use that to access it's assignedNodes. That said...I'm not sure why the properties aren't populated even though the assignedNodes are. That could be a browser timing issue with the slotchanged event timing or possibly an issue with our directive's implementation or timing. It certainly seems that if the assignedNodes is populated then the property should be. I'll try to look into this.

**Comment by KingOfTac** [comment]
I did a little digging and I think it is definitely a timing issue somewhere. When the slotted behaviors get bound, `SlottedBehavior.target` is assigned to the correct slot element, but `SlottedBehavior.getNodes` returns an empty array. So at some point between the behaviors binding and `$fastController.onConnectedCallback` finishing the slot's assigned nodes become available, but I have not been able to determine at what point the assigned nodes become available.

**Comment by EisenbergEffect** [comment]
Are the slotted nodes created by a repeater by any chance?

**Comment by KingOfTac** [comment]
No

**Comment by EisenbergEffect** [comment]
Hmm. Well, one theory out the window 🤣  I'll try to spin up a repro and take a look at what's happening at runtime. It seems like we should be able to make this better...

**Comment by EisenbergEffect** [comment]
FYI I think changing the bind vs. append ordering could have perf implications. I'm a bit nervous about making that change.

**Comment by KingOfTac** [comment]
Understandable. I am wondering however, if the browser waits to make the assigned nodes available until after the document fragment is inserted into the DOM. I also don't know enough about how this is implemented at the browser level, so I think this concludes my investigation into this. 

I will move forward with using `ref` on the slots and getting the nodes manually for the time being until a solution is found.

**Comment by EisenbergEffect** [comment]
Thanks for helping to investigate. I've got this one assigned and triaged so hopefully will get some time soon to look a bit further. I'll report back if I discover anything we can do to improve this (without breaking stuff).

**Comment by EisenbergEffect** [comment]
Just coming back to this. I haven't forgotten it. Reading back over this and thinking through it a bit. Maybe we can do something for FASTElement 2.0. For example, could we have a way to run the SlottedBehavior after the append? It seems like that's the real problem. We don't want everything to work that way, just this one, since the browser doesn't know to assign any nodes until the append operation. I'm going to add this to our 2.0 milestone and see if I can find a way to solve this.

**Comment by KingOfTac** [comment]
I think in hindsight using @observable and a separate init function for popper would have been the best approach, even though coordinating multiple observables is always tricky. I think the use case now may be a bit niche, and the best approach may be to adjust the docs to make note of the slottedNodes availability. That being said if the change could be made without a hit in performance, it may only expand the use cases for Slotted.

For context, this issue was created because I was trying to make a popup container, but I ended up rewriting the component a few months ago using the openui research for guidance and Tooltip's use of AnchoredRegion for reference, which now works a lot better than the popper.js implementation.

**Comment by EisenbergEffect** [comment]
Sounds good. I'll update the docs now and then we can consider whether there's an improvement we can make that doesn't degrade perf in FE 2.

**Comment by KingOfTac** [comment]
One thing this issue brings to mind though that could be a useful improvement, is if you could somehow configure observable to group a few `Ref`s or `Slotted`s together and call a propertyChanged handler when all the properties are available. Something like this may make coordinating element references a bit easier.

**Comment by EisenbergEffect** [comment]
I think we could do that on a per object basis. There's a way to observe an object and get notified once for any property that changes on that object. So, we could look at detecting a special method and enabling this on web components.

**Comment by EisenbergEffect** [comment]
Actually, it's a bit trickier than I was thinking at first. But, we can still look into that.

**Comment by KingOfTac** [comment]
Using `@observable` decorator poses another challenge since you can't decorate multiple properties at the same time.

I'm going to go ahead and make another feature ticket for this, since it doesn't relate to this issue.

**Comment by KingOfTac** [comment]
Closing since docs have been updated and other items discussed here have been moved to new feature requests.
#5450 
#5463
