### ISSUE TITLE
Add a fast-design-system-provider in the component explorer for each component

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4307]
# Description

The components which rely on the `<fast-design-system-provider>` do not see the design system's values change in the Monaco Editor preview. This change should expose the values being used on the design system provider to give an accurate code snippet to copy and paste. It should also be made available as a switch between editing that component and the wrapping design system provider so that a user can toggle between editing the design system and the component via UI.

## Requirements

- Add the `<fast-design-system-provider>` as a wrapper to each component
- Add a switch to toggle between the design system editing and component editing
- Remove the wrapper from the internal page in `fast-component-explorer` as this will now  be taken care of by the new wrapper

**Note**: Relies on #3974 for usability

**Comment by janechu** [comment]
Relies on #3947 for usability

**Comment by EisenbergEffect** [comment]
@janechu In light of recent changes I think we should either close this or "re-imagine" it based on the component and tooling updates. I'll let you figure out how you want to handle that.

**Comment by janechu** [comment]
I'll close this for now and when we have time we can "re-imagine" how the user will want the code to be copy pasted from the monaco editor. At present we only show the HTML, I would have to create a JS or TypeScript pane with another monaco editor to accommodate the new system.
