### ISSUE TITLE
docs: guidance on application scenarios

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#4312]
Documentation of new capabilities targeted at larger experiences such as DI and routing. Guidance on building larger experiences.

**Comment by janechu** [comment]
A precursor to this would be creating a documentation site for the `@microsoft/fast-router`.

**Comment by janechu** [comment]
I'm going to close this for now since this is a *very* future goal which includes updates to `@microsoft/fast-router` which is still in prerelease.
