### ISSUE TITLE
Increment @microsoft/fast-element major version to 1

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4321]
**Describe the bug; what happened?**
Right now, `@microsoft/fast-element` is major version 0. This is an issue because when a package has major version 0, `npm` treats the *minor* version as the major version when determining if a package dependency can be de-duped. For example, installing *only* `@fluentui/web-components@0.11.0` results in the following dependency graph for `@microsoft/fast-element`:

![image](https://user-images.githubusercontent.com/3213292/106702531-5c6f4900-659d-11eb-8d71-caa2047b2798.png)

`@fluentui/web-components@0.11.0` depends on `^@microsoft/fast-element@0.21.1`. It also depends on `@microsoft/fast-foundation`, which depends on `@microsoft/fast-element@^0.22.0`. This leads to two versions of `@microsoft/fast-element` being installed, which can cause major issues relating to element definitions not being found and new features not existing, for example https://github.com/microsoft/fluentui/issues/16734.

[npm iteslf](https://docs.npmjs.com/about-semantic-versioning) recommends production packages starting at version 1.0.0, so it might be time to increment this.

**Comment by chrisdholt** [comment]
Yes, let’s do it!

**Comment by nicholasrice** [comment]
Incremented in this commit: https://github.com/microsoft/fast/commit/2b465891734bca8b4a5cbfbc167bc7518ce5fd3f
