### ISSUE TITLE
Syntax Error and unexpected token in Data Grid on Staging.

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4325]
**Describe the bug; what happened?**
When viewing the Data Grid on https://stage.www.fast.design/docs/components/data-grid/ you'll notice the code sample example is not loading and instead reveals an error.

**What are the steps to reproduce the issue?**
Visit the link described above.

**What behavior did you expect?**
No syntax errors in documentation

**If applicable, provide screenshots:**
![Screen Shot 2021-02-03 at 1 08 50 PM](https://user-images.githubusercontent.com/16669785/106803102-0e9c2480-6621-11eb-8835-0432b6cb1257.png)

**In what environment did you see the issue?**

* OS & Device: [e.g. **MacOS**, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. **Microsoft Edge**, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0] **88.0.705.50**

**Is there any additional context?**

**Comment by chrisdholt** [comment]
Looks like this was closed w/ #4338
