### ISSUE TITLE
chore: want to generate monthly report from github 

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4334]
**What feature are you requesting?**
1. Monthly favorite report base on query
2. link: https://docs.github.com/en/rest/reference/activity#starring-vs-watching
3. link: https://docs.github.com/en/graphql/overview/explorer

**What would be the benefit of adding this feature?**
it will generate report monthly. right now github provide 2 weeks report

**What solution would be ideal for you?**
The ideal is to generate report base on query  monthly.

**What alternatives have you considered?**
using github Rest API and grapphQL API

**Is there any additional context for your request?**
continue automation on devOps Reporting
**Attach screenshots or images add detail to your request:**

**Comment by chrisdholt** [comment]
Closing as this has had no action for over a year
