### ISSUE TITLE
feat: add a horizontal scroll component

### ISSUE THREAD

**Issue by robarbms** [microsoft/fast#4335]
# Description

Add a carousel web component to fast-components.

## Motivation & context

A component for showing a set of scrolling inline content.
![Group 631294](https://user-images.githubusercontent.com/69695238/106941630-ef140300-66d7-11eb-8976-29541c40d270.png)

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [x] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

**Comment by chrisdholt** [comment]
Thanks @Robarms! Looking forward to digging in a bit here! 

I do think one change will need to be made with the name. Unless this maps to the W3C carousel, we'll likely want a more "utilitarian" name for this. In the past we've called it "Horizontal Scroll" but I'm open.

**Comment by SethDonohue** [comment]
Should we consider this different than the stale Carousel that is still in review but is fairly old?

**Comment by chrisdholt** [comment]
@SethDonohue see comment above: https://github.com/microsoft/fast/issues/4335#issuecomment-773536879

Yes, "Carousel" is commonly a term that design uses to describe this behavior but it conflicts with the W3C description which is typically our north star. The name will change here :)
