### ISSUE TITLE
Incorrect wording about React on the website

### ISSUE THREAD

**Issue by vkrol** [microsoft/fast#4340]
**Describe the bug; what happened?**
There is an incorrect wording about React on the website.
React 17 had already been released without the custom elements support.

**What are the steps to reproduce the issue?**
Example:
1. Go to https://www.fast.design/
2. Scroll down to the Works with existing frameworks section

**What behavior did you expect?**
Change of wording.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/153412/107063748-c9781e00-67eb-11eb-91ae-42f9fb8aa149.png)

**In what environment did you see the issue?**
N/A.

**Is there any additional context?**
No.

**Comment by chrisdholt** [comment]
Thanks @vkrol, when we initially put this out we were optimistic about support in v17. We'll look to rework that section. As a positive, you can still leverage Web Components w/ React!

**Comment by chrisdholt** [comment]
This was updated awhile ago - we are still eagerly awaiting React built-in support for custom elements. :)
