### ISSUE TITLE
Consider supporting navigation for Menu Items

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4342]
[This ARIA example](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html) sets a precedent that an element with `[role='menuitem']` can navigate the user as the primary action.

Is this something that we want to support with FAST menu item? What diligence would we need to do to validate this scenario?

Additional precedent:
https://w3c.github.io/aria-practices/examples/menubar/menubar-navigation.html

**Comment by radium-v** [comment]
We do this for `Listbox` and `Select`: any slotted element with a `[role="option"]` is considered to be part of the collection, and is treated as if it's a `ListboxOption`. It's then up to the implementer to make sure that other properties work.

**Comment by scomea** [comment]
Confirmed that anchor elements work as menu items after resolving this issue - https://github.com/microsoft/fast/pull/4656
