### ISSUE TITLE
Add title properties to the tag and attribute properties in the web component definitions

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4345]
# Description

The `title` and `description` in component definition files for attributes located in `@microsoft/fast-components` should be map better for the tooling. This means that the `title` should be as succinct as possible and the `description`, which will appear as a tooltip in the generated tooling form, should be as descriptive as possible. An example would be a checkbox's required attribute's `title` should be "Required" and it's `description` could be "The attribute indicating that a value is required".

Additionally, the `title` field should be filled in with "friendly" names for tags. If the name of a tag is "fast-checkbox", this could be "FAST: Checkbox".

The slot names should also be addressed so they are more succinct, instead of "The default slot" this should just be "Default slot".

## Requirements
- Add the `title` to both the tag, slot and attribute data structure
- Update the attribute and slot data structures `description` to provide a better tooltip

Reliant on #4344

**Comment by chrisdholt** [comment]
@janechu I think I'll break this up into a couple of PR's if that works - One for the slots and another addressing the attributes.
