### ISSUE TITLE
build tools: test steps cause redundant builds

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#4346]
These packages include `yarn build` as part of their `test` script, which creates unnecessary overhead and time-consuming workflow redundancies:
- `fast-figma-plugin-msft`
- `fast-tooling`
- `fast-tooling-react`
- `fast-animation`
- `fast-color-explorer`
- `fast-component-explorer`
- `fast-creator`
- `fast-tooling-examples`
- `fast-website`
- `site-utilities`

Projects `fast-tooling`, `fast-tooling-react` and `fast-animation` should run their test-step-build as `tsc --noEmit`, though any performance differences are trivial for these packages.

The remaining packages run full builds (usually `webpack`) in their test stages. There are a few options when it comes to addressing this:

- **Skip the test step for packages that don't have tests**: Skipping building entirely is not a viable option, since the underlying problem is that the projects without tests (the sites) are mostly all consumers of the other packages. These projects still need to be built _at some point_ to validate that straightforward build errors don't occur.
- **Add `prepare` steps to packages without tests that need to build**: This makes the most _technical_ sense since they're dependent on the builds from the workspace, but it's extremely time-consuming for everyone to sit through full production builds of all of the sites during our already very long `prepare` step.
- **Add real test steps to all packages**: This is probably the most time-consuming option, and since there's not much in terms of automated options yet, this probably isn't the right solution (playwright would work, but it would be a lot of work).
- **Specify an extended/alternative workflow**: This would work for developers so that we don't have to build everything all at once every time, and would allow for more granular control when running automated workflows.
- change lower level test to "test": "lerna run test",

**Comment by Ibrahimmaga** [comment]
I believe the work recently done by Jane on testing is sufficient for all testing on fast tooling.  Also,  all test are being done line by line. we are not skipping anything. It's time consuming, but it's better to catch the error early than doing damage control. 
I will ping Jane to see if she has something to add.

**Comment by Ibrahimmaga** [comment]
conversation to solve scripts:
- change lower level test to "test": "lerna run test",
- compare all build, test, prepare for all packages 
- make sure they are not duplicating command
- make sure developer workflow is not impacted

**Comment by awentzel** [comment]
This issue should be automatically resolved by completing the webpack upgrade.  Take no action on this PR until final implementation upgrade is complete.

**Comment by Ibrahimmaga** [comment]
After the audit, my opinion changed about this task. There are redundancies, but they are all needed.  There are some builds and tests that are being repeated for different purposes.  For example, some packages have 3 different configurations for webpack and they all need to build with 3 different scripts.  Sounds like the build is being repeated but for different purposes.

**Comment by janechu** [comment]
This should be solved with the work on #6955 as this should simplify the packages to just:
- `@microsoft/fast-element`
- `@microsoft/fast-ssr`
- `@microsoft/fast-router`
