### ISSUE TITLE
Result from fast-slider-label

### ISSUE THREAD

**Issue by pedrocardoz0** [microsoft/fast#4366]
**Describe the bug; what happened?**
The output from `fast/packages/web-components/fast-foundation/src/slider-label/`or **_https://www.fast.design/docs/components/slider-label_** is broken.

**What are the steps to reproduce the issue?**
1 - Go to _https://www.fast.design/docs/components/slider-labe_

**Comment by EisenbergEffect** [comment]
@pedrocardoz0 Are you referring to the demo in the web page itself?

**Comment by pedrocardoz0** [comment]
Yes

**Comment by eljefe223** [comment]
@pedrocardoz0 I believe this is by design. Since `slider-label` is meant to be used with `slider` the link should be

https://www.fast.design/docs/components/slider#sliderlabel
