### ISSUE TITLE
Non-destructive ElementDefinition Configuration

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4381]
This issue concerns the alpha `DesignSystem` and `FoundationElement` interfaces.

## Feature Description
To scaffold Design System features, we would like to be able to compose ElementStyles into a component definition's stylesheets during registration with the Design System. This would allow a component definition to expose very basic structural styling, with design opinion layered on top during registration, as well as arbitrary extensions to existing element definitions.

## Problem
It is not currently possible to extend the product of `FoundationElement.configuration()`, only override:

```ts
import { MyElementConfiguration } from "./my-element.ts";

new DesginSystem().register(MyElementConfiguration({styles: css`` /* This overrides (not extends) the existing styles */ }))
```

## Proposed Solution
There are a few options on how we could address this:

**1. Change the behavior We could change the behavior to merge styles instead of override the property. This would prevent removal of styles though, which is perhaps not what we want.**

**2. Expose an `addStyles()` method on the returned configuration function**
```ts
const myConfiguration = FoundationElement.configure({/* ... */});

myConfiguration.addStyles(myAddativeElementStyles);

new DesignSystem().register(myConfiguration());
```

**3. Expose a more general `compose()` method This would work a lot like the above, but would implement a sophisticated deep merge of the provided argument with the definition:**

```ts
const myConfiguration = FoundationElement.configure({/* ... */}, styles: css`` );

myConfiguration.compose({styles: myOtherStyles}); // -> Converts the `styles` property to an array including both stylesheets.

new DesignSystem().register(myConfiguration());
```

The benefit of this is that object-options like `elementOptions`, `attributes`, and `shadowOptions `could be additively configured.

My preference would be to go with option 3 (or something similar) because it provides the most flexibility for app authors. Thoughts?

**Comment by nicholasrice** [comment]
Revisiting this now that #4390 has gone in.

The complication for this feature comes primarily from the `styles` data and potentially the `attributes` data. In practice I don't think the `attributes` data will be edited often, but it does manifest as an array like styles.

To add and remove data from the definition's `styles` property, we need to expose some mechanism to *concat* and *filter* the styles. We cannot simply expose the original definition object and require authors to mutate that data into a new definition because #4390 introduces a function type that can be assigned to `styles` that lazily defines the styles. As a library we can help handle this case ergonomically with *some* API that augments an existing definition. There are a two primary API models I see that we can use to allow mutations of definitions are:

**Static methods returning new definitions**
```ts
let def = FoundationElement.compose({ /* ... */};
def = FoundationElement.concatStyles(css``);
def = FoundationElement.filterStyles(style => someBoolTest(style));
```

**Mutating method on the definition itself**
```ts
const def = FoundationElement.compose({/* ... *.});
def.concatStyle(css``);
def.fitlerStyles(style => someBoolTest(style))
```

A challenge in *removing* stylesheets is how would an app author know which stylesheet they want to remove? Testing a sheet will involve some comparison, and an app author might not have a reference to the sheet they want to remove. To aid this case, I'd propose adding a `name` field to `ElementStyles` that can be set and used during filtering. It would be up to component libraries to create meaningful names and style taxonomies.

```ts
const styles = css`/* */`.withName("button-fill")
```

**Comment by janechu** [comment]
Both the `DesignSystem` and `FoundationElement` are part of packages either deprecated, or in the process of being deprecated.
