### ISSUE TITLE
Add the design system to the Creator

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4410]
# Background

The `<fast-design-system-provider>` web component is currently wrapping the entire `<Viewer />` component in the Creator site, however this is not represented in the sites UI. To illustrate the changes that can be made to the design system that affect the components the provider is wrapping, this should be exposed in the `<Form />`.

Reliant on the completion of #4409

## Requirements

- Create a tabbed interface in the right panel showing two tabs "Page" for the current items on the page (the default and current contents of the right panel), "Global Design System" for the attributes of the `<fast-design-system-provider>`.
- The design system should be present as a named key "design-system" in the data dictionary
- When switching between "Page" and "Global Design System" tabs, use the `MessageSystem` to post a message, when changing to the "Global Design System" tab it should look like this:

```
fastMessageSystem.postMessage({
    type: MessageSystemType.navigation,
    action: MessageSystemNavigationTypeAction.update,
    activeNavigationConfigId: "",
    activeDictionaryId: "design-system"
});
```

Changing from the "GlobalDesignSystem" to "Page" tab should have a `postMessage` that looks like this:

```
fastMessageSystem.postMessage({
    type: MessageSystemType.navigation,
    action: MessageSystemNavigationTypeAction.update,
    activeNavigationConfigId: "",
    activeDictionaryId: this.state.activeDictionaryId
});
```

- In order to preserve the last component location, the `handleMessageSystem` method should check for `MessageSystemType.navigation` as the `type` and the `MessageSystemNavigationTypeAction.update` as the `action` and use `setState` to update the `activeDictionaryId`

**Comment by janechu** [comment]
Doing a further investigation as it looks like the mapping between the monaco editor and the data dictionary causes any additional values to be over-written.

**Comment by williamw2** [comment]
Ignore the above "merged" mention. I put the wrong issue number into the pull request.
