### ISSUE TITLE
A separator is not added to Breadcrumb item when new one is appended to the list. fast-foundation > Breadcrumb.ts

### ISSUE THREAD

**Issue by yeraycaballero** [microsoft/fast#4420]
**Description**

A separator is not added to Breadcrumb item when new one is appended to the list

This is something I haven't been able to reproduce it using the component explorer editor, so I added a runnable example in stackblitz instead. https://stackblitz.com/edit/fast-design-breadcrumb?file=src/app.ts

This example renders a breadcrumb with three items. 
There is a button, which will add a new item when clicked. That new item will be added at the end of the list, but the separator between the second last item and the last item won't be rendered

Notice that this issue doesn't happen when the component is created, but when the slotted items change.

**Steps to reproduce it**

1. Run the example in stackblitz
2. You should see a breadcrumb with three items and a button to add new items
3. click on the button
4. Notice that a new item has been added as last child but there is no separator between this new item and the pevious one

![image](https://user-images.githubusercontent.com/530305/110045330-6cb44880-7d42-11eb-8e9d-1e248b7fbfec.png)
![image](https://user-images.githubusercontent.com/530305/110045343-6f16a280-7d42-11eb-8305-7973c9d73885.png)

**Expected behaviour**

Once a new breadcrumb item is added to the list as last item. I expect to see a separator between the last previous item and the new last item.

* OS Device: MacOS
* Browser: Google Chrome
* Additional context:

BreadcrumbItem.ts: lines 24-28

On the slottedBreadcrumbItemsChanged callback there is code to remove the separator of the last breadcrumb item,
but there is not logic to add the separator when there is a new last item

**Comment by chrisdholt** [comment]
@khamudom can you take a look at this?
