### ISSUE TITLE
Add a way to filter only visual elements

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#4446]
**What feature are you requesting?**
Ran into some issues using `children` and `slotted` with `filter: elements()` returns `<style/>` and `<script/>` tags. This makes sense but would be nice if we had something we could pass an argument to `elements()` to effectively do:

```
<slot ${slotted({ property: "items", filter: (node: Node):boolean => node instanceof HTMLElement && node.offsetParent !== null })}></slot>
```

**What would be the benefit of adding this feature?**
Easily filter out none visual elements like `<script/>` and `<style/>`

**Comment by EisenbergEffect** [comment]
Happy to take a PR to the `elements` filter to make this the default behavior.

**Comment by eljefe223** [comment]
Use case has not come up again. Closing for now.
