### ISSUE TITLE
FASTButton content font size uses default user-agent style

### ISSUE THREAD

**Issue by tlmii** [microsoft/fast#4450]
**Describe the bug; what happened?**

The `<fast-button>` component's internal `<button>` element seems to use the default user-agent's stylesheet for font size rather than picking up on `--type-ramp-base-font-size` or something else configured in the DSP.

**What are the steps to reproduce the issue?**

1. Go to https://stackblitz.com/edit/typescript-vfnesb?file=index.ts
2. Notice that the font size for the button is MUCH smaller than the font size for the checkbox. The FASTDesignSystemProvider has --type-ramp-base-font-size set to 52px in the example. The Checkbox uses that - the button does not. 
3. Note also that the `<button>` is not picking up the custom stylesheet's `button` rule either (the way the regular button above it does). 

**What behavior did you expect?**

I expected the font size of the button to match something on the type ramp or DSP.

**In what environment did you see the issue?**

I'm seeing it in Chromium Edge, running both in our application (embedded in an ASP.NET app) and in the above stackblitz. Both are using the latest version of @microsoft/fast-components

**Is there any additional context?**

It looks like maybe this is related to there being no styling for the `content` class/part? But I'm not 100% sure.

**Comment by EisenbergEffect** [comment]
Perhaps @bheston can comment on whether this is by design or not. If it is, we may want to expand our documentation around the type ramp.

**Comment by chrisdholt** [comment]
@eisenbergeffect, I requested this from @tlmii - definitely a bug. We had similar issues previously with font-family as the UA tends to use `font` which can create issues w/ specificity.
