### ISSUE TITLE
Syntax Error on tabbable: while binding DesignSystemProvider to template.

### ISSUE THREAD

**Issue by sridharkrishna** [microsoft/fast#4463]
While binding FASTDesignSystemProvider or custom DesignSystemProvider to the template, causing a Syntax Error on dialog.js.

Created an application using VanillaJS
------------------------------------------

```
import { FASTElement, html, css } from '@microsoft/fast-element';
import { FASTDesignSystemProvider } from '@microsoft/fast-components';
import { BasicLayout } from './basic-layout';

FASTDesignSystemProvider;

const template = html`
  <fast-design-system-provider use-defaults>
    <basic-layout></basic-layout>
  </fast-design-system-provider>
`;
const styles = css`
  display: block;
`;

export class MyElement extends FASTElement {
  static definition = {
    name: 'My-Element',
    template,
    styles,
    attributes: [ ],
  };

}

FASTElement.define(MyElement);

```

Custom Design Provider Syntax:
-----------------------------------

```
import { FASTElement, css } from '@microsoft/fast-element';
import {
  DesignSystemProvider,
  DesignSystemProviderTemplate as template,
} from '@microsoft/fast-foundation';

export class MyDesignSystemProvider extends DesignSystemProvider {
  static definition = {
    name: "my-design-system-provider",
    template,
    styles: css`
    :host {display: block}
  `,
  }
};

FASTElement.define(MyDesignSystemProvider );

```

Fast versions used:

    "@microsoft/fast-components": "^1.18.1",
    "@microsoft/fast-element": "^1.0.0",
    "@microsoft/fast-foundation": "^1.15.1",

![image](https://user-images.githubusercontent.com/2061018/111067358-e1794680-84e9-11eb-9e0a-d9eeb340d45a.png)

**Comment by EisenbergEffect** [comment]
FAST doesn't have many dependencies but the tabbable library is one of them (the other is lodash). Based on the error, it seems that there could be an issue either with the transpiler/bundler you are using or perhaps something has changed in the way tabbable exports its functionality.

@chrisdholt has more knowledge in this area and can probably better help track down the issue.

**Comment by sridharkrishna** [comment]
FYI, I had used rollup JS for bundling purposes.

**Comment by nmetulev** [comment]
We are also running into this issue. Even though [tabbable exports an es module](https://github.com/focus-trap/tabbable/blob/master/package.json#L6), it is not picked up by rollup or other bundlers. We are also running into this with [@web/dev-server](https://www.npmjs.com/package/@web/dev-server).

I wonder if an option here is to reference the esm module directly when [importing tabbable](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/dialog/dialog.ts#L3)?

```
import tabbable from "tabbable/dist/index.esm.js";
```

**Comment by chrisdholt** [comment]
@sridharkrishna @nmetulev are these in bundles you're creating using Rollup? If so, I wonder if one approach would be to include the esm instance per the above. We generate a series of rollup bundles of all our components to be used as a straight script tag implementation and similarly, we need to export `fast-element` and `fast-foundation` specifically for the rollup bundles. An example of the rollup entry point illustrating that is here: https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/index-rollup.ts

I do think this is going to be a temporary problem. Being a library of custom elements, we're finding that tabbable works great for common and known elements but we need a more customized approach. We're about to start on a replacement for tabbable, so hopefully the issue is short lived. 

If the above doesn't work, let me know and we'll look at referencing directly and seeing if that helps.

**Comment by nmetulev** [comment]
I just noticed your dependency on `tabbable` is for version 4 which doesn't support es modules. I'm wondering if updating `tabbable` to the latest (5.1.*) will solve this issue?

> are these in bundles you're creating using Rollup? 

Yes. We are also using es modules in the browser without bundling and the browser doesn't know what to do with `tabbable` either.

I was able to get a workaround working for us by importing your bundle as you suggested. I did have to explisitly use an import from the bundle in my code so rollup doesn't tree shake it. This is what is working for us for now:

```ts
import { FluentProgressRing } from '@fluentui/web-components/dist/web-components.min';

console.log('This is a temporary workaround for using @fluentui/web-components', FluentProgressRing.name);
```

**Comment by sridharkrishna** [comment]
In our use case, the commonjs plugin helps us to get successful build files, and it's working. Still, we have issues with es modules in the browser without bundling.

```
src/app.js (2:8)
1: import { FASTElement, html, css } from '@microsoft/fast-element';
2: import  FASTDesignSystemProvider  from '@microsoft/fast-components';
           ^
3: import { BasicLayout } from './basic-layout';
Error: 'default' is not exported by node_modules/@microsoft/fast-components/dist/esm/index.js, imported by src/app.js
```

Fixed with:
```
import { FASTDesignSystemProvider } from '@microsoft/fast-components';
```

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
