### ISSUE TITLE
Add more examples to Skeleton component in Explorer

### ISSUE THREAD

**Issue by litteredwitherrors** [microsoft/fast#4465]
**What feature are you requesting?**

Additional examples for the skeleton component that showcase different ways to used them, as well as showing the shimmer effect.

**What would be the benefit of adding this feature?**

This would allow users to better understand how to use the FAST Skeleton component.

**Comment by chrisdholt** [comment]
@litteredwitherrors do you think you can come up with a couple of examples?

**Comment by litteredwitherrors** [comment]
> @litteredwitherrors do you think you can come up with a couple of examples?
Yeah, basically just need to copy what's in the Storybook. I can create a PR.

**Comment by chrisdholt** [comment]
closed by #5153
