### ISSUE TITLE
Allow `ComposableStyles` to be interpolated into an `ViewTemplate`

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4478]
A scenario brought up in the community channels is how, with injected templates, to add additional CSS for the template. The specific scenario involved the injected template being injected directly into the `repeat` directive. The author was using a `<style>` element in the template which works, but isn't performant for obvious reasons.

A thought I had was that we could leverage the binding syntax to bind a ComposableStyles instance to a ViewTemplate. Something like:

```ts
const styles = css`/* my styles */`;
const template = html`
  ${styles}
   <!-- my HTML -->
`
```
The above template could be the element's own template, or could get interpolated into a separate template:

```ts
const anotherTemplate = html`${template} <!-- more html -->`
```

In either case, the embedded ComposableStyles would get added as a stylesheet to the host element.

**Comment by janechu** [comment]
I believe this is resolved by the use of an array of styles that can be injected in `@microsoft/fast-element` v2.
