### ISSUE TITLE
Add OS specific behaviour to select component

### ISSUE THREAD

**Issue by vaudy** [microsoft/fast#4482]
**What feature are you requesting?**
On OSX a select option is only committed by pressing Space or Enter key while pressing Escape revert to the previous value.

**What would be the benefit of adding this feature?**
As a user, I would like a select to behave the same as my OS select behave

**What solution would be ideal for you?**
Reset previous value when
 - Pressing Escape
 - Clicking outside

**Is there any additional context for your request?**
The actual Fast Select behave exactly like its supposed to on Windows or Edge on OSX. However, a native select behave differently on OSX for Chrome, Firefox and Safari.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
