### ISSUE TITLE
Add "value" attribute to Select component

### ISSUE THREAD

**Issue by vaudy** [microsoft/fast#4494]
**What feature are you requesting?**
Doing proper binding in form when a model is involved

**What would be the benefit of adding this feature?**
Reloading persisted data without having to apply `selected` attribute on options when model equals option value.

**What solution would be ideal for you?**
Driving the selected option using the select "value" attribute while `null` select's the first non disabled option.

`<fast-select value="model" >...`

**What alternatives have you considered?**
Doing the option rendering with the `selected` attribute base on option value

**Attach screenshots or images add detail to your request:**

![Screen Shot 2021-03-24 at 11 10 33 AM](https://user-images.githubusercontent.com/1149156/112484124-0bcfcd00-8d50-11eb-8da5-0a2286280cee.png)

**Comment by vaudy** [comment]
Another tentative was to set select value programatically within the connectedCallback and didn't work either
`next` value was '15' but gets reseted at L96

<img width="1219" alt="Screen Shot 2021-03-25 at 3 16 43 PM" src="https://user-images.githubusercontent.com/1149156/112530737-2d937900-8d7d-11eb-9b0a-1a4147a0d2bb.png">

**Comment by radium-v** [comment]
This is the same behavior exhibited by the native HTML `select` element:

> The `value` IDL attribute, on getting, must return the value of the first `option` element in the list of options in tree order that has its selectedness set to true, if any. If there isn't one, then it must return the empty string.
>
> On setting, the `value` attribute must set the selectedness of all the `option` elements in the list of options to false, and then the first option element in the list of options, in tree order, whose value is equal to the given new value, if any, must have its selectedness set to true and its dirtiness set to true.

https://html.spec.whatwg.org/multipage/form-elements.html#dom-select-value

**Comment by vaudy** [comment]
You're right. My concern was more about driving the component with a model value. I found a workaround, thanks
