### ISSUE TITLE
window validation is failing

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4495]
**Describe the bug; what happened?**
Window validation failing since this work was completed on @microsoft/fast-component-explorer: https://github.com/microsoft/fast/pull/4457 
![image](https://user-images.githubusercontent.com/14119043/112510989-3a997380-8d4f-11eb-80c6-ef1556b5caba.png)

**What are the steps to reproduce the issue?**

Example:

1. Go to '...' Github actions
2. Click on '....' Fast-Validation
3. Scroll down to '....'windows_cross-platform_cross-browser
4. See error : testing unit tests

**What behavior did you expect?**
there should be no failure
**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/14119043/112508259-a201f400-8d4c-11eb-8423-ff7af97d8126.png)

**In what environment did you see the issue?**
Window environment
* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Is there any additional context?**

**Comment by williamw2** [comment]
These errors appear to be in untracked files that are auto-generated as part of the build process. Maybe some sort of caching problem in the test environment? Has the build process changed?

**Comment by Ibrahimmaga** [comment]
no. look at the first screenshot. it is trying to find a module in fast explorer
![image](https://user-images.githubusercontent.com/14119043/112522372-c533a000-8d5a-11eb-9d68-c52db2b82c4b.png)
 
and here the changes in fast explorer files https://github.com/microsoft/fast/pull/4457/files. Perhaps there may be a module needed that has been deleted.

**Comment by williamw2** [comment]
None of the \sites\fast-component-explorer\app\fast-components\configs\*.ts files where modified by the PR and the module files that are not found are in the /.tmp/ folder which is not tracked by GIT and are auto-generated. The /.tmp/accordion/scenario file states "// Generated file from ./build/convert-scenarios.js".
There is a "clean:tmp" and "convert:scenarios" scripts in the package.json which seems related.
I have asked Jane to investigate since I don't know how the build / test systems work.

**Comment by Ibrahimmaga** [comment]
Oh! thanks for the clarification. Let wait on Jane and see if she can come up with something

**Comment by janechu** [comment]
I've added a PR for it, seems like a very odd issue for windows to get caught up on, but hopefully this will resolve it.
