### ISSUE TITLE
Inherited font-sizes move glyph positions in fast-flipper

### ISSUE THREAD

**Issue by brookdozer** [microsoft/fast#4497]
When `<fast-flipper>` is a child of any element with a font-size, the slots inherit the parent font-size which messes up the glyph positioning. You can even see it in the docs page: https://www.fast.design/docs/components/flipper/ where it the glyph is offset due to the 15.4px font-size.

**What are the steps to reproduce the issue?**
- Go to the [example codepen](https://codepen.io/brookdurant/pen/vYgNEKa)
- Anywhere `<fast-flipper>` or `<fluent-flipper>` are children of elements that have a font-size and don't have a font-size explicitly set on themselves

**What behavior did you expect?**

I would expect default flipper behavior to be **either**: 
- the flipper to be unaffected by parent `font-size` (preferable)
- the entire flipper and its children to resize based on inherited `font-size`

**If applicable, provide screenshots:**
![flipperError](https://user-images.githubusercontent.com/20569231/112534259-15fdc580-8d68-11eb-8282-49f84424f205.png)

**Is there any additional context?**
I think the flipper behavior is different that the button behavior. Should they be consistent?

One option for fix could be setting `font-size: 0;` on the flipper by default.

**Comment by brookdozer** [comment]
Bringing over comments from the PR to track them here in the bug.

 @scomea said: 
> Wouldn't it be weird if someone adds content to a slot and we apply font size 0? Can we specify the height of something instead?
 @chrisdholt said: 
> This is a good call out if someone wanted to pass localized text. What if we applied the font size to slotted SVG’s?
> 
> ::slotted(SVG) {
> font-size: 0;
> line-height: 0;
> }

**Comment by brookdozer** [comment]
::slotted(svg) doesn't work because `previous` and `next` parts are spans that inherit the parent font-size and the slotted content is in those parts.

**Comment by radium-v** [comment]
Since `previous` and `next` are spans, adding a `display` of `flex`, `inline-flex`, `grid`, or `inline-grid`, to `.next, .previous` fixes this.

Alternatively, giving the `svg` in the `previous` slot a `display` of any non-`inline` type will work as well.
