### ISSUE TITLE
Replace the NavigationMenu component with fast-components tree view

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4501]
# Abstract

The `<NavigationMenu />` used in the Component Explorer site should be replaced with `<fast-tree-view>` from the `@microsoft/fast-components` package. This should help unify the "look and feel" of the Component Explorer site which already uses several `@microsoft/fast-components`.

## Requirements

Replace the `<NavigationMenu />` in `sites/fast-component-explorer/app/explorer.tsx` with `<fast-tree-view>` and `<fast-tree-item>` components (as necessary).

This should still perform all the current functionality of showing which tree item is active as well as updating routes when clicked.

**Comment by EisenbergEffect** [comment]
@janechu Should we move this issue to one of the new repos?

**Comment by janechu** [comment]
@EisenbergEffect no need, this was for the Component Explorer but based on the new direction we will be going with that site, this is no longer needed.
