### ISSUE TITLE
FAST component observable doesn't work in create-react-app (Typescript)

### ISSUE THREAD

**Issue by anjulgarg** [microsoft/fast#4503]
**Unable to make an observable re-render the template inside a typescript react app.**
(This might be a dumb question OR I might be missing something since I am fairly new to web components.)

"react": "^17.0.2"
"@microsoft/fast-components": "^1.19.1"
"@microsoft/fast-element": "^1.0.1"

**Steps to Reproduce**
```typescript
import React from 'react';
import './App.css';
import { FastCounter } from './FastCounter';

FastCounter;

function App() {
  return (
    <div className="App">
      <fast-counter />
    </div>
  );
}

export default App;
```

```typescript
import { customElement, FASTElement, html, observable } from '@microsoft/fast-element';

const template = html<FastCounter>`
  <h1>${x => x.counter}</h1>
  <button @click=${x => x.upCount()}>Increase Count</button>
`;

@customElement({name: 'fast-counter', template})
export class FastCounter extends FASTElement {
  @observable counter = 0;

  upCount() {
    console.log('Counter was called');
    this.counter += 1;
    console.log('New count is', this.counter);
  }
}
```
<img width="1080" alt="Screen Shot 2021-03-25 at 10 09 26 PM" src="https://user-images.githubusercontent.com/9782747/112585313-ceeaf100-8db6-11eb-8c4e-a8b9bdf6b7cc.png">

Clicking the Button should ideally increase the value from 0 to 1 and so on.

* OS & Device: MacOS
* Browser Google Chrome

**Comment by EisenbergEffect** [comment]
This is extremely odd. Can you share your project by any chance?

**Comment by anjulgarg** [comment]
Don't really have a project I can share. But I tried it multiple times and was able to replicate the issue every time.

**Comment by nicholasrice** [comment]
@anjulgarg is this using create-react-app? There are known integration issues with that package and property decorators.

**Comment by anjulgarg** [comment]
Yes. I used the guide here.

**Comment by anjulgarg** [comment]
Thanks for that info @nicholasrice 
I will try setting react from scratch, and see if the issue goes away.

**Comment by anjulgarg** [comment]
@nicholasrice I can confirm that decorators work when I created a react typescript from scratch and setup a custom webpack configuration. 
It would be great if we can have this explicitly mentioned in FAST docs. :)

**Comment by EisenbergEffect** [comment]
Turned into a docs request and assigned to @nicholasrice

**Comment by ashwinGokhale** [comment]
I'm also having the same issue 😢. Is there any way to make it work with Babel + Typescript?

**Comment by ashwinGokhale** [comment]
To give some more info, with legacy Babel decorators, the code compiles fine, but the decorators don't work because of how they are compiled as stated above ^:

```json
"plugins": [
        "babel-plugin-transform-typescript-metadata",
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true }]
    ]
```

When enabling the `decoratorsBeforeExport` option, the code compiles, but at runtime it throws an error:
```json
"plugins": [
        "babel-plugin-transform-typescript-metadata",
        ["@babel/plugin-proposal-decorators", { "legacy": false, "decoratorsBeforeExport": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true}]
    ]
```


Error thrown at runtime:
```
Uncaught TypeError: An element descriptor's .kind property must be either "method" or "field", but a decorator created an element descriptor with .kind "undefined"
```

**Comment by ashwinGokhale** [comment]
Did some digging. 

These are the Babel plugins I am using:

```json
"plugins": [
        "babel-plugin-transform-typescript-metadata",
        ["@babel/plugin-proposal-decorators", { "legacy": false, "decoratorsBeforeExport": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true}]
    ]
```

I think I found a bug in the way the `Observable` defines properties:
https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/src/observation/observable.ts#L148 

The way that Babel transpiles the code, the parameters will be this:
![image](https://user-images.githubusercontent.com/21692499/115824379-b0c7df00-a3bc-11eb-9b56-9422c9193a50.png)

The `target` will be a `Descriptor` and the `nameOrAccessor` will be `undefined`

The `attr` decorator on the other hand I don't know about. It is throwing a different runtime error:
![image](https://user-images.githubusercontent.com/21692499/115824921-917d8180-a3bd-11eb-8655-39a46f06de94.png)

**Comment by EisenbergEffect** [comment]
It looks like you may be using the wrong version of decorators. There is no `kind` property, for example. That was part of the second proposal. There have been 5 or 6 proposals over the years. TS uses the very first proposal and has stayed there awaiting the stabilization of the language feature (which finally looks like it's happening after many years of work). I don't know the correct configuration of the plugin, but I do know there is a way to configure it. @nicholasrice may be able to provide the specifics.

**Comment by ashwinGokhale** [comment]
I switched back to Babel legacy decorators:
```json
"plugins": [
        "babel-plugin-transform-typescript-metadata",
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true }]
    ]
```

I was able to find a workaround by creating my own `observable` decorator:

```typescript
function observable<T>(target: T, name: keyof T): any {
  const descriptor: PropertyDescriptor = {
    set: function (value: T) {
      Observable.notify(this, name);
      (this as any)[`__${name}`] = value;
    },
    get: function () {
      Observable.track(this, name as string);
      return (this as any)[`__${name}`];
    },
    enumerable: true,
    configurable: true
  };

  return descriptor;
}
```

**Comment by ashwinGokhale** [comment]
Also possibly related, the `attr` decorator does not trigger rerenders when an attribute changes, but using the `attributes` array in the `customElement` decorator instead does work. @nicholasrice @EisenbergEffect Since I was able to get around the `observable` decorator issue, I feel like this might be a bug related to the implementation of the decorators.

**Comment by EisenbergEffect** [comment]
@nicholasrice Can you take a few minutes this week to confirm that we've got this resolved with the appropriate update in our documentation? I'd like to close this out if the work's done or if not get a solution in place.

**Comment by nicholasrice** [comment]
We did, though I'm going to update it to reference this issue for future reference.
