### ISSUE TITLE
Docs: Provide guidance on Content Security Policy rules

### ISSUE THREAD

**Issue by Garbee** [microsoft/fast#4510]
Content Security Policy is an important part of web apps being more secure in deployment. Fast should provide a documentation page providing known limitations and guidance for how to avoid CSP issues in restricted environments. It does not need to be all inclusive to start. Just a few of the current known things with examples. The resource is expected to grow as more things are tested and discovered by the community and engineering team.

### Examples

A known limitation is the `:focus-visible` CSS support check needing a nonce to work if `unsafe-inline` is not allowed.

Guidance for components can be if `style-src 'self'` is enforced then the `style` attribute in templates can't be used. Developers will need to use JavaScript to directly update elements through their style property.

**Comment by Garbee** [comment]
Initial rough draft is available for review/commenting. I have a feeling this is a bit out from being decent enough for inclusion. Solid start though.

Reference: https://hackmd.io/@Garbee/Hk8qLm-Su

**Comment by awentzel** [comment]
@garbee this is a great idea.  Any chance, you want to contribute a docs update for this, probably beneath a Security section?    We're also using Docusaurus.

For reference, here's a configuration in use today:
```
// Manage CSP Policy for Creator Application only
if (process.env.WEBSITE_HOSTNAME.indexOf("create") > -1) {
    app.use(
        helmet.contentSecurityPolicy({
            directives: {
                defaultSrc: ["'self'"],
                fontSrc: ["'self' use.typekit.net static.fast.design c.s-microsoft.com"],
                frameAncestors: [`'self' ${process.env.FRAME_ANCESTOR_PARTNER}`],
                imgSrc: ["'self' data: *.fast.design via.placeholder.com"],
                scriptSrc: ["'self' 'unsafe-eval'"],
                styleSrc: ["'self' https: 'unsafe-inline'"],
            },
        })
    );
}```

If you have more insight or ideas on security let us know.

**Comment by awentzel** [comment]
If we can get a few eyes on your changes as published at https://hackmd.io/@Garbee/Hk8qLm-Su if this documentation looks good I can push a PR with these Docusaurus changes.   @EisenbergEffect @nicholasrice are you able to take a look?

**Comment by nicholasrice** [comment]
FAST's known violations are  currently more systemic than :focus-visible. `@microsoft/fast-element` will use an HTMLStyleElement implementation to compose custom elements with stylesheets in browsers where constructible stylesheets are not supported (FF, Safari). There is currently no mechanism to provide a nonce to these elements. This means restrictive style CSPs will block all custom element styling.

**Comment by EisenbergEffect** [comment]
@nicholasrice I think I remember you having some thoughts on how to address that. Do you still think that's something we can add a feature to address? Would it be breaking?

**Comment by nicholasrice** [comment]
I more just verified it was an issue when investigating a solution for https://github.com/microsoft/fast/issues/5125.

I don't claim to be a CSP expert, but the way this works in JSS is the script creating the HTMLStyleElement looks for a 
`<meta property="csp-nonce" content="{server-provided-nonce}" />` It then reflects that attribute value as a attribute to all HTMLStyleElement's it creates: `<style nonce="{server-provided-nonce}">`.  [cssinjs docs on this](https://cssinjs.org/csp/?v=v10.8.0).

Presuming this is an acceptable approach, we could introduce an API into fast-element to create style elements, applying the nonce if it exists.

**Comment by EisenbergEffect** [comment]
Sounds good. I tagged this issue for the 2.0 milestone. Maybe we should do this as part of a broader security pass. I was planning to adjust how the trusted HTML stuff worked too.

**Comment by nicholasrice** [comment]
We'll want to look at anywhere we add inline styles as well, as doing so can be illegal under some CSP configurations.

**Comment by nicholasrice** [comment]
Another approach would be to require authors to configure fast-element with the nonce through some JavaScript API. This might be more tedious for authors as they would need to figure how to get the nonce into their script, but it does provide a bit more implementation flexibility.

**Comment by EisenbergEffect** [comment]
@nicholasrice Do we have an issue tracking the style stuff? If not, can we create one and assign to the FE 2 milestone?

**Comment by EisenbergEffect** [comment]
@Garbee  Are you still interested in contributing to our docs on this topic?

**Comment by nicholasrice** [comment]
@EisenbergEffect I don't believe so - I'll add one.

**Comment by Garbee** [comment]
Sorry, haven't been on GH much since switching jobs.

No, not interested in getting it over the line. Feel free to use what I put up hackmd if you'd like.

New job is not using Fast, we're going with another thing for our needs to hep with Web Components. So it's no longer a work thing unfortunately. :/

**Comment by EisenbergEffect** [comment]
Thanks for the update @Garbee

**Comment by janechu** [comment]
This appears to be a duplicate of #5444 which is more up-to-date on what the solution could be for this issue.
