### ISSUE TITLE
When a value for FASTSlider is updated the thumb position does not move to the corresponding location

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4537]
**Describe the bug; what happened?**

After implementing the `<fast-slider>` there was a requirement to update the `value` attribute from a secondary source. When this is implemented, although the value can be implemented from the `<fast-slider>` when updating it from another source it will not show the correct position of the thumb.

**What are the steps to reproduce the issue?**

Example:

1. Implement `<fast-slider>`
2. Add an `<input />`
3. Use the `input` change event to set the `value` on `<fast-slider>`
4. See the thumb position not update

**What behavior did you expect?**

I expect the thumb position of the `<fast-slider>` to update.

**Comment by robarbms** [comment]
I created an example using an input field that updates the slider value when the input fields value changes. It is working as expected. I suspect that John had fixed this.
