### ISSUE TITLE
Add CI/CD pipeline for publishing FAST Nugget packages

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4540]
This pipeline will publish FAST Web Components for use on .NET Blazor ecosystems.

~~1. Enable manual GH Action to publish
2. Major/Minor will likely match FAST
3. Patch could be more C# related 
4. .NET repository that will facilitate this work https://github.com/dotnet/blazor-fluentui
5. Need an account and permissions to use Nuget.
6. Publish for [Nuget](https://www.nuget.org/)
7. Additional notes on [goals](https://github.com/dotnet/blazor-fluentui/blob/main/docs/investigation.md)~~

**Project properties:** 

Package id: Microsoft.Fast.Components.FluentUI 

Package version: 0.0.2 

Authors and company: Microsoft 

Product = FAST Blazor 

Description(reference to people what will be searching for) 

Licensing: MIT 

Repository url: https://github.com/dotnet/blazor-fluentui 

Tag: Latest 

Icon: we can provide fast Icon or url 

Release note: @fast microsoft components

**Comment by awentzel** [comment]
Blocked until Thursday April 22, when contact returns to office to give permissions for .net foundation.

**Comment by awentzel** [comment]
Started working through email to get information on permissions.

**Comment by Ibrahimmaga** [comment]
I saw a notification for package id: and project name that need to be updated. It should be in this issue right? I can't find it anymore

**Comment by Ibrahimmaga** [comment]
nevermind found it

**Comment by awentzel** [comment]
Now publishing to https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI/
