### ISSUE TITLE
fast-select tabindex="0" forced - Bug?

### ISSUE THREAD

**Issue by ScottKane** [microsoft/fast#4551]
I have started using fast on a larger scale application where accessibility is a bigger concern, I was putting together a form and noticed that all fast-selects get tabindex="0" but it's not even just by default, you can't override it at all. Is this a bug?

**Comment by chrisdholt** [comment]
@ScottKane, I'm digging into this a bit and wanted to understand more the impact of this on accessibility? Without digging into the PR's and prior code reviews, my base assumption here is that since this is a single-select combobox built to meet ARIA 1.2 requirements (rather than serving the native select, or delegating focus to an internal focusable element) we default the element to be focusable when it's enabled. In the event the control is disabled using the disabled attribute, no tabindex is included and the control is kept out of the tab order.

I *do* think that we can consider whether or not we should default to a provided tabindex if it's given, but that could cause some significant issues with regard to the component and it's accessibility as well.

**Comment by ScottKane** [comment]
This was based on an issue I had been having with a form. A select box was used half way down the form and was being set to tabindex 0. As a result, a user navigating the form with a keyboard would start navigation half way down the form. Even manually ordering the tabindex for each element resulted in the select still having tabindex 0 in the DOM.

**Comment by chrisdholt** [comment]
Ah - gotcha, are you manually setting tabindex for all form elements in numerical/sequential order?

**Comment by ScottKane** [comment]
Yes I had sequentially ordered the elements setting the select to say tabindex 5, all other elements respected the ordering but the select was overridden with 0 and was the navigation root for the form half way down

**Comment by chrisdholt** [comment]
> Yes I had sequentially ordered the elements setting the select to say tabindex 5, all other elements respected the ordering but the select was overridden with 0 and was the navigation root for the form half way down

This is helpful context. I think there's probably a point of discussion to be had here in terms of what/how we support things. On one hand, we typically want to respect properties being applied from outside the component. On the other hand, the setting of tabindex to a number greater than 0 is considered to be an anti-pattern.

As mentioned above we need to be able to set tabindex to 0 to ensure the control as a custom element receives focus. If we enable support for users to pass custom tabindex values, we open up the opportunity for them to set the value to a negative number as well which could have unknown implications. I'm open to the possibility, but I think we need to look at the implications of enabling this type of functionality for elements which need to receive focus by way of tabindex.

**Comment by chrisdholt** [comment]
> > Yes I had sequentially ordered the elements setting the select to say tabindex 5, all other elements respected the ordering but the select was overridden with 0 and was the navigation root for the form half way down
> 
> This is helpful context. I think there's probably a point of discussion to be had here in terms of what/how we support things. On one hand, we typically want to respect properties being applied from outside the component. On the other hand, the setting of tabindex to a number greater than 0 is considered to be an anti-pattern.
> 
> As mentioned above we need to be able to set tabindex to 0 to ensure the control as a custom element receives focus. If we enable support for users to pass custom tabindex values, we open up the opportunity for them to set the value to a negative number as well which could have unknown implications. I'm open to the possibility, but I think we need to look at the implications of enabling this type of functionality for elements which need to receive focus by way of tabindex.

Closing based on this comment and the fact that sequential tab ordering is not recommended as standard practice or pattern (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)
