### ISSUE TITLE
rfc: follow up on beachball publish

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4556]
# 💬 RFC

beachball publish failed due to access restriction
## 🔦 Context
![image](https://user-images.githubusercontent.com/14119043/113899223-6ff78580-9781-11eb-8661-7d28564bef50.png)

1. try to use --access public command and verify our credentials
2. have Chris use his credential
3. contact Ken from beachball team
4. research npm publish for organization
     Organizations allow teams of contributors to read, write, and public and private packages. Organizations are free when they 
     publish public packages. When organizations publish private packages, an npm Teams subscription is required. For more 
     information on npm Teams pricing, see our products page.
     https://docs.npmjs.com/adding-members-to-your-organization 
     https://docs.npmjs.com/cli/v7/using-npm/scope
5. binary path require configuration
    we will use "scripts-prepend-node-path=true" in .npmrc folder and it will solve the problem
6. npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@microsoft%2ffast-foundation - Not found
    The PUT is use to insert into an API.  Here when publish is writing to npm, it need to have a permission. We need to provide 
     npm token with write access.
     .npmrc and write //registry.npmjs.org/:_authToken=${NPM_TOKEN} into it
 7. Update $NPM_PAT to make sure it has read and write access policies
 8. npm config set registry https://registry.npmjs.org/ in npmrc

**Comment by awentzel** [comment]
I'm not sure the 4th item is relevant since we're part of Microsoft organization, we shouldn't have to worry about pricing plans, and we've already registered our service account with our organization NPMjs admin.

**Comment by Ibrahimmaga** [comment]
Ken confirm that we should use --access public command  to not be restricted

**Comment by awentzel** [comment]
closed by #3889
