### ISSUE TITLE
rfc:  The total coverage in the repository is 78.7% (0.0% change) drop from 85.2%

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4579]
# 💬 RFC
Improve code coverage with code climate

## 🔦 Context
better code coverage means lower technical debt

## 💻 Examples
Code Climate has analyzed commit 6a9ead7 and detected 0 issues on this pull request.

The test coverage on the diff in this pull request is 100.0% (50% is the threshold).

This pull request will bring the total coverage in the repository to 78.7% (0.0% change).

View more on Code Climate.

**Comment by EisenbergEffect** [comment]
I don't think we need an issue for this.
