### ISSUE TITLE
feat: add `tryGet()` method to dependency-injection `Container`

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4582]
# 🙋 Feature Request

Let's add a `tryGet()` method to `Container` so that authors can try to get a DI key value that may not exist without try/catching.

## 🔦 Context
PR conversation: https://github.com/microsoft/fast/pull/4580/files/1066544db1748a8353b39c644aa73aa1f45ad076#r611828395

**Comment by janechu** [comment]
Looks like this has been resolved with #4580
