### ISSUE TITLE
fix: macs os network failure

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4586]
# 🐛 Bug Report
Trouble with network connection on mac

## 💻 Repro or Code Sample
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.3.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/fast/fast/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

## 🤔 Expected Behavior

network issue should not happened when installing dependencies 
## 💁 Possible Solution
keep running the pipe line until it passed or add yarn install --network-timeout=30000 before installing dependencies

## 🔦 Context
This solution could increase the time it takes to download dependencies on mac, but will prevent consistent failure

## 🌍 Your Environment
MacOs

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
closing as part of #4617
