### ISSUE TITLE
Accessibility: Pane Separator incorrectly reports aria-valuenow

### ISSUE THREAD

**Issue by bekell** [microsoft/fast#4594]
Pane separator component had aria-valuenow added to it here: https://github.com/microsoft/fast/issues/3231

However, there are some issues with the current implementation.

1. Using the keyboard, aria-valuenow can be set below and above aria-valuemin and aria-valuemax. To reproduce, use the keyboard arrows to move the separator to the min & max values, notice aria-valuenow goes above & below the values.
2. aria-valuenow gets removed from the element after moving the separator with the keyboard. To reproduce, use the keyboard arrows to move the separator. Observe aria-valuenow gets set. Tab away from the separator and notice aria-valuenow is no longer an attribute of the element.

@chrisdholt @scomea FYI

**Comment by chrisdholt** [comment]
Hey @Bekell - We've deprecated the package that the pane was in, so closing this as it's no longer pertinent to this repository.
