### ISSUE TITLE
rfc: prettier check should run before the build across pipelines for consistency

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4636]
# 💬 RFC

ci-daily, ci-weekly, 
## 🔦 Context
Prettier check must fail the ci process if the code formatting is not complying. 
1. some prettier checks are run before builds and some run after builds. for consistency, we want to run prettier checks before build.
2.  we also want the build to compile code when the prettier check has passed.  The other benefit, if a PR will fail on the prettier check, we want it to fail before the build so we don't spend time building then fail again.  "saving time".
3.

**Comment by awentzel** [comment]
@Ibrahimmaga  Please elaborate on the problem and the solution in detail.

**Comment by Ibrahimmaga** [comment]
In some ci/cd we have prettier check before the build. There are some workflows that are checking prettier formatting after the build. It does not causing an issue,  but if prettier will fail, then if should fail before the build. It will save time.

**Comment by awentzel** [comment]
@Ibrahimmaga please create a PR to bring consistency to the build process by moving Prettier before the build.

**Comment by chrisdholt** [comment]
> @Ibrahimmaga please create a PR to bring consistency to the build process by moving Prettier before the build.
> 
> Additionally, I've updated the title, but please update the description and example sections of this issue to fully encapsulate the problem/solution.

@awentzel Is this still an outstanding task and is it accurately represented here?

**Comment by Ibrahimmaga** [comment]
This issue was resolved by #4706
