### ISSUE TITLE
feat: add a label slot in the Select component

### ISSUE THREAD

**Issue by m4thieulavoie** [microsoft/fast#4642]
# 🙋 Feature Request

As discussed [here](https://discord.com/channels/449251231706251264/482296787021856768/835220752226975764), I would like to request a label slot in the Select component, to give the same end result than the Text Field

## 🤔 Expected Behavior

A consumer can set a label in the Select component

## 💁 Possible Solution

Add an additional slot

**Comment by chrisdholt** [comment]
To be picked up in FAST Foundation vNext (as part of FE 2)

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time, additionally `@microsoft/fast-foundation` is being deprecated per #6955.
