### ISSUE TITLE
bug: slot attributes are duplicated in component explorer sample site

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#4648]
# 🐛 Bug Report

Code samples in the component explorer site that include "slot" attributes show duplicates.  You can see the issue with the tab and tree view component code samples.

![image](https://user-images.githubusercontent.com/7649425/116430605-d8270d80-a7fb-11eb-9277-87dbe47a0e46.png)

## 💻 Repro or Code Sample

See sample html generated here:
https://explore.fast.design/components/fast-tabs

## 🤔 Expected Behavior

no duplicate "slot" attributes

## 😯 Current Behavior

duplicate "slot" attributes

**Comment by janechu** [comment]
This issue was fixed and deployed.
