### ISSUE TITLE
fix: using setCustomValidity on form elements

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4652]
# 🐛 Bug Report

On HTML form elements such as `input` and `select` there is a method that can be used [`setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#methods). This should be available for web components that are `FormAssociated` and have a proxy element that has this option.

Examples of this are:
- `fast-checkbox`
- `fast-radio`
- `fast-combobox`
- `fast-text-field`
- `fast-number-field`
- `fast-text-area`
- `fast-select`
- `fast-slider`
- `fast-switch`

## 💻 Repro or Code Sample

Create any of the above components and attempt to use `setCustomValidity("example error string")`.

## 🤔 Expected Behavior

It is expected that the custom validity will be set, so that running `reportValidity()` for example, will display a browser tooltip.

## 😯 Current Behavior

Attempting to set custom validity results in the following:

```console
Uncaught TypeError: myElement.setCustomValidity is not a function
    at <anonymous>:1:9
```

## 🔦 Context

In cases where an additional validity check that cannot be applied to the component is needed, this method must be made available. An example might be where a round trip is needed to another service to determine if a username has not been taken.

**Comment by nicholasrice** [comment]
@janchu Yea Form Associated Custom Element's don't get a "setCustomValidity" method, only a "setValidity" which has a different API. I suppose we could add a "setCustomValidity" method to `FormAssociated` mixin and just alias it to "setValidity" but I don't really see the benefit of that

**Comment by janechu** [comment]
I think we can leave it, if we see a lot of requests to include it due to the expectation of it being there we could take another look at this.
