### ISSUE TITLE
fix: favicon in main fast.design website not serving up favicon.ico for google service

### ISSUE THREAD

**Issue by marjonlynch** [microsoft/fast#4654]
# 🐛 Bug Report

When a dev uses a service like "https://www.google.com/s2/favicons?sz=32&domain=fast.design" the correct favicon should be returned. Currently it is not. This might be due to the fact we have something like the following:
`<link rel="icon" type="image/svg+xml" href="https://static.fast.design/assets/favicon.svg" sizes="any">`

just plug this "https://www.google.com/s2/favicons?sz=32&domain=fast.design" into a browser address bar, observe the favicon returned

Expect to see the proper Fast logo favicon.

The rules on this page might help:
https://en.wikipedia.org/wiki/Favicon#File_format_support

## 🌍 Your Environment

* Mac OS Catalina 10.15.7
* Microsoft Edge Canary  92.0.872.0

**Comment by janechu** [comment]
This will be solved in the FE v2 documentation site update.
