### ISSUE TITLE
Add ability to select rows and add other fast_component in cell

### ISSUE THREAD

**Issue by apsthisdev** [microsoft/fast#4658]
# 🙋 Feature Request

**data-grid should have the ability to select the row and click event so authors can react to row selection**

Use case - Most typical use-cases will involve users seeing the data and then performing some actions on them like, opening the data record (row) or editing or deleting the record.

**data-grid should have the ability to add other fast_components in the cell instead of simple text**

Use case - There are many common use cases for this:
For e.g.
-  Add an action button for each row in leading or trailing cell that will show all the supported actions on the row
- Add a check box in the leading cell of a row to select the row

**Comment by EisenbergEffect** [comment]
@scomea Can you provide some thoughts on this? If I recall, we had some or all of this implemented already. Perhaps we just need to add documentation.

**Comment by scomea** [comment]
Yes, we absolutely definitely need to up our documentation game.  But in the meantime the best demo of advanced grid features is in the fast-components storybook sample. 

![image](https://user-images.githubusercontent.com/7649425/117184885-14271900-ad8e-11eb-936c-12ed59cff963.png)

Authors can specify cellTemplates to use per column with custom column definitions which allows for advanced custom cell scenarios and should enable devs to build the scenarios described above.

One of the things that is front of mind for me regarding Data-grid next steps is what belongs in the base grid implementation vs. derived types. I can see clear paths to implementing features like row/column selection, reordering, etc... but at the same time I don't want to turn the base grid into a mini-excel.  So thinking on how best to package additional functionality.

**Comment by ameyasubhedar** [comment]
Thanks, this was helpful. So we can use any fast-component inside the cell. That's great !

**Comment by ameyasubhedar** [comment]
The documentation needs some updates though with examples.

**Comment by chrisdholt** [comment]
Looks like #5786 would close this.

**Comment by janechu** [comment]
Closing per #5786
