### ISSUE TITLE
Data grid cell value does not indent properly

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4660]
OOTB fast_data_grid cells does not indent or align properly.

Q1: How do I tell the cells to left align with each corresponding column headers ?

Q2: How do I make the data grid responsive for specific certain column ?

Here is the simple example 

![image](https://user-images.githubusercontent.com/13166236/116914678-e0b68400-abff-11eb-8994-9f7b4e0eb9d8.png)

```
<fast-card>
    <fast-data-grid grid-template-columns="sticky" generate-header>
        <fast-data-grid-row row-type="sticky-header">
            <fast-data-grid-cell cell-type="columnheader" grid-column="1">Colum Header 1</fast-data-grid-cell>
            <fast-data-grid-cell cell-type="columnheader" grid-column="2">Colum Header 2 </fast-data-grid-cell>
            <fast-data-grid-cell cell-type="columnheader" grid-column="3">Colum Header 3</fast-data-grid-cell>
        </fast-data-grid-row>
        <fast-data-grid-row row-type="default">
            <fast-data-grid-cell cell-type="default" grid-column="1">Row Long Value 1</fast-data-grid-cell>
            <fast-data-grid-cell cell-type="default" grid-column="2">Row Value 1</fast-data-grid-cell>
            <fast-data-grid-cell cell-type="default" grid-column="3">Row 1</fast-data-grid-cell>
        </fast-data-grid-row>
        <fast-data-grid-row>
            <fast-data-grid-cell cell-type="default" grid-column="1">Row Very Very Very Long Value</fast-data-grid-cell>
            <fast-data-grid-cell cell-type="default" grid-column="2">Row Long Value 2</fast-data-grid-cell>
            <fast-data-grid-cell cell-type="default" grid-column="3">Row value 3</fast-data-grid-cell>
        </fast-data-grid-row>
    </fast-data-grid>
</fast-card>
```

**Comment by ameyasubhedar** [comment]
@EisenbergEffect I looked at the src and could not find any property that would help align the cells ? Is this missing completely or a bug !

**Comment by EisenbergEffect** [comment]
@scomea Can you provide some guidance here on how to achieve the desired effect?

**Comment by scomea** [comment]
"sticky" is not a valid value for `grid-template-columns` (https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns).   Try something like "1fr 1fr 1fr" and it should work.

**Comment by scomea** [comment]
As for making the grid responsive you can customize the `grid-template-columns` attribute for your grid which should give you a great deal of control over how the columns in your grid respond to resizing, similar to what you can do with a css grid (which is what controls the layout of each row).

**Comment by ameyasubhedar** [comment]
@scomea, thanks there appears to be a bug in the fast.design website component explorer. The Grid Template Columns has a drop down to choose for and that caused the confusion.
![image](https://user-images.githubusercontent.com/13166236/117207948-69bcef00-ada9-11eb-8fda-712ef460fa52.png)

As mentioned in your comments  I am now using grid-template-columns. But there is still this issues of cell values not aligning correctly 

![image](https://user-images.githubusercontent.com/13166236/117212420-2c5b6000-adaf-11eb-9018-e4c3f30dea62.png)


```
<div>
    <fast-data-grid grid-template-columns="auto auto auto">
        <fast-data-grid-row row-type="header">
            <fast-data-grid-cell grid-column="1" cell-type="columnheader">Header 1</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="2" cell-type="columnheader">Long Header 1</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="3" cell-type="columnheader">Very Long Header 1</fast-data-grid-cell>
        </fast-data-grid-row>
        <fast-data-grid-row>
            <fast-data-grid-cell grid-column="1">Header Value 1</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="2">Tiny 1</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="3">Very Long Header Value 1</fast-data-grid-cell>
        </fast-data-grid-row>
        <fast-data-grid-row>
            <fast-data-grid-cell grid-column="1">Header Value 2 Custom</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="2">Long Header Value 2 Custom</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="3">Short custom</fast-data-grid-cell>
        </fast-data-grid-row>
    </fast-data-grid>
</div>
```

**Comment by ameyasubhedar** [comment]
I don't want to have fixed size columns, **auto or 1fr** but the cell values (non headers) each indent differently based on the adjacent cell value.

**Comment by scomea** [comment]
Oh, I'll look into the site issue, that does look like a bug.

**Comment by scomea** [comment]
For the grid columns to align correctly their width can't be based on the width of the content because each row is it's own construct, so "auto" isn't going to align unless all items in the auto column are the same width (like maybe if you are toggling between a fixed width wide cell template and a narrow one for all items in a column).  The "fr" values work because they are based on available space so layouts like "10px 1fr 1fr 2fr" that don't vary based on content width are ok.

**Comment by scomea** [comment]
Note: an author could set up a mechanism that somehow collects the "desired width" of cells in a column and uses that to set the column width to match the widest one.

**Comment by scomea** [comment]
Issue for component explorer here:
https://github.com/microsoft/fast/issues/4677

**Comment by ameyasubhedar** [comment]
yup the "fr" work correctly.... I used "2fr 1fr 1fr"  Thanks. Good to go from my side

![image](https://user-images.githubusercontent.com/13166236/117223593-d85a7680-adc2-11eb-853f-2ccb3ab26762.png)

**Comment by ameyasubhedar** [comment]
@scomea, How do I hide the horizontal grid lines in the data-grid. I could not find any property that I could set on the fast-data-grid to hide the grid line.

**Comment by scomea** [comment]
That's the "border-bottom" from data-grid-row styles - https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/data-grid/data-grid-row.styles.ts.

You could set a custom "rowItemTemplate"  on the data grid, but I expect you could style it with css as well (data grid rows render in the light dom).

**Comment by evandigby** [comment]
> For the grid columns to align correctly their width can't be based on the width of the content because each row is it's own construct, so "auto" isn't going to align unless all items in the auto column are the same width (like maybe if you are toggling between a fixed width wide cell template and a narrow one for all items in a column). The "fr" values work because they are based on available space so layouts like "10px 1fr 1fr 2fr" that don't vary based on content width are ok.

@scomea is there a way to allow the same behavior as the max-content column size in CSS grids? (e.g. https://jsfiddle.net/95rhy2m1/).

I am able to replicate it by putting all cells in a single "row"; however, that prevents me from having a header:

```html
<div>
    <fast-data-grid id="samplegrid" grid-template-columns="max-content max-content" generate-header="none">
        <fast-data-grid-row>
            <fast-data-grid-cell grid-column="1" style="border:1px solid black">1.1asdfasdfasdfasdf</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="2" style="border:1px solid black">1.2</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="1" style="border:1px solid black">2.1asdfasdfasdfasdfasdfasdfasdfasdf</fast-data-grid-cell>
            <fast-data-grid-cell grid-column="2" style="border:1px solid black">2.2asfdasdfasdfasdf.akjsdf;kjasdflkj asl;kjf;lasdkjf ;lasdkjfl;ks dj;flksadjf ;lkasdjf ;lkjsad; lfkjasd;lf kasd;lkjf ;lsdkjf; lksadjf;lkasdj </fast-data-grid-cell>
        </fast-data-grid-row>
    </fast-data-grid>
    <p></p>
    <h1>Manual grid</h1>
    <h2>Grids can also be defined with html</h2>
    <h2>Authors will need to define the 'grid-template-columns' of manual grids aswell as assign each cell to a 'grid-column'.</h2>
</div>
```

**Comment by scomea** [comment]
I expect the "all the cells in a single row" approach would also break keyboarding and confuse screen readers.  I can't think of any quick way to enable this at the component level.  If an author had a good way to measure the expected width of all the cells in particular column by iterating through the row data they could set column widths based on that.

**Comment by evandigby** [comment]
> I expect the "all the cells in a single row" approach would also break keyboarding and confuse screen readers. I can't think of any quick way to enable this at the component level. If an author had a good way to measure the expected width of all the cells in particular column by iterating through the row data they could set column widths based on that.

@scomea Ah, yes good call on the accessibility aspect. I wonder how CSS grids impact readers. CSS grids seem to be more for laying things out than tabular data, so there are a few things that make less sense (to me, at least) when using the css constructs over the fast-data-grid constructs for tabular data--even if underneath it boils down to more-or-less the same. The explicit rows being one of them.

I'm working in Blazor (using mostly http://github.com/microsoft/fast-blazor but for grid I'm using the fluent-data-grid items until the PR for DataGrid component is merged). If I come up with a way to calculate the desired widths I will come back here and post. In the meantime I'll go to using fixed sizes.

Thank you!

**Comment by EisenbergEffect** [comment]
@scomea I was doing some cleanup today and saw this issue was still open. I think the action item for this is to check the component explorer configuration for this Grid component. There seems to be an option for "sticky" that shouldn't be there (if I understand correctly). Do you have a few minutes this week to resolve this? Thanks!

**Comment by scomea** [comment]
@EisenbergEffect The Component Explorer was fixed some time ago, so this can be closed.  
![image](https://user-images.githubusercontent.com/7649425/157330910-87c1fb90-e66a-46a4-b5ae-9e831b58d2b1.png)
