### ISSUE TITLE
update automated pipelines to notify upon failure

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4674]
# 🙋 Feature Request
Notify the operations team in the case of automated pipeline failures, this way DevOps can operate proactively and immediately.

## 🤔 Expected Behavior
Upon failure, for example, and starting with cron scheduled pipeline failures, send an email to the operations team with a link to the failed GitHub Action to be reviewed immediately and proactively solved before customer impact.

## 😯 Current Behavior
Pipeline failures for any reason will prevent publishing nightly packages.

## 💁 Possible Solutions
1. Upon failure, send an email.
2. Upon failure, pop a notification on the GH landing page as a banner.
3. *Send an update to a specific DevOps channel on Discord
4. Some solution that is easily identifiable through normal communication means.

*Preference

**Comment by Ibrahimmaga** [comment]
require webhook_id: ${{ secrets.WEBHOOK_ID }}  webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
https://github.com/appleboy/discord-action

**Comment by Ibrahimmaga** [comment]
After testing the configuration with Discord Channel for notifications. I can see notifications being sent to discord. But the test is for push events, issues status, Deployment success, or failure. That is not exactly what we want. We want notifications when cron scheduled pipeline fails.  The second option will be to write a script that will send the notification to the channel.

![image](https://user-images.githubusercontent.com/14119043/118867958-7e64b100-b898-11eb-9f16-adc29d142feb.png)

**Comment by awentzel** [comment]
@Ibrahimmaga Can we trigger a notification on deployment failures ONLY of the CD (Continuous Delivery) pipelines running on master branch only?  If so, that will be sufficient to implement.

**Comment by Ibrahimmaga** [comment]
The webhooks have a built-in function that can trigger a deployment if the deployment was deployed or deleted.   After the cd-publish was triggered, there was no notification for "the deployment was deployed.".  My guess is, it will only work if we use the actions workflow template provided by Github.  Our workflows are mostly empty templates. 
Or we can observe a deployment failure to confirm for a notification on failure.

The second option is to write a script in the cd-publish itself, which can send a notification to Discord if the workflow fails.

![image](https://user-images.githubusercontent.com/14119043/118901365-ee3e6000-b8c7-11eb-975f-c534b7d28707.png)

**Comment by awentzel** [comment]
We're only interested in notifying on discord channel Publishing Failures.  So, it seems like option 2 does this for us.  Please implement @Ibrahimmaga

**Comment by Ibrahimmaga** [comment]
sounds good

**Comment by Ibrahimmaga** [comment]
PR link https://github.com/microsoft/fast/pull/4743

**Comment by EisenbergEffect** [comment]
@Ibrahimmaga Is it ok to close this as done now?

**Comment by Ibrahimmaga** [comment]
Yes we can close it. we check in with Aaron if he is satisfied with the requirement.

**Comment by awentzel** [comment]
when adding links use a verb to describe as well.  For example, "closes #4743" and then this would automatically close upon merging to master of the PR itself.
