### ISSUE TITLE
docs: data grid definition file is incomplete/incorrect

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#4677]
# 🙋 Documentation Request

The data-grid.definition.ts file is incomplete/incorrect and doesn't show the right options in component explorer.

![image](https://user-images.githubusercontent.com/7649425/117222278-efe43000-adbf-11eb-81e8-4b84d81611fc.png)

## 💁 Possible Solution
Correct/complete the definition file.

**Comment by janechu** [comment]
Closed by https://github.com/microsoft/fast/pull/4763
