### ISSUE TITLE
rfc: add codespaces to improve development lifecycle

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4683]
# 💬 RFC
Evaluate GitHub Codespaces which can help with:
> Reducing time to set up development environments from hours per week to seconds.  Consistent development experience for the whole team - no more “works on my machine” Fully integrated into the GitHub developer experience. 
sourced from GitHub

## 🔦 Context
Evaluate how this could be used for our situation?
* Implement as part of CLI for onboarding
* Implement examples for inclusion in documentation to quickly see different implementation examples.
* Other applications?

* Determine the specific functionality that Codespaces provides that can be leveraged to improve developer efficiencies, customer adoption, and collaboration sandboxing with tooling that is natively integrated into our existing platform.
* Possible replacement to for CodePen?
* How does this compare with GitHub Gist?

**Comment by chrisdholt** [comment]
This can be accessed by hitting `.` within the root or any relevant portion of the code in GH's interface. You can't run the dev server but this is default behavior by GH now I believe. Closing this as I don't think there is any actionable effort required from us.
