### ISSUE TITLE
rfc: add GitHub Discussions

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4684]
# 💬 RFC
Today, our discussions take place on Discord.  It's great that Discord is the first place we send people to communicate with us.  However, things quickly get lost each day as the conversations move on to the next thing.

What if we implemented GitHub Discussions, as a central repository, available on private and public projects, to open conversations for the community to provide feedback.  Perhaps, even this RFC could be replaced with GitHub Discussions.

## 🔦 Context
* An obvious and central location to manage and contribute to discussions may encourage the ideation process, which in turn may excite the community to become a contributor.  At a minimum, it will increase engagement and thought into new features to ensure we're building what customers and partners desire.
* Q/A could also be accomplished here, though, I'm wondering how this would compete and/or integrate with StackOverflow.  I love SO because questions/answers there will increase our reach, thus drawing in more people to our project.  Perhaps, all q/a get stored here, then we refer from S/O our answers or thoughtfully craft them on our platform instead of SO.
* StackOverflow for `fluent-ui` https://stackoverflow.com/questions/tagged/fast-ui has relatively little info.  But, as our product matures I expect this to pick up steam, and getting ahead of this will be beneficial.  For each question we don't get into a knowledge base with an answer we duplicate work effort responding and communicating today.

**Comment by chrisdholt** [comment]
It would be great to see a proposal for this request for comments. I'd love to get a more full picture of the role all of the channels would play. Discussions look great, I'd love to see a proposal for how it can enhance our project, how we can guide the community in how to leverage each, and how we can keep things manageable for folks participating in these various platforms. Do we have a clear idea of how issues differentiate between discussions or discord? I think a proposal will help us iron this out ahead of time and equip us to better support folks in various channels.

**Comment by chrisdholt** [comment]
Added - closing this out!
