### ISSUE TITLE
fix: StartEnd does not always apply the appropriate classes to the template

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4692]
# 🐛 Bug Report
In the below min-repro, `StartEnd` does not apply a `start` class to the `[part='start']` element like it is supposed to. When the `slotchange` event handler is invoked, `HTMLSlotElement.assignedNodes()` returns an empty array. It seems odd that there is a slotchange event fired but no nodes are actually assigned.

One fix would be to defer the reading of `assignedNodes()` with `DOM.queueUpdate()`, but I worry that the actual bug lies elsewhere.

## 💻 Repro or Code Sample
Min repro: https://stackblitz.com/edit/web-platform-upgzy6?file=index.html

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by nicholasrice** [comment]
This seems to me to be an issue with https://github.com/microsoft/fast/blob/master/build/transform-fragments.js.

When the web-components.js file is built, templates are run through `transformHTMLFragment()` which outputting the following:
**Note: no space char between ref and slotchange**
```ts
html`<span part="start" ${ref("startContainer")}><slot name="start" ${ref("start")}@slotchange="${x => x.handleStartContentChange()}"></slot></span>`
```
The binding (an event listener) is being created as a normal binding behavior and getting evaluated during template initialization instead of being created as a trigger binding and getting  an event listener attached to the target. Adding a space char between `${ref("start")}` and `@slotchange...` fixes the issue.

@EisenbergEffect I'm *pretty sure* this isn't a problem w/ the template compiler but if you think this is a case it should handle more gracefully let me know. Since `ref` isn't an attribute it's kind-of a grey-area in terms of whether it should require spaces around the binding.
@radium-v Would it be easy to update `transformHTMLFragment()` to handle this case?

**Comment by EisenbergEffect** [comment]
Interesting! We could fix this here: https://github.com/microsoft/fast/blob/24e74a90708916c9c04d4b389a6219bf79f1a2c9/packages/web-components/fast-element/src/dom.ts#L132 by just adding a space before and after. What do you think?

**Comment by radium-v** [comment]
Swapping the two lines in the source template (`ref()` and `@slotchange`) would probably work in this case, though that would just be a quick fix and not a solution to the underlying problem.

**Comment by chrisdholt** [comment]
@radium-v when you're able - could you take a look, I do think the two issues (this and the one linked from Fluent UI) are likely related to the transform fragments snippets we currently use.
