### ISSUE TITLE
fix: Elements with non-observable properties get overriden value clobbered on connection

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4696]
# 🐛 Bug Report
It seems that an element with a non-observable property that is initialized and then externally overridden prior to connection gets it's value reverted after connection. See min-repro.
 

## 💻 Repro or Code Sample
Min repro: https://stackblitz.com/edit/property-clobber-repro?file=index.ts

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by RandomEngy** [comment]
I think this is behavior from custom elements. You can work around by moving that property initializer to the constructor and checking to see if it's been assigned a value already.

**Comment by chrisdholt** [comment]
Given the discussion here I'm going to close this issue as a platform issue. Feel free to reopen if you feel this is a mistake.
