### ISSUE TITLE
Blazor - Fast Button raises click event even if disabled

### ISSUE THREAD

**Issue by perpetualintelligence** [microsoft/fast#4698]
I have a simple fast-button in the disabled state. It may not be in disabled state and then the Click event is valid.

```
               <fast-button disabled="@Disabled" @onclick="@OnDisClick">
                    Disabled
                </fast-button>
```

The JSInterop for blazor for the click event...

```
    private async Task OnDisClick(MouseEventArgs args)
    {
        await JsInteropService.AlertAsync("Disabled Click");
    }
```

The button is correctly rendered and shows the disabled icon but if I click the onclick event calls OnDisClick... 

![image](https://user-images.githubusercontent.com/62374075/117732227-58f2eb80-b1a4-11eb-9da0-101abfb11493.png)

![image](https://user-images.githubusercontent.com/62374075/117732274-6e681580-b1a4-11eb-9ad5-e0c516d965df.png)

Visual Studio 2019
Blazor WebAssembly

**Comment by EisenbergEffect** [comment]
We'll have to investigate how to do this, since the platform doesn't block events just because an element is disabled. This seems to be something that is built into the platform button itself.

**Comment by ameyasubhedar** [comment]
Not just with button, fast menu item item also has this issue. Seems like a major bug as this would impact lot of downstream code for applications switching to fast framework.

@EisenbergEffect  Might be worth determining all the components that this issue.

**Comment by EisenbergEffect** [comment]
Closing this issue in favor of https://github.com/microsoft/fast/issues/4884 which tracks the core problem.
