### ISSUE TITLE
Remove duplicate fixture.ts files once `fast-tooling` no longer pulls packages from npm registry

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#4714]
As part of the vNext updates, the `fast-tooling` package was updated to pull dependencies from NPM to avoid issues and breaking changes. As part of this, we needed to remove the internal dependency on the local `fast-foundation` fixture utility and duplicate the those files within tooling.

This issue exists to track the removal of these duplicated files once tooling is again taking its dependency from within the repository.

**Comment by janechu** [comment]
We're going to keep this as a duplicate file, due to the potential for this breaking in the future, as well as the issue of this not being consumer-friendly as it is not documented in any meaningful way.
