### ISSUE TITLE
fix: error on attribute with empty string value followed by attached behavior in fast-element

### ISSUE THREAD

**Issue by RandomEngy** [microsoft/fast#4717]
# 🐛 Bug Report
An attached behavior directive following an attribute with an empty string value will cause an error.

## 💻 Repro or Code Sample
Minimal repro: https://stackblitz.com/edit/empty-attr-error-repro?file=index.ts

## 🤔 Expected Behavior
Binding works fine and gives empty string to the attribute value, and executes the attached behavior

## 😯 Current Behavior

> compiler.js:44 Uncaught (in promise) TypeError: finalParts[i] is not a function
>     at BindingObserverImplementation.binding (compiler.js:44)
>     at BindingObserverImplementation.observe (observable.js:284)
>     at BindingBehavior.normalBind [as bind] (binding.js:10)
>     at HTMLView.bind (view.js:117)
>     at BindingBehavior.updateContentTarget [as updateTarget] (binding.js:75)
>     at BindingBehavior.normalBind [as bind] (binding.js:10)
>     at HTMLView.bind (view.js:117)
>     at ViewTemplate.render (template.js:99)
>     at Controller.renderTemplate (controller.js:333)
>     at Controller.finishInitialization (controller.js:297)

## 🔦 Context

Ran across this trying to build the new tab page in web components. The instance ID attribute happened to be set to the empty string and I had a hard time figuring out why we were getting the error.

## 🌍 Your Environment

* Windows 10
* Edge
* `@microsoft/fast-element` 1.0.2

**Comment by chrisdholt** [comment]
Closing as stale. I also think that wrapping the binding expression in a string resolves this (`instanceid="${empty}" ${directive(...)}`)but perhaps I'm being dense. Late in the day and so close to break :). Feel free to open if that's the case!
