### ISSUE TITLE
fix: private backgroundColorChanged in FASTDesignSystemProvider 

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#4721]
# 🐛 Bug Report

I'm wondering if there is a specific reason why `backgroundColorChanged ()` is `private` in `FASTDesignSystemProvider ` ? See https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/design-system-provider/index.ts

## 🤔 Expected Behavior

I'm running an experiment to build an extended version of the fast design system. It's great to benefit from FAST and being able to extend things. But having `backgroundColorChanged()` private prevents it from being extendable. 

What I'm trying to accomplish in my use case is create a new neutral palette and call a custom method that creates a new color available for the design system (based on background) and do this any time backgroundColor changes.

If this method would be public I could do:

```ts
public backgroundColorChanged(oldValue: string, newValue: string): void {
    if (newValue !== oldValue) {
      this.backgroundColor = newValue;
      const parsedColor = parseColor(newValue)
      if (parsedColor) {
        this.neutralPalette = createColorPalette(parsedColor);
      }
      this.setBackgroundTeintedColor();
    }
    super.backgroundColorChanged();
  }
```

If it fits I would be happy to submit a PR to make it public.

**Comment by EisenbergEffect** [comment]
@nicholasrice Can you chime in here with recommendations? Am I correct in assuming that this issue is solved with the new design token implementation?

**Comment by nicholasrice** [comment]
I don't see a problem with making that method public. The `backgroundColor` property is observable though too, so you can subscribe from anywhere and do the same work:

```ts
// Somewhere in DSP, probably constructor or maybe connectedCallback
Observable.getNotifier(this).subscribe(subscriber, "backgroundColor")
```

https://www.fast.design/docs/fast-element/observables-and-state#external-observation goes into more depth on how to use

**Comment by ben-girardet** [comment]
Thanks for this answer. Makes sense. For now I'll play with the Observable. Had a look at DesignToken work and yeah seems very promising. It is still considered alpha, right ?

**Comment by EisenbergEffect** [comment]
The DesignToken work is technically still alpha. We're working on a bunch of stuff in a vNext design system branch. We hope that will merge pretty soon. When we release from that there will be a major version bump and all the alpha stuff will be official. Shouldn't be too much longer. We're working through the last details now.

**Comment by ben-girardet** [comment]
That's cool. Thanks for the infos
