### ISSUE TITLE
feat: Add ability to render elements in number field's step controls

### ISSUE THREAD

**Issue by daviddossett** [microsoft/fast#4724]
# 🙋 Feature Request

In order to match the design language of the rest of our component toolkit built on top of FAST, we need to be able to render our own arrow icons within the number field's step controls in place of the default arrow icons.

Given that we only need to customize the arrow icons themselves, I believe we only need the ability to slot content inside the `.step-up` and `.step-down` divs that house the default arrow icons and handle the click event.

Requested markup from `.number-field-template.ts`
```
 <div class="controls" part="controls">
  <div class="step-up" part="step-up" @click="${x => x.stepUp()}">
    <slot></slot>
  </div>
  <div class="step-down" part="step-down" @click="${x => x.stepDown()}">
    <slot></slot>
  </div>
</div>
```

## 💻 Examples

Default icons:
<img width="230" alt="CleanShot 2021-05-17 at 16 51 31@2x" src="https://user-images.githubusercontent.com/25163139/118570072-29a62680-b730-11eb-972b-1c572366ae3f.png">

Example of Figma component w/ custom styling + product-specific icons
<img width="544" alt="CleanShot 2021-05-17 at 17 05 17@2x" src="https://user-images.githubusercontent.com/25163139/118570999-109e7500-b732-11eb-9c9b-6215355ea3bd.png">

cc @hawkticehurst

**Comment by EisenbergEffect** [comment]
This feature is part of the next major release of the components. You'll also be able to override the glyph during component setup so that it's replaced across all instances of the number field and you don't have to slot it in everywhere.

**Comment by daviddossett** [comment]
@EisenbergEffect Thanks for letting us know!

One more question: Will the upcoming ability to override glyphs during component setup apply to other components as well (namely Breadcrumb Item separators and Checkbox icons)? We realized we're running into the same issues with those components.

Also, if it's not already on the to-do list I'd be happy to open new issues for them.

**Comment by chrisdholt** [comment]
> @EisenbergEffect Thanks for letting us know!
> 
> One more question: Will the upcoming ability to override glyphs during component setup apply to other components as well (namely Breadcrumb Item separators and Checkbox icons)? We realized we're running into the same issues with those components.
> 
> Also, if it's not already on the to-do list I'd be happy to open new issues for them.

Yes, this will support those as well. You'll have the ability to register the design system with those for your entire app. Additionally, you can still (as you can today) slot individual instances as well when needed, but the default slot behavior should support all instances where default slotted content previously existed.
