### ISSUE TITLE
fast_text_field missing DateTime support

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4725]
![image](https://user-images.githubusercontent.com/13166236/118578652-629ac700-b741-11eb-8fc1-f215afebedaf.png)

fast_text_field needs to support the DateTime in order for users to pic Date and Time.

**Comment by chrisdholt** [comment]
Thanks for the issue @ameyasubhedar - I think this is going to be a separate component. Were the text field component *just* an input with styles, this could be the case. It's more a matter of providing a control to text-specific inputs. @robarbms is working on "calendar" and as part of that has been looking at a necessary Date/Time control as well. I think those will go hand in hand and likely provide the type of support you are looking for.

**Comment by EisenbergEffect** [comment]
Closing this as duplicate of #4751
