### ISSUE TITLE
Missing File Picker

### ISSUE THREAD

**Issue by apsthisdev** [microsoft/fast#4726]
Fast components is missing the file picker.

Uploading files  is a common use case and a file picker should be available as a basic component.

Also the component should support filter types to filter file types.

**Comment by EisenbergEffect** [comment]
Thanks for the feature request @ameyasubhedar We will consider this addition. In the meantime, you may be able to accomplish what you need by using the Native FileSystem API. Here's a library that makes that very easy and provides a simple fallback for browsers that don't yet implement the standard: https://github.com/christianliebel/browser-nativefs You could wrap this up in a simple custom web component if desired as well.

**Comment by chrisdholt** [comment]
Just an updated that @litteredwitherrors is working on a spec for `file` as a new component.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
