### ISSUE TITLE
Missing Multiselect Component

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4727]
Fast components is missing a multi select component. There is a Radio Group, Select, List, but that enables only single select.

A check box group or a list with check box components would be ideal for multi selections.

**Comment by EisenbergEffect** [comment]
@radium-v Can you share a bit about the work going on with multi-select in the select component so we can better understand if that will address this request?

**Comment by chrisdholt** [comment]
> @radium-v Can you share a bit about the work going on with multi-select in the select component so we can better understand if that will address this request?

While we await @radium-v's response, I will note that my hope is that the multiselect behavior in Select will help solve this problem. If not, I'd like to hear and understand more about what a "checkbox" group would do? To me, that sounds primarily like an HTML form element. There's no additional behaviors I would expect to be part of that control besides styles to lay it out visually from what I can tell, so it would be helpful to understand the scenario you're looking to solve for if not Multiselect in Select. Thanks!

**Comment by radium-v** [comment]
I'm currently adding the `multiple` functionality to `listbox`, which will also enable it in `select`.

From a data standpoint, a checkbox group is currently achievable with `<fast-checkbox>` elements in a form. Any checked checkboxes in a form with the same `name` will be returned with [`FormData.getAll`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/getAll) and will also appear when the form is submitted (for `GET` requests, the checked values are all appended to the URL like `?check-group=1&check-group=2` etc.).

```html
<form id="demo" onchange="result.value=new FormData(demo).getAll('check-group').toString()">
    <div>
        <fast-checkbox name="check-group" value="1">1</fast-checkbox>
        <fast-checkbox name="check-group" value="2">2</fast-checkbox>
        <fast-checkbox name="check-group" value="3">3</fast-checkbox>
        <fast-checkbox name="check-group" value="4">4</fast-checkbox>
    </div>
    <output name="result" for="demo"></output>
</form>
```
(Here's a more comprehensive demo: https://stackblitz.com/edit/typescript-k5c5hn?file=index.html)

This is technically the same behavior that `radio` elements exhibit, with the additional constraint that only one radio in a group can be selected at a time.

**Comment by ameyasubhedar** [comment]
Thanks @radium-v , what about using the check box group in the Select Dropdown. We have common use case where we present dropdowns to the user and then they can check multiple options.

![image](https://user-images.githubusercontent.com/13166236/119565926-68a33000-bd5f-11eb-9046-3f7ac0d2c0ab.png)


I tried setting check box in the Select component but this does not work.

```
<fast-select>
    <fast-option value="1">
        <fast-checkbox>Option 1</fast-checkbox>
    </fast-option>
    <fast-option value="2">
        <fast-checkbox>Option 2</fast-checkbox>
    </fast-option>
    <fast-option value="3">
        <fast-checkbox>Option 3</fast-checkbox>
    </fast-option>    
</fast-select>
```

Also, @EisenbergEffect, what about model binding for select component ? Does radio, select, and now multiple select all have issues of not model binding for asp.net core and Blazor apps, or is it just the check box ([4248](https://github.com/microsoft/fast/issues/4248))

**Comment by EisenbergEffect** [comment]
@ameyasubhedar There is currently a feature being discussed for Blazor that would enable Blazor to set properties on HTML elements. Today it can only set attributes. Because our FAST components try to match platform behavior, a few form controls can only be updated through properties. Blazor has special code to handle this for built-ins rather than a general mechanism that can be used on any component. That's the source of the problem. If Blazor can't or is unwilling to add this as a general feature, there are a couple of other options, including trying to come up with another feature for Blazor that would solve this, or us re-working our web components to deviate from the behavior of built-ins. We're discussing some of this in the fast-blazor issue list.

**Comment by ameyasubhedar** [comment]
@EisenbergEffect, thanks: I have proposed a temporary workaround that asp.net core and Blazor apps can use immediately https://github.com/microsoft/fast/issues/4782. Please check and let me know if this something Fast team can provide as a workaround for binding issues.

**Comment by chrisdholt** [comment]
@ameyasubhedar wanted to give an update that we're pushing to get this done in September and out the door. I'm going to dupe this issue against #4190, but both of these are linked to the PR. They should both receive a notification when this has been merged. Once that's done it should be a quick update in the Fluent packages to get the latest version which will pave the way for you to leverage this.
