### ISSUE TITLE
update code ownership across mono-repository

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4750]
This repository has gone through many restructures and it's time we re-assess code ownership to ensure PRs are being approved by the correct owners and/or number of owners.

1. Evaluate existing code ownership policy from file and from GitHub as a feature may have had improvements since we began.
2. Setup a meeting to discuss each package current ownership and should it be changed or improved?
3. Provide recommendations to this issue
4. Implement after all fast-collaborators have approved a new code ownership policy.

**Comment by chrisdholt** [comment]
Closing as I think Codeowners is still likely valid from what I can tell.

If folks have a specific request or change they'd like to propose let's go through the process we have documented.
