### ISSUE TITLE
feat: add date-picker component

### ISSUE THREAD

**Issue by robarbms** [microsoft/fast#4751]
# 🙋 Feature Request

A custom date-picker component.

## 🤔 Expected Behavior

Can enter a date into a date-picker field with some basic validations. An icon for a calendar view that will allow the user to pick the date from a calendar.

## 😯 Current Behavior

We need a date-picker component ones found in other libraries.

## 💁 Possible Solution

`
<fast-date-picker></fast-date-picker>
`

## 🔦 Context

This is a community ask.

## 💻 Examples

[W3C Date picker](w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html)

![w3c-date-picker](https://user-images.githubusercontent.com/69695238/119026966-a4528a00-b95a-11eb-97da-a66665cc176f.png)
![w3c-calendar](https://user-images.githubusercontent.com/69695238/119026980-a87ea780-b95a-11eb-874c-0fa73c850f21.png)

[MDN Date picker](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)
![date-picker-SS](https://user-images.githubusercontent.com/69695238/119026995-ad435b80-b95a-11eb-9c59-b20bbf5c0f8d.png)

![date-picker-SS2](https://user-images.githubusercontent.com/69695238/119027011-b16f7900-b95a-11eb-9e4e-9fa1e51962d5.png)

**Comment by ben-girardet** [comment]
A date picker FAST web-component would be awesome !!

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
