### ISSUE TITLE
feat: custom attribute that create a new DSP with relative values

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#4760]
# 🙋 Feature Request

This feature request is more like an idea. I'm wondering what the FAST community and team is thinking about it and if it's doable ?

The idea is to create a practical way (such as with custom attribute) to alter a current DSP (from any point in the DOM) and propagate the new DSP version further in the DOM. It looks like what I'm suggesting is to place a new `<fast-design-system-provider>`  but it's not the point. The idea would be that a custom attribute (or something else if there is a better idea) could create a new DSP relative to the closest parent (and if possible without the need to create a new DSP element every time)

I'll quickly give an exemple:

```html
<fast-desisn-system-provider density="4">
  ...
  <fast-form-container densify>...</fast-form-container>
  <!-- the densify attribute above would not be an attribute of fast-form-container, but a custom attribute available everywhere -->
  ...
</fast-design-system-provider>
```

In the exemple above, the custom attributes `densify` above would do the following:

1. Find the closest DSP parent
2. Change some of its properties (density for exemple)
3. Create a new DSP at the level of the curent element (`fast-form-container densify` above)

The difference with "just another `fast-design-system-element` would be that the `densify` attribute takes the density of the closest DSP and manipulate it to get its own value (for exemple, increase the density of 1 point).

This leads me to a few questions:

1. Any interest for such a feature from the FAST team ?
2. Is it currently possible to create custom attribute(*). Meaning, an attribute that could be applied to any elements (at least any fast element but why not any element of the DOM)
3. In the above scenario, is it necessary to actually wrap the `[densify]` element with a new DSP element in the DOM ? Or is it possible to create a new DSP layer "on the fly" without placing one in the DOM ?

(*) Like in Aurelia

## 🤔 Expected Behavior

1. Possibility to create custom attribute
2. Possibility to add new DSP layers on the fly

## 💻 Examples / Use cases

Here are some use case I see for such a feature

1. `densify` => would increase / decrease the current density. For exemple a page would have a large density (big space between elements) and in the page, a FORM would have a smaller density (less space between fields elements). But the density of the form would be relative to the density of the page. If the density of the page is set higher, the form density would still be smaller than the page but larger than before
2. `darken` => would take a color such as backgroundColor and darken it. This could be used in multiple card / layer elements stacked over each other and getting darker with the number of elements stacked. Again, this would be relative to the context
3. `alternate` => would take the background color of the current DSP and switch to another color. Doing this back and forth, again depending on context.

There might be other / better approaches to accomplish what I'm describing. I'm naturally very open to hear any ideas that go in a similar direction.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time along with the design system provider.
