### ISSUE TITLE
audit tooling/fast-tooling-react

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4761]
Auditing fast-tooling-react package in the mono-repository to validate each dependency and document the impact of upgrading to Webpack 5. Before beginning, the audit, document the testing plan and discuss it with the team so we have a comprehensive understanding of what we're up against. Each package should be documented one at a time initially.

## 🔦 Context
Run all script commands on existing code to note dependencies, warnings, errors, and bugs running locally

## 💻 Examples

**Scripts**
$ yarn
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "win32" is incompatible with this module. fsevents is useful for MacOS environment only.

warning " > @microsoft/fast-tooling-react@2.8.9" has unmet peer dependency "@microsoft/fast-jss-manager-react@^3.0.0 || 
has unmet dependencies warning could be resolved by updating dependencies to the correct versions on all packages.

yarn prepare should also do the build. yarn build does not work by itself.

**Comment by chrisdholt** [comment]
Just a heads up - I'm going to change this from an "RFC" to just a generic issue. As an RFC is a "request for comment", I think this is likely best just a normal issue, unless there is a proposal/scenario where we're looking for feedback from the community.

**Comment by Ibrahimmaga** [comment]
Oh thanks

**Comment by Ibrahimmaga** [comment]
moved issue to #4736
