### ISSUE TITLE
FAST Menu cannot be used in named slots.

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#4795]
# 🐛 Bug Report

Currently, `Menu` cannot be slotted into other components using named slots.
Internally `Menu` checks to see if it is a submenu and either sets the slot attribute to `submenu` or `undefined`, thus removing any user-defined value for the slot attribute.

## 💻 Repro or Code Sample

https://stackblitz.com/edit/fast-design-qqi4ue?file=index.html

## 🤔 Expected Behavior

Menu should retain user-defined values for the `slot` attribute.

## 😯 Current Behavior

Menu overrides the user value to either `submenu` if it is a descendent to another menu, or `undefined`

## 💁 Possible Solution

Possible fix could be to first check if `slot` is already set and to then use that instead of setting to undefined.
However, this could potentially create some conflicts with the submenu behavior and user expectations in cases where developers are creating custom nested menus and are trying to set the `slot` to something other than `submenu`.

## 🔦 Context

Creating a generic popup-like component with multiple named slots. A workaround is currently achieved by using a default slot when using `Menu`, but this is not ideal.

## 🌍 Your Environment

Windows 10
Edge Canary(latest)
FAST-Element(latest)
FAST-Foundation(latest)
FAST-Components(latest)

**Comment by chrisdholt** [comment]
Thanks @KingOfTac!
