### ISSUE TITLE
Missing notification component

### ISSUE THREAD

**Issue by apsthisdev** [microsoft/fast#4811]
Fast components is missing a notification component such as a toast notification to flash a status of an action.

It should provide slots for icon, label and a timer to auto hide the notification after the specified time interval.

**Comment by atmgrifter00** [comment]
Any thoughts on this from the FAST devs?

**Comment by chrisdholt** [comment]
> Any thoughts on this from the FAST devs?

I think we can start a "spec" to investigate this after our Foundation vNext release.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time, additionally `@microsoft/fast-foundation` is in process to be deprecated per #6955.
