### ISSUE TITLE
fast_dialog locking height and width

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4813]
The fast_dialog defaults to height 480px and width 640px with the following css variables...

![image](https://user-images.githubusercontent.com/13166236/120404315-f2707180-c2fa-11eb-97e7-ba12db37999f.png)

![image](https://user-images.githubusercontent.com/13166236/120404269-dc62b100-c2fa-11eb-986e-6ce0b81c5499.png)

Why is the height and width fixed ? setting the style:height and style:width has no impact. 

How does app authors change the height and width to fit its contents ?

**Comment by chrisdholt** [comment]
We use CSS custom properties because the actual "dialog" part of the element is not the host, but DOM further down in the shadowDOM. If you pass your height/width as CSS custom properties you should see the dialog resize as expected:

```css
fast-dialog {
   --dialog-width: 50%;
   --dialog-height: 50%;
}
```

alternatively:

```html
<fast-dialog style="--dialog-width: 50%; --dialog-height: 50%;">My Dialog</fast-dialog>
```

**Comment by chrisdholt** [comment]
If the above address your question, I'll close the issue - leaving open now for your follow-up :)

**Comment by ameyasubhedar** [comment]
@chrisdholt thanks, yes the custom CSS properties does work, is there any link that list all the supported custom properties and its example usage. This would be helpful devs.
