### ISSUE TITLE
fast_anchor shows weird hover background in Firefox and Safari

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4817]
The fast anchor in lightweight mode shows this weird background on hover for Firefox and Safari browsers. They work fine on Edge and Chrome.

Edge, Chrome:
![image](https://user-images.githubusercontent.com/13166236/120687415-db469680-c456-11eb-8452-a23597530233.png)

Firefox, Safari:
![image](https://user-images.githubusercontent.com/13166236/120687114-8c006600-c456-11eb-858b-fdf0ee10b918.png)

**Comment by chrisdholt** [comment]
Thanks @ameyasubhedar - this looks like bug where the background is being applied on the host on hover and other appearances are applying that on the control part. @khamudom can you take this and get a fix up?
