### ISSUE TITLE
Website CORS policy when loading fonts from static.fast.design

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4819]
The current CORS policy for Creator is not allowing access to fonts from `static.fast.design`. When loading the page this results in the following console error:

Console error:
```
Access to font at 'https://static.fast.design/assets/fonts/SegoeUI-Roman-VF_web.ttf' from origin 'https://stage.create.fast.design' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://explore.fast.design' that is not equal to the supplied origin.
```

**Comment by awentzel** [comment]
A CORS policy already exists for allowing "https://static.fast.design".  On a network trace, I don't see any errors.  Where is the request coming from?  Is an Iframe involved? Could you add more details about how you're seeing this error?

**Comment by janechu** [comment]
This is specifically an issue on `stage.create.fast.design`. I'm not sure if that's because there's a difference in the servers hosting the staging and production sites or because production doesn't reference the `static.fast.design` for the font, it's hard to tell because the last time the production site was updated was a fairly long time ago.

**Comment by awentzel** [comment]
When the Standard rules engine for Azure CDN Standard are applied to fonts files stored on the CDN, the initial request works great, however, future requests never update the `Access-Control-Allow-Origin` and thus the originally requested origin does not match the response.  This explains, why for a long time I was making configuration changes with Express middleware and never seeing any changes.  The final, hint in troubleshooting this error came in when I got it running the site locally with `yarn start`.  Additionally, this error is occurring across other sites leading me to in fact a CDN configuration issue, not App Service or App code.

The [problem](https://docs.microsoft.com/en-us/azure/cdn/cdn-cors#multiple-origin-scenarios) occurs when the CDN caches the Access-Control-Allow-Origin header for the first CORS origin. When a different CORS origin makes a subsequent request, the CDN will serve the cached Access-Control-Allow-Origin header, which won't match. There are several ways to correct this.

The solution was to add a new [standard rules engine](https://docs.microsoft.com/en-us/azure/cdn/cdn-cors#azure-cdn-standard-profiles) configuration to handle this request/response from within Azure CDN.

Create a new standard rule on the `fast-cdn/fast-static` endpoint as described above.  

**The new rule:**
![Screen Shot 2021-06-09 at 10 16 07 AM](https://user-images.githubusercontent.com/16669785/121400134-125ff080-c90c-11eb-905b-711e954114c8.png)
The HTTP header name to use is "Access-Control-Allow-Origin" with a "*" wildcard for all. 

**The request header values:**
![Screen Shot 2021-06-09 at 10 15 58 AM](https://user-images.githubusercontent.com/16669785/121400185-23a8fd00-c90c-11eb-808d-a11d733a606b.png)
