### ISSUE TITLE
Creator CSP issue when attempting to reference images

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4820]
When attempting to load images from a placeholder service (which uses https) an error is thrown and the image is not loaded. This can be achieved in the Creator by adding a `Card` component.

Console error:
```
Refused to load the image 'https://via.placeholder.com/320x180' because it violates the following Content Security Policy directive: "img-src 'self' data: *.fast.design".
```

**Comment by awentzel** [comment]
I've updated the CORS policy to support this service. However, we should not really be using third-party services per Security Policy.  Let's see if CORS update will fix this.  Also, I'll have to reach out to Security team to understand alternative approaches.

**Comment by janechu** [comment]
I think we want to try both angles, getting an exception and having our own service.

I assume having our own service is going to take some time, and that's an issue because our pointing to other hosted image locations is causing the site to look broken.
