### ISSUE TITLE
fix: slider's thumb stays active after you go outside the container element

### ISSUE THREAD

**Issue by UtmostCreator** [microsoft/fast#4825]
# 🐛 Bug Report

If you hold down the left mouse button (LMB) on a thumb and start dragging it, and after you move your cursor outside the container and release the LMB; if you try to move your cursor back to the container (where the slider is, the thumb stays active so as if you weren't releasing the mouse button.

## 💻 Repro or Code Sample

[official example link](https://explore.fast.design/components/fast-slider)
code:
`<fast-slider></fast-slider>
`
## 🤔 Expected Behavior

After releasing the LMB the thumb of a slider should not move

## 😯 Current Behavior

After releasing the LMB the thumb of a slider outside the container, the thumb stays active and moves (when you entering the container); it stops only after you click inside the container.

## 💁 Possible Solution

detect releasing of a button to prevent the button from being inactive (as it is being held down w/o releasing)

## 🔦 Context
—

## 🌍 Your Environment
It can be reproduced only in the chrome browser.
Firefox works fine. 91.0.4472.77 

* OS & Device: Win 10 20h2, OS build 19042.985;
* Browser Google Chrome ( 93.0.4532.0; 91.0.4472.77);
* Version latest (from official web-page components.

**Comment by chrisdholt** [comment]
@robarbms I wanted to check in and see how this is coming along.
