### ISSUE TITLE
rfc: Color Recipe Dependency Injection [DesignSystem vNext]

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4829]
I discovered an issue w/ the current implementation of Color Recipes as DI symbols, specifically how they are used in DesignToken default values. As it stands today, there is not an opportunity for app-authors to register their own color-recipe using DI prior to DesignTokens setting default values and resolving the DI registration. The basic flow of what is happening is as follows:

1. Recipe DI interface is defined and provided a default value, using our color recipe
2. DesignToken is created and assigned a default value that retrieves the DI registration
3. Step 2 causes the token to be immediately evaluated so that the CSS custom property can be written to the DOM. That evaluation causes immediate retrieval of the default registration.

**example of what we have today:**
```ts
export const NeutralDivider = DI.createInterface<(element: HTMLElement) => SwatchRGB>(
    "neutral-divider",
    builder =>
        builder.instance((element: HTMLElement) =>
            neutralDividerAlgorithm(
                neutralPalette.getValueFor(element),
                fillColor.getValueFor(element),
                neutralDividerRestDelta.getValueFor(element)
            )
        )
);
/** @public */
export const neutralDivider = create<SwatchRGB>("neutral-divider").withDefault(element =>
    DI.getOrCreateDOMContainer(element).get(NeutralDivider)(element) // This gets called synchronously for the document body.
);
```

Somehow, we need to provide opportunity to the app-author to register their own color recipe prior to evaluating the DesignToken for the `withDefault()` call. 

A few options I see:

## DesignToken.init()
Require some sort of `DesignToken.init()` call that actually evaluates the token. That would need to be called by app authors. This isn't my favorite because design tokens can be created at any point in time, so either we require multiple `init()` calls or there is some inconsistency about when a token's value will be written. It also doesn't seem like the concern of a DesignToken to introduce a lifecycle just for an *implementation* of a token value using DI.

## Component-library init
Add some sort of function to be called that actually applies the default values:

```ts
import { designTokenInit, NeutralDivider } from "@microsoft/fast-components";

DI.getOrCreateDOMContainer().register(Registration.instance(NeutralDivider, () => /* do something */));

designTokenInit(); // This actually does the `withDefault()` call
```

I'm not the biggest fan of this for a few reasons:
1. It would prevent tree-shaking of design tokens and color recipes
2. Just like the above, it's another step an app-author needs to do to get up and running w/ Design Tokens

## Recipe API abstraction that handles updating recipes
We could introduce some sort of color API that would register a update DI registrations internally and re-assign token-values where necessary to force re-resolution of DI registrations:

```ts
FASTColors.register(NeutralDivider /* this is a DI interface */, () => /* do something */);

// Internally this does something like:
DI.getOrCreateDOMContainer().register(Registration.instance(NeutralDivider, fn);
neutralDivider.withDefault((el: HTMLElement) => 
    DI.getOrCreateDOMContainer().get(NeutralDivider)(el);
)
```

The problem with this approach is that it could have intuitive interactions with DesignTokens. Authors would need to know that the `FASTColors` API sets tokens if they're updating default values for tokens themselves. For instance, an author might not expect that the following would clobber their own default:

```ts
neutralDivider.withDefault(SwatchRGB.create(1, 0, 0));
FASTColors.register(NeutralDivider, () => /* do something */) // This calls neutralDivider.withDefault itself, clobbering the above expression
```

I'm honestly not the biggest fan of any of these approaches, so I would appreciate any thoughts on the issue.

**Comment by EisenbergEffect** [comment]
A couple additional ideas might be:

1. Add a `withLazyDefault` that could be used for these DI dependent scenarios, which would not immediately evaluate.
2. Wrap up the `withDefault` setup inside of a function that creates a `Registration` sort of like `FoundationElement.compose`. Then the end user would pass this to the design system and would have the opportunity to override it.
3. A variation of idea 2 would be to create a single color configuration API that returns a registration which can be passed to the DesignSystem. That API would let people pass in alternate implementations and would not call `withDefaults` on anything until it's `register` implementation.

So, something like idea 3 might look like this to the consumer

```ts
DesignSystem.getOrCreate()
  .register(
    fluentColorSystem(),
    fluentButton()
  )
```

Or with some sort of overrides:

```ts
const recipes = new Map();
recipes.set(NeutralDivider, () => ...something...);

DesignSystem.getOrCreate()
  .register(
    fluentColorSystem({
      recipes
    }),
    fluentButton()
  )
```

**Comment by EisenbergEffect** [comment]
Actually, we might be able to do this:

```ts
DesignSystem.getOrCreate()
  .register(
    Registration.instance(NeutralDivider, fn),
    fluentColorSystem(),
    fluentButton()
  )
```

In this case, `fluentColorSystem` in its `register` implementation can check each recipe to see if the container has an implementation. If so, get it and call `withDefaults` otherwise provide a default.

**Comment by EisenbergEffect** [comment]
We could also extend some DesignSystem related APIs so that it can do some things with colors that we do with components, where the component declares its intent to define but all the defines happen later at the end. You can see this in the way that `DesignSystem`, `ElementDefinitionContext`, and `FoundationElement` interact with one another.

**Comment by nicholasrice** [comment]
The second way you're showing here won't work, because `fluentColorSystem()` is evaluated before `register()`, so the overrides *still* aren't overriden. The first example would work, but I'm not the biggest fan of it for two reasons:
 1. It will be impossible to tree-shake un-used tokens and recipes because `fluentColorSystem()` would hold references to *all* recipes and tokens
 2. There isn't really any *functional* benefit to invoking it in the `.register()` method of the Design System other than execution order. The `.register()` method wouldn't really use the result of `fluentColorSystem()`
 
I think I might be able to address these a slightly different way.

A missing feature of `DesignToken` is the ability to configure the HTMLElement that default values are applied to. We could add a `DesignToken.configure(options: {defaultElement: HTMLElement})` API that needs to be invoked by app authors. That way, default values for tokens aren't actually evaluated until `DesignToken.configure()` is invoked. Authors could register new recipes prior to calling `DesignToken.configure()`

We could potentially also add a convenience method to synchronize the DesignSystem host with the DesignTokens:

```ts 
DesignSystem.configureTokens(DesignTokens);
````

The above would invoke `DesignTokens.configure()` with the defaultElement set to the `DesignSystem`'s host element.

Thoughts?

**Comment by bheston** [comment]
I've been a bit far from the details of the recent implementation, but it sounds like the issue here is exclusive to initialization and not subsequent update. Is the idea still that the DI graph is observable and when any upstream value (default or not) changes all downstream values are reevaluated?

Put another way, can `withDefault` simply set the initial value as equivalent to `ssetValueFor(document.body)`? That is logically what I was thinking `withDefault` did. So then if I update the `NeutralDivider` token value, at any scope, and dependent recipes would be updated even if they produced a css variable that had already been written to the dom.

If the issue is scoping or timing related, could we reserve the document root for the built-in default values and encourage / allow app authors to override values at an `app` scope, similar to the `root` node used in React?

Further, what if an app author doesn't want to update a value at app initialization, but later in response to a settings change or some other trigger? It seems like our solution needs to allow for something that works aside from initial values.

**Comment by EisenbergEffect** [comment]
@nicholasrice Can it be something like this?

```ts
DesignSystem.getOrCreate()
  .withTokens(...)
  .register(
    fluentButton()
  );
```

That seems like it would be pretty natural and fit into the current model.

**Comment by nicholasrice** [comment]
@EisenbergEffect yea something like that. In my example above the `DesignToken` factory is provided, not the token instances themselves. Providing the individual tokens might be a pain since there are 100+ token instances just in fast-components.

We could take the approach of configuring each individual token if we added a convience method to `DesignToken` to retrieve all tokens?

```ts
DesignSystem.getOrCreate()
  .withTokens(...DesginToken.all())
  .register(
    fluentButton()
  );
```

The above would require each token instance to track it's own *default element*, as opposed to the current implementation where all tokens share a *default element*. I'm not sure there is a practical reason that an author might want different elements registered as the default element for different tokens so at this point my preference would be to augment the factory with a configuration API as opposed to adding the configuration API to the design token instance.

@bheston DI isn't really observable; it doesn't really have an "update" model. It is largely designed to provide a value once, upon request. What you're describing maps more closely to a "context" API.

The problem with just encouraging authors to override values on a root node is that CSS custom properties are only emitted to elements for which the token is set for (this was part of the performance change I made). To achieve the behavior you're describing, an author would need to register a new recipe with DI for the root element *and* set the design token for that root element. WE can do that today by registering a new recipe and calling `withDefault()` again in the app, providing a new token value that uses the new registered recipe, it's just not intuitive or ergonomic.

If real-time configuration of recipes is a requirement (not just during app initialization) then I think we need to find an approach that does not use dependency injection to retrieve the recipe implementation.

**Comment by EisenbergEffect** [comment]
@nicholasrice Go with your approach to add a configuration API and then let's take a look at the PR carefully to make sure we feel good about the ergonomics. Is it correct that this is only really needed for scenarios where a token needs to access DI?

**Comment by nicholasrice** [comment]
Yep, DesignToken's will update accordingly as values change, we just don't have a mechanism to tell the design-token to re-evaluate so it uses the new registered recipe without setting the value of the token again.

**Comment by nicholasrice** [comment]
Recipes got implemented as DesignTokens instead of DI symbols, so closing this issue as it is no moot.
