### ISSUE TITLE
fast-tooltip does not provide positioning

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4831]
The fast tooltip is always shown at the bottom, which is not ideal for all cases. It overlaps with the user pointer and may hide a portion of message.

E.g. 

![image](https://user-images.githubusercontent.com/13166236/120849072-73618000-c52a-11eb-88d0-0ba7b49c8078.png)

The tooltip must provide a position, top, left, right, bottom with default value as bottom so that app authors can customize based on app needs.

See https://www.w3schools.com/css/css_tooltip.asp for example

**Comment by KingOfTac** [comment]
`<fast-tooltip>` has a position attribute that you can set, with "bottom" being the default behavior. See: [FAST Tooltip Positioning](https://stackblitz.com/edit/typescript-jwvzt2?file=index.ts) for an example.

**Comment by chrisdholt** [comment]
Per @KingOfTac's response, the tooltip does have a positioning attribute which can be set. If you run into questions on this feel free to reach out again or ping the support channel in Discord - always happy to help! Closing this as not-actionable. Thanks!

**Comment by KingOfTac** [comment]
One last thing to add. The position attribute also takes values `start` and `end` which behave the same as `left` and `right` respectively.

**Comment by chrisdholt** [comment]
> One last thing to add. The position attribute also takes values `start` and `end` which behave the same as `left` and `right` respectively.

Yes - if I recall, our reasoning behind this is that those semantic names lend themselves to localization while right/left, etc do not

**Comment by KingOfTac** [comment]
Is the positioning swapped for start and end when in a rtl layout? 
For example in ltr start = left, end = right and rtl start = right, end = left.

**Comment by chrisdholt** [comment]
> Is the positioning swapped for start and end when in a rtl layout?
> For example in ltr start = left, end = right and rtl start = right, end = left.

Official options shown below - I would expect start/end to localize. If they don't, please open a bug as that is not intuitive!
https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/tooltip/tooltip.options.ts
