### ISSUE TITLE
rfc: repository split proposal

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4832]
# Repository split proposal

This proposal is to split packages and sites from the FAST repository into multiple repositories.

## Should we split the repository?

Currently all FAST packages and sites are in the FAST mono-repository. This has some pros and cons and recently more cons have been exposed. Depending on how severe we feel the cons are, we should either keep the current stucture or opt to split out certain packages into their own repositories.

### Pros
- The sites, tooling and components allow for the sites to always have the latest updates from all packages
- Fixes to FAST tooling in the sites can be adopted instantly
- Testing changes to components and FAST tooling that might affect sites is more streamlined

### Cons
- The tooling is it's own distinct concept, while it is primarily made for the manipulation of web components, the way it has been structured allows for a multitude of use cases which is hard to explain in the context of the FAST components and therefore should deserve it's own project
- Painful rebasing can occur when feature branches are worked on, especially when they include breaking changes
- There is friction created from the current situation due to Tooling having to take FAST changes immediately, Tooling may have a niche feature it relies on not deemed essential to FAST dependencies but will force FAST libraries to wait to update their breaking changes until those requested feature(s) are completed.

### FAST

The FAST mono-repository would remain much the same, with all component architecture, utilities, and FAST components as packages. The philosophy for what packages *should* go into FAST could be that it is a vertical stack, the base of which is `@microsoft/fast-element` which travels up the stack. What should perhaps go into the stack are things you would need to make a basic site and any supporting packages that help the development of FAST.

Packages:
- `@microsoft/fast-element`
- `@microsoft/fast-foundation`
- `@microsoft/fast-components`
- `@microsoft/fast-router`
- `@microsoft/fast-animation`
- `@microsoft/fast-benchmarks`
- `@microsoft/fast-colors`
- `@microsoft/fast-eslint-rules`
- `@microsoft/fast-web-utilities`
- `@microsoft/fast-figma-plugin-msft` (N. Rice and B. Heston have context on this, it's assumed there is a future for this package, but should it be private since its msft?)

Sites:
- [FAST component explorer](https://explore.fast.design)
- [FAST color explorer](https://color.fast.design)
- [Docusaurus site](https://www.fast.design)

### FAST Tooling

FAST Tooling has a coherent story around the Message System and components and services that subsribe to it. Ideally only the packages that accrue to that concept should be included in the FAST Tooling mono-repository.

packages:
- `@microsoft/fast-tooling`
- `@microsoft/fast-tooling-react`
- `@microsoft/fast-tooling-wasm`

### FAST Marketing site

This does not need to be in the FAST mono-repository, as it is not directly related to documentation. Open to discussion on moving this site. This is currently intrinsically tied to the Docusaurus site at present and we may revisit moving this to another repository at another time.

Open questions:
- Is this an issue we want to resolve in the future?
- If so, we can create an issue for further discussion and leave it in FAST for now

### FAST Creator

This does not need to be in either mono-repository as the future development will include potential proprietary services, pipelines, server settings, and middleware. Ideally this should be moved to a private repository for ease of development.

## What new work will have to be done to enable the split?

- Add new FAST tooling repository
    - Setup of build and publish gates
    - Migrate issues
    - Setup any additional configurations for GitHub issues:
        - Labels
        - Projects
        - Milestones
    - Add beachball & automated publishing
    - Permissions configuration

- Add new FAST Creator repository
    - Setup of build and site publish gates
    - Setup of site publishing
    - Migrate issues
    - Determine if this should be ADO repository or GitHub private repository
        - Further tasks to be added once this decision is made
    - Permissions configuration
    - De-coupling logic from the site-utilities package

**Comment by marjonlynch** [comment]
For the rebasing pain alone I would vote for this, but also the separation proposed seems very logical to me and will make maintenance easier.

**Comment by EisenbergEffect** [comment]
I think I could get behind a version of this. I've got one thing I want to discuss related to some internal stuff that might influence us a bit. Would love to get perspective from @chrisdholt

**Comment by Ibrahimmaga** [comment]
Fast Marketing Site and Fast Creator are ideal for the split since they are more independent.  The misconception about the feature branch is that sooner or later the codes from a feature branch will collide, so collide them earlier than later by rebasing.

**Comment by chrisdholt** [comment]
I'm definitely in favor of moving tooling out. I'd also agree with @janechu on moving FAST Creator out from an application standpoint as the long term plans for that may include several proprietary things. 

I will note that I think the marketing site should stay, and I'm not sure we need an issue to track that quite yet. The marketing site itself is somewhat of an implementation detail. It's how we create and serve the homepage for docusaurus, but just as docusaurus is an implementation detail of our doc story, the marketing site here is also just an implementation detail. This package may cease to be needed in the future, but our docs for `fast-element`, `fast-foundation`, and `fast-components` should live where the code is and the homepage is part of that.

Ultimately, I see both tooling and creator as a vital part of the FAST story, but the workflow, cadence, and how the projects are maintained have fundamentally different needs. Forcing resolution in a single mono-repo served an initial purpose, but at this time it's no longer beneficial to either team to force resolutions. Tooling packages should be free to update as desired rather than as is currently *required*.

I'd propose the following resolution pending any push back from others:

**PROPOSED RESOLUTION**: `fast-tooling`, `fast-tooling-react`, `fast-tooling-wasm`, and `fast-creator` will all move out from this mono-repository following the "next steps" outlined above by @janechu. No changes to other packages at this time.

**Comment by awentzel** [comment]
Additional Pros:
- Testing may be more real as consumption would match that of most customers
- Performance would be improved across both repositories for CI/CD

Additional Cons:
- Working within separate repositories may be cumbersome
- Collaborators may loose some ability to quickly respond to customers as we now technically have two repos between fast and fast-blazor and this adds yet another.  We can overcome this with greater discipline to keep an eye on repositories but it's still a concern.

Marketing Site:
It's located in the mono-repository for convenience and integration with Docusaurus where we manage all of our markdown. Breaking this could complicate how they get built into a single site.  This could be a much larger conversation and I'm not aware of problems that require solved at this time.  If we split this out, then it would behoove us to also re-evaluate all aspects of building documentation and marketing.  For example, could we have a docs.fast.design which is built from markdown?  Could we have marketing just be a simple site built from FAST web components and deployed to www.  This could be one approach to easing how we integrate.

I propose moving the Marketing site topic into its own issue if this is a concern and describing the current problem or challenges it's faced with that we should solve.

Additional Questions: 
- Should this be private/public?  GitHub now supports Private repos for our organization which would allow us to leverage the exact same tooling as the other FAST packages.  ADO isn't in alignment with GitHub Actions yet so anything running there takes additional time and investigation to resolve.
- How/where would documentation be hosted?
- What would change in the process used today?
- What would change in the packages or modules used for building and working with tools?

**Comment by janechu** [comment]
@awentzel 
> Additional Questions:
> 
> * Should this be private/public?  GitHub now supports Private repos for our organization which would allow us to leverage the exact same tooling as the other FAST packages.  ADO isn't in alignment with GitHub Actions yet so anything running there takes additional time and investigation to resolve.

Private for the Creator and public for FAST tooling as noted in the description above.

> * How/where would documentation be hosted?

Nowhere at present, just as it currently is. We do not reference Creator nor do we document FAST tooling in any of the FAST sites as yet.

> * What would change in the process used today?

Which part of the process are you referring to?

> * What would change in the packages or modules used for building and working with tools?

No change for the packages except moving them. The code will remain the same and publish to the same locations.

**Comment by chrisdholt** [comment]
@EisenbergEffect @janechu I think we can close this, yes?

**Comment by EisenbergEffect** [comment]
Yes, indeed.

**Comment by chrisdholt** [comment]
🎉
