### ISSUE TITLE
rfc: Questions on `context.tagFor` in vNext templating

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#4833]
## 💬 RFC
My questions revolve around the upcoming component and design system registration in vNext. Specifically how component dependencies are handled at registration.

## 🔦 Context
I've seen in a few of the vNext components the use of `context.tagFor` when composing other components in a template. An example would be for `Tooltip`. I'm guessing this is for the new registration system for design systems and components and being able to define an element prefix at registration, but I'm not 100% sure.

## 💻 Examples
In `Tooltip`'s case it composes `AnchoredRegion` in its template. I'm guessing when registering the components with a design system it will take the given prefix and the baseName from AnchoredRegion and create the tag name in `Tooltip`'s template, but I haven't had a chance to confirm this.

## Questions
1. Will app authors need to manually register dependencies if the want to use a specific component that uses them, if so what is the best way to communicate to component users that they need to also register other components along with the one they intend to use?
2. If not 1, then do the dependencies automatically get registered using the app author's chosen component prefix, or does it use the default, `fast` in this case?

**Comment by nicholasrice** [comment]
Yes, they will need to manually register dependencies. We'll also be exporting an asset that contains *all* components which can be used.

At this time, dependencies do not get auto-registered and *must* be registered by the app author. I'd like to explore a mechanism to auto-register (or otherwise better communicate dependent elements) because I think that will be an important ergonomic improvement but I don't have details on that yet.

**Comment by KingOfTac** [comment]
Thanks for the comments.

I wonder how much work it would be to add something to `FoundationElement` where components can add references to their dependencies, and then when the `compose` call is made it registers the dependencies. There would need to be checks in place to see if a dependency has already been registered with this method, but I think it could work.

In the short term, I think what I am going to do with my components is just list the dependencies in the documentation and offer a code snippet for registering the component and dependencies.

**Comment by KingOfTac** [comment]
Closing because my questions were answered, and it sounds like @nicholasrice already has some ideas to solve the issues above.

**Comment by nicholasrice** [comment]
Yep, I was thinking something along those lines. As you say, we'll ideally need to make sure we don't re-register elements, nor would we want to register a dependency if the author is about to register the component. Then there is the issue of async registration, so perhaps we need some sort of update mechanism as well. I'm not 100% sure at this point what all the edge cases are so we'll need to do some investigations.

**Comment by KingOfTac** [comment]
I might try to shoehorn in some sort of auto register in my own package and try to identify some of the edge cases. If you do start an implementation in FAST, I'll be sure to comment on my attempt at it.
