### ISSUE TITLE
feat: add Snowpack to/in supported technologies to integrate FAST into

### ISSUE THREAD

**Issue by y330** [microsoft/fast#4836]
# 🙋 Feature Request

Add [Snowpack](https://www.snowpack.dev/) to the libraries FAST can be integrated into.

## 🤔 Expected Behavior

N/A 

## 😯 Current Behavior
Snowpack is an enhancement to the currently supported integrations,  because it is an alternative to heavier, more complex bundlers like webpack that already have FAST integration.

## 💁 Possible Solution

Have a package like `fast-webpack`(FAST integration with Webpack) but with Snowpack instead. As one might guess, the package would be called `fast-snowpack`.

## 🔦 Context

Use of Snowpack in some situations is an advantage compared to using Webpack as a bundler, and being able to use fluent design with it would be excellent.

Read more about Snowpack: [https://www.snowpack.dev/#what-is-snowpack%3F:~:text=Snowpack is a lightning-fast frontend build tool, designed for the modern web. It is an alternative to heavier, more complex bundlers like webpack or Parcel in your development workflow.](https://www.snowpack.dev/#what-is-snowpack%3F:~:text=Snowpack%20is%20a%20lightning%2Dfast%20frontend%20build,matter%20how%20big%20your%20project%20grows.)

**Comment by TenBuck** [comment]
You don't need any plugins to do that, it works out the box. Here's an example with a few plugins
https://github.com/TenBuck/web-snowpack

clone to your desktop, type npm install then npm start.

The style is very rudimental, don't judge.

**Comment by janechu** [comment]
Removing as it appears Snowpack is no longer actively maintained.
