### ISSUE TITLE
fast-data-grid focus incorrect behavior

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4839]
The fast-data-grid component focus behavior should be improved to support two things:

- Disallow focus on any specific fast-data-cell
- Automatically focus on the child component inside the fast-data-cell as focusing on the cell does not give user any value

Issue 1:
In the example below the Multiline text is the localized name of the property that user will enter certain value and it makes no sense to allow uses to focus on it. How we disable focus on specific cells ?

![image](https://user-images.githubusercontent.com/13166236/121057086-c24e2600-c773-11eb-82ff-5992ad5a8189.png)

Issue 2:
If we use the arrow keys to move the focus it comes back to cell and in this case the focus should automatically move to the text field inside the cell as as that is what the user will interact with.

![image](https://user-images.githubusercontent.com/13166236/121057748-78b20b00-c774-11eb-9605-dd1639b9ab2d.png)

**Comment by EisenbergEffect** [comment]
I think this is supported...just maybe not well documented. @scomea can fill in the details.

**Comment by scomea** [comment]
1 - There currently is not a way to make a cell not focusable and I'm not sure that is appropriate for regular grid cells - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role.  I just don't know where focus should go when a cell in the middle of a grid is not focusable and you navigate to it.  Maybe for column header and row header cells which avoid the issue by being on the perimeter, but I'd need to investigate a bit and more importantly add support for row header cells which we don't have yet. 

2 - you can use a column's cellFocusTargetCallback() function to reroute focus to an internal element when the cell gets focus, see our samples for an [example implementation](https://github.com/microsoft/fast/blob/fd6f1dd107c2fcee790b3d5e087f1c3e672191d6/packages/web-components/fast-components/src/data-grid/data-grid.stories.ts#L434).  

You can can also specify that a cell has an internal focus queue with the `cellInternalFocusQueue` column property which enables handling of cells that have multiple focusable elements.  This [pr](https://github.com/microsoft/fast/pull/4775) demonstrates a grid element within a grid cell (the change to support this is about being able to disable grid tabbing when it is a child).

**Comment by chrisdholt** [comment]
Closing this based on @scomea's response above - if there are still gaps here we can dig in and see if it is expected/should be supported. I think one problem with preventing focus on certain cells is that it could create conflicts or issues with Assistive Tech; we are really limited in what we can do given the current support and specifications around grid.
