### ISSUE TITLE
fast-number-field does not increment / decrement for nullable fields

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4840]
Just define a simple number field and try incrementing or decrementing.

`<fast-number-field placeholder="name"></fast-number-field>`

![image](https://user-images.githubusercontent.com/13166236/121059081-e7dc2f00-c775-11eb-9a48-8cd025cc9001.png)

Nothing will happen, the user has to explicitly type in some number first and then the counters will work.

This is not OK, as most languages now support nullable fields and a nullable field will start with a null value and user wants to set it to a number at runtime. 

So for null values the counter should just start from 1. Note I am not saying that the default value is 1, but for null values if user clicks the increment the value should be set to 1 automatically or based on increment step that user defines. Same for decrement.

**Comment by vnbaaij** [comment]
> So for null values the counter should just start from 1.

Should the initial value not be dependent on what is set for the `step` parameter? If step is set to '0.2', initial value should be '0.2' and not '1', agree?

**Comment by ameyasubhedar** [comment]
Yes agreed, that's what i said in my comments above "for null values if user clicks the increment the value should be set to 1 automatically or based on increment step that user defines".

**Comment by vnbaaij** [comment]
Sorry, did not read it thoroughly enough...
