### ISSUE TITLE
Investigate root cause and provide details on solution for SNAT port exhaustion notifications

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4851]
"We’ve detected potential SNAT port exhaustion symptoms   We’ve determined that   5 of your apps across 1 app service plan may be at risk of exhausting preallocated source network address translation (SNAT) ports. This can cause future outages.    Some of the high-risk apps are:   · www-west-app   · create-west-app   · explore-west-app   · color-west-app   Following app service plan was identified at risk:   west-asp   For details of the solution to this issue and a list of all apps at risk, review the step-by-step guidance in the Azure portal."

# 🐛 Bug Report
Need Investigation to determine root cause and solution.

## 🤔 Expected Behavior
There should be no alert for port exhaustion

## 😯 Current Behavior
Note this does not alert daily.  It's more like a monthly scan/alert.

## 💁 Possible Solution

> If you open your App Service and drill into Diagnose and Solve Problems->Availability and Performance->SNAT Port Exhaustion this will be where clues start to add up. If you see SNAT Port Pending or SNAT Ports Failed metrics in here, that’s a good indication you are dealing with SNAT issues.

The solution needs to be about resolving so the error does not happen anymore.  We don't need to configure anything new to monitor it because we're already getting notified.

The solution is about resolving and closing the issue so it stops happening. 

If you are connecting to the same resource over and over, re-use the connection. If you are heavily making outbound calls to something like a REST API and not re-using the connection this will consume excessive SNAT ports 

Additional information
Using a VNet NAT is the best method for outbound connectivity as it is highly scalable, reliable and doesn't have the same concerns with respect to SNAT port exhaustion. 

 

In our scenario, we are using app service and we want to handle global distribution and the best suited for that is AZURE FRONT DOOR. Which can handle inbound and outbound traffic using https. While Application gateway could be the best method for outbound connectivity, it won't support global distribution.  

 

Suggestion: 

Enable application insight to monitor traffic, cpu, memory 

Review application plan 

On front Door look at the metrics, health percentage, request latency 

Log Analytics can perform some query to know what happen at the date of the incident 

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by Ibrahimmaga** [comment]
I have added additional information mostly for suggestion

**Comment by awentzel** [comment]
@Ibrahimmaga I don't understand how adding monitoring solves the problem?  Monitoring is already being used and is why I was notified in email about this issue.  The question I have is what specific cloud infrastructure changes are required to resolve this issue, now or in the future (since it hasn't failed recently).  I'm looking for a detailed solution (step-by-step recipe) to follow.

**Comment by Ibrahimmaga** [comment]
This is the email notification 
![image](https://user-images.githubusercontent.com/14119043/124834257-4b53ab00-df34-11eb-9783-5edc57a152ca.png)
1. The SNAT port Exhaustion is usually related to the outbound call in the backdoor.  If we were using VM, we will think of using loadbalancer or application gateway to resolve SNAT exhaustion.
2. Since we are using app service, the one thing that can create SNAT exhaustion could be related to app service plan. This can be upgraded to premium. 
3. The SNAT Exhaustion never tells where the problem is exactly is. That why I'm suggesting the monitoring step, it could be a memory, cpu, etc. Analyzing metrics could tell us if one of these is the issue. we can use appInsight or azure monitor, and app logs if we want to use kusto query.
4. Here an article that suggests not to look for a fix when it is a warning unless there is a failure. https://devblogs.microsoft.com/premier-developer/reducing-snat-port-consumption-in-azure-app-services/
5. So far. The infrastructure is good using azure front door. If in the feature we add VMs or more resources in the same location, then we will think about adding loadbalancer or App gateway to handle the traffic.

**Comment by awentzel** [comment]
Identified work:  
1.  Create [NAT Gateway](https://docs.microsoft.com/en-us/azure/virtual-network/nat-gateway/nat-gateway-resource) within the existing Virtual Network / Front Door environment. 
2. Create Monitoring for SNAT, available on-demand, triggered, and through nightly emails.

**Comment by chrisdholt** [comment]
@awentzel is this still an open issue?

**Comment by chrisdholt** [comment]
Closing given no feedback on this from the last comment (9 months). If this is still an issue we can reopen and investigate.
