### ISSUE TITLE
fast_dialog modal does not reset old conent

### ISSUE THREAD

**Issue by apsthisdev** [microsoft/fast#4897]
# 🐛 Bug Report

The fast_dialog when used with modal attribute shows the same content or cached content from last state. I believe this is historically an issue with bootstrap dialog as well. And we used to implement js code to clear the modal content on dialog close.

fast_dialog should provide a property e.g. clear="true" that will clear the model content on close so the next show does not show the cached content.

```
<fast-dialog modal="true" hidden="@hidden" style="--dialog-width: auto; --dialog-height: auto">
 </fast-dialog>
```

Visual Studio 2019
Blazor

# Solution
```
<fast-dialog modal="true" clear="true" hidden="@hidden" style="--dialog-width: auto; --dialog-height: auto">
 </fast-dialog>
```

**Comment by chrisdholt** [comment]
This seems odd as the content is fully in the light DOM - can you provide a small repro using stackblitz or similar so we can investigate?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
