### ISSUE TITLE
What happened to accentForegroundCutRestBehavior ? 

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4910]
# 🐛 Bug Report

Since today morning the fast module stopped working, it was working till yesterday  !

The JS code is complaining that accentForegroundCutRestBehavior and accentForegroundCutBehavior is not found.

Please advice asap !

`
import { parseColorString, createColorPalette, neutralLayerCardBehavior, neutralForegroundHintBehavior, neutralForegroundHintLargeBehavior, accentForegroundCutRestBehavior } from "https://unpkg.com/@microsoft/fast-components";
`

```

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The requested module 'https://unpkg.com/@microsoft/fast-components' does not provide an export named 'accentForegroundCutRestBehavior'
      SyntaxError: The requested module 'https://unpkg.com/@microsoft/fast-components' does not provide an export named 'accentForegroundCutRestBehavior'
Microsoft.JSInterop.JSException: The requested module 'https://unpkg.com/@microsoft/fast-components' does not provide an export named 'accentForegroundCutRestBehavior'
SyntaxError: The requested module 'https://unpkg.com/@microsoft/fast-components' does not provide an export named 'accentForegroundCutRestBehavior'
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at PerpetualIntelligence.Shared.Components.Services.JsInteropService.InitDesignSystemProviderAsync() in D:\this\PI\Services\src\PerpetualIntelligence.Web.Shared.Components\Services\JsInteropService.cs:line 110
   at PerpetualIntelligence.Web.Client.App.OnAfterRenderAsync(Boolean firstRender) in d:\this\PI\Services\src\PerpetualIntelligence.Web.Client\App.razor:line 38
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by ameyasubhedar** [comment]
https://unpkg.com/@microsoft/fast-components@2.0.0/dist/fast-components.min.js....

Looks like even the parseColorString and createColorPalette are not found !

**Comment by ben-girardet** [comment]
Do you know which version of fast components is installed in your project ?

Version `2.0.0` came out 2 days ago with some breaking changes. These behaviors have been replaced by `DesignTokens` and some colors method have changed as well. From Discord channel I know that documentation is actively worked on but not yet up to date.

The quickest fix would be to stay on `1.x.x` version of `@microsoft/fast-components` until doc is available and migrate. 

I'll let people from FAST team comment with better instructions soon.

**Comment by ameyasubhedar** [comment]
Thanks, yeah i was just referencing the version independent identifier which defaults to latest in this case 2.0.0. Moved to last good 1.x.x version !

**Comment by EisenbergEffect** [comment]
We're actively working on updates to the documentation. Thanks for your patience!
