### ISSUE TITLE
feat: export @designToken decorator

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4916]
# 🙋 Feature Request
We should export the `@designToken` decorator that we use internally on the DSP so folks can leverage it in their own design-system providers. 

I'd like to find a different approach than we're using (manually assigning a `change` method) because it it will have unanticipated bugs if an author ever adds their own change handler for a decorated property.

Reference: https://github.com/microsoft/fast/pull/4912

**Comment by janechu** [comment]
Due to the up coming deprecation of `@microsoft/fast-foundation` per #6955 this issue no longer seems relevant.
