### ISSUE TITLE
feat: add composer field to the product of `FoundationElement.compose()`

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#4922]
# 🙋 Feature Request
`FoundationElement` exposes a static method `compose` to compose a custom element definition to be registered with the application's `DesignSystem` by app authors.

Authors are also able to compose function stylesheets and templates with `FoundationElement` components, allowing runtime retrieval of information about registered components, such as tag name. However, retrieving an element's tag name requires an implicit knowledge of the class that composed a definition:

```ts
// There is an implicit relationship between these two, which authors must be aware of to get the compsoed
// tag name for the element.
class MyElement extends FoundationElement {}
const myElementDefinition = MyElement.compose({baseName: "my-element"});


// To register the component, authors use the definition
DesignSystem.register(myElementDefinition());

// To retrieve the tag name, authors use the class itself
const myOtherElementTagName(context) => {
  const tag = context.tagFor(MyElement);
}
```

## 💁 Possible Solution
I'm proposing that the definition function returned from `FoundationElement.compose()` be augmented with a `composer` property that references the class that composed the definition. The above code example could then become the following, removing the implicit relationship:

```ts
// ...
const myOtherElementTagName(context) => {
  const tag = context.tagFor(myElementDefinition.composer);
}
```

We could even teach `DesignSystem` how to retrieve tags for definition functions, minimizing the above to:
```ts
// ...
const myOtherElementTagName(context) => {
  const tag = context.tagFor(myElementDefinition);
}
```

## Why?
The primary benefit for this feature would be to facilitate using library components by app authors in custom element templates. Rather than hard-coding the element name, authors could programmatically determine the name and guard against configuration changes. 

It could also be used *by* library authors, where a library component depends on a component from *another* library.

**Comment by EisenbergEffect** [comment]
Closing this since we're moving away from the `compose` APIs in the future.
