### ISSUE TITLE
docs: fix data-grid.spec.md cellTemplate example

### ISSUE THREAD

**Issue by xbb** [microsoft/fast#4937]
`columnData` here should be `columnDefinition`

https://github.com/microsoft/fast/blob/abe74acdb97008602fdf8193722388dbe454787f/packages/web-components/fast-foundation/src/data-grid/data-grid.spec.md#L99-L110

Thanks!

**Comment by EisenbergEffect** [comment]
Ping @scomea looks like a quick and easy fix.

**Comment by m4thieulavoie** [comment]
Would love to contribute a fix on this one! 👍

**Comment by chrisdholt** [comment]
Assigning @scomea for the quick fix
