### ISSUE TITLE
fix: base class discovery in context.tagFor()

### ISSUE THREAD

**Issue by m4thieulavoie** [microsoft/fast#4941]
# 🐛 Bug Report

[More detail here](https://discord.com/channels/449251231706251264/482296787021856768/862336132255842334)

Maybe a bit of a far-fetched issue, but for each of our components we apply a mixin to them. What that effectively means is that for example, instead of creating an `AnchoredRegion`, we create a `CustomAnchoredRegion`. With the new v2 release, this line doesn't resolve.

```
<${context.tagFor(AnchoredRegion)}
```

I would like to propose a new argument `baseClass` for the `compose()` method that would take the actual FAST base class.
Another idea could also be to have a fallback if `tagFor` returns undefined that would try `basePrefix-component-name` ?

## 💻 Repro or Code Sample

No repro, can always provide one if needed

## 🤔 Expected Behavior

FAST should resolve the base class, no matter how many mixins there are in the way

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
closed w/ #4943
