### ISSUE TITLE
Help needed: how to bind directive to a viewtemplate/html`` after it's built

### ISSUE THREAD

**Issue by chandde** [microsoft/fast#4945]
Sorry for the abuse of the repo, please let me know if there is a more appropriate place that I can ask this question.

Usually when we bind a directive to a view template, we have full control to its internal, e.g.
```js
html`
    <my-web-component
        ${someBindingCall( ...some params ) }
        ... other props
    />`
```
however, is it possible to attach the binding when the view template has been created? e.g. all I got is the x below, I have no access to its internal, can I still bind something to x? 
```js
const x = html`
    <my-web-component
        ... other props
    />`;
x.someBindingCall(); ?
someBindingCall(x); ??
```

**Comment by janechu** [comment]
Closing this as I don't believe we have plans to enable an after-the-fact binding.
