### ISSUE TITLE
fix: Default value of element overrides default value in component in Vue 3

### ISSUE THREAD

**Issue by MatusT** [microsoft/fast#4950]
# 🐛 Bug Report

I tried using fast-slider in my Vue 3 project. Apparently, fast-slider calls @change in Vue 3 with its default value (0.5) at the start of the project/component load.

## 💻 Repro or Code Sample

1. Create some data in component in Vue 3 like this:
```
export default defineComponent({
  data() {
    return {
      backgroundColor: { r: 0.0, g: 0.0, b: 0.0, a: 1.0 },
    };
  },
});
```
2. Create an 2-bind fast-slider like this:
```
      <fast-slider
        min="0.0"
        max="1.0"
        step="0.01"
        v-bind:value="backgroundColor.r"
        @change="backgroundColor.r = $event.target.value"
      ></fast-slider>
```
3. The value of backgroundColor.r will be 0.5 instead of 0.0. 

I am providing entire project stripped down to just this issue.

[replicate.zip](https://github.com/microsoft/fast/files/6797441/replicate.zip)

## 🤔 Expected Behavior

fast-slider should not call change unless user touches the slider

## 😯 Current Behavior

fast-slider calls change with its default value

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Google Chrome/Edge
* Version 2.1

**Comment by EisenbergEffect** [comment]
Sounds like a definite bug. The slider was an earlier component we implemented and may not have been updated to properly handle this. @marjonlynch Did you do the original implementation? Are you able to take a look when you are available?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
