### ISSUE TITLE
fix: Unable to slot fluent-option in fluent-select

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/fast#4952]
# 🐛 Bug Report

I cannot add a slot inside a `fluent-select` component e.g.

## 💻 Repro or Code Sample

My Component
```html
<div>
  <fluent-select>
    <slot name="menu"></slot>
  </fluent-select>
</div>
```

My Component Usage
```html
<my-component>
  <fluent-option slot="menu" value="s">Small</fluent-option>
  <fluent-option slot="menu" value="m">Medium</fluent-option>
  <fluent-option slot="menu" value="l">Large</fluent-option>
  <fluent-option slot="menu" value="xl">Extra Large</fluent-option>
</my-component>
```

## 🤔 Expected Behavior

In theory the `fluent-select` should continue to work.

## 😯 Current Behavior

The selection is not working.
![Animation](https://user-images.githubusercontent.com/2270364/125308582-eda2d280-e328-11eb-8cc3-5d59b0255bf0.gif)

* OS & Device: Windows
* Browser Microsoft Edge
* Version: Canary

**Comment by EisenbergEffect** [comment]
@RehanSaeed Thank you for the repro and the animate gif! My guess is that the selection logic is not implemented to handle the option elements existing as a child of another element. Probably, an improvement would be to re-work that logic against the select's default slot assigned nodes. I'm tracking this as an improvement for us to look into.

/cc @radium-v

**Comment by chrisdholt** [comment]
> @RehanSaeed Thank you for the repro and the animate gif! My guess is that the selection logic is not implemented to handle the option elements existing as a child of another element. Probably, an improvement would be to re-work that logic against the select's default slot assigned nodes. I'm tracking this as an improvement for us to look into.
> 
> /cc @radium-v

I agree we can likely support this so long as we focus on this scenario rather than supporting options as *any* nested child. Currently, I believe there is expected structure for a combobox and we should investigate prior to going further than supporting a slot which can project via another control. @EisenbergEffect this seems like a potential common issue; should we look at handling this in a more cross-cutting way? I could see this being a similar pattern with button, anchor, options, etc...:

```html
<my-component>
     <slot name="start"></slot>
     <slot></slot>
     </slot name="end></slot>
</my-component>
```

**Comment by EisenbergEffect** [comment]
I'm not sure yet if there's anything we would do at the fast-element level for this. We need to look into how the `select` is finding options. For example, is it trying to look at `children` or is it looking at the `slot`. If it's looking at `children`, then this scenario definitely wouldn't work, for example. So, this might be a set of internal changes in the individual component implementations to make sure they are getting slotted elements specifically.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
