### ISSUE TITLE
bug: multiple failure on CD-Fast (cd-www-stage.yml)

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#4962]
# 🐛 Bug Report

This bug is currently preventing deployment updates to https://stage.www.fast.design as it’s breaking the pipeline at this time for CD.
* first error occurred 3 days ago, the install dependencies task was looking for playwright modules: error /home/runner/work/fast/fast/node_modules/playwright
* the second run was canceled manually
* Third and last failure is in build&Prepare web application. Possible location of failure "tutorials/site-rebrand "
## 💻 Repro or Code Sample

Link to the first example that failed after previous success.  https://github.com/microsoft/fast/runs/3050818223?check_suite_focus=true 

![Screen Shot 2021-07-16 at 6 11 24 AM](https://user-images.githubusercontent.com/16669785/125953362-391200e4-b127-4894-9de0-5d32bc6b2288.png)

## 🤔 Expected Behavior
* cd-fast pipelines should not fail

## 😯 Current Behavior
* Failure 

## 💁 Possible Solution
* investigate the cause for failure

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by awentzel** [comment]
**Additional Details:**
_Confirmed_:  Error occurs when running yarn build on ./sites/fast-website/ I'm not familiar with this code and would appreciate code ownership help here.

**Repro** 
1. yarn install --frozen-lockfile
2. cd sites/website 
3. yarn install 
4. yarn build

**notes:**
1. fast-website has conflicting re-exports on rollup which does seem to resolve, build, and run the home page.
2. website fails on build and start scripts.

<img width="2852" alt="Screen Shot 2021-07-16 at 7 44 03 AM" src="https://user-images.githubusercontent.com/16669785/125970139-9c96bfa7-386e-43d7-b447-c9cc086ccc77.png">

**Comment by chrisdholt** [comment]
@awentzel I'll work on repro'ing and tracking this down a bit today if I can

**Comment by chrisdholt** [comment]
It seems like there is an issue with API extractor and API documenter here. I'm a bit stumped as it shows both of these having been solved, and while there is a warning that the `(DesignToken:interface)` is ambiguous...it's not - it's specifically calling out `interface`.

**Comment by nicholasrice** [comment]
I think the `(DesignToken:interface)` comments are a red herring. I just ran the repro steps on the v2 commit w/ those doc comments and everything worked fine. I'll track down the specific commit that caused the issue and go from there.

**Comment by nicholasrice** [comment]
https://github.com/microsoft/fast/commit/3a9f152446a1a9e0afd6fd84c808eba46839aeeb is the first commit that repros the error, so it is something introduced there.
