### ISSUE TITLE
feat: add searchbox component

### ISSUE THREAD

**Issue by LisavB** [microsoft/fast#4967]
# 🙋 Feature Request

A search box component to allow users to search through data.

## 🤔 Expected Behavior

Similar to that of the Microsoft fluent UI search box (https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox)

## 😯 Current Behavior

Does not currently exist.

## 💁 Possible Solution

`<fast-search-box></fast-search-box>`

**Comment by chrisdholt** [comment]
@eljefe223 is going to investigate what "Search" may look like as a component.
