### ISSUE TITLE
fix: slotted content in combobox options

### ISSUE THREAD

**Issue by bennypowers** [microsoft/fast#4978]
# 🐛 Bug Report

When I slot some content into a combobox option, then choose it, I'd expect to see only the label content, not the slotted content, in the box

## 💻 Repro or Code Sample

```html
<fast-combobox autocomplete="both" id="country" value="">
      <fast-option value="AD">Andorra
        <span slot="start">🇦🇩</span>
      </fast-option>
      <fast-option value="AE">United Arab Emirates
        <span slot="start">🇦🇪</span>
      </fast-option>
      <fast-option value="AF">Afghanistan
        <span slot="start">🇦🇫</span>
      </fast-option>
      <fast-option value="AG">Antigua and Barbuda
        <span slot="start">🇦🇬</span>
      </fast-option>
      <!-- etc -->
</fast-combobox>
```

## 🤔 Expected Behavior

Typing `United` into the combobox then hitting <kbd>Enter</kbd>, I expect to see `United Arab Emirates` in the text field

## 😯 Current Behavior

Instead, I see `United Arab Emirates         🇦🇪` Note also the extra whitespace. If I padded the start of the content of `<fast-option>` at all, that would break the typeahead search feature (unless for some reason i started typing spaces into the field) 

<img width="211" alt="Screen Shot 2021-07-21 at 22 40 28" src="https://user-images.githubusercontent.com/1466420/126549754-d6572efa-68d9-424d-b621-2b82c24c2782.png">

## 🔦 Context

The primary case for this particular combo box is a typeahead search, in which case I want to see only the searchable text

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
