### ISSUE TITLE
feat: add SnackbarComponent

### ISSUE THREAD

**Issue by mecirmartin** [microsoft/fast#4981]
# 🙋 Feature Request

I would like to have snackbar Fast component to use in my applications

## 🤔 Expected Behavior
I imagine it could work something like this 

https://github.com/material-components/material-components-web-components/tree/master/packages/snackbar

## 😯 Current Behavior

This component doesn't currently exist

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
