### ISSUE TITLE
fix: update displayed selected value in select component when an option changes

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#4982]
# 🐛 Bug Report

Given a Select component:

```html
<fast-select>
    <fast-option>This option has no value</fast-option>
    <fast-option disabled>This option is disabled</fast-option>
    <fast-option value="hi">This option has a value</fast-option>
    <fast-option selected>This option is selected by default</fast-option>
</fast-select>
```

If the `innerHTML` of the selected option changes, the displayed value of the select component should reflect the change.

## 💻 Repro or Code Sample

In the current storybook of Select, you can repro by:

```html
<!-- base.html -->
<fast-select>
    <fast-option>This option has no value</fast-option>
    <fast-option disabled>This option is disabled</fast-option>
    <fast-option value="hi">This option has a value</fast-option>
    <fast-option selected class="test">This option is selected by default</fast-option> <!-- add the test class -->
</fast-select>
```

```ts
// select.stories.ts

// add the following lines at the end:
setTimeout(() => {
    (document.querySelector('.test') as HTMLElement).innerHTML = 'Hello world';
}, 1000);
```

End result will look like:

<img width="311" alt="Capture d’écran 2021-07-22 à 21 24 16" src="https://user-images.githubusercontent.com/4275071/126697765-c724a015-442b-4b1c-9ddc-4069efe92a06.png">

where the displayed selected option still displays the "old" innerHTML of the selected option.

## 🤔 Expected Behavior

I'm expecting the change of the option (if it's the one selected) to be reflected in the display of the select. It seems a little "edge case" but this happens in my case with i18n issue which is very important. When a user changes the locale of the website, the localized texts are all automatically changes in realtime, and this should be reflected in the selected option.

## 🔦 Context

As mentioned before, the context is when changing locale in a website or web-application. When a user changes the locale, the localized texts are all automatically changes in realtime, and this should be reflected in the selected option.

## 🌍 Your Environment

Fast Components 2.3.0

**Comment by chrisdholt** [comment]
@radium-v can you take a look and see what options we have here and what potential issue may exist?
