### ISSUE TITLE
Add support for specifying the document to which fast stylesheets should attach

### ISSUE THREAD

**Issue by ShailyTyagiBlack-dev** [microsoft/fast#4985]
I am trying to use Fast component inside an iframe which lies in a main document. When i do that, the styles generated by FAst for that component get attached to the head of main document by default and they don't flow through ifarme - none of the iframe styles are applied to the component due to this - if e can spcify the document wth the component then the generated styles should get attched to the supplied document

**Comment by nicholasrice** [comment]
This issue appears to concern the `@microsoft/fast-jss-manager-react` package which no longer exists in this repository. The package itself is deprecated & no longer supported. For those reasons I'm going to close this out.
