### ISSUE TITLE
docs: fix class name to integrations/react and question for vscode intellisense

### ISSUE THREAD

**Issue by lesomnus** [microsoft/fast#4989]
# 🙋 Documentation Request

In section [Using the componenets](https://www.fast.design/docs/integrations/react#using-the-components), the provided code imports `FASTCard` or `FASTButton` but it should be `fastCard` or `fastButton`.

# 💁 Question

I got this error:
```
Property 'fast-design-system-provider' does not exist on type 'JSX.IntrinsicElements'.
Property 'fast-card' does not exist on type 'JSX.IntrinsicElements'.
...
```

I read this solution:
```
// custom-elements.d.ts
declare namespace JSX {
    interface IntrinsicElements {
        /**
         *  React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> allows setting standard HTML attributes on the element
         */
        "my-element": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
            "my-attribute-name": string;
        };
    }
}
```

Do I have to write all the intrinsics for the fast-components?
Or, is my `tsconfig.ts` worng?
```json
{
	"extends": "@tsconfig/node16/tsconfig.json",
	"compilerOptions": {
		"lib": [
			"DOM"
		],
		"jsx": "react",
		"experimentalDecorators": true,
		"sourceMap": true
	},
	"include": [
		"src"
	]
}
```

**Comment by nicholasrice** [comment]
You'll need to extend the `IntrinsicElements` interface for all custom elements you use in TSX files (including FAST components). Doing so informs TypeScript what attributes can be applied to the element.

The `FASTCard` vs `fastCard` issue you're seeing should be resolved shortly; The changes have already been made to the doc files, we're just awaiting site publishing.

Going to close this out, but feel free to re-open if the above doesn't sufficiently answer your questions.
