### ISSUE TITLE
chore: audit production sites with lighthouse from dev tools

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#5014]
# 🙋 Feature Request

Lighthouse is an automated quality assurance tool for websites. It rates your website in terms of search engine optimization (SEO), performance and other categories. It’s open-source and maintained by Google.

Lighthouse is run against individual pages of a website. After Lighthouse has been run a report is generated.

Lighthouse runs tests for each category. In each category, it runs a series of audits. An example is the ‘Properly sized images’ audit in the ‘Performance’ category.

<h2>Lighthouse performance calculator</h2>

<html>
<body>
<h3 id="lighthouse-8" style="box-sizing: border-box; color: rgb(32, 33, 36); margin: 48px 0px 16px; overflow: visible; font: 500 20px / 1.2 &quot;Google Sans&quot;, sans-serif; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Lighthouse 8<span> </span><a href="https://web.dev/performance-scoring/?utm_source=lighthouse&amp;utm_medium=devtools#lighthouse-8" class="w-headline-link" style="box-sizing: border-box; color: transparent; text-decoration: underline; display: inline; font-weight: 500; margin-left: 4px;">#</a></h3><div class="w-table-wrapper" style="box-sizing: border-box; margin: 0px 0px 32px; padding: 0px; overflow: auto; background: linear-gradient(to right, rgb(255, 255, 255) 30%, rgba(255, 255, 255, 0)) 0px 0px / 40px 100% no-repeat local, linear-gradient(to right, rgba(255, 255, 255, 0), rgb(255, 255, 255) 70%) 100% center / 40px 100% local, radial-gradient(farthest-side at 0px 50%, rgba(0, 0, 0, 0.2), transparent) 0px 0px / 14px 100% scroll, radial-gradient(farthest-side at 100% 50%, rgba(0, 0, 0, 0.2), transparent) 100% center / 14px 100% scroll rgb(255, 255, 255); color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, system-ui, -apple-system, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Audit | Weight
-- | --
First Contentful Paint | 10%
Speed Index | 10%
Largest Contentful Paint | 25%
Time to Interactive | 10%
Total Blocking Time | 30%
Cumulative Layout Shift | 15%

</div>
</body>
</html>

<h3>The metrics scores and the perf score are colored according to these ranges:</3>

. 0 to 49 (red): Poor
. 50 to 89 (orange): Needs Improvement
. 90 to 100 (green): Good
To provide a good user experience, sites should strive to have a good score (90-100). A "perfect" score of 100 is extremely challenging to achieve and not expected. For example, taking a score from 99 to 100 needs about the same amount of metric improvement that would take a 90 to 94.

## 🤔 Expected Behavior

none
## 😯 Current Behavior

none
## 💁 Possible Solution

any monitoring tool 
## 🔦 Context

**There are 5 categories in a report. The categories are:**

1. SEO: It checks whether the page has a title tag, a meta description, and other SEO best practices
2. Performance: Focus is on how fast the page loads and how quickly the user can interact with the page
3. Accessibility: The audits check the use of HTML attributes, that help screen readers understand the contents of the page, color contrasts, and font sizes.
4. Best practices: This category checks whether the page is compliant with ‘progressive web app’ standards.
5. PWA: In Branch, you can automatically run Lighthouse using the Lighthouse recipe. You can specify which URL’s to test and what scores you expect to see.

**Comment by chrisdholt** [comment]
I'd love to see a more robust call out to *why* this would be proposed to be added, what problem is it solving, what is the amount of work to maintain - what are the other solutions called out in "solutions", etc...

Keeping this in the backlog, but I do think this needs more information.

**Comment by awentzel** [comment]
@chrisdholt, only involves running the Edge Developer Tools feature named 'Lighthouse' to discover additional areas of improvement for our public-facing hosted websites.  In particular, I'm interested in PWA, Performance, and SEO optimization. We achieve higher page rankings, and when those interested in FAST come to our website, they see a picture-perfect model of building web solutions.  I'm less interested in what's revealed in Accessibility because I know Brook and you are working on those areas well before what's technically possible in today's accessibility tools.

Sites included in this analysis:
- https://www.fast.design
- https://explore.fast.design
- https://create.fast.design
- https://color.fast.design 

Nothing is being added to the source code at this time.

**Comment by chrisdholt** [comment]
> @chrisdholt, only involves running the Edge Developer Tools feature named 'Lighthouse' to discover additional areas of improvement for our public-facing hosted websites. In particular, I'm interested in PWA, Performance, and SEO optimization. We achieve higher page rankings, and when those interested in FAST come to our website, they see a picture-perfect model of building web solutions. I'm less interested in what's revealed in Accessibility because I know Brook and you are working on those areas well before what's technically possible in today's accessibility tools.
> 
> Sites included in this analysis:
> 
> * https://www.fast.design
> * https://explore.fast.design
> * https://create.fast.design
> * https://color.fast.design
> 
> Nothing is being added to the source code at this time.

Thanks for the clarification - I think this goes to my primary request for clarification. The above provides context of what the ask is: "Audit the sites using lighthouse". The initial issue doesn't really go into detail about what the actual request is, it simply reiterates what lighthouse is and what the report *does*. What would be helpful is the context you're providing. "Run an audit of all prod sites across lighthouse and identify issues and opportunities for improvement. Target areas include...." 

Your context is super helpful, if we can update the issue to reflect the work planned and the intent and the outcome that would help ensure we can triage properly.

**Comment by awentzel** [comment]
@Ibrahimmaga please update this issue with the specific new issues on GitHub you created which Lighthouse has identified for which we should add to the backlog for future fixing.  This issue should simply identify the future work items.

**Comment by Ibrahimmaga** [comment]
This is the Audit Result: we have already discussed the plan for improvement, but no action has been taken yet. 

![image](https://user-images.githubusercontent.com/14119043/134987813-7277aa8b-90bb-4d3d-9a74-850c3074e25d.png)

**Comment by awentzel** [comment]
The actual status here is that there are some issues getting this GitHub Action to work appropriately.  We are investigating two different GH Actions for Lighthouse command line integration on the CI.  We will report back soon.

**Comment by awentzel** [comment]
The audit has been completed.  We know where improvements could be made. But, they are acceptable at this time so no more action from the audit is required.
