### ISSUE TITLE
feat: add Coachmark/TeachingBubble Components to fast

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/fast#5025]
# 🙋 Feature Request

Our team (Edge New Tab Page) could really use these two components for a first run experience:

- [Coachmark](https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark)
- [TeachingBubble](https://developer.microsoft.com/en-us/fluentui#/controls/web/teachingbubble)

## 💁 Possible Solution

I'm currently thinking I can hack the Dialog component or roll something custom to get something similar in the short term.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
