### ISSUE TITLE
fix: adding a new tab on the official web page throws errors in the available list of components

### ISSUE THREAD

**Issue by UtmostCreator** [microsoft/fast#5041]
# 🐛 Bug Report

Preconditions:
You are using chrome or firefox (other browsers not tested)

Steps to reproduce:
1. Go to existing Fast-UI components [web page](https://explore.fast.design/components/fast-tabs);
2. Try to add a new tab [see the code example below - can be copied].

## 💻 Repro or Code Sample
Open 
```html
<fast-tabs>
    <fast-tab slot="tab">Tab one</fast-tab>
    <fast-tab slot="tab">Tab two</fast-tab>
    <fast-tab slot="tab">Tab three</fast-tab>
    <fast-tab slot="tab">Tab four</fast-tab>
</fast-tabs>
```

## 🤔 Expected Behavior
After adding a new tab no errors should be thrown.

## 😯 Current Behavior
After adding a new tab errors are thrown.
Error on the screenshot [left side - firefox log; right side - chrome log]:
![image](https://user-images.githubusercontent.com/22347676/128594599-33e81fa2-05f7-4399-9c99-83656c1154e4.png)

## 💁 Possible Solution

Check how the HRM module works. check JS code that alters it.

## 🔦 Context

I can not test many tabs on the official [web page](https://explore.fast.design/components/fast-tabs)

## 🌍 Your Environment

* OS & Device: Windows 10 2h21
* Browser [Google Chrome Version 93.0.4577.25, Mozilla FireFox 90.0.2]
* Version not sure [the one which is on the  [web site](https://explore.fast.design/components/fast-tabs), probably the latest]

**Comment by UtmostCreator** [comment]
Same thing is happens in some other components (e.g. accordion)
Also, if you add multiple buttons in the component ([button](https://explore.fast.design/components/fast-button), it throw another error):
![image](https://user-images.githubusercontent.com/22347676/128594920-e2e4461a-6710-41ce-a125-907bcac53c2c.png)

**Comment by EisenbergEffect** [comment]
@janechu I think this might be a bug in the explorer. Can you take a look? If it's not in the tools, let me know and we'll kick it over to the components team. Thanks!
