### ISSUE TITLE
fix: vertical mode in slider in the @microsoft/fast-components package

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#5054]
# 🐛 Bug Report

For LTR languages I would expect that slider would place the minimum value at the bottom of the range and the maximum value at the top. This appears to be inverted. I do not know what I would expect for RTL, but it also appears that those values are inverted when switching.

## 💻 Repro or Code Sample

Code:
![Screen Shot 2021-08-11 at 11 26 28 AM](https://user-images.githubusercontent.com/7559015/129083321-63cc2558-7109-4968-a0e3-80920d04359b.png)

LTR vertical result:
![Screen Shot 2021-08-11 at 11 26 22 AM](https://user-images.githubusercontent.com/7559015/129083342-3071711d-a7c5-48dc-a350-4edd6252d50b.png)

RTL vertical result:
![Screen Shot 2021-08-11 at 11 26 43 AM](https://user-images.githubusercontent.com/7559015/129083335-24d2cb26-13a7-4cdb-8fc9-b3adebc4cc89.png)

## 🤔 Expected Behavior

I would expect the current result for LTR to be the RTL and vice versa.

**Comment by chrisdholt** [comment]
Thanks for this @janechu, definitely something to address!

I did have one question - would we expect changes here for RTL/LTR for vertical or would you expect it to be the same given the vertical orientation. I think for vertical orientations I expect it to be the same.

**Comment by eljefe223** [comment]
this appears to be fixed, but the minimum value remains top. Based on what I'm seeing elsewhere I think @janechu is right. the minimum should be at the bottom.
