### ISSUE TITLE
feat: add height and width customization (css prop) to tab's activeIndicator in  fluentui/webcomponents 

### ISSUE THREAD

**Issue by vogtn** [microsoft/fast#5058]
# 🙋 Feature Request

We would like to further customize the active indicator as part of the tabs control, specifically the [height](https://github.com/microsoft/fast/blob/6de6117945e9624ae07a22eafaf5fda879ff6a1a/packages/web-components/fast-components/src/tabs/tabs.styles.ts#L58) or width to fit our designs. 

![tab](https://user-images.githubusercontent.com/11411686/129415462-23d8e7ad-ab41-426f-bb41-ee63608cdcbc.png)

## 🤔 Expected Behavior

![image](https://user-images.githubusercontent.com/11411686/129415712-02d9b9a5-5cd6-40e6-a92e-2293602e61e2.png)

## 😯 Current Behavior

![tab](https://user-images.githubusercontent.com/11411686/129415823-18a541cd-7128-4cd1-8454-8a9df13216ff.png)

## 💁 Possible Solution

Ideally a css property like:
```css
 fluent-tabs {
--active-indicator-height: 1px; 
}
```

## 🔦 Context

For screenshots of our project designs and the activity indicator we'd like:
https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1199#issuecomment-884992385

**Comment by chrisdholt** [comment]
Thanks for the issue @vogtn! Have you considered using CSS and targeting the part attribute to customize this?

**Comment by vogtn** [comment]
@chrisdholt 

Thanks chris, that works even better! Works for us, feel free to close this issue then.

**Comment by chrisdholt** [comment]
> @chrisdholt
> 
> Thanks chris, that works even better! Works for us, feel free to close this issue then.

Awesome, sounds good!
