### ISSUE TITLE
Ajust the CSP to allow for user image uploading to browser cache on Creator

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#5066]
# Description

Images should be able to be referred to when they have been uploaded from the user and stored in their local browser.

## Requirements

- Adjust the CSP (content security policy) to allow 'self' and possible 'blob'

**Comment by williamw2** [comment]
"blob" has been added to the CSP and images appear to be working as expected now in stage.create.fast.design.
Closing this issue.
