### ISSUE TITLE
fix: Start/end slots cannot be populated with default value in FoundationElementDefinition

### ISSUE THREAD

**Issue by scotia673** [microsoft/fast#5116]
# 🐛 Bug Report

Unlike slots defined within given components, it does not appear to be possible to populate the [start/end slots](https://github.com/microsoft/fast/blob/e498f1e35232169d2bf80e366350d0cde812d76d/packages/web-components/fast-foundation/src/text-field/text-field.template.ts#L79) with default values when using `compose` to register a component.

## 💻 Repro or Code Sample

N/A - the behavior I'm expecting isn't supported. I'm filing this as a bug instead of a feature request because I'd assume that all slots being accessed the same way is desirable, but feel free to move this to a feature request if that feels like a better fit.

## 🤔 Expected Behavior

I was expecting to be able to populate the end slot with default content using an approach in `compose` similar to the `checkedIndicator` in the [checkbox component](https://github.com/microsoft/fast/blob/e498f1e35232169d2bf80e366350d0cde812d76d/packages/web-components/fast-components/src/checkbox/index.ts#L21), as an example.

## 😯 Current Behavior

I am able to populate the end slot from within the `connectedCallback` in my component using `this.end.innerHTML`, but this doesn't feel as clean.

## 💁 Possible Solution

Add support in the [start/end templates](https://github.com/microsoft/fast/blob/062b6642246a8bf54a1371daeee4328660672f3f/packages/web-components/fast-foundation/src/patterns/start-end.ts#L33) to provide a default value via the `definition` object used in a given component's template and add these items to the FoundationElementDefinition.

## 🔦 Context

In my case, I am adding an icon to the text-field component (a component we're building which extends the `FoundationTextField`) that is displayed when the text field is in an invalid state.

## 🌍 Your Environment

* OS & Device: MacOS
* Browser Google Chrome
* Version 92.x

**Comment by scotia673** [comment]
Thanks for the quick turnaround on this @chrisdholt ! I'll plan to uptake this change and try it out as soon as it's published.

**Comment by chrisdholt** [comment]
> Thanks for the quick turnaround on this @chrisdholt ! I'll plan to uptake this change and try it out as soon as it's published.

Should publish this evening on the cron - let us know how it goes!

**Comment by scotia673** [comment]
@chrisdholt , I just tested and it works like a charm. Nice work - thanks again!
