### ISSUE TITLE
fix: Programmatic focus in Firefox

### ISSUE THREAD

**Issue by jumarroq** [microsoft/fast#5121]
# 🐛 Bug Report

Calling "focus" on web components does not always work the same as it does on Chrome or Edge Chromium. This seems to depend on how nested the component is and repros when circumventing FAST code by directly calling focus on the button you want to have focused.

## 💻 Repro or Code Sample

Have yet to find this repro in the FAST repo. This has been first seen in Firefox using this URL: https://www.msn.com/en-us/feed?ocid=windirect&pcsonly=true&item=flights%3Anone&item=spalink%3Alatest%2Fdebug

Find a card in the river
Select "Fewer Stories like this" under the card action menu. 
![image](https://user-images.githubusercontent.com/68871578/131374238-c320d44e-e772-4bc9-8418-33b7c26f3680.png)
"Not interested in this story" should be focused like in Edge, but instead focus is set to the browser.
![image](https://user-images.githubusercontent.com/68871578/131374311-610c3a5e-c160-428d-b70c-c285eb61b4ee.png)

## 🤔 Expected Behavior

After selecting Fewer Stories like this, the first button should have focus set to it:
![image](https://user-images.githubusercontent.com/68871578/131374515-bf6f1912-6688-4e3e-894f-2c5784e23502.png)

## 😯 Current Behavior

Focus is set to the browser instead of to the button.

## 💁 Possible Solution

Looks to be a browser difference with Firefox and perhaps how it handles shadow dom and focus. I was able to take our code out of the equation by setting focus on the button manually using setInterval(() => {button.focus()}, 500), which actually changed the behavior but didn't totally fix the issue. With that, the card itself was receiving focus every 500ms, but not the button. If I hit tab, I would go into the card and then the button would always get focused properly every 500ms. It's as if Firefox didn't know the button was there until I entered it. Before and after that the chain of activeElements (going through the shadow DOM) looked the same.

## 🌍 Your Environment

* Windows 10
* Browser [FireFox]
* Version [91]

**Comment by chrisdholt** [comment]
Thanks @jumarroq.

@EisenbergEffect could this be related to delegatesFocus not being fully supported? It seems odd that focus would move the the *window* though...

**Comment by EisenbergEffect** [comment]
I do agree that the browser focus is unexpected, but maybe that's what FF does when it doesn't know what to do? I seems like it could be related to delegatesFocus but I'm not sure.

**Comment by jumarroq** [comment]
I think the browser focus might be a more extreme case that might be exacerbated by the hide card's code. I mention in the bug description that manually focusing using the debugger produces a different, less extreme behavior.

I think a more typical example would be the settings gear:
![image](https://user-images.githubusercontent.com/68871578/131406560-19b59aa1-6c34-4be9-930a-a6807a5e6b40.png)
Here if the user tabs they do get to the close button instead of the start of the page. In Edge, the close button would automatically get focused, not requiring an extra "tab" to focus.

I'll see if I can get the browser focus scenario to not be as broken and instead just require the extra tab to navigate to the right place.

**Comment by jumarroq** [comment]
@chrisdholt @EisenbergEffect I found something significant. The Fast button doesn't properly get focused when you call focus on it. You can check the Fast Components storybook. In the "Button" section, the auto focus button doesn't get focus automatically, but it does in Edge/Chrome. I tested manually calling focus on the web component and that doesn't work, but manually calling focus on the internal button does.

I'll start looking into the internals where focus is defined.

**Comment by chrisdholt** [comment]
> @chrisdholt @EisenbergEffect I found something significant. The Fast button doesn't properly get focused when you call focus on it. You can check the Fast Components storybook. In the "Button" section, the auto focus button doesn't get focus automatically, but it does in Edge/Chrome. I tested manually calling focus on the web component and that doesn't work, but manually calling focus on the internal button does.
> 
> I'll start looking into the internals where focus is defined.

I’d start with delegatesFocus.

**Comment by jumarroq** [comment]
@chrisdholt @EisenbergEffect When I set delegatesFocus: false, calling focus on the fast-button causes Edge to behave the same as FireFox does when delegatesFocus is true or false. So seems to me that this is the root cause.

We can work around this by adding a "focus" function that calls the internal button element's focus function. That works for the dialog scenario, but obviously isn't ideal.

**Comment by scomea** [comment]
> We can work around this by adding a "focus" function that calls the internal button element's focus function. That works for the dialog scenario, but obviously isn't ideal.

Seems a viable approach to me.  Adding this to button fixed my local repro:

`public focus(): void {this.control?.focus();}`

Needs more testing though.   Would it break anything?

**Comment by jumarroq** [comment]
Another proposal my manager had was to add some logic to traverse the children and find the first focusable node to fix this for all scenarios, but that seems fragile to me and I think has the same problems we had with trapping focus in the Dialog where it's just not trivial to find everything that's focusable.

**Comment by chrisdholt** [comment]
I think what’s key here is to understand the actual issue - then a fix can be examined holistically. My concern right now is that we have proposed solutions but not a firm understanding of the underlying problem.

**Comment by jumarroq** [comment]
Do we need to go deeper than that delegatesFocus isn't working? I personally don't think it's needed to come out with a temporary fix, but maybe someone else that's confident reading through their bugs can get a deeper understanding of the problem.

**Comment by scomea** [comment]
There does appear to be related issues in their bugbase.  https://bugzilla.mozilla.org/buglist.cgi?short_desc=shadow%20dom%20focus&order=Importance&short_desc_type=allwordssubstr&resolution=---&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced

**Comment by scomea** [comment]
Actually, those above may explain why focused elements sometimes don't look focused, but not the focus() failure.  This is a better candidate and looks like it is currently being worked on.   https://bugzilla.mozilla.org/show_bug.cgi?id=1413836

**Comment by mollykreis** [comment]
I believe this is also related to a focus inconsistency I'm seeing with the FAST toolbar. In Chome/Edge, clicking in the toolbar focuses the first element in the toolbar, but in Firefox, you have to tab after clicking the toolbar to get the first element to be focused.

You can observe this behavior using the [FAST component explorer](https://explore.fast.design/components/fast-toolbar).

**Comment by chrisdholt** [comment]
Closing this as delegatesFocus is well supported over our current browser matrix for FAST (last 4 major versions w/ Safari 13.1+)
