### ISSUE TITLE
fix: listbox position not respected when opened programmatically in fast-select

### ISSUE THREAD

**Issue by brianehenry** [microsoft/fast#5123]
# 🐛 Bug Report

When a FAST select control dropdown is opened programmatically (with the `open` attribute), it doesn't use the `position` attribute if it's set. When opening the select dropdown interactively, it uses the `position` attribute correctly.

## 💻 Repro or Code Sample

```
<fast-select position="above" open>
    <fast-option value="1">Option 1</fast-option>
    <fast-option value="2">Option 2</fast-option>
    <fast-option value="3">Option 3</fast-option>
</fast-select>
```

## 🤔 Expected Behavior

The select dropdown should respect the `position` attribute if it has been set by the consumer of the control, even if the control is opened programmatically.

## 😯 Current Behavior

The select dropdown sometimes appears in a different position than the one set in the `position` attribute.

## 💁 Possible Solution

Call `setPositioning()` in [the connected callback](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/select/select.ts#L373) after setting `this.forcedPosition`. Also, don't call `setPositioning()` until the element is connected.

## 🔦 Context

We're using the `open` and `position` attributes together in a storybook to validate styles. 

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Microsoft Edge
* Version 92.0.902.78

**Comment by chrisdholt** [comment]
Thanks @brianehenry for the issue - we'll work to prioritize and get this fixed!

**Comment by atmgrifter00** [comment]
The only issue that I'm seeing that is still present is that if you set `position` to `above` in the HTML, the `fast-select` will have its `class` set with `below`. See [this Stackblitz example](https://stackblitz.com/edit/typescript-aaj7ij?devToolsHeight=33&file=index.html). Obviously you will need to inspect the DOM to see the wrong `class` applied.
