### ISSUE TITLE
rfc: solution to compress images for the web with GitHub Actions

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#5127]
# 💬 RFC

## 🔦 Context
Many images you see on the Internet today have undergone compression for various reasons. Image compression can benefit users by having pictures load faster and webpages use up less space on a Web host. Image compression does not reduce the physical size of an image but instead compresses the data that makes up the image into a smaller size.

The proposed solution is to use GitHub Actions from the GitHub marketplace called [calibreapp](https://dev.to/github/compress-images-for-the-web-with-github-actions-29a3) 

![image](https://user-images.githubusercontent.com/14119043/131554269-0d07e49d-f4e7-4afc-83d1-d2a767d36a03.png)

This will be the result of using image compression
![image](https://user-images.githubusercontent.com/14119043/131553868-fec70fec-e8a7-4cee-afbb-e66eff67df19.png)

**Comment by chrisdholt** [comment]
Can you elaborate on what purpose this serves within the context of the project, what the proposal/solution is, and what is recommended? Without that detail, I think an RFC is premature.

**Comment by Ibrahimmaga** [comment]
> Can you elaborate on what purpose this serves within the context of the project, what the proposal/solution is, and what is recommended? Without that detail, I think an RFC is premature.

give me a second Chris. I'm working on it. I keep closing the issue accidentally when putting it together and I prematurely save this and do the edit instead.

**Comment by Ibrahimmaga** [comment]
> Can you elaborate on what purpose this serves within the context of the project, what the proposal/solution is, and what is recommended? Without that detail, I think an RFC is premature.

Now it is good to comment on it.

**Comment by chrisdholt** [comment]
> > Can you elaborate on what purpose this serves within the context of the project, what the proposal/solution is, and what is recommended? Without that detail, I think an RFC is premature.
> 
> Now it is good to comment on it.

Thanks, I think I still have the same question in terms of what exactly image compression is solving within the context of the project today. With exception of the website, I can't think of where this would be useful in the project. If it's in terms of the website, I'm not sure how automation helps as it's pretty static and when images are added/updated we should ensure they are optimized and compressed. Is there another scenario I'm missing where this adds value?

**Comment by awentzel** [comment]
There are plenty of web assets that are generated and managed from the FAST some of which go to the website directly and others that go into a statics folder and uploaded to the CDN. 

We should never be hosting unoptimized images and this will help to prevent that as well as to ensure there is a consistent approach to compressing images. Frequently designers tackle this manually and have their own methods that may or may not work and change between people. More frequently engineers have even less experience here and so this improves quality, brings consistency, and automates the process.

**Comment by chrisdholt** [comment]
> There are plenty of web assets that are generated and managed from the FAST some of which go to the website directly and others that go into a statics folder and uploaded to the CDN.
> 
> We should never be hosting unoptimized images and this will help to prevent that as well as to ensure there is a consistent approach to compressing images. Frequently designers tackle this manually and have their own methods that may or may not work and change between people. More frequently engineers have even less experience here and so this improves quality, brings consistency, and automates the process.

To be clear, I'm not advocating for hosting unoptimized images. I'm wondering what the cost/benefit is for adding a build step for this considering these rarely change. I'd love to see a breakdown of the problem, the proposed solution, and any trade-offs, etc. I'm not explicitly saying I'm not for this, but if the ask is to comment based on what's been provided, I'm not sure I see the value of additions to the pipeline for assets which are essentially "set it and forget it" right now.

**Comment by EisenbergEffect** [comment]
@chrisdholt We ran tests against the website and determined that our perf was sub-optimal, mostly due to a few basic things that need to be fixed. One of the issues the site has is that various resources are not properly compressed. This would fix that issue while also putting automation in place to prevent the human error from happening in the future.

I don't see why we wouldn't go ahead and do this.

**Comment by chrisdholt** [comment]
> @chrisdholt We ran tests against the website and determined that our perf was sub-optimal, mostly due to a few basic things that need to be fixed. One of the issues the site has is that various resources are not properly compressed. This would fix that issue while also putting automation in place to prevent the human error from happening in the future.
> 
> I don't see why we wouldn't go ahead and do this.

My point is not to avoid compression, my point is that these assets do not change. Is there a reason to stand up a pipeline task which we then need to maintain, and which may over time have build-impact, for an issue that can be currently solved with a manual update, and solved in the future by ensuring we only add compressed images? Automation here seems like overkill considering once we run this we shouldn't need to run it again on the same images...

**Comment by EisenbergEffect** [comment]
It is a way of preventing human error, of which we have repeated instances in this case. As the team and project grow, there is increased chance that someone will forget (or never know) to do this type of menial work (as has already been demonstrated). We can automate and it and make sure we don't have to worry about it.

We should look to automate menial tasks, boilerplate, and work that require low skill, as those things are not cost-effective to do by hand, especially if it falls to an FTE.

In general, these types of automations are common in the industry and considered pretty standard practice. We should endeavor to lead with excellence especially when GitHub actions has an out-of-the-box solution, which brings the automation cost way down.

**Comment by chrisdholt** [comment]
Sounds good.

**Comment by Ibrahimmaga** [comment]
I appreciate all comments

**Comment by chrisdholt** [comment]
closing this due to implications of #5853
