### ISSUE TITLE
fix: initial value in FAST select control not used when using Angular two-way binding

### ISSUE THREAD

**Issue by brianehenry** [microsoft/fast#5139]
# 🐛 Bug Report

When using a FAST select control in Angular, a two-way value binding does not set the initial value of the control. I'm using [ngDefaultControl](https://angular.io/api/forms/DefaultValueAccessor), as suggested in the [FAST Angular integration docs](https://www.fast.design/docs/integrations/angular). 

## 💻 Repro or Code Sample

https://stackblitz.com/edit/angular-ivy-7kjj4p?file=src/app/app.component.html

## 🤔 Expected Behavior

When the select's value is two-way bound to a value in the component using `[(ngModel)]`, the initial value of the control should be the same as the initial value of the property in the component.

## 😯 Current Behavior

The select control does not use the value in the bound property for its initial value; instead it uses the first value in the listbox. 

## 💁 Possible Solution

It looks like the select's `value` property is being set before the `slottedOptions` property, so it treats the value as invalid. I don't see an obvious fix though.

## 🔦 Context

Trying the use the FAST select control in Angular with nice two-way binding behavior and form integration.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Microsoft Edge
* Version 92.0.902.78

**Comment by EisenbergEffect** [comment]
@chrisdholt While this issue is labeled as an Angular issue, I believe this is the same `select` `value` issue that has been reported a few times on Discord. Seems nearly every library/framework is affected by this and that folks find it unintuitive how `value` works.

**Comment by chrisdholt** [comment]
> @chrisdholt While this issue is labeled as an Angular issue, I believe this is the same `select` `value` issue that has been reported a few times on Discord. Seems nearly every library/framework is affected by this and that folks find it unintuitive how `value` works.

Sure, so this is related to an RFC that we have already, correct? Is there an ask here or just FYI?

**Comment by EisenbergEffect** [comment]
This is separate from the general `value` issue that @nicholasrice wrote the RFC for. There has been some general community feedback on `select` not being intuitive in how selection is handled I believe. I'm not sure if any of that was put in an issue. There were various conversations on Discord over 2-3 months. This may be the first issue filed. I wasn't sure.

**Comment by brianehenry** [comment]
@EisenbergEffect Yeah, I think you would see this issue any time you set the `value` property really early in the element's lifecycle.

Went and looked in Discord for a workaround, and it looks like setting the `option`'s `selected` attribute will set the initial value correctly.

I came up with a workaround for Angular, using a directive to set `selected` on the appropriate `option`: https://stackblitz.com/edit/angular-ivy-lvn1ty?file=src%2Fapp%2Ffast-select.directive.ts

**Comment by EisenbergEffect** [comment]
Makes sense. Thanks for your patience @brianehenry and willingness to work around for now. We can leave this open to track the issue and as a reference for anyone who hits the problem and needs the same work around.
