### ISSUE TITLE
fix: can not navigate to URLs from anchor tags in TreeItems

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#5159]
# 🐛 Bug Report

I expect that anchor tags (`<a>` or `<fast-anchor>`) within the <fast-tree-item> element would allow navigation to the specified 'href' setting upon click. This does not happen. 

## 💻 Repro or Code Sample

```
<fast-tree-view>
    <fast-tree-item>Tree item 1<fast-tree-item slot="item"><fast-anchor href="www.google.com">Google</fast-anchor></fast-tree-item>
    </fast-tree-item>
    <fast-tree-item>Tree item 2</fast-tree-item>
</fast-tree-view>
```

## 🤔 Expected Behavior

In the above example, I expect if a user clicks on the 'TreeItem` with the "Google" text that it will navigate the browser to www.google.com. This doesn't happen.

## 😯 Current Behavior

Nothing happens when the TreeItem is clicked.

## 💁 Possible Solution

At a guess, I would suspect that the TreeItem is eating the click event.

## 🔦 Context

We have an app that uses a tree to navigate between various pages. Without this, I have to resort to a programmatic solution, which isn't ideal.

## 🌍 Your Environment

Windows Desktop/Chrome.

**Comment by chrisdholt** [comment]
The tree item is definitely eating the click as of now. @eljefe223 has some updates coming in for tree view which is likely to change the current implementation, so depending on how that change impacts things, we may be able to address this in that PR. All said, this can hopefully be resolved soon :)
