### ISSUE TITLE
fix: TreeView has initial visual glitch when expanding tree groups

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#5166]
# 🐛 Bug Report

When expanding a tree group, you can see a quick rendering glitch for all of the child items under that group when they first appear. Successive collapsing/expanding of the same group does not have the glitch.

## 💻 Repro or Code Sample

I used the following snippet on your [FAST Tree View example](https://explore.fast.design/components/fast-tree-view) site:

```
<fast-tree-view>
    <fast-tree-item>Tree item 1<fast-tree-item slot="item">Test</fast-tree-item>
    </fast-tree-item>
    <fast-tree-item>Tree item 1<fast-tree-item slot="item">Item 2</fast-tree-item>
    </fast-tree-item>
    <fast-tree-item>Tree item 1<fast-tree-item slot="item">Item 3</fast-tree-item>
    </fast-tree-item>
    <fast-tree-item>Tree item 1<fast-tree-item slot="item">aasdf</fast-tree-item>
        <fast-tree-item slot="item">wer</fast-tree-item>
        <fast-tree-item slot="item">sfdh</fast-tree-item>
        <fast-tree-item slot="item">we34</fast-tree-item>
        <fast-tree-item slot="item">rewtret</fast-tree-item>
    </fast-tree-item>
    <fast-tree-item>Tree item 1
        <fast-tree-item slot="item">
            serfgsreg
        </fast-tree-item>
    </fast-tree-item>
    <fast-tree-item>Tree item 2</fast-tree-item>
</fast-tree-view>
```

To get around some of the initial wonky behavior the tree seems to exhibit on this example site (like the tree won't update with all  of the set tree items after copy-pasting the above snippet), you may have to update one of the text fields of one of the tree items.

## 🤔 Expected Behavior

There should be no glitch when expanding a tree group for the first time.

## 😯 Current Behavior

![TreeGlitch](https://user-images.githubusercontent.com/26874831/132540124-76dd8fb4-c8b1-4be8-8c47-be894e3dfb0d.gif)

## 🔦 Context

The glitch is noticeable, and doesn't make for the best impression for a user of the tree.

## 🌍 Your Environment

Windows Desktop/Chrome.

**Comment by chrisdholt** [comment]
Thanks @atmgrifter00 - I'm not able to repro this in a couple of different environments initially; can you provide what version of Chrome you are on and what version of `@microsoft/fast-components` you're using? I'll try with the exact versions on my Mac and if I can't repro I'll have someone test with their Windows machine.

**Comment by atmgrifter00** [comment]
Chrome Version 92.0.4515.159.
@microsoft/fast-element": "^1.4.1
@microsoft/fast-foundation": "^2.0.0

**Comment by chrisdholt** [comment]
> Chrome Version 92.0.4515.159.
> @microsoft/fast-element": "^1.4.1
> @microsoft/fast-foundation": "^2.0.0

Thanks! I'll take a look
