### ISSUE TITLE
fix: tab-panel display in FAST components

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#5171]
# 🐛 Bug Report

The [default display of `<fast-tab-panel>`](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/tab-panel/tab-panel.styles.ts#L21
) is `flex`, which is probably not what the majority of users want.

Consider the following code:

```html
<fast-tab-panel>
  Check out my code
  <pre><code>console.log('hello world');</code></pre>
</fast-tab-panel>
```

This results in child elements being stacked in the flex row.

<img width="392" alt="CleanShot 2021-09-09 at 11 50 17@2x" src="https://user-images.githubusercontent.com/55639/132719602-cd93214f-e12a-4b74-8f87-f52196b40400.png">

However, most users will likely expect a more common flow.

<img width="256" alt="CleanShot 2021-09-09 at 11 50 37@2x" src="https://user-images.githubusercontent.com/55639/132719668-f42f26ee-919f-4b90-a932-17736b831a41.png">

The bigger issue is that there's not a nice way to override this behavior with CSS. Applying `display: block` via CSS will override the `hidden` attribute causing the panels to stack, so a more complex selector is required.

```css
fast-tab-panel:not([hidden]) {
  display: block;
}
```

I'm happy to submit a PR (or anyone on the team can swap [`flex` to `block`](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/tab-panel/tab-panel.styles.ts#L21)) but figured I'd raise the issue first since this would probably be a breaking change.

[This also affects Fluent WC.](https://github.com/microsoft/fluentui/blob/master/packages/web-components/src/tabs/tab-panel/tab-panel.styles.ts#L9)

**Comment by chrisdholt** [comment]
We'd welcome a PR (in both repos if you like)! I'd agree that the default of `block` is likely a more appropriate and expected default.
