### ISSUE TITLE
Fix "method_count" issue in packages/fast-form-generator-react/src/form/form-item.children.tsx

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#519]
`FormItemChildren` has 24 functions (exceeds 20 allowed). Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-form-generator-react/src/form/form-item.children.tsx#issue_5b1efe48480d0a000100028d

**Comment by Falkicon** [comment]
@awentzel, what is the impact of this?

**Comment by nicholasrice** [comment]
@Falkicon This is auto-generated by code-climate. It just means there is some refactoring work needed to meet code-climate criteria - this is low pri and has no end-user impact.
