### ISSUE TITLE
fix: [Position Top and Left shift and glitch?] in [Tooltips?]

### ISSUE THREAD

**Issue by shmehltr** [microsoft/fast#5191]
# 🐛 Bug Report

Tooltips with position "top" and "left" do not work properly. The tooltip appears then shifts position. This can result in an infinite loop of hiding and showing when hovering over an anchor.

![toolti](https://user-images.githubusercontent.com/77364983/133487901-a7edd129-015d-46e0-9203-976845db368b.gif)

## 💻 Repro or Code Sample

add position top or left to a fast tooltip and observe behavior.

<div>
    <fast-button id="anchor" style="height: 40px; width: 100px; margin: 100px; background: green;">Hover me</fast-button>
    <fast-tooltip anchor="anchor" position="top">Tooltip text</fast-tooltip>
</div>

## 🤔 Expected Behavior

The tooltip should work smoothly like it does in other positions

## 😯 Current Behavior

The tooltip glitches into position and sometimes results in blinking and erratic behavior when hovering near the edge of an anchor.

## 💁 Possible Solution

 It looks like the mouseover when initially showing the tooltip may be causing mouse over to trigger on the tooltip instead of the anchor resulting in this endless loop we see.

## 🔦 Context

It looks glitchy

## 🌍 Your Environment

tested in
Windows - chrome and edge.
Mac - Edge

**Comment by claviska** [comment]
Confirmed that this happens in Fluent too, although it's harder to replicate in Storybook for some reason.

**Comment by chrisdholt** [comment]
@scomea can you investigate this?
