### ISSUE TITLE
fix: allowing decimal values in fast number field

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#5196]
# 🐛 Bug Report

Currently, the `<fast-number-field>` doesn't handle decimal values properly.

- [x] With a decimal step, the up and down buttons work properly
- [ ] The field doesn't allow for the `.` symbol to be entered
- [ ] The `inputmode` is set as `numeric` which is intended for integer only values

## 🤔 Expected Behavior

This component should properly handled both integer and decimal values.

## 💁 Possible Solution

I'm happy to submit a PR to fix this issue, but I would like to discuss the right course of action first. I suggest:

1. Adding an `@attr` for `inputmode` allowing for `numeric` and `decimal` values.
2. I'm wondering if the `type` of the input should be `number`. Problem is: it will display the native up/down buttons but they can be hidden with CSS.

Would be happy to get some feedback before to jump on the PR.

**Comment by atmgrifter00** [comment]
Personally, I feel that there shouldn't be a strict distinction between what kind of numeric the number field supports (integer vs. decimal), and instead it should allow a user to _always_ enter a decimal value (this works just fine on the standard HTML input element set to 'number' type).

Instead, if the goal is to restrict what the user can ultimately see in the input field, it would be nice if a user could specify formatting options (e.g. number of digits of precision, scientific notation, etc...).
