### ISSUE TITLE
feat: VS Code Go to Definition

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5212]
# 🙋 Feature Request

Enable easily jumping to the definition of a custom element from anywhere that it is used.

## 🤔 Expected Behavior

When I've got an HTML tagged template literal or an HTML file, I should be able to control/cmd-click the element name and jump to the source code for the element.

## 😯 Current Behavior

No special behavior for custom elements.

## 💁 Possible Solution

Likely will involve a custom VS Code plugin that can search for files based on typical naming conventions since there is technically no strong coupling between a tag name and a JS class. The setting for the plugin could include a set of patterns to match so that the app developer could also add their own if they are using a different organization.

## 🔦 Context

App developers using FAST want to be able to navigate their code more easily, with the same fidelity that they are used to having with React.

**Comment by janechu** [comment]
Closing this as out of scope per #6955.
