### ISSUE TITLE
fix: value property not reflected to attribute in fast-option

### ISSUE THREAD

**Issue by brianehenry** [microsoft/fast#5219]
# 🐛 Bug Report

When the `value` property is set on a `fast-option` element, the value is not reflected to the `value` attribute. Also, the `value` property does not coerce the value to a string. 

## 💻 Repro or Code Sample

```js
const option = document.querySelector('fast-option');
option.value = 1;
console.log(option.getAttribute('value')); // I'd expect this to be '1'
console.log(option.value) // I'd expect this to be '1' (as a string)
```

## 🤔 Expected Behavior

I'd expect that the FAST option would reflect the `value` property to the `value` option, since this is how the native `option` element behaves. I'd also expect the value to be coerced to a string, which is also a native `option` behavior.

## 😯 Current Behavior

The `value` property is not reflected to the `value` attribute, and the `value` property is not coerced to a string.

## 💁 Possible Solution

This workaround seems to be working for me:
```js
class ListboxOption extends FoundationListboxOption {
    public get value(): string {
        return super.value;
    }

    public set value(value: string) {
        // Coerce value to string
        super.value = `${value}`;

        if (this.$fastController.isConnected) {
            this.setAttribute('value', this.value);
        }
    }

    public override connectedCallback(): void {
        super.connectedCallback();
        this.setAttribute('value', this.value);
    }
}
```

## 🔦 Context

When integrating the `fast-select` component in Angular, I want Angular to treat the component as if it were a native HTML `select`. But this inconsistency causes problems.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Microsoft Edge
* Version 93.0.961.47

**Comment by radium-v** [comment]
For `ListboxOption`, changing the `value` _property_ doesn't change the `value` _attribute_ since the attribute actually represents the _initial value_ of the option. This is evidenced by the `@attr` decorator being applied to the `initialValue` property rather than the `value` property.

Changing the value via `option.setAttribute("value", "1")` should work as long as the `value` hasn't already been changed via `option.value`.
