### ISSUE TITLE
feat: add method to flush/clear updateQueue created by DOM.queueUpdate().

### ISSUE THREAD

**Issue by brianehenry** [microsoft/fast#5222]
# 🙋 Feature Request

Due to weird interactions between Angular's usage of Zone.js and FAST's `DOM.queueUpdate()`, it would be helpful to have a way to clear the list of queued actions for testing purposes. 

I explain the issue we're seeing in more detail in the "Context" section.

## 🤔 Expected Behavior

After calling `DOM.queueUpdate()` (either directly or indirectly, e.g. by creating a FAST component), I can call something like `DOM.clearUpdateQueue()`, which will remove all items from the [updateQueue](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/src/dom.ts#L4).

## 😯 Current Behavior

There's no way to un-queue items from the `updateQueue` after calling `DOM.queueUpdate()`. This becomes a problem if the original `requestAnimationFrame` never resolves.

## 💁 Possible Solution

See "Expected Behavior".

## 🔦 Context

When using FAST components in an Angular app, and testing the app using [fakeAsync()](https://angular.io/guide/testing-components-scenarios#async-test-with-fakeasync), we see issues with the `requestAnimationFrame()` in `DOM.queueUpdate()` not resolving. I think this issue is likely to be encountered by anyone using FAST components in Angular apps, if they attempt to use `fakeAsync` in their tests.

[I created a repo with a simple reproduction](https://github.com/brianehenry/fast-angular-async-issue-repro). Here's the test code that is affected by this issue:

```js
describe('fakeAsync() DOM.nextUpdate() issue', () => {
  it('test 1', fakeAsync(() => {
      const textField = document.createElement('fast-text-field');
      document.body.appendChild(textField);
      // By creating a FAST element, DOM.queueUpdate() will be called. But since this is within
      // fakeAsync(), the requestAnimationFrame in DOM.queueUpdate() will never resolve unless
      // we explicitly flush it. This causes issues for subsequent tests that will queue processes
      // on the same requestAnimationFrame call that will never resolve.

      // Calling tick(16) here will flush the requestAnimationFrame queued by DOM.nextUpdate()
      // and will allow the other tests to pass. But it's not ideal to have to call that at the
      // end of every test. And calling it in a beforeEach or afterEach wouldn't work because
      // it would be in a different Zone context.
  }));

  it('test 2', fakeAsync(() => {
      // This test will succeed if run by itself, but will fail if test 1 is run first

      const textField = document.createElement('fast-text-field') as TextField;
      document.body.appendChild(textField);
      textField.disabled = true;
      tick(16);
      expect(textField.getAttribute('disabled')).toBe('');
  }));

  it('test 3', async () => {
      // This test will succeed if run by itself, but will time out if test 1 is run first
      await DOM.nextUpdate()
  });
});
```

Angular uses Zone.js to monkey patch `requestAnimationFrame()` and other async operations. When using `fakeAsync`, Angular creates a new Zone for each test. In `fakeAsync` tests, time must be manually be advanced by calling the `tick()` function - and async operations will not resolve until `tick()` is called. If an async operation has not resolved by the end of the test method, it will never resolve. 

Since `DOM.queueUpdate()` uses a global queue based on a single call to `requestAnimationFrame()`, if a rAF doesn't resolve, it can block the update queue permanently. 

To be honest, I feel like this is more of an issue with Angular and Zone.js than an issue with FAST. That's why I decided to file this as a feature request instead of a bug. We're also considering filing an issue in the Angular repo about this class of issue. 

## 💻 Examples

N/A

**Comment by EisenbergEffect** [comment]
@brianehenry Do you want the helper method to process the queue or clear the queue?

**Comment by brianehenry** [comment]
@EisenbergEffect I think we want the method to process the queue. That way we can call the method in our `fakeAsync` tests to get the element to update.

**Comment by EisenbergEffect** [comment]
That what I figured but just wanted to make sure. That should be pretty easy to manage. I've assigned the task to myself. I may not get to it this week, but it shouldn't take too long.
