### ISSUE TITLE
fix: Client side form validation pseudo-classes only in browsers with native form-associated custom elements

### ISSUE THREAD

**Issue by rajsite** [microsoft/fast#5231]
# 🐛 Bug Report

I'd like to be able to style controls such as `fast-text-field` using [form validation UI pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#ui_pseudo-classes) such as `:invalid`.

These pseudo-classes work on browsers with native form-associated custom element support such as Chrome and Edge but do not work in Firefox and there does not seem to be a workaround implemented such as an `invalid` class that is added to the element.

## 💻 Repro or Code Sample

Run the following stackblitz in Chrome / Edge to see styles apply and Firefox to see the styles fail to apply: https://fast-client-side-validation-pseudo-classes.stackblitz.io/

Source: https://stackblitz.com/edit/fast-client-side-validation-pseudo-classes?file=style.css

## 🤔 Expected Behavior

I'd expect the pseudo-class to apply across browsers (or having a fallback class to target) resulting in the following:
![image](https://user-images.githubusercontent.com/1588923/134954600-69db4af3-d6f4-4c8f-abe2-664dbc1b705e.png)

## 😯 Current Behavior

In Chrome and Edge I see:
![image](https://user-images.githubusercontent.com/1588923/134954634-2279500d-b13c-4df6-a5f4-9fd308749a91.png)

In Firefox:
![image](https://user-images.githubusercontent.com/1588923/134954684-a83c5c05-0857-4d1c-a96b-b313a1a7ccab.png)

## 💁 Possible Solution

- Have the form associated custom elements polyfill reflect the different UI pseudo-classes as normal CSS classes that can be targeted cross-browser.

## 🔦 Context

I'm trying to provide default styles for the different pseudo-classes in element CSS, ie:

```
:host(:invalid) {
    border: 1px solid red;
}
```

## 🌍 Your Environment

* OS & Device: Windows
* Browser Chrome 93, Edge 94, Firefox 92
* Version fast-components@2.10.0

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
