### ISSUE TITLE
rfc: add refs to all shadow DOM nodes in component templates

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5234]
# 💬 RFC - Add refs to all Shadow DOM nodes in component templates

The templates and classes included as part of FAST Foundation exist to provide markup and functionality for a majority of use cases and serve as building blocks for not only the FAST components, but for any component which may require the same underlying role, behavior, etc. While it is almost impossible to handle any and all scenarios a user may be able to consider with a given component, we can provide an extensible model for them to build off. A good and extremely simple example of this is the concept of "appearance" in the FAST and Fluent Design Systems. The foundation classes do not include this concept as they are quite specific to a given design language. There are different semantics, implementations, restrictions - the concept of appearance is one that is *not* foundational or "globally applicable" across all design systems *OR* across all instances of a given type of component - some things which are buttons do not have the need for multiple appearances. With this in mind, we take an approach where we extend the class to enable and support our unique scenarios.

This RFC recommends an additional improvement to the extensibility of our classes and templates. Currently, refs only exist on the control for things which we *know* exist at the foundation level. This creates a limitation to our ability to use the templates. While I can easily extend the class to include certain new attributes and properties such as the `appearance` example above, I cannot do this for references to the template nodes. In instances where I need a reference, I'm essentially relegated to either swapping out the template to include refs where needed OR querying the shadow DOM from within the class which while somewhat reasonable seems less-than-ideal.

One of our core values for these Foundation controls is that they are for broad use and not specifically to support our own scenarios - `fast-components` is just another implementation of foundation, it does not get special treatment. With that said, traditionally, anytime that we've added features or functionality which requires the addition of a ref, we are able to easily add it. In this case, we have the benefit because of our monorepo to make these additions for our own ease of use. It seems reasonable that rather than adding refs whenever we find a use case, we extend the API to include these references which opens up more flexibility and opportunity for the community to take advantage of them. This also means that in the future if we want to use the Web Animations API to transition seamlessly in and out of showing/hiding the Dialog we don't need to go add refs to accomplish this. Folks using Foundation also get access to this immediately and without needing to file an issue and elevate their use case, etc.

## Implementation
The implementation of this would be fairly straight forward. Any node which is not a root node or slot (which is projected into the light DOM so refs can be added by end users) would now have a reference from the component class. Refs would be named according to the CSS Part which I think is intuitive as it's already an established API for providing authors the opportunity to reach in and style via CSS. Refs would all be typed as well, which is an added benefit.

## 💻 Examples

While not illustrative of the entire component set, I've started a [draft PR](https://github.com/microsoft/fast/pull/5235) to illustrate what this would look like across templates.

**Comment by EisenbergEffect** [comment]
What if instead of adding the refs everywhere, we add a typed `findPart` API to each component? Refs are not free and do cost memory/perf in startup cost for every ref we add. In the case above, we'd be adding refs that wouldn't be used most of the time. So, what if we took the API approach instead?

Example use would be like this:

```ts
const link = avatar.findPart('link');
```

We could provided typed overrides so that 'link' actually return an `HTMLAnchorElement`. That would enable autocomplete for the `findPart` string options as well as typed return values. Then you only pay the cost if you need to find the ref. As an optimization, we can make it cache the refs internally (we'd have to empty the cache if the template was changed).

This brings up something interesting though. The refs are really details of the template, not necessarily the component class. The purposes we have of creating the refs is as part of the contract between the template any the class. Basically, any template must contain certain refs to work with the component. However, what if someone provides a different template? Now either our `findPart` API or our ref properties will be invalid. Is that acceptable? If not, then we should look at this as an API for `View` instead. I'd need to think through whether we could type the template such that we could provide the info needed to produce a view with the properly typed `findPart()` API.

**Comment by scomea** [comment]
I worry this could make it very difficult to modify templates after publishing without breaking someone.

**Comment by chrisdholt** [comment]
> I worry this could make it very difficult to modify templates after publishing without breaking someone.

I’m going to spin up a discussion topic on this. I’m concerned that there’s an assumption this is already and should be easy, which it shouldn’t. It’s not that we can’t change templates, but an assumption today that it’s currently harmless or should be easy to change templates is a pretty significant blind spot for us if that’s the case.

**Comment by nicholasrice** [comment]
@chrisdholt are there specific PRs / desired changes that this RFC is addressing or is this problem more theoretical?

I'd also like to echo @EisenbergEffect's point on class vs template responsibilities. I do feel that using refs and class properties as an implementation would impose a tighter coupling of class -> template pairs which may not be desirable.

**Comment by chrisdholt** [comment]
> @chrisdholt are there specific PRs / desired changes that this RFC is addressing or is this problem more theoretical?
> 
> I'd also like to echo @EisenbergEffect's point on class vs template responsibilities. I do feel that using refs and class properties as an implementation would impose a tighter coupling of class -> template pairs which may not be desirable. Exposing an API on the template itself seems like a good alternative to me.

I think it's both theoretical and an existing problem. Theoretical in that I can see both for us and others a desire or need to add additional functionality or behaviors hooking off Shadow DOM nodes which we don't intend to support directly in FAST. An example which is technically already handled is animating in the `dialog` on top of the overlay using the web animations API. This example is *only* currently handled because we've added a ref to manage trapping focus.

I'm not sold on this needing to be *ref* though I think it provides an easy ergonomic. I do want to address the issue of tight coupling. I agree that could be a problem - someone goes to use the class and swaps out the template and the ref isn't there and the class is expecting it, etc...that's also an existing problem though, is it not? Currently, our practice is that if something needs a ref, we have added it for our own use cases. This is similar to scenarios where we have needed to take action on slotted items and so we've added a `slotted` directive to enable our own scenarios (this happened in anchor and button). 

To be clear here, I'm not arguing *for* tight coupling, but more that I think we need consistency in how we handle our own scenarios and what deserves being elevated as a first class citizen. Perhaps the solution here is improved guidance, workflow, etc. While it seems quite reasonable that we be able to add something like a slotted directive to serve our needs, or to add a ref when we need to accomplish something in `fast-components` - it seems like we're hoisting our requirements as "special", when I'm not sure they should be.

Perhaps the proposal above is not the right implementation, but we need a pattern for when someone should use `ref`, `slotted`, etc in Foundation, and what all should be included in the class implementation. For the dialog scenario above, I would expect that if we wanted to add an animation to the open/close of the dialog itself we would add that at the `class` level of `fast-components` rather than foundation. After all, it's presentational and while the hooks should exist for managing that transition, the transition itself is an implementation detail. I'm not sure we are being true to this construct though in the templates, or how we do have approached these problems up until now. If I need a reference for something purely visual, perhaps the right thing is to query the shadow DOM in an extended class, even for our own scenarios.

Note: This brings up the same issue with `slotted` which is likely a larger conversation as I can think of a number of use cases today where an array of elements would be helpful...the same question is valid here - when do we take on and include the cost of said direction in `foundation` on behalf of the community? What is our bar for when we use these helpers and create a coupled scenario?

**Comment by chrisdholt** [comment]
> > I do want to address the issue of tight coupling. I agree that could be a problem - someone goes to use the class and swaps out the template and the ref isn't there and the class is expecting it, etc...that's also an existing problem though, is it not?
> 
> I believe we typically mark a 'ref' property on a class as "internal", which to me says to anyone using this public property that it isn't part of the official api so there's no guarantee it won't change in the future. If we decide to expose a particular 'ref' prop as part of the interface we should label it as public and document it. Should be done with deliberate intent and not to every shadow dom node IMO.

This is a good point @scomea and one that didn't immediately come to mind. We do typically shield things like refs from the public as a stable API by marking as`@internal`. I think this helps with the current issue of coupling existing in that form as of now.

I don't think it addresses the issues of reasonable times a user might need a reference to a node or what is likely more difficult in current form, the benefits of the `slotted()` directive. Perhaps this isn't an issue, but it seems like we need both guidance for contributors governing how and when we use these and for what in Foundation classes themselves (noted above such as a11y, focus management, etc).

**Comment by nicholasrice** [comment]
I've always consider elements within the shadow DOM decorated with a `part` attribute to be part of the components "public API" (at least from the perspective of CSS styling), and perhaps would work that into a private mechanism to retrieved elements by part from a template (I think this is maybe what Rob is suggesting). These parts then become the constant and removing them designates a "breaking change", where other template changes don't.

**Comment by chrisdholt** [comment]
> I've always consider elements within the shadow DOM decorated with a `part` attribute to be part of the components "public API" (at least from the perspective of CSS styling), and perhaps would work that into a private mechanism to retrieve elements by part from a template (I think this is maybe what Rob is suggesting). These parts then become the constant and removing them designates a "breaking change", where other template changes don't.

We're certainly aligned here as far as what would be considered breaking. Specifically in Foundation, the template itself is a stand alone export which is used by teams composing their own controls, which I think goes *beyond* just those decorated with parts. That's unrelated here, but an important thing to consider with this change. Whatever goes into Foundation is *not* being consumed as a dependency of a component itself, but as a dependency for building a component - the entire template is essentially the contract when it comes to Foundation.

All said, I think having some utility or lookup that is either no-cost until used or opt-in would be beneficial for teams who need access to certain things which don't currently decorate the templates. The more I consider it, the more it seems that reaching into the Shadow DOM is the easier thing to solve for here - support from the `slotted()` directive is much harder to address. Technically even if we didn't add refs we could still reach into the shadow DOM if we had to.
