### ISSUE TITLE
fix: validation state on fast-text-field (and other form associated elements) never updates to valid in Firefox

### ISSUE THREAD

**Issue by caseyfaber** [microsoft/fast#5267]
# 🐛 Bug Report

If you have a field with `required` or `pattern`, it will mark the field as invalid. But when using Firefox, if you fill it in matching the requirements, it will never change to valid.

## 💻 Repro or Code Sample

https://codesandbox.io/s/fast-text-field-validation-in-firefox-wgtb0?file=/src/index.js

This sample has a required field, and is outputting the results of `validity.valid`, `validity.valueMissing`, and `validationMessage`.

## 🤔 Expected Behavior

It should update the `validationMessage` to be blank when the field is valid, and `validity.valid` should be true.

## 😯 Current Behavior

In Firefox, `validationMessage` retains the error message even if you fill in the field, and `validity.valid` never turns true.

## 💁 Possible Solution

It is related to the `validate()` function called in `valueChanged()`. I was able to fix this by calling `this.proxy.setCustomValidation('')` with an empty string in `valueChanged()` before `validate()` is called. 

It looks like `validate()` should end up calling `setCustomValidation` with an empty string anyway (in `setValidity()`), but for some reason it is keeping an old `validationMessage` and `validity.valid` state.

Here is an example with this working in Firefox: https://codesandbox.io/s/text-field-firefox-fix-0sy4l?file=/src/index.ts

```js
class TextField extends FoundationTextField {
  valueChanged(previous: string, next: string) {
    if (this.proxy instanceof HTMLElement && !this.elementInternals) {
      this.proxy.setCustomValidity("");
    }
    super.valueChanged(previous, next);
  }
}
```

## 🌍 Your Environment

Note: Codesandbox is a bit wonky in Chrome, but Stackblitz will not allow me to use fast-foundation for some reason. These samples are intended to show Firefox behavior, but if you look at the code samples in Chrome you may need to press the refresh button in the Browser section to get it to work. 

* OS & Device: Windows
* Browser: Firefox
* Version: fast-foundation 2.17.1

**Comment by rajsite** [comment]
Sounds like the same class of issue as discussed here: https://github.com/microsoft/fast/issues/5231

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
