### ISSUE TITLE
fix: when using minlength on fast-text-field or fast-number-field, field won't be invalid even if the amount of characters is too short

### ISSUE THREAD

**Issue by caseyfaber** [microsoft/fast#5268]
# 🐛 Bug Report

If you use `minlength` on `<fast-text-field>` or `<fast-number-field>`, it will not be marked as invalid even if the number of characters is less than the minlength. If you look at the `validity` or `validationMessage` properties of the internal input control, they are correct there, it's just not matching up to  `validity` and `validationMessage` of the fast-text-field.

## 💻 Repro or Code Sample

https://stackblitz.com/edit/js-gbursy?file=index.js

In this example I am showing the `validity.valid`, `validity.tooShort` and `validationMessage` properties of both the fast-text-field and the internal control input when the field is typed in. 

## 🤔 Expected Behavior

If the characters are less than the minlength attribute, I expect `validity.valid` to be false, `validity.tooShort` to be true, and `validationMessage` to have an appropriate error message.

## 😯 Current Behavior

The field is marked as 'valid' no matter what the length is.

## 🔦 Context

I am trying to style fields as invalid if they don't contain the amount of characters in 'minlength'.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Chrome, Edge
* Version: fast-foundation 2.17.1

**Comment by chrisdholt** [comment]
@nicholasrice curious of your thoughts here. It looks like perhaps scenarios where we have an internal input such as text field, number field, etc, we need to pass the validity from the input being used for text field to the class itself.

**Comment by nicholasrice** [comment]
All form associated custom elements should implement validity behavior to match control options (min-length) for example. For these controls that implement an internal input element then we may be able to use that control to inform the custom element's validity, but AFAIK the `.setValidity()` method still needs to be invoked with that validity. I don't know at this point what, if any, edge cases there may be in populating validity this way. An alternative would be to implement our own code to determine and set validity, though I suspect it will be redundant to the native element in many cases.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
