### ISSUE TITLE
rfc: add FAST file selector spec to/in component specs

### ISSUE THREAD

**Issue by litteredwitherrors** [microsoft/fast#5269]
# 💬 RFC

## 🔦 Context

Seeking feedback for this FAST specification for checkpoint 1.

# FAST File Selector

## Process

- [ ] **Checkpoint 1** - Schedule a spec review meeting to cover the Overview section before proceeding to work on the Design section. Be sure to include relevant stakeholders such as members of the tools team.

- [ ] **Checkpoint 2** - Schedule a spec review meeting before beginning the implementation work. Be sure to invite relevant stakeholders such as design system owners.

- [ ] **Checkpoint 3** - Submit the component PR and schedule a component code review meeting or present the component in one of our Engineering Open Mic sessions. Address feedback from the review, obtain final approvals through GitHub, and merge.

## Overview

A file input is a control that is used to give a user the ability to select files from their computer's file system.

### Background

There is currently an existing HTML implementation that is part of the `input` element specification.

**Related issues**:
https://github.com/microsoft/fast/issues/4726

### Use Cases

A user wants to upload a document, such as an image, from their device to the website or web application.

### Non-goals

The file input will not utilize the base level javascript file API, but will rather invoke the native HTML element's `click()` function.
  
### Features

- Prompts a user to select files to upload
- Ability to slot in a file list
- Ability to slot in a button

### Risks and Challenges

N/A

### Prior Art/Examples

- [Ant Design](https://ant.design/components/upload/)
- [Bootstrap](https://getbootstrap.com/docs/4.0/components/forms/#form-controls)
- [Carbon](https://www.carbondesignsystem.com/components/file-uploader/usage/)
- [Evergreen](https://evergreen.segment.com/components/filepicker)
- [Materialise](https://evergreen.segment.com/components/filepicker)
- [MOJ](https://moj-design-system.herokuapp.com/components/multi-file-upload)

---

**Comment by EisenbergEffect** [comment]
@daviddossett Awesome. Concrete use cases from real products are pure gold. Sketches are very welcome.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
