### ISSUE TITLE
fix: Changing tab disabled flag doesn't bring back click handler in tabs.ts

### ISSUE THREAD

**Issue by skawian** [microsoft/fast#5274]
# 🐛 Bug Report

## 💻 Repro or Code Sample

```
<fast-tabs activeid=${x => x.selectedTab} @change=${(x, e) => x.tabsChangeHandler(e)}>
    <fast-tab slot="tab">Tab one</fast-tab>
    <fast-tab slot="tab">Tab two</fast-tab>
    <fast-tab slot="tab" ?disabled=${x => x.isTabThreeDisabled}>Tab three</fast-tab>
    <fast-tab-panel slot="tabpanel">Tab panel 1</fast-tab-panel>
    <fast-tab-panel slot="tabpanel">Tab panel 2</fast-tab-panel>
    <fast-tab-panel slot="tabpanel">Tab panel 3</fast-tab-panel>
</fast-tabs>
```

Changing `isTabThreeDisabled` from false to true does not trigger https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/tabs/tabs.ts#L175 so it could add back click event listener.

## 🤔 Expected Behavior

Tab should have event listener and become responsive for clicking

## 😯 Current Behavior

change handler stops working as the event listener for clicking on the tab is not assigned

## 💁 Possible Solution

I have a temporary fix in my project where I assign click handler to the tab itself but it's not a long term solution.

I was thinking about moving logic for checking if tab is focusable to the click event handler and assigning click handler no matter if tab is disabled or not

**Comment by chrisdholt** [comment]
@eljefe223 any update on this?

**Comment by brianehenry** [comment]
I ran into a related (opposite) issue - if you set disabled=true on a tab programmatically after it has been created, it will still respond to click events (i.e. you can still select the tab). Let me know if I should file a separate issue for this, but it seems like the fix would be the same.
