### ISSUE TITLE
feat: add custom dependabot configuration

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#5285]
# 🙋 Feature Request

Since Dependabot doesn't really handle our Yarn lockfile well, we should add a configuration file which allows us to run custom steps.

## 🤔 Expected Behavior

Dependabot properly resolves simple security updates for Yarn dependencies.

## 😯 Current Behavior

A combination of Yarn v1 bugs and automation defaults cause Dependabot PRs to be useless. These are the current steps needed to resolve simple package updates:

1. Check out Dependabot's branch
2. rebase with master
3. revert the dependabot commit (for the paper trail)
4.a open `yarn.lock` and find the entry for the package, delete it
4.b if there are multiple separate entries, dissect why and see if any apply: backported fixes, out-of-date dependent packages, unmerged duplicates, other general nonsense
5. `yarn --ignore-scripts` (grabs the latest version to replace what got deleted, and adds any new resolutions if any)
6. `yarn-deduplicate` (install it globally with either NPM or Yarn if you don't have it)
7. `yarn --ignore-scripts` (the dedupe sometimes doesn't sort the versions)
8. commit and force-push

## 💁 Possible Solution

Add a custom `dependabot.yml` file to manage how Dependabot resolves new dependency updates: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/customizing-dependency-updates

## 🔦 Context

This may become less of an issue if/when we switch from Yarn 1.

## 💻 Examples

https://github.com/microsoft/fast/pulls?q=is%3Apr+author%3Aapp%2Fdependabot

**Comment by janechu** [comment]
During the updates to release `@microsoft/fast-element` v2 this will no longer be an issue as we will move to npm over yarn.
