### ISSUE TITLE
fix: dialog does not detect fast elements with closed shadow dom as tabbable/focusable.

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#5291]
# 🐛 Bug Report
Because dialog (and Toolbar?) relies on checking element.shadowRoot to determine if a fast element is focusable this check fails with elements that have closed shadow roots (like fluent-button, for example).

**Comment by chrisdholt** [comment]
@scomea I think that anything in closed shadow DOM with regard to this behavior should likely be expected to use `tabindex="0"`. Curious of @EisenbergEffect's thoughts here, but I'm not sure we'll be able to do much consistently with how the intent of "closed" is to make it near impossible to query or tap into the shadow root.

**Comment by scomea** [comment]
I believe the best we can do is assume that a fast-element with delegatesFocus is also tabbable.  The biggest issue here is that fluent versions of components like button have closed roots.

**Comment by chrisdholt** [comment]
> I believe the best we can do is assume that a fast-element with delegatesFocus is also tabbable. The biggest issue here is that fluent versions of components like button have closed roots.

Fluent defaults to open - any implementation which is closed is now on the implementation and not the default component set. Just as FYI :)

**Comment by chrisdholt** [comment]
Closing based on the above conversation - if we gather feedback from the community here, more than happy to dig in on how we might address this, but I think this was point in time and implementation specific for folks running in closed mode.
