### ISSUE TITLE
fix: setting active tab does not always update active indicator in fast-tabs

### ISSUE THREAD

**Issue by brianehenry** [microsoft/fast#5296]
# 🐛 Bug Report

Setting the active tab programmatically with the `activeid` property does not always position the active tab indicator correctly.

## 💻 Repro or Code Sample

```html
<fast-tabs id="tabs">
    <fast-tab slot="tab" id="1">Tab one</fast-tab>
    <fast-tab slot="tab" id="2">Tab two</fast-tab>
    <fast-tab slot="tab" id="3">Tab three</fast-tab>
    <fast-tab-panel slot="tabpanel">Tab panel 1</fast-tab-panel>
    <fast-tab-panel slot="tabpanel">Tab panel 2</fast-tab-panel>
    <fast-tab-panel slot="tabpanel">Tab panel 3</fast-tab-panel>
</fast-tabs>
```
```js
const tabs = document.getElementById('tabs');
tabs.activeid = '2';
// Active tab is now tab two, and active indicator is moved appropriately
tabs.activeid = '1';
// Active tab is now tab one, but active indicator is still positioned under tab two
```

## 🤔 Expected Behavior

Active indicator moves to active tab when active tab is set via the `activeid` property.

## 😯 Current Behavior

Active indicator is sometimes incorrectly positioned after setting the `activeid` property.

![tab-active-indicator](https://user-images.githubusercontent.com/5454342/137963335-e6c1f46b-614b-4be2-beec-4253fff74c7c.gif)

## 🔦 Context

I want to be able to set the active tab programmatically. 

## 🌍 Your Environment

* OS & Device: Windows PC
* Browser: Microsoft Edge
* Version: @microsoft/fast-foundation: 2.12.0

**Comment by chrisdholt** [comment]
Closing as the fast components package has been deprecated.
