### ISSUE TITLE
Add aliases to slot names

### ISSUE THREAD

**Issue by michaeldbrandt** [microsoft/fast#5297]
# 🙋 Feature Request

It should be possible to easily add new names to existing slots on FAST components.

For example, it's sometimes helpful for documentation to specify that icons should be placed in the `icon` slot, with the component designer deciding the location and behavior of the icon slot.

## 🤔 Expected Behavior

When composing a component, it should be possible to specify an alias, or list of aliases for an existing slot.  This might be accomplished through adding a property on the object passed to the compose function, or through a modification to the component template.

## 😯 Current Behavior

Currently, there's no way to simply rename a slot without having other effects on the behavior of components.  For example, the menu's indent behavior depends on icons being slotted into the start slots only.  Any attempt to use another slot name and to project content into the existing slots breaks this indenting.

## 💁 Possible Solution

The ideal behavior I envision is setting a property on the object passed to the compose function that specifies an alias for an existing slot.  For example, we had some success using this pattern on certain components to put a new slot into the default content of the start slot:

    export const myComponent= Component.compose({
        ...
        start: html`<span part="icon"><slot name="icon"></slot></span>`,
        ...
    });

Note: This breaks the menu-item indenting as mentioned above, since it's looking for a [slot="start"] selector in the light DOM to know if something has been slotted.

A property called `start-alias` or similar that allowed a string or array of names to alias would be much cleaner and easier to use.  Something like this:

    export const myComponent= Component.compose({
        ...
        start-alias: "icon",
        ...
    });

Another option would be to allow an extra segment of template to be specified.  That would allow things like projecting content into an existing slot, similar to the example in the shadow DOM docs page: https://www.fast.design/docs/fast-element/working-with-shadow-dom

    <slot name="uber-avatar" slot="avatar">      
            
    </slot>

While you currently can modify the template to add a new slot and project that content into an existing slot, this requires copying the entire template into your own codebase along with all the maintenance that requires.  Allowing some kind of inheritance for templates would make this a better option.

## 🔦 Context

We would ultimately like to have a slot named "icon" on all our components to simplify the API for our users.  At the moment in our code base, this `icon` slot would always be an alias of `start`, but could vary.

One reason we'd like this is that we automatically generate components for common icons, and having a consistent slot name makes this easier.  For example, our button might choose to map the `icon` slot to `end` while the menu-item could map `icon` to `start`, but the icon itself would not need to care about this detail.

**Comment by chrisdholt** [comment]
Good feedback, perhaps we can do an investigation to see how feasible this would be or how potentially painful to maintain or manage this could end up.

**Comment by chrisdholt** [comment]
I think that some of what is enumerated in #5849 for the future of `fast-foundation`. @EisenbergEffect as FYI w/r/t template customization.

**Comment by EisenbergEffect** [comment]
Yep. I think this can be easily handled as part of the new foundation APIs I thinking of.

**Comment by janechu** [comment]
With the re-alignment goals of the FAST project (see #6955) the `@microsoft/fast-foundation` package will be deprecated.
