### ISSUE TITLE
feat: add panel component to fast

### ISSUE THREAD

**Issue by Cobra86** [microsoft/fast#5300]
# 🙋 Feature Request
Could you please add the panel component to fast ?

## 🔦 Context
Panel is overlaid on top of a page and slides in from the side. 
It's easy way to access other component.

## 💻 Examples
MS Fluent UI
https://developer.microsoft.com/en-us/fluentui#/controls/web/panel

**Comment by LuohuaRain** [comment]
I love this Feature Request!

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
