### ISSUE TITLE
feat: Add exported ECMAScript modules to fast-animation package

### ISSUE THREAD

**Issue by msmithNI** [microsoft/fast#5304]
# 🙋 Feature Request

Currently the fast-animation package exports CommonJS modules, but not ECMAScript modules.

If fast-animation is used in an Angular application, this triggers a warning at build-time, as [CommonJS dependencies are discouraged for Angular projects](https://angular.io/guide/build#configuring-commonjs-dependencies) (harder to optimize / can increase the bundle size)

## 🤔 Expected Behavior

fast-animation package has ECMAScript module exports (perhaps in addition to CommonJS module exports, for anyone currently relying on them), similar to `fast-foundation` and `fast-components`

> `npx is-esm @microsoft/fast-foundation`
> `√ Yes`

## 😯 Current Behavior

> `npx is-esm @microsoft/fast-animation`
> `‼ No`

Current warning seen when an Angular app pulls in fast-animation:
> Warning: [...]index.js depends on '@microsoft/fast-animation'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

## 💁 Possible Solution

Update or remove [fast-animation/lib/tsconfig.json](https://github.com/microsoft/fast/blob/master/packages/utilities/fast-animation/lib/tsconfig.json#L5) which is currently specifying CommonJS.

#825 changed fast-animation back to CommonJS (to prevent an unexpected breaking change).

Suggestion is to provide both CommonJS + ECMAScript module exports, as a new package version with a major version bump.

## 🔦 Context

My current goal is to use fast-foundation, and new elements extending fast-foundation elements (and using fast-animation) in an Angular application.
This issue can cause suboptimal bundle optimization / increased bundle size in that scenario.

**Comment by chrisdholt** [comment]
Thanks for this issue @msmithNI! We'll look into any implications here but I agree that this is something that we should update.

**Comment by msmithNI** [comment]
@chrisdholt any updates on this issue? I saw that there's a PR for it now, but it hasn't been committed so far.
Thanks.
