### ISSUE TITLE
feat: add callout

### ISSUE THREAD

**Issue by Ciwo-K** [microsoft/fast#5307]
# 🙋 Feature Request

I'd like to use the callout component from Fluent UI. 
For example: to manage the active user (logout option, show information etc.) after the user clicks on a button.
![image](https://user-images.githubusercontent.com/62892625/138274700-abf4210a-8b04-418f-9672-cb1ce91a35fd.png)

**Comment by joecuevasjr** [comment]
This would be a beneficial component to add to the Fluent UI components.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
