### ISSUE TITLE
bug: Number Fields not validating input

### ISSUE THREAD

**Issue by Ciwo-K** [microsoft/fast#5308]
# 🐛 Bug Report

The component 'Number Field' doesn't seem to validate user input. No error message is shown. One can input strings like '@.-_abc' even though the TValue ist set to 'int?'.

## 💻 Repro or Code Sample

`
    
    <h4>Required</h4>
    <FluentNumberField TValue="int?" Required="true"></FluentNumberField>
`

Please open the Fluent component test page -> webcomponents -> Number Field -> type any character into the Number Field with the label Required.
![image](https://user-images.githubusercontent.com/62892625/138272126-b1ab5cc4-2ecd-4e08-9287-29d353c82134.png)

## 🤔 Expected Behavior

The component should only accept valid numbers as input or a customizable validation error message (for localisation) is shown when users input invalid data.

## 😯 Current Behavior

Users can input invalid data into Number Fields. No validation error message is shown.

## 🌍 Your Environment

Windows, Chrome (Version 94.0.4606.81), fast-blazor (Version 0.4.0)

**Comment by chrisdholt** [comment]
@robarbms did this get closed? If so can you link the PR?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
