### ISSUE TITLE
feat: enable components build with static definition (no decorator) to register with the design system

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5313]
# 🙋 Feature Request

Provide easier and more foolproof APIs for components defined without decorators.

## 🤔 Expected Behavior

It should be possible to register a component defined with a static `definition` field by passing it to `DesignSystem#register`. Doing so should call `FASTElement.define` behind the scenes.

## 😯 Current Behavior

Passing a component directly to `DesignSystem#register` does nothing.

## 💁 Possible Solution

This needs some research, put perhaps we can enable discovery of things passed to `register` that don't implement the `Registry` interface. Quick and dirty solution would be to inspect everything for a hard-coded `definition` property and then turn that into a registry that calls `FASTElement.define`. However, that's a one-off type of solution. Maybe we can come up with something a little nicer. For example, what if `FASTElement` implemented a static `register` method and then inside of that called `FASTElement.define` passing `this` which would point to the current subclassed type? Would that enable any FASTElement to define itself through DI registration? I *think* so but need to explore a bit.

## 🔦 Context

I witnessed someone attempt to actually do this. It seemed intuitive to them even though it didn't work. So, I'm thinking that maybe we should make it work.

## 💻 Examples

```ts
class Foo extends FASTElement {
  private static definition = {
    //...
  };
}

provideFASTDesignSystem().register(Foo);
```

**Comment by janechu** [comment]
With the removal of the `DesignSystemProvider` this issue is no longer relevant.
