### ISSUE TITLE
fix: Selecting disabled tree items in the FAST TreeView issues 'selected-change' events

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#5322]
# 🐛 Bug Report

As the description states, when clicking on a tree item inside a FAST TreeView the 'selected-change' event [will be emitted](https://github.com/microsoft/fast/blob/45f000f038302d31636bccd85cf20a366aad7a0b/packages/web-components/fast-foundation/src/tree-item/tree-item.ts#L133), even if the TreeItem has the 'disabled' flag set, which will prevent it from becoming "selected" (having the `selected` attribute applied to it).

This seems incorrect.

## 🤔 Expected Behavior

Clicking on a disabled TreeItem does not result in that TreeItem issuing a `selected-change` event.

## 😯 Current Behavior

Clicking on a disabled TreeItem results in a `selected-change` event being issued, despite the fact that the TreeItem `selected` state does not change.

## 💁 Possible Solution

Check if the TreeItem is disabled before emitting the `selected-change` event.

## 🔦 Context

This isn't really an issue for us, as we have an extended TreeItem that ultimately allows us to provide us the behavior we expect.

## 🌍 Your Environment

Windows desktop. Chrome.

**Comment by chrisdholt** [comment]
@rajsite just an update - @eljefe223 is running an audit and addressing all instances where disabled controls still emit events. This should be addressed as part of that.

**Comment by rajsite** [comment]
@chrisdholt thanks! I appreciate the update :)

**Comment by eljefe223** [comment]
Have a PR up that addresses the above https://github.com/microsoft/fast/pull/5421

This fixes the selected change event from being fired, however I think we should investigate moving the click event that assigns the `selected-change` event from the root template to the `positioning-region`. This is would ensure that only the click event fires on the item itself and not when a Tree Item's children are clicked.

Click event fires on entire region rather that just the red highlighted:

![image](https://user-images.githubusercontent.com/37851214/144108288-e7d649dc-7daa-43f0-91f8-6b921798d154.png).

Another reason this is an issue is if the Tree Item does not span the entire width of the Tree clicking outside the Tree Item would select it's parent.

With this change we could simply prevent `pointer-events` via css on a disabled TreeItem:

```css
fast-tree-item([disabled]) {
    pointer-events: none;
}
```

**Comment by chrisdholt** [comment]
> Have a PR up that addresses the above #5421
> 
> This fixes the selected change event from being fired, however I think we should investigate moving the click event that assigns the `selected-change` event from the root template to the `positioning-region`. This is would ensure that only the click event fires on the item itself and not when a Tree Item's children are clicked.
> 
> Click event fires on entire region rather that just the red highlighted:
> 
> ![image](https://user-images.githubusercontent.com/37851214/144108288-e7d649dc-7daa-43f0-91f8-6b921798d154.png).
> 
> Another reason this is an issue is if the Tree Item does not span the entire width of the Tree clicking outside the Tree Item would select it's parent.
> 
> With this change we could simply prevent `pointer-events` via css on a disabled TreeItem:
> 
> ```css
> fast-tree-item([disabled]) {
>     pointer-events: none;
> }
> ```

Thanks for this @eljefe223 - I agree we should take this as a follow-up and solve the immediate issue. There's definitely a tension here as I think we want the event fired from the node w/ role="treeitem". Let's plan on taking that as a follow-up for sure.
