### ISSUE TITLE
rfc: error codes

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5323]
# 💬 RFC

FAST should provide more and better error messages to designers and developers using the tech stack. This could be accomplished by using organized error codes accompanied by a dedicated documentation page and perhaps an optional debug add-on.

## 🔦 Context

Our error messages don't provide adequate information to users of the libraries. We need to address this issue in a way that is scalable across libraries and without bloating our packages.

A few goals would be:

* More error messages for fail scenarios rather than silent failures.
* More descriptive messages with accompanying potential resolutions.
* Do not make the packages larger by embedding lots of strings.
* Errors/messages should be organized.
* Error messages and resolutions should be updatable without needing to ship a library update.
* The system should be extensible.

## Technical Proposal

`@microsoft/fast-element` should expose a method called `errorCode` with the following signature:

```ts
export function errorCode(packageId: number, areaId: number, errorId: number): Error;
```

Internally, we would remove `new Error` code and replace it with a call to this function. For example, we have code like this today:

```ts
if (definition === void 0) {
    throw new Error("Missing FASTElement definition.");
}
```

Which would be changed to this:

```ts
if (definition === void 0) {
    throw errorCode(1, Area.components, Code.componentDefinitionNotFound);
}
```

The number `1` is a global identifier for the `fast-element` package. `Area` and `Code` would be internal [const enums](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums) that return numbers. The error that was thrown would result in a message something like this:

```shell
FAST Error 001006001: More info at https://www.fast.design/docs/errors/001006001
```

The implementation of `errorCode` would simply take the number inputs and construct an `Error` instance with the above format. We would then have an errors section of our documentation, with a dedicated page for each error message. These would be written in Markdown like the rest of our documentation so the community can also help us improve the messages and resolutions through the normal contribution process. Improvements to the messages and resolutions would not need a package release.

Additionally, we could have the `errorCodes` function check for a globally available debug module. If present, it could pass the code along. That module could take the error code, construct an HTTP request to fetch the documentation page, extract the content, and push it to the console. This would be a separate debug script tag that could be added to the page. This isn't something that's required for the first version of this feature.

**Comment by KingOfTac** [comment]
Would library authors be able to use this to provide errors in packages that use or extend FAST, or is it limited to being internal to FAST only?

**Comment by EisenbergEffect** [comment]
Not planning anything in the design that would be limiting. We could do something like "reserve" the first X number of package ids for ourself I imagine, and maybe reserve ranges for various open source libraries as well. I hadn't thought about that as I was mostly thinking of this in order to solve some of our own issues with embedding error messages and package size.

**Comment by EisenbergEffect** [comment]
The thing I'm not planning is building any kind of robust logging framework, for example. This would be dead simple, very small mechanism, for a very specific purpose.

**Comment by KingOfTac** [comment]
A specific case that came to mind when reading the proposal is, say someone creates a component that extends one of the FAST components and add new functionality to the component but want to provide errors that are consistent with the errors emitted from FAST.

**Comment by EisenbergEffect** [comment]
Makes sense. Let me think through that a bit.

**Comment by KingOfTac** [comment]
Maybe `fast-element` could expose an additional configuration function that authors could call and provide an object that gets merged with the existing options that are internal to FAST. 

Possibly something like:
```ts
import { defineErrorCodes } from '@microsoft/fast-element';

enum Areas {
    'exampleComponents',
}

enum Codes {
    'exampleComponentDefinitionNotFound' = 'path-to-my-libary-docs'
}

defineErrorCodes({
    areas: Areas,
    codes: Codes
});
```

This does get tricky if someone decides to use two third-party libraries that both extend FAST. I don't really have an idea on how configuration conflicts between packages would get resolved, and maybe that work would be too complicated for something that authors may not be interested in.

However, what sparked my initial comment was from an app author's perspective it would make resolving errors a lot quicker if you know errors from FAST and FAST-derived libraries follow the same format:
```
FAST Error 001006001: More info at https://www.fast.design/docs/errors/001006001
```
```
EXAMPLE-LIBRARY Error 001006088: More info at https://www.example-library.com/errors/001006088
```

Another idea to keep the complexity to a minimum is to just provide guidance documentation for creating FAST-like errors as a part of the `creating-a-component-library` docs.

**Comment by RandomEngy** [comment]
Would we have a way to tell what template was failing? We have dozens on the page and we just got this error stack report:

```
TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.\n    
at r.insertBefore (https://assets.msn.com/bundles/v1/edgeChromium/latest/microsoft.7922a21dd03080d936db.js:518:6682)\n    
at v.f [as updateTarget] (https://assets.msn.com/bundles/v1/edgeChromium/latest/microsoft.7922a21dd03080d936db.js:518:14511)\n    
at v.handleChange (https://assets.msn.com/bundles/v1/edgeChromium/latest/microsoft.7922a21dd03080d936db.js:518:16215)\n    
at x.notify (https://assets.msn.com/bundles/v1/edgeChromium/latest/microsoft.7922a21dd03080d936db.js:518:8674)\n    
at x.call (https://assets.msn.com/bundles/v1/edgeChromium/latest/microsoft.7922a21dd03080d936db.js:1186:10121)\n    
at c (https://assets.msn.com/bundles/v1/edgeChromium/latest/microsoft.7922a21dd03080d936db.js:1:10151)\n    
at processUpdates (https://assets.msn.com/bundles/v1/edgeChromium/latest/microsoft.7922a21dd03080d936db.js:1:10958)",
```

Knowing what kind of problem would be nice, but some info like this would be really helpful:

* Which element this template was being filled out for
* Which specific template had the issue
* Where in the template did we have the problem

Are you going to try to use const enums for the areas and codes?
