### ISSUE TITLE
fix: gradient covers first item in horizontal-scroll

### ISSUE THREAD

**Issue by robarbms** [microsoft/fast#5335]
# 🐛 Bug Report

When using a left gradient in horizontal-scroll, the first item will scroll under it and be partially obscured.

## 🤔 Expected Behavior

The first item should be fully visible.

## 😯 Current Behavior

Scrolling past the first item will scroll the last full in view item to the start with the left gradient going over it.

## 💁 Possible Solution

Possible fixes:
The item stops short of the gradient. Stops would need to pre-calculate where gradients end.

There could be states. Start, middle, end. We could show the left gradient only when it reaches the end.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
