### ISSUE TITLE
Turn on noImplicitAny and strictPropertyInitialization in `fast-element` and resolve errors

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5337]
As part of #5303 we turned off `@typescript-eslint/typedef` globally as it was overwritten across multiple packages. As part of that, we turned on `noImplicitAny` and `strictPropertyInitialization` for all packages. Turning this on revealed several issues related to both tsconfig settings in `fast-element` and so it was turned off explicitly for that package. This issue exists to track turning that back on and resolving the errors.

**Comment by m4thieulavoie** [comment]
@chrisdholt I can take this one too and work on it tomorrow 👍

**Comment by m4thieulavoie** [comment]
@chrisdholt I think we can close this issue as this will be included in [fast-element-2](https://github.com/microsoft/fast/pull/5357#issuecomment-957534482)

**Comment by janechu** [comment]
Looks like this was closed with #5357.
