### ISSUE TITLE
Turn on `noImplicitAny` and `strictPropertyInitialization` for `fast-components`

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5339]
As part of #5303 we turned off @typescript-eslint/typedef globally as it was overwritten across multiple packages. As part of that, we turned on noImplicitAny and strictPropertyInitialization for all packages. Turning this on revealed several issues related to both tsconfig settings in fast-components and so it was turned off explicitly for that package. The errors should be fixed and addressed as part of this issue and the code should be tested to ensure that there are no breaks or side effects of the change. This issue exists to track turning that back on and resolving the errors.

**Comment by m4thieulavoie** [comment]
@chrisdholt I'll look at this one too 👍

**Comment by m4thieulavoie** [comment]
@chrisdholt https://github.com/microsoft/fast/pull/5354 is ready for review too :ok_hand:
