### ISSUE TITLE
Refactor Anchored Region stories to remove non-null-assertions

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5340]
As part of #5303 we added configuration to disallow non-null-assertions. Anchored region stories within `fast-components` includes several non-null-assertions which should be fixed-up. This task exists to track the removal of the flag disabling that check and fix up the necessary code to remove the warnings.

**Comment by m4thieulavoie** [comment]
@chrisdholt I would be happy to take care of that if you want to assign this issue to me 👍

**Comment by chrisdholt** [comment]
> @chrisdholt I would be happy to take care of that if you want to assign this issue to me 👍

Done!
