### ISSUE TITLE
fix: disabled menu items are still keyboard focusable

### ISSUE THREAD

**Issue by caseyfaber** [microsoft/fast#5342]
# 🐛 Bug Report

If you have `disabled` on a menu item, you can't click it, but you can still use the keyboard to focus on it.

## 💻 Repro or Code Sample

```html
<fast-menu>
    <fast-menu-item>Menu item 1</fast-menu-item>
    <fast-menu-item disabled>Menu item 2</fast-menu-item>
    <fast-menu-item>Menu item 3</fast-menu-item>
</fast-menu>
```

1. Go to https://explore.fast.design/components/fast-menu
2. Add `disabled` to of the `<fast-menu-item>` elements.
3. Tab to the menu.
4. Press the down arrow key to the menu item.

## 🤔 Expected Behavior

I believe it should skip the disabled item.

## 😯 Current Behavior

It highlights the disabled item.

Maybe related, if you do click a disabled item with your mouse, it will still run click events, but if using menuitemcheckbox or menuitemradio roles, it correctly won't change the state of those.

Also possibly related... pushing Enter on any of the items (disabled or not) will *not* run click events.

## 💁 Possible Solution

The method `handleMenuKeyDown()` is adding/subtracting to focus the next element, and doesn't check if the menu item is disabled or not.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Chrome
* Version: fast-foundation 2.21.0

**Comment by caseyfaber** [comment]
Thank you! I guess I was expecting disabled behavior that <fast-select> uses, looks like that is not the correct expectation for menu. I am closing this issue.

**Comment by chrisdholt** [comment]
> Thank you! I guess I was expecting disabled behavior similar to `<fast-select>`, looks like that is not the correct expectation for menu. I am closing this issue.

No worries at all - when I’m doubt please do file an issue! Thanks!
