### ISSUE TITLE
Refactor `fast-colors` to support tsconfig with `noImplicitAny`, `strictNullChecks` and `strictPropertyInitialization`

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5343]
As part of #5303 we turned off `@typescript-eslint/typedef` globally as it was overwritten across multiple packages. As part of that, we turned on `noImplicitAny`, `strictNullChecks`, `strictPropertyInitialization` for all packages. Turning this on revealed several issues related to both tsconfig settings in `fast-colors` and so it was turned off explicitly for that package. The errors should be fixed and addressed as part of this issue and the code should be tested to ensure that there are no breaks or side effects of the change. This issue exists to track turning that back on and resolving the errors.

**Comment by imrishabh18** [comment]
Hey @chrisdholt! Is this issue still valid. I would like to contribute to this project, and would like to know the first few steps to resolve this issue.

**Comment by janechu** [comment]
The `@microsoft/fast-colors` package has been removed and deprecated.
