### ISSUE TITLE
Turn on `strictNullChecks`, `strictPropertyInitialization` for `fast-web-utilities` in tsconfig

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5344]
As part of #5303 we turned off `@typescript-eslint/typedef` globally as it was overwritten across multiple packages. As part of that, we turned on `strictNullChecks` and `strictPropertyInitialization` for all packages. Turning this on revealed several issues related to a few tests and function implementations in `fast-web-utilties` and so it was turned off explicitly for that package. The errors should be fixed and addressed as part of this issue and the code should be tested to ensure that there are no breaks or side effects of the change. This issue exists to track turning that back on and resolving the errors.

**Comment by NiteshSethi09** [comment]
Hey @EisenbergEffect, may you assign me this issue. I'd like to work on this!

**Comment by NiteshSethi09** [comment]
Hi @chrisdholt! I've successfully made changes for this issue and the code is merged in the codebase. May you please close this issue?

**Comment by NiteshSethi09** [comment]
Thank you for the information @chrisdholt.
