### ISSUE TITLE
chore: convert functions for templates and styles to `FoundationElementTemplate` type

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#5347]
# 🙋 Feature Request

The templates in `fast-foundation` and the styles in `fast-components` should use the `FoundationElementTemplate` type.

## 😯 Current Behavior

Each function for every template and style has their own individual type signature, which can cause collisions when working across projects with different `foundation` bases.

Here's an example of a template that uses the generic function typing:

```ts
export const componentTemplate: (
    context: ElementDefinitionContext,
    definition: ComponentOptions
> = (
    context: ElementDefinitionContext,
    definition: ComponentOptions
) => html`
```

Here's an example of a style that uses the generic function typing:

```ts
export const componentStyles: (
    context: ElementDefinitionContext,
    definition: ComponentOptions
) => ElementStyles = (
    context: ElementDefinitionContext,
    definition: ComponentOptions
) => css`
```

## 🤔 Suggested Behavior

The `FoundationElementTemplate` type takes two parameters, one for the return type and one for the `definition`. This type is a wrapper for `LazyFoundationOption<T, K>` but it ensures that `K` extends `FoundationElementDefinition` and at least equals it.

Here's  what it looks like for templates:
```ts
export const componentTemplate: FoundationElementTemplate<
    ViewTemplate<Component>,
    ComponentOptions
> = (context, definition) => html`
```

Here's what it looks like for styles:
```ts
export const componentStyles: FoundationElementTemplate<ElementStyles, ComponentOptions> = (
    context,
    definition
) => css`
```

## 🔦 Context

This will reduce the surface area for conflicts with newer versions of the API Extractor by allowing TypeScript to properly import the types at a higher level, rather than defaulting to `import()` types. These `import()` types often cause conflicts when working with multiple fast-based component libraries in one project.

**Comment by m4thieulavoie** [comment]
I'm happy to contribute a PR for this one, feel free to assign it to me @EisenbergEffect :)

**Comment by EisenbergEffect** [comment]
Done! Thanks for the help! 😄
