### ISSUE TITLE
fix: template partials in component definitions passed as string literals

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#5349]
# 🐛 Bug Report

Partials that are provided in component definitions are set as template literals, though they should be handled as `html` templates.

## 💻 Repro or Code Sample

```ts
export const fastComponent = Component.compose({
    baseName: "component",
    template,
    styles,
    defaultContent: `
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M3.8 3h12.4c.4 0 .8.3.8.8v12.4c0 .4-.3.8-.8.8H3.8a.8.8 0 01-.8-.8V3.8c0-.5.3-.8.8-.8zm12.4-1H3.8C2.8 2 2 2.8 2 3.8v12.4c0 1 .8 1.8 1.8 1.8h12.4c1 0 1.8-.8 1.8-1.8V3.8c0-1-.8-1.8-1.8-1.8zM14 9H6v2h8V9z"/>
        </svg>
    `,
// ...
```

## 💁 Possible Solution

```ts
import { html } from "@microsoft/fast-element";

export const fastComponent = Component.compose({
    baseName: "component",
    template,
    styles,
    defaultContent: html`
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M3.8 3h12.4c.4 0 .8.3.8.8v12.4c0 .4-.3.8-.8.8H3.8a.8.8 0 01-.8-.8V3.8c0-.5.3-.8.8-.8zm12.4-1H3.8C2.8 2 2 2.8 2 3.8v12.4c0 1 .8 1.8 1.8 1.8h12.4c1 0 1.8-.8 1.8-1.8V3.8c0-1-.8-1.8-1.8-1.8zM14 9H6v2h8V9z"/>
        </svg>
    `,
// ...
```

## 🔦 Context

Components which have definition properties set as string literals:
* fastAccordionItem
* fastCheckbox
* fastCombobox
* fastFlipper
* fastMenuItem
* fastNumberField
* fastProgress
* fastProgressRing
* fastRadio
* fastSelect
* fastSlider
* fastSwitch
* fastTreeItem

**Comment by EisenbergEffect** [comment]
I think the final template could handle either a string or a template. Do we want to type these properties to enable either? It's cheaper to use strings if templating features (e.g. binding) aren't needed in the content. So, maybe we leave things as they are with the strings but just change the types to allow either for more end-user flexibility. Thoughts?

**Comment by radium-v** [comment]
I think allowing strings is good, since tools like Webpack typically import SVG as raw string imports. We can and should still allow strings since there are implementations in the wild that use strings and we don't want those to break.

For me, the main downside to using strings in our own compositions is that syntax highlighting (#4001) doesn't apply to these partials, which makes them difficult to work with. If we use an import technique that allows these strings to be maintained as their content dictates (SVG or HTML), then this issue will be less apparent.

**Comment by m4thieulavoie** [comment]
@EisenbergEffect @radium-v I'm happy to tackle this issue, feel free to assign it to me :+1: 
I see that each content attributes already have the `string | SyntheticViewTemplate` type, so that shouldn't introduce any breaking change for third-party implementations, whereas it'll add extra typings to each `fast*` components :)
