### ISSUE TITLE
fix: 'change' event for menu items with a role of "menuitemcheckbox" is emitted twice

### ISSUE THREAD

**Issue by caseyfaber** [microsoft/fast#5358]
# 🐛 Bug Report

## 💻 Repro or Code Sample

I have a code sample here that is logging to the console the textContent and checked props in the 'change' listener.: https://codesandbox.io/s/menu-item-double-change-event-sowb5?file=/src/index.js

If you click a menuitem, it logs one change event.
If you click a menuitemradio, it logs two change events - one for the radio getting unchecked and one for the radio getting checked.
If you click a menuitemcheckbox, it logs two change events for the same item.

## 🤔 Expected Behavior

menuitemcheckbox should just emit the event once on change.

## 😯 Current Behavior

menuitemcheckbox changes emit change event twice.

## 💁 Possible Solution

This is caused because inside the `invoke()` method of menu-item, 'change' is being emitted, but it is also changing the 'checked' prop, and `checkedChanged` is also emitting 'change'. I believe it should not be emitted for menuitemcheckbox in `invoke()` (just like it is not doing so on menuitemradio).

## 🔦 Context

I am trying to make some events happen when checkboxes are changed based on their checked status, but don't want them to happen twice.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Chrome, Edge
* Version: fast-foundation 2.21.0

**Comment by chrisdholt** [comment]
Thanks @caseyfaber! @eljefe223 could you take a look at this when you have a second?
