### ISSUE TITLE
fix: NumberField does not visually reflect the component's 'value' when 'value' is assigned programatically

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5359]
# 🐛 Bug Report
When `NumberField.value` is assigned via JavaScript, the component's `value` is not reflected to the inner `<input />` control's `value`. The effect of this is that there is no visual representation of a assigned value (or changed value). 

## 💻 Repro or Code Sample
Min repro here: https://stackblitz.com/edit/typescript-7hcdkp?file=index.ts

## 🤔 Expected Behavior
Assigning a `value` to the control via JavaScript should visually reflect the assigned `value`.

**Comment by radium-v** [comment]
The `control.value` doesn't seem to update to match the value when it's forced to change after the min/max range changes:

1. set `min` to 0 and `max` to 100
2. set `value` to 100
3. set `max` to 10

The `value` and `currentValue` return 10 but the `control.value` stays at 100 until I interact with the control.
