### ISSUE TITLE
docs: add "search" in the documentation pages

### ISSUE THREAD

**Issue by facowk** [microsoft/fast#5379]
# 🙋 Documentation Request

Often is difficult to find a specific argument inside the documentation and you've to look inside many pages

## 💁 Possible Solution

Adding a search field?

**Comment by EisenbergEffect** [comment]
Closing this one as a duplicate. We've got this tracked already and are hoping to address this soon.

**Comment by facowk** [comment]
@EisenbergEffect oh, sorry. I've searched in the opened issues, but i didn't found it!

**Comment by EisenbergEffect** [comment]
No problem. Here's project board that has a few improvements listed: https://github.com/microsoft/fast/projects/19
We've got someone hopefully joining our team soon to help with some of this. We welcome your contributions as well!
