### ISSUE TITLE
docs: add package containing the DI class to the Dependency Injection page

### ISSUE THREAD

**Issue by facowk** [microsoft/fast#5380]
# 🙋 Documentation Request

The [Dependency Injection page](https://www.fast.design/docs/apps-and-experiences/dependency-injection) doesn't specify the package (fast-foundation?) containing the DI class.

## 💁 Possible Solution

Adding the package to the page.

Adding the package containing the classes and methods of the documentation could be useful for all the pages.

**Comment by EisenbergEffect** [comment]
Good feedback! Thank you! Yes, it's fast-foundation. We'll get this fixed.
