### ISSUE TITLE
fix: unable to set position of combobox and select programmatically

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#5383]
# 🐛 Bug Report

Both combobox and select have a `position` attribute that forces the menu to appear `above` or `below`. Both components work as expected when setting the attribute explicitly.

```html
<fast-select position="above">
  <fast-option value="1">Option 1</fast-option>
  <fast-option value="2">Option 2</fast-option>
  <fast-option value="3">Option 3</fast-option>
</fast-select>

<fast-combobox position="above">
  <fast-option value="1">Option 1</fast-option>
  <fast-option value="2">Option 2</fast-option>
  <fast-option value="3">Option 3</fast-option>
</fast-combobox>
```

But neither work when setting the attribute or property programmatically, as demonstrated below.

## 💻 Repro or Code Sample

```html
<fast-select>
  <fast-option value="1">Option 1</fast-option>
  <fast-option value="2">Option 2</fast-option>
  <fast-option value="3">Option 3</fast-option>
</fast-select>

<fast-combobox>
  <fast-option value="1">Option 1</fast-option>
  <fast-option value="2">Option 2</fast-option>
  <fast-option value="3">Option 3</fast-option>
</fast-combobox>

<script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>

<script>
  const combobox = document.querySelector('fast-combobox');
  const select = document.querySelector('fast-select');

  customElements.whenDefined('fast-select').then(() => {
    // Setting the property doesn't work
    select.position = 'above';
    
    // Nor does setting the attribute
    select.setAttribute('position', 'above');
    
    select.open = true;
  });

  customElements.whenDefined('fast-combobox').then(() => {
    // Setting the property doesn't work
    combobox.position = 'above';
    
    // Nor does setting the attribute
    combobox.setAttribute('position', 'above');
    
    combobox.open = true;
  });
</script>
```

Fiddle: https://jsfiddle.net/dpe9k07u/2/

## 🤔 Expected Behavior

The position should be updated when setting the corresponding attribute or property programmatically.

## 😯 Current Behavior

The position doesn't update.

## 💁 Possible Solution

Both components have logic [similar to this](https://github.com/microsoft/fast/blob/6d3dfcc7250a323e13e2168e4335a79e7ccebc66/packages/web-components/fast-foundation/src/select/select.ts#L386) that assigns a value to `this.forcedPosition` in `connectedCallback()`, but it doesn't update if the position changes later.

## 🔦 Context

We discovered this when trying to set the position using the React wrappers, which isn't currently possible because of this bug.

**Comment by chrisdholt** [comment]
@radium-v can you look into this?

**Comment by radium-v** [comment]
The `position` attribute is mapped to the `positionAttribute` property, but this doesn't seem to be a very ergonomic mapping. It should be changed so that the `position` attribute is mapped to the `position` property, which should allow setting both the attribute and the property with the same `positionChanged` observer. The component's internal state would then be handled by a private and internal `_position` property.

**Comment by rajsite** [comment]
Related issue: https://github.com/microsoft/fast/issues/5123
