### ISSUE TITLE
fix: disabled attribute didn't block @click handler in fast-flipper

### ISSUE THREAD

**Issue by akronbook** [microsoft/fast#5385]
## Issue description
When a fast-flipper sets the "disabled" attribute, the @click handler is still triggered. 

## 💻 Repro or Code Sample

https://github.com/akronbook/flipper-disable-bug

## 🤔 Expected Behavior
When the "disabled" attribute is set, the @click handler should NOT be called. 

## 😯 Current Behavior

In the sample code, the @click handler was triggered even though the flipper was disabled. If you keep clicking on the disabled flipper, the page count will keep increasing, which is surprising.

## 🔦 Context
I am trying to disable the flipper in certain conditions in my application. Currently the workaround is to use "when" directive to remove fast-flipper totally from the DOM tree: this is not an ideal solution for us.

## 🌍 Your Environment

* OS & Device: Mac OS
* Browser Google Chrome
* Version fast-components 2.16.2, fast-element 1.6.2

**Comment by chrisdholt** [comment]
@eljefe223 can you investigate this and see about potentially addressing this holistically across all controls? Are there any scenarios where we would want to invoke click or keydown handlers on disable elements?
