### ISSUE TITLE
fix: Tabs jumping around in Vertical Tab mode

### ISSUE THREAD

**Issue by MvandeRuitenbeek** [microsoft/fast#5389]
# 🐛 Bug Report

Tabs component does not outline properly in Orientation.Vertical mode

## 💻 Repro or Code Sample

Create a FluentTabs component with Orientation="Orientation.Vertical"
Create a few tabs.
Put a lot of content in one of the tabs, e.g. 20 lines of text

`
<FluentTabs ActiveIndicator="false" Orientation="Orientation.Vertical">
    <FluentTab>Tab one</FluentTab>
    <FluentTab>Tab two</FluentTab>
    <FluentTab>Tab three</FluentTab>
    <FluentTabPanel>
        Tab one content. This is for testing.
    </FluentTabPanel>
    <FluentTabPanel>
        Tab two content. This is for testing.
    </FluentTabPanel>
    <FluentTabPanel>
        Tab three content. This is for testing.
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
        Tab three content. This is for testing.<br />
    </FluentTabPanel>
</FluentTabs>
`

## 🤔 Expected Behavior

The vertical tabs should stay in place at the top left

## 😯 Current Behavior

The vertical tabs are vertically aligned at the bottom of the content. So whenever you click the top with the large amount of content, then the tabs will jump to the bottom

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Microsoft Edge, Google Chrome
* .NET and FAST

**Comment by chrisdholt** [comment]
@eljefe223 can you dig in here?
