### ISSUE TITLE
fix: DesignToken unexpectedly removing CSS custom property

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5390]
# 🐛 Bug Report
DesignToken is removing CSS custom properties set for an element that is also a DesignToken root when the property is changed back to the *default* value.

## 💻 Repro or Code Sample
https://stackblitz.com/edit/fast-design-e5xbf1?file=components/my-app-root.ts
In the above repro, click the "Black on Yellow" button, then click the "White on Blue" button. Notice that the `--foreground-on-accent-rest` CSS custom property is removed and the text color on accent becomes black instead of white.

## 🤔 Expected Behavior
`--foreground-on-accent-rest` should not be removed and should be assigned white.

## 😯 Current Behavior
This behavior is occurring due to an interaction between the default DesignTokenNode and a DesignTokenNode that is also a DesignTokenRoot. When the token value is set back to white, the value is the same as the upstream default value of the token, so it is removed as a CSS custom property. In this case, we need to detect that this element is configured as a DesignTokenRoot and doesn't have a logical parent that should be emitting CSS custom properties.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by guiherzog** [comment]
I am seeing this issue while working on an Extension that uses the [Webview UI Toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit/issues), which is based on this library.

**Comment by janechu** [comment]
The `@microsoft/fast-foundation` package is being deprecated per #6955.
