### ISSUE TITLE
fix: Unable to install `fast-react-wrapper` due to React peer dependency conflicts

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/fast#5391]
# 🐛 Bug Report

When following the [React integration docs](https://www.fast.design/docs/integrations/react) I (and some [others](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/283#issuecomment-959846833)) have run into issues installing the `fast-react-wrapper` package due to peer dependency conflicts in the installed React version––forcing us to downgrade our `react` and `react-dom` packages to `v16.9.0` in order to install the package.

## 💻 Repro or Code Sample

Try to create a new TypeScript-based CRA app (which installs React `v17` by default now), then try to install the `@microsoft/fast-react-wrapper` package and you should run into install errors (screenshot below).

```bash
npx create-react-app fast-app --template typescript --use-npm
cd fast-app
npm install --save @microsoft/fast-react-wrapper
```

## 🤔 Expected Behavior

The `fast-react-wrapper` package should be installable and work with any version of React or at least it should work with `v16.9.0+`.

## 😯 Current Behavior

<img width="695" alt="Screen Shot 2021-11-16 at 3 07 22 PM" src="https://user-images.githubusercontent.com/39639992/142081443-931632a4-b4cb-424e-abc9-7e7782a10d64.png">

## 💁 Possible Solution

Based on the suggestion of the earlier [comment](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/283#issuecomment-959846833) I linked to you could try to update the `fast-react-wrapper` package.json to include:

```json
"peerDependencies": {
    "react": "^16 || ^17 || ^18"
}
```

With that said, I noted that the [current package.json](https://github.com/microsoft/fast/blob/master/packages/utilities/fast-react-wrapper/package.json#L91-L93) actually uses a syntax that should already include React `v17`, `v18`, and so on. So I'm not entirely sure what's going on here.

## 🌍 Your Environment

* OS & Device: MacOS on MacBook
* Browser: Chrome / VS Code Webview (i.e. Chromium)
* Version: FAST React Wrapper (`v0.1.15`)

**Comment by hawkticehurst** [comment]
> With that said, I noted that the current package.json actually uses a syntax that should already include React `v17`, `v18`, and so on. So I'm not entirely sure what's going on here.

Oh wait, I just remembered a discussion with @chrisdholt where a change in NPM `v7` (which is what I'm using) might be the culprit for this behavior?

**Comment by chrisdholt** [comment]
> > With that said, I noted that the current package.json actually uses a syntax that should already include React `v17`, `v18`, and so on. So I'm not entirely sure what's going on here.
> 
> Oh wait, I just remembered a discussion with @chrisdholt where a change in NPM `v7` (which is what I'm using) might be the culprit for this behavior?

This is kind of both - we have a PR that went in today for this to support >=16.9.0 which will publish tonight. i think you hit the issue immediately because it automatically installs the deps w/ NPM 7+. This should be published and should close out with #5388

**Comment by hawkticehurst** [comment]
Oh whoops, apologies for the unnecessary/duplicate issue in that case! But yay, thanks for addressing this already!

**Comment by chrisdholt** [comment]
No worries - we were tracking this but we had a contribution last night :)
