### ISSUE TITLE
feat: add mechanism to prefix DesignToken CSS Custom Properties

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5397]
# 🙋 Feature Request
A common pattern among UI libraries and application authors is the prefix CSS custom properties with some namespace to prevent name collisions with other code. We would like to support this use-case with DesignToken, so that library authors or application authors have the opportunity to supply or change an `CSSDesignToken`'s CSS custom property.

Currently, `CSSDesignToken`s can define their CSS custom property provided during token creation:
```ts
DesignToken.create({name: "foo", token: "my-foo"}) // --my-foo
```

This means that token creators can *currently prefix a `CSSDesignToken`*. There are two approaches the I think will work to *change* a prefix.
1. Rename the CSS custom property token entirely, eg `myToken.withCSSCustomPropertyName("my-new-name");`
2. Provide a prefix to an existing name, eg `myToken.withPrefix("my-prefix");'

I think I favor the first option because it supports more scenarios. An author could rename to some arbitrary name, an author could *mangle* the names to some hash or unique character set, and an author can prefix (```myToken.withCSSCustomPropertyName(`prefix-${myToken.cssCustomPropertyName}``` presuming CSSDesignToken.cssCustomPropertyName is added as a property)

**Challenges**:
I think in an ideal world there would be a prefix all tokens coming out of a single library easily, something like `DesignSystem.withTokenPrefix("foobar")`. The trouble is that `DesignSystem` doesn't have a good way to know all of the tokens defined by a single library. We could in theory export accept a collection of tokens for this method, `DesignSystem.withTokenPrefix("foobar", tokens)`, but doing so would prevent any tree-shaking that could be taking place of un-necessary tokens so in practice it may not be a useful pattern.

**Comment by janechu** [comment]
I agree, I think the first option is going to give the most flexibility. As far as the challenges go, the developer implementing can devise their own method for tracking the tokens they are using and then changing them to their desired CSS property names.

My only concern would be that in terms of the lifecycle of how DesignTokens work, will we be able to apply an updated CSS custom property token *before* it is applied to the DOM for the custom elements? Specifically I am thinking of the components exported from `@microsoft/fast-components`.

**Comment by nicholasrice** [comment]
Because no CSS custom properties are emitted until a DesignToken root has been registered, so assuming the token rename method gets invoked prior to registering the root then the first emission would be the new name.

I also think it would be a requirement that if the token is changed *after* it has emitted, all emissions would need to tear down the stale CSS custom property and add a new one by the new name.

**Comment by chrisdholt** [comment]
Is the "author" above the original creator of the `DesignToken`? If so, that would mean that the custom properties need to be prefixed at the library level, which I think would be problematic as it removes the "opt-in" nature for library consumers. As a user, if I'm using a single library, why do I care if it's prefixed? If it's not the case, I think it's fine - but I wanted to get clarity on the first use case before digging in further.

**Comment by nicholasrice** [comment]
@chrisdholt yes, "author" refers to a consumer of the library. A library *could* use this method but it wouldn't make sense to do that instead of simply defining the token with the desired name.

**Comment by chrisdholt** [comment]
> @chrisdholt yes, "author" refers to a consumer of the library. A library _could_ use this method but it wouldn't make sense to do that instead of simply defining the token with the desired name.

Thanks for clarifying the usage here! So similar to registering the components, I would essentially "register" the token with a new name. That sounds good and reasonable to me. That allows for either a prefix or a new semantic name that works better for a library user.

**Comment by nicholasrice** [comment]
*sort of*. You don't ever register the token itself, you register a location to emit default values. So actually what I wrote above isn't *entirely* accurate; an author could set a token value for an element *prior* to registering a token root and it would emit a CSS custom property. That is an edge case though, and is covered by the tear CSS custom property down / boot up behavior I'm describing above. The flow would look something like this:

```ts
import { someToken, someComponent  } from "some-library";
someToken.withCSSCustomPropertyName("some-new-name");

// Internally defines the token root during .register()
DesignSystem.getOrCreate().register(someComponent());

// Or Explicitly define the token root
DesignSystem.getOrCreate().withDesignTokenRoot(someElement).register(someComponent())
```

**Comment by janechu** [comment]
Closing this as DesignTokens are no longer part of the FAST projects main goals.
