### ISSUE TITLE
fix: Drop menu clipped in fluent-combobox on Edge

### ISSUE THREAD

**Issue by marinasundstrom** [microsoft/fast#5404]
I have been using the ```fluent-combobox``` in Blazor. 

On Safari it all looks great. The drop menu is floating and visible outside the boundaries of the ```fluent-card```.

But, on Edge it is bound to the card.

```razor
<FluentCard>
  <FluentCombobox @bind-Value="text">
      <FluentOption Value="1">Test 1</FluentOption>
      <FluentOption Value="2">Test 2</FluentOption>
  </FluentCombobox>
</FluentCard>
```

<img width="273" alt="Screenshot 2021-11-18 at 18 15 07" src="https://user-images.githubusercontent.com/919580/142464304-7d4581f2-4beb-42f7-b973-63c3b0b6f96a.png">

**Comment by chrisdholt** [comment]
Thanks @robertsundstrom for the issue - would you say that [this](https://github.com/microsoft/fast/issues/5363) is similar to what you are experiencing? 

As an FYI, that's been closed in favor of implementing https://github.com/microsoft/fast/issues/4971.

**Comment by janechu** [comment]
It seems this issue was filed in the wrong place.
