### ISSUE TITLE
feat: VS Code Plugin

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5408]
# 🙋 Feature Request

A VS Code Plugin that adds better completion in FAST templates.

## 🤔 Expected Behavior

Here's an example of something similar: https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin

## 😯 Current Behavior

Currently, we have basic syntax highlighting of HTML and CSS through other plugils.

## 💁 Possible Solution

We should have an all-in-one VS Code plugin that provides highlighting, completion, linting, etc. for FAST developers.

**Comment by rajsite** [comment]
Our team currently leverages the following extensions for some syntax highlighting during FAST element development in VS code:
- literally-html: https://marketplace.visualstudio.com/items?itemName=webreflection.literally-html
- es6-string-css: https://marketplace.visualstudio.com/items?itemName=bashmish.es6-string-css

**Comment by chrisdholt** [comment]
Potentially could be added to https://github.com/microsoft/fast/pull/4001 (fast-tagged-templates) which just merged.

**Comment by janechu** [comment]
Closing as this no longer falls within the goals of the FAST project #6955.
