### ISSUE TITLE
fix: Incorrect z-index in fast-menu slot="submenu"

### ISSUE THREAD

**Issue by BieleckiLtd** [microsoft/fast#5417]
# 🐛 Bug Report

When you place menu with submenu in a container that does not allow overflow (overflow: hidden) the submenu is not visible (is being cut off). Even placing one menu with submenu in the same container as other controls, close to them, renders the submenu under the other controls.

## 💻 Repro or Code Sample

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            display: flex;
        }
    </style>
</head>
<body>
    <fast-menu>
        <fast-menu-item>Menu item 1</fast-menu-item>
        <fast-menu-item>Menu item 2</fast-menu-item>
        <fast-menu-item>Menu item 3
                <fast-menu slot="submenu">
                    <fast-menu-item>Menu item 3.1</fast-menu-item>
                    <fast-menu-item>Menu item 3.2</fast-menu-item>
                    <fast-menu-item>Menu item 3.3</fast-menu-item>
                </fast-menu>
        </fast-menu-item>
    </fast-menu>
    <fast-menu>
        <fast-menu-item>Menu item 1</fast-menu-item>
        <fast-menu-item>Menu item 2</fast-menu-item>
        <fast-menu-item>Menu item 3
                <fast-menu slot="submenu">
                    <fast-menu-item>Menu item 3.1</fast-menu-item>
                    <fast-menu-item>Menu item 3.2</fast-menu-item>
                    <fast-menu-item>Menu item 3.3</fast-menu-item>
                </fast-menu>
        </fast-menu-item>
    </fast-menu>
    <script type="module" src="https://unpkg.com/@microsoft/fast-components"></script>
</body>
</html>
```

## 🤔 Expected Behavior

Submenu should pop up above any other UI element.

## 😯 Current Behavior

Submenu renders below other controls or is being chopped off.

## 💁 Possible Solution

z-index?
position: fixed?

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Edge, Firefox

**Comment by BieleckiLtd** [comment]
Possibly linked with #3813

**Comment by chrisdholt** [comment]
There could be a couple of issues here - Menu uses Anchored Region, so it should be able to break out of it's container, unless of course that container is the body. In terms of z-index, @robarbms can you dig in here with the z-index issues first as I know you've been looking to address that in Fluent as well.
