### ISSUE TITLE
fix: inconsistent default slot naming in accordian item

### ISSUE THREAD

**Issue by dirthsj** [microsoft/fast#5437]
# 🐛 Bug Report

`fast-accordion`'s definition [available here](https://explore.fast.design/components/fast-accordion) has a name for the default slot; elsewhere the default slot is named empty string.

## 💻 Repro or Code Sample

No code is required. Read the component definition(s) [on the component explorer](https://explore.fast.design/components/) and compare the default slot names.

## 🤔 Expected Behavior

The default slot should be named empty string

## 😯 Current Behavior

The default slot is named item

## 💁 Possible Solution

Rename slot to empty string

## 🔦 Context

I was attempting to generate svelte components with typescript definitions from the JSON definition(s) of the components. I noticed this inconsistency when it caused my generated code to not work as expected until I removed the name from this slot in my generated svelte component.

## 🌍 Your Environment

N/A

**Comment by eljefe223** [comment]
@EisenbergEffect it appears the `accordion` template has a `name` on the default slot. We believe we should just remove the `name`

**Comment by chrisdholt** [comment]
I think the issue here is that removing this will break the current templates for anyone who is projecting using `name`. If we remove those will no longer project.

My proposal here would be to add a generic/default slot in addition to the named slot and then track the removal of that with an issue AND a TODO in the codebase for the next major version.

**Comment by chrisdholt** [comment]
Marking as good first issue for anyone in the community who wants to pick this up.

**Comment by m4thieulavoie** [comment]
@chrisdholt I'm happy to contribute a PR!

**Comment by chrisdholt** [comment]
Thanks!

**Comment by chrisdholt** [comment]
@m4thieulavoie pinging here because I don’t recall your @ on discord. Can you shoot me a message there when you get a second. Thanks again :)
