### ISSUE TITLE
Update Add building blocks UI to use full pane on FAST Documentation site

### ISSUE THREAD

**Issue by Falkicon** [microsoft/fast#544]
### **User benefit**
User will have more space to choose a component to add without having to deal with a bunch of presets above.

### **Problem statement**
Today, the add building blocks UI sits below the presets and building bocks. On smaller screens and more complex components, this can leave very little space to see and navigate building blocks. This also causes challgens with scrollable regions if the pane and the add building blocks UI needs to scroll.

### **Preferred solution**
When the user chooses to add building blocks it will open a new view in the pane that shows only the building blocks. There a user can filter building blocks or choose a building block to add. When a building block is closen, the add building block view will close. A user can exit the add building blocks view wihout adding a building block if desired.

**Comment by chrisdholt** [comment]
@janechu is this still valid with the latest tooling investigations and requirements or can we close as obsolete?

**Comment by janechu** [comment]
@chrisdholt we can close this as obsolete as the development site no longer exists.
