### ISSUE TITLE
feat: add disabling "selection" for parent node fast-tree-item's with child nodes.

### ISSUE THREAD

**Issue by vogtn** [microsoft/fast#5448]
# 🙋 Feature Request

We would like to support a tree-view with parent tree-items that are **not** selectable, but is still able to open and close, [w3](https://w3c.github.io/aria-practices/#:~:text=For%20parent%20nodes%2C%20one%20possible%20default%20action%20is%20to%20open%20or%20close%20the%20node), to access the child elements and select them instead. 

## 🤔 Expected Behavior

From https://explore.fast.design/components/fast-tree-view

```
<fast-tree-view>
    <fast-tree-item selectable="false">Tree item 1<fast-tree-item slot="item">Tree item 1 - 1</fast-tree-item>
    </fast-tree-item>
    <fast-tree-item selectable="false">Tree item 2</fast-tree-item>
</fast-tree-view>
```

## 😯 Current Behavior

Disabled/Selectable currently affects entire tree. 

## 💁 Possible Solution

`Selectable?` attribute  

## 🔦 Context

Our implementation example is a "teams-channel-picker",  we have teams as the parents, and teams's channels as the child nodes. Teams aren't selectable, but the channels are. See the mgt [storybook](https://mgt.dev/?path=/story/components-mgt-teams-channel-picker--teams-channel-picker) teams-channel-picker for example functionality. 

Disabled functionality doesn't support this, as we still want the child nodes selectable. 

## 💻 Examples

Sample, red is not selectable:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11411686/145059295-10e5f28f-117c-47ec-aaec-0d95fe40871f.png)

**Comment by chrisdholt** [comment]
I've updated this issue title to better represent what I think the ask is. From what I've understood from our conversations, currently parent nodes within a tree item (items with child nodes) are _selectable_ and interactive. The one and primary concern I have here (as mentioned offline) is that I'm not sure that can be done in a way that is both standard based and accessible, and so I'm not sure it is something we can for sure add first-party support for.

With that said, I'd like to take the following approach here:

1) Investigate if this is a standard pattern.

2) If this is a standard pattern, we can support it. If it's not a standard pattern, is there something we are doing which makes you taking this approach prohibitive AND is that something we can find a way to enable this. 

The above leaves room for first party support while at the very least identifying what's preventing it and seeing if there is a way we can enable you accomplishing your goals with this scenario.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
