### ISSUE TITLE
rfc: Looking for feedback/suggestions on a Github Discord bot

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#5454]
# Github Discussions Discord Bot

## Background
Per @EisenbergEffect I am creating this RFC for an idea I had to try and bring the github and discord sides of the FAST community closer together.
This project is intended to enhance discussions in the community by allowing members that are either not on discord, or not yet members of the server to participate in discussions created in discord and vice versa.

## Goals
- Must have configuration that allows server owners to specify channels the bot is allowed to operate in.
- Must be able to import existing github discussions on Bot install, if requested by the server owner.
- Must maintain message formatting between github and discord.

## Non-Goals
- The MVP will only provide a link between discussions and threads, any other github or discord message features such as issues, projects, voice channels, etc is considered out of scope.
- Other features can be added later on but trying to keep the initial project as lean as possible.

## Supporting Technologies & Research
- Github has a pretty extensive GraphQL api for discussions that should support all of the initial requirements
- Discord's api allows bots to create, delete, modify, and control just about every aspect of a channel's threads, unless limited by role restrictions or permissions.
- For simplicity and development speed the bot will be written using Node.js.
- As of 9/22/2021. Discord bots can serve Vue-based buttons and select menus to users that interact with them.
  - This would allow the bot to provide better interaction options to users if needed.
  - These types of messages can also be sent as ephemeral messages so that they don't clutter a thread or channel.
  - I don't think custom components are supported at this time as there is no mention of them in the documentation.
- Discord's js package includes markdown formatting helpers that will allow message formatting to remain consistent between the two platforms.

## Gotchas/Challenges
- The biggest challenge I see is when comments are made on the github side, there isn't a clear-cut method for a bot to get notified of the event.
   - This can be addressed via webhooks, and bots can use them so this may be a non-issue in the end, but it does pose a greater challenge than comments coming from the discord side.
- The closest match to github discussions in discord would be threads, however this may make the bot less desirable to use if users are required to change the way they ask questions and participate in discord.
  - I'm not entirely sure yet if this will actually be an issue or the best way to solve it if it is.

## Mapping Conversations Between Platforms
- I haven't gone through all the data structures from both platforms yet, but so far it appears discussions in github are synonymous to threads in discord.
- The different discussion categories in github could be mapped to channels in discord, so for example if someone created a discussion in the Q&A category, the bot would take that and create a new thread in the support channel in discord.
- So far, the category-channel mappings are:
  - General -> General
  - Ideas -> ?
  - Q&A -> Support
  - Show and Tell -> Showcase

## Project Status So Far
- I have done some initial testing of the various apis involved to see if this is something that is doable, and I am fairly confident that it is.
- I have also setup a repo and begun scaffolding the project locally.
- At this point in time I am looking for feature suggestions and feedback on this post in case I have made any false assumptions, or someone thinks I have missed something important.

## Project Timeline
I currently have a lot of time on my hands and was looking for a new project to work on, so I anticipate about a week for an MVP and maybe another week to iron out major issues and refactoring before looking for help testing.

**Comment by EisenbergEffect** [comment]
This sounds pretty awesome if you can get it working @KingOfTac We can create any needed channels and do configuration on our end when the bot is ready. I'd love to see something like this put in place to help integrate the various places that the community is interacting.

Let me know if you need anything from us and please keep us posted on how the project progresses.

**Comment by KingOfTac** [comment]
Progress update on this.

I ran into a small roadblock on the Github side of things right before the holidays that required that I take step back and rethink a couple of items.

The discord bot part is moving right along and just about ready to plug into Github.
I am going to have to shift gears a bit over the next couple of weeks due to some personal stuff, but I'll work on this when I can get away for a minute.

The updated timeline is TBD until I can do a more in-depth analysis for the Github integration.

**Comment by EisenbergEffect** [comment]
Thanks for keeping us posted on this @KingOfTac 😄
