### ISSUE TITLE
docs: clarify the need for z-index on dialogs

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5461]
# 🙋 Documentation Request

Community members have repeatedly encountered issues using our dialog components where the component does not overlay their UI properly.

## 💁 Possible Solution

We should add content to our documentation on this component that indicates the typical requirement to set z-index.

**Comment by chrisdholt** [comment]
Is there any additional context here? I have a feeling that a big reason this is coming up is likely more due to _where_ in the DOM the dialog should be rendered and where it is being rendered. I'm happy to take a pass at this.

**Comment by EisenbergEffect** [comment]
There are several cases of people attempting to use the dialog and having other web components render over top. I don't have more details than that. Some sort of guidance in the docs would probably help. If it's not z-index than maybe point out where the dialog should be I suppose.

(Whenever I build apps I always built a dialog service that dynamically creates dialogs at the end of the body. My guess is that people are just putting them inline wherever and sometimes that isn't working out like they expect. We also used to have some z-index stuff set on some of our components, which could be causing issues too.)
