### ISSUE TITLE
feat: Ability to group properties for observation

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#5463]
# 🙋 Feature Request

Occasionally a component has multiple observable `Ref`s, or `Slotted`s that are needed for a single mechanism within the component. Coordinating when the observables are ready and when to run the dependent code can be a little tricky and produces a lot of redundant code.

I'm proposing a way for `@observable` to group properties together and execute a propertyChanged handler when all grouped properties become available.

## 🤔 Expected Behavior

Ability to tell `@observable` that it needs to execute a propertyChanged handler when all linked properties are available.

## 😯 Current Behavior

NA

## 💁 Possible Solution

A configuration object that can be passed to `@observable` calls, to tell it which properties to group, as well as a new handler `[propertyGroup]Available` that gets called when all properties are available.

Naming things is a slight issue, since I feel like grouping regular properties on the class and grouping `Ref` or `Slotted` directives pose two separate scenarios.

```ts
class MyElement extends FASTElement {

  @observable({ group: 'myGroup' })
  public someSlotted: HTMLElement[];

  @observable({ group: 'myGroup' })
  public otherSlotted: HTMLElement[];

  public myGroup: ObservableGroup;
  public myGroupAvailable() {
    // Both this.someSlotted and this.otherSlotted should be available
  }
}
```

**Comment by KingOfTac** [comment]
Not sure how typing on the grouped property will work, thus the ambiguous ObservableGroup type.

**Comment by EisenbergEffect** [comment]
Not sure if we can do this very easily and with good perf, but I'll try to spend some time looking into it while we're updating the internals of FASTElement for 2.0.

**Comment by KingOfTac** [comment]
Sounds good. In the meantime, I think I'll just make a utility function that can do this. If a built-in method is unfeasible then I can share any code in case others are looking for similar functionality.

**Comment by KingOfTac** [comment]
Closing this as something close to this can be accomplished with volatile properties.
