### ISSUE TITLE
fix: Non-modal FAST Dialog always consumes Escape key when visible

### ISSUE THREAD

**Issue by msmithNI** [microsoft/fast#5465]
# 🐛 Bug Report

When `fast-dialog` is used with `modal="false"`, it still consumes Escape keypresses on the page (expected for a modal dialog, but not for a non-modal one).

A non-modal dialog may want to stay open when Escape is pressed, and only close when a particular HTML button is clicked.
Not dismissing when Esc is pressed is straightforward (can just not handle the `dismiss` event), but there's not a good way to prevent the Esc keypress from being handled by the dialog (FAST Dialog `handleDocumentKeydown` will always do `event.preventDefault()` for an Esc press if the dialog is non-hidden).

## 💻 Repro or Code Sample

[Example StackBlitz using both a modal + a non-modal dialog](https://stackblitz.com/edit/typescript-lhumk2?file=index.ts)
In that example, Esc will only work to close the modal dialog if the non-modal dialog has already been closed.

## 🤔 Expected Behavior

A non-modal FAST Dialog shouldn't always consume the Escape key when pressed (even if visible).

## 😯 Current Behavior

A non-modal FAST Dialog always consumes the Escape key, if visible.

## 💁 Possible Solution

A few different options (all would work for my use case):
- If `modal=false`, always just skip handling the Escape key
- If `modal=false`, only dismiss on Esc if focus is within the dialog (`dialog.contains(document.activeElement)`)
- Add a `protected shouldDismiss(): boolean` method which a subclass can override. When Escape is pressed, if `shouldDismiss()` = false, `dismiss()` is not called and `event.preventDefault()` isn't called. (For my use case, I already have a class deriving from the fast-foundation Dialog)

## 🔦 Context

The StackBlitz shows one example of how this bug could be an issue (non-modal cookie disclosure dialog, and a modal dialog being used for something else).

In my application, I have some app navigation links within a modal FAST Dialog which is shown when a button is pressed on the page. The user can also dock/pin that navigation panel, in which case I set modal=false on that FAST dialog. In that configuration, I noticed that pressing the Escape key, even when other parts of the page were focused/active, were still dismissing my navigation panel.

## 🌍 Your Environment

* OS & Device: Windows PC
* Browser: Chrome
* Version 96

**Comment by EisenbergEffect** [comment]
Thanks for the detailed write up @msmithNI !
/cc @chrisdholt

**Comment by chrisdholt** [comment]
Not stale - we’ll handle in the next version of Foundation, coming with Fast element 2

**Comment by janechu** [comment]
Unfortunately as of #6955 we are deprecated the `@microsoft/fast-foundation` package. We will have more information on libraries that are picking up that work in our upcoming v2 release of `@microsoft/fast-element`.
