### ISSUE TITLE
feat: enable lightweight array change notification

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#5466]
# 🙋 Feature Request

Fast enables array observation that triggers a callback when the array is modified:
Observable.getNotifier(myArray)

The callback includes detailed information about the change to the array in the form of splices:
public handleChange(source: any, splices: Splice[]){...}

However not all listeners necessarily care about the splices and just want to be triggered when contents have changed, and calculating the splices can be expensive with large arrays.  The request is for a way to observe an array and get notified of changes without the overhead of calculating the splices.

**Comment by Pines408** [comment]
> # 🙋 Feature Request
> 
> Fast enables array observation that triggers a callback when the array is modified:
> Observable.getNotifier(myArray)
> 
> The callback includes detailed information about the change to the array in the form of splices:
> public handleChange(source: any, splices: Splice[]){...}
> 
> However not all listeners necessarily care about the splices and just want to be triggered when contents have changed, and calculating the splices can be expensive with large arrays.  The request is for a way to observe an array and get notified of changes without the overhead of calculating the splices.
> 
> 

 ("Lejonta Jones");
