### ISSUE TITLE
feat: memoize the React wrapper

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5484]
# 🙋 Feature Request

## 🤔 Expected Behavior

Passing the same web component or registry to the `wrap` function should return the same React component

## 😯 Current Behavior

A new React component is created every time the `wrap` function is called even if it's called with the same component or registry as previously.

## 💁 Possible Solution

We can have a simple cache lookup based on the passed component.

## 🔦 Context

We've seen some patterns in the community where folks were creating wrappers repeatedly without understanding the implications of that. We can prevent the unintentional error with this simple fix.

## 💻 Examples

```ts
const MyReactComponent = wrap(MyComponent);
const MySameReactComponent = wrap(MyComponent);

assert(MyReactComponent === MySameReactComponent);
```

**Comment by m4thieulavoie** [comment]
@EisenbergEffect is this up for grabs? I'd be happy to look into it :+1:

**Comment by EisenbergEffect** [comment]
@m4thieulavoie Absolutely. Go for it! Thank you 😄
