### ISSUE TITLE
fix: 'provideReactWrapper' function to render web component violates CSP in Edge Settings page in fast-react-wrapper

### ISSUE THREAD

**Issue by Ceveos** [microsoft/fast#5489]
# 🐛 Bug Report

When rendering a web component under a react framework, the guidance is to use the `provideReactWrapper` from `@microsoft/fast-react-wrapper`. When using this to render a web component in the Edge settings page, the whole page errors out as the CSP was violated.

It seems like the wrap function may be injecting HTML causing the CSP to not be happy.

## 💻 Repro or Code Sample

Simply import a web component, such as Fluent Menu, and try to wrap it.
When you render the component, you will have broken CSP.
```ts
import { provideReactWrapper } from "@microsoft/fast-react-wrapper";
import { fluentMenu } from "@fluentui/web-components";

const { wrap } = provideReactWrapper(React);

const FluentMenu = wrap(fluentMenu());

public render(): JSX.Element {
  return <FluentMenu/>
}
```

## 🤔 Expected Behavior

Web component would render on the settings page without issue

## 😯 Current Behavior

Edge Settings Page does not load at all. CSP has been violated.

Error log:
```
GET edge://resources/js/cr/ui/command.js net::ERR_FAILED
assert.js:85 
        
       crbug/1173575, non-JS module files deprecated.
(anonymous) @ assert.js:85
promise_resolver.js:84 
        
       crbug/1173575, non-JS module files deprecated.
(anonymous) @ promise_resolver.js:84
cr.js:615 
        
       crbug/1173575, non-JS module files deprecated.
(anonymous) @ cr.js:615
define @ cr.js:259
(anonymous) @ cr.js:463
ui.js:213 
        
       crbug/1173575, non-JS module files deprecated.
(anonymous) @ ui.js:213
define @ cr.js:259
(anonymous) @ ui.js:5
keyboard_shortcut_list.js:94 
        
       crbug/1173575, non-JS module files deprecated.
(anonymous) @ keyboard_shortcut_list.js:94
define @ cr.js:259
(anonymous) @ keyboard_shortcut_list.js:5
parse_html_subset.js:223 
        
       crbug/1173575, non-JS module files deprecated.
(anonymous) @ parse_html_subset.js:223
util.js:320 
        
       crbug/1173575, non-JS module files deprecated.
(anonymous) @ util.js:320
lib_common.chunk.js:4320 
        
       Refused to create a TrustedTypePolicy named 'fast-html' because it violates the following Content Security Policy directive: "trusted-types parse-html-subset".
45930 @ lib_common.chunk.js:4320
n @ settings.bundle.js:1
58520 @ lib_common.chunk.js:4320
n @ settings.bundle.js:1
32164 @ lib_common.chunk.js:4320
n @ settings.bundle.js:1
65336 @ lib_common.chunk.js:4391
n @ settings.bundle.js:1
74075 @ settings.bundle.js:1
n @ settings.bundle.js:1
(anonymous) @ settings.bundle.js:1
n.O @ settings.bundle.js:1
(anonymous) @ settings.bundle.js:1
(anonymous) @ settings.bundle.js:1
lib_common.chunk.js:4320 
        
      
        
        
      
      
       
        
       Uncaught TypeError: Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy "fast-html" disallowed.
    at Object.45930 (lib_common.chunk.js:4320:34417)
    at n (settings.bundle.js:1:3231884)
    at Object.58520 (lib_common.chunk.js:4320:42550)
    at n (settings.bundle.js:1:3231884)
    at Object.32164 (lib_common.chunk.js:4320:28524)
    at n (settings.bundle.js:1:3231884)
    at Object.65336 (lib_common.chunk.js:4391:4064)
    at n (settings.bundle.js:1:3231884)
    at Object.74075 (settings.bundle.js:1:625416)
    at n (settings.bundle.js:1:3231884)
```

## 💁 Possible Solution

Either we add an exception for this in the CSP or find a new method of injecting HTML in order to render a web component in a react page.

## 🔦 Context

We are unable to render a web component in the settings page that is needed to render a high impact feature. There is a react version which is deprecated and contains accessibility bugs that won't be addressed as we are migrating to the new web component version.

## 🌍 Your Environment

Edge Chromium codebase on Windows.

**Comment by EisenbergEffect** [comment]
Can you try to use a FAST web component directly without the wrapper? I suspect you will have the same issue. Let me know.

FAST uses Trusted Types to create HTML. The error above "Uncaught TypeError: Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy "fast-html" disallowed." seems to indicate that you haven't allowed the FAST policy. You can either allow that policy via CSP or create your own policy, and pass it to FAST via FAST's `DOM.setHTMLPolicy(yourPolicy);` API.

**Comment by EisenbergEffect** [comment]
Closing since it's been about a month without response and this seems to be a configuration issue rather than a bug.
