### ISSUE TITLE
fix: if fast-combobox is opened by clicking an associated <label>, it becomes very difficult to close

### ISSUE THREAD

**Issue by caseyfaber** [microsoft/fast#5491]
# 🐛 Bug Report

If you open a combobox by clicking a `<label>` that is connected to it with the `for` attribute, the only way to close it is to pick on of the options or click the combobox first (then it becomes closeable again). Pushing Escape won't work, clicking the down arrow doesn't close it, you can even open multiple up and they will all be stuck open.

## 💻 Repro or Code Sample

https://codesandbox.io/s/combobox-with-label-hym61?file=/index.html

1. Click the label. The combobox will open.
2. Try to close it by pressing Escape, or clicking outside the listbox, or clicking the dropdown caret.

## 🤔 Expected Behavior

The combobox should close by clicking outside the combobox or pressing Escape.

## 😯 Current Behavior

It stays open unless you pick an option or click the input box and then focus out.

## 💁 Possible Solution

I thought one option might be to add a label slot so the component has full control even if opened by clicking a label. I saw this feature request, which is something we would like as well just for consistency with FAST text fields: https://github.com/microsoft/fast/issues/4642

However, `<label>` is working with `<fast-select>`, so that shouldn't actually be required, perhaps there is some conflict with the combobox text field when focus is externally given to `<fast-combobox>`.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Chrome
* Version: fast-foundation 2.27.1

**Comment by claviska** [comment]
@caseyfaber This bug appears to be fixed, at least in the current version.

**Comment by chrisdholt** [comment]
Yes, I was able to repro this in Chrome (not Edge interestingly enough) with that version, but it does appear to be fixed in 2.28.0. @caseyfaber if this comes up again, please reopen and we'll be happy to dig in.

Thanks!
