### ISSUE TITLE
feat: Different default picker item list positioning

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#5493]
# 🐛 Bug Report

In the current implementation of `Picker`, "picked" tags appear to the left of the control shifting the input to the right with each selection. This can be a bit jarring for the end user when the input is moving around.

## 💻 Repro or Code Sample

Start storybook in fast-components and navigate to `Picker`

## 🤔 Expected Behavior

Looking around at other implementations, it appears the most common practice is to put the picked items either above or below the input. FluentUI - React puts the picked items inside the input, which doesn't shift the entire input, but it does shift the cursor, forcing the user to still alter how far they are moving the mouse with each selection.

I'm pretty sure changing the default positioning can be done entirely in css. I was able to accomplish this by changing some styles in the web console in storybook.

By changing the display of the internal `picker-list` from flex to grid and some other tweaks to the css, picked items can be moved into a "cloud" above the input.
![image](https://user-images.githubusercontent.com/32497422/147791226-46d6f267-260e-4dfd-9cb2-299a7eceda2f.png)

There may be some template changes needed as I had to apply some styling to the list items slot element, which may be undesirable.

## 😯 Current Behavior

When picking items, they appear to the side of the input, shifting it over and eventually wrapping it onto a new line.
![image](https://user-images.githubusercontent.com/32497422/147791421-674aa2d0-63f0-4e7b-bad4-d68dd66f70d9.png)

## 💁 Possible Solution

Quickest solution would be to adjust the styling of the internal list to css grid with the items located either above or below the input.

Another possible solution that would allow some more customization of the positioning for developers, would be to contain the `picker-list-items` in an `AnchoredRegion` with the input set as the anchor and reflecting some of the regions positioning properties through the picker component similar to how `Tooltip` is designed.

## 🔦 Context

This is just my two cents on the current implementation coming from my own experiences as a dev and user. If there is a specific reason behind the current behavior, I would love to learn more about it.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
