### ISSUE TITLE
fix: slotted horizontal-scroll component does not have a scroll next flipper

### ISSUE THREAD

**Issue by robarbms** [microsoft/fast#5503]
# 🐛 Bug Report

When the horizontal-scroll component is used in a slot of another component, it will not scroll. This looks like it is calling setStops() in scrollItemsChanged() when they are added to the horizontal-scroll component when slotting. This is happening before the component has rendered to the page. As a result, leftOffset and widthOffset for all items is returning 0. This is causing the component to think that all of the children fit within the viewport.

## 🤔 Expected Behavior

It should scroll.

## 💁 Possible Solution

1. Call setStops() in onConnectedCallback(). This should call once the component has rendered it's child nodes. There could be a check of this.scrollStops and only update if they all are equal to 0.
2. In scrollItemsChanged(), if the values for offsetLeft and offsetWidth are == 0, delay calling setStops().

## 🔦 Context

Edge home page are trying to use a msft-horizontal-scroll inside of a msft-card. The scroll next flipper is not rendering so they can not scroll to the next item.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by robarbms** [comment]
I created an example based on what the dev was doing in FAST internal. It appears it has something to do with msft-card and not specifically with it being slotted as I had initially suspected. I could not repro the problem when slotting fast-horizontal-scroll inside of fast-card. I'll work on recreating the problem in msft-card to isolate the problem.

**Comment by chrisdholt** [comment]
> I created an example based on what the dev was doing in FAST internal. It appears it has something to do with msft-card and not specifically with it being slotted as I had initially suspected. I could not repro the problem when slotting fast-horizontal-scroll inside of fast-card. I'll work on recreating the problem in msft-card to isolate the problem.

Is this still a pertinent issue @robarbms or can we close?

**Comment by robarbms** [comment]
This was due to the way content was being referenced in article card and not due to the horizontal scroll component.
