### ISSUE TITLE
feat: add valueAsNumber property to number field and slider

### ISSUE THREAD

**Issue by brianehenry** [microsoft/fast#5506]
# 🙋 Feature Request

FAST's number field and slider are numeric inputs with string `value` properties. I assume that these properties are strings to match the behavior of native `<input type="number">` and `<input type="range">` elements, which makes sense. But it would be nice if the FAST numeric inputs had a `valueAsNumber` property like the native inputs do. 

## 🤔 Expected Behavior

```js
const numberField = document.querySelector('fast-number-field');
numberField.value = '123';
console.log(numberField.value); // prints '123'
console.log(numberField.valueAsNumber); prints 123
numberField.valueAsNumber = 456;
console.log(numberField.value); // prints '456'
console.log(numberField.valueAsNumber); prints 456
```

## 😯 Current Behavior

`valueAsNumber` field is not implemented on the FAST numeric inputs. A number value can be set on a field like this: 

```js
numberField.value = 123
```

But in order to read the value as a number, you have to parse the value from its string representation:

```js
const value = parseFloat(numberField.value);
```

## 💁 Possible Solution

A `valueAsNumber` property that matches the behavior of the native input would be ideal. If necessary, this property could be read-only (since it is already possible to set the `value` property directly with a number value).

In addition, it would be nice if the `value` property of these fields always returned string values for consistency. As of now, the `value` property could return either a string or a number, depending on how the value is set. But since this could be considered a breaking change, I don't think it is super important. 

## 🔦 Context

It's a slight inconvenience to have to parse numeric values from these controls. It would be nice to provide the same API that the numeric inputs have.

**Comment by chrisdholt** [comment]
Thanks for this @brianehenry, if you have any interest we'd welcome a PR :).
