### ISSUE TITLE
feat: slider should have "input" event, and should emit "change" event only at the end of an interaction

### ISSUE THREAD

**Issue by brianehenry** [microsoft/fast#5508]
# 🙋 Feature Request

The FAST slider emits a `change` event every time the value of the slider is changed. The `change` event could be emitted many times in a single drag interaction. There is not currently a good way to be notified of the updated value of the slider at the end of an interaction.

Most other FAST input elements have both `change` and `input` events for this purpose. The FAST slider does not have an `input` event, and its `change` event acts like an `input` event. 

The native `<input type="range">` element has both `change` and `input` events. `input` is fired every time the thumb is moved to a new location along the track, and the `change` event only fires when the drag interaction ends. 

## 🤔 Expected Behavior

Match the event behavior of the `<input type="range">` element. Emit `input` every time the thumb is moved to a new value, and `change` on mouse up.

## 😯 Current Behavior

Slider only has a `change` event, and it is emitted every time the value is changed.

## 🔦 Context

A user may want to preview the effect of adjusting the slider, without actually committing the value.

**Comment by KingOfTac** [comment]
As another note on this. The current behavior does not work properly with angular form directives, but other FAST elements that are emitting change and input properly do work just fine.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
