### ISSUE TITLE
fix: flaky unit test in DateFormatter

### ISSUE THREAD

**Issue by m4thieulavoie** [microsoft/fast#5513]
# 🐛 Bug Report

On my personal computer, `fast-foundation` test suite fails on the `DateFormatter` test suite. It looks like my date format (?) is conflicting with what the suite expects. Happy to provide more details if needed

Here's a summary of the failing test

```
SUMMARY:
✔ 1212 tests completed
✖ 3 tests failed

FAILED TESTS:
  Calendar
    DateFormatter
      ✖ Should be able to get a date string for a specific date
        Chrome Headless 96.0.4664.110 (Linux x86_64)
      AssertionError: expected '02/01/2020' to equal '1/2/2020'
          at Context.<anonymous> (dist/esm/__test__/webpack:/dist/esm/calendar/calendar.spec.js:77:97)

      ✖ Should default formatting to [weekday='long'], [month='long'] [day='numeric'], [year='numeric'] string
        Chrome Headless 96.0.4664.110 (Linux x86_64)
      AssertionError: expected 'Wednesday, 1 January 2020' to equal 'Wednesday, January 1, 2020'
          at Context.<anonymous> (dist/esm/__test__/webpack:/dist/esm/calendar/calendar.spec.js:81:19)

      ✖ Should be able to change formats
        Chrome Headless 96.0.4664.110 (Linux x86_64)
      AssertionError: expected '1 Jan 2020' to equal 'Jan 1, 2020'
          at Context.<anonymous> (dist/esm/__test__/webpack:/dist/esm/calendar/calendar.spec.js:89:19)
```

## 💻 Repro or Code Sample

unsure

## 🤔 Expected Behavior

Tests should pass

## 💁 Possible Solution

unsure

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]: Ubuntu 20.04
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]: n/a
* Version [e.g. 1.8.0]: 20.04

**Comment by janechu** [comment]
With the deprecation of `@microsoft/fast-foundation` as of #6955, this issue is being closed.
