### ISSUE TITLE
feat: deprecate item slot in accordion

### ISSUE THREAD

**Issue by m4thieulavoie** [microsoft/fast#5515]
# 🙋 Feature Request

Follow-up of https://github.com/microsoft/fast/issues/5437 . This issue is for tracking the deprecation of the `item` slot name in the Accordion component. Once https://github.com/microsoft/fast/pull/5514 merges in, Accordion should support both a default slot and the `item` one, but in the next major version, we'll want to get rid of the latter to keep a lean API. Note that as soon as the above PR merges in, no mention of `item` will be present in the docs

**Comment by m4thieulavoie** [comment]
@chrisdholt feel free to fill in any missing piece of information!

**Comment by chrisdholt** [comment]
Closed w/ #5945
