### ISSUE TITLE
fix: `current-value` attribute being applied to top level button component when wrapped with `fast-react-wrapper`

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/fast#5524]
# 🐛 Bug Report

I'm still not completely sure if this is a bug or not, but we ([Webview UI Toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit)) have discovered that a component built with the fast foundation button (and also then wrapped with the `fast-react-wrapper`) will have the `current-value` attribute ([inherited from FormAssociated](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/form-associated/form-associated.ts#L678)) applied at the top level of the button component.

This ends up being fine when the wrapped React component is used in a web browser or VS Code webview environment but is causing issues in our Storybook instance because other component attributes (such as button `appearance`) are not being applied and only the `current-value` attribute is present.

This also strays from the web component version of the button where `current-value` is not present at the top level at all.

Any thoughts or insights into what might be going on would be appreciated! 🙂

## 💻 Repro or Code Sample

**Button wrapping code:**

```ts
import React from 'react';
import { provideReactWrapper } from '@microsoft/fast-react-wrapper';
import { provideVSCodeDesignSystem } from '../vscode-design-system';

import { vsCodeButton } from '../index.ts';

const { wrap } = provideReactWrapper(React, provideVSCodeDesignSystem());

/**
 * VS Code Button React component.
 *
 * @public
 */
export const VSCodeButton = wrap(vsCodeButton());
```

**React component in use:**

```jsx
// ... other code ...
<VSCodeButton appearance="secondary">Howdy!</VSCodeButton>
// ... other code ...
```

**Resulting build output when React component is used in a web server:**

```html
<vscode-button current-value="" appearance="secondary">Howdy!</vscode-button>
```

**Resulting build output when React component is used in Storybook:**

```html
<vscode-button current-value="">Howdy!</vscode-button> // Note the lack of appearance attribute
```

**VS Code button web component (no React) when used in Storybook/web server (as a comparison):**

```html
<vscode-button appearance="secondary">Howdy!</vscode-button> // Note the lack of current-value attribute
```

## 🤔 Expected Behavior

Based on the web component example, I would expect: 1) The `current-value` attribute should probably not be applied at the top-level component and 2) That the `appearance` attribute should be correctly applied when in Storybook.

## 😯 Current Behavior

The `current-value` attribute is being applied to all React wrapped button components and it seems to be affecting the ability of other button attributes to be applied/render in a Storybook context (maybe?).

## 💁 Possible Solution

I've done a deep dive through some of the FAST source code (particularly [`FormAssociatedButton`](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/button/button.form-associated.ts) and [`FormAssociated`](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/form-associated/form-associated.ts)) to discover that the `current-value` attribute stems from these locations but I'm still not sure why this attribute is getting applied to top-level components when the `fast-react-wrapper` is used.

## 🔦 Context

We're planning to ship a set of React components that are wrapped using the `fast-react-wrapper` and are currently in the phase of testing these components using Storybook.

## 🌍 Your Environment

* OS & Device: `MacOS` / `MacBook`
* Browser `Google Chrome`
* Version `v97`

**Comment by EisenbergEffect** [comment]
@chrisdholt Any ideas what might be going on here? Where would `current-value` be coming from?

**Comment by hawkticehurst** [comment]
Back with some updates!

## An almost working fix

We've continued to do some testing/exploration on our end and @mattrothenberg discovered that by adding the name property to the React wrapper config and also importing the wrapped React components (into Storybook) from our build file versus the wrapping declaration file this seems to fix the problems we've been seeing!

```ts
export const VSCodeButton = wrap(vsCodeButton(), {
  name: 'vscode-button', // <-- not included before
});
```

```jsx
// Button.stories.tsx
// Doesn't work!
import {VSCodeButton} from '../../src/react';

// Works!
import {VSCodeButton} from '../../dist/react';
```

However, with these changes, there is a new issue that shows up now where the `disabled` attribute is being applied across all our stories for some yet to be determined reason. 

This is potentially notable because, before this fix, the `disabled` attribute was actually the one attribute that worked in all our stories (while all the other attributes were broken).

(@mattrothenberg feel free to chime in with more details if I missed anything)

```jsx
// Button.stories.tsx
// Note: I've removed a lot of details from this code snippet to focus only on 
// the disabled attribute but if you want to see the full template let me know

... other config ...

const Template = args => {
  const { disabled, ... other args ... } = args;
  return (
    <VSCodeButton
      disabled={disabled} // <-- disabled truthiness seems to break (?) and is always applied across all stories
      ... other attributes ...
    >
      ... other template code ...
    </VSCodeButton>
  );
};

... other stories ...
```

## `current-value` not actually the problem?

I also noticed yesterday that while `current-value` is not applied to vanilla web components in our original Storybook, when used in a VS Code extension this attribute actually **_does_** appear and everything seems to work just fine. So perhaps the correlation between `current-value` and the issues we've been running into within Storybook is unfounded. 

There's definitely still something that is broken/weird going on but since this issue is all about `current-value` I'd be happy to close this issue and open a new one specifically focused on the fact that the `disabled` attribute is being inappropriately applied if that is preferred.

Let me know what you think!

**Comment by EisenbergEffect** [comment]
This is very, very strange. I'm inclined to believe that there's something odd coming from Storybook.
No need to close and open a new issue. If you want to rename this issue, that's fine.

**Comment by hawkticehurst** [comment]
We never ended up discovering what the problem was but decided to shift our efforts from using Storybook to creating a Node script that configures a test environment/sandbox directly inside VS Code instead.

Gonna go ahead and close this issue since we're no longer working on/tracking this.

**Comment by chrisdholt** [comment]
Thanks @hawkticehurst - I noticed this as well the other day in a sample react app. @EisenbergEffect, could this be related to the attribute reflecting? Not sure why it would, but it seems like it's reflecting without an actual value.

**Comment by EisenbergEffect** [comment]
That's a good theory. I'd need to dig into button specifically in the context of the wrapper and see what's going on. Maybe the wrapper is trying to set a value when there is none?

**Comment by chrisdholt** [comment]
> That's a good theory. I'd need to dig into button specifically in the context of the wrapper and see what's going on. Maybe the wrapper is trying to set a value when there is none?

This could be it; I may try and dig into this in my test app to see if I can find an oddity.

**Comment by chrisdholt** [comment]
Hey @hawkticehurst + all - I wanted to follow up after some investigation. 

After looking into my own use where this repros and digging into the implementation, I believe that this is currently _by design_. The initial value of these form associated components, including button, is an empty string - rather than null/undefined. This means that there *is* a value present, even though that value is "empty string". The default value is being reflected to the attribute, which ultimately is the feature here with `current-value`. After discussing this with @nicholasrice we believe that this is working as intended and expected. While we discussed the possibility of not reflecting the initial value, that would revert the goals of providing "current-value" in the first place. While that value _could_ be identified via the IDL attribute when not reflecting, implementations such as Blazor would not be able to access that value, which was a big reason for adding this attribute in the first place.

While the presence of the attribute _appears_ to be boolean, it's simply the result of how the platform treats attributes with an empty string value, which is technically how boolean attributes operate anyway. It seems that the confusion really results from this delta. I'm going to take a look at the code to see if a comment can help provide clarity here. Ultimately, we find that this behavior is not only by design but an accurate reflection of the elements "current-value".
