### ISSUE TITLE
fix: build failures in static site deploys & individual PRs

### ISSUE THREAD

**Issue by huynhicode** [microsoft/fast#5527]
# 🐛 Bug Report

Build errors in static site deploys and individual PRs.

## 😯 Current Behavior

Reason for build errors:

"This Static Web App already has the maximum number of staging environments (10). Please remove one and try again."

## 💁 Possible Solution

Proposed by @awentzel:

- Include paths in pipeline files to only build sites when site dependencies/requirements are changed.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by huynhicode** [comment]
Listing file paths that represent dependencies of the various site builds:

**fast-color-explorer**
none

**fast-component-explorer**
sites/fast-component-explorer/*
packages/web-components/fast-foundation/*
packages/web-components/fast-components/*

**fast-website**
sites/fast-website/*

**site-utilities**
sites/site-utilities/*

**website**
sites/website/*
sites/fast-website/*
sites/site-utilities/statics/assets/fast-inline-logo.svg
sites/site-utilities/statics/assets/fast-inline-logo-light.svg
sites/site-utilities/build/badges.js
packages/web-components/fast-components/dist/fast-components.iife.min.js
packages/web-components/fast-foundation/docs/integrations/*
packages/web-components/fast-foundation/docs/tools/*
packages/web-components/fast-element/docs/guide/*
packages/web-components/fast-components/docs/design/*
packages/web-components/fast-foundation/src/*
packages/utilities/fast-animation/dist/fast-animation.api.json
packages/utilities/fast-colors/dist/fast-colors.api.json
packages/web-components/fast-element/dist/fast-element.api.json
packages/web-components/fast-foundation/dist/fast-foundation.api.json
packages/web-components/fast-components/dist/fast-components.api.json

**Comment by awentzel** [comment]
no repo
