### ISSUE TITLE
streamline github actions for pure documentation changes

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#5540]
When changes that only modify certain parts of the documentation are merged, the full GH actions suite needs to be triggered for all open PRs when they're updated. This creates an exceedingly large backlog of builds, which in many cases can be skipped.

We could:
1. identify non-critical-path documents and files
2. analyze their respective build processes, if any, and determine the best workflow paths for different parts of the monorepo
3. allow downstream pull requests to skip rebuilding if the changes are non-critical or unrelated
4. ensure any changes to `master` always complete all workflows

**Comment by janechu** [comment]
This is being accounted for in the updates slotted for the v2 release of `@microsoft/fast-element`.
