### ISSUE TITLE
feat: add Rich Text Editor in web-components

### ISSUE THREAD

**Issue by sayers24** [microsoft/fast#5542]
# 🙋 Feature Request

Many teams are wanting a RTE control.

RoosterJS is a vanilla js component that has a lot of usage. It could be possible to build off of this but appears to be incompatible with the shadow DOM (see [an issue logged](https://github.com/microsoft/roosterjs/issues/706))

[A related feature request](https://github.com/microsoft/roosterjs/issues/722) could be a dependency if RoosterJS was to be pursued.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
