### ISSUE TITLE
fix: tree-item no longer emits the expanded-change event on right arrow key

### ISSUE THREAD

**Issue by aleun** [microsoft/fast#5548]
# 🐛 Bug Report

tree-item no longer emits the expanded-change event on right arrow key since PR https://github.com/microsoft/fast/pull/5194.
The spec states that the expanded-change event is part of the public API, which leads me to believe this was an unintended regression:
https://github.com/microsoft/fast/blob/eeb625e346a54da4c1f338eb90341a6e2d9ddb83/packages/web-components/fast-foundation/src/tree-view/tree-view.spec.md#L100-L101

## 💻 Repro or Code Sample

1. Instantiate a tree-view with nested tree-items and load in Edge.
2. Open DevTools and select the tree-item in Elements view.
3. Add an event listener to the tree-item in the Console: `$0.addEventListener("expanded-change", console.log)`
4. Expand the tree-item using the keyboard right arrow key.

## 🤔 Expected Behavior

Event listener should fire and output to Console:

```
CustomEvent {isTrusted: false, detail: fast-tree-item.nested, type: 'expanded-change', target: fast-tree-item.nested, currentTarget: fast-tree-item.nested, …}
```

## 😯 Current Behavior

Event does not fire.

## 💁 Possible Solution

PR https://github.com/microsoft/fast/pull/5194 moved keyboard handling logic into tree-view.ts, and in so doing modified item expansion on right arrow so that it directly assigns the `expanded` property: https://github.com/microsoft/fast/blob/7fd3f17ae4a54c44605b82915e355423833a8c1c/packages/web-components/fast-foundation/src/tree-view/tree-view.ts#L134-L141

Prior to this PR, the equivalent logic went through the `setExpanded` method, which  emits the `expanded-change` event.
https://github.com/microsoft/fast/blob/e8602a247065b0c916bdc8e55314f2d3e3403fd1/packages/web-components/fast-foundation/src/tree-item/tree-item.ts#L245-L257 
https://github.com/microsoft/fast/blob/e8602a247065b0c916bdc8e55314f2d3e3403fd1/packages/web-components/fast-foundation/src/tree-item/tree-item.ts#L304-L307

One proposed fix would change access level for `setExpanded` to public, then call it from the tree-view handler instead of directly assigning `expanded`.

## 🔦 Context

My component uses a tree-view with expanded-change handlers that trigger re-fetching dynamic data to be rendered by child tree-items. I'm unable to upgrade the FAST dependency without breaking this behavior for keyboard users.

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge
* Version 97.0.1072.69

**Comment by chrisdholt** [comment]
@scomea can you take a look and triage this to come up with the right fix/path forward?

**Comment by scomea** [comment]
> @scomea can you take a look and triage this to come up with the right fix/path forward?

I've had a PR out to address this for some time.  Needs reviews for forward motion.

**Comment by scomea** [comment]
Merged.  This issue should now be resolved.
