### ISSUE TITLE
fix: spellcheck attribute in fast-text-field does almost nothing

### ISSUE THREAD

**Issue by TravisSpomer** [microsoft/fast#5549]
# 🐛 Bug Report

The `spellcheck` attribute on `fast-text-field` doesn't seem to work properly in any case.

* If you just use `spellcheck` then the generated `input` element gets `spellcheck` which isn't valid.
* If you use `spellcheck="true"` then the generated `input` element gets `spellcheck` which isn't valid.
* If you use `spellcheck="false"` then the generated `input` element gets `spellcheck` which isn't valid **and** is the opposite of what you want.

## 💻 Repro or Code Sample

```html
<fast-text-field spellcheck="false">I should not be spellchecked</fast-text-field>
```

## 🤔 Expected Behavior

I would expect `spellcheck` or `spellcheck="true"` to produce an `input` element with `spellcheck="true"`, and `spellcheck="false"` to produce an `input` element with `spellcheck="false"`.

## 🔦 Context

This bug makes the `spellcheck` attribute effectively useless. Text fields in Edge already have spell check enabled by default, so no matter what value you use for `spellcheck` (including none at all), the end effect is exactly the same.

I think that part of the problem is that `spellcheck` is treated like a typical boolean attribute, but according to the docs it's actually *not* a boolean attribute. The only valid values are the strings `true` and `false` and it's not valid to use the shorthand that doesn't include a value. I haven't dived into why `spellcheck="false"` isn't working.

## 🌍 Your Environment

I'm testing in Edge 97 for Windows.

**Comment by chrisdholt** [comment]
This is a great catch @TravisSpomer - the attribute isn't boolean. We'll get this fixed up. Just as an FYI, we'll map directly to the attribute here for the element. Once fixed, whatever native behavior of this is on the input will be reflected on the control.

**Comment by chrisdholt** [comment]
> This is a great catch @TravisSpomer - the attribute isn't boolean. We'll get this fixed up. Just as an FYI, we'll map directly to the attribute here for the element. Once fixed, whatever native behavior of this is on the input will be reflected on the control.

Interestingly enough, I think we'll need to investigate more. When updating this, I get a type error as it relates to HTMLElement as the type for that is `boolean` (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement). Alternatively, on MDN when looking at an input with type text, the attribute is enumerated as noted above (https://developer.mozilla.org/en-US/docs/web/html/element/input/text).

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
