### ISSUE TITLE
fix: text field `onChange` event incorrectly firing when wrapped as React component

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/fast#5551]
# 🐛 Bug Report

Passing along a report from @mattrothenberg who is using the [VS Code toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit) React components in the GitHub Next [Flat Editor extension](https://github.com/githubocto/flat-editor/pull/18). (Matt if I miss anything in this bug report feel free to chime in and add details).

The short version is that he's run into an issue where the `onChange` event handler is firing at incorrect times based on React event standards (which, to be clear, stray from native `change` event standards).

In React land, [this event should fire for every keystroke in the text field](https://reactjs.org/docs/forms.html#:~:text=Since%20handleChange%20runs%20on%20every%20keystroke%20to%20update%20the%20React%20state%2C%20the%20displayed%20value%20will%20update%20as%20the%20user%20types.). However, this event is only firing when blurring away from the focused input (which, again, correctly follows the [native `change` event standard](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event#:~:text=When%20the%20element%20loses%20focus%20after%20its%20value%20was%20changed%2C%20but%20not%20committed%20(e.g.%2C%20after%20editing%20the%20value%20of%20%3Ctextarea%3E%20or%20%3Cinput%20type%3D%22text%22%3E).)).

The hope is that there might be some way to adjust the behavior of `onChange` when defining/using the React-based toolkit components while keeping the regular/default `change` event behavior in the toolkit web components?

## 💻 Repro or Code Sample

```jsx
// Change event follows native standards and only fires when component loses focus
// This strays from React conventions where onChange should fire on every keystroke
<VSCodeTextField onChange={handleChange}></VSCodeTextField>
```

## 🤔 Expected Behavior

When wrapped in the `fast-react-wrapper`, fast foundation components should adjust the behavior of the `onChange`/`change` event to follow the conventions of React.

## 😯 Current Behavior

When wrapped in the `fast-react-wrapper`, fast foundation components follow the behavior of the native `change` event.

## 💁 Possible Solution

Matt discovered there's a solution of using the `onInput` event to achieve the desired result of "fire event on every keystroke." If needed we're happy to just document this reality and tell people to use `onInput` instead of `onChange`.

```jsx
// This achieves the behavior expected of the onChange event
<VSCodeTextField onInput={handleChange}></VSCodeTextField>
```

## 🌍 Your Environment

_n/a (if needed Matt can provide info)_

**Comment by hawkticehurst** [comment]
Oh also for those not using Chromium-based browsers the links referencing the respective React and native change event standards were links to specific text highlights that included the following:

React reference:

> Since handleChange runs on every keystroke to update the React state, the displayed value will update as the user types.

Native reference:

> Depending on the kind of element being changed and the way the user interacts with the element, the change event fires at a different moment:
>
> - ... other text ...
> - When the element loses focus after its value was changed, but not committed (e.g., after editing the value of <textarea> or <input type="text">).

**Comment by EisenbergEffect** [comment]
Honestly, I'm not sure if we can change this or even if we'd want to. The web components inputs offer two events: `change` that happens on blur and `input` that happens on keystroke, per the HTML standard pattern. The trouble here is that React is fighting against the way that HTML is designed to work and is overriding the native behavior of change events. My recommendation would be to use the `input` event when you want updates on key press.

**Comment by mattrothenberg** [comment]
Thanks for your feedback @EisenbergEffect! Hooking into the input event is a perfect workaround for the React components. We will clarify the usage with good docs 👍

**Comment by hawkticehurst** [comment]
Exactly what @mattrothenberg said! 

Thanks for the input (no pun intended)--happy to just update the guidance in our docs on this matter.

Also going to go ahead and close this issue (unless you have a reason for keeping it open in which case I can reopen it).
