### ISSUE TITLE
feat: Allow tooltip to appear even when item is disabled

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/fast#5555]
# 🙋 Feature Request

The tooltip should be able to display regardless of whether the target element is disabled or not.

For instance, this works fine:

```xml
<FluentCheckbox id="anchor1">Stuff</FluentCheckbox>
<FluentTooltip Anchor="anchor1" Position=TooltipPosition.Bottom>I'm helping!</FluentTooltip>
```

But this does not:

```xml
<FluentCheckbox id="anchor1" Disabled="true">Stuff</FluentCheckbox>
<FluentTooltip Anchor="anchor1" Position=TooltipPosition.Bottom>Please log in to interact.</FluentTooltip>
```

## 🤔 Expected Behavior

If the checkbox is disabled, the tooltip can still appear.

## 😯 Current Behavior

If the checkbox is disabled, the tooltip cannot appear.

## 💁 Possible Solution

1) `Tooltip` ignores the `disabled` attribute.
2) Add a new property `OnActivating` on `Tooltip` to programatically control whether the tooltip should appear.

microsoft/fast-blazor#1 seems easiest, but is a breaking change
microsoft/fast-blazor#2 might be useful to a wider audience

## 🔦 Context

I'm making a todo list of sorts and wanted to tell the users that they can't interact with the checkboxes until they are logged in. I suppose I could just leave the checkboxes enabled and just let them know that their actions wouldn't be saved.

I started off with Blazorise, but I was having other UI issues so I decided to try this library.

**Comment by EisenbergEffect** [comment]
Moved this issue from `fast-blazor` to here as this is likely not Blazor-specific but a part of the underlying web component implementation.

**Comment by chrisdholt** [comment]
I wonder if the initial issue here relates to how we're suppressing events with CSS (pointer-events)? There's probably a much larger investigation here needed than just the surface level issue called out here. I can confirm that the behavior of native inputs still show the tooltip on hover - no action should be taken in this scenario though for disabled elements w/ keyboard though as the elements shouldn't be traversable the DOM in most cases.

**Comment by scomea** [comment]
Tooltip watches for mouse enter/leave events on the anchor. If disabled events suppress pointer events I don't expect those to be emitted.

**Comment by Pines408** [comment]
Well were are all my assets everyone forking my repository i built git hub
with bitcoin were is my money for all these projects people stole from me

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
