### ISSUE TITLE
select dropdown items are not accessible using the voice commands in mac.

### ISSUE THREAD

**Issue by saichiravuri** [microsoft/fast#5557]
# 🐛 Bug Report

 select are not accessible using the voice control commands.

## 💻 Repro or Code Sample
In any mac machine
- switch on voice control under accessibility
- try to navigate the list of items in the select dropdown

## 🤔 Expected Behavior

Items should be selcted via voice commands.

## 😯 Current Behavior

items are not accesible via voice commands

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by EisenbergEffect** [comment]
@saichiravuri Can you provide operating system and browser information please?

**Comment by chrisdholt** [comment]
> @saichiravuri Can you provide operating system and browser information please?

Additionally the name or details for how which assistive tech you are using and your repro steps.

**Comment by saichiravuri** [comment]
@EisenbergEffect @chrisdholt please find the details

Environment details:
Mac:
macOS: Big Sur  
mac Version: 11.6.2
Edge Canary version: 99.0.1111.0
AT: VoiceControl

Received an Accessibility bug with the below details::
Repro Steps (one of the edge browser features that uses fast select component):
Launch Edge Canary application and open any web page.
Navigate to 'Read aloud' button and select it
Navigate to 'Voice options' button and select it.
Navigate to 'Choose a voice' combo box and select it.
Use the voice control commands to access the 'Choose a voice' menu items and observe.

Actual Result:
'Choose a voice' menu items are not accessible using the voice control commands.

Expected Result:
'Choose a voice' menu items should be accessible using the voice control commands.
 
User Impact:
The user with motor impairment who rely on the voice control will face difficulties as they will not be able to access the elements.

Although above repro steps are feature specific behavior is same across all other items that uses the same component

**Comment by chrisdholt** [comment]
After investigation the referenced control does not seem to be a FAST Web Component. If you feel this was closed in error, please feel free to reopen and provide a min-repro with the FAST control itself.
