### ISSUE TITLE
feat: sidenav component along with mobile support

### ISSUE THREAD

**Issue by codef0rmerz** [microsoft/fast#5562]
# 🙋 Feature Request

For creating apps on top of FAST components, it's extremely important to have a sidenav component that let's you have collapsible sidebar navigation. But unfortunately, it's missing.

## 🤔 Expected Behavior

```
<fast-sidenav-container>
  <fast-sidenav mode="side" opened>Sidenav content</fast-sidenav>
  <fast-sidenav-content>Main content</fast-sidenav-content>
</fast-sidenav-container>
```

## 😯 Current Behavior

For now, one can create [a custom element](https://www.fast.design/docs/fast-element/defining-elements) manually.

## 💁 Possible Solution

https://material.angular.io/components/sidenav/overview

## 💻 Examples

https://material.angular.io/components/sidenav/examples

**Comment by arjendeblok** [comment]
If I want to switch from material design components to FAST then this is absolutely necessary.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
