### ISSUE TITLE
`focusStrokeWidth` not applied on text-field and number-field

### ISSUE THREAD

**Issue by fcollonval** [microsoft/fast#5565]
In text field and number field the box-shadow width is constant

https://github.com/microsoft/fast/blob/3337629dc557dba8b893038597ee3465f58f4dab/packages/web-components/fast-components/src/text-field/text-field.styles.ts#L130

But in select it is using the design token `focusStrokeWidth`

https://github.com/microsoft/fast/blob/3337629dc557dba8b893038597ee3465f58f4dab/packages/web-components/fast-components/src/select/select.styles.ts#L107

What is the reason behind that discrepancy?

**Comment by chrisdholt** [comment]
Looks like a bug, thanks for filing!
