### ISSUE TITLE
fix: The global title attribute is hijacked in <fast-disclosure>

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#5568]
# 🐛 Bug Report

The `<fast-disclosure>` element is using the [global `title` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) to populate its button text. This results in a system tooltip unexpectedly displaying redundant text on hover.

<img width="257" alt="CleanShot 2022-02-07 at 11 24 30@2x" src="https://user-images.githubusercontent.com/55639/152829041-4ba3f740-e403-4c98-8ccc-6cec0820cb03.png">

You can [replicate the problem in the demo](https://explore.fast.design/components/fast-disclosure) by hovering over the button.

This is true _unless_ the user provides a `title` slot, in which case the `title` attribute becomes optional.

```html
<fast-disclosure title="">
  <span slot="title">Open this thing</span>
</fast-disclosure>
```

Unfortunately, most users seem to prefer the attribute because button text seldom has HTML, and then they complain about the system tooltip because it's unexpected and doesn't match their other tooltips.

## 🤔 Expected Behavior

The component shouldn't hijack global attributes.

## 💁 Possible Solution

I suggest renaming the `title` attribute and slot (for consistency) to `summary`, which aligns more with the [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) API.

I'm happy to submit a PR for this, but it's a breaking change so I wanted to get some feedback first.

## 🔦 Context

This isn't blocking my team, as we're able to extend and change the template to `summary`.

**Comment by chrisdholt** [comment]
Yeah, this is an unfortunate oversight. Changing to summary would be welcome.

**Comment by chrisdholt** [comment]
Picking this up with Foundation vNext work.
