### ISSUE TITLE
fix: empty `option` value attribute does not follow native HTML behavior

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/fast#5569]
# 🐛 Bug Report

Bubbling a [bug report](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/327) we got on the toolkit upstream to FAST.

A toolkit dev discovered the following issue: "When having a dropdown with an option with the value set to an empty string, the empty value is not used, but the label of the option instead."

I created a reproduction of this issue (linked below) and was able to confirm that a native HTML `option` element with the attribute `value=""` will return an empty string when the `.value` property is accessed in JS, while on the other hand both the Webview UI Toolkit and FAST Components respective `option` components with the same attribute-value pair will instead return the option label when accessed via JS.

## 💻 Repro or Code Sample

Reproduction: [GitHub repo](https://github.com/hawkticehurst/fast-option-bug-reproduction) 

## 🤔 Expected Behavior

The FAST Foundation `option` element should follow native HTML behavior and return an empty string when its `value` attribute is set with an empty string.

## 😯 Current Behavior

The FAST Foundation `option` element currently returns the option label string when its `value` attribute is set with an empty string.

## 🌍 Your Environment

* OS & Device: macOS / MacBook Pro
* Browser: Microsoft Edge, Google Chrome, Apple Safari, and Mozilla Firefox
* Version: Latest versions of all above-mentioned browsers

**Comment by chrisdholt** [comment]
@radium-v can you investigate?

**Comment by hawkticehurst** [comment]
Thanks for the quick fix @radium-v!
