### ISSUE TITLE
feat: add support for W3C design token format to Adaptive UI

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5572]
# 🙋 Feature Request

Let's consider whether we can create an API that takes a w3C design token JSON file as input and uses that to set the tokens for Adaptive UI.

## 🤔 Expected Behavior

Some sort of API we can call that enables someone to set tokens based on a JSON doc that matches the specified format. Could it be as simple to use as this?

```ts
import designTokens from 'design-tokens.json';
import { provideFASTDesignSystem, tokensFromJSON } from '@microsoft/fast-components';

provideFASTDesignSystem()
  .register(
    tokensFromJSON(designTokens)
  );
```

## 😯 Current Behavior

No such API exists.

## 💁 Possible Solution

Details about the standard can be found here: https://github.com/design-tokens/community-group

It's a pretty straight forward JSON formatted document with token names, types, and values. I'd propose that the API be not put on the design system directly so that it can be tree-shaken for folks that don't need this feature. We can create base capabilities in `fast-foundation` that are then used to create the mapper function for each design system.

## 🔦 Context

We like web standards.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. Also Adaptive UI has been moved from FAST https://github.com/microsoft/fast/pull/6648
