### ISSUE TITLE
fix: setDefaultSelectedOption does not check selected property in listbox

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/fast#5583]
# 🐛 Bug Report

This is discovered in vscode-webview-ui-toolkit (in vscode-dropdown): https://github.com/microsoft/vscode-webview-ui-toolkit/issues/332

When generating vscode-option elements inside a vscode-dropdown and setting `.selected = true;` on one, it should be selected in the UI, but isn't (reset by an internal reset if no values are selected check)

## 💻 Repro or Code Sample

See linked issue above (vscode webview ui toolkit)

## 🤔 Expected Behavior

The option check should check for the selected property as well or the selected property should set the selected attribute.

## 😯 Current Behavior

FAST thinks no options are selected so it default selects the first option in the dropdown.

## 💁 Possible Solution

in

https://github.com/microsoft/fast/blob/eff36b2834b7709cc2281738007019fd264c3d31/packages/web-components/fast-foundation/src/listbox/listbox.ts#L537

we could also check for the .selected property like in combobox:

https://github.com/microsoft/fast/blob/256fe07122c2838e6bf0edd639a539b9ceeaa1bf/packages/web-components/fast-foundation/src/combobox/combobox.ts#L546

or the option selected property could modify the DOM attribute to make this extra check not needed altogether.

## 🌍 Your Environment

-  Browser / OS Version: VSCode 1.64.0 on Electron 13.6.8 on ArchLinux i3 (X11)
-  Version: vscode-webview-ui-toolkit `v0.9.0` (not sure which FAST version that is based on, I seem to have multiple different versions in my package-lock.json, so I don't know which one it's actually using)

**Comment by CharlieGreenman** [comment]
any work being done on this one?

**Comment by ranitg** [comment]
Is this issue going to be treated?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.

**Comment by soyrubio** [comment]
Just sharing my workaround. I write my webview in Svelte so this is very specific, but might help someone in the future. 

I store the dropdown result in a Svelte store (can also be a simple prop etc.) and modify it on input change. I then force display the correct selected value in the dropdown using the `slot="selected-value"`, which overrides the selected value visible in the dropdown. See below:

```html
<vscode-dropdown on:change={handleValueChange}>
    <!-- here go all the <vscode-option> -->
    <span slot="selected-value">Selected value</span>
</vscode-dropdown>
```
