### ISSUE TITLE
fix: Changing select `open` property errors

### ISSUE THREAD

**Issue by rajsite** [microsoft/fast#5586]
# 🐛 Bug Report

Changing the value of the open property results in an error in the select control.

When creating a control programmatically and setting the open property, the following codepath is triggered:
https://github.com/microsoft/fast/blob/b8e71f23c976545c16cd3ca05ee6dfc6dc47788f/packages/web-components/fast-foundation/src/select/select.ts#L39

Resulting in error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
```

## 💻 Repro or Code Sample

```js
const select = document.createElement('fast-select');
select.innerHTML = `
  <fast-option value="one">One</fast-option>
  <fast-option value="two">Two</fast-option>
  <fast-option value="three">Three</fast-option>
`;
select.open = true; // throw exception
```

Stackblitz: https://stackblitz.com/edit/typescript-q93mmy

## 🤔 Expected Behavior

Expect to be able to manipulate property values before an element has been connected to the DOM.

## 😯 Current Behavior

Manipulating the open property on Select results in an error.

## 💁 Possible Solution

Curious what approaches there are to protect this kind of situation. Seems like tests for setting properties programmatically may be useful.

## 🔦 Context

Tried to update to latest FAST. We have some tests where we copied the [fixture.ts](https://github.com/microsoft/fast/issues/4930) and the following fixture started to fail:

```ts
async function setup(
    position?: string,
    open?: boolean
): Promise<Fixture<Select>> {
    const viewTemplate = html`
        <nimble-select
            ${position !== undefined ? `position="${position}"` : ''}
            ${open ? 'open' : ''}
        >
            <nimble-listbox-option value="one">One</nimble-listbox-option>
            <nimble-listbox-option value="two">Two</nimble-listbox-option>
            <nimble-listbox-option value="three">Three</nimble-listbox-option>
        </nimble-select>
    `;
    return fixture<Select>(viewTemplate);
}
```

where setup is called as `setup('above', true);`

## 🌍 Your Environment

* OS & Device: Win10 PC
* Browser Chrome 98
* Version fast-components 2.21.2

**Comment by chrisdholt** [comment]
@radium-v can you investigate when able?
