### ISSUE TITLE
fix: Slider labels wrongly positioned when wrap for React js

### ISSUE THREAD

**Issue by fcollonval** [microsoft/fast#5599]
# 🐛 Bug Report

The slider labels are wrongly positioned when using the React wrapped components.

## 💻 Repro or Code Sample

Convert the following snippets

```ts
      <fast-slider min="0" max="100">
        <fast-slider-label position="0">0%</fast-slider-label>
        <fast-slider-label position="50">50%</fast-slider-label>
        <fast-slider-label position="100">100%</fast-slider-label>
      </fast-slider>
```

in

```tsx
        <Slider min="0" max="100" onChange={onChangeConsole}>
          <SliderLabel position="0">0%</SliderLabel>
          <SliderLabel position="50">50%</SliderLabel>
          <SliderLabel position="100">100%</SliderLabel>
        </Slider>
```

after wrapping the web component with the `provideReactWrapper` from `@microsoft/fast-react-wrapper`

## 🤔 Expected Behavior

Slider labels are position correctly with their position value

## 😯 Current Behavior

Web components | React wrapped components
![slider-react-labels](https://user-images.githubusercontent.com/8435071/153884810-36a05c95-9abd-41bd-9dcf-1253844c825f.png)

See [online](https://mybinder.org/v2/gh/jupyterlab-contrib/jupyter-ui-toolkit/main)

## 🌍 Your Environment

* OS & Device: Debian 11 PC
* Browser Mozilla FireFox
* Version 96.0.3

**Comment by EisenbergEffect** [comment]
Can you provide an output of the DOM structure from the browser's dev tools for both the correct and incorrect behavior?

**Comment by fcollonval** [comment]
For the web components:
```html
<jp-slider min="0" max="100" current-value="50" step="1" orientation="horizontal" mode="single-value" role="slider" class="horizontal" tabindex="0" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" aria-orientation="horizontal">
  <jp-slider-label position="0" class="horizontal" aria-disabled="false">0%</jp-slider-label>
  <jp-slider-label position="50" class="horizontal" aria-disabled="false">50%</jp-slider-label>
  <jp-slider-label position="100" class="horizontal" aria-disabled="false">100%</jp-slider-label>
  <input min="0" max="100" step="1" style="display: none;" slot="form-associated-proxy" type="range">
</jp-slider>
```
![slider-web-components](https://user-images.githubusercontent.com/8435071/154027416-5f26028a-9b13-49a5-9b48-55453fbfcdfa.png)


For the react components

```html
<jp-slider role="slider" class="horizontal" tabindex="0" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100" aria-orientation="horizontal" current-value="5" min="0" max="100" step="1" orientation="horizontal" mode="single-value">
  <jp-slider-label class="horizontal" aria-disabled="false" position="0">0%</jp-slider-label>
  <jp-slider-label class="horizontal" aria-disabled="false" position="50">50%</jp-slider-label>
  <jp-slider-label class="horizontal" aria-disabled="false" position="100">100%</jp-slider-label>
  <input min="0" max="100" step="1" style="display: none;" slot="form-associated-proxy" type="range">
</jp-slider>
```
![react_slider](https://user-images.githubusercontent.com/8435071/154027497-c89f61ea-e915-4bb1-809e-f19a34ca087a.png)

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
