### ISSUE TITLE
fix: incorrect indention in fast-menu

### ISSUE THREAD

**Issue by mollykreis** [microsoft/fast#5603]
# 🐛 Bug Report

When adding elements that are not `fast-menu-item` into a `fast-menu`, the indentation of the menu items is incorrectly adjusted when the additional elements have a role of `menuitem`.

## 💻 Repro or Code Sample

With the HTML shown below, setting `role="menuitem"` on the anchor element adjusts the indent of the `fast-menu-items` to 1. Without `role="menuitem"` on the anchor element, the indent of the `fast-menu-items` is 0.

```html
<fast-menu>
    <fast-menu-item>Menu item 1</fast-menu-item>
    <fast-menu-item>Menu item 2</fast-menu-item>
    <fast-menu-item>Menu item 3</fast-menu-item>
    <a href="https://www.fast.design/docs/components" role="menuitem">Menu item 4</a>
</fast-menu>
```

## 🤔 Expected Behavior

Adding elements with a role of 'menuitem' should not affect the indention of other items.

## 😯 Current Behavior
Correct indention without anchor element:
![image](https://user-images.githubusercontent.com/20542556/154116029-62df5002-a3ef-4ede-a2e2-b6a83b9b9263.png)

Incorrect indention with anchor element:
![image](https://user-images.githubusercontent.com/20542556/154115688-913d10f4-9643-45a8-8974-424a5c102643.png)

## 💁 Possible Solution
The logic to determine the indention should look only at the 'role' of the element, not its type. See [fast foundation menu](https://github.com/microsoft/fast/blob/af1f8736ae9ff54a7449324bad952865981d1ece/packages/web-components/fast-foundation/src/menu/menu.ts#L224).

## 🔦 Context

I need to create a menu that has hyperlink items and non-hyperlink items. All items should have an indention level of 0.

## 🌍 Your Environment

Windows 10, Chrome 98.0.4758.102

**Comment by rajsite** [comment]
Seems related to https://github.com/microsoft/fast/issues/5415 currently assigned to @chrisdholt
