### ISSUE TITLE
fix: selecting elements in select differs from native implementation

### ISSUE THREAD

**Issue by simonxabris** [microsoft/fast#5605]
# 🐛 Bug Report

`fast-select` works differently from the native select implementation in an edge-case scenario. 

With a `native` select, if you open the dropdown, hover over an element and *press space/enter*, the element that you hovered over will be selected.

In `fast-select`, this behaviour is not implemented and I imagine the reason is because it is also not implemented in the WAI-ARIA reference implementation.

My question is, does anybody know why is there a difference in this with the native implementation and the WAI-ARIA reference implementation and was implementing this behaviour ever considered?

I filed this as a bug, because this was the issue type that it fit the most IMO, but really it's more of a question, so sorry if it should've been filed as something else, feel free to convert it.

## 💻 Repro or Code Sample

- You can see the native behaviour here: https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox
- Fast here: https://explore.fast.design/components/fast-select
- WAI-ARIA reference here: https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox

## 💁 Possible Solution

I tried to investigate why is there this difference between native and WAI-ARIA reference, but wasn't able to find anything. Hoping that someone on the team might have some info about this (or able to conduct a better investigation than I was). Based on the results it might be a possibility that this behaviour is not needed, in that case feel free to close the issue!

## 🔦 Context

We implement our design system on top of FAST and one of our users filed a bug with us stating that they expected our select to work like the native one in this scenario. It kind of blows my mind that anyone would use a select like this, but as it turns out, they do.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
