### ISSUE TITLE
feat: allow custom menu-items to participate in menu indent mechanism

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#5608]
# 🙋 Feature Request

The method by which we apply indentation to menu items is very specific to fast menu items, we set a property on the instance based on the type:  `if (item instanceof MenuItem) {item.startColumnCount = indent;}`  .   

We support elements with a role of 'menuitem` that aren't a `fast-menu-item`, but they can't easily participate in the whole menu indent setting.  Should we revise this mechanism to enable that?

**Comment by chrisdholt** [comment]
I'll add a thought that I think this behavior should likely exist in implementation and not in *foundation*. I don't think this behavior is foundational to ALL menu item instances, in our code base it should probably move to live in `fast-components` rather than Foundation.

**Comment by chrisdholt** [comment]
Closing as this issue is obsolete in vNext Foundation since the behavior has been removed (it's too prescriptive for ALL menus and is directly related to visuals).
