### ISSUE TITLE
feat: API to support accessible color palette based on custom color input

### ISSUE THREAD

**Issue by rnive** [microsoft/fast#5625]
# 🙋 Feature Request
In order to support custom colors in Teams, we'll need to generate accessible color palettes based on hex code input. 

## 💁 Possible Solution

The ideal API for us would look like:

input: {

customerSelectedAccentColor,

customerSelectedNeutralColor,

other constants / variables computed from the existing teams theme - thinking about deltas or anything else required by FAST

}

output:

{

token1,

...

tokenN

} which we will map to the palette at [Fluent UI - Color schemes (windows.net)](https://fluentsite.z22.web.core.windows.net/0.60.1/color-schemes)

**Comment by EisenbergEffect** [comment]
@bheston Can you address this?

**Comment by bheston** [comment]
Chatting with this team directly. I've asked for it to be closed as I believe they have what they need now.
