### ISSUE TITLE
feat: add select method to text field

### ISSUE THREAD

**Issue by rajsite** [microsoft/fast#5626]
# 🙋 Feature Request

I'd like to use the equivalent of the `<input type="text">` [select method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select) on the text-field.

Would probably make sense on other controls that are input analogs like number field, etc.

## 🤔 Expected Behavior

Calling the select method selects the text in the text field following input's behavior.

More generally, I'd expect FAST text field to be mostly api compatible with `<input type="text">`.

## 😯 Current Behavior

An analogous method is not available.

## 💁 Possible Solution

Call select on the inner input control.

## 🔦 Context

Migrating an application from using a control with `<input type="text">` to a FAST Foundation text field-based control. I'd expect the API surface area to be compatible but select is missing.

## 💻 Examples

Workaround: Call `myTextField.control.select()`.

**Comment by rajsite** [comment]
@chrisdholt another client of ours landed on this and while the method now exists we were surprised that it was marked protected. The select method is part of the public api of the native `<input type="text">` which is the API surface that FAST Text Field would try to implement.

Is the intention that as a class extending Fast Foundation we would have to manually opt-in to exposing parts of the API or should the select method actually be exposed as public? My guess is the later, the Fast Text Field intends to expose an API compatible with `<input type="text">`.

**Comment by chrisdholt** [comment]
> @chrisdholt another client of ours landed on this and while the method now exists we were surprised that it was marked protected. The select method is part of the public api of the native `<input type="text">` which is the API surface that FAST Text Field would try to implement.
> 
> Is the intention that as a class extending Fast Foundation we would have to manually opt-in to exposing parts of the API or should the select method actually be exposed as public? My guess is the later, the Fast Text Field intends to expose an API compatible with `<input type="text">`.

Do you have an example of the implementation being utilized here so we can look across things accordingly?

**Comment by rajsite** [comment]
> Do you have an example of the implementation being utilized here so we can look across things accordingly?

For usage of the select() method an example that came up was a text field used for form entry. When the user attempted to submit the form and validation failed a script called select() on the text field to highlight the content of the text field that failed validation making it easier for the user to try and enter a new valid value.

In our design system we implemented a TextField that extends FoundationTextField and just adds styling for our design system. It's expected to be a drop-in replacement for `<input type="text">` but when a client tried to use it as a drop-in replacement it was mostly but not completely api compatible (in this case just missing select).

**Comment by chrisdholt** [comment]
Thanks @rajsite, I think if I can get a small repro illustrating this it will help. Just from a cursory test myself, I'm able to get a reference to the element (text field) and call `.select()` on it, which resulted in correctly selecting the text while testing the foundation component.

**Comment by chrisdholt** [comment]
> It's a development time typing issue not a runtime issue. Marking it `protected` tells TypeScript that it is not accessible on the public API. Notice the red squiggle for invoking the select method on the `fast-text-field`: https://stackblitz.com/edit/fast-protected-members?file=index.ts
> 
> ![image](https://user-images.githubusercontent.com/1588923/181610170-fa6bf9bb-9c48-4352-9fec-0353f759639d.png)

Thx for confirming, happy to take a PR to update.

**Comment by rajsite** [comment]
> Thx for confirming, happy to take a PR to update.

Will do!

**Comment by m-akinc** [comment]
I have created PR #6246 to make the select() functions public.
