### ISSUE TITLE
Consolidate the Row and Pane resize capabilities into a utility or set of utilities

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#564]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-layouts-react/src/row/row.tsx#issue_5b2abb343795e200010002a8

**Comment by janechu** [comment]
See also similar code in:
- (line 273) packages/fast-layouts-react/src/row/row.tsx
- (line 263) packages/fast-layouts-react/src/pane/pane.tsx

- (line 206) packages/fast-layouts-react/src/row/row.tsx
- (line 196) packages/fast-layouts-react/src/pane/pane.tsx

- (line 176) packages/fast-layouts-react/src/row/row.tsx
- (line 166) packages/fast-layouts-react/src/pane/pane.tsx

- (line 302) packages/fast-layouts-react/src/row/row.tsx
- (line 292) packages/fast-layouts-react/src/pane/pane.tsx

- (line 191) packages/fast-layouts-react/src/row/row.tsx
- (line 181) packages/fast-layouts-react/src/pane/pane.tsx

- (line 261) packages/fast-layouts-react/src/row/row.tsx
- (line 251) packages/fast-layouts-react/src/pane/pane.tsx

- (line 229) packages/fast-layouts-react/src/row/row.tsx
- (line 219) packages/fast-layouts-react/src/pane/pane.tsx

- (line 58) packages/fast-layouts-react/src/row/row.tsx
- (line 48) packages/fast-layouts-react/src/pane/pane.tsx

- (line 246) packages/fast-layouts-react/src/row/row.tsx
- (line 236) packages/fast-layouts-react/src/pane/pane.tsx
