### ISSUE TITLE
fix / question: programmatically determining `data-grid` column count (almost) always returns zero

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/fast#5659]
# 🐛 Bug Report

I've been working on this for the past 2-3 days and I'm still not sure if this is a bug or a misunderstanding/question on my end.

**Task / Goal**

I'm currently trying to set a new default for the `vscode-data-grid` component where columns will have an equal width of `1fr`. I'm trying to achieve this by programmatically acquiring the number of columns in the data grid and then setting the `grid-template-columns` attribute all in the `connectedCallback` life cycle method. 

With one expectation, the count returned is always zero despite being able to log the chosen data grid row in the Chrome inspector and see that all the children are defined.

**Exception** 

There's one case where this code does actually work and that's when `generate-header="none"` is set on the data grid.

## 💻 Repro or Code Sample

This is the data grid logic I currently have implemented:

```ts
export class DataGrid extends FoundationDataGrid {
    public connectedCallback() {
        super.connectedCallback();
        
        if (!this.hasAttribute('grid-template-columns')) {
            // Arbitrarily getting a reference to the first row
            // I've also tried using this.lastElementChild?.childElementCount but still run into the same issue
            const columnCount = this.firstElementChild?.childElementCount;
            this.setAttribute(
                'grid-template-columns',
                `repeat(${columnCount}, 1fr)`
            );
        }
    }
}
```

## 🤔 Expected Behavior

Since I proved that this code can work in some cases (i.e. when `generate-header="none"` is applied), I would expect this to work in all cases.

## 😯 Current Behavior

The code above usually returns a value of 0 for `columnCount`.

## 💁 Possible Solutions

**Q & A**
I'm thinking this might just be a misunderstanding on my part so any expertise or even just a second brain on this would be helpful/appreciated.

**`columnCount` property**
If the FAST team wants to take on a wider scope of work, exporting a `columnCount` property on the `data-grid` foundation component that can be read by component consumers (so we don't have to determine it ourselves) would be incredible.

**Set this default on the foundation `data-grid`**
Going even wider, if the FAST team wants to take on setting this default (evenly spaced columns) in the FAST Foundation `data-grid` that would be even better. 

We've received a number of toolkit issues since its release with people thinking that there are alignment issues in the data grid because they didn't manually set the data grid to have an attribute of `grid-template-columns: repeat({insert-column-count}, 1fr)`. After a few months of these issues, I think this is probably a common-sense default that should be added.

## 🌍 Your Environment

* OS & Device: MacOS on MacBook
* Browser: VS Code Webview (Chromium)
* Version: FAST Element `v1.6.2` | FAST Foundation `v2.33.1` | Toolkit `v0.9.1`

**Comment by chrisdholt** [comment]
@scomea would likely be the best to dig into this. He has been traveling a bit, but pinging here to see if he can hop on and help!

**Comment by hawkticehurst** [comment]
Awesome, thanks for tagging him in and giving the heads up on his travel!

**Comment by scomea** [comment]
Have you tried myGrid.columnDefinitions.length?

**Comment by scomea** [comment]
This may be a bug - 

"We've received a number of toolkit issues since its release with people thinking that there are alignment issues in the data grid because they didn't manually set the data grid to have an attribute of grid-template-columns: repeat({insert-column-count}, 1fr). After a few months of these issues, I think this is probably a common-sense default that should be added" 

The grid should correctly auto generate template columns when the author has not manually generated column definitions.  I'll take the bug and poke at it shortly.

**Comment by scomea** [comment]
Wait...this is for a "manual grid" where the author creates the grid with html markup rather than by passing in data?  Like so?

```
<fast-data-grid id="manualGrid" grid-template-columns="1fr 1fr" generate-header="none">
    <fast-data-grid-row>
        <fast-data-grid-cell grid-column="1">1.1</fast-data-grid-cell>
        <fast-data-grid-cell grid-column="2">1.2</fast-data-grid-cell>
    </fast-data-grid-row>
    <fast-data-grid-row>
        <fast-data-grid-cell grid-column="1">2.1</fast-data-grid-cell>
        <fast-data-grid-cell grid-column="2">2.2</fast-data-grid-cell>
    </fast-data-grid-row>
</fast-data-grid>
```

**Comment by hawkticehurst** [comment]
> Wait...this is for a "manual grid" where the author creates the grid with html markup rather than by passing in data?

Yes, although technically this is showing up in both cases where data grids are defined manually and via JS.

> What is happening with your code is that you are finding an empty header that the grid attempts to generate as it does by default, but because it has no data to base that on the header is likely empty. When you set 'generate-header' to "none" it doesn't do that.

Yep, I realized this was the case for the manual grid I was testing. However, the other grids that are populated with data via the `rowsData` property in JS are still returning zero despite the fact that they have a header row filled data.

> The expectation in this scenario is that the author knows the number of columns and sets that manually.

We actually do have this expectation documented in the toolkit docs but I've had so many people miss this detail or not read the docs that I'm starting to think equal width columns should be the default because everyone assumes there's an alignment bug when they first try the data grid.

> I think a reasonable change would be for the grid not to attempt to generate a header when their is no data regardless of the "generate-header" value.

Ooh I would certainly give a +1 to this change. We have a fair number of people defining manual data grids while using the React toolkit components and not having to define `generate-header="none"` on every grid would be a welcome improvement to the ergonomics.

> I'm thinking on whether adding a behavior like you suggest for scanning the first row of a manual grid to generate 'template-columns' could be added to the grid as well.

Yeah, again I'll point to what I said above about people not seeing the docs regarding equal width columns and assuming there's a bug. So this change would be really ideal in my opinion.

**Comment by hawkticehurst** [comment]
> Have you tried myGrid.columnDefinitions.length?

Tried this out with both manually defined and automatically generated data grids and the call to `this.columnDefinitins?.length` returned `undefined` in all instances (`this.columnDefinitions `retuned `null`).

**Comment by hawkticehurst** [comment]
Also I'd be happy to create and link to a reproduction of all of this on Monday if that would be helpful?

**Comment by scomea** [comment]
Please have a look at the PR that I just pushed up.
