### ISSUE TITLE
Warnings in FAST element 2.0 block the API extractor from completing without warnings

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#5664]
# Description

The script `test` in `@microsoft/fast-element` fails because of the warnings generated from `yarn doc:ci`.

## Requirements

- Add missing comments needed for the api-extractor to complete building without warnings

**Comment by EisenbergEffect** [comment]
Actually, I think I'll pick this up earlier because it is kind of annoying. Thanks Jane!
