### ISSUE TITLE
feat: add [Sticky Header and Sticky Column] to [FluentDataGrid]

### ISSUE THREAD

**Issue by josephkazarian** [microsoft/fast#5672]
# 🙋 Feature Request

Making the first header and the first column in the Grid Sticky.

## 🤔 Expected Behavior

When scrolling down or right, the first Row and the First column stick to the Top/Left side of the grid.

## 😯 Current Behavior

Not Available

## 🔦 Context

I have a data grid with a lot of columns and rows, I couldn't find a possible way to make the first row and the first column stick to the grid, and be shown on the screen when the user scrolls right and down.

**Comment by chrisdholt** [comment]
@EisenbergEffect the code for this is also in Fluent, should we move it there to track? If I recall, we had at least "sticky" header support at some point. My hope here would be that we could extrapolate this out beyond the generic ask above. While I agree that sticky-header support is fairly common, it seems like having the first row also sticky is a bit specific. Would a more broad ask potentially be enabling a method of setting the first (n) number of rows to sticky?

Sticky header would certainly be foundation work, but I can't help but feel like the other ask may fall beyond the bounds if we don't make it a more generic feature and would be better added in the Fluent implementation.

**Comment by EisenbergEffect** [comment]
@chrisdholt I'm fine with how/wherever you want to track.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
