### ISSUE TITLE
docs: add design systems and companies to the home page

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5674]
Let's update the FAST home page with two new sections:

* Show the companies/products that are using FAST
* Show design systems built on FAST

**Comment by chrisdholt** [comment]
@eisenbergeffect marking this as "needs design". We don't need redlines but we should understand the best way to illustrate this within the current confines while leaving room to scale as needed.

**Comment by EisenbergEffect** [comment]
@bheston Any chance you could spare a few minutes to sync with @huynhicode on this from a design perspective?

**Comment by chrisdholt** [comment]
> @bheston Any chance you could spare a few minutes to sync with @huynhicode on this from a design perspective?

Will likely want "sign-off" from @Falkicon as well.

**Comment by bheston** [comment]
> @bheston Any chance you could spare a few minutes to sync with @huynhicode on this from a design perspective?

We chatted about this last week. I was able to help track down some logos and provided some feedback on the layout and treatment.
