### ISSUE TITLE
perf: setup FluentUI WX with React Wrapper Krausest

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5693]
Use the Krausest infrastructure to test several versions of Web Component performance in React and non-React contexts.

**Comment by prudepixie** [comment]
tests can be referenced here : https://github.com/prudepixie/js-framework-benchmark/tree/master/frameworks/keyed

**Comment by prudepixie** [comment]
![Screen Shot 2022-03-04 at 3 27 33 PM](https://user-images.githubusercontent.com/6309989/156855624-c2a93596-53b8-419d-ba1d-c08ab851c62b.png)
![Screen Shot 2022-03-04 at 3 27 27 PM](https://user-images.githubusercontent.com/6309989/156855627-9ca7032c-437d-418c-bdcf-c9f2a544c6aa.png)
