### ISSUE TITLE
feat: add feature to disable template rendering during controller initialization

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5703]
SSR uses specialized template rendering for custom elements, so it is un-necessary for the controller to create and render a component's template. Further, template creation and rendering uses DOM apis that are unavailable in NodeJS, causing the process to throw.

Assign a `null` value to the `Controller.template` property does not circumvent the issue, because if `Controller.template` is `null` during initialization, the controller goes through the template resolution code-path and retrieves a template from the definition.

**Comment by EisenbergEffect** [comment]
@nicholasrice If you have code in place, can you point me to where you would want to grab the template, so I can see the context. I think that will help me figure out how to best enable this.

**Comment by nicholasrice** [comment]
Here in the [ElementRenderer](https://github.com/microsoft/fast/blob/3c1a0f0100d26d298cf4bec2ea30058c8687a354/packages/web-components/fast-ssr/src/element-renderer/element-renderer.ts#L58) we need to render a component's template. To do this, we'll get the template from the element and use the *TemplateRenderer* to render the element's template. That will look something like:
```ts
*renderShadow(renderInfo: RenderInfo) {
  yield* templateRenderer.render(this.element.template, renderInfo, this.element);
}
```

In the [TemplateRenderer](https://github.com/microsoft/fast/pull/5698/files#diff-50110aba3319e9be3a17529b661245db859c4be8c9d55e970918a5aaf9ad777aR111), we invoke a custom element's connectedCallback so that it can update any state and reflect up any attributes it needs to as a result of connection. This is where the error I refer to above gets thrown (connectedCallback invokes `ViewTemplate.create()` and `ViewTemplate.render()`)

**Comment by EisenbergEffect** [comment]
@nicholasrice When doe the `connectedCallback` run? If that can run before or during the `renderShadow` method of the renderer then I have an idea. We could just let the custom element render like normal, doing all its connected callback logic, including the template rendering. However, I would make the compiler pluggable so that you could plug in the SSR compiler and that could return its own version of the `View` interface. I'd remove all the code for template elements and put that into the client version of the compiler so the template would just run your compilation logic with the string and directives, store your result object, and your result object could then create views of a special type which you could use to yield results.

Some pseudo code:

**Your compiler**
```ts
const compileForSSR = (html: string | HTMLTemplateElement, directives: HTMLDirective[]) => {
    // TODO: do your stuff
    return SSRCompilationResult(...); // this will get cached by the template instance
  }
}
```

**Plug in your compiler**
```ts
ViewTemplate.setDefaultCompiler(compileForSSR); // following the same pattern we used for styles
```

**Modified ViewTemplate**
```ts
export class ViewTemplate {
    // elided...

    public create(hostBindingTarget?: Element): HTMLView<TSource, TParent, TGrandparent> {
        if (this.result === null) {
            // previous template vs. string logic moved to the client compile method
            this.result = compile(this.html, this.directives); // compile points to the configured compile function
        }

        // all previous construction logic moved to the createView method of the compilation result
        return this.result.createView(hostBindingTarget);
    }

    // called by the controller in connected callback
    public render(
        source: TSource,
        host: Node,
        hostBindingTarget?: Element
    ): HTMLView<TSource, TParent, TGrandparent> {
        const view = this.create(hostBindingTarget ?? (host as any));
        view.bind(source, defaultExecutionContext); // let the connected callback give you these params
        view.appendTo(host); // this could be a no op if you want
        return view;
    }
}
```

**Element renderer**
```ts
*renderShadow(renderInfo: RenderInfo): IterableIterator<string> {
    // TODO: get element from render info
    // assumes connectedCallback was previously run
    const view = element.$fastController.view as SSRView; // your ssr view implementation
    yield view.render();
}
```

**Comment by nicholasrice** [comment]
Yep, connectedCallback() gets invoked before renderShadow(). I think that approach will work.

**Comment by EisenbergEffect** [comment]
Great! I'll get on this then 😄
