### ISSUE TITLE
fix: fastAnchor in latest @microsoft/fast-component after v2.20.2

### ISSUE THREAD

**Issue by codef0rmerz** [microsoft/fast#5705]
# 🐛 Bug Report

The `@microsoft/fast-component` releases after v2.20.2 breaks fastAnchor with `Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes` in Angular/React apps.

## 💻 Repro or Code Sample

1. Create a sample Angular application using Angular CLI.
2. Install FAST npm dependencies and register `fastAnchor()`.
3. Use `<fast-anchor>Foobar</fast-anchor>` in the Angular template.
4. Check the devtools console for the aforementioned error.

## 🤔 Expected Behavior

It should work like v2.20.2 without any JS exception.

## 😯 Current Behavior

Currently the Anchor styles dot not apply and devtools console throws the aforementioned JS exception.

## 💁 Possible Solution

N/A

## 🔦 Context

Just trying to use fastAnchor in Angular/React apps.

## 🌍 Your Environment

* OS & Device: MacOS on PC
* Browser Google Chrome
* Version 98.0.4758.109

**Comment by radium-v** [comment]
Related PR: https://github.com/microsoft/fast/pull/5646
