### ISSUE TITLE
fix: keyboard navigation in toolbar with disabled buttons

### ISSUE THREAD

**Issue by mollykreis** [microsoft/fast#5723]
# 🐛 Bug Report

When using the keyboard to navigate through a toolbar, the focus gets "lost" when encountering a disabled button.

## 💻 Repro or Code Sample

1. Navigate to https://explore.fast.design/components/fast-toolbar and update the code to be
```
<fast-toolbar>
    <fast-button>button1</fast-button>
    <fast-button>button2</fast-button>
    <fast-button disabled>button3</fast-button>
    <fast-button>button4</fast-button>
</fast-toolbar>
```

2. Click on the toolbar (but not one of the buttons). 'button1' has focus (correct).
3. Press the right arrow on the keyboard. 'button2' has focus (correct).
4. Press the right arrow a second time on the keyboard. Nothing in the toolbar has focus (incorrect - focus should have moved to 'button4')
5. Click on the toolbar again (still not one of the buttons). 'button1' has focus again.
6. Press the right arrow on the keyboard. 'button4' has focus (incorrect - focus should have moved to 'button2' as in step 3 above).

## 🤔 Expected Behavior

With the toolbar in focus, pressing the right arrow key on the keyboard should move focus to the next element in the toolbar, skipping over any disabled buttons.

## 😯 Current Behavior

With the toolbar in focus, pressing the right arrow key on the keyboard moves focus to the next element in the toolbar until the next element is a disabled button. The toolbar attempts to focus the disabled button, which does not work. After this, pressing the arrow keys in the toolbar does nothing.

## 💁 Possible Solution

I'm willing to contribute a fix, but I don't have a specific fix in mind yet. I believe the fix should go in `reduceFocusableItems` of [toolbar.ts](https://github.com/microsoft/fast/blob/9542f92e85384aa39e8b9ab71b3972fb6dfc5bcd/packages/web-components/fast-foundation/src/toolbar/toolbar.ts#L243). That function incorrectly identifies the disabled button as a focusable element because `isFocusableFastElement` is true since `delegatesFocus` is set to `true` on the button.

## 🔦 Context

This keeps toolbars in my application from being fully keyboard accessible.

## 🌍 Your Environment

* OS & Device: Windows 10 PC
* Browser: Chrome
* Version 99.0.4844.51

**Comment by chrisdholt** [comment]
@radium-v can correct me here, but I think what should be expected here is that the disabled element _is_ focused. My recollection is that we keep disabled elements focusable when they are within the toolbar: https://www.w3.org/TR/wai-aria-practices-1.2/#toolbar

It sounds like focus is being lost, which is unexpected, but the focusable element here should be the disabled element.

**Comment by radium-v** [comment]
There's a chance this may be a problem with `Button` rather than `Toolbar`. I'm investigating now.

**Comment by radium-v** [comment]
@mollykreis you're right on all accounts. It's a conflict between Tabbable's `isFocusable` returning `false` if the element is disabled, and then the `isFocusableFastElement` being true regardless of the `disabled` state of the element.

The fix would require changing the first check in `reduceFocusableItems`:

```ts
if (
    !element.hasAttribute("disabled") &&
    (isFocusable(element) ||
        isRoleRadio ||
        isFocusableFastElement ||
        hasFocusableShadow)
) {
```

**Comment by mollykreis** [comment]
@radium-v, your suggested change works when the item becomes disabled before the toolbar is connected. However, if an item becomes disabled afterwards (and nothing else with the slots changes), then `reduceFocusableItems` is not called again. Do you have any suggestions of the best place to call `reduceFocusableItems` to handle this scenario?

**Comment by radium-v** [comment]
I think a standard `MutationObserver` would probably work to track child attribute changes. The `DataGrid` class does a similar thing with its `onChildListChange` property: https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid.ts#L612
