### ISSUE TITLE
fix: setting an option's selected property has no affect on the selection

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#5734]
# 🐛 Bug Report

Setting the `selected` property on any `<fast-option>` should update the selection in the parent element (e.g. select, combobox, etc.). It works when setting an attribute, but not when setting the corresponding property. See the fiddle below for details.

Because of the way React wrappers set properties instead of attributes, this means none of our React users can set a default option for these controls without using a ref.

## 💻 Repro or Code Sample

https://jsfiddle.net/a4or6zL0/

## 🤔 Expected Behavior

Setting the `selected` property of an option should update the select/combobox/etc. selection.

## 😯 Current Behavior

Nothing happens and the UI remains unchanged.

## 💁 Possible Solution

It seems like the parent element (select, combobox, etc.) will need to use a Mutation Observer to listen for attribute changes on child options and respond accordingly.

Alternatively, options could emit an event when their `selected` attribute changes that bubbles up to the parent element so it can respond to the change.

Not sure how you'd like to handle this one.

Note: I looked through the issues and found a few that might be related or affected by this, but none seemed to cover this exact issue. Apologies if it turns out to be a dupe.

**Comment by rajsite** [comment]
Related https://github.com/microsoft/fast/issues/5219

**Comment by chrisdholt** [comment]
@claviska we're working on how to best approach/solve this. I'm going to pull the `fast-components: final` label off this as it's explicitly tied to code in `fast-foundation` which is a dependency so I don't think we need to block or component changes. Thanks for hanging with us, we'll work on coming up with a way to solve this.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
