### ISSUE TITLE
Implement Directive handling in SSR

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5743]
SSR infrastructure needs custom handling of Directives. Implement custom handling for

* [x] `RepeatDirective`
* [x] `ChildrenDirective`
* [x] `RefDirective`
* [x] `SlottedDirective`

**Comment by nicholasrice** [comment]
I think we're going to need to no-op `ChildrenDirective`, `RefDirective`, and `SlottedDirective` for a couple reasons.
1. All of those provide references *after the shadow DOM has rendered*. In the SSR environment, this means that some or all of the DOM will already be emitted.
2. The TemplateRenderer doesn't create element instances for native elements, so there are no nodes for the directive to operate on.

**Comment by EisenbergEffect** [comment]
As I was reading your code, I thought of this same thing just before I saw your implementations. Makes sense to me.
