### ISSUE TITLE
fix: aria-current applied twice in breadcrumb

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#5747]
# 🐛 Bug Report

When adding breadcrumb items to a breadcrumb component dynamically, there is an edge case in which two aria-current are being added.

## 💻 Repro or Code Sample

Here's a repro:
https://codesandbox.io/s/lingering-pine-wb2lfn?file=/src/index.js

This emulates a SPA in which the breadcrumbs is constant in the header and the view changes.  On every view change, the breadcrumbs is updated.

In this use case, we dynamically add a breadcrumb item (e.g. like angular's forEach) when I move to a sub view.

See that the old view also keeps `aria-current`.

## 🤔 Expected Behavior

Remove `aria-current` from obsolete anchor on slot change.

## 😯 Current Behavior

`aria-current` appears twice.

## 💁 Possible Solution

Remove `aria-current` on slot change.

## 🔦 Context

Does not affect me but it's an edge case.

**Comment by chrisdholt** [comment]
Thanks @yonatkra - would you like to submit a PR for this?
