### ISSUE TITLE
[foundation] semantic meaning for 'control' referenced elements in templates

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#5757]
looking up the repo for all `control` members and their paired refs in templates shows incoherent pattern.

where in most cases `control` refs are "_[A reference to the internal input element](https://github.com/yinonov/fast/blob/853355c7bd25aa2a6ab12ecba8d2b3fd7f6eb43c/packages/web-components/fast-foundation/src/text-field/text-field.ts#L171)_", in one case (anchor) it "_[References the root element](https://github.com/yinonov/fast/blob/8a264ec2a22d4f02e901a260b85f77c381a52231/packages/web-components/fast-foundation/src/anchor/anchor.ts#L94)_".

is there a convention to setting an element as control?

if it generally follows that pattern when a native form control is used, perhaps it is an anomaly in anchor? anti-pattern?

**Comment by yinonov** [comment]
I believe openui/open-ui#81 addresses this issue exactly

**Comment by chrisdholt** [comment]
> I believe [openui/open-ui#81](https://github.com/openui/open-ui/issues/81) addresses this issue exactly

I think the intent here is slightly different, so I don’t see an exact application given the context, but I do agree it’s beneficial and can help lead any discussion here. From what I recall, that issue is around semantics of what constitutes what we would refer to as a “component”. We can also lean on the parts enumerated in Open UI though as we look to update those. Control in our case here is typically what we are referencing as a specific part.

**Comment by yinonov** [comment]
> > I believe [openui/open-ui#81](https://github.com/openui/open-ui/issues/81) addresses this issue exactly
> 
> I think the intent here is slightly different, so I don’t see an exact application given the context, but I do agree it’s beneficial and can help lead any discussion here. From what I recall, that issue is around semantics of what constitutes what we would refer to as a “component”. We can also lean on the parts enumerated in Open UI though as we look to update those. Control in our case here is typically what we are referencing as a specific part.

if it has any resemblance, it at least excludes _[References the root element](https://github.com/yinonov/fast/blob/8a264ec2a22d4f02e901a260b85f77c381a52231/packages/web-components/fast-foundation/src/anchor/anchor.ts#L94)_ from meeting _control_ criterions, right?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time and we are deprecating `@microsoft/fast-foundation`, so this issue is obsolete.
