### ISSUE TITLE
feat: add esm module for individual components

### ISSUE THREAD

**Issue by aszenz** [microsoft/fast#5760]
Add an esm module for each component

Right now i can only import the whole web components library from the esm cdn, I would like to import only the specific component i need in that page to save some bandwidth

This would make using fast components easier in legacy projects where there are no build setups / webpack

**Comment by chrisdholt** [comment]
Thanks for this issue @aszenz - we're experimenting with this type of approach in a separate project and seeing positive results. I'm going to leave the label for investigation on and we'll look to potentially put together a spec or discussion around this larger architectural change.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
