### ISSUE TITLE
rfc: Deprecate Custom Element Attribute Enums?

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5765]
https://github.com/microsoft/fast/pull/5745 introduces string literal type unions for custom element HTML attributes where they exist in the FAST component packages. 

This issue tracks an open question from that PR is if the enum exports that exist for these attributes should be deprecated.

**Comment by chrisdholt** [comment]
Would be a welcome change IMO. In most cases I would prefer an alternative to enums, personally. One thing I was considering was if a const could avoid the removal of the enums without a break and pave the way for this change over time…even that may not be necessary though…

**Comment by radium-v** [comment]
Enums can be replaced with objects: https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums

**Comment by radium-v** [comment]
It can be super useful to have explicit types available as values, especially in tests and Storybook fixtures. You can't use `Object.values(SomeList)` with union types.

**Comment by rajsite** [comment]
I think switching [enums to objects](https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums) would work well together with [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) to create enumerable objects and create a union type that is easy to maintain:

```ts
const PositionOptions = {
  Up: 'up',
  Down:'down',
  Left: 'left',
  Right:'right',
} as const;

type Position = `${typeof PositionOptions[keyof typeof PositionOptions]}`;

```
[playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBACiCBLKTwHkAOrwRgXhgG8BYAKBhgFVMAuGAcgFdMGAacygERAHcxaDACZ8w7TjAAyAUwBmUegwA2cqOIowASkgDmACwUMATroPqAvjACGeUJCgBucuSgBPTNPiIUaMARgABgAkRG4eILJeyDhgWDEQANoA1tKuETBh0ukI0b5xvhAAuuYBTmRAA)

**Comment by chrisdholt** [comment]
I have a PR for this and as illustrated by @rajsite I think this is going to be essentially transparent. The types will exist so types shouldn't break and importing the const should be able to be used like the enum was.
