### ISSUE TITLE
fix: inconsistent word delimitation in fast-web-utilities

### ISSUE THREAD

**Issue by rajsite** [microsoft/fast#5766]
# 🐛 Bug Report

The [`pascalCase`](https://github.com/microsoft/fast/blob/082acb9ad25e3f27580f4f948b3446b276da65fc/packages/utilities/fast-web-utilities/src/strings.ts#L77) and [`spinalCase`](https://github.com/microsoft/fast/blob/082acb9ad25e3f27580f4f948b3446b276da65fc/packages/utilities/fast-web-utilities/src/strings.ts#L92) functions in `@microsoft/fast-web-utilities` delineate words at different spots.

## 💻 Repro or Code Sample

https://stackblitz.com/edit/fast-string-helpers-split?file=index.ts

## 🤔 Expected Behavior

See below.

## 😯 Current Behavior

 For spinalCase("thinkIAm") expect "think-i-am" actual "think-i-am" ✔

 For pascalCase("thinkIAm") expect "ThinkIAm" actual "ThinkIam" ❌

 For spinalCase("typeRampMinus1FontSize") expect "type-ramp-minus-1-font-size" actual "type-ramp-minus1-font-size" ❌

 For pascalCase("typeRampMinus1FontSize") expect "TypeRampMinus1FontSize" actual "TypeRampMinus1FontSize" ✔

## 💁 Possible Solution

Quick and dirty workaround for ❌ pascalCase behavior above: `pascalCase(spinalCase(someVal))`
Workaround for ❌ spinalCase behavior above: n/a

## 🔦 Context

Trying to standardize on the fast string helpers over some we had.

## 🌍 Your Environment

`@microsoft/fast-web-utilities@5.1.0`

**Comment by wannieman98** [comment]
Hi, I am new to open source but I wish to contribute. Can I give this issue a try? Thanks!

**Comment by chrisdholt** [comment]
I believe this was closed with #5802 :)
