### ISSUE TITLE
feat: add Name of Library to license header to have it included in the license generated file by webpack 5

### ISSUE THREAD

**Issue by Holyphoenix** [microsoft/fast#5768]
We recently upgraded to Webpack 5 and we are working on automating the generating of a license attribution file along with our build (we noticed this file generated by default for us when we switched to Webpack 5 but are still working to make sure it includes all licenses). I believe Webpack grabs the license from the various projects, and places them into the license.txt file it generates, and it seems to work pretty well. The problem with FAST is that the license doesn't include the Project Name or the project components, and just displays the license, so when looking at the license attribution file it generates we just see the Microsoft license without knowing what components or modules it belongs to. Would you be willing to update your license text to include the project components that are covered by the license?

I have included a screenshot of the generated file we are receiving within our project.  

![image](https://user-images.githubusercontent.com/3467817/159722511-4aa6403d-7026-41a1-8b6e-4070bfddef67.png)

**Comment by EisenbergEffect** [comment]
Ok, I've got approval from legal to change the header from this:

```
MIT License
 
Copyright (c) Microsoft Corporation. All right reserved.
```

To this:
 
```
FAST - https://www.fast.design/
MIT License
Copyright (c) Microsoft Corporation. All right reserved.
```

@huynhicode Can you add this to the top of your todo list so we can get this customer going with their new build system? Thanks!

**Comment by huynhicode** [comment]
@EisenbergEffect Thank you - PR submitted: https://github.com/microsoft/fast/pull/5771

**Comment by EisenbergEffect** [comment]
Thanks everyone!
