### ISSUE TITLE
fix: changing slotted options does not maintain the selected value in fast-select

### ISSUE THREAD

**Issue by mollykreis** [microsoft/fast#5773]
# 🐛 Bug Report

If you change the set of slotted options within a fast-select, the selected value does not stay selected. Instead, the selected index remains selected.

## 💻 Repro or Code Sample

Create a fast-select with the value set to 'my-selected-value' and the following options:
```
<fast-option value="option1">Option 1</fast-option>
<fast-option value="option2">Option 2</fast-option>
<fast-option value="option3">Option 3</fast-option>
<fast-option value="my-selected-value">Selected value</fast-option>
```

Then, update the slotted options to be:
```
<fast-option value="option1">Option 1</fast-option>
<fast-option value="option2">Option 2</fast-option>
<fast-option value="option3">Option 3</fast-option>
<fast-option value="option4">Option 4</fast-option>
<fast-option value="my-selected-value">Selected value</fast-option>
```
Notice that the selected index remains as 3 and 'option4' ends up selected rather than 'my-selected-value'.
## 🤔 Expected Behavior

When the slotted options change within a fast-select, the selected value should remain the same as long as it is still value.

## 😯 Current Behavior

When the slotted options change within a fast-select, the selected value does not remain the same. Instead, the selected index is kept.

## 💁 Possible Solution

Reset the value of the select after the slotted options change.

## 🔦 Context

In an Angular app, the set of possible options for a select is configured using an `ngFor`. When the set of options changes (specifically if the index of the currently selected option changes within the array being iterated over by the `ngFor`), then the user's selection is modified.

## 🌍 Your Environment
* OS & Device: Windows 10 PC
* Browser: Microsoft Edge
* Version: 99.0.1150.46

**Comment by chrisdholt** [comment]
@radium-v can you investigate when you have a moment?

**Comment by fredvisser** [comment]
I assume this is resolved in https://github.com/microsoft/fast/pull/5878?

**Comment by chrisdholt** [comment]
> I assume this is resolved in #5878?

I have a repro of this still I believe - https://stackblitz.com/edit/typescript-qjvxhe?file=index.ts

@radium-v can you investigate and see if this can be addressed prior to the removal of fast-component?

**Comment by chrisdholt** [comment]
Dropping the `fast-components:fiinal` label from this. We're investigating and working on this, but we'll need more time. The work here is in `fast-foundation` so I don't think we need to block to get the fix in for the `fast-components`.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
