### ISSUE TITLE
Neutral appearance for button doesn't render as expected in Angular app

### ISSUE THREAD

**Issue by random-creator** [microsoft/fast#5777]
I have an app in Angular 13 and I am trying to integrate Fast components following the tutorial here https://www.fast.design/docs/integrations/angular. 

I want to render the button with default or neutral appearance. This is how it gets rendered: 
![image](https://user-images.githubusercontent.com/25162104/160500650-17e5897f-ee50-47ad-afbe-8c131772d775.png)

I am expecting it to be rendered like so:
![image](https://user-images.githubusercontent.com/25162104/160500739-eeda6bb4-c13e-4432-96fa-661850f2bf4b.png)

Could you please help me understand what is missing? Thanks

**Comment by chrisdholt** [comment]
Without any details here it may be hard to track down the exact issue. Can you help us get started by putting together a small scoped repro illustrating the problem? Feel free to use stackblitz or similar.

**Comment by random-creator** [comment]
Here is a quick stackblitz similar to my app https://stackblitz.com/edit/angular-ivy-crynuk?file=src/app/app.component.html

**Comment by random-creator** [comment]
hey @chrisdholt Let me know if you need further details or the above stackblitz link is not working.

**Comment by chrisdholt** [comment]
Good news @random-creator, thanks to your repro I was able to figure this out after taking a quick look about 60 seconds ago :).

The components default to having a dark luminance value, which means that they are in "dark" mode out of the box. A quick way to address the dark mode controls appearing would be to set the css of the body element to the `fill-color` variable. However, given your expectation (the controls appear with light mode luminance) take a look at line 28 here and you can see how we can quickly accomplish what's expected for your app: https://stackblitz.com/edit/angular-ivy-kjyhiu?file=src%2Fmain.ts

If you want to condition the mode based on the browser mode you can also wire the setting of the luminance value to the result of the browsers state via media query.

**Comment by chrisdholt** [comment]
Closing this as resolved :)

**Comment by random-creator** [comment]
@chrisdholt that worked! thanks a lot
