### ISSUE TITLE
feat: add tabbing support for slot element inside dialog when it has first or last focusable element

### ISSUE THREAD

**Issue by abbasc52** [microsoft/fast#5781]
# 🙋 Feature Request
When using fast-dialog in a web component, if the dialog content has a `<slot>` element. It should allow tabbing into slotted content even if it first or last element in the dialog

## 🤔 Expected Behavior

When your focus is in dialog and the next focusable item is inside a slot, on pressing of tab, it should focus on the focusable element inside the slot.

## 😯 Current Behavior

When your focus is in dialog and the next focusable item is inside a slot, on pressing of tab, it skips the content of 
slot if it slot is first or last element of dialog

## 💁 Possible Solution

Adding specific handling for slot elements, here is the patch i  am currently using :
```diff --git a/node_modules/@microsoft/fast-foundation/dist/esm/dialog/dialog.js b/node_modules/@microsoft/fast-foundation/dist/esm/dialog/dialog.js
index b251181..1467b10 100644
--- a/node_modules/@microsoft/fast-foundation/dist/esm/dialog/dialog.js
+++ b/node_modules/@microsoft/fast-foundation/dist/esm/dialog/dialog.js
@@ -219,11 +219,15 @@ export class Dialog extends FoundationElement {
             elements.push(element);
             return elements;
         }
+        if (element.tagName === 'SLOT'){
+          return elements.concat(Array.from(element.assignedElements()).reduce(Dialog.reduceTabbableItems, []));
+        }
         if (element.childElementCount) {
             return elements.concat(Array.from(element.children).reduce(Dialog.reduceTabbableItems, []));
         }
         return elements;
     }
+
     /**
      * Test if element is focusable fast element
      *
```

## 🔦 Context

This is useful whenever we want to use fast-dialog inside a web component with slots

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
