### ISSUE TITLE
feat: add readonly mode to picker

### ISSUE THREAD

**Issue by m-akinc** [microsoft/fast#5813]
# 🙋 Feature Request

I would like to have a read-only mode for the picker, where the selection input is hidden and only the selected items are shown (and are not interactive). A common way to style the picker's selections would be as pills/chips, and a read-only set of pills/chips would be a useful element to have.

## 🤔 Expected Behavior

Setting the readonly attribute on the picker would:
1. Hide the input control
2. Disable the interactivity of the selected items
3. Remove the selected items from the tab order

## 😯 Current Behavior

Picker has no read-only mode.

## 🔦 Context

I want to be able to display a set of selections that cannot be modified, and I want them styled the same way as the editable picker would style them (e.g. pills).

## 💻 Examples

I want something like this (non-interactive):
![image](https://user-images.githubusercontent.com/7282195/162256449-5d9a7654-3a75-44aa-aba7-0f2af369e5b0.png)

**Comment by scomea** [comment]
You may be able to create this behavior by using custom list items that eat clicks so they can't get deleted and have any aria attributes you may need to communicate their state and limiting the number of selected items the number of items in your list initially so no edit box shows up.  Not saying a read-only mode isn't interesting, just that their may be reasonable workarounds in the meantime.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
