### ISSUE TITLE
fix: scrolling back from end and forward retains next flipper in horizontal-scroll

### ISSUE THREAD

**Issue by robarbms** [microsoft/fast#5830]
# 🐛 Bug Report

Scrolling to previous will scroll the first in view card. This is different than the next behavior which scrolls to the last in full view card. When in view cards are slightly bigger than the viewport, this is causing the horizontal scroll to require another scroll to bring the last few pixels in view when scrolling to the end.

## 💻 Repro or Code Sample

Resizing the cards in the storybook to 120.1px wide exposes the problem. Scrolling back from the end, will scroll card #12 to the end even though its only partially in view. 1-2 pixels are off screen.

## 🤔 Expected Behavior

It should scroll back to card #13 since it's the last full in view card.

## 💁 Possible Solution

Should scroll to the last in full view card.

## 🔦 Context

Surfaced in FAST internal for Microsoft NTP.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by janechu** [comment]
This appears to have been resolved in #5831
