### ISSUE TITLE
feat: add control over 'parts' when extending fast foundation components

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#5832]
# 🙋 Feature Request

setting parts on shadowRoot elements makes them exposed for authors to customize (and abuse) easily.
when locking down components to enforce a design system rules is a concern, setting `part` attributes conflicts with that general intention.

wondering what other design system maintainers feel about that...

## 🤔 Expected Behavior

consumers of fast foundation components should be able to decide whether parts should be included in the template or not

There are rare cases where `part` is absolutely required.
So the ideal solution would probably be to opt-in (or out) (during component definition phase) to whichever parts needed

## 😯 Current Behavior

Parts are enforced in templates unless overriding.

## 💁 Possible Solution

Consumers of components may query all `part` attributes from within the component class and remove 'em programmatically, still this is not ideal as it results in dirty redundant solution that should be probably handled architecturally. 

I'm not fully keen with how definition of components work but can it be leveraged to

```js
export const myComponent = MyComponent.compose({
    baseName: "my-component",
    template,
    styles,
    parts: {
        base: true,
        control: false
    }
});
```

**Comment by chrisdholt** [comment]
Thanks opening this @yinonov - a key belief some of the core maintainers have held is that design systems are often on a spectrum of customization. Where that customization happens depends on the requirements of a given project; some may value more open approaches and some may want things more locked down. I think this falls into the latter camp which is a gap right now. We have some ideas brewing, but we'll start with an issue here and see if we can gather additional feedback from the community. 👍

**Comment by simonxabris** [comment]
I agree with @yinonov that the less escape hatches you have the more you're able to enforce consistency within the apps that are consuming the design system and in my opinion `part` is an escape hatch. Any new features that lets us customise this would be a welcome addition.

**Comment by yinonov** [comment]
exactly. it puts much trust in authors. which, unfortunately, hasn't been working out for us and the unification objective
But I can honestly say locking down has done wonders

**Comment by janechu** [comment]
With #6955 we are deprecated `@microsoft/fast-foundation`.
