### ISSUE TITLE
fix: generating palette with PaletteRGBOptions.preserveSource does not give cohesive results

### ISSUE THREAD

**Issue by CuddleBunny** [microsoft/fast#5852]
# 🐛 Bug Report

New palette generator does not yield cohesive colors relative to source color with `preserveSource: true`.

## 💻 Repro or Code Sample

In the `feature/fast-component-update-visuals` branch `ComponentStateColorPalette` has been deprecated in favor of a new approach which I believe is based on contrast instead of luminance. The new palette generation code does not guarantee that the source color will be included but has a `preserveSource` option to force it. 

Here is a sample showing the palettes generated using `ComponentStateColorPalette` and `PaletteRGB.from` both with and without `preserveSource`: [https://stackblitz.com/edit/typescript-9eyosz](https://stackblitz.com/edit/typescript-9eyosz). 

## 😯 Current Behavior

When using preserve, the source color feels out of place:

![image](https://user-images.githubusercontent.com/2207938/163596993-c629ef71-7749-4f13-8b97-632407cf8ba7.png)

## 🤔 Expected Behavior

After speaking with @bheston I understand that contrast based palettes offer more consistent results, especially with neutral colors. My main concern is with accent colors which are often based on brand colors. Some companies are becoming more flexible but some have very rigid color requirements.

I admit that these color algorithms are well outside my understanding but could a luminance based generator be included with the same number of steps in such a way that it can be used for accent colors while still meshing with contrast based neutral palettes?

**Comment by EisenbergEffect** [comment]
Assigned to @bheston to explore options with @CuddleBunny.

**Comment by janechu** [comment]
I believe this to be related to `@microsoft/fast-colors` which has been deprecated.
