### ISSUE TITLE
fix: copyright should be horizontally aligned with all footer items

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#5864]
# 🐛 Bug Report
The footer links are not in alignment:
![Screen Shot 2022-04-18 at 1 40 52 PM](https://user-images.githubusercontent.com/16669785/163874707-b2e37aa8-42f1-4203-9479-dd2295374af1.png)

## 💻 Repro or Code Sample
Visit https://www.fast.design or https://stage.www.fast.design/ 

## 🤔 Expected Behavior
All footer links should align on the same horizontal access point.

## 😯 Current Behavior
notice the footer links are not horizontally aligned and they should be.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by EisenbergEffect** [comment]
@huynhicode Can you take a look into this? Hopefully it's a quick fix but there are some nuances to the footer. I think that @radium-v has the details if you aren't familiar with that part of the site's code.
