### ISSUE TITLE
fix: building FAST results in hundreds of "failed to retrieve the git history" errors

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#5865]
# 🐛 Bug Report
![Screen Shot 2022-04-18 at 1 53 16 PM](https://user-images.githubusercontent.com/16669785/163876441-d7659e78-a033-4798-8bdd-a3eb58f547e9.png)

This depends on a resolution to #5868 #5867 before troubleshooting will continue. It seems that Docusaurus should gracefully handle these errors by not creating "lastUpdatedTime" value because the only way to retrieve this value is if they are in fact committed to source control.

If Docusaurus gracefully handles, one solution could be to generate the required API JSON data from the project they reside in and under source control. Then when compiling the website, all of these files have the data value because they exist in source control.

~~it originally appeared this may be related to GitHub Actions not having access to the entire log history.~~ However, after adding depth 0 to get the entire git log and GH token still occurred. 

The current theory is now that these files are not committed to source control and that is why it's failing. This may require a feature improvement to track API documentation in git.

## 🤔 Expected Behavior
No errors should exist on CLI output.

## 😯 Current Behavior
Hundreds of errors for the past couple of weeks have been displaying on Pipelines and Locally when running in VS Code.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
Does this repro outside vscode or is it specific to that tooling? I don’t repro locally outside vscode, so I’m curious if this is specific to that scenario.

**Comment by awentzel** [comment]
> Does this repro outside vscode or is it specific to that tooling? I don’t repro locally outside vscode, so I’m curious if this is specific to that scenario.

this started appearing on the pipeline last week and now appears locally when building the documentation sites.

**Comment by chrisdholt** [comment]
> > Does this repro outside vscode or is it specific to that tooling? I don’t repro locally outside vscode, so I’m curious if this is specific to that scenario.
> 
> this started appearing on the pipeline last week and now appears locally when building the documentation sites.

Thanks for the info.

@williamw2 this may be unrelated but it looks like the timeline tracks with the CEM work. Not sure if you can glean any potential insights from the errors above…

**Comment by williamw2** [comment]
I doubt it. The CEM changes do not touch any of the files in the /website/docs/api folder. CEM only modifies the markdown files in fast-foundation/src/ which indirectly modifies the files in the /website/docs/components folder. I am able to repro these errors locally when I run "yarn build" within the /sites/website/ folder. It appears to be Docusaurus related.

**Comment by williamw2** [comment]
I've done a little digging. This seems related to the "showLastUpdateTime" option in the docusaurus.config.js file. Setting this to "false" resolves the errors. It appears to have been changed to "true" here: #5505

**Comment by awentzel** [comment]
> I've done a little digging. This seems related to the "showLastUpdateTime" option in the docusaurus.config.js file. Setting this to "false" resolves the errors. It appears to have been changed to "true" here: #5505

Thanks @williamw2 this is helpful. That's actually the attribute I'm testing for right now.  When set to "true" that value should be writing to the page, instead it's null.  I'll poke around Docusaurus and file a bug on them if I can't figure it out in 15 minutes.

**Comment by williamw2** [comment]
No problem, @awentzel. I also notice that all of the errors occur on files that are not actually tracked in github, which is probably why github does not return a history. It seems odd to me that this is even on. Maybe I'm blind but I don't see the "last updated" dates on any of the pages on fast.design. If there isn't a better solution you can probably just turn it off.

**Comment by EisenbergEffect** [comment]
We'd like to have the last updated date for each document if possible. But if there's no way to make it work with how docusaurus is implemented, then we can just turn it off. Let's at least try to determine that for sure first though. Research shows that a "freshness" date on documentation helps instill confidence in the community.

**Comment by EisenbergEffect** [comment]
I'm not sure they are related, but I've assigned the other issues to @huynhicode to investigate since she's been doing lots of other docs improvements.

**Comment by awentzel** [comment]
Docusaurus requires git tracked files to determine last updated date. API files are not tracked and so these errors result. Resolution is to not use last updated date for Docs at this time util all files are tracked.
