### ISSUE TITLE
fix: warnings when building sites

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#5867]
# 🐛 Bug Report
![Screen Shot 2022-04-18 at 3 41 52 PM](https://user-images.githubusercontent.com/16669785/163888821-c4dff349-0d00-45b5-9403-bd6f2435c63d.png)

## 💻 Repro or Code Sample
1. cd sites/website
2. yarn
3. yarn api-documenter markdown -i src/docs/api -o docs/api
4. This is the internal command that's creating these issues.

## 🤔 Expected Behavior
Warnings should not occur

## 😯 Current Behavior
Many warnings, and they could be leading to documentation site issues.  Running `buildAPIMarkdown()` creates these errors on `generate-docs.js` execution.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by awentzel** [comment]
@bheston said "Just a guess, but design-system-provider/index.ts  has {@link DesignSystemProvider} in the docs on line 1078. This references the class on line 146, but it's marked @internal. Do elements need to be marked public to turn up in the docs?"

@nicholasrice agreed, and said "exports marked as internal won't emit to docs"

**Comment by EisenbergEffect** [comment]
@huynhicode Here's another few documentation generation issues to look into when you get a chance. These likely need to be fixed directly in our source code, either by using some other link/doc format or by correcting some visibility of linked types.

**Comment by nicholasrice** [comment]
The DesignToken warnings *may* be impossible to circumvent. I recall API documenter being unable to surface two exports by the same name (in this case a const variable and an interface). I haven't looked into it in a while so that may be fixed in newer versions of API extractor, but just wanted to drop this for context.

**Comment by awentzel** [comment]
Resolved most issues with the PR above.  two issues remain: 

![Screen Shot 2022-04-28 at 3 59 10 PM](https://user-images.githubusercontent.com/16669785/165883126-73d5974b-8b53-42ab-9d3c-676cb77d21d6.png)
