### ISSUE TITLE
fix: windows build pipeline fails on Accordion tests

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#5874]
# 🐛 Bug Report
![Screen Shot 2022-04-21 at 7 33 37 AM](https://user-images.githubusercontent.com/16669785/164481787-45448a40-fe18-4813-b61d-e49296b30558.png)

## 💻 Repro or Code Sample
1. Rebuild
2. run 'yarn lerna run test --stream since=origin/master'
3. See the errors that happen only on Windows Platform

## 😯 Current Behavior
Windows platform fails the test scenario

## 💁 Possible Solution
Fix the test harness

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, **Windows**, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
test have been passing for awhile and new accordion tests have been added - closing this out as no repro. If you find this repro's again, feel free to reopen!
