### ISSUE TITLE
fix: options don't display above if not enough space below in FluentCombobox 

### ISSUE THREAD

**Issue by eero-dev** [microsoft/fast#5881]
# 🐛 Bug Report

Basically the same as here: https://github.com/microsoft/fluentui/issues/3719

## 💻 Repro or Code Sample

Solution with repro in Index.razor
[Repro.zip](https://github.com/microsoft/fast-blazor/files/8353453/Repro.zip)

## 🤔 Expected Behavior

The options should display above the combobox if there is not enough space below

## 😯 Current Behavior

The options display below and can't be seen
![bug](https://user-images.githubusercontent.com/49983218/160192065-4b9f1546-814e-4628-bcee-a98b0c0fa399.gif)

## 🔦 Context

Unable to adopt the library for UI since the ComboBox element is not working as desired

## 🌍 Your Environment

* OS & Device: Windows PC
* Browser: Chrome (latest ver)
* .NET and FAST Version: Latest

**Comment by chrisdholt** [comment]
I believe this has been fixed with the migration to Floating UI. If you still repro with the latest alpha packages, please feel free to reopen.
