### ISSUE TITLE
feat: add custom filtering option to combobox

### ISSUE THREAD

**Issue by simonxabris** [microsoft/fast#5882]
# 🙋 Feature Request

I'd like to be able apply my custom filtering logic when using the combobox in an ergonomic manner.

## 💁 Possible Solution

My idea is that a `customFilter` property could be added to the `Combobox` class that users can bind a function to with (roughly) the following signature: `(option: ListboxOption) => boolean`. This function would define if an option fits the given criteria or not and then pass this in to this `filter` here: https://github.com/microsoft/fast/blob/cae5b3fab883ce38f623192ba9d7a8b105208cd2/packages/web-components/fast-foundation/src/combobox/combobox.ts#L320-L322

## 🔦 Context

This would make the combobox much more flexible to use in my opinion, in our org this need comes up very frequently.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated per #6955.
