### ISSUE TITLE
fix: fast-accordion-item has higher z-index than other components

### ISSUE THREAD

**Issue by CuddleBunny** [microsoft/fast#5885]
# 🐛 Bug Report

fast-accordion-item has a z-index of 2 which causes it to appear above dialogs and other components with a z-index of 1.

## 💻 Repro or Code Sample
https://stackblitz.com/edit/typescript-nsa8l3

## 🤔 Expected Behavior

Accordion items should appear below dialogs and other components which use z-index.

## 💁 Possible Solution

In my own components I've removed z-index and left the rest of the styles the same. This has been working as expected for 2 years without issue. I'm unsure of any edge cases for which this z-index addition was intended.

**Comment by chrisdholt** [comment]
I believe that #5381 resolves this - let's confirm and if so we can close. Thanks @cuddlebunny!

**Comment by CuddleBunny** [comment]
> I believe that #5381 resolves this - let's confirm and if so we can close. Thanks @CuddleBunny!

it does, closing
