### ISSUE TITLE
feat: add basic styles and storybook testing setup for fast-foundation

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5886]
# 🙋 Feature Request
With the coming removal of `fast-components`, we will need/want some basic styles to ensure that templates can accommodate common scenarios and validate that certain changes don't cause significant regressions. This feature request exists to add a new storybook testing site with a thin layer of visual styles to provide support for testing the foundation classes and templates.

## 🤔 Expected Behavior
The fast-foundation package will support local testing with limited visual styles to ensure templates meet common needs.

## 😯 Current Behavior
No such testing exists!

**Comment by radium-v** [comment]
Related: https://github.com/microsoft/fast/pull/5821

We should use Storybook as intended, with atomic stories for each component.

**Comment by chrisdholt** [comment]
> Related: #5821
> 
> We should use Storybook as intended, with atomic stories for each component.

This is the hope - planning on leveraging this work for the conversion!
