### ISSUE TITLE
rfc: add a User friendly approach to Documentation

### ISSUE THREAD

**Issue by Mashiane** [microsoft/fast#5928]
# 💬 RFC

Thanks for an awesome framework. I was just going through the documentation and I must admit, it's not "newbie" friendly at all. I feel like the assumption that is being made here is that "people know what we are talking about". A simple distinction is  what a "field" is and what an "attribute" is when creating HTML elements in the context of Fast. Are these interchangeble / mutually exclusive, what can be used in a basic <html></html> context?

If however the expection from you is that people "should know what we are talking about", then its all good, but what about those who are interested and "dont know what you are talking about" and would like to use your framework. Yes, there are links in the documentation that go to MSN docs, granted, a simple example is I was trying to find where "events" are defined for each of the components listed. Nada.

## 🔦 Context

If you were explaining this to your grandma or your 5 year old child, would they understand? How many questions would they have. If its not following that kind of approach, granted. It just takes away all the developer friendliness by being opinionated.

## 💻 Examples

A simple example is the "appearance" attribute which appears in most of the Live Editor examples, which is not featured on the "fields" or "attributes" section of the documentation. Its there on the starting of the document, this however can tend to be lost in translation.

I could be wrong, but at first look, people are interested in how you define the HTML element first, which attributes it uses, which styles etc etc, and then with more experienced users, then the API is the go area. The documents start with explaining the HTML element, do an example using some attributes, then soon jump into the API. The "attributes" section at the bottom of the documents per element, what does it apply to? If it applies to the Live Usage example, doesnt it make better sense to move that section up in the documentation for ease of referral?

#Just Thoughts.

**Comment by EisenbergEffect** [comment]
Thanks for the feedback @Mashiane ! We really appreciate it. We're working on a next round of updates to the component documentation to include things like events. It's also great feedback on the ordering of the content and the terminology. I'm not 100% sure what the best way to handle the terminology is, especially with something like fields vs. attributes. I think we do explain this in the docs somewhere but maybe your path through the content took you around that without seeing it first. I'll think a bit more about that and see if we can improve things.

**Comment by EisenbergEffect** [comment]
We've made a number of improvements to content based on this issue. We still know we have a lot more work to do here. I'm going to close this issue out now since it is very general. We can open individual issues for specific issues in the future. Thanks again for the feedback!
