### ISSUE TITLE
fix: [a wrong Animation is added to tab when re-rendering the tab panels ] in [tabs]

### ISSUE THREAD

**Issue by JennyzhaoM** [microsoft/fast#5933]
# 🐛 Bug Report

There is an issue on the internal function tabpanelsChanged which calls handleActiveIndicatorPosition to renew the tab status by using the the previous active tab index. However ths prevActiveTabIndex was not updated to the current index if we had switch once betore. For this scenario,  1. we click on the second tab to call change the active tab from tab1 to tab2.  2. we make click on tab3 to and changes to the tab3 Panel by rerender it, so it will trigger the tabpanelsChanged. we noticed there will be animation making it like you were switching from tab 2 to tab3, but you were actually not making switch but just update the tabpanel.  

I need to call the adjust(0) as work around to update the previous active id = current active id, so there is no animation add on it. 

## 💻 Repro or Code Sample

I don't have a repro since I add a work around solution. The issued test link would need mock data to verify. Please contact me if you need to see the issue.

## 🤔 Expected Behavior

expected no animation when the tabPanel is re-rendered and trigger the tabpanelsChanged()

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
I think we'll need some kind of repro of this, even if it doesn't include the exact visual effects you're currently using. Without that, I'm not sure we can understand your specific scenario. Thanks!

**Comment by JennyzhaoM** [comment]
I just remove the work around fix in my build, so it the issue can be repro in the test link: https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffast%2Fissues%2F5933

https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffast%2Fissues%2F5933

**Comment by chrisdholt** [comment]
> I just remove the work around fix in my build, so it the issue can be repro in the test link: https://www.msn.com/en-us/feed?item=spalink%3A20220505.593/debug&item=flights%3Aprg-1sw-gbcnews3&wpoitems=Carousel%3AGroupedXfeedUpsell%3Bdynamicregion%3ACarouselCards

Most everything is 404'ing on this page. Are you able to put together a repro using just the basic components or is this specific to your scenario?

**Comment by JennyzhaoM** [comment]
Sorry for the late response. 
Here is the repo: 
Test link: https://www.msn.com/en-us/feed?item=spalink%3A20220704.380/debug&item=flights%3Aprg-1sw-gbcnews3&wpoitems=Carousel%3AGroupedXfeedUpsell%3Bdynamicregion%3ACarouselCards
1. set the network to "slow 3G" from the devtool - network, click disable cache
![image](https://user-images.githubusercontent.com/100661201/177213400-fb138165-c2a1-41d8-bbbb-69e55eee0cee.png)
2: wait for the News tabs card to appear in line 3th
3. click the second tab and wait for the content load
4. observe the underline switch from 2nd tab to the 1st tab, but the active one is actually the 2nd tab. 
5. if the issue doesn't appear, try clicking other tabs to trigger the load again or refresh the homepage.

**Comment by janechu** [comment]
I don't believe this is related to a package maintained in this project.
