### ISSUE TITLE
fix: Tooltip position attribute has no effect in <fluent-tooltip> web-component

### ISSUE THREAD

**Issue by donaldmcn** [microsoft/fast#5938]
# 🐛 Bug Report

When using the <fluient-tooltip> web component the position= attribute has not effect. The tool tip is always being rendered in the same options (appears to be the top / center)

## 💻 Repro or Code Sample

[](https://stackblitz.com/edit/typescript-xq1him?file=index.ts)

## 🤔 Expected Behavior

the tool tip should render in the position indicated by the position attribute

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
Thanks @donaldmcn for this. I believe that I'm repro'ing this issue with this stackblitz: https://stackblitz.com/edit/typescript-xq1him as any value passed for position doesn't seem to take effect (repro's with the FAST components as well as the Fluent component in example).

@scomea would you mind taking a look?

**Comment by scomea** [comment]
The problem is that tooltip is dependent on anchored-region, and we don't automatically register dependencies.  If you register fluentAnchoredRegion it works.  We have an issue for this - https://github.com/microsoft/fast/issues/5423
