### ISSUE TITLE
fix: Disabled options in Combobox do not get filtered

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#5952]
# 🐛 Bug Report

When using the FAST `Combobox` (`fast-combobox`), and you give it an option that is set to `disabled`, then if the `Combobox` has its `autocomplete` set to filter the options (`inline` or `both`), then when you enter in text, even if the disabled item doesn't match the entered text it still shows up in the dropdown.

While harmless in that you can't select it, it's at least a visual annoyance.

## 💻 Repro or Code Sample

Use the below snippet and then type in "Mayr".:
```
<fast-combobox autocomplete="list">
    <fast-option value="1">Mary</fast-option>
    <fast-option value="2" disabled>Sue</fast-option>
    <fast-option value="3">Frank</fast-option>
</fast-combobox>
```

## 🤔 Expected Behavior

In the above example if one types "Mary", "Sue" should not show up in the dropdown.

## 😯 Current Behavior

If a user types "Mary", "Sue" remains in the dropdown.

## 💁 Possible Solution

Improve the filtering logic in `Combobox` to exclude disabled items that don't match the filter.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
