### ISSUE TITLE
Associated form elements' validation is not observed

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#5963]
Shouldn't the validation state be an observable?
The use case is I'm trying to create a custom error message in the template like this:
```
${when( x => x.validationMessage, html`<span class="error">${ x => x.validationMessage }</span>`)}
```
This will not change the view because `validationMessage` is not observed. Nor any of the validity variables.
My workaround was to do the following:
```
	@observable _valid = true;

	@volatile
	get errorValidationMessage() {
		return this._valid ? '' : this.validationMessage;
	}

	override validate() {
		super.validate();
		if (this.proxy instanceof HTMLElement) {
			this._valid = Boolean(this.validationMessage);
		}
	}
```
And then in my template use `errorValidationMessage` to set the message.
This forces me to expose another property (`_valid` in this case) on the element.
Is there a "cleaner" way to do this? Would you be open to a PR where we have observability over validation status?

**Comment by usrrname** [comment]
Hey, great minds think alike! (totally unhumble brag)

This is a great point you raise! I'm not a maintainer but I am having a similar difficulty here although I made a custom attribute specifically observing `validityState.valid` and am *still* unable to set the invalid attribute. https://stackblitz.com/edit/vitejs-vite-ef5nob?file=src/components/custom-text-field/custom-text-field.template.ts

Any ideas how to trigger `validate()` or `setValidity()` on form submit ?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
