### ISSUE TITLE
rfc: What should be included in SSR DOM shim

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5970]
The SSR package requires certain DOM global to exist with certain functionality to function properly. It ships these in an installable dom-shim export that is imported by application authors. I'd like to discuss what exactly we put in this DOM shim, because the required globals will vary depending on what APIs components are accessing.

For instance, the `@microsoft/fast-element` package accesses far few DOM API's than `@microsoft/fast-foundation`, which accesses fewer than the now extinct `@microsoft/fast-compoonents` package. Regardless of what we choose to expose, extending the DOM shim needs to be easy for application authors, but aside from that I think there are two support models that make sense to me:

**Support fast-element out of box**:
We can choose to support only the APIs used by `@microsoft/fast-element`. This would expose the smallest possible dom-shim and only expose what is necessary for fast-element to function.

**Support fast-foundation out of box**:
This would expose a DOM shim that can handle all APIs leverage by `@microsoft/fast-foundation`. This is a larger set of APIs and will result in a larger DOM shim. The largest addition here will be the addition of a functional `CSSStyleSheet` to support `DesignToken`.

My preference is to only expose APIs required by fast-element. This keeps the shim lean for all users, while still extensible for authors that need more APIs to render correctly, but I'm open to discussion here. If we take this route, we'll likely want to expose a DOM shim that handles fast-foundation APIs from fast-foundation itself.

**Comment by KingOfTac** [comment]
Does the shim get exported by fast-element or the SSR package? If it was exported by fast-element, I think it would make sense for it to only provide the APIs needed for fast-element to function and then foundation could extend the shim and re-export it. This way users who only need fast-element get the minimal shim and users who need the extra APIs provided by foundation get those as well.

**Comment by nicholasrice** [comment]
The shim does get exported from the SSR package. I agree with you though @KingOfTac, to me it makes sense to minimally support fast-element w/ the default DOM shim. fast-foundation can expose it's *own* shim that extends that shim. Though, that would put fast-foundation in an odd position of taking a dependency on the FAST ssr package (in order to extend the shim).

Another alternative would be to expose multiple shims from separate endpoints of the SSR package. For instance, folks wanting a minimal shim could include:

```ts
import "@microsoft/fast-ssr/install-minimal-dom-shim";
```

whereas folks wanting the foundation shim could include:
```ts
import "@microsoft/fast-ssr/instal-foundation-dom-shim";
```

**Comment by KingOfTac** [comment]
I think the alternative would make the most sense. No reason for foundation to take on the extra dependency for something that isn't a requirement for it to function.
