### ISSUE TITLE
fix: Escape key is not handled for menu items

### ISSUE THREAD

**Issue by mollykreis** [microsoft/fast#5984]
# 🐛 Bug Report

According to the [ARIA accessibility guidelines](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role#keyboard_interactions), when you press Escape on a menu item, the menu should close and focus should return to the parent menu item.

In FAST, when you press Escape on a menu item, nothing happens.

## 💻 Repro or Code Sample

1. Go to https://explore.fast.design/components/fast-menu and selected the "Nested" example
2. Focus the menu and use the keyboard to open one of the sub-menus
3. With the sub-menu focused, press Escape
4. Notice nothing happens

## 🤔 Expected Behavior

When you press Escape with a submenu focused, that submenu should close and focus should move to the parent menu item.

## 😯 Current Behavior

When you press Escape with a submenu focused, nothing happens.

## 💁 Possible Solution

Add logic for handling the Escape key being pressed on a menu item.

## 🌍 Your Environment

Not environment dependent

**Comment by chrisdholt** [comment]
Planning on picking this up once #6113 goes in.
