### ISSUE TITLE
fix: Keyboard Functionality Still Works in Readonly Sliders

### ISSUE THREAD

**Issue by break-stuff** [microsoft/fast#5985]
# 🐛 Bug Report

Users can still update readonly slider inputs using the keyboard.

## 💻 Repro or Code Sample

https://codesandbox.io/s/web-component-header-test-forked-kg241l

## 🤔 Expected Behavior

Keyboard functionality to update the slider value should be disabled when the component is `readonly`.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
fixed with #5987 via @break-stuff so closing this
