### ISSUE TITLE
fix: Recycle Property On Repeat Does Not Work When Binding Does Not Change

### ISSUE THREAD

**Issue by Brian-Hofmann** [microsoft/fast#5996]
When using the repeat directive with recycle false, the view is still reused when the binding does not change.

Example code:

I was using a custom dropdown I made using FAST.

```
<my-dropdown>
   <my-option></my-option>
   <my-option></my-option>
   <my-option></my-option>
</my-dropdown>
```

When I used my dropdown in an application, I used the repeat directive as so:

```
<my-dropdown>
${repeat(
     (f) => f.options ?? [],
    html<any>`<my-option></my-option>`
    , { recycle: false }
    )}
</my-dropdown>`;
```

I run specific logic in my `slottedNodesChanged` function on my dropdown and noticed it was not running whenever the dropdown got new options that were the same length as the number of options currently in the dropdown. 

When I dug into the issue, it looks like the recycle property is only used in the `updateViews` function in the **repeat.js** file which is only hit if the binding is not the same. In my case, the binding does stay the same and that causes me to hit the else and call `refreshAllViews` with the default param of false which causes my view to be reused (thus `slottedNodesChanged` does not fire when the number is the same).

![image](https://user-images.githubusercontent.com/37916393/169087719-1ad1039f-2f98-41d4-8d2f-6ea2509433d2.png)
![image](https://user-images.githubusercontent.com/37916393/169087735-50f939d9-6681-458d-95a1-95cf985a3f2c.png)

**Comment by prudepixie** [comment]
This iteration seems to improve the perf when repeat has the default settings of {recycle: true}, what is curious is why {recycle:false} is still generally slower than {recycle:true}
<img width="2227" alt="recycle property implementation" src="https://user-images.githubusercontent.com/6309989/172268551-53b3cc2c-5e31-4ca7-8eb6-6dfbf2a356cd.png">

**Comment by prudepixie** [comment]
Here's a representation of the performance between refreshView() and updateView() - updateView() much slower
using default options where {recycle: true}
![repeatNested Benchmark refreshView() vs updateView()](https://user-images.githubusercontent.com/6309989/172492759-2356dd24-4759-419e-a970-1cd289842554.png)

**Comment by prudepixie** [comment]
faster in {recycle: false} case 
![repeatNestedNoRecycle Benchmark refreshView() vs updateView()](https://user-images.githubusercontent.com/6309989/172497522-d36607e8-744c-493b-8f2f-bb7be700f707.png)
