### ISSUE TITLE
feat: add event support to SSR 

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#6009]
# 🙋 Feature Request
This feature adds event support to fast-ssr. Specifically, it adds the `Element.addEventListener()`, `Element.removeEventListener()`, and `EventTarget.dispatchEvent()` methods, and the `CustomEvent` global type.

It also adjusts the ElementRenderer to support custom events.

Event support is for programmatically emitted events on custom elements only - handlers on native elements will not be invoked and no browser events are emitted automatically.

See https://github.com/microsoft/fast/issues/5961 for more context.

**Comment by EisenbergEffect** [comment]
Did we get this in or was it coming in a follow-up after the initial package publish?

**Comment by EisenbergEffect** [comment]
If the event bubbles all the way up and isn't handled by a custom element in the stack then we should emit the event on the window shim.

**Comment by nicholasrice** [comment]
This is still open; it hasn't been integrated yet.
