### ISSUE TITLE
fix: Submenus Not Displaying Correctly in CodeSandbox

### ISSUE THREAD

**Issue by break-stuff** [microsoft/fast#6012]
# 🐛 Bug Report

Submenus are not rendering correctly in a CodeSandbox environment

## 💻 Repro or Code Sample

https://codesandbox.io/s/stupefied-moon-2skhey

## 😯 Current Behavior

When rendering submenus in a CodeSandbox environment, they are not hidden initially and overlap the menu contents rather than display to the right.

## 💁 Possible Solution

It looks like the slot is not being appropriately applied to the submenu. Setting a timeout to check for parent menus should fix the issue.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
Thanks for the issue @break-stuff - looks like an issue with AnchoredRegion not being registered perhaps...we'll take a look.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
