### ISSUE TITLE
fix: autofill background color breaks in text field

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#6073]
textfield's autofill style only applies on the input itself and when affixing something to start / end slot, u'd notice the bug.

I would just have it stretched and positioned absolutely to make autofill display fully

note that this will override the natural inline `size` behavior

![image](https://user-images.githubusercontent.com/15140652/172377712-aa390f23-1d15-4659-aa93-cb762cdc8f01.png)

**Comment by EisenbergEffect** [comment]
@bheston I have created a new label `area:adaptive-ui` and will be assigning related issues to the Design Systems board for you. This will include anything explicitly related to adaptive UI but also anything that pertained to the styles of the old fast components.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
