### ISSUE TITLE
fix: Use of API Extractor @internal flag used against intent and breaks when filtered

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#6081]
# 🐛 Bug Report

The fast-element 2.0 branch included a change to trim the primary API Extractor declaration output to only `public` and `beta` tags. We have commonly used `internal` to mark private class members, but have also done this for protected members and even some public members.

Now that the default types export is the trimmed declarations, libraries that have subclassed the fast-foundation components no longer compile, for instance Fluent UI.

## 💻 Repro or Code Sample

fast-foundation exports a class for `Combobox` with an internal member variable pointer to the `listbox` element:

```ts
/**
 * @public
 */
export class Combobox extends FormAssociatedCombobox {
    /**
     * @internal
     */
    public listbox: HTMLDivElement;
}
```

This is a useful reference for an implementation class, but with it marked `internal` the subclass doesn't compile:

```ts
import { Combobox as FoundationCombobox } from '@microsoft/fast-foundation';

export class Combobox extends FoundationCombobox {
  public connectedCallback(): void {
    super.connectedCallback();

    if (this.listbox) {
      fillColor.setValueFor(XXX===> this.listbox <====XXX, neutralLayerFloating);
    }
  }
}
```

This is an example, but is true for a number of functions.

## 🤔 Expected Behavior

Public and protected member functions should be marked `public` so they are included in the type declaration.

## 😯 Current Behavior

Members are missing from type declarations and dependent projects won't compile.

## 💁 Possible Solution

We should mark all public and protected members as `public` for API Extractor. The [guidance on the release tags](https://api-extractor.com/pages/setup/configure_rollup/) seems to apply more to hidden implementation members than simply _not_ being public, which is how we've been using them.

Additionally, we should consider observing the recommendation to prefix true internal members with an underscore. This check seems to work for top-level exports like classes, but it doesn't appear to be working as documented for class members.

This actually feels like a missing feature of API Extractor. They need to understand that protected members can be used within the subclass but not called externally. In their current model it doesn't seem there's a way to express this, therefore they must be public even though that is also misleading.

## 🔦 Context

I'm trying to upgrade Fluent UI, at least locally, to be able to incorporate and continue development of the `adaptive-ui` package, which is limited now without `fast-components`.

**Comment by janechu** [comment]
I believe Fluent UI is now removing `@microsoft/fast-foundation` as a dependency, we will also be migrating from yarn to npm and updating all of our dependencies where possible, which may fix the issue depending on changes to the `api-extractor`. I'm going to close this issue for now, with the intent that we re-open it after the v2 launch of `@microsoft/fast-element` if it still is an issue.
