### ISSUE TITLE
fix: proxy fails to support native attributes in text field

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#6082]
# 🐛 Bug Report

text field isn't delegating `autocomplete`, `enterkeyhint`, `name`, `inputmode` (not supported by safari but might benefit in other browsers) to its proxy

## 💻 Repro or Code Sample

just paste the following in [fast-explorer](https://explore.fast.design/components/fast-text-field)

```html
<fast-text-field name="phone" inputmode="tel" autocomplete="off"></fast-text-field>
```

## 🤔 Expected Behavior

text field should support the mentioned attributes to play well in production

## 😯 Current Behavior

it doesn't :)

**Comment by rajsite** [comment]
Also ran into the need to configure autocomplete, are there any specific complexities to be aware of related to the ElementInternals polyfill etc?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
