### ISSUE TITLE
feat: Update fast dialog to take advantage of new platform capabilities

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#6088]
We should look at updating our dialog component to take advantage of new platform capabilities like those described in this article - https://web.dev/building-a-dialog-component/.

**Comment by rajsite** [comment]
This would be interesting for us as well. We use the Foundation Dialog class and template to implement a Drawer component and behaviors like capturing / returning focus would be helpful.

The above screenshot shows how while the drawer is open I can still tab to the button underneath it which I imagine would be prevented if the dialog template leveraged the native dialog element.

![image](https://user-images.githubusercontent.com/1588923/174396440-26000e3e-3d6f-437d-b97f-e57ffc181bce.png)

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
