### ISSUE TITLE
perf: when script option is turned on, enable custom script to run benchmarks

### ISSUE THREAD

**Issue by prudepixie** [microsoft/fast#6110]
Following the script that was created under the **Repeat** benchmark, there needs to be a way to run the script that compiles the JSON object that the script reads into a table that is more readable. 

Tracking work here https://github.com/microsoft/fast/tree/users/wendy/custom-script
- There is a PR in tachometer where you can turn on 'collate' and it would filter the table to separate tables for better readability of the results, so to achieve this with my script, I currently have to symlink to that PR/branch 
- The next task around this work is to figure out a 'base suite' of benchmarks that would be able to test Repeat holistically.
-----------Update-----------------------------

Currently, each 'configuration' is generated to a unique url that is passed into the benchmarks array (for tachometer config), and the entryName under measurement all point to the same _operation_ 

```
"url": "dist/fast-element_repeat-clickTrigger10x.html?template=basic&method=reverse&loopCount=1&itemCount=500",
...
  "measurement": [
        {
          "mode": "performance",
          "entryName": "clickTrigger10x"
        },
        {
          "name": "usedJSHeapSize",
          "mode": "expression",
          "expression": "window.usedJSHeapSize"
        }
      ]
```

another possible approach is to create unique entryNames under the measurement array (for tachometer config):
```
  "measurement": [
        {
          "mode": "performance",
          "entryName": "reverse"
        },
        {
         "mode": "performance",
          "entryName": "push"
        },
       {
         "mode": "performance",
          "entryName": "shift"
        }
      ]
```

**Comment by prudepixie** [comment]
This work is moved back to backlog, as this works locally, but to merge into the main branch, would have to wait until the collate PR gets merged to tachometer.

**Comment by janechu** [comment]
Benchmarks have been redone to use the tensile perf package see #6968. As such this issue is no longer valid.
