### ISSUE TITLE
fix: Combobox does not always allow arbitrary values as its value

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#6111]
# 🐛 Bug Report

The Combobox should always allow arbitrary values to be entered as its `value`. Currently, however, there is a (common) situation where this is prevented. If, at any point, a user selects a value that is one of the dropdown options, the user can then _not_ have an arbitrary value (one not represented by any option) accepted as the Combobox `value`.

If, prior to any option being selected as the value, a user enters an arbitrary value, that value will be accepted as the Combobox `value`.

## 💻 Repro or Code Sample

See [this Stackblitz example](https://stackblitz.com/edit/typescript-6epjle?file=index.ts,index.html).

## 🤔 Expected Behavior

The Combobox should update its `value` _always_ to user entered input.

## 😯 Current Behavior

See description above.

## 🔦 Context

Without the Combobox handling this properly, a larger burden is placed on the consumer for detecting invalid values. Ideally, we would get a `change` event, inspect the `value` of the Combobox, verify that that value is valid or not, and respond appropriately. The current behavior would require us to track the current value of the Combobox through other means (like the `input` event, or DOM inspection), which is more awkward.

**Comment by atmgrifter00** [comment]
@EisenbergEffect, I thought I had fixed this issue with the above PR (#6415), but that didn't cover the case for the `autocomplete` modes of `inline` and `both`. Apologies. I will have a new PR up shortly to address this.

**Comment by EisenbergEffect** [comment]
Not a problem. Adding @chrisdholt since he manages the component work.

**Comment by atmgrifter00** [comment]
Fixed by [https://github.com/microsoft/fast/pull/6145](https://github.com/microsoft/fast/pull/6145) and [https://github.com/microsoft/fast/pull/6242](https://github.com/microsoft/fast/pull/6242).
