### ISSUE TITLE
rfc: new render directive for advanced MVVM

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#6114]
# 💬 RFC

FAST has a powerful rendering engine with more capabilities than what are exposed out-of-the-box today. Of note, it has particularly strong support for MVVM through its basic templating model. However, while the engine supports very advanced MVVM techniques developed on other platforms over the last 15 or so years, FAST doesn't expose easy or ergonomic ways of using them. They are only accessible through the creation of custom directives, which is a more advanced task, not presently documented (docs coming for v2 though!).

This RFC proposes a general purpose `render` directive to unlock more advanced MVVM scenarios. The directive will not be bundled with the core, but will be made available through a special export such as `@microsoft/fast-element/render`.

## 🔦 Context

Often times there's a need to render a template over part of a model. Or to render different versions of a template over the same model depending on scenario. Or to render a list of various types of objects, each with their own specialized template, sometimes even with variations on the templates depending on context. All these scenarios are *possible* today but they are not easy or intuitive to accomplish. They typically involve writing custom directives, as a bare minimum.

## 💻 Examples

In this RFC, I'm going to propose a new `render` directive that makes the above scenarios easier. To explain its capabilities, let's start with a very simple example model and a couple of basic templates:

### Example Model

```ts
class Address {
  @observable city: string;
}

class Person {
  @observable name: string;
  @observable address: Address;
}
```

### Example Templates

```ts
const addressTemplate = html<Address>`
  ${x => x.city}
`;

const editAddressTemplate = html<Address>`
  <input type="text" :value=${bind(x => x.city, twoWay)}>
`;
```

### Example Scenarios

Now, given an instance of a `Person` model, how would be apply either of the address templates? It is not straight forward today:

```ts
const personTemplate = html<Person>`
  Name: ${x => x.name}

  ${...how do we use the addressTemplate with the x.address property???...}
`;
```

There seems to be no way to apply the `addressTemplate` to the `address` property without either re-working the `Person` model or reworking the `addressTemplate`. This is where the `render` directive would come into play. Here's how you would accomplish this scenario:

```ts
const personTemplate = html<Person>`
  Name: ${x => x.name}
  ${render(x => x.address, addressTemplate)}
`;
```

A similar scenario can arise when we've got an unknown object that we want to render. Imagine for a moment that the value of `address` could be one of several different types of addresses, and we need to render a different template depending on the type. If we want to build this in an extensible way, we should avoid if/else and switch/case constructs that select templates, but rather handle this in a more polymorphic way where the model can tell the render what its template is. With this in mind, we can extend the `render` directive so that it can locate templates, and perhaps provide a simple decorator-based approach for associating templates with models. Here's an example:

```ts
@renderWith(addressTemplate)
class Address {
  city: string;
}

const personTemplate = html<Person>`
  Name: ${x => x.name}
  ${render(x => x.address)} // finds the template associated with the address value and renders it here
`;
```

Another scenario complicates matters. What if we want to render different templates based on context? The `render` directive handles this in a pretty straight forward fashion when the template is known:

```ts
const personTemplate = html<Person>`
  Name: ${x => x.name}
  ${render(x => x.address, editAddressTemplate)}
`;
```

But what about when a non-default template is needed for an unknown value? We can handle this by extending the metadata associated with views.

```ts
@renderWith(addressTemplate)
@renderWith(editAddressTemplate, "edit")
class Address {
  city: string;
}

const personTemplate = html<Person>`
  Name: ${x => x.name}
  ${render(x => x.address, "edit")}
`;
```

In the above case, the value of the address is used to look up a template, and in particular, a template identified as the "edit" template.

Finally, what if the type of template for the same model needs to be selected dynamically? We can do that in the simple scenario by enabling a binding for the template itself:

```ts
const personTemplate = html<Person>`
  ${render(x => x.address, (x, c) => c.parent.mode === "edit" ? editAddressTemplate : addressTemplate)}
`;
```

And we can similarly enable this for the more polymorphic scenario as well:

```ts
@renderWith(addressTemplate)
@renderWith(editAddressTemplate, "edit")
class Address {
  city: string;
}

const personTemplate = html<Person>`
  ${render(x => x.address, (x, c) => c.parent.mode)}
`;
```

## Alternatives

Several alternatives were explored as part of creating this proposal.

### Extending Template

We could accomplish a set of scenarios like this:

```ts
const personTemplate = html<Person>`
  Name: ${x => x.name}

  ${addressTemplate.with(x => x.address)}
`;
```

However, this has a few distinct disadvantages:

* We must include this functionality with the core, as part of templates, so it won't be tree-shakeable, increasing our minimal bundle size. This isn't great since this functionality is not typically needed when creating design system components at all. It's more of an application-oriented feature.
* This does not work for more dynamic cases since the only way to accomplish this is either by implementing something like `render` and using it internally anyway, or by implementing a different custom directive with less capability.

### Bake it into Content Rendering

We could try to accomplish this by baking this into our normal content binding. That would look like this:

```ts
@renderWith(addressTemplate)
class Address {
  city: string;
}

const personTemplate = html<Person>`
  Name: ${x => x.name}
  ${x => a.address}
`;
```

This is very nice when the decorated model approach is used, but has some severe drawbacks:

* We must include this functionality with the core, as part of content bindings, so it won't be tree-shakeable, increasing our minimal bundle size. This isn't great since this functionality is not typically needed when creating design system components at all. It's more of an application-oriented feature. It might also slow down the most common content binding scenarios.
* This approach does handle dynamically selecting templates via polymophism but doesn't handle things like switching between "edit" and "default" since there's no way to provide that data to the rendering engine.
* It doesn't solve the simple scenario of wanting to apply a template to part of a model without needing `view` metadata.

## Prototype

I hacked together an implementation of this a while back for my own personal use. It's not exactly like what I describe above but it is very similar. That code, based on fast-element v1, can be found in this gist:

https://gist.github.com/EisenbergEffect/281efd9ae96ad1439f2eb95ee745fd47

For the production implementation, I would start with this and refine the code. The most likely improvement would to to introduce an explicit `TemplateLocator` service that would be used to find templates for arbitrary objects. This would support the `view` decorators but also be pluggable so that developers can plug in their own logic.

**Comment by bheston** [comment]
I've come up against similar issues in both the Color Explorer and Figma plugin. The examples I'm thinking of were both 'switch' type selection for different templates.

Regarding the `@view` technique above, what if `Address` isn't my class, or if it exists in a separate data model structure where augmenting with rendering information is not possible or doesn't feel right? Is there an alternative that would put that information into the template, like:
```ts
const addressTemplate = html<Address>``;
const editAddressTemplate = html<Address>("edit")``;
```
Or maybe even a way to have a single template support rendering modes, effectively:
```ts
const addressTemplate = html<Address>`
  ${x => x.city}
`.mode("edit")`
  <input type="text" :value=${bind(x => x.city, twoWay)}>
`;
```
Then I still have a single template to render an address, but somehow I can control the mode, probably through another binding on the container (whatever is holding the `Person` in this case).

I suppose `Address` already has to have `@observable` decorators, so maybe this isn't a requirement. Off-topic, but is there a way to decorate a class that wasn't built specifically for use in a FAST component? It seems like this would come up anywhere there was an external data source.

---

I've also found an issue using `when` to switch out templates, which if I recall correctly was that if a conditional template rendered, then is _not_ rendered, and then is rendered again, it wasn't updating to the new bindings. It's possible this was something strange about the structure of the model class or observable setup. Looking at that code now, I believe it's in `design-token-field` which renders different UI based on data type (color, number, string, etc.) and I believe the solution is the `ref` in the container `design-token-add` and explicitly setting `value` to `undefined` to force the rebind. I mention this in case it helps when thinking about the context of switching between different templates.

**Comment by EisenbergEffect** [comment]
With the above `render` directive, I would expose some sort of `TemplateLocator` API so that if the class originated in a library that wasn't your own, you could call APIs directly to associate templates with the types. The `view` decorator would likely just call this same API internally.

The above is the way that all of our decorators work. They just call an imperative API internally. So, you can always call them against classes/objects that you get from other sources you don't have control over.

In v2, I've already added a `makeObservable` utility that uses these APIs to convert a plain object and all its properties into an observable object. But this is something that has always been possible.

I don't want to bake this into the base template because then we can't tree-shake it. So, I think a custom directive that leverages a `TemplateLocator` API is a better choice.

**Comment by EisenbergEffect** [comment]
As an example of the locator API, it might be used directly something like this:

```ts
TemplateLocator.register(Address, addressTemplate);
TemplateLocator.register(Address, addressEditTemplate, "edit");
```

And all the `view` decorator would so is this:

```ts
function view(template, type?) {
  return function(target) {
    TemplateLocator.register(target, template, type);
  }
}
```

**Comment by robinchesterman** [comment]
FWIW, this is the code example that made me say "this is what I want":

```
 ${render(x => x.address, editAddressTemplate)}
 ```

**Comment by EisenbergEffect** [comment]
Ok, I've started working on this. The gist above should serve for folks on v1 today. The official version will be part of v2 and hopefully I'll have a PR next week. Most of the work is done in my branch but I need to add tests.

**Comment by EisenbergEffect** [comment]
PR is ready for review. The above API is implemented along with a few additional capabilities.
