### ISSUE TITLE
fix: Submenus in small screens get cut off

### ISSUE THREAD

**Issue by caseyfaber** [microsoft/fast#6125]
# 🐛 Bug Report

If menu has submenus, they aren't usable on small screen sizes as the submenu items get cut off.

## 💻 Repro or Code Sample

Sandbox: https://codesandbox.io/s/fast-submenu-issue-forked-tmommy?file=/index.html

1) Resize display area to 400px or less
2) Hover over Menu item 3

## 🤔 Expected Behavior

Perhaps the anchored region could position differently, like to the bottom or top, if there is no space to the right or left.

## 😯 Current Behavior

The submenu items are cut off.

## 🔦 Context

We have a context menu made with menu, with a submenu inside a menu item, and during accessibility testing a bug was filed where submenus are cut off when the window is 320px, which makes it not pass accessibility requirements.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Edge, Chrome, Firefox
* Version: fast-foundation 2.46.8

**Comment by Yashi1201** [comment]
**GitHub Tags**:#LinkedBug;#Linked:Bug39148928;


Primary Bug Link : https://microsoft.visualstudio.com/OSGS/_workitems/edit/39148928

**Comment by scomea** [comment]
Fix in progress.  Should have something up in the next few days.

**Comment by chrisdholt** [comment]
I believe this has been closed both by the issues above and the migration to floating ui.
