### ISSUE TITLE
rfc: DesignToken API changes for fast-foundation@3.0.0 

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#6134]
For fast-foundation@3.0.0 we're looking at making some changes to the DesignToken API. The changes are intended to address a couple issues identified with the current implementation:

1. The existing implementation allows setting values for native HTML elements. Native HTML elements don't have lifecycle hooks to notify connection and disconnection, which have caused a few known issues and complicates the implementation. They also don't exist in the implementation of SSR for web-components that fast has published, making usage in SSR environments more limited than on the client. This can lead to visual differences between client and SSR output, which is very undesirable in most SSR scenarios.
2. The sole argument to DesignToken function values (`DerivedDesignTokenValue`) is the HTML element for which the function is evaluating. This needs to change to address the above. Additionally, it isn't super clear *why* that argument is an HTMLElement. It is implied that this is the element for which all dependent tokens should retrieve their values, *except* for in circular dependency scenarios, where a value might depend on the token that is being assigned the value (setting fillColor to a function that requires fillColor).
3. Supplying an HTML element to function values *also* prevents an isomorphic implementation of the core design token resolution and notification implementation, which prevents usage in other JavaScript ecosystems, notably in design tool plugins.

For these reasons, I'm proposing the following changes to `DesignToken`:

## Token values can only be set for FAST element instances:
The `getValueFor`, `setValueFor`, and `deleteValueFor` APIs will only accept `FASTElement` instances.

```ts
const someToken = DesignToken.create<number>("foo");
someToken.setValueFor(someFASTElementInstance);
```

It is likely that there are existing scenarios that *require* setting token values for native elements. I believe these scenarios can be addressed through the patterns described by https://github.com/microsoft/fast/issues/5286

## DerivedDesignToken values receive a resolver:

Previously, function values for tokens had the folling function signature:
```ts
type DerivedDesignTokenValue<T> = (target: HTMLElement) => T;
```

Instead, function values will be provided a resolver function that knows how to resolve values of any `DesignToken` instance. It will be a function that accepts a single DesignToken instance and returns the resolved value for that token. Functionally, this will be almost identical to the existing `token.getValueFor(target)` that is implemented by many values today. The sole difference is that the resolver will be able to identify and guard against circular token references (setting a token to a function that depends on the token being set). This change should make the feature easier to understand and use and paves the way for an isomorphic implementation.

```ts
type DesignTokenResolver<T> = (token: DesignToken<T>) => T;
type DerivedDesignTokenValue<T> = (resolve: DesignTokenResolver<any>) => T;
myToken.setValueFor(someFASTElement, (resolve: DesignTokenResolver) => {
  const otherTokenValue = resolve(someOtherToken);
  
  return otherTokenValue * 2;
});
```

## Isomorphic Implementation
The `DesignToken` API will continue to be DOM dependent to facilitate web platform development, but the core infrastructure will be abstracted away form DOM specific APIs. This core abstraction will be managed by `DesignToken` and mapped to FASTElement trees. I'd also like to expose the core infrastructure though, so that implementations for arbitrary tree structures can be created, notably for design tool plugins.

**Comment by bheston** [comment]
This looks like a great set of updates overall. A few thoughts about each point:

1. As you and I have discussed a few times, and documented in #5286 and #5848, I hope we can solve the nested color token scenario efficiently without having to redefine custom color recipes as we did for scenarios like the button inside the tree view item. This has come up in support scenarios and would be good to resolve for good.
2. The resolver should address one of the issues I came across in the adaptive density work in #5511 and [this comment](https://github.com/microsoft/fast/pull/5511/files#r782326354) on the token that builds a cumulative value based on another token value from the parent. Might be a good example if you need a test scenario.
3. Also good based on the changes I had to make to get the Figma plugin to work. I wonder if this portion of the work should be extracted out, potentially into the new adaptive-ui package or maybe its own. With the increase in design token tech and tools across the industry, it would be great if we could publish some infrastructure others could use. For instance, this might tie into some work that converts the standard token format into the model we build here.
