### ISSUE TITLE
fix: toggling a checkbox inside of an accordion item causes accordion item to collapse

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#6144]
# 🐛 Bug Report

## 💻 Repro or Code Sample

https://jsfiddle.net/teu5bnof/

## 🤔 Expected Behavior

Toggling the checkbox shouldn't cause the accordion item to close.

## 🙃 Current Behavior

Toggling a checkbox causes the accordion item to close.

## 💁 Possible Solution

I haven't looked at the code, but it appears as if the `change` event emitted by the checkboxes may be related. A workaround is to call `event.stopPropagation()` on the `change` event emitted by the checkbox, as demonstrated here:

https://jsfiddle.net/teu5bnof/2/

**Comment by scomea** [comment]
I believe the fix is for accordion to make sure that the event originated on a child accordion item:
    `private activeItemChange = (event: Event): void => {
        if (event.target === null || this.accordionItems.indexOf(event.target as HTMLElement) === -1){
            return;
        }`

fix coming soon
