### ISSUE TITLE
docs: fix data grid custom columns sample in component explorer

### ISSUE THREAD

**Issue by izaxon** [microsoft/fast#6180]
# 🙋 Documentation Request

The custom columns sample of the data grid doesn't seem to work. Cell content go missing when switching between custom columns.
![image](https://user-images.githubusercontent.com/805898/177087712-bbbbf9ec-5ac5-48dc-b3e4-93f3834cc4de.png)

It may be that the problem is in the data grid component.

## How to repeat:
1.  Go to https://explore.fast.design/components/fast-data-grid
2. Select Custom components in the dropdown:
![image](https://user-images.githubusercontent.com/805898/177087938-e6b34b5f-c399-4b3a-80df-20a1def28746.png)
3. Click the Three columns button:
![image](https://user-images.githubusercontent.com/805898/177087979-2abef08f-3558-4762-b29f-78c883419d85.png)
4. The first two columns lack values in their cells.

**Comment by EisenbergEffect** [comment]
Thanks for reporting this @izaxon !
@scomea Any idea whether this is an issue with the grid itself or something in the explorer?

**Comment by YonatanKra** [comment]
@EisenbergEffect 
This is an issue with the grid itself.
Here is a cleaner example: https://codepen.io/yonatankra/pen/vYredxP?editors=1111
It also happens locally for me.

**Comment by EisenbergEffect** [comment]
Thanks for the update @YonatanKra !

**Comment by scomea** [comment]
There looks to be an issue with swapping in a new array instance for columnDefinitions vs mutating the existing array.
This variation of the example works as expected - https://codepen.io/scomea/pen/poKWYJp?editors=1111
Ideally the grid should tolerate a swap as well, so I'll look into it.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955 and we will not be publishing the explore site going forward.
