### ISSUE TITLE
fix: Disclosures overlap adjacent elements and incorrectly cache their expanded height

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#6190]
# 🐛 Bug Report

Disclosures overlap elements that appear below them in the normal document flow.

I was creating a repro for one of our consumers and discovered a second, somewhat related bug, where it appears the expanded height is initially cached. That means subsequent changes to child elements will cause even more overlap.

Examples in the repro.

## 💻 Repro or Code Sample

https://jsfiddle.net/qr6241db/1/

## 🤔 Expected Behavior

- The disclosure should function as expected in the normal document flow and not overlap adjacent elements.
- The disclosure should recalculate the expanded height when content changes.

## 😯 Current Behavior

- The disclosure overlaps elements, even when not expanded.
- The disclosure maintains the same expanded height, even when its content changes.

## 💁 Possible Solution

In the linked repro, the internal `<details>` element receives a fixed height of 18.5px when collapsed. This causes the first issue. The height should probably be set to `auto` when the element isn't animating to ensure its collapsed state and its expanded state don't interfere with adjacent elements.

## 🔦 Context

This was reported to us by a consumer.

**Comment by chrisdholt** [comment]
Closing this given the current state of the FAST components. @bheston and @KingOfTac tagging you as an FYI to watch out for this as you look into kicking off a new effort related to https://github.com/microsoft/fast/issues/6603.
