### ISSUE TITLE
Couldn’t found the supported attributes and functionalities inside the Fluent UI documentation.

### ISSUE THREAD

**Issue by apanwar22i** [microsoft/fast#6204]
Hi,
If I want to implement any FluentUI component, there is no description of the supported attributes of the component.
For example, If i'm going to implement fluent-combobox, i can see the implementation tags inside the combobox documentation but not the supported attributes and the functionalities
https://docs.microsoft.com/en-us/fluent-ui/web-components/components/combobox

🙋 Please can you provide me any detailed documentation of the Fluent UI.

Thanks

**Comment by KingOfTac** [comment]
@apanwar22i Fluent UI Web Components uses the component classes exported by fast-foundation which have API documentation that can be found on the FAST website. https://www.fast.design/docs/components/anchor#api

Fluent UI also has a storybook. https://fluent-components.azurewebsites.net/

**Comment by apanwar22i** [comment]
Thanks, @KingOfTac @EisenbergEffect for directing towards Fast documentation, it did help in resolving the issue. Glad that you are keeping this open and adding information to the Fluent site as well.

**Comment by apanwar22i** [comment]
@KingOfTac @EisenbergEffect Just want to give you a heads-up.
If we are using components like this:
`<fluent-checkbox checked>Label string</fluent-checkbox>`
then FastUI docs are good.
But when we use the components inside react like this:
`<FluentCheckbox defaultChecked={true}>Label string</FluentCheckbox>`
Then we will face problem to understand attribute names.
Attribute names are different in both ways.

**Comment by EisenbergEffect** [comment]
Ah, that makes sense! We've recently done some work to improve the Fluent UI documentation for Web Components, where we've added explicit Blazor code samples. Our next step is to publish all the API definitions there, for general use. So, that should help in figuring this out going forward. After that, we can look at adding dedicated React examples along side the Blazor examples. It will take quite a bit of time to get that all done. Thank you for your patience.

**Comment by janechu** [comment]
This appears to be resolved see https://web-components.fluentui.dev/
