### ISSUE TITLE
Fluent Card is not working correctly and throwing "Cannot read properties of undefined".

### ISSUE THREAD

**Issue by apanwar22i** [microsoft/fast#6205]
Hi, im getting a runtime error of the Fluent Card component.
<img width="503" alt="card" src="https://user-images.githubusercontent.com/109206668/178691494-db90f983-6f86-4150-bad2-e04ba1795898.png">

my implementation is like this:
![card code](https://user-images.githubusercontent.com/109206668/178691166-e1f4f40f-6b47-42ad-86ff-1d9b71db047e.png)

Tags:
![card tags](https://user-images.githubusercontent.com/109206668/178691447-ac672374-af54-4009-bff2-cab1a9ce8d79.png)

Is im missing something?

Thanks

**Comment by KingOfTac** [comment]
@apanwar22i It looks like you may be using FAST within a React application. There are integration docs available for React that might alleviate the issues you're having. https://www.fast.design/docs/integrations/react

**Comment by KingOfTac** [comment]
Stackblitx example. https://stackblitz.com/edit/react-ts-wr3hj1?file=App.tsx

**Comment by apanwar22i** [comment]
> Stackblitx example. https://stackblitz.com/edit/react-ts-wr3hj1?file=App.tsx

Thank you, Its working now.
