### ISSUE TITLE
Design system tutorial TS build error

### ISSUE THREAD

**Issue by benwaar** [microsoft/fast#6208]
Trying to build the design system tutorial results in a build error:

ERROR in ./src/main.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. False expression: Non-string value passed to ts.resolveTypeReferenceDirective, likely by a wrapping package working with an outdated resolveTypeReferenceDirectives signature. This is probably not a problem in TS itself.

Yarn in the root of the project is fine and the todo app runs also.

**Comment by chrisdholt** [comment]
Thanks @benwaar, taking a look

**Comment by janechu** [comment]
Due to project re-alignment goals, see #6955, we will not have a focus going forward on design systems so this tutorial will be removed.
