### ISSUE TITLE
fix: auto sized children break horizontal scroll

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#6211]
# 🐛 Bug Report

When children inside of `horizontal-scroll` have their widths set to `auto` the flippers will not appear.

## 💻 Repro or Code Sample

```
<fluent-horizontal-scroll>
     <fluent-card style="width:auto"></fluent-card>
     <fluent-card style="width:auto"></fluent-card>
     <fluent-card style="width:auto"></fluent-card>
     ...Etc...
</fluent-horizontal-scroll>  
```

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by janechu** [comment]
I believe this is no longer an issue, as `@microsoft/fast-foundation` is being deprecated, refer to #6955. If this is still an issue for Fluent UI web components, please file an issue there.
