### ISSUE TITLE
fix: [when the attribute of the array element instruction changes， The repeat DOM dose not updated]

### ISSUE THREAD

**Issue by liulina0228** [microsoft/fast#6212]
# 🐛 Bug Report

 when the attribute of the array element  instruction changes， The repeat DOM dose  not updated

## 💻 Repro or Code Sample
// dom
${repeat(
    x => x.uploadQueue,
    html`
    <li class="uploader-file">
      <span class="uploader-file-name">${ x=> x.name}</span>
      ${when(x => x.showFilePauseBtn, html`
        <span class="uploader-file-pause" @click="${(x, c) => c.parent.filePauseHandler(x, c.index)}"></span>`)}
</li>`, {positioning: true})}

 // ts
  filePauseHandler (file, index) {
    file.pause();
    file.showFilePauseBtn = false;
    file.showFileResumeBtn = true;
   // uploadQueue has changed
    console.log(this.uploadQueue);
  }
## 🤔 Expected Behavior

after clicked the span of ‘.uploader-file-cancel' dose  not show

## 😯 Current Behavior

nothing happened

## 🌍 Your Environment

fast-element latest

* Browser [Google Chrome]
* Version [ 103.0.5060.114]

**Comment by liulina0228** [comment]
The uploadQueue is an observable， the showFilePauseBtn is a property of uploadQueue Array elements

**Comment by EisenbergEffect** [comment]
Is the `showFilePauseBtn` itself an `@observable` property? That's the key requirement to get UI updates. Each property has to be observable.

**Comment by chrisdholt** [comment]
> Is the `showFilePauseBtn` itself an `@observable` property? That's the key requirement to get UI updates. Each property has to be observable.

@liulina0228 just wanted to follow up and see if making `showFilePauseBtn` observable solved the issue. I'm going to close this out as stale and given the above note from Rob as that item being observable is key to getting updates.
