### ISSUE TITLE
fix: tri-state visible boolean value in fast/tooltip.ts

### ISSUE THREAD

**Issue by aidendk** [microsoft/fast#6247]
# 🐛 Bug Report
The FAST tooltip variable `visible` is declared as a `boolean` here, https://github.com/microsoft/fast/blob/775d51602cba544347ec1e57fdb4fea248d1b1b5/packages/web-components/fast-foundation/src/tooltip/tooltip.ts#L33

but has the possibility of being `undefined` in this function.
https://github.com/microsoft/fast/blob/775d51602cba544347ec1e57fdb4fea248d1b1b5/packages/web-components/fast-foundation/src/tooltip/tooltip.ts#L544-L557

Because `visible` is a boolean attribute, it should not have behavior associated with being set to `undefined`. Additionally, because the attribute mode of the attribute is `boolean`, it is impossible to set the value back to `undefined` after it has been changed via HTML.

## 💻 Repro or Code Sample
Shown above

## 🤔 Expected Behavior
`visible` should only have the values `true` or `false`. If three states are needed, the type should be something other than a boolean.

## 😯 Current Behavior
The behavior is associated with the boolean being `undefined`, which isn't a valid value. The `visible` boolean has 3 states, which doesn't correspond with its datatype.

## 💁 Possible Solution
`visible` should only be able to have the values `true` or `false`, so getting rid of the possibility of `visible` being `undefined` could be a possible fix. The alternative would be to use an enumeration instead of a boolean.

## 🔦 Context
Because the attribute mode of the attribute is `boolean`, it is impossible to set the value back to `undefined` after it has been changed via HTML.

## 🌍 Your Environment
All

**Comment by chrisdholt** [comment]
Adding @scomea who can hopefully provide some insight into when we might ever have a non-boolean value.

**Comment by scomea** [comment]
The intent is that the tooltip's visibility can either be explicitly controlled with true/false or if undefined the tooltip manages that itself based on the hover/focus state of the anchor.  Perhaps an enum "auto/visible/hidden" attribute ("visibility-mode"?) with a boolean read-only prop that tracks the current state of the tooltip?

**Comment by chrisdholt** [comment]
I believe this can be closed with the changes recently made to tooltip with #6468.
