### ISSUE TITLE
docs: Algolia search box on fast.design docs returns no results for most keywords

### ISSUE THREAD

**Issue by jweill-aws** [microsoft/fast#6250]
# 🐛 Bug Report

On the [fast.design documentation web site](https://www.fast.design/docs/introduction/), the search box in the upper-right corner does not return results for most keywords. For example, the keywords `design` and `checkbox` yield no results, but page names such as `Archive` return a link to the page.

## 💻 Repro or Code Sample

Visit https://www.fast.design/docs/introduction/, click the search box, and type the word `design`:

![image](https://user-images.githubusercontent.com/93281816/182199416-9ff146da-63ce-4921-a110-178d5be67ae1.png)

## 🤔 Expected Behavior

I expect to see pages with the word `design` in their body.

## 😯 Current Behavior

I see no results.

## 💁 Possible Solution

I asked a friend who works at Algolia; they replied that this seems to be a configuration issue and not a problem with Algolia. They recommended that whoever maintains the search box needs to troubleshoot their config and recrawl the index.

## 🔦 Context

Trying to find info about specific items in FAST.

## 🌍 Your Environment

* OS & Device: macOS 12.4
* Browser: Firefox
* Version: 91.11.0esr

**Comment by EisenbergEffect** [comment]
Thanks for reporting this. We're looking into it now.

**Comment by huynhicode** [comment]
This has been resolved by recrawling the site; search now returns results. 🎉 @EisenbergEffect @jweill-aws

**Comment by EisenbergEffect** [comment]
Thanks @huynhicode ! Closing as done.
