### ISSUE TITLE
fix: next flipper disabled for hidden horizontal-scroll

### ISSUE THREAD

**Issue by robarbms** [microsoft/fast#6261]
# 🐛 Bug Report

If a horizontal-scroll component is rendered hidden or inside of a hidden element, it will calculate all of it's children widths as 0px. This causes the next flipper to be disabled. It also causes all of the scroll stops to be 0.

## 💻 Repro or Code Sample

Render horizontal-scroll in a hidden container. Show the container.

## 🤔 Expected Behavior

When shown, the horizontal-scroll should have a next flipper.

## 😯 Current Behavior

When shown, the horizontal-scroll does not have a flipper.

## 💁 Possible Solution

We need to verify that the stops are not 0 when deciding to show the next flipper.
When using next or previous flipper, we should make sure that stops are not 0 and rerun HorizontalScroll.setStops() if they are.

## 🔦 Context

This is causing horizontal-scroll components in tabs 2-n to not have a next flipper in coreux repo.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
