### ISSUE TITLE
fix: Typing text in Combobox does not update value as you type

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#6267]
# 🐛 Bug Report

I brought up this behavior in this [Discord post](https://discord.com/channels/449251231706251264/482296787021856768/1005149970665574501) in order to determine if there was an explicit reason why the `Combobox` didn't update its value as you typed the way the native `input` and the FAST `TextField` do. @radium-v noted some [ARIA guidance](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html#:~:text=Navigating%20the%20list,clicking%20the%20input), but I believe we agreed that that was directed at what happens as a user navigates the dropdown.

As such, I don't believe there is strong reasoning behind not having the Combobox update its value as the user types. Particularly from the point of view that a Combobox is really just supposed to be a fancy text field with hints.

## 🤔 Expected Behavior

- As the user types, the `value` gets updated.
- As the user types, only `input` events are emitted, _not_ `change` events
- Upon focus out or pressing \<Enter\>, if a user typed in text that makes it different from the original text prior to typing, a `change` event is emitted. **_Note_**: This is the same behavior as the `TextField`.

## 😯 Current Behavior

- As the user types, the `value` is not updated.

## 💁 Possible Solution

`Combobox` simply needs to handle the cases outlined above in its implementation.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by au5ton** [comment]
Is this something that can be looked at? As it stands now, this makes the combobox needlessly challenging for autocompleting with remote data. This is because I can't access what the user has typed after an `input` event without accessing `.control.value` directly, which is very impractical in some environments (like Blazor).

Eventually, what the user has typed does get saved, but not until the field loses focus or the user selects an option.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
