### ISSUE TITLE
feat: add SSR DesignToken strategy

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#6272]
# 🙋 Feature Request
Implement a DesignToken resolution strategy that correctly resolves DesignTokenNode hierarchies in SSR environments.

## 😯 Current Behavior
The default resolution strategy implemented in DesignToken uses manual DOM walking to resolve DesignTokenNode hierarchies. This is more performant than Event emission, however it leverages APIs that are not implemented in SSR and the custom element hierarchies it relies on do not exist in SSR.

## 💁 Possible Solution
An Event based resolution strategy should be developed. SSR supports event emission and listening, so events can be used to resolve DesignTokenNode hierarchies.

**Comment by EisenbergEffect** [comment]
@nicholasrice Is this one complete? Would you link the related PRs? Thanks!
