### ISSUE TITLE
feat: re-implement #6253

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#6296]
# 🙋 Feature Request
We needed to revert #6253 to satisfy publishing requirements (https://github.com/microsoft/fast/pull/6295). This issue tracks the re-implementation of that PR. Re-implementation should happen after FAST packages have been brought out of alpha and beta versions.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-web-utilities` is being deprecated, refer to #6955 thus this reversion is no longer needed for launch of v2 `@microsoft/fast-element`.
