### ISSUE TITLE
fix: avatar element missing alt and src attributes

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#6309]
# 🐛 Bug Report

The spec for the FASTAvatar component describes `alt` and `src` attributes, which are currently not implemented.

## 💻 Repro or Code Sample

https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/avatar/avatar.spec.md

```html
<fast-avatar alt="Annie's profile image" link="#">
    <img slot="media" src="https://via.placeholder.com/32x32" />
</fast-avatar>

<fast-avatar src="https://via.placeholder.com/32x32" link="#"></fast-avatar>
```

## 🤔 Expected Behavior

* The `src` attribute should add an internal image.
* The `alt` attribute should be reflected onto the internal image.

## 😯 Current Behavior

The `alt` and `src` attributes are not implemented.

## 💁 Possible Solution

The `alt` and `src` attributes should be removed from the spec, or implemented to handle the addition of an automatic media image.

## 🔦 Context

This bug was discovered while converting the Karma tests to Playwright.

**Comment by chrisdholt** [comment]
I think this scenario likely is dependent on API changes to Foundation. IMO if an image is slotted we likely shouldn't have attributes for either alt or src. Will take a look.

**Comment by radium-v** [comment]
I initially got it wrong thinking `alt` goes on the internal anchor - I updated the issue text to fix that. The `alt` attribute would only make sense on an `<img>`, which would have to be present with a `src` to be valid.
