### ISSUE TITLE
fix: unable to set initial boolean attributes on picker

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#6311]
# 🐛 Bug Report

The `filter-selected` and `filter-query` boolean attributes on the `<fast-picker>` are `true` by default and the picker cannot be initialized in a state where they are not present.

## 💻 Repro or Code Sample

In this example, the picker is created and by default has the `filter-selected` and `filter-query` attributes present:
```js
const picker = document.createElement("fast-picker");
document.body.append(picker);
```

Inserting a `<fast-picker>` element in HTML has the same effect:
```html
<!-- Inserted markup -->
<fast-picker></fast-picker>

<!-- after DOM load -->
<fast-picker current-value="" selection="" filter-selected="" filter-query="" no-suggestions-text="No suggestions available" suggestions-available-text="Suggestions available" loading-text="Loading suggestions" menu-placement="bottom-fill"><fast-picker-list slot="list-region" role="list" class="picker-list"><!---->
    <input slot="input-region" role="combobox" type="text" autocapitalize="off" autocomplete="off" haspopup="list">
</fast-picker-list><fast-picker-menu role="list" slot="menu-region" id="listbox-0"><!----></fast-picker-menu></fast-picker>
```

In this example, the picker is created and does not have the attributes present when appended to the document body:
```js
const picker = document.createElement("fast-picker");
picker.filterSelected = false;
picker.filterQuery = false;
document.body.append(picker);
```

## 🤔 Expected Behavior

The attributes `filter-selected` and `filter-query` should not be present when not explicitly set. 

## 😯 Current Behavior

Since both `filterSelected` and `filterQuery` are both `true` at construction time, their boolean attributes are mapped to be present. There's no way to declare a `<fast-picker>` element without these attributes - property mutation after assignment and before connection is required.

## 💁 Possible Solution

Here are some possible solutions:
* Use the `booleanConverter` converter to allow string values of `true` and `false`. This would break the defined API.
* Set `filterSelected` and `filterQuery` to `false` by default. This would break existing implementations which don't already set these attributes in an explicit manner.

## 🔦 Context

This bug was found while converting the Karma tests to Playwright.

**Comment by EisenbergEffect** [comment]
@radium-v I believe we made a general decision that all boolean attributes should be setup to be `false` by default. @chrisdholt can confirm/deny.

**Comment by chrisdholt** [comment]
@scomea can you take a look at reworking picker to support defaulting to `false`.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I see this was mentioned in a PR, we will be addressing open PRs and merging what we can before we snap an archive branch to preserve the latest state of Foundation, however to bring us up to date I am closing out issues.
