### ISSUE TITLE
fix: render-collapsed-nodes attribute present but not implemented in tree view 

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#6312]
# 🐛 Bug Report

The `render-collapsed-nodes` attribute has no implementation details on the `<fast-tree-view>` element. Its mapped property, `renderCollapsedNodes`, has no initial value and is type `boolean`.

## 💻 Repro or Code Sample

```html
<fast-tree-view render-collapsed-nodes="false"></fast-tree-view>

<fast-tree-view render-collapsed-nodes="true"></fast-tree-view>

<fast-tree-view render-collapsed-nodes></fast-tree-view>

<fast-tree-view></fast-tree-view>
```

## 🤔 Expected Behavior

I would expect this attribute to control whether or not collapsed nodes are made present in the DOM.

## 😯 Current Behavior

This functionality, while indicated by the existence of the property and attribute, is not implemented.

## 💁 Possible Solution

Some possible solutions:
* Remove the attribute and property. This would change the API, but since it's not implemented, would have limited effect.
* Implement the functionality implied by the attribute.

## 🔦 Context

This bug was discovered while converting the Karma tests to Playwright.

**Comment by chrisdholt** [comment]
Note that the functionality has been removed I believe so the attribute should likely go as well. I'll follow up and check on this.
