### ISSUE TITLE
"onChange()" event is not firing on Fluent Checkbox

### ISSUE THREAD

**Issue by apanwar22i** [microsoft/fast#6313]
Hi, We are applying "onChange()" event on Fluent Checkbox but it is not firing. same thing is happening with "**onKeyup()**" event, it is not working as well. I'm only getting response on "onClick()" event.

Below is the code snippet and here is the Stack Blitz: 
https://stackblitz.com/edit/react-ts-bzusgl?file=App.tsx

```
import * as React from 'react';
import './style.css';

import {
  provideFluentDesignSystem,
  fluentButton,
  fluentDivider,
  fluentCheckbox,
  fluentCard,
} from '@fluentui/web-components';
import { provideReactWrapper, ReactWrapper } from '@microsoft/fast-react-wrapper';
import { Checkbox } from '@microsoft/fast-foundation'; // get the type from foundation


const { wrap } = provideReactWrapper(React, provideFluentDesignSystem());

const FluentDivider = wrap(fluentDivider());
const FluentCheckbox = wrap(fluentCheckbox()) as ReactWrapper<Checkbox, {}>;
const FluentCard = wrap(fluentCard());

export default function App() {
  const onCheckboxUpdate = (e: any) => {
    console.log(e);
  };

  return (
    <FluentCard style={{ padding: '1rem' }}>
      <h2>Fluent UI: React </h2>
      <FluentDivider />
      <FluentCheckbox 
      onChange={onCheckboxUpdate}>
        checkbox</FluentCheckbox>
    </FluentCard>
  );
}

```

Thank you.

**Comment by KingOfTac** [comment]
You may need to configure event mappings for the checkbox.

https://www.fast.design/docs/integrations/react#configuring-custom-events

**Comment by EisenbergEffect** [comment]
@apanwar22i Can you give the event mapping that @KingOfTac mentions a try? This is sometimes required due to React's non-standard approach to handling events.

**Comment by tebinraouf** [comment]
@apanwar22i , for the checkbox onChange to work, you would need event mappings as @KingOfTac  suggested. Here is a Stackblitz that shows how to: https://stackblitz.com/edit/react-dgvloj?file=src/App.js

**Comment by apanwar22i** [comment]
Thanks, @KingOfTac @EisenbergEffect @tebinraouf the above solution work. 👍
