### ISSUE TITLE
fix: Cannot compose `FASTDataGrid` with `dataGridTemplate` and `FASTDataGridRow`

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#6338]
# 🐛 Bug Report
When composing `FASTDataGrid` with `dataGridTemplate`, a runtime error occurs when providing `FASTDataGridRow` to template options. This error occurs because `dataGridTemplate` immediately invokes [`tagFor`](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid.template.ts#L34) on invocation, and at composition time, `FASTDataGridRow` is not expected to be defined.

I think we need to implement a pattern change here, because calling `tagFor` in the body of any of the fast-foundation template functions will fail if the provided argument has not been defined yet, which is a common scenario when constructing component definitions. This issue may affect components other than data-grid.

## 💻 Repro or Code Sample
https://stackblitz.com/edit/typescript-r3xexl?file=index.ts

**Comment by EisenbergEffect** [comment]
I believe this problem can be solved by passing the definition object that you get from `compose` into the grid template function's options. Here's a link that shows some code:

https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

Let me know if that soles the problem.

**Comment by nicholasrice** [comment]
Yep, that should work - thanks @EisenbergEffect!
