### ISSUE TITLE
fix: fast foundation templates should be generic

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#6344]
# 🐛 Bug Report

## 💻 Repro or Code Sample

If extend a class and then use the foundation template there is a type mismatch. 

View error on `template`
https://stackblitz.com/edit/typescript-p5udp6?file=repro.ts

```ts
import { attr } from '@microsoft/fast-element';
import { FASTHorizontalScroll, horizontalScrollTemplate } from '@microsoft/fast-foundation';

class MyClass extends FASTHorizontalScroll {
  @attr({ attribute: "test-attribute" })
    public testAttribute: string;
}

const template: ElementViewTemplate<MyClass> = horizontalScrollTemplate(
  {
      nextFlipper: html`
          <div>
          ${x => x.testAttribute}
          </div>
      `,
      previousFlipper: html`
          <div>
          ${x => x.testAttribute}
          </div>
      `,
  }
)
```

## 🤔 Expected Behavior

I should be able to assign a foundation template to an extended class.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by EisenbergEffect** [comment]
Dropping a note here as a reminder, I think we need to change the types to something like this:

```ts
export function horizontalScrollTemplate<T extends FASTHorizontalScroll = FASTHorizontalScroll>(
    options: HorizontalScrollOptions = {}
): ElementViewTemplate<T>
```

**Comment by chrisdholt** [comment]
> Dropping a note here as a reminder. I think we need to change the types to something like this:
> 
> ```ts
> export function horizontalScrollTemplate<T extends FASTHorizontalScroll = FASTHorizontalScroll>(
>     options: HorizontalScrollOptions = {}
> ): ElementViewTemplate<T>
> ```

I can take a look at picking this up @eisenbergeffect.

**Comment by EisenbergEffect** [comment]
@chrisdholt We would need to make this sort of change across every template factory function in foundation I believe. Probably also want to verify that this fixes @eljefe223's issue. I think it should but haven't checked myself yet.

**Comment by chrisdholt** [comment]
> @chrisdholt We would need to make this sort of change across every template factory function in foundation I believe. Probably also want to verify that this fixes @eljefe223's issue. I think it should but haven't checked myself yet.

Yep - Going one by one now :). I have a sandbox I can test as well.

**Comment by EisenbergEffect** [comment]
Ok, just did a confirmation that this does fix the compile error.
