### ISSUE TITLE
fix:  `@attr` in a derived class affects the getter methods in another derived class.

### ISSUE THREAD

**Issue by xuwaters** [microsoft/fast#6368]
# 🐛 Bug Report

The `videoId` getter method in `ComponentB` is proxied to access the non-existing attribute `videoId` defined in `ComponentA`.

## 💻 Repro or Code Sample

Thanks Alberto Rivera for creating this repro link:
https://stackblitz.com/edit/fast-design-sfdxwf?file=src%2FChildrenComponent.ts,src%2FParentComponent.ts,index.html

A similar sample:

```typescript
export abstract class BaseElement extends FASTElement {
  @attr anotherOne = "";
}

@customElement({
  name: "my-component-a",
  template: html`
  <div>
    Component A: ${x => x.videoId}
  </div>
  `,
})
export class ComponentA extends BaseElement {
  @attr videoId = "id-A";
}

@customElement({
  name: "my-component-b",
  template: html`
  <div>
    Component B: ${x => x.videoId}
  </div>
  `
})
export class ComponentB extends BaseElement {
  private get videoId(): string {
    return "id-B"
  }
}

@customElement({
  name: "my-app",
  template: html`
    <my-component-a></my-component-a>
    <my-component-b></my-component-b>
  `
})
export class App extends FASTElement {
}
```

## 🤔 Expected Behavior

The expected result should be:

<img width="107" alt="image" src="https://user-images.githubusercontent.com/1222863/189430033-781c966b-e11e-4a4d-95eb-81d766b9cfc1.png">

## 😯 Current Behavior

But the current result is:

<img width="124" alt="image" src="https://user-images.githubusercontent.com/1222863/189429930-51ec3835-7f69-4e08-86b7-9c958288624e.png">

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge, Google Chrome
* Version 1.10.1

**Comment by chrisdholt** [comment]
Assigning to @eisenbergeffect who I believe has an idea already of what is going on here.

**Comment by EisenbergEffect** [comment]
I've marked this as pertaining to the FASTElement 2.0 milestone. However, as soon as we get this sorted I'll back port it to 1.x. I've wedged it into our current sprint so hopefully we can tackle this next week. It's top of my list.

**Comment by EisenbergEffect** [comment]
I'm a little behind schedule but am starting this one now.
