### ISSUE TITLE
rfc: FAST Website Updates for VNext

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#6370]
# 💬 RFC
This is a summary of proposed updates to the FAST homepage to coincide with the release of vNext. The RFC is to get feedback and suggestions from the team and members of the community.

## 🔦 Context
With all the new features coming out, there will need to be some docs restructuring as well as some wording changes on the homepage.

## 💻 Planned Changes
- Update the Features section with new FAST features and remove features that are no longer relevant.
- Update the Showcase section to highlight companies and other partners that are using FAST.
- Add a tutorial section to the docs.
- Update the docs organization for a more streamlined user flow. **Still working out the details on this one so stay tuned.**

**Comment by EisenbergEffect** [comment]
Yep. All sounds good. I think we might want to break the docs tasks out into a separate issue. There is going to be a bunch of new content, some old stuff removed, and definitely some re-organization, particularly in light of the new CLI-based design system approach.

It might be easier to start on the docs first, get that into a good position, and then circle back around for this second round of homepage updates. Thoughts?

**Comment by KingOfTac** [comment]
Agreed. I think updates to the homepage will fall into place easier if the new docs are already in place. I can split out the tutorial section into another issue if you'd like.

**Comment by janechu** [comment]
This is currently in progress with the push for v2 `@microsoft/fast-element` and is mostly done, closing the issue for now please re-open if you see gaps after launch!
