### ISSUE TITLE
fix: JavaScript class fields incompatible with Observable decorator

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#6375]
# 🐛 Bug Report
It appears that the output of TypeScript decorators is incompatible with JavaScript class fields. We should document that using JavaScript class fields is not currently supported, and that anyone compiling projects with TypeScript should ensure that the `useDefineForClassFields` is set to `false`. `useDefienForClassFields` is automatically set to `true` for `target: ES2022` so authors will have to override when using that target.

## 💻 Repro or Code Sample
Min repro of generic issue : https://stackblitz.com/edit/js-kvjawt?file=index.js

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by rajsite** [comment]
Related issue https://github.com/microsoft/fast/issues/5017

**Comment by janechu** [comment]
Closing in favor of #5261, if a solution to that issue is not forthcoming, we will add documentation.
