### ISSUE TITLE
docs: add 'Working without decorators' to 'Apps and Experiences\Dependency Injection'

### ISSUE THREAD

**Issue by send2vinnie** [microsoft/fast#6376]
# 🙋 Documentation Request

The FAST element defining tasks can be done without using decorators according to the documentation. So does the FAST built in dependency injection capability. It's suggested to add a 'Working without decorators' section in the corresponding chapter as well as other pure Javascript practices while working with FAST in the no-transpilation world.

**Comment by EisenbergEffect** [comment]
Thanks for creating this for me @send2vinnie. I'm going to try to pick this up in our next spring, which starts next week. In the meantime, do you have the information you need to move forward with your project?

**Comment by send2vinnie** [comment]
Would that be feasible for providing examples (in the docs, the storybooks and the repo) in both TypeScript and JavaScript? That would be helpful for bringing FAST to the pure-JS world.

**Comment by EisenbergEffect** [comment]
@send2vinnie I think that's a reasonable request. Unfortunately, I don't think we have the resources right now to go through all the documentation and make separate JS examples of everything. If you want to create a separate issue for this, we can track if for some time in the future.
