### ISSUE TITLE
fix: repeat directive indexing fails on splice of associated array

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#6379]
# 🐛 Bug Report
After a recent update my virtual list pr stopped working correctly.  The underlying issue turned out to be how the observed array used in the repeat directive was being manipulated which could result in the `c.index` value used in item bindings always reported the array length and not the item's index.  

When the list was updated with new items I had been using `splice` to clear out the old items and swap in the new items while maintaining the same array instance:

`this.visibleItems.splice(0, this.visibleItems.length, ...newVisibleItems);`

When I just swapped in a new array the `c.index` values are correct:

`this.visibleItems = newVisibleItems;`

## 🤔 Expected Behavior

Items generated by the repeat directive should get the correct value for `c.index` in template binding.

## 😯 Current Behavior

All items generated by the repeat directive get the list length as the value for `c.index` when the list has been manipulated by a `splice()`

## 🔦 Context

Repeat directives should pass correct index values to generated items regardless when associated array is modified.

**Comment by EisenbergEffect** [comment]
@prudepixie Can you take a look at this? It looks like it might be a regression related to the recent changes in repeat.

**Comment by prudepixie** [comment]
Hi @scomea , can you adjust this stackblitz for a repro of this bug https://stackblitz.com/edit/typescript-opxvbs?file=index.ts

**Comment by scomea** [comment]
> Hi @scomea , can you adjust this stackblitz for a repro of this bug https://stackblitz.com/edit/typescript-opxvbs?file=index.ts
> 
> Did you update fast-element to 1.10.5 or 2.0.0-beta.6? Thank you

My initial repro is in a local branch that I updated to the latest master.  I've modifed your stackblitz and managed to get an error state that isn't the same behavior I was seeing but may be related - 

https://stackblitz.com/edit/typescript-tf1b4y?file=index.ts

When I click the button twice I get an error the second time:

`Error in /turbo_modules/@microsoft/fast-element@2.0.0-beta.6/dist/esm/templating/repeat.js (19:10)
Cannot read properties of undefined (reading 'bind')`

**Comment by scomea** [comment]
This is the fast branch where I can see the issue - https://github.com/microsoft/fast/tree/users/scomea/add-virtual-list

If you run it and swap comments on lines 1074 and 1075 of "virtual-list.ts" you can see the behavior change - https://github.com/microsoft/fast/blob/9cc401df293409959723cef70df3bd18b590b1f6/packages/web-components/fast-foundation/src/virtual-list/virtual-list.ts#L1074

**Comment by EisenbergEffect** [comment]
@scomea Can you create a separate issue for the rebind problem? I've got a fix for the original index issue that I'm about to post. I'll need to tackle the other issue separately.

**Comment by scomea** [comment]
> @scomea Can you create a separate issue for the rebind problem? I've got a fix for the original index issue that I'm about to post. I'll need to tackle the other issue separately.

https://github.com/microsoft/fast/issues/6431
