### ISSUE TITLE
fix: Missing syntax highlighting for css partials in FAST tagged templates extension

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#6380]
# 🐛 Bug Report
The FAST Tagged Template Literals vscode extension doesn't recognize `css.partial` for syntax highlighting.

## 🤔 Expected Behavior
`css.partial` should be recognized for syntax highlighting

## 😯 Current Behavior
`css.partial` does not have syntax highlighting.

## 💁 Possible Solution
I think this [line](https://github.com/microsoft/fast/blob/c1909e9899d517f9483b24043d49a8b193af3c26/packages/tooling/fast-vscode-syntax-highlighting/syntaxes/fast-tagged-templates.tmLanguage.json#L18) would need to include partials in some way. (not a regex expert)

As a workaround `css.partial/* css */` will enable the syntax highlighting but it gets tedious.

**Comment by janechu** [comment]
Unfortunately the tag template extension has been deprecated, refer to #6955, there may be a replacement available in another project please re-file this issue there if it persists.
