### ISSUE TITLE
Observable not updating when a method is called from a nested component

### ISSUE THREAD

**Issue by PoojaC94** [microsoft/fast#6393]
### Discussed in https://github.com/microsoft/fast/discussions/6392

<div type='discussions-op-text'>

<sup>Originally posted by **PoojaC94** September 22, 2022</sup>
I have a FAST component which has multiple components in it
Component A
`const template = html<item>
${when x=> x.isComponentOpen,
<componentB></componentB>
}`
`<componentC :onClick={(x)=>x.onClick}></componentC>`

`@observable isComponentOpen = false;`
`onClick() {
this.isComponentOpen=true
}`

When componentC calls onClick, the isComponentOpen is set to true but componentB is not appearing. Why does this happen?</div>

**Comment by KingOfTac** [comment]
Resolved in linked discussion
