### ISSUE TITLE
rfc: changes in class bindings

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#6413]
# 💬 RFC

There are three ways to set `class` on an `HTMLElement` and two ways on an `SVGElement`. I think we should make these mechanisms explicit rather than having FAST try to "do the right thing" especially since this attempt can fail with SVG in scenarios where it seems like it should not.

## 🔦 Context

We want to set `class` on an `HTMLElement`. There are **three** ways to do this from JS:

* `element.className = "my-class";` - fastest
* `element.setAttribute("class", "my-class");` - a little slower
* `element.classList.add("my-class");` - a little slower

**Note:** `fast-element` v1 always used `classList.add(...)`.

We want to set `class` on an `SVGElement` also. There are **two** ways to do this from JS:

* `element.setAttribute("class", "my-class");` - fastest
* `element.classList.add("my-class");` - a little slower

**Note:** You cannot set `className` on an `SVGElement`. It is readonly.

## 💻 Examples

Today, if you bind `class` on an element, instead of setting the attribute, it will detect this and try to set `className` for better perf. 

This...

```html
<div class=${x => x.someProperpty}></div>
```

...essentially gets turned into this...

```js
element.className = x.someProperty;
```

However, since this isn't supported on `SVGElement`, this will crash. This auto-mapping of an attribute to a property with a different name will certainly surprise folks when used with an `SVGElement`. There's also no way to have FAST use `setAttribute` for `class`.

## Proposal

I believe we shouldn't do the auto-mapping. If a `class` binding is set, we should just use `setAttribute` like we do with every other attribute. This will work for both `HTMLElement` and `SVGElement`. Anyone can then opt into `className` (for perf) or `classList` (for class change conflict/isolation) with an explicit property binding.

**Comment by nicholasrice** [comment]
That makes sense to me. I'd prefer to have consistent behavior w/ opportunity to optimize for a given scenario than to have fast-element branch it's behavior for this attribute.

**Comment by radium-v** [comment]
> Today, if you bind `class` on an element, instead of setting the attribute, it will detect this and try to set `className` for better perf.

I wasn't aware of this behavior for the `class` attribute. Are there any noticeable differences on layout rendering between the three methods, in terms of frame timing?

**Comment by EisenbergEffect** [comment]
> > Today, if you bind `class` on an element, instead of setting the attribute, it will detect this and try to set `className` for better perf.
> 
> I wasn't aware of this behavior for the `class` attribute. Are there any noticeable differences on layout rendering between the three methods, in terms of frame timing?

Not that I'm aware of, but I haven't tested that specifically. I'd be surprised if there was.

**Comment by EisenbergEffect** [comment]
I'm going to go ahead and put together a PR for these changes.
