### ISSUE TITLE
fix: repeat directive can unnecessarily rebind views when source array manipulated

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#6431]
# 🐛 Bug Report

Initially associated with https://github.com/microsoft/fast/issues/6379#issuecomment-1270432999 but turned out to be a separate issue.

I'm seeing a lot of rebinding when I do a splice operation with the same objects. In V1 I could do a splice operation on an array used in a repeat directive that cleared out the previous objects, repopulated it with the same objects or mostly the same objects, and not see all the views disconnect/connect. In the current V2 that approach seems to reset all the views.

See this example:
https://stackblitz.com/edit/typescript-gbi5b5?file=index.ts

## 💻 Repro or Code Sample

https://stackblitz.com/edit/typescript-gbi5b5?file=index.ts

## 🤔 Expected Behavior
No unnecessary resetting of views.

## 😯 Current Behavior
Splice operations cause components to reconnect unnecessarily.

**Comment by janechu** [comment]
It appears this has been addressed in #6786 and #6379, please re-open if you still see the issue in v2 of `@microsoft/fast-element`.
