### ISSUE TITLE
fix: $fastController.isConnected is returning false when component renders

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#6435]
# 🐛 Bug Report

`$fastController.isConnected` is returning false when `tree-item` renders. This causes a `tree-view-item` tha is set to `expanded` with to not display its nested items because `aria-expanded` never gets set.

```ts
 @attr({ mode: "boolean" })
    public expanded: boolean = false;
    protected expandedChanged(prev: boolean | undefined, next: boolean): void {
        if (this.$fastController.isConnected) {
            this.ariaExpanded = this.childItems?.length
                ? next
                    ? "true"
                    : "false"
                : null;

            this.$emit("expanded-change", this);
        }
    }
```

## 💻 Repro or Code Sample

This needs to be repro'd using the lastest fast-foundation and fast-element. 

```html
<fluent-tree-view>
    <fluent-tree-item expanded>
           Item 1
           <fluent-tree-item>Nested Item 1</fluent-tree-item>
           <fluent-tree-item>Nested Item 2</fluent-tree-item>
           <fluent-tree-item>Nested Item 3</fluent-tree-item>
           <fluent-tree-item>Nested Item 4</fluent-tree-item>
    </fluent-tree-item>
    <fluent-tree-item>Item 2</fluent-tree-item>
    <fluent-tree-item>Item 3</fluent-tree-item>
<fluent-tree-view>
````

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
@eljefe223 I'm going to close this as the component doesn't actually call this during connectedCallback. I'll push a fix that should address the issue here tonight.
