### ISSUE TITLE
WCAG 4.1.2: Ensures ARIA attributes are allowed for an element's role (fast-radio)

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#6437]
#### Issue
`Ensures ARIA attributes are allowed for an element's role` ([aria-allowed-attr](https://accessibilityinsights.io/info-examples/web/aria-allowed-attr))
#### Target application
[FAST](https://explore.fast.design/components/fast-radio)
#### Element path
iframe;fast-radio
#### Snippet
`<fast-radio readonly="" role="radio" class="readonly" aria-checked="false" aria-required="false" aria-disabled="false" aria-readonly="true" tabindex="0" current-value="on" current-checked="false">Label</fast-radio>`
#### How to fix
    Fix any of the following:
      ARIA attribute is not allowed: aria-readonly="true"
#### Environment
Chrome version 105.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.35.0 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

**Comment by yinonov** [comment]
this was generated by accessibility insight chrome extension
<img width="795" alt="image" src="https://user-images.githubusercontent.com/15140652/194740947-0a6d0f6d-b831-43f7-bc43-17f61deb60f9.png">

**Comment by janechu** [comment]
It appears this was fixed in #6438
