### ISSUE TITLE
feat: add ability for multiple tabs to point to the same tab panel

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/fast#6445]
# 🙋 Feature Request

The tab component seems to use the index of the tabs and tab panels to determine how they are linked.

## 🤔 Expected Behavior

I'd like a way to force a particular tab to point to a particular tab panel.

## 😯 Current Behavior

The implementation seems to use the index of the tab or tab panel to relate the two together.

## 🔦 Context

We have a single tab panel containing a iFrame which we would like to point at from two separate tabs. In each tab we will be posting a message to the iFrame to display different content. Ideally, we don't want the iFrame to be disconnected and connected from the DOM i.e. we want to avoid having to reload the iFrame content (if possible).

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
