### ISSUE TITLE
fix: screen readers don't announce the indeterminate state correctly in checkbox

### ISSUE THREAD

**Issue by MaiLeeTR** [microsoft/fast#6448]
# 🐛 Bug Report

The indeterminate state of the checkbox isn't announced correctly to users who use screen reader software and declares the state as "checked." 

Screen readers will announce the indeterminate state in different ways, such as "mixed" (iOS), "half-checked" (NVDA), "partially checked" (JAWS), or "partially ticked" (TalkBack). (2.1.1)(1.3.1)(4.1.2)

Also agree that there should also be an indeterminate content attribute https://github.com/microsoft/fast/issues/4084. 

## 💻 Repro or Code Sample

1. Turn on screen reader software 
2. Use the Tab key to navigate to the Checkbox Indeterminate example
    - I couldn't produce the indeterminate state in Component Explorer and ran the FAST repo locally to test.
3. Notice that the screen reader software announces the indeterminate state as "checked"

## 🤔 Expected Behavior

Screen readers will announce the indeterminate state in different ways, such as "mixed" (iOS), "half-checked" (NVDA), "partially checked" (JAWS), or "partially ticked" (TalkBack). (2.1.1)(1.3.1)(4.1.2)

## 😯 Current Behavior

`fast-checkbox` is setting `aria-checked="true"` for indeterminate state
<img width="1081" alt="Screen Shot 2022-10-12 at 12 04 37 PM" src="https://user-images.githubusercontent.com/55507048/195412071-4de5d512-73a7-45c1-b183-8d1b9409ce0e.png">

Example from [Aria Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/example-index/checkbox/checkbox-mixed.html) is setting `aria-checked="mixed"` for indeterminate state
<img width="1202" alt="Screen Shot 2022-10-12 at 12 02 59 PM" src="https://user-images.githubusercontent.com/55507048/195412305-5598c5b2-6436-4e36-8d95-d93804777f7c.png">

## 💁 Possible Solution

Set `aria-checked="mixed"` for indeterminate state.

## 🔦 Context

This issue has accessibility implications and is not delivering correct information to screen reader users. [ARIA guidelines from the W3C](https://www.w3.org/WAI/ARIA/apg/example-index/checkbox/checkbox-mixed.html) provides excellent documentation about mixed-state checkboxes.

## 🌍 Your Environment

* MacOS
* Google Chrome Version 106.0.5249.103
* VoiceOver

**Comment by chrisdholt** [comment]
Thanks for this - picking it up :)

**Comment by chrisdholt** [comment]
There is a PR out with a fix for this issue.

With regards to this:

> Also agree that there should also be an indeterminate content attribute https://github.com/microsoft/fast/issues/4084.

Definitely appreciate the feedback here. While these are ARIA radios and not inputs with a type of checkbox, I'm not ready yet to add a content attribute given the current platform API for checkboxes and indeterminate being strictly a property. We'll certainly keep an eye on it. If we wanted to change platform behavior to reflect the property as an attribute, that may be something that could be opened up in Open UI as something to gather community feedback and momentum around.

**Comment by MaiLeeTR** [comment]
> Thanks for this - picking it up :)

Thanks for the quick response and turnaround time for getting a fix in! Really appreciate it.
