### ISSUE TITLE
Convert fast-animation test app to JSS

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#645]
Convert the current test application for fast-animation from SASS to JSS.

In the process of this, remove all files relating to Sass and the dependency on node-sass from the package.

The remove of node-sass will solve the current security vulnerability as well.

![screen shot 2018-07-24 at 3 26 03 pm](https://user-images.githubusercontent.com/16669785/43169467-0654da5a-8f56-11e8-9534-652dae742a4e.png)

node-sass -> request -> hawk -> hoek

**Comment by RamIyer1998** [comment]
Is this issue open? I'd like to look at it if possible.

**Comment by chrisdholt** [comment]
Go for it!

**Comment by RamIyer1998** [comment]
Awesome, thanks! Just to make sure, is [this](https://github.com/Microsoft/fast-dna/blob/master/packages/fast-animation/client/examples/app/assets/styles/test-page.css) the main file you want me to alter? Any other ones or any other advice?

**Comment by chrisdholt** [comment]
@Ramlyer1998 looks like I missed your last comment; this is still up for grabs if you like. If you need details on JSS I'm happy to point you in the right direction.

**Comment by RamIyer1998** [comment]
Hi @chrisdholt ! Sorry for the late reply, finals week is coming so I haven't had time to look at it. I'll would greatly appreciate any guidance you have on the issue.
