### ISSUE TITLE
feat: add default value for `activeid` to `Tabs`

### ISSUE THREAD

**Issue by KingOfTac** [microsoft/fast#6455]
# 🙋 Feature Request
When `Tabs` does not have the activeid attribute explicitly set by a developer, the active indicator jumps beyond the next tab that is clicked on before settling into the correct position. By setting the activeid this behavior does not happen.

## 🤔 Expected Behavior
If the active indicator is enabled, the animation for selecting tabs should function smoothly.

## 😯 Current Behavior
The active indicator jumps beyond the first tab selected by a user before settling on the selected tab if the activeid is not set.

## 💁 Possible Solution
Since `Tabs` assigns ids to its child tab elements in the event that page authors don't provide ids to the tabs, it should probably also set the `activeid` to the first non-disabled tab.

## 💻 Examples
This behavior can be seen in both the now archived `fast-components` package https://explore.fast.design/components/fast-tabs and the vNext storybook example.

**Comment by KingOfTac** [comment]
> @KingOfTac as noted in our quick poll of the collaborators channel the other day I think we'll remove this in Foundation with an expectation it'll exist in the CLI. Should we move this to that repo to track the addition of the active indicator? I'm also thinking of creating an issue to track creating an example for active indicator support since it won't exist in Foundation. Thoughts?

I'm good with either result. I can see value in both tracking for adding through the CLI and an example of manually adding it for folks who opt out of using the CLI.

**Comment by yinonov** [comment]
here's another related issue, the initial transition should be avoided -

https://user-images.githubusercontent.com/15140652/210511658-0b3a7399-6e92-48e2-8771-3005db5bbbf3.mov
