### ISSUE TITLE
fix: validation doesn't work in text-area

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6458]
# 🐛 Bug Report

When trying to check for text-area validation, I keep getting a valid state:
```
<fast-text-area minlength="10" value="111"></fast-text-area>
```
When running:
`element.checkValidity()`
it returns `true` even though it is supposed to return false.

## 💻 Repro or Code Sample

```
<fast-text-area minlength="10" value="111"></fast-text-area>
```

## 🤔 Expected Behavior

I'd expect `checkValidity` to return `false` and set the element's state to `invalid`.

## 😯 Current Behavior

Validity remains true even though it is false.

## 💁 Possible Solution

I checked the proxy state and it seems like it reports true no matter if the text area is valid or not. I was unable to find a quick workaround for this.

## 🔦 Context

Cannot validate a text area.

## 🌍 Your Environment

* OS & Device: MacOS PC
* Browser [Google Chrome, Apple Safari, Mozilla FireFox]

**Comment by YonatanKra** [comment]
@chrisdholt 
It happens for me locally with 2.46.14 but also happens here.

**Comment by chrisdholt** [comment]
> @chrisdholt It happens for me locally with 2.46.14 but also happens [here](https://explore.fast.design/components/fast-text-area).

These are the same versions - we fixed validation in the latest alphas...I'll take a look and see if that can be backported to fix this.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
