### ISSUE TITLE
rfc: consider connecting behaviors *before* rendering component templates

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#6462]
# 💬 RFC
In investigating a bug in DesignToken, I realized that the `ElementController` invokes the element's behavior's connectedCallback *after* it renders the element template. The impact of this is that a descendent element will have its behavior's connectedCallback invoked *before* an ancestor's behavior's connectedCallback is invoked. See https://stackblitz.com/edit/typescript-pehqnq?file=index.ts,index.html for an example.

Effectively, invocation order is:
1. ancestor's connectedCallback invoked
2. descendant's connectedCallback invoked
3. descendant's behavior's connectedCallback invoked
4. ancestor's behavior's connectedCallback invoked

This seems problematic to me, because it means that behaviors cannot reliably be used to implement context-like scenarios where DOM location is a factor (DesignToken for example). If instead ElementController connected behaviors *before* rendering its template, invocation order would be as follows:

1. ancestor's connectedCallback invoked
2. ancestor's behavior's connectedCallback invoked
3. descendant's connectedCallback invoked
4. descendant's behavior's connectedCallback invoked

To me this order is more intuitive because it matches custom element connectedCallback ordering and would allow Behaviors better opportunity to support context-like scenarios.

**Comment by EisenbergEffect** [comment]
Thanks for the detailed invocation order. That makes things very clear. I agree, the current behavior is odd and I can see how that would cause issues. Let's move ahead and see if we can make this change, just making sure to test a few different behavior scenarios.

**Comment by EisenbergEffect** [comment]
@nicholasrice Can you link the PR and update the status on this? Thanks!
