### ISSUE TITLE
fix: discrepancy between Slider and native input range behaviors

### ISSUE THREAD

**Issue by olaf-k** [microsoft/fast#6473]
# 🐛 Bug Report

The current Slider implementation differs from the native input range element in two aspects:
- The default `max` value: 10 for the FAST Slider, 100 for the native input.
- The Slider `step` attr/prop accepts values that do not evaluate to a positive number, which breaks it. It also does not recognize `any` as a valid value.

## 💻 Repro or Code Sample

Simple demo: https://stackblitz.com/edit/slider-vs-input-range?file=index.ts

## 🤔 Expected Behavior

As per specs¹:
- `max` should default to 100 (but that's very minor)
- `step` should only accept positive numbers or fallback on the default value (1)
- `step` should accept `any` as a valid value (meaning `no step`)

¹ https://html.spec.whatwg.org/multipage/input.html#range-state-(type=range)
  https://html.spec.whatwg.org/multipage/input.html#the-step-attribute
  https://www.w3.org/TR/wai-aria/#slider

## 😯 Current Behavior

(See intro.)

## 💁 Possible Solution

Changing `max`'s default is trivial, making `step` only accept positive numbers or reverting to 1 should also be.

Making `step` accept `any` may require a bit more code. Notably, `increment()` and `decrement()` are affected.
[Chromium settled on using 1/100 of the range value](https://chromium.googlesource.com/chromium/src/+/c91b13c8b1e3eb18efc1e9de4ec67fbb2e678e91/third_party/WebKit/Source/core/html/forms/RangeInputType.cpp#207), FAST could do the same.

One way to minimize code—and stay close to the native implementation—could also be to offload these algorithms to the underlying native element stored in `this.proxy`. This way, the code of `convertToConstrainedValue` becomes as trivial as:
```javascript
this.proxy.value = `${value}`;
return +this.proxy.value;
```

But I assume this isn't done in FAST to avoid potential differences in browsers implementations?

**Comment by yinonov** [comment]
there's no smooth dragging in the slider 😿

**Comment by EisenbergEffect** [comment]
@chrisdholt I tagged this one and then assigned to you so you could figure out how you want to handle it. Seems like some good feedback and suggestions here. I think slider hasn't been touched in a long time. IIRC it was one of our first components.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. If there is a need for this to be fixed in Fluent UI web components please file an issue there, it may already have been resolved.
