### ISSUE TITLE
fix: Fallback renderer fails to process boolean type

### ISSUE THREAD

**Issue by YusakuNo1** [microsoft/fast#6476]
# 🐛 Bug Report

My code fails at this line: https://github.com/microsoft/fast/blob/master/packages/web-components/fast-ssr/src/element-renderer/element-renderer.ts#L134 with a boolean attribute

## 💻 Repro or Code Sample

Attribute definition
`@attr isShow = false;`

## 🤔 Expected Behavior

Render correctly

## 😯 Current Behavior

ElementRenderer throws an exception

## 💁 Possible Solution

Add boolean type check at this line: https://github.com/microsoft/fast/blob/master/packages/web-components/fast-ssr/src/element-renderer/element-renderer.ts#L131

**Comment by chrisdholt** [comment]
Thanks @YusakuNo1 - Does this fail when the boolean attribute is decorated with a mode of boolean? That would denote that this is actually boolean. Besides the value given to the property above, there's nothing to say it's boolean.

```ts
@attr({ attribute: "is-show", mode: "boolean" })
public isShow = false;
```

Here's a link to the current docs on customizing attributes: https://www.fast.design/docs/fast-element/defining-elements#customizing-attributes

**Comment by YusakuNo1** [comment]
Discussed offline, let me close this issue as Chris suggested above

**Comment by YusakuNo1** [comment]
Fixed: https://github.com/microsoft/fast/pull/6493
