### ISSUE TITLE
feat: Support Mithril.js

### ISSUE THREAD

**Issue by soulofmischief** [microsoft/fast#6480]
[Mithril](https://mithril.js.org/) is a view framework which offers a much terser and idiomatic developer experience than React. Component lifecycle is very similar to React.

I looked into the fluent Web Components but found the documentation lacking. Would love to get the discussion started on Mithril support! Happy to provide more information, but not sure where to start.

**Comment by EisenbergEffect** [comment]
@soulofmischief Thanks for reaching out. We're happy to add documentation on additional frameworks. Unfortunately, we're not experts in Mithril, so it's a bit difficult for our team to put that together. We'd be happy to work with you to make this happen if you are interested in working on the documentation.

As a first step, have a look at some of our other integration docs:

https://www.fast.design/docs/category/integrations

These guides tend to follow the same format, so we'd just need to figure out what parts are unique to Mithril and document how to set that up. Please let me know if you are interested in working on a contribution like that.

**Comment by janechu** [comment]
I'm going to close this issue due to activity. We are also minimizing our documentation on integrations in v2 of the `@microsoft/fast-element` docs, if someone can confirm that Mithril.js works with web components, we'll add it to the list of cross compatible libraries.
