### ISSUE TITLE
[select]: fast-listbox for wrapping fast-potion

### ISSUE THREAD

**Issue by rachelbt** [microsoft/fast#6494]
Isn't it better for the fast-potion to be wrapped fast-listbox rather than a div with `role="listbox"`?

https://github.com/microsoft/fast/blob/6ebb5ec7bdb7666f49ddc524bc56f70a2e8aa574/packages/web-components/fast-foundation/src/select/select.template.ts#L58

**Comment by chrisdholt** [comment]
Bringing in an answer from @radium-v on Discord. The Select class is extended from ListboxElement so it essentially is a listbox of sorts. Utilizing a `<fast-listbox>` inside of the select template in this way would create a duplication of the functionality.
