### ISSUE TITLE
fix: keyboard navigation not working anymore in nested components in a datagrid

### ISSUE THREAD

**Issue by vnbaaij** [microsoft/fast#6500]
# 🐛 Bug Report

(report and sample are on fluentui but error lies in fast) 
If you nest, for example, text fields in a data grid, you cannot navigate through a text field with the keyboard anymore. Instead, you are transferred to other fields in the grid. 

## 💻 Repro or Code Sample

See https://codepen.io/vnbaaij/pen/LYrZmjb. This is using `web-components@2.0.0` where it works like it should. If you change it to `web-components@2.5.8` it breaks.

## 🤔 Expected Behavior

Keyboard navigation should work inside the nested component

## 😯 Current Behavior

Keyboard navigations works on the datagrid itselfL

## 💁 Possible Solution
Find out what changed in keyboard navigation between 2.0.0 and current version

**Comment by chrisdholt** [comment]
@scomea are you able to investigate?

**Comment by scomea** [comment]
> @scomea are you able to investigate?

Yup, will take a look.

**Comment by scomea** [comment]
Here's a pen with what I believe is the correct keyboarding behavior
https://codepen.io/scomea/pen/yLEVXGP?editors=1010

Two issues:
- passing the columnDefinition to cells could be challenging in Blazor.  Can this api be made easier to use for simple cases?
- There is a bug where the row moves focus when a cell's internal queue is active if arrow key events from the cell internals are not marked with preventDefault.  I will open an issue and add a fix for this after which the event listener with stopPropagation would no longer be required.

**Comment by vnbaaij** [comment]
I'm using this `js` file for the grid: https://github.com/microsoft/fast-blazor/blob/v2/src/Microsoft.Fast.Components.FluentUI/Components/DataGrid/FluentDataGrid.razor.js. The `init` function is called right after the grid is rendered for the first time (Blazor's JavaScript interop in the `OnAfterRenderAsync` Method). 
You think it would be possible to integrate your code from the pen in this javacript file and then call if from the `init` function? (as you might have noticed by now, I'm not the greatest JavaScript guru...😁

**Comment by scomea** [comment]
> I'm using this `js` file for the grid: https://github.com/microsoft/fast-blazor/blob/v2/src/Microsoft.Fast.Components.FluentUI/Components/DataGrid/FluentDataGrid.razor.js. 

Is this for FAST V2?  If so, I'd rather get the bug fix part into FAST so we don't have to worry about it here.  The part about how to pass the columnDefinition to the cells remains.  Ideally authors would be able to control these params, yes?

**Comment by vnbaaij** [comment]
Not sure which version is used underneath the Fluent UI web components atm. Anyways, I'm not exposing `columnDefinition` to the user (and not using it internally either). If it is needed, I think I can generate it internally and pass it onwards.

**Comment by chrisdholt** [comment]
> Not sure which version is used underneath the Fluent UI web components atm. Anyways, I'm not exposing `columnDefinition` to the user (and not using it internally either). If it is needed, I think I can generate it internally and pass it onwards. I suppose you can fix just it on the FAST side. What I meant was to use repurpose/re-use the script that contains my `init` function to pass the needed `columnDefinition`

Sorry, just seeing this response - while work is happening on a Fluent v2 visually aligned WC version, the current prod version being used by the Blazor repo is not the alpha versions, it's the stable (FAST Element v1) versions. Hope this helps give clarity on the path forward.

**Comment by Ogglas** [comment]
Is this being looked at?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I don't believe Fluent UI will have a data grid either.
