### ISSUE TITLE
docs: SSL/TLS certificate for fast.design is expired

### ISSUE THREAD

**Issue by brendonofficial** [microsoft/fast#6524]
# 🙋 Documentation Request

The SSL/TLS certificate for hostname `fast.design` expired November 13, 2022.

## 💁 Possible Solution

Replace the certificate so that redirection to `www.fast.design` works again without security warning.

**Comment by EisenbergEffect** [comment]
Thanks for reporting. We are aware of this and working towards a fix. For now, if you visit `www.fast.design` you shouldn't have any problem.
