### ISSUE TITLE
fix: limitation when trying to set a default value without triggering change event in radio-group and radio components

### ISSUE THREAD

**Issue by thomleclerc** [microsoft/fast#6525]
# 🐛 Bug Report

I'm using the radio group and the radio button FAST components and I came across a small limitation and was wondering if there was any workaround possible. I'm trying to provide a defaultValue to the radio-group component using the value attribute which works but it's triggering the "change" event which isn't a really big problem but I'd like it better if was possible to not trigger it. As you can see in the stackblitz, the change event is triggered as soon as the page load. A defaultValue could prevent this type of behaviour but it's not currently available on the radio-group and radio. I tried adding a defaultValue on a customElement extending the RadioGroup class but wasn't able to do it as of right now. Are you guys aware if there is any workaround possible? I'm available if you guys have any questions, just tag me.

## 💻 Repro or Code Sample

[Stackblitz](https://stackblitz.com/edit/typescript-3fsewe?file=index.ts,package.json)

## 🤔 Expected Behavior

Having a default value which doesn't trigger the change event could prevent the behaviour I'm facing.

## 😯 Current Behavior

As of right now, there is only a value attribute which triggers a change event whenever it's updated (like it should). 

## 💁 Possible Solution

Having a defaultValue attribute on the radio-group components or defaultChecked attribute that works in radio-group which doesn't trigger the change event.

## 🔦 Context

It's not a major issue since there is a few workarounds. But I haven't found any workaround which doesn't trigger the change event which would be ideal in my case.

## 🌍 Your Environment

package.json versions :
 "@microsoft/fast-components": "^2.30.6",
    "@microsoft/fast-element": "^1.10.2",
    "@microsoft/fast-foundation": "^2.46.8",
    "@microsoft/fast-react-wrapper": "^0.3.9",
    "@microsoft/fast-web-utilities": "^6.0.0",

OS & Device: MacOS BigSUR v11.2
Browser : Google Chrome Version 104.0.5112.101 (Official Build) (x86_64)

**Comment by EisenbergEffect** [comment]
@chrisdholt Assigning this to you for further triage and follow-up.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
