### ISSUE TITLE
fix: yarn fails

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6526]
When I run `yarn` the installation fails on the `prepare` flow.
Here's the error I get:
```
../../../../../node_modules/@types/mocha/index.d.ts:2584:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'.

2584 declare var beforeEach: Mocha.HookFunction;
```
It appears to be an issue with `mocha`.

This happens even if I add `skipLibCheck` in `tsConfig`.

Any idea what the issue might be?

**Comment by EisenbergEffect** [comment]
This is strange. I just did a clean install on a new OS this morning and everything worked as expected. Did you run `yarn` exactly or did you also run something like `npm install` first by any chance? Any additional details you can provide?

**Comment by YonatanKra** [comment]
Nope - just followed the `contribution` guide to the letter :)
It used to work in the past. Deleted the old clone, recloned, and started all over - but it didn't work.
It fails on `fast-todo-app`:
```
lerna ERR! yarn run prepare stderr:
error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run prepare exited 1 in 'fast-todo-app'
error Command failed with exit code 1.
```

**Comment by YonatanKra** [comment]
@EisenbergEffect 
I've added `"skipLibCheck": true,` to the `todo-app`'s `tsconfig` and now everything is working fine.
