### ISSUE TITLE
'control' is not always defined on BreadcrumbItem

### ISSUE THREAD

**Issue by mollykreis** [microsoft/fast#6531]
# 🐛 Bug Report

The `BreadcrumbItem` class extends `Anchor`, which exposes a public property `control: HTMLAnchorElement`. However, when an instance of a breadcrumb item does not specify an `href`, the template for the breadcrumb item does not include an anchor element. As a result, `control` is undefined, which isn't a valid value for type `HTMLAnchorElement`.

This causes problems when `@typescript-eslint/no-unnecessary-condition` is enabled if you want to write code that looks something like`const myHref = myBreadcrumbItem.control?.href`.

## 🤔 Expected Behavior

The `control` property on a BreadcrumbItem should be appropriately typed as `HTMLAnchorElement | undefined`.

## 😯 Current Behavior

The `control` property on a BreadcrumbItem is typed as `HTMLAnchorElement` even though it is possible to be undefined. You have to disable the `@typescript-eslint/no-unnecessary-condition` lint rule to check for `control` being defined.

See this [stackblitz example](https://stackblitz.com/edit/typescript-4tlyn9?file=index.ts). The console prints out _Breadcrumb 2 control is not defined_, showing that it is possible for `control` to be undefined. However, if you lint the code, the condition of `breadcrumbItem.control === undefined` causes the following lint error: `Unnecessary conditional, the types have no overlap  @typescript-eslint/no-unnecessary-condition`.

## 🌍 Your Environment

Not environment specific.

**Comment by chrisdholt** [comment]
@mollykreis can you create a simple repro with this in Stackblitz perhaps?

**Comment by mollykreis** [comment]
> @mollykreis can you create a simple repro with this in Stackblitz perhaps?

I've updated the description to include a stackblitz link.

**Comment by chrisdholt** [comment]
> > @mollykreis can you create a simple repro with this in Stackblitz perhaps?
> 
> I've updated the description to include a stackblitz link.

Thanks, I think this is essentially "resolved" in the vNext implementation as we've removed the "when" in favor of keeping the anchor (just without an href): https://github.com/microsoft/fast/blob/802443ffb2b19a078f9b48f62e6d1a35e3276fb5/packages/web-components/fast-foundation/src/breadcrumb-item/breadcrumb-item.template.ts#L14

I'll take an action item to update the typing in the archives branch though.

**Comment by chrisdholt** [comment]
> > @mollykreis can you create a simple repro with this in Stackblitz perhaps?
> 
> I've updated the description to include a stackblitz link.

Thanks @mollykreis, upon looking into this on our side, we'll need to make this change in the "anchor" class which is less than ideal. *Technically* though, I think that the reference _could_ be undefined if a separate template were provide for anchor which didn't include the reference which gives some precedent for making the update there. I'll look to get a change up in the archives branch.
