### ISSUE TITLE
docs: fix contribution guide

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6532]
The contribution guide is out of date.

For instance, the path `packages/web-components/fast-components` does not exist on `master`.

In addition, npm scripts like:

```
"tdd": "yarn dev & yarn test-chrome:watch",
    "tdd:firefox": "yarn dev & yarn test-firefox:watch",
```

No longer work.

**Comment by KingOfTac** [comment]
The docs will be seeing a complete overhaul soon for the vNext release so if you could add any feedback/suggestions on #6527 so that they can be consolidated and tracked along with that effort, it would be greatly appreciated.

**Comment by EisenbergEffect** [comment]
Closing this one as duplicate since we're tracking a big rework of the content starting soon.
