### ISSUE TITLE
fix: custom dataGridRow and dataGridCell result in `undefined` tag names in data-grid

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6534]
# 🐛 Bug Report

When using the `data-grid` and trying to add custom grid classes with foundation's templates, the tag names are not taken correctly

## 💻 Repro or Code Sample

https://codesandbox.io/s/using-fast-data-grid-forked-2oe93h

Note the output in the screen with `undefined` tag names.

## 🤔 Expected Behavior

I would expect the tag name to be the tag name of my custom row and cell elements.

## 😯 Current Behavior

It adds an `undefined` element.

## 💁 Possible Solution

There is an issue with the build that hard codes the `DataGridRow` and `DataGridCell` in the build artifact's template files.
This snippet was taken from the `npm package` version 2.47.1:

```
import { DataGridRow } from "./data-grid-row.js";
function createRowItemTemplate(context) {
    const rowTag = context.tagFor(DataGridRow);
    return html `
    <${rowTag}
        :rowData="${x => x}"
        :cellItemTemplate="${(x, c) => c.parent.cellItemTemplate}"
        :headerCellItemTemplate="${(x, c) => c.parent.headerCellItemTemplate}"
    ></${rowTag}>
`;
}
```

## 🔦 Context

I cannot use custom elements without rebuilding the whole templates.

* Version 2.47.1

**Comment by YonatanKra** [comment]
I found out now that `Master` is not the released version (quite confusing for me).
The version in `Master` should indeed fix this issue.
Any ETA for its release?

**Comment by EisenbergEffect** [comment]
Some of the code in the code sandbox is incorrect. I think there's a simple solution, which is to tell foundation that the base type maps to your new derived type. You can do this when you define your component:

```ts
const myDataGridCell = MyDataGridCell.compose({
    baseName: "data-grid-cell",
    baseClass: DataGridCell,
    template: dataGridCellTemplate,
    styles: cellStyles
});
```
