### ISSUE TITLE
fix: change event in menu fired multiple times when clicking on `menuitemradio` items

### ISSUE THREAD

**Issue by rinaok** [microsoft/fast#6536]
# 🐛 Bug Report

The `menu` fires a `change` event multiple times when you click on a` menu item radio`.

## 💻 Repro or Code Sample

Catch the `change` event by clicking on a `menu item radio`.

## 🤔 Expected Behavior

`Change` event should only be fired once.

## 😯 Current Behavior

The `change` event is fired multiple times.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by yinonov** [comment]
menu `change` event is bubbling from `menuitemradio` buttons
the following recording shows how 1 click triggers 3 changes -

https://user-images.githubusercontent.com/15140652/203319476-52953bd5-983c-45b8-9893-17e8191c054f.mov

1. the clicked radio button that changed from `checked="undefined"` to `checked="true"`
2. the previous sibling radio button that changed from `checked="undefined"` to `checked="false"`
3. the next sibling radio button that changed from `checked="undefined"` to `checked="false"`

the natural expectation is for the initially undefined values would be false, and prevent redundant bubbling changes.

are there details missing in that expectation?
