### ISSUE TITLE
fix: date selection in Calendar does not work

### ISSUE THREAD

**Issue by mmmhsalois** [microsoft/fast#6538]
# 🐛 Bug Report
When trying to select a date in the Calendar, the date does not get selected.

## 💻 Repro or Code Sample
- Open Storybook
- Go to Calendar component
- click on a date

## 🤔 Expected Behavior
The date should receive the class `selected` and the styles applied.

## 😯 Current Behavior
Nothing happens. There's no error, but the date does not receive the `select` class and no styles are applied.
Also the test for selecting a date passes.

## 💁 Possible Solution
When I click on the date, the `dateSelected` event is emitted correctly via the `handleDateSelect` function, but I got trouble following it after that.
I want to contribute.

## 🔦 Context
I discovered this while trying to use the Calendar to make a date picker. When I used the `handleDateSelect` function, it had the same behaviour as in the Storybook.

## 🌍 Your Environment

* OS & Device: MacOS
* Browser: Chrome, Firefox
* Version [e.g. 1.8.0]: master branch

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
