### ISSUE TITLE
fix: Fluent-tabs .tabpanel missing "part attribute"

### ISSUE THREAD

**Issue by navinamat** [microsoft/fast#6539]
# 🐛 Bug Report

![image](https://user-images.githubusercontent.com/118706167/204336729-401d0e5b-7973-41f4-9437-2d75af70f722.png)

In the shadow root of the fluent-tabs component, the div with the class "tabpanel" is missing the part="tabpanel" attribute.

Instead the part="tabpanel" attribute has been added to the slot element within the div.
This means we are unable to select it in CSS and therefore are unable to style it.
The workaround below uses JavaScript to manually add and remove styles.

## 🤔 Expected Behavior

Expected behavior 
div class="tabpanel" part="tabpanel"

## 😯 Current Behavior

Current behavior (our workaround due to this bug):
Unable to access the tabpanel css since it is in the shadom-root with no "part" attribute
Due to this we are:
- creating a @change listener to determine when a user changes tabs
-parsing the data to determine the current tab is "home-tab"
- adding and removing classes to the :host to add specific styles to the "home-tab" tabpanel
-adding/removing classes when the connectedCallback() is called, so on refresh the correct styles are applied when the default tab ("home-tab") is open 

<img width="644" alt="932aa128-498d-49d8-ae19-870cdf3e5b74" src="https://user-images.githubusercontent.com/118706167/204343044-e7437ac3-2e0c-478f-8cac-dae5759b7f3f.png">

<img width="691" alt="5fd94e76-856f-4c0f-bc9a-6b24e06be378" src="https://user-images.githubusercontent.com/118706167/204342947-5d35d13f-8a7c-487e-bebe-8655208d877c.png">

## 💁 Possible Solution
div class="tabpanel" part="tabpanel"

## 🔦 Context

Instead the part="tabpanel" attribute has been added to the slot element within the div.
This means we are unable to select it in CSS and therefore are unable to style it.
The workaround below uses JavaScript to manually add and remove styles.

**Comment by chrisdholt** [comment]
I think this is an issue both in the main branch and the archives. Thanks for this!
