### ISSUE TITLE
fix: Incorrect dates when in different timezones in the Calendar

### ISSUE THREAD

**Issue by mmmhsalois** [microsoft/fast#6547]
# 🐛 Bug Report
When there's a big time difference (>3 hours) withe EST timezone, the active dates, today and selected dates are incorrect.

## 💻 Repro or Code Sample
* Put your timezone to CET (problems with big timezone difference)
* Open storybook
* Select the Calendar component

## 🤔 Expected Behavior
Should display the right active days, today's date and select the correct day.

## 😯 Current Behavior
When timezone in CET, you can see the inactive dates are not the right dates and when selecting a date it selects the previous day.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/64780157/204577200-7f23e7df-f077-4e2f-9afa-7f97c9f2ec0a.png">

## 💁 Possible Solution
The problem is solved in the Date Picker PR (#5539). I'm investigating what succeeded in solving this problem. 

## 🔦 Context
I was trying to use the Calendar to make a Date Picker for our Design System.

## 🌍 Your Environment

* OS & Device: MacOS
* Browser: Chrome
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
closed with #6548
