### ISSUE TITLE
fix: default property missing in DesignTokens

### ISSUE THREAD

**Issue by nelak2** [microsoft/fast#6555]
# 🐛 Bug Report

As per the documentation for using DesignTokens located at: https://github.com/microsoft/fast/blob/master/sites/website/src/docs/design-systems/design-tokens.md

The currently set default value of a DesignToken can be retrieved through it's 'default' property. This property does not appear to exist and there doesn't seem to be a clearly defined way to get the default value of the DesignToken.

## 💻 Repro or Code Sample

```
import { DesignToken } from "@microsoft/fast-foundation";

export const specialColor = DesignToken.create<string>("special-color");
specialColor.withDefault("#FFFFFF");

const value = specialColor.default;
```

## 🤔 Expected Behavior

specialColor.default should be defined and return ``"#FFFFFF"``

## 😯 Current Behavior

specialColor.default is not defined and there doesn't appear to be a way to access the default value.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
I don't see versions listed here, but I think if you're on the non-alpha versions then this feature does not yet exist. The doc referenced above is for the latest alphas which are tracking our main branch and has this support. Here's your example using the latest alpha version: https://stackblitz.com/edit/typescript-sv1fdw?file=index.ts

**Comment by nelak2** [comment]
That would certainly explain it. Thanks!
