### ISSUE TITLE
JS application of style in DataGridCell

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6559]
In DataGridCell, there are these lines:
[Line 1](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts#L115)
And this:
[Line 2
](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts#L286)
In these lines, the element's `style` property is updated from within the code.

There are a few issues in this context:
1. The separation from the template is fractured. Suddenly something appears on my element I might not expect (which happened to me while trying to work with a custom grid cell template).

2. In that same file, the `updateCellStyle` is called on change but also on `connectedCallback`. [Line 1](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts#L115) already sets the style, but then we have `updateCellStyle` called to change the style again. What is the purpose of [Line 1](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts#L115) if it is overridden by the call to `updateCellStyle` a few lines later?

3. `updateCellStyle` is private. Typescript would not allow to override it. Looking at `gridColumnChanged`, I see its only function is to invoke `updateCellStyle` if the element is connected. Hence, overriding `gridColumnChanged` gives me the same effect. This does not solve the `connectedCallback` call to `updateCellStyle` and because `gridColumn` is set by the template, `updateCellStyle` sets the style automagically.

The same thing happens in the row class for `gridTemplateColumns`.

Because the style is set on the element, a way to bypass that is to use `!important` in the `.scss` file.

Is there a reason this logic is in the class file? Wouldn't it be better to move the styling logic to the template file?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
