### ISSUE TITLE
fix: Screen reader reporting "dash dash dash" when in focus is on fast-divider

### ISSUE THREAD

**Issue by cdvillard** [microsoft/fast#6560]
# 🐛 Bug Report

When using the `fast-divider` component in its default configuration and testing with the JAWS screen reader, the user was able to focus on it via keyboard navigation and it was reported back as "dash dash dash dash." Considering it's primarily a decorative component, it should not be focusable with keyboard navigation.

## 🤔 Expected Behavior

Should skip this out of the box with minimal intervention.

## 😯 Current Behavior

When navigating with a keyboard using JAWS or a screen reader, the divider is selected and reported as "dash dash dash dash".

## 💁 Possible Solution

Ensure the appropriate ARIA is in place to label this as "decoration" so that it's skipped over.

**Comment by chrisdholt** [comment]
Can you please a repro or code example of the “default configuration” song with the appropriate version number?

**Comment by chrisdholt** [comment]
Just as a quick follow-up, I'd be curious if this repro's in any other AT. If so, a repro will help to see if perhaps its a separate issue. The default implementation includes a role, by default (template and class links below).

Template setting the role: https://github.com/microsoft/fast/blob/archives/fast-element-1/packages/web-components/fast-foundation/src/divider/divider.template.ts

Default role is `separator`: https://github.com/microsoft/fast/blob/9f60490fed33e582875d740e9de2da6e9a5cb7a7/packages/web-components/fast-foundation/src/divider/divider.ts#L23

Given the above, I don't believe this is something in the divider code, so a repro will really help see if something else is going on.

**Comment by chrisdholt** [comment]
@cdvillard just wanted to follow up on the above and see if you have any more information. Given the implementation and the fact that we have this specific scenario being regularly tested, I'm likely going to close out as no-repro without any further info. It's definitely possible that something else is happening under the covers so if you have a repro (especially with other AT) that will go a long way to helping identify any possible issue.

**Comment by chrisdholt** [comment]
Closing this as no repro - if you have a repro or more details feel free to open!
