### ISSUE TITLE
fix: Inheriting from FoundationElement does not seem to work 

### ISSUE THREAD

**Issue by r-laf** [microsoft/fast#6562]
# 🐛 Bug Report

I was trying to following the document <https://www.fast.design/docs/design-systems/creating-a-component-library> to create a counter component, but the result has not been great.

I created two fastCounters: fastCounter1 and fastCounter2. The former directly extends FoundationElement, whereas the latter indirectly extends FoundationElement (via Button in this case, but it works with several existing component as I tested) They are mostly the same in other aspects .

```js
export class Counter1 extends FoundationElement {
    @attr count = 0;

    increment() {
        this.count++;
    }
}

export const fastCounter1 = Counter1.compose<CounterDefinition>({
    baseName: 'counter1',
    template: counterTemplate,
    styles: counterStyles,
    defaultButtonContent: "Count 1!"
});
```

```js
export class Counter2 extends Button {
    @attr count = 0;

    increment() {
        this.count++;
    }
}

export const fastCounter2 = Counter2.compose<CounterDefinition>({
    baseName: 'counter2',
    template: counterTemplate,
    styles: counterStyles,
    defaultButtonContent: "Count 2!"
});
```

Though you might see some error in the console complaining about fastCounter2, but it actually works. The problem is fastCounter1 does not even show its content up in the page. 

```html
            <fast-button>I'm a useless button</fast-button>
            <fast-counter1></fast-counter1>
            <fast-counter2></fast-counter2>
```

As shown in the screenshot below:
![image](https://user-images.githubusercontent.com/7352394/206856630-5955c0a7-6df3-4483-a005-9f1e7c1ea462.png)

## 💻 Repro or Code Sample

A code sample is available at <https://github.com/zh4ui/fastComponentTest/blob/main/src/fast-counter.ts>
The sample is based on <https://github.com/microsoft/fast/tree/master/examples/vite-starters/vite-fast-typescript-starter>

## 🤔 Expected Behavior

fastCounter1 should appear in the page.

## 😯 Current Behavior

fastCounter1 does not appear in the page.

## 💁 Possible Solution

Can not find a clue about what's wrong.

## 🌍 Your Environment

* OS & Device:: Windows 11 (up to date)
* Browser: Microsoft Edge (up to date)
* Version 
  ```
      "@microsoft/fast-components": "^2.30.6",
      "@microsoft/fast-element": "^1.7.0",
      "@microsoft/fast-foundation": "^2.47.1-0"
  ```

**Comment by chrisdholt** [comment]
Thanks for the issue and repro - we'll investigate and follow up.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
