### ISSUE TITLE
fix: duplicate and missing rows and cells in data-grid

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6564]
# 🐛 Bug Report

When removing and appending a data grid to the DOM it recreates the header row and doesn't populate the data cells.

## 💻 Repro or Code Sample

1. Go to this demo: https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid.ts#L382
2. Click on the `toggle grid` button twice
3. See that the grid reappears with double headers and without the data.
4. Click a few more times, and you'll see that every time it adds another header row, and still no data.

I first noticed it when I used `when` to toggle the grid.

## 🤔 Expected Behavior

I'd expect the grid to render correctly according to its data.

## 😯 Current Behavior

Header is added on every insertion. Data is missing.

## 💁 Possible Solution

Extra header rows:
Removing [this line](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/data-grid.ts#L382) solves the issue. It arises from the header being added on every connected callback but not removed on disconnected callback, so there are many other ways to go at it.

Missing data:
The grid does not refresh according to the data. A simple reassignment of the `rowsData` can solve it (adding a hacky `this.rowsData = JSON.parse(JSON.stringify(this.rowsData));` to the connected callback solved it). Again, there are several ways to solve the issue.

## 🔦 Context

I was unable to use the grid with a conditional template directive (`when`).

**Comment by YonatanKra** [comment]
I'll be happy to raise a PR for this one. If you'd like to direct me on the solution's direction, I'll implement it.

**Comment by chrisdholt** [comment]
@scomea can you take a look at this?
