### ISSUE TITLE
fix: setting rowsData to undefined or null throws an error in data-grid

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6565]
# 🐛 Bug Report

setting rowsData to undefined or null throws an error in data-grid

## 💻 Repro or Code Sample

1. Create a data-grid
2. Set rowsData to `undefined` or `null`
3. See the error

## 🤔 Expected Behavior

I'd expect the grid to clear the data.

## 😯 Current Behavior

It throws an error and leaves the data as it is in the grid (but `rowsData` is set to undefined).

## 💁 Possible Solution

Handle non Array case in `rowsDataChanged`.

## 🔦 Context

Sometimes data comes from the server and the data property does not exist (and not set with empty array).

**Comment by chrisdholt** [comment]
Assigning @scomea to investigate, thanks @YonatanKra!

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
