### ISSUE TITLE
Grid refocus feature

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6582]
While exploring the grid, I found this hidden feature:

`// if focus was on the row when data changed try to refocus on same cell`

[link to code](https://github.com/microsoft/fast/blob/ec2b158dcf39c8b4152b22c3b65963046b473e17/packages/web-components/fast-foundation/src/data-grid/data-grid-row.ts#L196)

Reading it more thoroughly, I see that `refocusOnLoad` changes to `true` only when the row's data changes.

That means that if it didn't change after the element was connected and then we remove and add the row again, the refocus wouldn't work.

At first glance, it looks like a cumbersome and error-prone mechanism to keep something in focus. 

Can you explain the idea behind it, please? There is no test for this feature, so it might be redundant.

**Comment by YonatanKra** [comment]
I think I found it. A few lines above this line, it explains that the repeat behavior reuses the rows. Can I assume that the repeat behavior disconnects and reconnects the rows to the DOM, and hence this is the mechanism that makes this work?

**Comment by scomea** [comment]
I believe that exists to handle the frame interval between the rows repeat creating the rows and the cells repeat creating the cells.

**Comment by YonatanKra** [comment]
Yea, that's what I meant in my comment. Thanks for clarifying this.
