### ISSUE TITLE
Effect of grid-template-columns in data-grid

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6583]
Hi,
I tried playing with `grid-template-columns` in the grid but it had no effect.
Looking at the code, what sets the number of columns is the actual number of `rowElements`.
What is `grid-template-columns`'s purpose?

**Comment by scomea** [comment]
Each row in a datagrid has a css grid layout internally but only uses the horizontal axis.  The parent `grid-template-columns` attribute is passed to each row to apply to its internal layout which keeps the column widths in sync.  It provides an easy way for developers to modify the column widths.

**Comment by scomea** [comment]
This example uses the "gridTemplateColumns" prop to make the current "sort" column of the grid wider. 

https://github.com/scomea/FASTPWA/blob/c8c3a2b48470b9f7ad35ea6892c5843df34b2736/src/pages/file-view-page/file-view-panel.ts#L174

**Comment by YonatanKra** [comment]
It works this way. Thanks!
