### ISSUE TITLE
Datagrid focusOnCell method

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6588]
Hi,
In the data grid, the focusOnCell method has some row template logic hard coded into it:
```
const cells: NodeListOf<Element> = focusRow.querySelectorAll(
            '[role="cell"], [role="gridcell"], [role="columnheader"], [role="rowheader"]'
        );
```
This can be replaced by `focusRow.cellElements` instead of the hard coded `querySelector`. Kind of dependency inversion that couples the row to its parent without the abstraction allowed via `cellElements`.

IMO this makes the component harder to test and reduces its flexibility as it forces the grid to know more about its children's implementation detail (how do we call a cell).

Is there a reason why it should not use `focusedRow.cellElements`?

**Comment by scomea** [comment]
Worth looking into.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
