### ISSUE TITLE
fix: anchor href difference in fast-foundation

### ISSUE THREAD

**Issue by m-akinc** [microsoft/fast#6591]
# 🐛 Bug Report

For a FAST anchor and a native anchor (`a` element), there are cases where the retrieved `href` value differs, given the same attribute value.

## 💻 Repro or Code Sample

https://codepen.io/m-akinc/pen/xxJRBQG
See the output in the debug console.

## 🤔 Expected Behavior

The value retrieved from the FAST anchor should match the one retrieved from the native anchor.

## 😯 Current Behavior

The value returned from the native anchor is the full URL (not just relative part), and it has been url encoded (double quotes have been replaced with %22). The value from the FAST anchor is unchanged from the value specified as the `href` attribute value.

## 💁 Possible Solution

Apply a tranformation when fetching the value.

## 🔦 Context

I was replacing native `a` elements with anchors from our design system (based on the FAST anchor), and a unit test failed because of this API difference.

**Comment by chrisdholt** [comment]
Just for awareness, there's no modification of this happening on our side from what I can tell. We pass the string through as it is and do not modify it whatsoever. The change here may be happening, but the I'm not sure it's an artifact of code in FAST Foundation itself...

Template passing `href`: https://github.com/microsoft/fast/blob/ca0e62ee8d05f72d1d8c1ad66bd6eea8e3f0a4eb/packages/web-components/fast-foundation/src/anchor/anchor.template.ts#LL17C13-L17C34

`@attr` for `href`:
https://github.com/microsoft/fast/blob/ca0e62ee8d05f72d1d8c1ad66bd6eea8e3f0a4eb/packages/web-components/fast-foundation/src/anchor/anchor.ts#L42

**Comment by EddieMachete** [comment]
> Just for awareness, there's no modification of this happening on our side from what I can tell. We pass the string through as it is and do not modify it whatsoever. The change here may be happening, but the I'm not sure it's an artifact of code in FAST Foundation itself...
> 
> Template passing `href`: https://github.com/microsoft/fast/blob/ca0e62ee8d05f72d1d8c1ad66bd6eea8e3f0a4eb/packages/web-components/fast-foundation/src/anchor/anchor.template.ts#LL17C13-L17C34
> 
> `@attr` for `href`:
> 
> https://github.com/microsoft/fast/blob/ca0e62ee8d05f72d1d8c1ad66bd6eea8e3f0a4eb/packages/web-components/fast-foundation/src/anchor/anchor.ts#L42

The `href` attribute/property in `HTMLAnchorElement` behaves differently to most others. With relative paths, calling the `href` getter method returns a full URL, while the value of the attribute remains the same:

<details>
  <summary>HTML Anchor case</summary>
  
  **Given** that the `href` attribute of an `<a>` is set to `/relative-path`
  **When** calling `a.href`
  **Then** the system returns `https://my-domain/relative-path`
  **When** calling `a.getAttribute('href')`
  **Then** the system returns `/relative-path`
</details>

This is different for `FASTAnchor` where both the attribute and getter method return the same value.

<details>
  <summary>FAST Anchor case</summary>
  
  **Given** that the `href` attribute of a `<fast-anchor>` is set to `/relative-path`
  **When** calling `anchor.href`
  **Then** the system returns `/relative-path`
  **When** calling `anchor.getAttribute('href')`
  **Then** the system returns `/relative-path`
</details>

As you mentioned, there is no modification on the component code taking place. The HTML Anchor just works in a different way. With a _vanilla_ custom element it would be possible to write a getter method and replicate the functionality. I have not been able to replicate the functionality on the FAST Anchor using a converter.

Here is a codepen where I was attempting to add an attribute that replicates the functionality in `<a>`: https://codepen.io/eddiemachete/pen/JjmqzPE

**Comment by chrisdholt** [comment]
Thanks @EddieMachete - by "vanilla" do you mean specifically leveraging `is` along with the HTMLAnchorElement itself? Basically, `foo-element` is HTMLAnchorElement?

**Comment by chrisdholt** [comment]
> @chrisdholt, what I meat is that if we were building the component without extending `FASTElement` we can easily replicate the `<a>` behaviour by just providing a getter for `href`. See example: https://codepen.io/eddiemachete/pen/jOejYwV

Thanks, just wanted to clarify.

**Comment by EddieMachete** [comment]
I've worked with a couple design systems in the past (Ionic and Shopify's polaris) and they did not provide a custom implementation for `<a>`. They only had custom controls for buttons. This may be a reason why.

**Comment by chrisdholt** [comment]
> > @chrisdholt, what I meat is that if we were building the component without extending `FASTElement` we can easily replicate the `<a>` behaviour by just providing a getter for `href`. See example: https://codepen.io/eddiemachete/pen/jOejYwV
> 
> Thanks, just wanted to clarify.

Actually - this example leverages `is` and extends anchor - I think that's an important consideration here because it's _leveraging_ the browser internals of an Anchor. I would expect this, which is what I was getting at - the reason this works just like the anchor is because it *is* an anchor (also to your point). I don't think I'd expect the same from a vanilla implementation which shadows an anchor.

The important thing here is to emphasize that I think this is likely an artifact of custom elements which do not extend built-ins, rather than a "bug" in how this is managed. I'm open to proposals here, but currently the only way I can see solving the underlying problem here (the value of href in the test is different after changing from an anchor to `foo-anchor` in `%22`) would be to add side-effects which try to augment what the browser is doing to mirror what a built-in would do...which would be odd to me.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
