### ISSUE TITLE
Datagrid - using custom row and cell elements

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6593]
I'm trying to port the data-grid to our design system gradually.
The simplest thing to start the port would be as follows:
1. Create grid/row/cell classes that extend FAST's grid classes.
2. Create grid/row/cell templates that at first export the source's templates.
3. Create my own style files for grid/row/cell
4. Create an index file that looks like this:
```
xport const dataGrid = DataGrid.compose<FoundationElementDefinition>({
	baseName: 'data-grid',
	template: template as any,
	styles: dataGridStyles,
})();

export const dataGridRow = DataGridRow.compose<FoundationElementDefinition>({
	baseName: 'data-grid-row',
	template: DataGridRowTemplate as any,
	styles: dataGridRowStyles,
})();

export const dataGridCell = DataGridCell.compose<FoundationElementDefinition>({
	baseName: 'data-grid-cell',
	template: DataGridCellTemplate as any,
	styles: dataGridCellStyles,
})();
export const dataGridElements = [dataGridCell, dataGridRow, dataGrid];

export const designSystem = DesignSystem.getOrCreate();

designSystem.withPrefix(prefix).register(...dataGridElements);
```
I omitted the imports and some constants. The idea is all the imports of the components/styles/templates are from my files that either extend of export FAST's originals.

Here are my issues:
1. I had to recreate the grid and row templates because of the hard coded usage of `tagFor`. It uses static imports that always bring FAST's classes. So if I register my own row and cell components, `tagFor` returns `undefined`. 
2. I tried using `rowElementTag`, but because of said issue, it only sets the tag for the `header row`, while the data rows remained `undefined` until I changed the rewrote the template file. Might this be a bug in `rowElementTag`? It is a public API, but it is not really explained.

Thanks!

**Comment by scomea** [comment]
You can define what tag the grid uses for rows (and rows use for cells) when you register the components:

![image](https://user-images.githubusercontent.com/7649425/211599778-99573e1f-5530-4ebb-bd42-5516edba5ad7.png)

ie. dataGridRow: "my-custom-row-element"

https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/stories/data-grid.register.ts

**Comment by YonatanKra** [comment]
`rowElementTag` affects only the header row as far as I can see.
I tried it locally as well as in here: https://explore.fast.design/components/fast-data-grid
Maybe I missed something?

**Comment by scomea** [comment]
The prop is used to generate the header in component code, but for regular rows it is used to generate the default row template.  Note that the default row template is defined when the component type is defined and setting the tag later won't change the default template.  You can always pass a custom row template to a grid instance using whatever row element component you want.  IMO the best approach is to set the tag property to use as default when you define the component and pass in custom row templates to grid instances that need custom treatments.  Data grid is extremely customizable via templates.

https://github.com/microsoft/fast/blob/dfab11aed93627f28d0985a376f6fd461b27cdb6/packages/web-components/fast-foundation/src/data-grid/data-grid.template.ts#L19

**Comment by YonatanKra** [comment]
Thanks for clarifying this issue.
We have a unique requirement to allow consumers more flexibility with custom element tags (via custom prefixes).
This way, they can use multiple versions of the DS (e.g. call grid V2 and V3, but give each its own prefix) and avoid custom elements naming clash.
I went with a custom template (copy-pasting yours actually).
Thanks again!

**Comment by YonatanKra** [comment]
> You can define what tag the grid uses for rows (and rows use for cells) when you register the components:
> 
> ![image](https://user-images.githubusercontent.com/7649425/211599778-99573e1f-5530-4ebb-bd42-5516edba5ad7.png)
> 
> ie. dataGridRow: "my-custom-row-element"
> 
> https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/data-grid/stories/data-grid.register.ts

Regarding this, I get the following error:
```
Argument of type '{ dataGridRow: string; }' is not assignable to parameter of type 'ElementDefinitionContext'.
      Object literal may only specify known properties, and 'dataGridRow' does not exist in type 'ElementDefinitionContext'.
```
It might work In `js` but `ts` fails for this.

**Comment by scomea** [comment]
> It might work In `js` but `ts` fails for this.

Should work, this has definitely been used with ts.  Can you post a repro?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
