### ISSUE TITLE
rfc: add [node_modules] to [.prettierignore] file

### ISSUE THREAD

**Issue by Ibrahimmaga** [microsoft/fast#6595]
# 💬 RFC

node_modules shouldn't be formatted. Therefore, it should be included in .prettierignore file
## 🔦 Context
![image](https://user-images.githubusercontent.com/14119043/211688674-35295d78-b51e-4d6e-b0a7-506a22b243de.png)

**Comment by chrisdholt** [comment]
Hey @Ibrahimmaga! While these aren't enumerated in the .prettierignore file, I don't see prettier actually running on these files. Is there a repro for this behavior?

**Comment by chrisdholt** [comment]
Closing this as no repro, feel free to reopen with a consistent repro though.
