### ISSUE TITLE
rfc: move "adaptive" capabilities out of FAST repo

### ISSUE THREAD

**Issue by bheston** [microsoft/fast#6603]
# 💬 RFC

When FAST started a few years ago the landscape was quite different. We were building React components with a forward-looking design system capability we've since dubbed "Adaptive UI".

Now, at the core, FAST's mission is to power standards-based optimized web components. We also offer foundation templates for some of these components as a starting point.

Components built on FAST, whether they use Foundation or not, have unique design requirements and styling needs. Since we've deprecated the `fast-components`, the Adaptive UI work is no longer core to this offering.

## 🔦 Context

"Adaptive UI" currently exists in four places in the FAST repo:
1. `utilities/adaptive-ui`, the core package published in alpha as `@microsoft/adaptive-ui`, which is the evolution of the capabilities from `fast-components` and the Fluent UI web components
2. `tooling/adaptive-ui-explorer`, the latest manifestation of what used to be the "Color explorer", a site for experimenting with changing adaptive values
3. `tooling/fast-figma-plugin-msft`, a Figma plugin that applies Adaptive UI recipes to Figma elements
4. `sites/fast-color-explorer`, the outdated site for experimenting with color recipe setting, built on `fast-components`

A few of the core FAST collaborators have a renewed interest in advancing the adaptive capabilities. Considering the previous decision to deprecate `fast-components`, publishing a final, usable components package would need to be done under another name. If the adaptive components are going to be built outside of this repo, it seems to make sense that all adaptive capabilities should be worked on as a whole together. This will better support the mono-repo structure and allow both repos to move faster without interdependency.

Referencing the list above:
1. would be deprecated, migrated to the new repo, renamed, and subsequently published from there
2. has not been released under FAST, but would also migrate to the new repo and be published as a web site under the new name
3. has also not been released under FAST, and would also migrate and be published under the new name (this will allow for publishing to the Figma community)
4. will go away as it's already been refactored into item 2

The migrated adaptive work will still have the mission of supporting use with FAST-based components. Anyone interested in using or building this technology is invited to join the new community once it's ready.

**Comment by chrisdholt** [comment]
I'm for it - thanks for the write-up @bheston.

**Comment by yinonov** [comment]
to clarify, this has no effect over fast-element & fast-foundation. true?

**Comment by chrisdholt** [comment]
> 

Correct 👍

**Comment by janechu** [comment]
Resolved with #6648.
