### ISSUE TITLE
Unexpected behavior of derived `DesignToken` value with `observable`

### ISSUE THREAD

**Issue by johnpantini** [microsoft/fast#6627]
# 🐛 Bug Report

The CSS change is happening only once when using derived `DesignToken` value with observables.

## 💻 Repro or Code Sample

https://codepen.io/johnpantini/pen/PoBVPop

## 🤔 Expected Behavior

The same code sample with older package versions:
https://codepen.io/johnpantini/pen/JjBxRRN

The square should toggle its color from #000 to #ddd every 2s.

## 😯 Current Behavior

The square just goes black (#000).

## 🌍 Your Environment
* OS & Device: Windows on PC
* Latest Edge, Chrome
* Version: fast-element@2.0.0-beta.20, fast-foundation@3.0.0-alpha.24

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
