### ISSUE TITLE
fix: change event not fired by fast-switch in js-environment-env

### ISSUE THREAD

**Issue by ashinzekene** [microsoft/fast#6633]
# 🐛 Bug Report

Simulating a click or `checked` change does not fire the change event on js-environment-dom for `fast-switch`

## 💻 Repro or Code Sample

[Repro link on codesandbox](https://codesandbox.io/s/festive-yalow-7q6s4y?file=/src/index.test.js)

## 🤔 Expected Behavior

Should fire change event

## 😯 Current Behavior

No event fired

## 🌍 Your Environment

```
"@Microsoft/fast-components": "2.30.6",
"jest": "25.1.0",
"jest-environment-jsdom": "29.4.2"
````

**Comment by chrisdholt** [comment]
@ashinzekene - I noticed that when creating the elements you are doing so with the `fluent` namespace - does this still repro as an issue when you use the `fast-` namespace (`document.createElement("fast-switch")`) instead of `fluent-`?

**Comment by ashinzekene** [comment]
Yes, it still repros. I updated the repro link

**Comment by chrisdholt** [comment]
> Yes, it still repros. I updated the repro link

I'm not up on the latest with Jest so forgive any ignorance, but is it intended that the you're adding an event listener for "change" and then dispatching a click event from the switch? If I add a listener for change it's fired. If I dispatch change its fired. I seem to recollect that `.click()` doesn't simulate clicking the element it just dispatches whatever listener is added to the element (thus, changing to listen for click passes the test using only `click()` or listening to change and dispatching change passes the test).

**Comment by chrisdholt** [comment]
> Thanks, I see firing a change event works. Also, not sure but shouldn't changing the `checked` property also fire the change event?

Again it's been awhile since I've really dug deep with Jest, but this seems like an artifact of needing to mock in this specific testing library rather (given this is jsdom, I'm not sure changing a property will emit the actual event). Given the above, I'm going to close this out since the issue does not repro in any browser or from what I can tell a test runner which runs in a browser.
