### ISSUE TITLE
TypeError when adding a required attribute to a disabled Switch

### ISSUE THREAD

**Issue by brianchristopherbrady** [microsoft/fast#6635]
# 🐛 Bug Report

Setting the `required` attribute to `true` on a `disabled Switch` results in the following error in the console..

`Uncaught TypeError: Failed to execute 'setValidity' on 'ElementInternals': The second argument should not be empty if one or more flags in the first argument are true.`

## 🌍 Your Environment

Chrome 109.0.5414.119 on Mac
Chrome on Windows 11

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
