### ISSUE TITLE
💬 RFC: add onboarding docs geared at newcomers to web components or JS framework devs, to fast.design

### ISSUE THREAD

**Issue by usrrname** [microsoft/fast#6638]
# Context

This request comes about from discussions I’ve had with @rajsite on the steep learning gradient Javascript framework developers who may also be new to web components experience when onboarding to use FAST.

I propose collaborating on a documents to address the following topics with the goal of:

- allowing JS framework developers to become productive sooner when contributing to design systems that use FAST by offering mental models that differentiate web components from the internal logic and way-of-working with Angular and React.
- enable JS devs who are new to web components to comfortably identify differences between web component syntax and leverage FAST features to build components, faster.

The following are topics I suggest adding articles, codeblocks or tutorials for are a result of common questions I've received from onboarding teams of 5-20 at work to contribute components to a design system built with `"@microsoft/fast-element": "2.0.0-beta.18"` and `"@microsoft/fast-foundation": "3.0.0-alpha.22"`

Related Discord threads: [1](https://discord.com/channels/449251231706251264/449251231706251266/1072866563096592446), [2](https://discord.com/channels/449251231706251264/449251231706251266/1073240928015360001), [3](https://discord.com/channels/449251231706251264/449251231706251266/1073243799079366796), [4](https://discord.com/channels/449251231706251264/449251231706251266/1073256532076142633)

Related: #6527 but Rob [asked me to create a RFC](https://discord.com/channels/449251231706251264/449251231706251266/1073256532076142633) to track this.

## Potential Topics

- What are web components and what does FAST have to do with it?
    - What is the role of shadow DOM in web components?
    - How can I use CSS to target elements in Shadow DOM?
    - What the shadow DOM is not.
    - How does rendering of FAST web components differ from rendering in Angular or React?
        - How does the native Shadow DOM differ from Angular's ViewEncapsulation Shadow DOM?
        - How does rendering in React's Virtual DOM differ to that of FAST?
    - How can I mitigate Flash of Unstyled Custom Element (FOUCE) with FAST?
    - Which package should I import to:
        - extend an existing Fast component?
        - build a custom component?
        - Do I _still_ need to use the `@customElement` directive?
        
- How FAST accelerates component development instead of writing vanilla JS web components
    - `@observables` instead of `static getObservedAttributes()`
    - using `@attr` to define (custom) attributes to make them available on the custom element markup level
    - conditional rendering with `when`, `ViewTemplates` and `@observable`
    - the role of named and unnamed slots, the `slotted` directive, and the role of `defaultSlottedContent` property in existing FAST components and `FASTElement`, and how that impacts component architecture
    - the inheritance of web component lifecycle events like `connectedCallback()` in `FASTElement` that require calling `super()` in extended components to leverage inherited class methods.
    - the relationship between FAST type definitions and the HTML Living Standard and W3C spec.
    
- How do event lifecycles in FAST differ from handling events in Angular or React? 

  Example [Stackblitz]( https://stackblitz.com/edit/vitejs-vite-p2v9tm?file=README.md) showing:
    - calling upon `super.<inheritedMethod>()` in a class method
    - event binding on templates and the `@<event>` syntax
    - The JS Proxy object and its role in events, getting and setting of inherited attributes in FAST components like `FASTButton`
    - usage of`$emit` for dispatching custom events within the light DOM.

- How to prepare form field components so that work inside a form element?
   Example [Stackblitz](https://stackblitz.com/edit/vitejs-vite-154zcd?file=README.md) demonstrating preparation of Text Field as a Form Associated Custom Element. Related: #3536 
   To Be Offered:
     - Integrating the Text Field into Angular (14)
     - Integrating the Text Field into React (18)
    
    Other lifecycle topics: 
    - the role of `Updates.enqueue()` to queue the application of changes on re-renders
    
- Configuring FAST components to close or disable the Shadow DOM/ only support Light DOM
    - The implications of disabling or closing the Shadow DOM 
      Example: article and [Stackblitz](https://stackblitz.com/edit/vitejs-vite-h1bj7f?file=README.md) with `fast-foundation` components to prototype these attempts in ["Closing, Cloning, or Disabling the Shadow DOM"](https://dev.to/jenc/closing-cloning-or-disabling-the-shadow-dom-2m00) 

    _Note: I know there is already advice on the doc site, but the above subject came up so much at work in comparison with Stencil with all-or-nothing ideas about implementing components with shadow DOM; I believe we could supply explainers of the implications of “disabling” or “closing” the shadow DOM and offer ways to work with event emitting or scoping styles for shadow DOM instead_

## 💻 Examples

The following typologises existing industry examples of onboarding JS developers to onboard, adopt or migrate frameworks:

**The FAQ style page:**

- [“How Does Stencil Compare to Traditional Frameworks? | Stencil Frequently Asked Questions”](https://stenciljs.com/docs/faq#how-does-stencil-compare-to-traditional-frameworks) StencilJS Docs. 2023
- ["Knowledge Level Assumptions"](https://reactjs.org/docs/hello-world.html#knowledge-level-assumptions), React, 2023.

**The Framework Comparison:**

- [“All the Ways To Build a Web Component”](https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component), [webcomponents.dev](http://webcomponents.dev/) by `<div> riots`,  Feb 17, 2022.
- Marius Bogarts, [“Will Web Components Replace Front end Frameworks?”](https://web-highlights.com/blog/will-web-components-replace-frontend-frameworks-they-are-built-to-solve-different-problems/#:~:text=While%20Web%20Components%20provide%20strong,The%20two%20goals%20are%20complementary.&text=You%20just%20don't%20need%20React%20to%20create%20a%20reusable%20button), Web Highlights, Oct 26, 2022
- Dave Rupert, ["Comparing Web Component Libraries"](https://htmlwithsuperpowers.netlify.app/writing/libraries.html), _HTML with Super Powers_, 2023. 
- Burton Smith. (@break-stuff) ["Custom Forms with Web Components and "ElementInternals""](https://dev.to/stuffbreaker/custom-forms-with-web-components-and-elementinternals-4jaj)

**Conceptual Translations**
Familiar mental models that developers comfortable with non-web-component frameworks can use to ramp up faster:
- Angular.io, ["Angular - Content Projection"](https://angular.io/guide/content-projection), Feb 28 2022
- Ryan Merill @procload, ["Web components and Angular"](https://gist.github.com/procload/5ccc126c6ed93cc14a9908a7b97ee121)
- Sandro Roth, ["Building Component Slots in React"](https://sandroroth.com/blog/react-slots), Oct 31, 2022.

**The tutorial series with code clips:**

- Tebin Raouf (@tebinraouf) , [“Building Web Components 101: Part 1 of 4”](https://dev.to/tebin/building-web-components-101-part-1-5p5), [Dev.to](http://dev.to/). Feb 17, 2022
- Simon MacDonald (@macdonst) , [“Using Fast Components in an Enhance App”](https://dev.to/begin/using-fast-components-in-an-enhance-app-4057), [Dev.to](http://dev.to/), Jan 20, 2023.
- NextJS. [“Building Forms with Next.js”](https://nextjs.org/docs/guides/building-forms), 2023
- Dave Rupert,  ["Styling Light DOM"](https://htmlwithsuperpowers.netlify.app/styling/light-dom.html),  _HTML with Super Powers_ , 2023

**The Table-of-contents for Incremental Code-along Learning**
- Lit. ["Lit.dev Tutorials"](https://lit.dev/tutorials/), 2023.
- [“Developing Components: Code Examples”](https://open-wc.org/guides/developing-components/code-examples/), Open Web Components, 2023.
- [“Migrating from Gatsby | Next.js”](https://nextjs.org/docs/migrating/from-gatsby), 2023.

**Recommended Testing Integrations**
- Playwright setup

**Comment by janechu** [comment]
This is being addressed in the v2 `@microsoft/fast-element` documentation that is soon to be released. Closing the issue for now but please re-open or open a new issue after the launch if you feel the documentation could be more clear.
