### ISSUE TITLE
docs: add missing components

### ISSUE THREAD

**Issue by mrlife** [microsoft/fast#6639]
# 🙋 Documentation Request

Some of the listed component types are not available. In the [component list](https://explore.fast.design/components), some are listed that don't have content. Are these components available in FAST?

Please see the highlighted components in this screenshot:

![Untitled](https://user-images.githubusercontent.com/213164/218779313-7eb3f4fa-f593-4ced-a32f-ec75acdae739.jpg)

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time and `@microsoft/fast-foundation` is being deprecated, refer to #6955.
