### ISSUE TITLE
Label attribute does not exist on `option`

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6651]
According to HTML spec, the `label` attribute for `option` should be reflected in the `selected-value` text instead of the `option` text:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/6459899/221897055-aec13a2a-7952-45a8-a616-9e73f31853e1.png">
(Taken from https://www.w3schools.com/jsref/dom_obj_option.asp)

In addition, the `option.label` returns `value ?? text` which is not as the Spec which returns `label ?? text`.

Is this intentional? I fixed it in our design system. Would you be open to a PR for this?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
