### ISSUE TITLE
fix: input event is not fired in checkbox and radio inputs

### ISSUE THREAD

**Issue by simonxabris** [microsoft/fast#6657]
# 🐛 Bug Report

When you click on a native HTML `checkbox` or `radio` input, they emit an `input` event, when you do it on their FAST equivalents, there is not `input` event, only `change`

## 💻 Repro or Code Sample

You can see on the below link that the HTML elements fire the input event, while the FAST elements do not

https://codesandbox.io/s/goofy-feynman-zrtmps?file=/src/index.ts

## 🤔 Expected Behavior

The FAST element aligns with how the HTML controls behave and emits an `input` event.

## 💁 Possible Solution

Emit the `input` event the same place where the `change` event is emitted.

## 🔦 Context

We built our design system on FAST, and some teams using our components are missing this behaviour, which was present in the previous library they were using.

## 🌍 Your Environment

It happens in every environment as it's not implemented.

I'm happy to contribute the fix if this is not intentional, if it is, could you explain the deviation from the HTML controls please?

**Comment by chrisdholt** [comment]
I think the primary deviation here is that radio and checkbox are not technically inputs, so it probably didn't even come to mind to include both but rather just change. I looked at both events emitted and the signatures are pretty much the same from what I can tell. I think it's reasonable to emit both from both radio and checkbox. If you'd like to open to a PR for that @simonxabris I think we'd welcome it.

**Comment by simonxabris** [comment]
Awesomel, I'll open a PR then.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
