### ISSUE TITLE
fix: `tagFor` returns wrong tag when practicing composite components

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#6659]
# 🐛 Bug Report

when registering same FAST class with multiple prefixes that depend on another FAST class, `tagFor` ignores prefix context returning the 1st registered class reference, even though it's in a different context.

![image](https://user-images.githubusercontent.com/15140652/222922758-82120db8-9f40-4906-b0b4-caeea437af2d.png)

## 💻 Repro or Code Sample

[codesandbox repro](https://codesandbox.io/s/funny-dawn-v4hbtk?file=/src/index.js)

## 🤔 Expected Behavior

I expected `tagFor` to return the closest reference, so, when called in a button template, `<hsbc-button>` it will return `<hsbc-icon>`, `<citi-button>` will return `<citi-icon>` etc'.

## 🔦 Context

This use-case is important when:
- in need of a workaround for scoped elements
- utilizing options to register 2 types of the same class (like 2 different buttons or/with 2 different definitions for its dependency)

**Comment by janechu** [comment]
This should be rectified in v2 of `@microsoft/fast-element`, additionally `tagFor` appears to be a `@microsoft/fast-foundation` utility and unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
