### ISSUE TITLE
Safari: attribute in child element is undefined when declaring it observable

### ISSUE THREAD

**Issue by taxiahou** [microsoft/fast#6671]
Hi, team, 

Recently we found that an element is not rendered on Mac Safari while not repro on Edge. 

The scenario is quite simple. The page element will send API request to initialize the data that will pass to child element.
The issue is that the **data** in _**_child.template.js_**_ is always undefined. 
If we remove the observable directive from **_child.js_**, then it will work.

I want to confirm with team if this "remove" is suggested fix for this issue. 

``` 
// sample code to demo the scenario
// page.js
export class DemoPage extends FASTElement {
  @observable public childData;  // this will be set async
  @observable public loaded = false; // will be true when API finished
  ...
}

// page.template.js
export const DemoPageTemplate = html<DemoPage>`
  ${when(x => x.loaded, html`<div>
      <ChildElement :data=${x => x.childData}><ChildElement>
  </div>`)
 } 
`;

// child.js
export class ChildElementextends FASTElement {
  @observable public data; 
  ...
}

// child.template.js
export const ChildElementTemplate = html<DemoPage>`
 ${when(x => x.data != null), html`<h2>Me</h2>`}
`;

// index.js
export function definePage() {
    FASTElement.define(DemoPage, {
        name: "demo-page",
        template: DemoPageTemplate,
    });
}
```

**Comment by janechu** [comment]
This appears to be a platform issue as observables are not specific to the `@microsoft/fast-element` package, you may want to file an issue with them.
