### ISSUE TITLE
fix: [radio button bug] in [fast.design website]

### ISSUE THREAD

**Issue by harunfr** [microsoft/fast#6687]
# 🐛 Bug Report
Story is here:
I visit https://www.fast.design,
slide page to bottom until I see radio buttons,
I click radio button named "Radio 1" 
Button named "Radio 2" is checked. 

## 🤔 Expected Behavior
"Radio 1" should be checked.

## 😯 Current Behavior
"Radio 2" becomes checked

## 🌍 Your Environment

* OS: MacOS - Ventura 13.2.1
* Browser: Chrome Version 111.0.5563.110 (Official Build) (arm64)

**Comment by janechu** [comment]
The website is undergoing a major rehaul for v2 of `@microsoft/fast-element`. This will no longer be an issue, however if you spot anything wrong after the v2 launch please file an issue!
