### ISSUE TITLE
fix: Content packaging issue in Blazor Nuget package

### ISSUE THREAD

**Issue by matt-goldman** [microsoft/fast#6695]
# 🐛 Bug Report

In a Blazor WASM project, adding the `Microsoft.Fast.Components.FluentUI` Nuget package doesn't work when it's using the ASP.NET Core hosted model (e.g. `dotnet new blazor --hosted`).

As per the docs, add the Nuget package and add the script block to `index.html`, and if you run the Blazor app on its own, it works fine. However, if you run the back end and host the app that way, you get 404 errors for the Nuget package's static content (e.g., the CSS files that should be served out of the `_content` folder).

Confirmed that it works fine when just the WASM app is run, but doesn't work when the WASM app is hosted by the ASP.NET Core project.

As the issue doesn't occur with other component libraries, I suspect there is an issue with the way the static files are packaged.

## 💻 Repro or Code Sample

https://github.com/matt-goldman/FastBlazorHostedBug

## 🤔 Expected Behavior

The Blazor WASM app should run the same way from an ASP.NET Core hosted app as it does as a static web app.

## 😯 Current Behavior

The app doesn't start due to the 404 errors

![image](https://user-images.githubusercontent.com/19944129/228410479-8fde2e5e-06aa-4de0-a6b2-e3af881c0d87.png)
**Figure: 404 errors accessing static content when the Server project is run**

![image](https://user-images.githubusercontent.com/19944129/228410597-fade2f5e-6b17-498d-bfe6-8bdbb87882e9.png)
**Figure: No issues running the Blazor project standalone**

## 🔦 Context

As it stops the app from loading altogether, this is a showstopper for deployment. As a workaround, I can work on the Blazor app and the API separately, but I can't deploy them until this issue is fixed.

## 🌍 Your Environment

* OS & Device: Tested on Windows 11 and macOS (M1)
* Browser Microsoft Edge and Firefox tested

**Comment by chrisdholt** [comment]
Tagging @vnbaaij here for context/insight, etc.

**Comment by vnbaaij** [comment]
I tried to reproduce with a new project created in VS, added the package, went through [project setup](https://www.fluentui-blazor.net/ProjectSetup) and [code setup](https://www.fluentui-blazor.net/CodeSetup) and removed Bootstrap styling to make sure that that was not interfering with anything. Pressing F5 gives me this:
<img width="606" alt="image" src="https://github.com/microsoft/fast/assets/1761079/efae3439-7c95-46d9-beb3-961fd90def56">
I.e. working as expected.

I'm guessing you are using an older version. The latest [docs](https://www.fluentui-blazor.net/) say specifically to **NOT** install a script block.

PS for Blazor specific issues/question, please use the https://github.com/microsoft/fluentui-blazor repository. Thanks!
