### ISSUE TITLE
feat: upgrade to Storybook 8 in `fast-foundation`

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#6698]
# 🙋 Feature Request

Storybook 7 is now available: https://github.com/storybookjs/storybook/releases

We should see if this new major release offers any improvements to the developer experience when working on Foundation components.

**Comment by radium-v** [comment]
So I've got this working with `@storybook/html-vite` but I'm running into issues. Running `storybook dev` works without any issue but `storybook build` doesn't seem to actually initialize any of the components and I'm not sure why. I'm thinking it's an issue with `esbuild` since it doesn't support decorators. Once I get that going, I'll have a PR ready.

As an aside, Vite is pretty great and I think I prefer it to webpack and rollup now.

**Comment by ScottAwesome** [comment]
> So I've got this working with `@storybook/html-vite` but I'm running into issues. Running `storybook dev` works without any issue but `storybook build` doesn't seem to actually initialize any of the components and I'm not sure why. I'm thinking it's an issue with `esbuild` since it doesn't support decorators. Once I get that going, I'll have a PR ready.
> 
> As an aside, Vite is pretty great and I think I prefer it to webpack and rollup now.

You'll need to use  `@rollup/plugin-typescript` or `@rollup/plugin-babel` with [`enforce: pre`](https://vitejs.dev/guide/api-plugin.html#plugin-ordering).

`@rollup/plugin-swc` might work too bet I never tested it. the `pre` allows it to run before esbuild

**Comment by usrrname** [comment]
Perhaps some helpful comments here from @evertpot about exporting and supporting both CJS and ESM https://evertpot.com/universal-commonjs-esm-typescript-packages/ Been referencing this a ton for my own projects

**Comment by radium-v** [comment]
Storybook 8 is now out 😅

**Comment by janechu** [comment]
This appears to be resolved by #6929
