### ISSUE TITLE
fix: button does not work as expected inside a form

### ISSUE THREAD

**Issue by simonxabris** [microsoft/fast#6704]
# 🐛 Bug Report

When `fast-button` is inside a `form` element, navigating to a `type="button"` via the keyboard and hitting `Enter` submits the form and doing the same on a `type="submit"` (either explicit or implicit submit) submits the form `twice`.

## 💻 Repro or Code Sample

You can reproduce it here: https://stackblitz.com/edit/vitejs-vite-86nklr?file=src/main.ts

Open up the console and focus the buttons with the keyboard, hit `Enter` and observe the logs in the consolde.

## 🤔 Expected Behavior

I expected the `fast-button` to behave as a native HTML `button` would inside `form` elements.

## 😯 Current Behavior

Desribed above.

## 💁 Possible Solution

I found the bug in the code, I'll open a PR.

## 🔦 Context

This hurts the keyboard a11y in the forms that we're developing.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I see this was mentioned in a PR, we will be addressing open PRs and merging what we can before we snap an archive branch to preserve the latest state of Foundation, however to bring us up to date I am closing out issues.
