### ISSUE TITLE
[formAssociatedElements]: missing setCustomValidity method

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6706]
Is there a reason why `setCustomValidity` is missing from the form elements interface?
Thanks :)

**Comment by chrisdholt** [comment]
> Is there a reason why `setCustomValidity` is missing from the form elements interface? Thanks :)

setValidity public method: https://github.com/microsoft/fast/blob/3217e47423b03f97f3661fefdad7e27f73949974/packages/web-components/fast-foundation/src/form-associated/form-associated.ts#L564
