### ISSUE TITLE
docs: fix tsconfig.js example on Vite Integration guidance

### ISSUE THREAD

**Issue by andre-gra** [microsoft/fast#6710]
# 🙋 Documentation Request

On [Vite Integration section](https://www.fast.design/docs/integrations/vite) there is the _tsconfig.js_ file example. On last row the `"include": ["src/*/.ts"]` needs to be changed.

## 💁 Possible Solution

Change  `"include": ["src/*/.ts"]` with  `"include": ["src/*.ts"]`

**Comment by yinonov** [comment]
Noticed it! indeed a typo

**Comment by chrisdholt** [comment]
Great catch, marked as a good first issue.

**Comment by andre-gra** [comment]
I'll do a PR as soon as possible. I would like to start contributing to the project!

**Comment by andre-gra** [comment]
I have opened the [PR](https://github.com/microsoft/fast/pull/6720).

**Comment by janechu** [comment]
For the upcoming release of v2 of `@microsoft/fast-element` the docs are undergoing a significant change and this issue should no longer exist. After the launch if you feel there are documentation gaps, please file another issue!
