### ISSUE TITLE
fix: remove keyboard ability to change value for readonly state in fast-number-field

### ISSUE THREAD

**Issue by MaiLeeTR** [microsoft/fast#6712]
# 🐛 Bug Report

## 💻 Repro or Code Sample

1. Go to the [number field demo]( https://explore.fast.design/components/fast-number-field) or in Storybook and set the state to readonly. 
2. Use the tab key to navigate to the input. 
3. When focus is on the input, use the up or down arrow key to increment the value.

## 🤔 Expected Behavior

In readonly state, users shouldn't be able to change the value by using the up/down keys on keyboard.

## 😯 Current Behavior

In readonly state, users are able to change the value by using the up/down keys on keyboard.

* MacOS 
* Chrome
* Version [1.8.0]

**Comment by chrisdholt** [comment]
closed with #6730
