### ISSUE TITLE
fix: allow more than 12 numbers to be entered in fast-number-field

### ISSUE THREAD

**Issue by MaiLeeTR** [microsoft/fast#6713]
# 🐛 Bug Report

Users aren't able to enter more than 12 numbers before the numbers automatically change to zeros. 

## 💻 Repro or Code Sample

1. Go to Number field in Storybook
2. Enter more than 12 numbers

## 🤔 Expected Behavior

Users should be able to enter more than 12 numbers without them turning into zeros.

## 😯 Current Behavior

After entering 12 numbers, the rest of the numbers automatically turn into zeros.

<img width="477" alt="Screen Shot 2023-04-20 at 7 40 32 AM" src="https://user-images.githubusercontent.com/55507048/233370131-89cd8948-78a5-4a6f-a759-9bdcb4fa5ac8.png">

## 🌍 Your Environment

* MacOs
* Chrome
* Version [1.8.0]

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I see this was mentioned in a PR, we will be addressing open PRs and merging what we can before we snap an archive branch to preserve the latest state of Foundation, however to bring us up to date I am closing out issues.
