### ISSUE TITLE
fix: not able to enter decimal values in fast-number-field

### ISSUE THREAD

**Issue by MaiLeeTR** [microsoft/fast#6714]
# 🐛 Bug Report

User is not able to enter a decimal value.

## 💻 Repro or Code Sample

1. Go to Number field in Storybook
2. Set the step value to 0.01
3. Try to enter 5.5

## 🤔 Expected Behavior

User should be able to enter a decimal value similar to the [MDN example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#allowing_decimal_values).

## 😯 Current Behavior

If step value is set to two decimal points, user can only enter whole numbers but can use the controls via mouse or keyboard to increment by two decimal points.

https://user-images.githubusercontent.com/55507048/233647984-cd0345ac-e7d9-46e7-abb3-fc0a94fb1954.mov

## 🌍 Your Environment

* MacOS
* Chrome
* Version 1.8.0

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I see this was mentioned in a PR, we will be addressing open PRs and merging what we can before we snap an archive branch to preserve the latest state of Foundation, however to bring us up to date I am closing out issues.
