### ISSUE TITLE
Using a private property inside an attributeChanged method fails

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6716]
A simple way to reproduce:

```
export class Popup extends FoundationElement {
	@attr({
		mode: 'boolean',
	}) open = false;

	#five = 5;

       openChanged() {
		console.log(this.#five);       	
       }
}
```

Results in the following error:
```
 TypeError: Cannot read private member from an object whose class did not declare it
```

This might be related to the use of `$fastController` as a kind of `proxy`:  `this.$fastController.onAttributeChangedCallback(name, oldValue, newValue);` but I'm not sure.

Is this intended or a bug?

**Comment by nicholasrice** [comment]
This is a timing issue: https://stackblitz.com/edit/typescript-5xfsyu?file=index.ts

The handler gets invoked during construction when `open` is initialized, but `#five` has not been initialized at that point, so it is undefined.

**Comment by YonatanKra** [comment]
Thanks a lot!
I would have never thought the order of declaring the properties had such a meaning :)
In my case I just added `if (oldValue === undefined) return;` in the `openChanged` method, and it worked.
