### ISSUE TITLE
docs: fix fast-react-wrapper outdated usage example

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#6717]
# 🙋 Documentation Request

Fast React wrapper documentation instruct importing an outdated export

https://github.com/microsoft/fast/blob/864303b923a10fd8b1d88444efb05e3f64c9524d/packages/utilities/fast-react-wrapper/README.md?plain=1#L26

while the actual import used in tests is
https://github.com/microsoft/fast/blob/864303b923a10fd8b1d88444efb05e3f64c9524d/packages/utilities/fast-react-wrapper/src/index.spec.tsx#L6

notice the export is now a function and not an object containing the `wrap` function anymore

## 💁 Possible Solution

update the documentation

**Comment by EisenbergEffect** [comment]
This is a difference between v1 and v2. The docs on the site still pertain to v1. I tagged this so that it hopefully gets corrected as part of the v2 docs work.

**Comment by yinonov** [comment]
Navigating through the npm space to [the alpha version](https://www.npmjs.com/package/@microsoft/fast-react-wrapper/v/1.0.0-alpha.24) presents the outdated readme. This can be addressed by publishing the updated doc along with the alpha version

**Comment by usrrname** [comment]
That's how we're using it at work too with latest alphas: ` import { reactWrapper } from './index.js'; `

I should also have mentioned that we do this:

```
import { Button } from './path/to/exported/webcomponents';

const wrap = reactWrapper(React);

const buttonEvents = {
        'click' : 'onClick'
        }
        
export const MyReactButton = wrap(Button, buttonEvents);
```

That final line gets bundled into ESM and becomes importable as a React component.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-react-wrapper` is being deprecated, refer to #6955.
