### ISSUE TITLE
fix: tooltip not shown for disabled button

### ISSUE THREAD

**Issue by vnbaaij** [microsoft/fast#6722]
# 🐛 Bug Report

This is reported in the Blazor library (https://github.com/microsoft/fluentui-blazor/issues/376) but cause lies directly in the Fluent UI web components (and FAST components)

FluentTooltip text is not shown in Chrome when a FluentButton is Disabled. It is shown in Firefox.

## 💻 Repro or Code Sample

Go to https://explore.fast.design/components/fast-tooltip and change the fast-button to be disabled.
## 🤔 Expected Behavior

I'm not sure if the tooltip should be displayed on a disabled element, but I think the behavior should be consistent.

## 😯 Current Behavior

When button state is disabled, tooltip does not appear on Edge/Chrome. It does appear on Firefox

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by chrisdholt** [comment]
We can explore this but the repo being browser specific…it seems like the issue may lay with browsers here. Worth investigating, but noting but I can’t think of what code could be conditionally applied on the FAST side here.

**Comment by chrisdholt** [comment]
@vnbaaij I believe this is an issue with browsers where behavior differs.
