### ISSUE TITLE
fix: FAST.getById crashes when fast element is added to a bundle as a dependency

### ISSUE THREAD

**Issue by yairy** [microsoft/fast#6734]
# 🐛 Bug Report

Fast element breaks when imported.

## 💻 Repro or Code Sample

I'm following the 'Getting Started with VS code webview UI toolkit' located here: https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/docs/getting-started.md

Part of the guide is creating a javascript file with the following import line:

`import { provideVSCodeDesignSystem, vsCodeButton } from '@vscode/webview-ui-toolkit';`

This results is a transpiled script (using esbuild) that starts like this:

```
var $global = function() {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  try {
    return new Function("return this")();
  } catch (_a) {
    return {};
  }
}();
if ($global.trustedTypes === void 0) {
  $global.trustedTypes = { createPolicy: (n, r) => r };
}
var propConfig = {
  configurable: false,
  enumerable: false,
  writable: false
};
if ($global.FAST === void 0) {
  Reflect.defineProperty($global, "FAST", Object.assign({ value: /* @__PURE__ */ Object.create(null) }, propConfig));
}
var FAST = $global.FAST;
if (FAST.getById === void 0) {
```
The line below fails bcause FAST is already defined on the window object (window.hasOwnPropert('FAST') === true), albeit its value is undefined.
`Reflect.defineProperty($global, "FAST", Object.assign({ value: /* @__PURE__ */ Object.create(null) }, propConfig));
`

Which causes the entire script to crash on this line:

`if (FAST.getById === void 0) {`

## 🤔 Expected Behavior

FAST property should not exist on the window object; If it does, we shouldn't crash after trying to redefine it unsuccessfully.

## 😯 Current Behavior

The bundled script, which includes FAST element as a dependency, crashed. 

<img width="474" alt="image" src="https://github.com/microsoft/fast/assets/3206243/6fa0e887-01c4-46da-9b2d-e871b632daa0">

->

## 🔦 Context

I'm trying to use vs code UI toolkit, which imports '@vscode/webview-ui-toolkit', which imports fast-element, which crashes my script altogether.

## 🌍 Your Environment

VS Code Web View

* OS & Device: MacOs Motntery
* Browser: VS Code Webview
* Version 1.78.1

**Comment by Wouterdek** [comment]
I fixed this in my project by changing 
```
<script src="webview.js"></script>
```
to
```
<script type="module" src="webview.js"></script>
```

**Comment by janechu** [comment]
Seems this has been resolved, closing.
