### ISSUE TITLE
fix: `expandCollapseGlyph` and nested tree items in `FASTTreeItem` don't render in Angular

### ISSUE THREAD

**Issue by usrrname** [microsoft/fast#6740]
# 🐛 Bug Report

Summary: 

Despite being present in the shadow DOM, nested tree items fail to display when they are placed in FASTTreeItem in Angular.

## 💻 Repro or Code Sample

https://stackblitz.com/edit/fast-angular-15

This is a [reproduction](https://stackblitz.com/edit/fast-angular-15) of the issue mentioned above where console errors link to code errors in `ChildrenDirective` in FASTTreeItem. 

The first example shows a nested tree item inside a tree view.

The second example shows a tree item with nested tree items.

Console errors:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'fast-fmoaic-304-c')
    at ChildrenDirective.getSource (node-observation.js:[60:22](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/src/templating/node-observation.ts#L81))
    at ChildrenDirective.handleEvent (children.js:[18:36](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/src/templating/children.ts#L100))
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Zone.runGuarded (zone.js:144:47)
    at MutationObserver.<anonymous> (zone.js:128:29)
```

This reproduction uses Angular 15 and the following FAST packages:
```
"@microsoft/fast-element": "2.0.0-beta.23",
"@microsoft/fast-foundation": "3.0.0-alpha.27",
"@microsoft/fast-web-utilities": "6.0.0",
```

## 🤔 Expected Behavior

Nested tree items should display as they do in [Component Explorer FASTTreeView](https://explore.fast.design/components/fast-tree-view) when the expandCollapse glyph is clicked when FASTTreeItem is imported in Angular 14 and 15

## 😯 Current Behavior

On my project at work, I've discovered the following defects after importing a FAST-extended TreeItem and Tree View into Angular 14 and 15 projects:

1. `FASTTreeItem`s that are nested within a tree item's empty slot don't display when component is imported in Angular.
2.  `expandCollapseGlyph` (Chevron) in Tree Item with nested children don't display

<img width="1636" alt="view-error" src="https://github.com/microsoft/fast/assets/6406037/3b2f3640-4c45-46e3-a5d7-003c5719997c">
<img width="1628" alt="treeview" src="https://github.com/microsoft/fast/assets/6406037/cd83d0e6-fe06-4287-a008-2e9c26f97aa6">

<img width="1388" alt="node-observation-error" src="https://github.com/microsoft/fast/assets/6406037/939b43f1-ab2f-430f-9f4b-f91af1169ebe">
<img width="797" alt="children-directive-err" src="https://github.com/microsoft/fast/assets/6406037/be48a338-d7e0-4fe8-887f-b093715d62a5">

## 💁 Possible Solution

I'm currently unable to find a solution as I can't entirely understand the exact order of functions in `node-observation.js` and `children.js`.

I would be happy to contribute a fix if I can learn more about what these directives do!

Edit: Workaround for time being:  [disable `zone.js`]( https://angular.io/guide/zone#noopzone) will allow `expandCollapse` glyph to display when  nested Tree Items are inside `FASTTreeView`

## 🔦 Context

I created an extremely similarly FAST component to TreeItem at work, and is also not displaying its expand-collapse slotted start button, and also uses the `children()` directive to observe changes in nested items. (exact sample console errors)

Besides that my workplace is using TreeItem and Tree view in their design system and have been unable to get the expand collapse glyph to display in Angular. 

## 🌍 Your Environment

* OS & Device: MacOS Ventura 13.3.1, Macbook Pro 2019
* Browser: Chrome Version 113.0.5672.126 (Official Build) (x86_64)

```
"@microsoft/fast-element": "2.0.0-beta.23",
"@microsoft/fast-foundation": "3.0.0-alpha.27",
"@microsoft/fast-web-utilities": "6.0.0",
```

**Comment by usrrname** [comment]
Workaround found for displaying the expandCollapse glyph:

Remove zone.js import.

**Comment by chrisdholt** [comment]
Thanks for this issue and the simple repro @usrrname. @nicholasrice mentioned this end of last week and I believe he has a plan to push a fix in the coming week.

**Comment by nicholasrice** [comment]
Yep, I'll have a PR up shortly.

**Comment by usrrname** [comment]
Omg omg omg thank you so much I've been bashing my head on a brute force solution!!! @nicholasrice

**Comment by usrrname** [comment]
Unfortunately this has recurred in Angular 15 and 16, especially using the `nested` attribute

**Comment by impxd** [comment]
I have found the same issue while working with dynamic generated elements:

https://stackblitz.com/edit/angular-fast-marco-nctc7f?file=src%2Fapp%2Fapp.component.html
