### ISSUE TITLE
fix: Anonymous component names in React Tree View in React Wrapper

### ISSUE THREAD

**Issue by procload** [microsoft/fast#6741]
# 🐛 Bug Report
When web components are wrapped with the React wrapper they do not include a displayName property, which results in the component being displayed as `Anonymous` in the React tree view using the React Developer Tools.

![image](https://github.com/microsoft/fast/assets/49389/9723c65e-550c-4abf-92d0-3180bf96edd7)

## 💻 Repro or Code Sample

This occurs when the FAST component is wrapped using the FAST React Wrapper, such as:
```
const SliderWrapper = reactWrapper(React);
export const Slider = SliderWrapper(FooSlider, {
    name: "foo-slider",
});
SliderDefinition.define(customElements);
```

## 🤔 Expected Behavior

I expect the React Tree view to properly display the component name, not `Anonymous`

## 😯 Current Behavior

The current behavior displays `Anonymous` in the React Tree View

## 💁 Possible Solution

A possible solution would be to set the displayName within the wrapper code:
```
ReactComponent.displayName = `ReactComponent(${getTagName(type, config)})`;
const reactComponent = React.forwardRef((props, ref) => React.createElement(ReactComponent, Object.assign(Object.assign({}, props), { __forwardedRef: ref }), props === null || props === void 0 ? void 0 : props.children));
reactComponent.displayName = `ReactWrapper(${getTagName(type, config)})`;
```
Where `ReactComponent` is the name of the component being wrapped. We could pass in a custom display name when the component is initially wrapped, e.g.
```
export const Slider = SliderWrapper(FooSlider, {
    displayName: "Slider",
    name: "foo-slider",
});
```

## 🌍 Your Environment
React Developer Tools

* OS & Device: MacOS, iOS, Windows, Linux
* Browser Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox

**Comment by miroslavstastny** [comment]
> Where ReactComponent is the name of the component being wrapped. We could pass in a custom display name when the component is initially wrapped, e.g.

In the `Slider` example, I would expect the outer component name to match the `displayName` - `Slider`. For that reason the third line in the proposed solution should set just the `displayName`?

**Comment by procload** [comment]
Based on the above, I took a stab at implementing a fix. But the Typescript casting threw me for a loop and I don't like how I had to recast the `reactComponent`. I tried this out locally and it works.

Here's the PR #6747
