### ISSUE TITLE
fix: Combobox filter not reset in `fast-foundation`

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#6749]
# 🐛 Bug Report

There are a couple of inconsistencies/oddities related to how the filter gets updated during various edits to the `Combobox`. I will enumerate them below:

1. If the `value` property is programmatically set after a user has typed into the `Combobox` (with its `autocomplete` set to some filtering setting like `both`) and set the value, then if a user clicks on the `Combobox` to open the dropdown, it still contains the items the original typed text would filter. So, if there is an option with the text "Mary", and a user types "M" followed by `Enter`, but then the `value` is changed to "foo" programatically, if the user opens the dropdown, it will show "Mary".
2. Again with a `Combobox` having its `autocomplete` set to a filtering mode, if a user, with having text focus in the Combobox, presses the down arrow to select a different value (by pressing `Enter`), if the user then presses the down arrow again, they will get a filtered list. If, however, instead of pressing the down arrow to bring up the dropdown they click on the `Combobox`, they will get an unfiltered list.

## 💻 Repro or Code Sample

This example shows how the filtered dropdown does not match the value that is present in the `Combobox` after bring set programmatically.

[https://typescript-zjqwv2.stackblitz.io](https://typescript-zjqwv2.stackblitz.io)

If you remove the `change` event handler, you can easily see the second issue noted above.

## 🤔 Expected Behavior

This is debatable. I actually want to propose a possible behavior semantic that I think would be a good UX for the `Combobox`, but recognize there could be disagreement with this. The behavior where a filtered `Combobox` still allows a user to open the dropdown after a value has been set to see the whole set of options I think is useful.

What I think would be nice is if the filter was only active _while a user is typing characters into the input area_. The filter would be cleared upon either an `Enter` key press, a focus out, or an item click.

If this behavior is not considered correct/appropriate, then I think the expected behavior is that the filter always match what the current text value is in the input field.

## 😯 Current Behavior

The dropdown filtered list is not based on the current text in the input field.

![image](https://github.com/microsoft/fast/assets/26874831/1a1a4058-aa9f-4ac9-8afa-79efa1772531)

## 💁 Possible Solution

Tighter management of when the `filter` for the `Combobox` gets set.

## 🔦 Context

We have a product using the `Combobox` that needs to set the `value` programmatically, but this results in a strange UX when the user ultimately clicks on the dropdown, and sees unrelated items to the one that's present in the input.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
