### ISSUE TITLE
feat: Please add Sveltekit SSR support

### ISSUE THREAD

**Issue by sudo-sand** [microsoft/fast#6750]
# 🙋 Feature Request

Please add support for Sveltekit SSR.

## 🤔 Expected Behavior

To work correctly in Sveltekit SSR. If I register in +layout.svelte, it flashes and then the components hydrate.

## 😯 Current Behavior

The current solution would be a bit hacky, registering the components in `+layout.svelte` `onMount`.

**Comment by janechu** [comment]
Our SSR solution (still very much in pre-release) should provide enough hooks to work in any library. I think this is more of a documentation problem, and one we will address once we are close to a production release.
