### ISSUE TITLE
[select]: a11y problem with shadow DOM

### ISSUE THREAD

**Issue by YonatanKra** [microsoft/fast#6752]
When running the `select` component in `axe` I get the following error:

`Invalid ARIA attribute value: aria-controls="listbox-0"`

This happens when the component is in `open` state only (as it removes the `aria-controls` when closed).

How to reproduce?

1. Using playwright + axe-playwright
2. In the test use the following code:
```
import { test } from '@playwright/test';
import type { Page } from '@playwright/test';
import {checkA11y, injectAxe} from "axe-playwright";

test('a11y', async ({ page }: { page: Page }) => {
	const template = `
	<div style="height: 500px; width: 500px; display: flex; flex-wrap: nowrap;">
			<fast-select open id="select" aria-label="test">
					<fast-option value="option-1">Option 1</fast-option>
					<fast-option value="option-2">Option 2</fast-option>
			</fast-select>
		</div>
	`;

	await page.addScriptTag({
		url: `https://cdn.jsdelivr.net/npm/@microsoft/fast-components/dist/fast-components.min.js`,
		type: 'module',
	});

	await page.$('body').then(body => body?.evaluate((body, {template}) => {
		body.innerHTML = `<div id="wrapper">${template}</div>`;
	}, {template}));

	await page.$('#wrapper');

	await page.waitForLoadState('networkidle');

	await injectAxe(page);

	await checkA11y(page, '#wrapper', {
		detailedReport: true,
		verbose: true,
		detailedReportOptions: {
			html: true,
		}
	}, true, 'html', {
		outputDir: 'a11y-reports',
		reportFileName: 'accessibility-audit.html'
	});
});
```
3. See that the output file contains:
![image](https://github.com/microsoft/fast/assets/6459899/01b9ff4e-a038-4f7f-8add-30d06b4438de)

This happens because the `aria-controls` is outside the shadow DOM while the controlled `id` is inside. 

This might be related to #5557 as well.

**Comment by chrisdholt** [comment]
I just went through a manual test using AT and this read out the relationship as expected. I understand that the error is being thrown by automated tooling, and I'm happy to leave this open to track, but from what I can tell it actually "works" as expected, even though one ID in reference is within the shadow DOM.

**Comment by YonatanKra** [comment]
Good to know. Thanks.
I asked the ppl at `axe` about it and that was their response:
https://github.com/dequelabs/axe-core/issues/4044
We are counting on FAST to keep us a11y compliant, and the automated tools are our way of checking that.
Having said that, the select is one of the more a11y complex components out there IMO, so one semi-glitch seems fine to me :)

**Comment by chrisdholt** [comment]
I'm aware of the constraints of an IDRef, which is part of the discussions happening around cross root ARIA. They are correct that DOM instances and ID's are isolated and they aren't finding that element. With that said, the pattern works - perhaps that's an artifact of it being in the shadow DOM and having the right markup and roles, etc...worth checking to see if it breaks without it.

I don't think there's any appetite to rewrite the component and encapsulate everything - that brings with it a whole other host of concerns some of which exist on other elements.

**Comment by yinonov** [comment]
Side question, is _selectmenu_ work going to affect the future of the fast select component?

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
