### ISSUE TITLE
feat: Allow non-tab elements in the tabs component tablist

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/fast#6755]
# 🙋 Feature Request

I have the requirement to add headings to groups of tabs e.g. like so. I want to be able to add content to the `tab` slot which is not a `fluent-tab`. In my case I'd like to add a `h2` tag.

![image](https://github.com/microsoft/fast/assets/2270364/975cb780-2aa1-49df-8cb8-ac3b7ad719fc)

## 🤔 Expected Behavior

Any non-`fluent-tab` content should not be treated like a tab.

## 😯 Current Behavior

My `h2` tags are treated like they are tabs and things like `aria-selected` etc. are added to it:

![image](https://github.com/microsoft/fast/assets/2270364/02fe3f41-3df8-4e91-8ae6-b1ed0b6b9eb1)

## 💁 Possible Solution

I cannot use the start and end slots because I also want to add headings in between tabs.

Only look for `fluent-tab` components to apply customize. I currently set `aria-disabled="true"` on my `h2` tag to work around this issue, as this causes the element to be ignored by the `fluent-tabs` component.

**Comment by chrisdholt** [comment]
Closing per the above.
