### ISSUE TITLE
fix: Combobox does not scroll option into view at times in `fast-foundation`

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#6776]
# 🐛 Bug Report

There are situations where while typing into the Combobox the selected item does _not_ scroll into view, when there doesn't seem to be a functional reason why that would be.

Specifically, this seems to be an issue with either the `inline` or `none` autocomplete setting.

## 💻 Repro or Code Sample

[Stackblitz example](https://stackblitz.com/edit/typescript-ursvw7?file=index.html,index.ts)

If you type 'a', you will see the first option become selected. If you continue typing by adding 'b' ('ab' is now in the input), you will see that 'ab' is not scrolled into view, though it is indeed selected which you can see if you scroll down manually. If you instead, from an empty input, typed in 'z', you will see 'zoo' be immediately scrolled into view.

## 🤔 Expected Behavior

Any newly selected item as you type should be scrolled into view.

## 😯 Current Behavior

Newly selected items as you type with either the `inline` or `none` `autocomplete` setting at times are not scrolled into view (see reproducing example above)).

## 💁 Possible Solution

It seems like the Combobox should just call its `focusAndScrollOptionIntoView` method more aggressively. I imagine in the `inputHandler` implementation you could just always call it, or at worst, scope it to if the current input value (`this.control.value`) is not the same as `this.value`.

## 🔦 Context

[https://github.com/ni/nimble/issues/1325](https://github.com/ni/nimble/issues/1325)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
