### ISSUE TITLE
fix: Radio button in your homepage

### ISSUE THREAD

**Issue by tiagocouto126** [microsoft/fast#6787]
What: When I click "Radio 1" the one that gets checked is "Radio 2".
Where: in your homepage,
When: it seems that only in the first click ("radio group"), everytime I access the homepage. If already triggered the select of "Radio 2" then it "does not happen".

Windows 11
Chrome v 114.0.5735.199
Firefox Developer v 116.0b6

**Comment by olaf-k** [comment]
dupe of #6687 and in general of #6735

**Comment by janechu** [comment]
For the launch of v2 of `@microsoft/fast-element` we are completely redoing our homepage and it will not feature radio, closing this to reflect that upcoming change.
