### ISSUE TITLE
fix: fast buttons inside form don't behave correctly

### ISSUE THREAD

**Issue by sm3rta** [microsoft/fast#6790]
# 🐛 Bug Report

1. When a form has two Fast buttons, one `type="button"` and a `type="submit"`, focusing on and pressing Enter on the first button triggers form `onSubmit` and `onClick` handler of the submit button as well. Pressing space or clicking behaves normally.
2. Clicking on the submit button triggers form `onSubmit` before its own `onClick`
3. Pressing enter on the submit button triggers `onClick` and form `onSubmit` twice, this has already been reported in [#6704](https://github.com/microsoft/fast/issues/6704)

## 💻 Repro or Code Sample

[repro](https://stackblitz.com/edit/stackblitz-starters-3tjtuk)
Interestingly, in the repro, the second form that has only one button with `type="button"` doesn't show this weird behavior

## 🤔 Expected Behavior

1. Pressing Enter on a button with `type="button"` should behave like pressing space or clicking on it and shouldn't submit the form
2. The order of function calls should be reversed like native html buttons
3. Pressing Enter on a submit button should submit only once

## 😯 Current Behavior

1. Pressing Enter on the cancel button triggers the submit button onClick and the form submit ![Screenshot_6](https://github.com/microsoft/fast/assets/29488774/2a6c100a-3e9e-4646-926f-88f1aa6cb464)
2. Pressing Enter on the FAST submit button, then Enter on the native html button fired `onClick` and form `onSubmit` in different orders ![Screenshot_8](https://github.com/microsoft/fast/assets/29488774/f52d84ae-7992-4e18-8eea-cdea181ab492)
3. Pressing Enter on the submit button triggers handlers twice ![Screenshot_9](https://github.com/microsoft/fast/assets/29488774/65511e0f-bd9d-4082-abf1-987373a201c4)

## 💁 Possible Solution

The [`FASTButton` class](https://github.com/microsoft/fast/blob/9f6451f7e7c121d76e2ead6f50f77c312a0157f7/packages/web-components/fast-foundation/src/button/button.ts#L26) inherits from `FormAssociatedButton` which inherits from `FormAssociated`
`FormAssociated` has a [`_keypressHandler`](https://github.com/microsoft/fast/blob/9f6451f7e7c121d76e2ead6f50f77c312a0157f7/packages/web-components/fast-foundation/src/form-associated/form-associated.ts#L662) that dictates pressing enter on any element inside the form (including the submit button itself) will trigger a click event on the submit button inside the form
Maybe a solution would be to check if the element is a button and prevent the click event from firing

## 🔦 Context

We're trying to build a form with 2 buttons, one for canceling the form and another for submitting. After investigating, we found the two other issues.

## 🌍 Your Environment

- OS & Device: Windows 10
- Browser: Microsoft Edge Version 115.0.1901.183 (Official build) (64-bit), also tried Firefox 115.0.2 (64-bit)

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
