### ISSUE TITLE
Home page broken on iPhone

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#6791]
When I go to fast.design via my iPhone the page looks ugly and broken.

I've tried both Safari and Chrome

![image](https://github.com/microsoft/fast/assets/42288570/364ce3a3-e65b-45ee-8cfa-9643bb8bb6c9)

![image](https://github.com/microsoft/fast/assets/42288570/3655bfd6-9f3c-44cc-992c-de15c3ebeb85)

**Comment by danimydev** [comment]
Confirm, links also broken. At least design.

![image](https://github.com/microsoft/fast/assets/31113489/e9786149-4541-4d92-a702-bf774fbc9f10)

**Comment by chrisdholt** [comment]
Thanks all - this is likely the result of a bug in Safari which we mitigated, though it seems the site didn’t get deployed. We likely need to get that addressed. On a positive, it looks like Safari fixed the bug on their end, which is promising regardless :).

leaving this open to track getting the site updated.

**Comment by janechu** [comment]
The home page is undergoing a complete re-write for the launch of v2 `@microsoft/fast-element` which may resolve this issue, please feel free to open issues against it after the launch.
