### ISSUE TITLE
Fix: When tabbing into the accordion, the focus is on the second accordion item instead of the first in Mozilla Firefox version 116.0.

### ISSUE THREAD

**Issue by brianchristopherbrady** [microsoft/fast#6792]
## 🐛 Bug Report

When tabbing into the accordion in Firefox version 116.0, the second accordion item is focused first instead of the first accordion item.

## 💻 Repro or Code Sample

Navigate to the page with the accordion.
Use the Tab key to move focus between the accordion items.

## 🤔 Expected Behavior

When tabbing into the accordion, the focus should be on the first accordion item.

## 😯 Current Behavior

When tabbing into the accordion, the second accordion item receives focus instead of the first accordion item.

## 💁 Possible Solution

The issue might be related to the order of focusable elements in the DOM or how Firefox handles keyboard navigation. Further investigation is required to identify the root cause.

## 🔦 Context

This issue affects users who rely on keyboard navigation to access and interact with the accordion. It makes it challenging for them to navigate through the accordion items in the intended order.

## 🌍 Your Environment

OS & Device: Windows 11 on PC
Browser: Mozilla Firefox
Version: 116.0

**Comment by chrisdholt** [comment]
@brianchristopherbrady can you provide a link to for the suggested repro?

**Comment by chrisdholt** [comment]
I tested this across a couple of different instances and I'm not able to repro - though I agree that if the first _could_ be focusable but isn't being focused that would be weird. Given I can't get a repro I'm going to close this for now.
