### ISSUE TITLE
fix: Not tree-shakeable in esbuild

### ISSUE THREAD

**Issue by mohamedmansour** [microsoft/fast#6809]
When using esbuild, we cannot tree shake any component in FAST including FluentUI/web-components, here are the current bundle sizes, comparing it to Lit and LitMaterial for importing just a single `Button`
```
Built www/scripts/lit-element/app.js from webuis/lit-element/app.ts (25.47 KB)
Built www/scripts/fast-element/app.js from webuis/fast-element/app.ts (63.99 KB)
Built www/scripts/react/app.js from webuis/react/app.tsx (981.10 KB)
Built www/scripts/fastv3/app.js from webuis/fastv3/app.ts (798.02 KB)
Built www/scripts/litmaterialv1/app.js from webuis/litmaterialv1/app.ts (67.63 KB)
```

The reasons of this are because is exactly similar to this blog post https://konnorrogers.com/posts/2023/the-shoelace-side-effect-scavenger-hunt/

- There are side effects in decorators, we should probably make a similar plugin for esbuild https://www.npmjs.com/package/vite-plugin-tree-shakable-decorators, the way the plugin works is by rewriting it as a PURE CLASS https://github.com/evanw/esbuild/issues/649#issuecomment-1515466947
  from
  ```
  let Dialog = class Dialog extends FASTElement {
  };
  __decorate([
      Prop({ required: true })
  ], Dialog.prototype, "params", void 0);
  Dialog = __decorate([
      Component
  ], Dialog);
  ```
  to
  ```
  let Dialog =  class Dialog extends FASTElement {
  };
  Dialog = /* @__PURE__ */ ((_) => {
      __decorate([
          Prop({required: true})
      ], _.prototype, "params", void 0);
      return __decorate([
          Component
      ], _);
  })(Dialog);
  ```
- Another side effect is using useDefineForClassFields = false, this basically makes static functions non tree-shakable.  The blog explained it well.
- FAST basically imports directly from `index.ts` everywhere which exports folders, if one folder has a side-effect, it will bring it in making it not tree-shakable. Instead, we should not import from `index.ts` but rather import from the class itself.

Recommendation is to:
- Let's add all the `@microsoft/fast-element` libs to the `exports` path in its packages.json file.
- Let's add all the `@microsoft/fast-foundation` components to the `exports` path in its packages.json file.

Those two above will immediately see improvements in bundle size for esbuild. Similar to how Material Lit does it.

**Comment by KingOfTac** [comment]
Pinging @EisenbergEffect and @chrisdholt for visibility.

This looks similar to what Chris has been looking into around the exports.

**Comment by chrisdholt** [comment]
> Pinging @EisenbergEffect and @chrisdholt for visibility.
> 
> This looks similar to what Chris has been looking into around the exports.

One and the same - Several things to address to support this but it's in progress. We'll start with `fast-element` and move to Foundation. Others can follow...
