### ISSUE TITLE
fix: flipper/horizontal scroll not taking RTL into account

### ISSUE THREAD

**Issue by vnbaaij** [microsoft/fast#6810]
# 🐛 Bug Report

When using a fluent-flipper or fluent-horizontal-scroll in web components 2.5.16, they are not responding to a LTR->RTL change. That is if my assumption is correct that the direction of the arrow should change then,

## 💻 Repro or Code Sample

Go to https://explore.fast.design/components/fast-flipper and select the direction switch on the top of the page. Flipper moves to other side but arrow does not change/mirror.

## 🤔 Expected Behavior

Arrows should mirror when changing direction

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by janechu** [comment]
This appears to be related to another project, Fluent UI or Fluent UI Blazor.

**Comment by vnbaaij** [comment]
No, as said in the repro steps, this can be observed at https://explore.fast.design/components/fast-flipper already. It just trickles through too Fluent UI Web Components

**Comment by chrisdholt** [comment]
If we can fix it in the stable version we may do it just in Fluent. It looks quite involved with some dragons.
