### ISSUE TITLE
fix: fluent-search has a11y issue

### ISSUE THREAD

**Issue by vnbaaij** [microsoft/fast#6813]
The fluent-search component does not have any discernible text for the clear button. See https://github.com/microsoft/fluentui-blazor/issues/621 for more inforation

**Comment by chrisdholt** [comment]
The button should likely have `aria-hidden` set on it given it's not in the tabindex, although it's possible that this should really just be a slot and not bake in the button or glyph. That would be breaking, so the latter is likely the best path forward for vNext, while the archive might be mitigated with aria-hidden...

**Comment by vnbaaij** [comment]
I'll take a stab at adding the aria-hidden in a PR

**Comment by janechu** [comment]
Closing this as it appears to not be related to a PR in FAST.
