### ISSUE TITLE
feat: add functionality for enabling Virtualized Listbox

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fast#6814]
# 🙋 Feature Request

I originally opened an issue for Virtualize Listbox in fluentui-blazor here: https://github.com/microsoft/fluentui-blazor/issues/460#issuecomment-1679057885. 

Virtualization works really well for Data grid with large data sets in fluentui-blazor. Given that Listbox can sometimes contain large data sets I think it would be really good here as well. For fluentui-blazor this could also mean that Search with debounce would only be needed for API calls. 

https://www.fluentui-blazor.net/Search#interactive-with-debounce

Could be an alternative for this fix in fluentui-blazor:

https://github.com/microsoft/fluentui-blazor/issues/389

This could however not be done in fluentui-blazor since “we cannot interject into the rendering of the listbox”. Is it possible to add this functionality?

**Comment by vnbaaij** [comment]
@chrisdholt not sure. If you have a stackblitz with an example of how that would look with Javascript, I can take a look on how/if I can translate it to Blazor

**Comment by chrisdholt** [comment]
> @chrisdholt not sure. If you have a stackblitz with an example of how that would look with Javascript, I can take a look on how/if I can translate it to Blazor

I don't have one but it would be akin to using `repeat()` or `when()` as examples of other directives.

**Comment by vnbaaij** [comment]
No experience with both of those either...

**Comment by Ogglas** [comment]
@chrisdholt @vnbaaij Any way forward on this?

**Comment by vnbaaij** [comment]
Not from my side...

**Comment by codeaphex** [comment]
So, I landed here from the FluentUI Blazor repo and am a bit confused.
I see you are against using hundreds or thousands of items in a ListBox, this maybe somehow understandable, but what is the correct solution to be used for endless feeds like we have in many social or newsfeed apps?
The ListBox seems to be an implementation of https://www.w3.org/WAI/ARIA/apg/patterns/listbox/, what I probably need is an implementation of the feed pattern https://www.w3.org/WAI/ARIA/apg/patterns/feed/.
Example: https://www.w3.org/WAI/ARIA/apg/patterns/feed/examples/feed-display.html
Is there anything you can recommend for this pattern?

fyi: The link in the ListBox docs points to https://www.w3.org/TR/wai-aria-practices-1.2/#Listbox which is outdated.

**Comment by janechu** [comment]
Looks like this issue should be filed with Fluent UI.

**Comment by Ogglas** [comment]
@janechu Not according to [this ](https://github.com/microsoft/fluentui-blazor/issues/460#issuecomment-1679057885) issue comment?
