### ISSUE TITLE
feat: add vertical/horizontal orientation option in menu

### ISSUE THREAD

**Issue by sayers24** [microsoft/fast#6829]
# 🙋 Feature Request

I noticed the menu/menu-item components have keyboard navigation listeners that assumes vertical navigation for a top-level list of items and right-arrow to open sub-menus. I have a case where a menu is laid out in a horizontal fashion. Very similar to the scenario W3C describes where [Web application menus are expected to work like desktop application menus](https://www.w3.org/WAI/tutorials/menus/application-menus/#keyboard-behavior)

## 🤔 Expected Behavior

[W3C app menu spec](https://www.w3.org/WAI/tutorials/menus/application-menus/) - When horizontal layout is specified, left/right arrows nav between top level items, down arrow opens sub menu, up arrow closes sub menu

## 😯 Current Behavior

Vertical layout is assumed where up/down arrows nav between top level menu items, right arrow opens sub menu

## 💁 Possible Solution

Add an orientation option to support pivoted keyboard actions

## 🔦 Context

Context listed above

## 💻 Examples

[fast's vertical menu](https://explore.fast.design/components/fast-menu) (Nested option)

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
