### ISSUE TITLE
fix: Modal Dialog is not working as per MDN

### ISSUE THREAD

**Issue by c0g1t8** [microsoft/fast#6837]
# 🐛 Bug Report

When **modal** parameter is set to true, I would expect that the dialog is not dismissable when clicking on the overlay as per the MDN.  

## 💻 Repro or Code Sample

This can be demontrated by starting story book and selecting _Dialog With Dismiss_. 

## 🤔 Expected Behavior

Dialog to not be dismissable when clicking on the overlay when **modal** is set to true. This is the expected behavior for modal dialogs as per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

> The <dialog> element is exposed by browsers similarly to custom dialogs using the ARIA [role="dialog"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) attribute. <dialog> elements invoked by the showModal() method will have an implicit [aria-modal="true"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal), whereas <dialog> elements invoked by the show() method, or rendered by use of the open attribute or changing the default display of a <dialog> will be exposed as [aria-modal="false"]. When implementing modal dialogs, everything other than the <dialog> and its contents should be rendered [inert](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) using the inert attribute. When using <dialog> along with the HTMLDialogElement.showModal() method, this behavior is provided by the browser.

## 😯 Current Behavior

The behavior is currently reversed for the **modal** setting. The dialog is not dismissable when modal is set to false.

## 💁 Possible Solution

A possible solution is the change the call to _when_ with 

```typescript
            ${when(
                x => x.modal,
                html<T>`
                    <div class="overlay" part="overlay" role="presentation"></div>
                `,
                html<T>`
                    <div
                        class="overlay"
                        part="overlay"
                        role="presentation"
                        @click="${x => x.dismiss()}"
                    ></div>
                `
            )}

```

I can provide a PR. It is texted and appears to be work.

## 🔦 Context

This issue was discovered while working with **fluentui-blazor.net**.  This incorrect behavior is actually called out in https://www.fluentui-blazor.net/Dialog. 

## 🌍 Your Environment

Used in .net 7 Blazor web application.

**Comment by chrisdholt** [comment]
Thanks for the issue here - the overlay specifically is part of the modal and the dismiss event allows for supporting "soft-dismiss", where just as escape closes a modal dialog, a click outside on the overlay (which obfuscates the UI) can close the modal dialog. This is a common pattern for modal dialogs across various component libraries. 

While the event is provided, the dialog itself isn't being closed - the event is simply being raised. I think rather than removing this behavior wholesale, which we can consider with more feedback on this PR, the desired outcome would be to handle this when capturing the event. Is there an issue you're running into when trying to do that?

**Comment by c0g1t8** [comment]
@chrisdholt 

Thanks for the quick response. My reading of the MDN is that everything outside the dialog should be _inert_. The _overlay_ itself is not part of the dialog and thus clicking on it should not dismiss the _modal dialog_, I've also found another reference https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/. This reference supports your point but from my experience is atypical behavior.

One of the things that originally caught my attention was that I got the expected behavior when the modal parameter was set to false which is the complete reverse.  This is the reason I believe this to be a bug.

More feedback is always good  🙂.  I don't have a pressing need for this fix since I have alternative ways of addressing this issue.

**Comment by c0g1t8** [comment]
@chrisdholt 

Preventing the user from accidentally closing the dialog is the reason I don't think it should be dismssable by clicking on the overlay.  The partial obfuscation provided by the overlay is also desirable. I'm currently using a non-modal dialog to achieve this but without the nice visual effect. 

I also checked Bootstrap 5 - https://getbootstrap.com/docs/5.3/components/modal/#fullscreen-modal. They exhibit the same default behavior as currently implemented here. That is, clicking outside of the dialog causes the dialog to close.

In order to prevent this default behavior, _static_ needs to be specified as an option. Taking this route of providing an additional option would make any change non-breaking to existing users.  Hmmmm.... is this a viable option?

**Comment by c0g1t8** [comment]
Closing this issue. Though I believe we need to have an option to make the modal dialog non-dismissable when clicking on the overlay, it does require more thought.

@chrisdholt 🙏
