### ISSUE TITLE
unmatched div tag in menu-item.template.ts

### ISSUE THREAD

**Issue by oldoldman** [microsoft/fast#6840]
Hi guys,
I've double checked that ```</div>``` at this [line](https://github.com/microsoft/fast/blob/6091f89a6a0b8bf3baa4cd4ed2aae1078ba9865b/packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts#L58) has no matching start tag. Many thanks!!!

**Comment by KingOfTac** [comment]
@chrisdholt @bheston could this be addressed as a part of the ongoing template updates or should we get a fix in sooner?

**Comment by kamalrohra** [comment]
Hello, I would like to work on this issue

**Comment by KingOfTac** [comment]
> Hello, I would like to work on this issue

You're more than welcome to take this. I have gone ahead and assigned this to you.

**Comment by rahul0x00** [comment]
@KingOfTac Hi, it seems he's not working on this issue as he's taking so much time for a pretty easy fix. should i work on this?

**Comment by kamalrohra** [comment]
Hey I have made the required changes just creating a pr wasn't well for a couple of days sorry for the delay

**Comment by bheston** [comment]
Agreed we should get this in aside from the larger template update. I've commented on the PR.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I see this was mentioned in a PR, we will be addressing open PRs and merging what we can before we snap an archive branch to preserve the latest state of Foundation, however to bring us up to date I am closing out issues.
