### ISSUE TITLE
fast-textfield internally has fixed control id

### ISSUE THREAD

**Issue by kwemou** [microsoft/fast#6852]
Dear all,
in the fast-textfield component, the input (class="control") has a fixed id named "control".

If I use more that one fast-text-field control in my form, I will have many elements having the id="control".
The id of the control should be somehow projected from the id of the fast-text-field

Best regards
Emeric

**Comment by KingOfTac** [comment]
@kwemou While normally true for HTML documents, this isn't the case here due to Shadow DOM encapsulation.

https://javascript.info/shadow-dom#encapsulation
