### ISSUE TITLE
Component  that support markdown editor similar to github comments

### ISSUE THREAD

**Issue by VijayakumarKothapalle** [microsoft/fast#6858]
we have a requirement where the end user should create the comments in our portal . we are looking for a component that support markdown edit , preview before submitting the comments . Could you please let us know the component that supports Markdown syntax . 

Thanks & Regards,
K. VijayKumar .

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. We are no longer doing new work on components.
