### ISSUE TITLE
fix: FASTBadge in @microsoft/fast-foundation

### ISSUE THREAD

**Issue by DavidVollmers** [microsoft/fast#6860]
# 🐛 Bug Report

There is a huge difference in the badge template of `@microsoft/fast-foundation` version `2.49.3` (https://github.com/microsoft/fast/blob/%40microsoft/fast-foundation_v2.49.3/packages/web-components/fast-foundation/src/badge/badge.template.ts) and the master branch (https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/badge/badge.template.ts).

I want to use the latest and more unopiniated version of the Badge element for my design system. I don't understand what is the current version branch and why `master` is so different to it.

## 🌍 Your Environment

`@microsoft/fast-foundation` version `2.49.3`

**Comment by chrisdholt** [comment]
The current master branch is tracking the vNext implementations which are currently in Alpha (Foundation) and Beta (FAST Element). The stable versions are within `archives/fast-element-1`.

**Comment by DavidVollmers** [comment]
Thank you very much!
