### ISSUE TITLE
fix: [npm reporting this package as deprecated] @ [https://www.npmjs.com/package/@microsoft/fast-components]

### ISSUE THREAD

**Issue by ontoneio** [microsoft/fast#6865]
# 🐛 Bug Report

upon install package reports: `npm WARN deprecated @microsoft/fast-components@2.30.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.`

## 💻 Repro or Code Sample
Run
`npm i @microsoft/fast-components`

## 🤔 Expected Behavior
No deprecated message

## 😯 Current Behavior
Returns: `npm WARN deprecated @microsoft/fast-components@2.30.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.`

<img width="875" alt="image" src="https://github.com/microsoft/fast/assets/24515434/ed09f85b-2638-439b-aa67-10fcb1b4e88a">

## 💁 Possible Solution

Is there something that happened, which caused this package to be deprecated as setting in NPM?

## 🔦 Context

We built a design system based on these dependencies and just got to a first iteration. It's disconcerting if this is already deprecated.

## 🌍 Your Environment

Not relevant in this case.

**Comment by noseratio** [comment]
I'm seeing this too.  Indeed disconcerting.

**Comment by chrisdholt** [comment]
The *fast-components* package, the “styled” controls, was deprecated in (I believe 2022) to avoid confusion of having an alternative design system to Fluent from Microsoft. The foundation package and fast-element all remain supported from this project. When I’m back at my computer I can find the PR with the description which is a bit more robust. We also notified the community through discord.

With that said, out of this effort, an evolution of the fast-components was sprouted. That package/project is Open Source, was started on the initial code from fast-components, is maintained by core contributors to FAST, and includes all the adaptive UI work previously there. @bheston can provide more details on the Adaptive Web Components package.

**Comment by noseratio** [comment]
> The foundation package and fast-element all remain supported from this project. When I’m back at my computer I can find the PR with the description which is a bit more robust. We also notified the community through discord.

Thanks @chrisdholt for your prompt reply, it's been a relief! 😊

**Comment by tomdelahaba** [comment]
> The _fast-components_ package, the “styled” controls, was deprecated in (I believe 2022) to avoid confusion of having an alternative design system to Fluent from Microsoft. The foundation package and fast-element all remain supported from this project. When I’m back at my computer I can find the PR with the description which is a bit more robust. We also notified the community through discord.
> 
> With that said, out of this effort, an evolution of the fast-components was sprouted. That package/project is Open Source, was started on the initial code from fast-components, is maintained by core contributors to FAST, and includes all the adaptive UI work previously there. @bheston can provide more details on the Adaptive Web Components package.

Well I believe then the documentation should be updated:
https://www.fast.design/docs/integrations/react#configuring-packages

It literally says `npm install --save @microsoft/fast-components @microsoft/fast-foundation @microsoft/fast-element @microsoft/fast-react-wrapper` but the `@microsoft/fast-components` are deprecated... I am not quite sure now, if `fast-element` resolves some of the issues that were in there with the `fast-components` (eslint related issues) or not. Another thing, I saw "somewhere" in the doc mention about the `fast-elements`, but right now cannot find that again... But, everywhere in the doc its populated with `fast-element`... I believe, this is a "breaking change" that should be addressed in the documentation but its not...

**Comment by janechu** [comment]
Documentation is being updated for the launch of `@microsoft/fast-element` v2.
