### ISSUE TITLE
FIX: steps ignore exponential in fast-number-field

### ISSUE THREAD

**Issue by rizwan3d** [microsoft/fast#6869]
# 🐛 Bug Report

The <fast-number-field> element allows the 'e' character to be entered, but when the user presses the step button, the 'e' gets removed from the input.

## 💻 Repro or Code Sample

1. Go to https://explore.fast.design/components/fast-number-field
2. Click the number field
3. type 1e10
4. press ^ button.

## 🤔 Expected Behavior

manage step action with by keeping e as a part of input.

## 😯 Current Behavior

The exponential part gets removed.

## 💁 Possible Solution

If your input value is in the form of mantissa * 10^exponent (11e11), pressing the step-up button could increment the exponent, making the number larger, and vice versa for the step-down button.

## 🌍 Your Environment

OS & Device: Windows 11, PC

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I see this was mentioned in a PR, we will be addressing open PRs and merging what we can before we snap an archive branch to preserve the latest state of Foundation, however to bring us up to date I am closing out issues.
