### ISSUE TITLE
fix: Anchor does not behave like native when in contenteditable element

### ISSUE THREAD

**Issue by m-akinc** [microsoft/fast#6870]
# 🐛 Bug Report

When a native anchor is inside a element (or has an ancestor) with the `contenteditable` attribute, it is not clickable or focusable, and it does not show a URL preview when hovered with the mouse. The FAST anchor does not behave this way.

## 💻 Repro or Code Sample

https://stackblitz.com/edit/typescript-hdeikv

## 🤔 Expected Behavior

FAST anchor should not be clickable, focusable, or show URL preview on hover.

## 😯 Current Behavior

FAST anchor behaves the same way whether it is in a `contenteditable` element or not.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
