### ISSUE TITLE
fix: code duplication between text-field and search components

### ISSUE THREAD

**Issue by olaf-k** [microsoft/fast#6871]
# 🐛 Bug Report

Not that much of a bug really but I noticed the search text input had a dedicated `search` component in fast-foundation, while other variants of the input (default text, tel, password and so on) were handled in `text-field`.
A large part of the functional code seem duplicated as a result.

## 🤔 Expected Behavior

I would expect the text-field to provide a search variant so as to keep the code consistent in one place.
I understand this would be a breaking change (the search component would have to be deprecated) and I may have overlooked a significant difference that actually justifies having two separate entities, yell at me if that's the case 😁

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
