### ISSUE TITLE
fix: invalid radiogroup value when selected radio removed from DOM

### ISSUE THREAD

**Issue by olaf-k** [microsoft/fast#6874]
# 🐛 Bug Report

Pretty much as it says on the tin 😁

## 💻 Repro or Code Sample

Can be reproduced on https://explore.fast.design/components/fast-radio-group if you update the code snippet to add different values for each radio, or using the fast-foundation storybook:
<img width="910" alt="image" src="https://github.com/microsoft/fast/assets/1153034/8fbb79c5-d107-4514-a605-bf336380a5dc">
→ In dev tools, the radiogroup's value is `undefined` as it should since nothing has been selected.
<img width="145" alt="image" src="https://github.com/microsoft/fast/assets/1153034/a9a5e0c2-905c-46f2-966f-be8d5004bff4">
Select any radio button, say Grapefruit.
<img width="910" alt="image" src="https://github.com/microsoft/fast/assets/1153034/3980354e-4a7d-4ae8-ba03-667b101c5f08">
→ The radiogroup's value is `grapefruit` as it should.
<img width="145" alt="image" src="https://github.com/microsoft/fast/assets/1153034/f7dbfa6e-ef0e-412f-b2f2-4867b49ee964">
Now remove the selected fast-radio from the DOM.
<img width="910" alt="image" src="https://github.com/microsoft/fast/assets/1153034/299e879f-48f4-4596-9058-506dc0648c13">
→ The radiogroup's value remains `grapefruit` while no radio is selected.
<img width="145" alt="image" src="https://github.com/microsoft/fast/assets/1153034/7ace897c-00c3-4888-8910-d2feaab3d843">

## 🤔 Expected Behavior

The radiogroup's value should be set to `undefined`.

## 💁 Possible Solution

Fix `setupRadioButtons()` to account for the case where `this.value` is set but does not match any of the radios'.

**Comment by yinonov** [comment]
A good feasible solution here could be making the value member a getter. Same as form data

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
