### ISSUE TITLE
feat: add close watcher where supported in place of escape key handlers

### ISSUE THREAD

**Issue by lukewarlow** [microsoft/fast#6878]
# 🙋 Feature Request

Use the new CloseWatcher API [1][2] (where supported) instead of an escape keydown event listener. This means you can dismiss these components using Android back gestures/button among other close signals.

[1] https://html.spec.whatwg.org/multipage/interaction.html#the-closewatcher-interface
[2] https://developer.chrome.com/blog/new-in-chrome-120#close-watcher

## 🤔 Expected Behavior

Android back gesture should close an open modal dialog along with a few other elements that close with eacape key.

## 😯 Current Behavior

Only escape key closes them.

## 💁 Possible Solution

The close watcher api mentioned above is the perfect candidate

## 💻 Examples

https://close-watcher-demo.glitch.me/

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. I see this was mentioned in a PR, we will be addressing open PRs and merging what we can before we snap an archive branch to preserve the latest state of Foundation, however to bring us up to date I am closing out issues.
