### ISSUE TITLE
feat: Combobox should allow diacritic-insensitive filtering

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#6887]
# 🙋 Feature Request

Many languages use diacritics (i.e. the glyphs seen on letters like "ü", "ó", "ô", etc...) in their spelling , which is often presented in components like selectors. Allowing filtering to find words that use diacritics easily can be extremely useful, and further, not having it can be of great hindrance. Consider the case where a selector is displaying airports, where one of them is represented in the selector as "Zürich Airport". Currently, if a user types in "Zu", in the `Combobox` (with `autocomplete` set to some filter mode), the user will not find "Zürich Airport".

## 🤔 Expected Behavior

The `Combobox` will find options that have diacritics in their text when the input text does _not_ contain diacritics.

## 😯 Current Behavior

The `Combobox` fails to find options when filtering when the input text doesn't match the option text precisely (see Feature Request section for the example).

## 💁 Possible Solution

[This blog](https://claritydev.net/blog/diacritic-insensitive-string-comparison-javascript) details a solution that FAST might be able to leverage for performing diacritic-insensitive filtering.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
