### ISSUE TITLE
fix: Narrator reads out info about newly focused tab twice

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#6891]
## 💻 Repro or Code Sample
Focusing on a new `tab` in the `tabs` component will cause the tab details to be read out twice.

Launch storybook, navigate to tabs samples, turn on narrator, click on a different tab than the currently selected one.  Note that tab details are read out twice. (Win, Narrator, Edge)

Note: only gets read out once in Windows/Chrome.

## 🤔 Expected Behavior

Tab info read out once.

## 😯 Current Behavior
Info read out twice.

## 💁 Possible Solution
I suspect it has to do how we reset some tab attributes on selection.

## 🔦 Context
Bad accessibility UX

**Comment by scomea** [comment]
I've reproed this on the MS outlook online tabs, so it looks like an Edge issue and not a FAST issue.

<img width="225" alt="image" src="https://github.com/microsoft/fast/assets/7649425/69cea636-85bd-4360-ab49-08a8d43a876a">

**Comment by chrisdholt** [comment]
@Scomea given this is likely a 3rd party issue, is there anything we need to continue to track here or can this be closed?

**Comment by scomea** [comment]
closing
