### ISSUE TITLE
feat: add secure algolia search in documentation

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#6895]
# 🙋 Feature Request
Add Secure Algolia Search to Docusaurus, assuming Docusaurus is still the desired solution.

## 🤔 Expected Behavior
Algolia search should be implemented with a secure key.

## 😯 Current Behavior
This [PR](https://discord.com/channels/449251231706251264/928532241812963338/1197243670546624692) was merged to remove a security vulnerability. The current site will continue to function, however, upon site rebuild Agolia will fail to work deeming the documentation in an unsearchable state.

## 💁 Possible Solution
Algolia search must be [implemented](https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/) with a secure API key per Microsoft Security requirements. 

## 🔦 Context
The App ID PG0CVQLQ81 likely should be retained, but, it's unclear who configured this initially. 
The enables searching across all documentation pages

**Comment by huynhicode** [comment]
Hi 👋, that was me!

https://github.com/microsoft/fast/pull/5620
