### ISSUE TITLE
fix: bad example in fast-foundation/src/accordion/README.md

### ISSUE THREAD

**Issue by guimard** [microsoft/fast#6938]
# 🐛 Bug Report

When trying this example given in [fast-foundation/saccordion/README.md](packages/web-components/fast-foundation/src/accordion/README.md) with the current master branch, I got an error.

## 💻 Repro or Code Sample

**Example from doc**
```typescript
import { Accordion, accordionTemplate as template } from "@microsoft/fast-foundation";
import { accordionStyles as styles } from "./my-accordion.styles";

export const myAccordion = Accordion.compose({
    baseName: "accordion",
    template,
    styles,
});
```

## 🤔 Expected Behavior

tsc success.

## 😯 Current Behavior

```
error TS2305: Module '"@microsoft/fast-foundation"' has no exported member 'Accordion'
```

## 🔦 Context

Trying to update jupyter-ui-toolkit

## 🌍 Your Environment

* OS & Device: Linux Debian

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
