### ISSUE TITLE
fix: textarea missing attributes

### ISSUE THREAD

**Issue by olaf-k** [microsoft/fast#6941]
# 🐛 Bug Report

The `<fast-text-area>` lacks some attributes present on the native component.

## 💻 Repro or Code Sample

Missing attributes ([based on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attributes)): `autocapitalize` (nonstandard), `dirname`, `autocomplete` (nonstandard), `autocorrect` (nonstandard) and `wrap`.

## 🤔 Expected Behavior

- `autocapitalize` while nonstandard, might be useful and should be set on the underlying textarea in the template.
- `dirname` doesn't work, but is quite a niche attribute and has an unusual behavior that might be tricky to emulate.
- `autocomplete` is nonstandard, doesn't work in any browser AFAIK and can be safely ignored.
- `autocorrect` while nonstandard, might be useful but is not yet defined (PR stuck [here](https://github.com/whatwg/html/issues/3595)) and can continue to be ignored atm.
- `wrap` should work when set on the underlying textarea in the template but currently doesn't?
<img width="330" alt="image" src="https://github.com/microsoft/fast/assets/1153034/748d54a0-df84-414e-a6dd-cc5d4cbb9ee2">

## 💁 Possible Solution

`autocomplete` is useless and `autocapitalize` is just about updating the component's template, so those are easy ones.
It'd be nice to get `wrap` to work, maybe `autocorrect` too and `dirname` if the implementation is not too complex.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
