### ISSUE TITLE
RFC: Removal of `fast-tagged-templates`

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#6953]
# Removal of `fast-tagged-templates`

## Reason for removal

While useful for developer experience, this package serves a purpose that is not part of the core goals of FAST. We are open to the adoption of the package by other interested parties. Refer to the [core goals in the project re-alignment issue](https://github.com/microsoft/fast/issues/6955).

**Comment by radium-v** [comment]
I cloned this project to a personal repository here: https://github.com/radium-v/fast-vscode-syntax-highlighting

I'll discuss the VS Code Marketplace publishing process with @chrisdholt and make sure that can still happen.
