### ISSUE TITLE
Removal of `@microsoft/fast-web-utilities`

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#6954]
# Removal of `@microsoft/fast-web-utilities`

## Reason for removal

Once the other packages have been removed, this package has limited use as it was primarily for removing duplication.

**Comment by radium-v** [comment]
I'd prefer to see this package get reduced or dissolved over time, since it's used in many places and provides a lot of constants.

**Comment by janechu** [comment]
> I'd prefer to see this package get reduced or dissolved over time, since it's used in many places and provides a lot of constants.

This will probably be one of the last ones we remove due to it being leveraged by other packages, is it being used much outside of this repository?
