### ISSUE TITLE
RFC: FAST Project Re-alignment

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#6955]
# FAST Project Re-alignment

The FAST project currently has a number of stated goals and packages that have grown over the course of development. Many of these packages are either unrelated or only slightly related to the core goals of the FAST project and as such are no longer actively maintained.

These packages may still provide value to the open source community, as such we are opening the conversation to determine if anyone is willing to take on and maintain the packages outside of the FAST project.

## FAST Project Core Goals

The stated goals of FAST are as follows:

- Where the platform has gaps we intend to create solutions to fill those gaps, this primarily concerns the creation of performant rich web experiences.
- If we have created a solution for a platform gap and that gap is filled for all modern browsers, we will deprecate and remove that solution.

## List of Packages

The packages that the FAST maintainers has deemed as non-essential to the project are listed below, please follow the links for the individual package issues to provide feedback:

- [`fast-tagged-templates`](https://github.com/microsoft/fast/issues/6953)
- [`@microsoft/fast-benchmarks`](https://github.com/microsoft/fast/issues/6949)
- [`@microsoft/fast-colors`](https://github.com/microsoft/fast/issues/6950)
- [`@microsoft/eslint-config-fast-dna`](https://github.com/microsoft/fast/issues/6948)
- [`@microsoft/fast-react-wrapper`](https://github.com/microsoft/fast/issues/6952)
- [`@microsoft/fast-web-utilities`](https://github.com/microsoft/fast/issues/6954)
- [`@microsoft/fast-foundation`](https://github.com/microsoft/fast/issues/6951)

## Timeline

We will give the community what we consider a reasonable timeframe of 2 weeks to start discussion on maintaining packages, with a flexible end date depending on how conversations resolve.

## Resolution

Once a resolution has been reached for each package, we will deprecate the package and remove the package from the repository.

We will also provide a link in the upcoming documentation update that refers to the package and links to the RFC for that particular package.

## Future

The core focus of the FAST project will be on the `@microsoft/fast-element` package. We will be making changes to the documentation to reflect this re-alignment and we ask the community to be patient with us as we make these changes to the project.

**Comment by scomea** [comment]
FAST SSR stays?  Are there plans to improve/document that one?

**Comment by janechu** [comment]
> FAST SSR stays? Are there plans to improve/document that one?

FAST SSR stays, still in pre-release, it needs some love and we'll have to determine what next steps are. As for documentation, right now it will just be `@microsoft/fast-element` that has documentation, going forward we may have 1 docusaurus site per package. Attempting to have multiple in one doesn't make sense for versioning as the packages version independently.

**Comment by janechu** [comment]
@patrickroelofs I think this has been the struggle of the last couple years with priorities for the project (hence the reason our prerelease has been delayed by a few years), also sorry about the conflicting messages there, I have unpinned the issue but left it open and pinned this one.

You're right that we originally wanted foundation to be an accelerator for teams and considered it a core priority for a long time, and we still believe in the concept and the problems it solves, having the solution be part of this project is not what we believe the answer to be going forward. This is why we are looking for outside contributors to take on the goals of package and build on it, potentially creating multiple projects. We would also love to showcase the work of other projects that build on `@microsoft/fast-element` as well, instead of being the arbiters of everything "FAST".

The `@microsoft/fast-element` package remains an extremely lightweight and performant web component library.

**Comment by Patrickroelofs** [comment]
I understand the idea of making Foundation a community effort, and would gladly pitch in but I have no experience with contributing to open source projects so I would not take a leading role.

I do wonder what the plan is with the Design Tokens system which is defined in Foundation, I find this to be an integral part of FAST and it should probably stay with the team if this is possible and the team agrees.

I also hope the documentation will be improved as currently I find it very difficult to learn everything I need from the documentation and this is where foundation filled the gaps.

**Comment by scomea** [comment]
> I know that @radium-v is interested in making some changes to leverage ElementInternals for native form association 

Where would this be happening?  I'm interested in the latest/greatest in terms of implementing form elements.

**Comment by janechu** [comment]
@r1m it can't be removed if it never was added 🥲. Original intentions aside, we're hopeful that the community will see the value in the underlying architecture that due to the layer of abstraction on top for design systems, was never able to shine. We still get asked "what is the value of `@microsoft/fast-element`" regularly, which I don't intend to address anymore as the updated documentation will showcase the value in a thorough manner.

If someone wants to create a CLI as part of tooling around developer experience, we welcome the effort, and should it become something we would recommend to the community it will become part of our showcase.

**Comment by ontoneio** [comment]
It's hard to read that you all want to abandon `@microsoft/fast-foundation` when people are still actively using it. We chose fast-foundation specifically because of it's proposal of being able to maintain a design system on top of standard component API and ability to integrate tokens, which fit our use case perfectly. It definitely lacks documentation and some of the use cases are bit confusing at times, but I agree with whoever said above that this was one of the biggest value propositions of the FAST eco-system. I hope to see what migrating if at all to the new FAST versions will look like.

**Comment by macel94** [comment]
#6881 should not be closed as it was never solved, or did I miss something?

**Comment by janechu** [comment]
> #6881 should not be closed as it was never solved, or did I miss something?

Yes, we have removed the package this issue was filed against, see previous discussion and description of this issue.
