### ISSUE TITLE
fix: Add title property in web-components/fast-foundation/src/button

### ISSUE THREAD

**Issue by marcoseiza** [microsoft/fast#6956]
# 🐛 Bug Report

The web component button implementation doesn't have a [`title`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) attribute. (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title)

This means that the button doesn't show a tooltip when keyboard focused.

## 💻 Repro or Code Sample

`<fast-button title="test"></fast-button>`
- Hover over the element, observe tooltip
- Keyboard focus the element, observe no tooltip

## 🤔 Expected Behavior

Both hover and keyboard focus should show a tooltip.

## 💁 Possible Solution

Add a title attribute to web-components/fast-foundation/src/button

## 🔦 Context

This is an accessibility concern with the button implementation.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
