### ISSUE TITLE
where is the source code of home page

### ISSUE THREAD

**Issue by chensce** [microsoft/fast#6984]
![image](https://github.com/microsoft/fast/assets/93559562/bb45e29c-a365-41dc-a4aa-c9a23f8d4e25)
I want to view the source code of home page,but I can not find it in the repo.

**Comment by DavidVollmers** [comment]
Should be here: https://github.com/microsoft/fast/tree/master/sites/website

**Comment by janechu** [comment]
This is currently being re-written and we haven't deployed since we are in the middle of re-aligning the project, see #6955 and #6971.
