### ISSUE TITLE
fix: using string interpolation to define element tag name

### ISSUE THREAD

**Issue by DavidVollmers** [microsoft/fast#7019]
# 🐛 Bug Report

It seems one cannot use string interpolation in `html` templates to set the name of an element.

## 💻 Repro or Code Sample

```ts
export const template = (prefix: string) => html`
  <${prefix}-button>
  </${prefix}-button>
`;
```

## 🤔 Expected Behavior

The above template should render to something like that (prefix = xxx):

```html
<xxx-button>
</xxx-button>
```

## 😯 Current Behavior

The following is rendered instead:

```html
<fast-wuxaqt{fast-wuxaqt-1601}fast-wuxaqt-button>
</fast-wuxaqt{fast-wuxaqt-1601}fast-wuxaqt-button>
```

## 🔦 Context

Our Design System needs to be able to have a custom prefix for its components. So when a component is using other components in its template, this prefix needs to be passed along and rendered correctly.

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Microsoft Edge
* Version fast-element@2.0.0-beta.26

**Comment by KingOfTac** [comment]
This behavior is by-design as FAST's DOM security considers strings used as HTML markup as potentially unsafe, this includes tag names.

To properly interpolate the string in the tag use `html.partial`.

Example
```ts
export const template = (prefix: string) => {
  const tag = html.partial(`${prefix}-button`);
  return html`
    <${tag}>
    </${tag}>
  `;
}

template('xxx');
```

Alternatively, you could also implement in your codebase the `tagFor` helper from the now deprecated foundation package and pass the component's class to it; It will then resolve the currently defined tag name for the class, prefix and all.

Example with `tagFor`
```ts
export const template = (DepCtor: FASTElement) => {
  const tag = html.partial(tagFor(DepCtor));
  return html`
    <${tag}>
    </${tag}>
  `;
}

template(MyButton);
```

**Comment by DavidVollmers** [comment]
Thank you very much, that was exactly what I was looking for!
