### ISSUE TITLE
Add filtering to building blocks panel on fast development site

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#730]
There should be a the ability to filter building blocks in the `fast-development-site` based on name and status to quickly find components.

User stories:

- Bill is an web developer and he's considering using FAST-DNA components in his project. Bill has a couple components in mind that would help speed up his development process. Bill uses the filter box to distill the long list down to what he is looking for.
- Rochelle is DPM on a project to build a new marketing site for Microsoft. She wants to filter the components down to only those that are release ready. She types "release" and is then on presented with release ready components.

Functional requirements:

- Text input is shown about the component list
- As a user types the list filters down to the relevant results
- User can also type in things like "complete, beta or alpha" for component status.

Technical spec:

- Filtering is calculated when a user starts typing. It will calculate this by filtering based on tags or the name of the component.

**Comment by nicholasrice** [comment]
Sounds good - It looks like this will take a dependency on combo box.

**Comment by Falkicon** [comment]
Probably just a dependency on text field since I don't think you would need the combo functionality.

**Comment by janechu** [comment]
@chrisdholt looks like I missed this, due to the refactor and other moving pieces the development site no longer exists as a package, additionally there is currently no need to filter because of the smaller size number of available components. We may revisit or add a new issue for this if we ever reach that point in the future.
