### ISSUE TITLE
Add props for controlling Horizontal Overflow

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#812]
HorizontalOverflow is currently a 100% uncontrolled component. The prevents an author from manually setting a position if desired, which would be a requirement for a scenario involving reloading stored app state.

To solve for this, HorizontalOverflow should:
1. Expose a `scrollPosition` prop with a type of `number`
2. Expose a `scrollPostion` value on the object passed to any `onScrollChange` set to the new calculated scroll position.

**Comment by chrisdholt** [comment]
@nicholasrice I think this is a really valuable feature add and would propose moving this from a feature request to a task and moving to the backlog.

**Comment by chrisdholt** [comment]
closed with #3517
