### ISSUE TITLE
Test the dependencies on distributed packages

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#934]
Create a test project that imports all exports from a package and tries to compile, this will make sure all dependencies are accounted for.

Check for peerDependencies as well, suggested implementation is to capture stdout of the initial npm install and finding all required peer dependencies and subsequently installing them.

**Comment by awentzel** [comment]
This might be something we can implement on one of the new projects in a isolated manner and if that works more easily implement here.

**Comment by chrisdholt** [comment]
I'm going to close this issue as stale. Given the state of the latest stable versions of NPM which by default notify or simply install peer deps and the fact that the SSR package is currently the only one w/ peer deps, I think this can be closed for now.
