### ISSUE TITLE
Create a navigational UI from a data location

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#967]
Issue: Currently the only navigation for editing a component is via the form generator breadcrumbs and section links.
Goal: A new component should be created which can generate navigational UI.

Details to follow.

**Comment by chrisdholt** [comment]
@janechu is this related to your most recent PR?

**Comment by janechu** [comment]
Closing as this work was completed with the addition of the `Navigation` component in `@microsoft/fast-tooling-react`
